In [1]:
pwd

'C:\\Users\\bayo'

In [4]:
import pandas as pd

In [5]:
import pandas as pd

Bee = pd.read_csv("Mall_Customers.csv")

In [9]:
buz = pd.DataFrame(Bee)

In [14]:
buz['Age']

0      False
1      False
2      False
3      False
4      False
       ...
195    False
196     True
197    False
198    False
199    False
Name: Age, Length: 200, dtype: bool

In [5]:
print(Bee)

     CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [6]:
Bee.describe()

       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

In [7]:
Bee_xlsx = pd.read_excel("Dominoh.xlsx")

In [19]:
print(Bee_xlsx. head(5))

   S/N       Date   Branch    Pizza Sold  Price  Quantity  Sales      Time
0    1 2015-12-11   Ibadan       Meatzaa   2000         5  10000  08:00:01
1    2 2015-12-14    Ikoyi  Extravaganza   2000         4   8000  08:00:02
2    3 2015-12-04    Lekki   BBQ Chicken   4000         5  20000  08:00:04
3    4 2015-12-14    Ikoyi  Extravaganza   2000         1   2000  08:00:07
4    5 2015-12-07  Gbagada       Meatzaa   2000         4   8000  08:00:08

In [21]:
print(Bee_xlsx.tail(5))

       S/N       Date    Branch      Pizza Sold  Price  Quantity  Sales  \
4995  4996 2015-12-13     Lekki       Margarita   4000         1   4000
4996  4997 2015-12-07  Surulere       Beef Suya   3000         5  15000
4997  4998 2015-12-07     Ikoyi  Pepperoni Suya   3000         4  12000
4998  4999 2015-12-08   Gbagada        Italiano   3000         1   3000
4999  5000 2015-12-10     Ikoyi       Beef Suya   3000         5  15000

          Time
4995  09:42:28
4996  09:42:31
4997  09:42:32
4998  09:42:32
4999  09:42:33

In [28]:
print(Bee.columns)

Index(['CustomerID', 'Genre', 'Age', 'Annual Income (k$)',
       'Spending Score (1-100)'],
      dtype='object')

In [34]:
print(Bee[['Age', 'Genre','CustomerID']])

     Age   Genre  CustomerID
0     19    Male           1
1     21    Male           2
2     20  Female           3
3     23  Female           4
4     31  Female           5
..   ...     ...         ...
195   35  Female         196
196   45  Female         197
197   32    Male         198
198   32    Male         199
199   30    Male         200

[200 rows x 3 columns]

In [66]:
print(Bee.iloc[1:4])

   CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77

In [15]:
Bee_xlsx.loc[Bee_xlsx['Branch'] == "Lekki"]

       S/N       Date Branch      Pizza Sold  Price  Quantity  Sales      Time
2        3 2015-12-04  Lekki     BBQ Chicken   4000         5  20000  08:00:04
10      11 2015-12-12  Lekki  Chicken Legend   2000         5  10000  08:00:26
15      16 2015-12-07  Lekki       Beef Suya   3000         5  15000  08:00:34
17      18 2015-12-14  Lekki      Hot Veggie   4000         5  20000  08:00:35
20      21 2015-12-06  Lekki       Margarita   4000         3  12000  08:00:37
...    ...        ...    ...             ...    ...       ...    ...       ...
4985  4986 2015-12-13  Lekki     BBQ Chicken   4000         4  16000  09:42:13
4986  4987 2015-12-09  Lekki        Italiano   3000         2   6000  09:42:14
4992  4993 2015-12-10  Lekki     BBQ Chicken   4000         4  16000  09:42:26
4994  4995 2015-12-04  Lekki    Chicken Suya   4000         4  16000  09:42:28
4995  4996 2015-12-13  Lekki       Margarita   4000         1   4000  09:42:28

[968 rows x 8 columns]

In [14]:
Bee_xlsx.loc[Bee_xlsx['Price'] == '4000']

Empty DataFrame
Columns: [S/N, Date, Branch, Pizza Sold, Price, Quantity, Sales, Time]
Index: []

In [71]:
Bee_xlsx.describe()

               S/N        Price     Quantity         Sales
count  5000.000000  5000.000000  5000.000000   5000.000000
mean   2500.500000  3136.400000     3.010000   9474.000000
std    1443.520003   846.367714     1.412763   5305.558763
min       1.000000  2000.000000     1.000000   2000.000000
25%    1250.750000  2000.000000     2.000000   4000.000000
50%    2500.500000  3000.000000     3.000000   8000.000000
75%    3750.250000  4000.000000     4.000000  12000.000000
max    5000.000000  4000.000000     5.000000  20000.000000

In [78]:
Bee_xlsx.sort_values(['Sales', 'Price'],ascending =[0,1])

,S/N,Date,Branch,Pizza Sold,Price,Quantity,Sales,Time
2,3,2015-12-04,Lekki,BBQ Chicken,4000,5,20000,08:00:04
6,7,2015-12-04,Ibadan,BBQ Philly Steak,4000,5,20000,08:00:20
9,10,2015-12-04,Ibadan,Chicken Suya,4000,5,20000,08:00:25
17,18,2015-12-14,Lekki,Hot Veggie,4000,5,20000,08:00:35
38,39,2015-12-14,Ibadan,Pepperoni Feast,4000,5,20000,08:01:16
...,...,...,...,...,...,...,...,...
4930,4931,2015-12-15,Gbagada,Meatzaa,2000,1,2000,09:41:06
4960,4961,2015-12-07,Ibadan,Chicken Bali,2000,1,2000,09:41:43
4971,4972,2015-12-14,Gbagada,Chicken Bali,2000,1,2000,09:41:59
4975,4976,2015-12-06,Lekki,Meatzaa,2000,1,2000,09:42:06
4978,4979,2015-12-09,Lekki,Chicken Bali,2000,1,2000,09:42:08

In [97]:
Bee_xlsx.head(5)

   S/N       Date   Branch    Pizza Sold  Price  Quantity      Time
0    1 2015-12-11   Ibadan       Meatzaa   2000         5  08:00:01
1    2 2015-12-14    Ikoyi  Extravaganza   2000         4  08:00:02
2    3 2015-12-04    Lekki   BBQ Chicken   4000         5  08:00:04
3    4 2015-12-14    Ikoyi  Extravaganza   2000         1  08:00:07
4    5 2015-12-07  Gbagada       Meatzaa   2000         4  08:00:08

In [95]:
Bee_xlsx.head(5)
Bee_xlsx= Bee_xlsx.drop(columns=['Revenue'])

In [96]:
Bee_xlsx.head(5)

   S/N       Date   Branch    Pizza Sold  Price  Quantity      Time
0    1 2015-12-11   Ibadan       Meatzaa   2000         5  08:00:01
1    2 2015-12-14    Ikoyi  Extravaganza   2000         4  08:00:02
2    3 2015-12-04    Lekki   BBQ Chicken   4000         5  08:00:04
3    4 2015-12-14    Ikoyi  Extravaganza   2000         1  08:00:07
4    5 2015-12-07  Gbagada       Meatzaa   2000         4  08:00:08

In [101]:
Bee_xlsx['Revenue'] = Bee_xlsx['Price'] * Bee_xlsx['Quantity']
Bee_xlsx.head(5)

   S/N       Date   Branch    Pizza Sold  Price  Quantity      Time  Revenue
0    1 2015-12-11   Ibadan       Meatzaa   2000         5  08:00:01    10000
1    2 2015-12-14    Ikoyi  Extravaganza   2000         4  08:00:02     8000
2    3 2015-12-04    Lekki   BBQ Chicken   4000         5  08:00:04    20000
3    4 2015-12-14    Ikoyi  Extravaganza   2000         1  08:00:07     2000
4    5 2015-12-07  Gbagada       Meatzaa   2000         4  08:00:08     8000

In [112]:
by =Bee_xlsx

In [103]:
bx.head(5)

   S/N       Date   Branch    Pizza Sold  Price  Quantity      Time  Revenue
0    1 2015-12-11   Ibadan       Meatzaa   2000         5  08:00:01    10000
1    2 2015-12-14    Ikoyi  Extravaganza   2000         4  08:00:02     8000
2    3 2015-12-04    Lekki   BBQ Chicken   4000         5  08:00:04    20000
3    4 2015-12-14    Ikoyi  Extravaganza   2000         1  08:00:07     2000
4    5 2015-12-07  Gbagada       Meatzaa   2000         4  08:00:08     8000

In [104]:
bx['Snap'] = bx.iloc[:,4:6].sum(1)

In [105]:
bx.head(7)

,S/N,Date,Branch,Pizza Sold,Price,Quantity,Time,Revenue,Snap
0,1,2015-12-11,Ibadan,Meatzaa,2000,5,08:00:01,10000,2005
1,2,2015-12-14,Ikoyi,Extravaganza,2000,4,08:00:02,8000,2004
2,3,2015-12-04,Lekki,BBQ Chicken,4000,5,08:00:04,20000,4005
3,4,2015-12-14,Ikoyi,Extravaganza,2000,1,08:00:07,2000,2001
4,5,2015-12-07,Gbagada,Meatzaa,2000,4,08:00:08,8000,2004
5,6,2015-12-08,Surulere,Hot Veggie,4000,2,08:00:14,8000,4002
6,7,2015-12-04,Ibadan,BBQ Philly Steak,4000,5,08:00:20,20000,4005

In [110]:
cols=list (bx.columns)
bx = bx[cols[0:4] + [cols[-1]]+ cols[4:9]]

In [1]:
bx.drop('Snap')

NameError: name 'bx' is not defined

In [113]:
by.head(6)

,S/N,Date,Branch,Pizza Sold,Price,Quantity,Time,Revenue,Snap
0,1,2015-12-11,Ibadan,Meatzaa,2000,5,08:00:01,10000,2005
1,2,2015-12-14,Ikoyi,Extravaganza,2000,4,08:00:02,8000,2004
2,3,2015-12-04,Lekki,BBQ Chicken,4000,5,08:00:04,20000,4005
3,4,2015-12-14,Ikoyi,Extravaganza,2000,1,08:00:07,2000,2001
4,5,2015-12-07,Gbagada,Meatzaa,2000,4,08:00:08,8000,2004
5,6,2015-12-08,Surulere,Hot Veggie,4000,2,08:00:14,8000,4002

In [124]:
by.to_csv('modified.csv', index = False)
by.to_excel('modofied.xlsx', index = False)
by.to_csv('modified.txt', index = False, sep='\t')

In [132]:
by.loc[(by['Branch'] =='Ikoyi') & (by['Revenue'] == 20000)]

,S/N,Date,Branch,Pizza Sold,Price,Quantity,Time,Revenue,Snap
143,144,2015-12-15,Ikoyi,Pepperoni Feast,4000,5,08:04:35,20000,4005
165,166,2015-12-15,Ikoyi,Margarita,4000,5,08:05:12,20000,4005
214,215,2015-12-11,Ikoyi,BBQ Chicken,4000,5,08:06:46,20000,4005
241,242,2015-12-08,Ikoyi,BBQ Chicken,4000,5,08:07:28,20000,4005
309,310,2015-12-06,Ikoyi,BBQ Philly Steak,4000,5,08:09:47,20000,4005
...,...,...,...,...,...,...,...,...,...
4718,4719,2015-12-10,Ikoyi,Hot Pepperoni Feast,4000,5,09:38:04,20000,4005
4773,4774,2015-12-05,Ikoyi,Hot Pepperoni Feast,4000,5,09:38:44,20000,4005
4804,4805,2015-12-07,Ikoyi,Hot Veggie,4000,5,09:39:11,20000,4005
4814,4815,2015-12-08,Ikoyi,BBQ Chicken,4000,5,09:39:20,20000,4005
4900,4901,2015-12-15,Ikoyi,Margarita,4000,5,09:40:29,20000,4005

In [135]:
by.loc[by['Pizza Sold'].str.contains('Chicken')]

,S/N,Date,Branch,Pizza Sold,Price,Quantity,Time,Revenue,Snap
2,3,2015-12-04,Lekki,BBQ Chicken,4000,5,08:00:04,20000,4005
7,8,2015-12-07,Ikoyi,Chicken Feast,2000,1,08:00:20,2000,2001
9,10,2015-12-04,Ibadan,Chicken Suya,4000,5,08:00:25,20000,4005
10,11,2015-12-12,Lekki,Chicken Legend,2000,5,08:00:26,10000,2005
12,13,2015-12-15,Gbagada,Chicken Suya,4000,2,08:00:29,8000,4002
...,...,...,...,...,...,...,...,...,...
4983,4984,2015-12-11,Surulere,BBQ Chicken,4000,4,09:42:12,16000,4004
4985,4986,2015-12-13,Lekki,BBQ Chicken,4000,4,09:42:13,16000,4004
4988,4989,2015-12-14,Gbagada,BBQ Chicken,4000,3,09:42:15,12000,4003
4992,4993,2015-12-10,Lekki,BBQ Chicken,4000,4,09:42:26,16000,4004
4994,4995,2015-12-04,Lekki,Chicken Suya,4000,4,09:42:28,16000,4004

In [137]:
import re
by.loc[by['Branch'].str.contains('Lekki|Ikoyi', regex = True)]

,S/N,Date,Branch,Pizza Sold,Price,Quantity,Time,Revenue,Snap
1,2,2015-12-14,Ikoyi,Extravaganza,2000,4,08:00:02,8000,2004
2,3,2015-12-04,Lekki,BBQ Chicken,4000,5,08:00:04,20000,4005
3,4,2015-12-14,Ikoyi,Extravaganza,2000,1,08:00:07,2000,2001
7,8,2015-12-07,Ikoyi,Chicken Feast,2000,1,08:00:20,2000,2001
10,11,2015-12-12,Lekki,Chicken Legend,2000,5,08:00:26,10000,2005
...,...,...,...,...,...,...,...,...,...
4993,4994,2015-12-10,Ikoyi,Beef Suya,3000,3,09:42:27,9000,3003
4994,4995,2015-12-04,Lekki,Chicken Suya,4000,4,09:42:28,16000,4004
4995,4996,2015-12-13,Lekki,Margarita,4000,1,09:42:28,4000,4001
4997,4998,2015-12-07,Ikoyi,Pepperoni Suya,3000,4,09:42:32,12000,3004
4999,5000,2015-12-10,Ikoyi,Beef Suya,3000,5,09:42:33,15000,3005

In [139]:
by.loc[by['Pizza Sold'].str.contains('^Chi[a-z]*', regex = True)]

,S/N,Date,Branch,Pizza Sold,Price,Quantity,Time,Revenue,Snap
7,8,2015-12-07,Ikoyi,Chicken Feast,2000,1,08:00:20,2000,2001
9,10,2015-12-04,Ibadan,Chicken Suya,4000,5,08:00:25,20000,4005
10,11,2015-12-12,Lekki,Chicken Legend,2000,5,08:00:26,10000,2005
12,13,2015-12-15,Gbagada,Chicken Suya,4000,2,08:00:29,8000,4002
13,14,2015-12-11,Ibadan,Chicken Feast,2000,5,08:00:33,10000,2005
...,...,...,...,...,...,...,...,...,...
4965,4966,2015-12-03,Gbagada,Chicken Legend,2000,4,09:41:52,8000,2004
4967,4968,2015-12-03,Surulere,Chicken Suya,4000,5,09:41:53,20000,4005
4971,4972,2015-12-14,Gbagada,Chicken Bali,2000,1,09:41:59,2000,2001
4978,4979,2015-12-09,Lekki,Chicken Bali,2000,1,09:42:08,2000,2001
4994,4995,2015-12-04,Lekki,Chicken Suya,4000,4,09:42:28,16000,4004

In [142]:
by.loc[by['Pizza Sold'] == 'Extravaganza', 'Pizza Sold']= 'Yummy'

In [141]:
by

,S/N,Date,Branch,Pizza Sold,Price,Quantity,Time,Revenue,Snap
0,1,2015-12-11,Ibadan,Meatzaa,2000,5,08:00:01,10000,2005
1,2,2015-12-14,Ikoyi,Yummy,2000,4,08:00:02,8000,2004
2,3,2015-12-04,Lekki,BBQ Chicken,4000,5,08:00:04,20000,4005
3,4,2015-12-14,Ikoyi,Yummy,2000,1,08:00:07,2000,2001
4,5,2015-12-07,Gbagada,Meatzaa,2000,4,08:00:08,8000,2004
...,...,...,...,...,...,...,...,...,...
4995,4996,2015-12-13,Lekki,Margarita,4000,1,09:42:28,4000,4001
4996,4997,2015-12-07,Surulere,Beef Suya,3000,5,09:42:31,15000,3005
4997,4998,2015-12-07,Ikoyi,Pepperoni Suya,3000,4,09:42:32,12000,3004
4998,4999,2015-12-08,Gbagada,Italiano,3000,1,09:42:32,3000,3001
4999,5000,2015-12-10,Ikoyi,Beef Suya,3000,5,09:42:33,15000,3005

In [148]:
by.loc[by['Pizza Sold'] == 'Yummy', 'Snap']= 2010

In [149]:
by

,S/N,Date,Branch,Pizza Sold,Price,Quantity,Time,Revenue,Snap
0,1,2015-12-11,Ibadan,Meatzaa,2000,5,08:00:01,10000,2005
1,2,2015-12-14,Ikoyi,Yummy,2000,4,08:00:02,8000,2010
2,3,2015-12-04,Lekki,BBQ Chicken,4000,5,08:00:04,20000,4005
3,4,2015-12-14,Ikoyi,Yummy,2000,1,08:00:07,2000,2010
4,5,2015-12-07,Gbagada,Meatzaa,2000,4,08:00:08,8000,2004
...,...,...,...,...,...,...,...,...,...
4995,4996,2015-12-13,Lekki,Margarita,4000,1,09:42:28,4000,4001
4996,4997,2015-12-07,Surulere,Beef Suya,3000,5,09:42:31,15000,3005
4997,4998,2015-12-07,Ikoyi,Pepperoni Suya,3000,4,09:42:32,12000,3004
4998,4999,2015-12-08,Gbagada,Italiano,3000,1,09:42:32,3000,3001
4999,5000,2015-12-10,Ikoyi,Beef Suya,3000,5,09:42:33,15000,3005

In [162]:
by.loc[by['Revenue'] >=19000, ['Snap']]= 5000

In [163]:
by

,S/N,Date,Branch,Pizza Sold,Price,Quantity,Time,Revenue,Snap
0,1,2015-12-11,Ibadan,Meatzaa,2000,5,08:00:01,10000,3000
1,2,2015-12-14,Ikoyi,Yummy,2000,4,08:00:02,8000,3000
2,3,2015-12-04,Lekki,BBQ Chicken,4000,5,08:00:04,20000,5000
3,4,2015-12-14,Ikoyi,Yummy,2000,1,08:00:07,2000,2010
4,5,2015-12-07,Gbagada,Meatzaa,2000,4,08:00:08,8000,3000
...,...,...,...,...,...,...,...,...,...
4995,4996,2015-12-13,Lekki,Margarita,4000,1,09:42:28,4000,4001
4996,4997,2015-12-07,Surulere,Beef Suya,3000,5,09:42:31,15000,3000
4997,4998,2015-12-07,Ikoyi,Pepperoni Suya,3000,4,09:42:32,12000,3000
4998,4999,2015-12-08,Gbagada,Italiano,3000,1,09:42:32,3000,3001
4999,5000,2015-12-10,Ikoyi,Beef Suya,3000,5,09:42:33,15000,3000

In [167]:
by.groupby(['Branch']).mean().sort_values('Revenue', ascending = False)

                  S/N        Price  Quantity      Revenue         Snap
Branch
Lekki     2455.842975  3153.925620  3.040289  9641.528926  3159.590909
Surulere  2545.069767  3137.420719  3.027484  9483.086681  3132.641649
Ibadan    2495.543086  3121.242485  3.018036  9469.939880  3161.824649
Gbagada   2490.072604  3124.878993  3.013553  9467.570184  3132.150048
Ikoyi     2516.408531  3145.023697  2.955450  9322.274882  3156.957346

In [168]:
by.groupby(['Pizza Sold']).mean().sort_values('Revenue', ascending = False)

                             S/N   Price  Quantity       Revenue         Snap
Pizza Sold
Hot Pepperoni Feast  2464.023739  4000.0  3.183976  12735.905045  3667.813056
BBQ Philly Steak     2347.166113  4000.0  3.162791  12651.162791  3591.508306
Chicken Suya         2472.884244  4000.0  3.073955  12295.819936  3607.893891
Margarita            2511.834507  4000.0  3.066901  12267.605634  3662.183099
Hot Veggie           2480.481481  4000.0  2.932099  11728.395062  3617.493827
Pepperoni Feast      2476.932476  4000.0  2.916399  11665.594855  3614.356913
BBQ Chicken          2426.190323  4000.0  2.903226  11612.903226  3613.135484
Beef Suya            2602.270701  3000.0  3.124204   9372.611465  3000.191083
Veggie Supreme       2499.753799  3000.0  3.066869   9200.607903  3000.164134
Pepperoni Suya       2600.092697  3000.0  3.025281   9075.842697  3000.188202
Italiano             2566.480122  3000.0  3.012232   9036.697248  3000.192661
Yummy                2623.932432  2000.0  3.064189   6128.378378  2615.371622
Chicken Legend       2445.583051  2000.0  2.993220   5986.440678  2600.616949
Chicken Feast        2510.447020  2000.0  2.887417   5774.834437  2576.804636
Chicken Bali         2556.009677  2000.0  2.867742   5735.483871  2571.574194
Meatzaa              2402.815700  2000.0  2.860068   5720.136519  2570.610922

In [171]:
by['count']=1
by.groupby(['Pizza Sold', 'Branch']).count()['count']

Pizza Sold   Branch
BBQ Chicken  Gbagada     66
             Ibadan      56
             Ikoyi       65
             Lekki       59
             Surulere    64
                         ..
Yummy        Gbagada     65
             Ibadan      56
             Ikoyi       58
             Lekki       63
             Surulere    54
Name: count, Length: 80, dtype: int64

In [185]:
print(Bee)

     CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [226]:
for boss in pd.read_csv("Modified.csv", chunksize=5):
    print("CHUNK BOSS")
    print(boss)

CHUNK BOSS
   S/N        Date   Branch    Pizza Sold  Price  Quantity      Time  Revenue  \
0    1  2015-12-11   Ibadan       Meatzaa   2000         5  08:00:01    10000
1    2  2015-12-14    Ikoyi  Extravaganza   2000         4  08:00:02     8000
2    3  2015-12-04    Lekki   BBQ Chicken   4000         5  08:00:04    20000
3    4  2015-12-14    Ikoyi  Extravaganza   2000         1  08:00:07     2000
4    5  2015-12-07  Gbagada       Meatzaa   2000         4  08:00:08     8000

   Snap
0  2005
1  2004
2  4005
3  2001
4  2004
CHUNK BOSS
   S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
5    6  2015-12-08  Surulere        Hot Veggie   4000         2  08:00:14
6    7  2015-12-04    Ibadan  BBQ Philly Steak   4000         5  08:00:20
7    8  2015-12-07     Ikoyi     Chicken Feast   2000         1  08:00:20
8    9  2015-12-07   Gbagada           Meatzaa   2000         3  08:00:22
9   10  2015-12-04    Ibadan      Chicken Suya   4000         5  08:00:25

   Revenue  Snap
5     8000  4002
6    20000  4005
7     2000  2001
8     6000  2003
9    20000  4005
CHUNK BOSS
    S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
10   11  2015-12-12     Lekki    Chicken Legend   2000         5  08:00:26
11   12  2015-12-09   Gbagada  BBQ Philly Steak   4000         4  08:00:27
12   13  2015-12-15   Gbagada      Chicken Suya   4000         2  08:00:29
13   14  2015-12-11    Ibadan     Chicken Feast   2000         5  08:00:33
14   15  2015-12-05  Surulere     Chicken Feast   2000         4  08:00:33

    Revenue  Snap
10    10000  2005
11    16000  4004
12     8000  4002
13    10000  2005
14     8000  2004
CHUNK BOSS
    S/N        Date    Branch     Pizza Sold  Price  Quantity      Time  \
15   16  2015-12-07     Lekki      Beef Suya   3000         5  08:00:34
16   17  2015-12-08   Gbagada  Chicken Feast   2000         5  08:00:35
17   18  2015-12-14     Lekki     Hot Veggie   4000         5  08:00:35
18   19  2015-12-11  Surulere        Meatzaa   2000         5  08:00:35
19   20  2015-12-11    Ibadan        Meatzaa   2000         2  08:00:36

    Revenue  Snap
15    15000  3005
16    10000  2005
17    20000  4005
18    10000  2005
19     4000  2002
CHUNK BOSS
    S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
20   21  2015-12-06     Lekki       Margarita   4000         3  08:00:37
21   22  2015-12-14  Surulere        Italiano   3000         5  08:00:40
22   23  2015-12-14   Gbagada      Hot Veggie   4000         2  08:00:45
23   24  2015-12-08     Ikoyi  Pepperoni Suya   3000         3  08:00:45
24   25  2015-12-09     Lekki  Veggie Supreme   3000         5  08:00:48

    Revenue  Snap
20    12000  4003
21    15000  3005
22     8000  4002
23     9000  3003
24    15000  3005
CHUNK BOSS
    S/N        Date  Branch           Pizza Sold  Price  Quantity      Time  \
25   26  2015-12-04  Ibadan  Hot Pepperoni Feast   4000         3  08:00:49
26   27  2015-12-09   Ikoyi       Chicken Legend   2000         4  08:00:49
27   28  2015-12-03  Ibadan     BBQ Philly Steak   4000         1  08:00:52
28   29  2015-12-14   Ikoyi  Hot Pepperoni Feast   4000         2  08:00:56
29   30  2015-12-06   Lekki         Chicken Bali   2000         4  08:00:56

    Revenue  Snap
25    12000  4003
26     8000  2004
27     4000  4001
28     8000  4002
29     8000  2004
CHUNK BOSS
    S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
30   31  2015-12-03    Lekki   Chicken Feast   2000         3  08:00:57
31   32  2015-12-05    Ikoyi  Veggie Supreme   3000         2  08:00:57
32   33  2015-12-13  Gbagada    Extravaganza   2000         4  08:01:00
33   34  2015-12-13   Ibadan  Pepperoni Suya   3000         4  08:01:01
34   35  2015-12-04  Gbagada  Veggie Supreme   3000         2  08:01:02

    Revenue  Snap
30     6000  2003
31     6000  3002
32     8000  2004
33    12000  3004
34     6000  3002
CHUNK BOSS
    S/N        Date  Branch        Pizza Sold  Price  Quantity      Time  \
35   36  2015-12-08   Ikoyi      Extravaganza   2000         2  08:01:08
36   37  2015-12-11   Lekki          Italiano   3000         2  08:01:14
37   38  2015-12-09   Lekki  BBQ Philly Steak   4000         2  08:01:16
38   39  2015-12-14  Ibadan   Pepperoni Feast   4000         5  08:01:16
39   40  2015-12-05   Lekki      Chicken Bali   2000         4  08:01:17

    Revenue  Snap
35     4000  2002
36     6000  3002
37     8000  4002
38    20000  4005
39     8000  2004
CHUNK BOSS
    S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
40   41  2015-12-05     Lekki    Pepperoni Suya   3000         2  08:01:18
41   42  2015-12-10   Gbagada  BBQ Philly Steak   4000         5  08:01:20
42   43  2015-12-12  Surulere      Chicken Bali   2000         3  08:01:21
43   44  2015-12-11   Gbagada          Italiano   3000         5  08:01:22
44   45  2015-12-10   Gbagada  BBQ Philly Steak   4000         4  08:01:26

    Revenue  Snap
40     6000  3002
41    20000  4005
42     6000  2003
43    15000  3005
44    16000  4004
CHUNK BOSS
    S/N        Date    Branch           Pizza Sold  Price  Quantity      Time  \
45   46  2015-12-08     Lekki  Hot Pepperoni Feast   4000         5  08:01:28
46   47  2015-12-09     Lekki       Chicken Legend   2000         2  08:01:31
47   48  2015-12-07     Lekki         Chicken Bali   2000         2  08:01:32
48   49  2015-12-12     Lekki     BBQ Philly Steak   4000         1  08:01:34
49   50  2015-12-06  Surulere          BBQ Chicken   4000         4  08:01:34

    Revenue  Snap
45    20000  4005
46     4000  2002
47     4000  2002
48     4000  4001
49    16000  4004
CHUNK BOSS
    S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
50   51  2015-12-05    Ikoyi   Pepperoni Feast   4000         4  08:01:35
51   52  2015-12-12  Gbagada  BBQ Philly Steak   4000         1  08:01:36
52   53  2015-12-14   Ibadan  BBQ Philly Steak   4000         4  08:01:36
53   54  2015-12-14   Ibadan    Pepperoni Suya   3000         2  08:01:37
54   55  2015-12-08  Gbagada    Veggie Supreme   3000         5  08:01:37

    Revenue  Snap
50    16000  4004
51     4000  4001
52    16000  4004
53     6000  3002
54    15000  3005
CHUNK BOSS
    S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
55   56  2015-12-03  Surulere      Chicken Suya   4000         5  08:01:39
56   57  2015-12-05  Surulere         Margarita   4000         4  08:01:43
57   58  2015-12-13  Surulere      Chicken Bali   2000         5  08:01:44
58   59  2015-12-09   Gbagada           Meatzaa   2000         5  08:01:44
59   60  2015-12-09  Surulere  BBQ Philly Steak   4000         3  08:01:46

    Revenue  Snap
55    20000  4005
56    16000  4004
57    10000  2005
58    10000  2005
59    12000  4003
CHUNK BOSS
    S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
60   61  2015-12-11    Lekki  Pepperoni Suya   3000         5  08:01:48
61   62  2015-12-06  Gbagada   Chicken Feast   2000         5  08:01:49
62   63  2015-12-11  Gbagada   Chicken Feast   2000         4  08:01:52
63   64  2015-12-05  Gbagada    Chicken Suya   4000         2  08:01:54
64   65  2015-12-14   Ibadan  Chicken Legend   2000         3  08:01:55

    Revenue  Snap
60    15000  3005
61    10000  2005
62     8000  2004
63     8000  4002
64     6000  2003
CHUNK BOSS
    S/N        Date  Branch       Pizza Sold  Price  Quantity      Time  \
65   66  2015-12-15   Ikoyi    Chicken Feast   2000         4  08:01:56
66   67  2015-12-10   Lekki     Chicken Bali   2000         1  08:02:03
67   68  2015-12-08   Ikoyi   Pepperoni Suya   3000         1  08:02:03
68   69  2015-12-14   Lekki  Pepperoni Feast   4000         3  08:02:04
69   70  2015-12-03  Ibadan        Beef Suya   3000         3  08:02:05

    Revenue  Snap
65     8000  2004
66     2000  2001
67     3000  3001
68    12000  4003
69     9000  3003
CHUNK BOSS
    S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
70   71  2015-12-03  Surulere      BBQ Chicken   4000         1  08:02:06
71   72  2015-12-10     Ikoyi  Pepperoni Feast   4000         3  08:02:10
72   73  2015-12-07    Ibadan  Pepperoni Feast   4000         5  08:02:13
73   74  2015-12-08     Ikoyi      BBQ Chicken   4000         2  08:02:13
74   75  2015-12-06   Gbagada     Extravaganza   2000         5  08:02:18

    Revenue  Snap
70     4000  4001
71    12000  4003
72    20000  4005
73     8000  4002

74    10000  2005
CHUNK BOSS
    S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
75   76  2015-12-09     Lekki  Chicken Legend   2000         1  08:02:18
76   77  2015-12-06     Ikoyi  Pepperoni Suya   3000         2  08:02:22
77   78  2015-12-13   Gbagada      Hot Veggie   4000         2  08:02:22
78   79  2015-12-07     Lekki    Extravaganza   2000         3  08:02:30
79   80  2015-12-04  Surulere    Chicken Suya   4000         3  08:02:31

    Revenue  Snap
75     2000  2001
76     6000  3002
77     8000  4002
78     6000  2003
79    12000  4003
CHUNK BOSS
    S/N        Date  Branch        Pizza Sold  Price  Quantity      Time  \
80   81  2015-12-03  Ibadan   Pepperoni Feast   4000         5  08:02:35
81   82  2015-12-12   Ikoyi   Pepperoni Feast   4000         3  08:02:36
82   83  2015-12-04   Lekki       BBQ Chicken   4000         3  08:02:37
83   84  2015-12-08  Ibadan  BBQ Philly Steak   4000         4  08:02:38
84   85  2015-12-05   Lekki        Hot Veggie   4000         5  08:02:38

    Revenue  Snap
80    20000  4005
81    12000  4003
82    12000  4003
83    16000  4004
84    20000  4005
CHUNK BOSS
    S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
85   86  2015-12-13     Lekki      Chicken Bali   2000         1  08:02:42
86   87  2015-12-05    Ibadan         Beef Suya   3000         2  08:02:44
87   88  2015-12-04  Surulere  BBQ Philly Steak   4000         2  08:02:46
88   89  2015-12-07     Ikoyi    Veggie Supreme   3000         4  08:02:47
89   90  2015-12-09  Surulere      Chicken Suya   4000         1  08:02:47

    Revenue  Snap
85     2000  2001
86     6000  3002
87     8000  4002
88    12000  3004
89     4000  4001
CHUNK BOSS
    S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
90   91  2015-12-10   Ibadan       BBQ Chicken   4000         5  08:02:49
91   92  2015-12-07    Ikoyi  BBQ Philly Steak   4000         4  08:02:50
92   93  2015-12-14   Ibadan           Meatzaa   2000         5  08:02:50
93   94  2015-12-05  Gbagada        Hot Veggie   4000         5  08:02:55
94   95  2015-12-11    Ikoyi          Italiano   3000         2  08:03:00

    Revenue  Snap
90    20000  4005
91    16000  4004
92    10000  2005
93    20000  4005
94     6000  3002
CHUNK BOSS
    S/N        Date    Branch           Pizza Sold  Price  Quantity      Time  \
95   96  2015-12-04     Ikoyi     BBQ Philly Steak   4000         3  08:03:01
96   97  2015-12-04  Surulere       Chicken Legend   2000         1  08:03:02
97   98  2015-12-14  Surulere  Hot Pepperoni Feast   4000         2  08:03:05
98   99  2015-12-05   Gbagada  Hot Pepperoni Feast   4000         4  08:03:05
99  100  2015-12-15     Ikoyi     BBQ Philly Steak   4000         4  08:03:09

    Revenue  Snap
95    12000  4003
96     2000  2001
97     8000  4002
98    16000  4004
99    16000  4004
CHUNK BOSS
     S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
100  101  2015-12-14     Lekki  Veggie Supreme   3000         3  08:03:10
101  102  2015-12-04  Surulere    Chicken Suya   4000         5  08:03:10
102  103  2015-12-07     Ikoyi  Pepperoni Suya   3000         5  08:03:15
103  104  2015-12-05  Surulere    Chicken Bali   2000         4  08:03:17
104  105  2015-12-09   Gbagada    Extravaganza   2000         4  08:03:18

     Revenue  Snap
100     9000  3003
101    20000  4005
102    15000  3005
103     8000  2004
104     8000  2004
CHUNK BOSS
     S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
105  106  2015-12-14    Ibadan   Veggie Supreme   3000         5  08:03:22
106  107  2015-12-11   Gbagada  Pepperoni Feast   4000         3  08:03:25
107  108  2015-12-08   Gbagada     Chicken Suya   4000         5  08:03:26
108  109  2015-12-12  Surulere         Italiano   3000         1  08:03:27
109  110  2015-12-05     Ikoyi        Margarita   4000         4  08:03:28

     Revenue  Snap
105    15000  3005
106    12000  4003
107    20000  4005
108     3000  3001
109    16000  4004
CHUNK BOSS
     S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
110  111  2015-12-07  Surulere    Chicken Suya   4000         5  08:03:29
111  112  2015-12-09    Ibadan         Meatzaa   2000         4  08:03:29
112  113  2015-12-03     Lekki  Veggie Supreme   3000         2  08:03:31
113  114  2015-12-05     Ikoyi    Chicken Bali   2000         3  08:03:32
114  115  2015-12-09   Gbagada        Italiano   3000         3  08:03:32

     Revenue  Snap
110    20000  4005
111     8000  2004
112     6000  3002
113     6000  2003
114     9000  3003
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
115  116  2015-12-06     Lekki  Hot Pepperoni Feast   4000         4
116  117  2015-12-10  Surulere       Pepperoni Suya   3000         4
117  118  2015-12-03    Ibadan            Beef Suya   3000         3
118  119  2015-12-07     Lekki       Veggie Supreme   3000         5
119  120  2015-12-13  Surulere             Italiano   3000         4

         Time  Revenue  Snap
115  08:03:32    16000  4004
116  08:03:33    12000  3004
117  08:03:36     9000  3003
118  08:03:39    15000  3005
119  08:03:44    12000  3004
CHUNK BOSS
     S/N        Date   Branch           Pizza Sold  Price  Quantity      Time  \
120  121  2015-12-07   Ibadan  Hot Pepperoni Feast   4000         2  08:03:44
121  122  2015-12-10  Gbagada         Chicken Suya   4000         2  08:03:52
122  123  2015-12-12    Lekki       Veggie Supreme   3000         4  08:03:53
123  124  2015-12-03   Ibadan              Meatzaa   2000         4  08:03:54
124  125  2015-12-03   Ibadan           Hot Veggie   4000         5  08:03:54

     Revenue  Snap
120     8000  4002
121     8000  4002
122    12000  3004
123     8000  2004
124    20000  4005
CHUNK BOSS
     S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
125  126  2015-12-13    Ikoyi  BBQ Philly Steak   4000         4  08:03:54
126  127  2015-12-11    Ikoyi         Beef Suya   3000         1  08:03:57
127  128  2015-12-08    Lekki    Veggie Supreme   3000         3  08:04:00
128  129  2015-12-12    Lekki        Hot Veggie   4000         2  08:04:01
129  130  2015-12-10  Gbagada         Margarita   4000         4  08:04:04

     Revenue  Snap
125    16000  4004
126     3000  3001
127     9000  3003
128     8000  4002
129    16000  4004
CHUNK BOSS
     S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
130  131  2015-12-10    Ibadan    Chicken Legend   2000         1  08:04:07
131  132  2015-12-06   Gbagada    Veggie Supreme   3000         1  08:04:13
132  133  2015-12-11  Surulere        Hot Veggie   4000         5  08:04:14
133  134  2015-12-07     Lekki    Pepperoni Suya   3000         4  08:04:18
134  135  2015-12-15   Gbagada  BBQ Philly Steak   4000         4  08:04:18

     Revenue  Snap
130     2000  2001
131     3000  3001
132    20000  4005
133    12000  3004
134    16000  4004
CHUNK BOSS
     S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
135  136  2015-12-11  Gbagada           Meatzaa   2000         5  08:04:19
136  137  2015-12-03   Ibadan         Beef Suya   3000         2  08:04:20
137  138  2015-12-06   Ibadan   Pepperoni Feast   4000         5  08:04:21
138  139  2015-12-05   Ibadan  BBQ Philly Steak   4000         2  08:04:21
139  140  2015-12-04  Gbagada         Margarita   4000         1  08:04:21

     Revenue  Snap
135    10000  2005
136     6000  3002
137    20000  4005
138     8000  4002
139     4000  4001
CHUNK BOSS
     S/N        Date Branch       Pizza Sold  Price  Quantity      Time  \
140  141  2015-12-15  Lekki     Chicken Suya   4000         2  08:04:24
141  142  2015-12-13  Lekki     Chicken Bali   2000         2  08:04:27
142  143  2015-12-03  Lekki        Margarita   4000         3  08:04:28
143  144  2015-12-15  Ikoyi  Pepperoni Feast   4000         5  08:04:35
144  145  2015-12-11  Ikoyi  Pepperoni Feast   4000         3  08:04:35

     Revenue  Snap
140     8000  4002
141     4000  2002
142    12000  4003
143    20000  4005
144    12000  4003
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
145  146  2015-12-13     Ikoyi            Beef Suya   3000         1
146  147  2015-12-12    Ibadan  Hot Pepperoni Feast   4000         5
147  148  2015-12-08     Ikoyi       Pepperoni Suya   3000         1
148  149  2015-12-15     Lekki         Chicken Suya   4000         3
149  150  2015-12-05  Surulere  Hot Pepperoni Feast   4000         2

         Time  Revenue  Snap
145  08:04:40     3000  3001
146  08:04:41    20000  4005
147  08:04:42     3000  3001
148  08:04:43    12000  4003
149  08:04:44     8000  4002
CHUNK BOSS
     S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
150  151  2015-12-14    Ibadan  Chicken Legend   2000         5  08:04:45
151  152  2015-12-04  Surulere    Extravaganza   2000         5  08:04:50
152  153  2015-12-14   Gbagada       Beef Suya   3000         2  08:04:50
153  154  2015-12-10     Lekki    Extravaganza   2000         4  08:04:53
154  155  2015-12-11     Lekki  Pepperoni Suya   3000         2  08:04:55

     Revenue  Snap
150    10000  2005
151    10000  2005
152     6000  3002
153     8000  2004
154     6000  3002

CHUNK BOSS
     S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
155  156  2015-12-09    Ibadan  BBQ Philly Steak   4000         3  08:04:56
156  157  2015-12-06   Gbagada          Italiano   3000         1  08:04:56
157  158  2015-12-15     Ikoyi      Extravaganza   2000         1  08:05:00
158  159  2015-12-06  Surulere  BBQ Philly Steak   4000         2  08:05:03
159  160  2015-12-13   Gbagada          Italiano   3000         1  08:05:06

     Revenue  Snap
155    12000  4003
156     3000  3001
157     2000  2001
158     8000  4002
159     3000  3001
CHUNK BOSS
     S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
160  161  2015-12-13  Surulere  Chicken Legend   2000         2  08:05:10
161  162  2015-12-07     Ikoyi        Italiano   3000         4  08:05:11
162  163  2015-12-12    Ibadan      Hot Veggie   4000         4  08:05:11
163  164  2015-12-06    Ibadan   Chicken Feast   2000         3  08:05:11
164  165  2015-12-09     Ikoyi         Meatzaa   2000         2  08:05:12

     Revenue  Snap
160     4000  2002
161    12000  3004
162    16000  4004
163     6000  2003
164     4000  2002
CHUNK BOSS
     S/N        Date  Branch           Pizza Sold  Price  Quantity      Time  \
165  166  2015-12-15   Ikoyi            Margarita   4000         5  08:05:12
166  167  2015-12-05   Lekki  Hot Pepperoni Feast   4000         5  08:05:14
167  168  2015-12-12  Ibadan          BBQ Chicken   4000         3  08:05:23
168  169  2015-12-07   Lekki  Hot Pepperoni Feast   4000         5  08:05:23
169  170  2015-12-03   Ikoyi       Chicken Legend   2000         4  08:05:23

     Revenue  Snap
165    20000  4005
166    20000  4005
167    12000  4003
168    20000  4005
169     8000  2004
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
170  171  2015-12-13  Surulere         Chicken Bali   2000         3
171  172  2015-12-07  Surulere         Chicken Suya   4000         5
172  173  2015-12-10  Surulere  Hot Pepperoni Feast   4000         4
173  174  2015-12-14  Surulere  Hot Pepperoni Feast   4000         2
174  175  2015-12-14   Gbagada        Chicken Feast   2000         1

         Time  Revenue  Snap
170  08:05:25     6000  2003
171  08:05:25    20000  4005
172  08:05:25    16000  4004
173  08:05:28     8000  4002
174  08:05:32     2000  2001
CHUNK BOSS
     S/N        Date   Branch           Pizza Sold  Price  Quantity      Time  \
175  176  2015-12-12    Lekki          BBQ Chicken   4000         2  08:05:34
176  177  2015-12-06    Ikoyi         Extravaganza   2000         1  08:05:34
177  178  2015-12-05   Ibadan              Meatzaa   2000         2  08:05:34
178  179  2015-12-15    Ikoyi      Pepperoni Feast   4000         3  08:05:37
179  180  2015-12-09  Gbagada  Hot Pepperoni Feast   4000         1  08:05:38

     Revenue  Snap
175     8000  4002
176     2000  2001
177     4000  2002
178    12000  4003
179     4000  4001
CHUNK BOSS
     S/N        Date    Branch     Pizza Sold  Price  Quantity      Time  \
180  181  2015-12-13    Ibadan    BBQ Chicken   4000         3  08:05:39
181  182  2015-12-12    Ibadan    BBQ Chicken   4000         4  08:05:40
182  183  2015-12-11     Ikoyi  Chicken Feast   2000         3  08:05:41
183  184  2015-12-04  Surulere      Beef Suya   3000         1  08:05:41
184  185  2015-12-10  Surulere   Extravaganza   2000         1  08:05:43

     Revenue  Snap
180    12000  4003
181    16000  4004
182     6000  2003
183     3000  3001
184     2000  2001
CHUNK BOSS
     S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
185  186  2015-12-06  Surulere  Pepperoni Feast   4000         2  08:05:44
186  187  2015-12-14   Gbagada        Beef Suya   3000         4  08:05:46
187  188  2015-12-11  Surulere   Veggie Supreme   3000         3  08:05:47
188  189  2015-12-10   Gbagada          Meatzaa   2000         5  08:05:51
189  190  2015-12-06   Gbagada     Chicken Bali   2000         3  08:05:53

     Revenue  Snap
185     8000  4002
186    12000  3004
187     9000  3003
188    10000  2005
189     6000  2003
CHUNK BOSS
     S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
190  191  2015-12-15  Gbagada    Pepperoni Suya   3000         1  08:05:53
191  192  2015-12-15    Ikoyi    Pepperoni Suya   3000         5  08:05:55
192  193  2015-12-03    Ikoyi    Veggie Supreme   3000         3  08:05:55
193  194  2015-12-12  Gbagada  BBQ Philly Steak   4000         3  08:05:56
194  195  2015-12-03  Gbagada         Margarita   4000         4  08:06:00

     Revenue  Snap
190     3000  3001
191    15000  3005
192     9000  3003
193    12000  4003
194    16000  4004
CHUNK BOSS
     S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
195  196  2015-12-13    Lekki      BBQ Chicken   4000         4  08:06:01
196  197  2015-12-10    Lekki        Beef Suya   3000         1  08:06:01
197  198  2015-12-07   Ibadan      BBQ Chicken   4000         1  08:06:03
198  199  2015-12-12    Ikoyi        Beef Suya   3000         4  08:06:07
199  200  2015-12-08  Gbagada  Pepperoni Feast   4000         3  08:06:08

     Revenue  Snap
195    16000  4004
196     3000  3001
197     4000  4001
198    12000  3004
199    12000  4003
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
200  201  2015-12-07     Lekki  Hot Pepperoni Feast   4000         2
201  202  2015-12-14  Surulere  Hot Pepperoni Feast   4000         4
202  203  2015-12-05   Gbagada      Pepperoni Feast   4000         3
203  204  2015-12-14     Lekki         Chicken Bali   2000         5
204  205  2015-12-09   Gbagada          BBQ Chicken   4000         5

         Time  Revenue  Snap
200  08:06:10     8000  4002
201  08:06:10    16000  4004
202  08:06:12    12000  4003
203  08:06:22    10000  2005
204  08:06:22    20000  4005
CHUNK BOSS
     S/N        Date  Branch        Pizza Sold  Price  Quantity      Time  \
205  206  2015-12-10   Ikoyi    Chicken Legend   2000         2  08:06:28
206  207  2015-12-07  Ibadan        Hot Veggie   4000         5  08:06:30
207  208  2015-12-10  Ibadan  BBQ Philly Steak   4000         4  08:06:32
208  209  2015-12-12  Ibadan         Margarita   4000         4  08:06:33
209  210  2015-12-03  Ibadan           Meatzaa   2000         1  08:06:33

     Revenue  Snap
205     4000  2002
206    20000  4005
207    16000  4004
208    16000  4004
209     2000  2001
CHUNK BOSS
     S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
210  211  2015-12-10  Gbagada    Extravaganza   2000         5  08:06:37
211  212  2015-12-06  Gbagada         Meatzaa   2000         4  08:06:37
212  213  2015-12-09  Gbagada     BBQ Chicken   4000         2  08:06:40
213  214  2015-12-03  Gbagada  Veggie Supreme   3000         3  08:06:45
214  215  2015-12-11    Ikoyi     BBQ Chicken   4000         5  08:06:46

     Revenue  Snap
210    10000  2005
211     8000  2004
212     8000  4002
213     9000  3003
214    20000  4005
CHUNK BOSS
     S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
215  216  2015-12-08    Ikoyi  BBQ Philly Steak   4000         2  08:06:46
216  217  2015-12-14    Ikoyi         Margarita   4000         1  08:06:50
217  218  2015-12-11   Ibadan        Hot Veggie   4000         5  08:06:50
218  219  2015-12-08  Gbagada    Chicken Legend   2000         5  08:06:51
219  220  2015-12-10    Ikoyi        Hot Veggie   4000         3  08:06:53

     Revenue  Snap
215     8000  4002
216     4000  4001
217    20000  4005
218    10000  2005
219    12000  4003
CHUNK BOSS
     S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
220  221  2015-12-15     Ikoyi  Chicken Legend   2000         5  08:06:54
221  222  2015-12-13  Surulere  Veggie Supreme   3000         4  08:06:55
222  223  2015-12-10     Ikoyi  Pepperoni Suya   3000         3  08:06:57
223  224  2015-12-13  Surulere         Meatzaa   2000         4  08:07:00
224  225  2015-12-03   Gbagada    Chicken Bali   2000         2  08:07:03

     Revenue  Snap
220    10000  2005
221    12000  3004
222     9000  3003
223     8000  2004
224     4000  2002
CHUNK BOSS
     S/N        Date   Branch           Pizza Sold  Price  Quantity      Time  \
225  226  2015-12-12   Ibadan       Veggie Supreme   3000         3  08:07:03
226  227  2015-12-07    Lekki  Hot Pepperoni Feast   4000         5  08:07:04
227  228  2015-12-10    Lekki     BBQ Philly Steak   4000         5  08:07:04
228  229  2015-12-03  Gbagada            Margarita   4000         2  08:07:05
229  230  2015-12-10    Ikoyi       Chicken Legend   2000         3  08:07:05

     Revenue  Snap
225     9000  3003
226    20000  4005
227    20000  4005
228     8000  4002
229     6000  2003
CHUNK BOSS
     S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
230  231  2015-12-06    Ibadan      BBQ Chicken   4000         3  08:07:07
231  232  2015-12-05     Lekki       Hot Veggie   4000         1  08:07:07
232  233  2015-12-06   Gbagada       Hot Veggie   4000         3  08:07:16
233  234  2015-12-06     Lekki     Chicken Suya   4000         1  08:07:16
234  235  2015-12-04  Surulere  Pepperoni Feast   4000         3  08:07:21

     Revenue  Snap
230    12000  4003
231     4000  4001
232    12000  4003
233     4000  4001
234    12000  4003
CHUNK BOSS
     S/N        Date   Branch           Pizza Sold  Price  Quantity      Time  \
235  236  2015-12-13    Ikoyi  Hot Pepperoni Feast   4000         3  08:07:21
236  237  2015-12-08  Gbagada         Extravaganza   2000         4  08:07:22
237  238  2015-12-09    Ikoyi              Meatzaa   2000         1  08:07:23
238  239  2015-12-06  Gbagada       Veggie Supreme   3000         4  08:07:23
239  240  2015-12-15   Ibadan  Hot Pepperoni Feast   4000         4  08:07:25

     Revenue  Snap
235    12000  4003
236     8000  2004
237     2000  2001
238    12000  3004
239    16000  4004

CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
240  241  2015-12-12     Ikoyi         Extravaganza   2000         1
241  242  2015-12-08     Ikoyi          BBQ Chicken   4000         5
242  243  2015-12-05   Gbagada         Extravaganza   2000         3
243  244  2015-12-09   Gbagada              Meatzaa   2000         1
244  245  2015-12-03  Surulere  Hot Pepperoni Feast   4000         3

         Time  Revenue  Snap
240  08:07:26     2000  2001
241  08:07:28    20000  4005
242  08:07:30     6000  2003
243  08:07:42     2000  2001
244  08:07:42    12000  4003
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
245  246  2015-12-09     Lekki            Beef Suya   3000         5
246  247  2015-12-10  Surulere            Margarita   4000         3
247  248  2015-12-07   Gbagada  Hot Pepperoni Feast   4000         1
248  249  2015-12-08     Ikoyi         Chicken Bali   2000         4
249  250  2015-12-07     Ikoyi              Meatzaa   2000         2

         Time  Revenue  Snap
245  08:07:43    15000  3005
246  08:07:46    12000  4003
247  08:07:49     4000  4001
248  08:07:49     8000  2004
249  08:07:50     4000  2002
CHUNK BOSS
     S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
250  251  2015-12-08    Ikoyi  BBQ Philly Steak   4000         2  08:07:50
251  252  2015-12-05    Lekki   Pepperoni Feast   4000         2  08:07:56
252  253  2015-12-11  Gbagada     Chicken Feast   2000         5  08:07:56
253  254  2015-12-03   Ibadan    Veggie Supreme   3000         5  08:07:59
254  255  2015-12-04    Ikoyi   Pepperoni Feast   4000         4  08:08:01

     Revenue  Snap
250     8000  4002
251     8000  4002
252    10000  2005
253    15000  3005
254    16000  4004
CHUNK BOSS
     S/N        Date  Branch       Pizza Sold  Price  Quantity      Time  \
255  256  2015-12-05   Lekki     Extravaganza   2000         1  08:08:03
256  257  2015-12-07   Lekki     Chicken Bali   2000         5  08:08:04
257  258  2015-12-13   Lekki          Meatzaa   2000         3  08:08:04
258  259  2015-12-04  Ibadan  Pepperoni Feast   4000         4  08:08:11
259  260  2015-12-14  Ibadan   Veggie Supreme   3000         1  08:08:12

     Revenue  Snap
255     2000  2001
256    10000  2005
257     6000  2003
258    16000  4004
259     3000  3001
CHUNK BOSS
     S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
260  261  2015-12-09  Gbagada      Hot Veggie   4000         1  08:08:17
261  262  2015-12-06  Gbagada        Italiano   3000         4  08:08:25
262  263  2015-12-05    Lekki        Italiano   3000         3  08:08:25
263  264  2015-12-15  Gbagada  Chicken Legend   2000         3  08:08:27
264  265  2015-12-15    Lekki         Meatzaa   2000         4  08:08:29

     Revenue  Snap
260     4000  4001
261    12000  3004
262     9000  3003
263     6000  2003
264     8000  2004
CHUNK BOSS
     S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
265  266  2015-12-14     Ikoyi       BBQ Chicken   4000         1  08:08:31
266  267  2015-12-07     Ikoyi  BBQ Philly Steak   4000         1  08:08:32
267  268  2015-12-06  Surulere      Chicken Suya   4000         2  08:08:33
268  269  2015-12-04  Surulere    Veggie Supreme   3000         4  08:08:34
269  270  2015-12-08     Lekki      Chicken Bali   2000         1  08:08:35

     Revenue  Snap
265     4000  4001
266     4000  4001
267     8000  4002
268    12000  3004
269     2000  2001
CHUNK BOSS
     S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
270  271  2015-12-09     Ikoyi    Chicken Suya   4000         4  08:08:39
271  272  2015-12-06  Surulere  Chicken Legend   2000         5  08:08:40
272  273  2015-12-09     Lekki  Pepperoni Suya   3000         2  08:08:40
273  274  2015-12-05    Ibadan      Hot Veggie   4000         2  08:08:42
274  275  2015-12-13  Surulere     BBQ Chicken   4000         5  08:08:45

     Revenue  Snap
270    16000  4004
271    10000  2005
272     6000  3002
273     8000  4002
274    20000  4005
CHUNK BOSS
     S/N        Date    Branch     Pizza Sold  Price  Quantity      Time  \
275  276  2015-12-05    Ibadan    BBQ Chicken   4000         3  08:08:45
276  277  2015-12-13     Ikoyi        Meatzaa   2000         1  08:08:45
277  278  2015-12-12    Ibadan  Chicken Feast   2000         2  08:08:47
278  279  2015-12-14     Ikoyi      Beef Suya   3000         5  08:08:50
279  280  2015-12-04  Surulere     Hot Veggie   4000         2  08:08:53

     Revenue  Snap
275    12000  4003
276     2000  2001
277     4000  2002
278    15000  3005
279     8000  4002
CHUNK BOSS
     S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
280  281  2015-12-13     Lekki     Extravaganza   2000         5  08:08:53
281  282  2015-12-12    Ibadan  Pepperoni Feast   4000         4  08:08:57
282  283  2015-12-07    Ibadan   Pepperoni Suya   3000         2  08:09:00
283  284  2015-12-15   Gbagada  Pepperoni Feast   4000         1  08:09:00
284  285  2015-12-05  Surulere   Veggie Supreme   3000         2  08:09:01

     Revenue  Snap
280    10000  2005
281    16000  4004
282     6000  3002
283     4000  4001
284     6000  3002
CHUNK BOSS
     S/N        Date   Branch           Pizza Sold  Price  Quantity      Time  \
285  286  2015-12-03  Gbagada         Chicken Suya   4000         3  08:09:02
286  287  2015-12-05    Ikoyi  Hot Pepperoni Feast   4000         3  08:09:02
287  288  2015-12-11  Gbagada         Chicken Suya   4000         4  08:09:03
288  289  2015-12-06    Ikoyi             Italiano   3000         4  08:09:05
289  290  2015-12-06    Lekki           Hot Veggie   4000         2  08:09:05

     Revenue  Snap
285    12000  4003
286    12000  4003
287    16000  4004
288    12000  3004
289     8000  4002
CHUNK BOSS
     S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
290  291  2015-12-12    Ikoyi  Chicken Legend   2000         5  08:09:08
291  292  2015-12-04    Ikoyi    Extravaganza   2000         3  08:09:08
292  293  2015-12-09   Ibadan  Pepperoni Suya   3000         1  08:09:10
293  294  2015-12-05  Gbagada  Chicken Legend   2000         5  08:09:11
294  295  2015-12-11    Lekki       Beef Suya   3000         4  08:09:11

     Revenue  Snap
290    10000  2005
291     6000  2003
292     3000  3001
293    10000  2005
294    12000  3004
CHUNK BOSS
     S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
295  296  2015-12-06    Ibadan         Meatzaa   2000         3  08:09:16
296  297  2015-12-12     Lekki    Chicken Bali   2000         1  08:09:20
297  298  2015-12-03  Surulere       Margarita   4000         4  08:09:23
298  299  2015-12-10    Ibadan  Pepperoni Suya   3000         3  08:09:28
299  300  2015-12-11     Lekki         Meatzaa   2000         3  08:09:28

     Revenue  Snap
295     6000  2003
296     2000  2001
297    16000  4004
298     9000  3003
299     6000  2003
CHUNK BOSS
     S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
300  301  2015-12-13     Lekki  Veggie Supreme   3000         5  08:09:29
301  302  2015-12-12  Surulere      Hot Veggie   4000         1  08:09:33
302  303  2015-12-07  Surulere       Margarita   4000         4  08:09:33
303  304  2015-12-06    Ibadan  Chicken Legend   2000         3  08:09:37
304  305  2015-12-04   Gbagada        Italiano   3000         2  08:09:39

     Revenue  Snap
300    15000  3005
301     4000  4001
302    16000  4004
303     6000  2003
304     6000  3002
CHUNK BOSS
     S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
305  306  2015-12-08  Surulere  BBQ Philly Steak   4000         5  08:09:39
306  307  2015-12-15  Surulere         Beef Suya   3000         2  08:09:41
307  308  2015-12-15     Lekki  BBQ Philly Steak   4000         2  08:09:45
308  309  2015-12-11  Surulere         Beef Suya   3000         2  08:09:46
309  310  2015-12-06     Ikoyi  BBQ Philly Steak   4000         5  08:09:47

     Revenue  Snap
305    20000  4005
306     6000  3002
307     8000  4002
308     6000  3002
309    20000  4005
CHUNK BOSS
     S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
310  311  2015-12-09   Gbagada         Italiano   3000         5  08:09:47
311  312  2015-12-03   Gbagada   Veggie Supreme   3000         1  08:09:47
312  313  2015-12-10  Surulere       Hot Veggie   4000         3  08:09:49
313  314  2015-12-05     Ikoyi  Pepperoni Feast   4000         2  08:09:54
314  315  2015-12-14   Gbagada       Hot Veggie   4000         4  08:09:55

     Revenue  Snap
310    15000  3005
311     3000  3001
312    12000  4003
313     8000  4002
314    16000  4004
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
315  316  2015-12-08   Gbagada          BBQ Chicken   4000         3
316  317  2015-12-05     Lekki  Hot Pepperoni Feast   4000         5
317  318  2015-12-04     Ikoyi            Margarita   4000         5
318  319  2015-12-15  Surulere        Chicken Feast   2000         5
319  320  2015-12-07  Surulere          BBQ Chicken   4000         4

         Time  Revenue  Snap
315  08:09:55    12000  4003
316  08:09:59    20000  4005
317  08:10:00    20000  4005
318  08:10:08    10000  2005
319  08:10:08    16000  4004
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
320  321  2015-12-04   Gbagada       Pepperoni Suya   3000         5
321  322  2015-12-04     Lekki        Chicken Feast   2000         5
322  323  2015-12-05  Surulere  Hot Pepperoni Feast   4000         1
323  324  2015-12-03     Ikoyi      Pepperoni Feast   4000         1
324  325  2015-12-05     Ikoyi       Chicken Legend   2000         1

         Time  Revenue  Snap
320  08:10:10    15000  3005
321  08:10:11    10000  2005
322  08:10:12     4000  4001
323  08:10:14     4000  4001
324  08:10:15     2000  2001

CHUNK BOSS
     S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
325  326  2015-12-08     Lekki       Beef Suya   3000         5  08:10:18
326  327  2015-12-05  Surulere    Chicken Bali   2000         2  08:10:18
327  328  2015-12-07     Lekki    Chicken Bali   2000         3  08:10:18
328  329  2015-12-08     Lekki  Pepperoni Suya   3000         5  08:10:22
329  330  2015-12-05     Lekki  Chicken Legend   2000         5  08:10:25

     Revenue  Snap
325    15000  3005
326     4000  2002
327     6000  2003
328    15000  3005
329    10000  2005
CHUNK BOSS
     S/N        Date   Branch           Pizza Sold  Price  Quantity      Time  \
330  331  2015-12-04   Ibadan  Hot Pepperoni Feast   4000         5  08:10:26
331  332  2015-12-03    Ikoyi        Chicken Feast   2000         1  08:10:33
332  333  2015-12-10   Ibadan            Margarita   4000         4  08:10:35
333  334  2015-12-09  Gbagada         Extravaganza   2000         5  08:10:37
334  335  2015-12-06  Gbagada       Veggie Supreme   3000         1  08:10:37

     Revenue  Snap
330    20000  4005
331     2000  2001
332    16000  4004
333    10000  2005
334     3000  3001
CHUNK BOSS
     S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
335  336  2015-12-08     Lekki   Veggie Supreme   3000         1  08:10:38
336  337  2015-12-12  Surulere  Pepperoni Feast   4000         2  08:10:42
337  338  2015-12-10     Ikoyi   Pepperoni Suya   3000         5  08:10:43
338  339  2015-12-09     Lekki         Italiano   3000         5  08:10:45
339  340  2015-12-12  Surulere         Italiano   3000         1  08:10:49

     Revenue  Snap
335     3000  3001
336     8000  4002
337    15000  3005
338    15000  3005
339     3000  3001
CHUNK BOSS
     S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
340  341  2015-12-06  Surulere  Pepperoni Suya   3000         1  08:10:54
341  342  2015-12-07  Surulere  Chicken Legend   2000         5  08:10:56
342  343  2015-12-15   Gbagada  Chicken Legend   2000         1  08:11:00
343  344  2015-12-10  Surulere      Hot Veggie   4000         5  08:11:02
344  345  2015-12-11    Ibadan  Pepperoni Suya   3000         4  08:11:05

     Revenue  Snap
340     3000  3001
341    10000  2005
342     2000  2001
343    20000  4005
344    12000  3004
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
345  346  2015-12-13     Lekki       Veggie Supreme   3000         5
346  347  2015-12-03   Gbagada             Italiano   3000         1
347  348  2015-12-14     Lekki      Pepperoni Feast   4000         5
348  349  2015-12-04  Surulere  Hot Pepperoni Feast   4000         5
349  350  2015-12-10    Ibadan       Veggie Supreme   3000         4

         Time  Revenue  Snap
345  08:11:06    15000  3005
346  08:11:08     3000  3001
347  08:11:13    20000  4005
348  08:11:13    20000  4005
349  08:11:14    12000  3004
CHUNK BOSS
     S/N        Date   Branch           Pizza Sold  Price  Quantity      Time  \
350  351  2015-12-10  Gbagada       Pepperoni Suya   3000         3  08:11:15
351  352  2015-12-12    Ikoyi            Margarita   4000         3  08:11:17
352  353  2015-12-13  Gbagada       Veggie Supreme   3000         2  08:11:19
353  354  2015-12-04  Gbagada  Hot Pepperoni Feast   4000         5  08:11:19
354  355  2015-12-15   Ibadan         Chicken Bali   2000         4  08:11:19

     Revenue  Snap
350     9000  3003
351    12000  4003
352     6000  3002
353    20000  4005
354     8000  2004
CHUNK BOSS
     S/N        Date    Branch    Pizza Sold  Price  Quantity      Time  \
355  356  2015-12-03     Ikoyi      Italiano   3000         3  08:11:22
356  357  2015-12-12    Ibadan    Hot Veggie   4000         4  08:11:22
357  358  2015-12-10  Surulere    Hot Veggie   4000         5  08:11:23
358  359  2015-12-10   Gbagada  Extravaganza   2000         3  08:11:23
359  360  2015-12-07   Gbagada  Chicken Bali   2000         1  08:11:26

     Revenue  Snap
355     9000  3003
356    16000  4004
357    20000  4005
358     6000  2003
359     2000  2001
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
360  361  2015-12-13  Surulere  Hot Pepperoni Feast   4000         5
361  362  2015-12-13   Gbagada         Extravaganza   2000         1
362  363  2015-12-14    Ibadan        Chicken Feast   2000         4
363  364  2015-12-06    Ibadan            Margarita   4000         3
364  365  2015-12-11    Ibadan       Chicken Legend   2000         5

         Time  Revenue  Snap
360  08:11:26    20000  4005
361  08:11:27     2000  2001
362  08:11:27     8000  2004
363  08:11:29    12000  4003
364  08:11:31    10000  2005
CHUNK BOSS
     S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
365  366  2015-12-07    Ikoyi  BBQ Philly Steak   4000         1  08:11:33
366  367  2015-12-14  Gbagada           Meatzaa   2000         1  08:11:36
367  368  2015-12-05    Ikoyi  BBQ Philly Steak   4000         5  08:11:40
368  369  2015-12-06    Lekki     Chicken Feast   2000         4  08:11:42
369  370  2015-12-13    Ikoyi   Pepperoni Feast   4000         2  08:11:43

     Revenue  Snap
365     4000  4001
366     2000  2001
367    20000  4005
368     8000  2004
369     8000  4002
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
370  371  2015-12-12     Ikoyi      Pepperoni Feast   4000         1
371  372  2015-12-14   Gbagada            Margarita   4000         3
372  373  2015-12-13     Ikoyi  Hot Pepperoni Feast   4000         5
373  374  2015-12-15     Lekki        Chicken Feast   2000         1
374  375  2015-12-13  Surulere            Margarita   4000         5

         Time  Revenue  Snap
370  08:11:45     4000  4001
371  08:11:46    12000  4003
372  08:11:46    20000  4005
373  08:11:47     2000  2001
374  08:11:49    20000  4005
CHUNK BOSS
     S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
375  376  2015-12-07     Lekki  Chicken Legend   2000         3  08:11:49
376  377  2015-12-12     Lekki  Veggie Supreme   3000         2  08:11:51
377  378  2015-12-14     Ikoyi      Hot Veggie   4000         1  08:11:55
378  379  2015-12-15     Ikoyi        Italiano   3000         4  08:11:58
379  380  2015-12-09  Surulere       Margarita   4000         5  08:11:58

     Revenue  Snap
375     6000  2003
376     6000  3002
377     4000  4001
378    12000  3004
379    20000  4005
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
380  381  2015-12-13   Gbagada             Italiano   3000         2
381  382  2015-12-14     Lekki             Italiano   3000         5
382  383  2015-12-04  Surulere         Chicken Suya   4000         5
383  384  2015-12-09  Surulere  Hot Pepperoni Feast   4000         4
384  385  2015-12-08  Surulere        Chicken Feast   2000         3

         Time  Revenue  Snap
380  08:11:59     6000  3002
381  08:12:02    15000  3005
382  08:12:06    20000  4005
383  08:12:07    16000  4004
384  08:12:09     6000  2003
CHUNK BOSS
     S/N        Date  Branch           Pizza Sold  Price  Quantity      Time  \
385  386  2015-12-05   Ikoyi        Chicken Feast   2000         5  08:12:11
386  387  2015-12-10  Ibadan       Pepperoni Suya   3000         3  08:12:11
387  388  2015-12-06  Ibadan       Pepperoni Suya   3000         4  08:12:17
388  389  2015-12-03   Lekki       Chicken Legend   2000         3  08:12:18
389  390  2015-12-13   Ikoyi  Hot Pepperoni Feast   4000         4  08:12:18

     Revenue  Snap
385    10000  2005
386     9000  3003
387    12000  3004
388     6000  2003
389    16000  4004
CHUNK BOSS
     S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
390  391  2015-12-08     Ikoyi          Italiano   3000         1  08:12:20
391  392  2015-12-05   Gbagada    Veggie Supreme   3000         2  08:12:21
392  393  2015-12-11     Lekki      Extravaganza   2000         1  08:12:22
393  394  2015-12-14     Ikoyi    Veggie Supreme   3000         4  08:12:23
394  395  2015-12-12  Surulere  BBQ Philly Steak   4000         5  08:12:24

     Revenue  Snap
390     3000  3001
391     6000  3002
392     2000  2001
393    12000  3004
394    20000  4005
CHUNK BOSS
     S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
395  396  2015-12-06  Gbagada         Beef Suya   3000         5  08:12:27
396  397  2015-12-11    Lekki         Margarita   4000         2  08:12:30
397  398  2015-12-11   Ibadan  BBQ Philly Steak   4000         5  08:12:31
398  399  2015-12-04  Gbagada        Hot Veggie   4000         1  08:12:31
399  400  2015-12-14    Lekki        Hot Veggie   4000         5  08:12:33

     Revenue  Snap
395    15000  3005
396     8000  4002
397    20000  4005
398     4000  4001
399    20000  4005
CHUNK BOSS
     S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
400  401  2015-12-15  Surulere       Margarita   4000         1  08:12:35
401  402  2015-12-07    Ibadan    Extravaganza   2000         1  08:12:38
402  403  2015-12-03     Lekki  Pepperoni Suya   3000         4  08:12:40
403  404  2015-12-07     Ikoyi    Chicken Bali   2000         4  08:12:44
404  405  2015-12-06    Ibadan  Veggie Supreme   3000         2  08:12:45

     Revenue  Snap
400     4000  4001
401     2000  2001
402    12000  3004
403     8000  2004
404     6000  3002
CHUNK BOSS
     S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
405  406  2015-12-10  Surulere        Italiano   3000         4  08:12:45
406  407  2015-12-03    Ibadan   Chicken Feast   2000         5  08:12:46
407  408  2015-12-09    Ibadan         Meatzaa   2000         1  08:12:47
408  409  2015-12-08    Ibadan  Veggie Supreme   3000         5  08:12:50
409  410  2015-12-05    Ibadan       Beef Suya   3000         4  08:12:50

     Revenue  Snap
405    12000  3004
406    10000  2005
407     2000  2001
408    15000  3005
409    12000  3004
CHUNK BOSS
     S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
410  411  2015-12-03     Ikoyi         Meatzaa   2000         5  08:12:51
411  412  2015-12-11     Ikoyi  Chicken Legend   2000         2  08:12:52
412  413  2015-12-05     Lekki         Meatzaa   2000         4  08:12:57
413  414  2015-12-13     Ikoyi  Veggie Supreme   3000         3  08:12:59
414  415  2015-12-05  Surulere       Beef Suya   3000         3  08:12:59

     Revenue  Snap
410    10000  2005
411     4000  2002
412     8000  2004
413     9000  3003
414     9000  3003
CHUNK BOSS
     S/N        Date  Branch      Pizza Sold  Price  Quantity      Time  \
415  416  2015-12-12   Lekki         Meatzaa   2000         4  08:12:59
416  417  2015-12-07   Ikoyi  Veggie Supreme   3000         1  08:13:00
417  418  2015-12-05   Lekki       Beef Suya   3000         2  08:13:00
418  419  2015-12-11   Ikoyi       Beef Suya   3000         5  08:13:01
419  420  2015-12-04  Ibadan      Hot Veggie   4000         3  08:13:02

     Revenue  Snap
415     8000  2004
416     3000  3001
417     6000  3002
418    15000  3005
419    12000  4003

CHUNK BOSS
     S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
420  421  2015-12-05    Ikoyi      Chicken Bali   2000         3  08:13:02
421  422  2015-12-15   Ibadan           Meatzaa   2000         5  08:13:03
422  423  2015-12-07   Ibadan     Chicken Feast   2000         2  08:13:05
423  424  2015-12-03  Gbagada  BBQ Philly Steak   4000         4  08:13:05
424  425  2015-12-10   Ibadan          Italiano   3000         2  08:13:05

     Revenue  Snap
420     6000  2003
421    10000  2005
422     4000  2002
423    16000  4004
424     6000  3002
CHUNK BOSS
     S/N        Date Branch      Pizza Sold  Price  Quantity      Time  \
425  426  2015-12-15  Lekki  Pepperoni Suya   3000         1  08:13:06
426  427  2015-12-05  Ikoyi         Meatzaa   2000         2  08:13:06
427  428  2015-12-09  Ikoyi       Beef Suya   3000         2  08:13:07
428  429  2015-12-04  Lekki         Meatzaa   2000         5  08:13:07
429  430  2015-12-11  Ikoyi    Chicken Suya   4000         2  08:13:11

     Revenue  Snap
425     3000  3001
426     4000  2002
427     6000  3002
428    10000  2005
429     8000  4002
CHUNK BOSS
     S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
430  431  2015-12-05  Surulere     Chicken Bali   2000         4  08:13:18
431  432  2015-12-15   Gbagada   Chicken Legend   2000         4  08:13:20
432  433  2015-12-14    Ibadan   Chicken Legend   2000         1  08:13:22
433  434  2015-12-09     Ikoyi  Pepperoni Feast   4000         5  08:13:23
434  435  2015-12-15    Ibadan    Chicken Feast   2000         3  08:13:26

     Revenue  Snap
430     8000  2004
431     8000  2004
432     2000  2001
433    20000  4005
434     6000  2003
CHUNK BOSS
     S/N        Date  Branch        Pizza Sold  Price  Quantity      Time  \
435  436  2015-12-05   Ikoyi      Chicken Suya   4000         4  08:13:28
436  437  2015-12-04  Ibadan         Beef Suya   3000         3  08:13:35
437  438  2015-12-07   Ikoyi    Chicken Legend   2000         1  08:13:37
438  439  2015-12-09   Lekki          Italiano   3000         3  08:13:38
439  440  2015-12-10   Lekki  BBQ Philly Steak   4000         5  08:13:40

     Revenue  Snap
435    16000  4004
436     9000  3003
437     2000  2001
438     9000  3003
439    20000  4005
CHUNK BOSS
     S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
440  441  2015-12-10   Ibadan       Margarita   4000         3  08:13:50
441  442  2015-12-10  Gbagada         Meatzaa   2000         3  08:13:51
442  443  2015-12-06   Ibadan    Chicken Bali   2000         4  08:13:53
443  444  2015-12-15   Ibadan      Hot Veggie   4000         2  08:13:57
444  445  2015-12-10    Ikoyi  Pepperoni Suya   3000         3  08:13:57

     Revenue  Snap
440    12000  4003
441     6000  2003
442     8000  2004
443     8000  4002
444     9000  3003
CHUNK BOSS
     S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
445  446  2015-12-03    Ibadan   Pepperoni Feast   4000         4  08:13:59
446  447  2015-12-04  Surulere    Veggie Supreme   3000         5  08:14:00
447  448  2015-12-11     Lekki  BBQ Philly Steak   4000         2  08:14:02
448  449  2015-12-06     Lekki  BBQ Philly Steak   4000         1  08:14:03
449  450  2015-12-08  Surulere      Chicken Bali   2000         3  08:14:03

     Revenue  Snap
445    16000  4004
446    15000  3005
447     8000  4002
448     4000  4001
449     6000  2003
CHUNK BOSS
     S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
450  451  2015-12-12    Lekki   Chicken Legend   2000         1  08:14:05
451  452  2015-12-05    Lekki     Chicken Suya   4000         3  08:14:06
452  453  2015-12-09  Gbagada  Pepperoni Feast   4000         1  08:14:11
453  454  2015-12-11   Ibadan   Chicken Legend   2000         1  08:14:13
454  455  2015-12-12   Ibadan     Extravaganza   2000         5  08:14:14

     Revenue  Snap
450     2000  2001
451    12000  4003
452     4000  4001
453     2000  2001
454    10000  2005
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
455  456  2015-12-06    Ibadan  Hot Pepperoni Feast   4000         2
456  457  2015-12-04     Ikoyi         Extravaganza   2000         3
457  458  2015-12-12    Ibadan         Extravaganza   2000         2
458  459  2015-12-08  Surulere         Chicken Suya   4000         3
459  460  2015-12-13   Gbagada      Pepperoni Feast   4000         3

         Time  Revenue  Snap
455  08:14:15     8000  4002
456  08:14:21     6000  2003
457  08:14:23     4000  2002
458  08:14:23    12000  4003
459  08:14:29    12000  4003
CHUNK BOSS
     S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
460  461  2015-12-10    Lekki  Veggie Supreme   3000         3  08:14:33
461  462  2015-12-04  Gbagada  Pepperoni Suya   3000         5  08:14:36
462  463  2015-12-06    Lekki    Extravaganza   2000         2  08:14:47
463  464  2015-12-04  Gbagada         Meatzaa   2000         4  08:14:53
464  465  2015-12-06  Gbagada    Extravaganza   2000         1  08:14:55

     Revenue  Snap
460     9000  3003
461    15000  3005
462     4000  2002
463     8000  2004
464     2000  2001
CHUNK BOSS
     S/N        Date   Branch    Pizza Sold  Price  Quantity      Time  \
465  466  2015-12-07    Ikoyi       Meatzaa   2000         2  08:14:58
466  467  2015-12-14    Ikoyi  Chicken Bali   2000         1  08:14:58
467  468  2015-12-06    Lekki    Hot Veggie   4000         5  08:15:00
468  469  2015-12-15  Gbagada   BBQ Chicken   4000         3  08:15:02
469  470  2015-12-03   Ibadan     Beef Suya   3000         4  08:15:04

     Revenue  Snap
465     4000  2002
466     2000  2001
467    20000  4005
468    12000  4003
469    12000  3004
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
470  471  2015-12-13  Surulere            Beef Suya   3000         1
471  472  2015-12-07     Ikoyi      Pepperoni Feast   4000         4
472  473  2015-12-12     Lekki  Hot Pepperoni Feast   4000         3
473  474  2015-12-14    Ibadan            Beef Suya   3000         2
474  475  2015-12-11    Ibadan              Meatzaa   2000         3

         Time  Revenue  Snap
470  08:15:04     3000  3001
471  08:15:08    16000  4004
472  08:15:12    12000  4003
473  08:15:14     6000  3002
474  08:15:18     6000  2003
CHUNK BOSS
     S/N        Date  Branch        Pizza Sold  Price  Quantity      Time  \
475  476  2015-12-11  Ibadan   Pepperoni Feast   4000         2  08:15:18
476  477  2015-12-05  Ibadan         Margarita   4000         5  08:15:21
477  478  2015-12-05   Ikoyi  BBQ Philly Steak   4000         2  08:15:24
478  479  2015-12-11  Ibadan          Italiano   3000         2  08:15:24
479  480  2015-12-08   Lekki    Chicken Legend   2000         2  08:15:25

     Revenue  Snap
475     8000  4002
476    20000  4005
477     8000  4002
478     6000  3002
479     4000  2002
CHUNK BOSS
     S/N        Date    Branch    Pizza Sold  Price  Quantity      Time  \
480  481  2015-12-12    Ibadan     Beef Suya   3000         4  08:15:30
481  482  2015-12-10    Ibadan  Chicken Suya   4000         4  08:15:31
482  483  2015-12-13     Ikoyi      Italiano   3000         5  08:15:36
483  484  2015-12-09    Ibadan       Meatzaa   2000         4  08:15:36
484  485  2015-12-11  Surulere     Beef Suya   3000         3  08:15:38

     Revenue  Snap
480    12000  3004
481    16000  4004
482    15000  3005
483     8000  2004
484     9000  3003
CHUNK BOSS
     S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
485  486  2015-12-13    Ikoyi   Chicken Feast   2000         2  08:15:39
486  487  2015-12-09  Gbagada   Chicken Feast   2000         3  08:15:39
487  488  2015-12-08  Gbagada      Hot Veggie   4000         4  08:15:45
488  489  2015-12-14    Lekki    Chicken Suya   4000         5  08:15:47
489  490  2015-12-05  Gbagada  Veggie Supreme   3000         2  08:15:48

     Revenue  Snap
485     4000  2002
486     6000  2003
487    16000  4004
488    20000  4005
489     6000  3002
CHUNK BOSS
     S/N        Date  Branch      Pizza Sold  Price  Quantity      Time  \
490  491  2015-12-12   Ikoyi      Hot Veggie   4000         4  08:15:51
491  492  2015-12-04   Ikoyi  Pepperoni Suya   3000         4  08:15:52
492  493  2015-12-03  Ibadan    Chicken Suya   4000         5  08:15:54
493  494  2015-12-09  Ibadan         Meatzaa   2000         1  08:15:57
494  495  2015-12-05   Lekki   Chicken Feast   2000         1  08:15:59

     Revenue  Snap
490    16000  4004
491    12000  3004
492    20000  4005
493     2000  2001
494     2000  2001
CHUNK BOSS
     S/N        Date   Branch           Pizza Sold  Price  Quantity      Time  \
495  496  2015-12-15    Ikoyi      Pepperoni Feast   4000         5  08:16:07
496  497  2015-12-04  Gbagada  Hot Pepperoni Feast   4000         3  08:16:10
497  498  2015-12-06   Ibadan       Pepperoni Suya   3000         4  08:16:10
498  499  2015-12-07    Lekki         Chicken Suya   4000         5  08:16:13
499  500  2015-12-03    Ikoyi      Pepperoni Feast   4000         2  08:16:16

     Revenue  Snap
495    20000  4005
496    12000  4003
497    12000  3004
498    20000  4005
499     8000  4002

CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
500  501  2015-12-06  Surulere           Hot Veggie   4000         5
501  502  2015-12-14    Ibadan       Veggie Supreme   3000         4
502  503  2015-12-06  Surulere  Hot Pepperoni Feast   4000         5
503  504  2015-12-09   Gbagada         Chicken Suya   4000         1
504  505  2015-12-13     Lekki         Chicken Suya   4000         4

         Time  Revenue  Snap
500  08:16:17    20000  4005
501  08:16:19    12000  3004
502  08:16:19    20000  4005
503  08:16:20     4000  4001
504  08:16:21    16000  4004
CHUNK BOSS
     S/N        Date   Branch           Pizza Sold  Price  Quantity      Time  \
505  506  2015-12-05    Ikoyi       Veggie Supreme   3000         2  08:16:21
506  507  2015-12-06  Gbagada       Veggie Supreme   3000         3  08:16:22
507  508  2015-12-10    Ikoyi  Hot Pepperoni Feast   4000         1  08:16:25
508  509  2015-12-10   Ibadan           Hot Veggie   4000         2  08:16:29
509  510  2015-12-14    Lekki       Chicken Legend   2000         2  08:16:35

     Revenue  Snap
505     6000  3002
506     9000  3003
507     4000  4001
508     8000  4002
509     4000  2002
CHUNK BOSS
     S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
510  511  2015-12-05     Ikoyi         Meatzaa   2000         5  08:16:36
511  512  2015-12-05   Gbagada    Chicken Suya   4000         3  08:16:36
512  513  2015-12-13   Gbagada  Pepperoni Suya   3000         5  08:16:36
513  514  2015-12-14  Surulere    Chicken Bali   2000         5  08:16:38
514  515  2015-12-06     Lekki       Margarita   4000         1  08:16:43

     Revenue  Snap
510    10000  2005
511    12000  4003
512    15000  3005
513    10000  2005
514     4000  4001
CHUNK BOSS
     S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
515  516  2015-12-03     Ikoyi     BBQ Chicken   4000         1  08:16:43
516  517  2015-12-06   Gbagada  Pepperoni Suya   3000         1  08:16:44
517  518  2015-12-05   Gbagada  Pepperoni Suya   3000         2  08:16:46
518  519  2015-12-05     Ikoyi        Italiano   3000         4  08:16:49
519  520  2015-12-06  Surulere   Chicken Feast   2000         1  08:16:54

     Revenue  Snap
515     4000  4001
516     3000  3001
517     6000  3002
518    12000  3004
519     2000  2001
CHUNK BOSS
     S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
520  521  2015-12-05     Ikoyi          Italiano   3000         4  08:16:55
521  522  2015-12-14   Gbagada   Pepperoni Feast   4000         3  08:16:58
522  523  2015-12-05     Ikoyi  BBQ Philly Steak   4000         2  08:17:06
523  524  2015-12-06  Surulere    Veggie Supreme   3000         3  08:17:08
524  525  2015-12-03    Ibadan        Hot Veggie   4000         1  08:17:09

     Revenue  Snap
520    12000  3004
521    12000  4003
522     8000  4002
523     9000  3003
524     4000  4001
CHUNK BOSS
     S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
525  526  2015-12-13  Gbagada  Pepperoni Feast   4000         4  08:17:11
526  527  2015-12-06    Ikoyi       Hot Veggie   4000         5  08:17:12
527  528  2015-12-05   Ibadan    Chicken Feast   2000         4  08:17:16
528  529  2015-12-08    Ikoyi     Chicken Suya   4000         1  08:17:21
529  530  2015-12-15   Ibadan        Margarita   4000         2  08:17:21

     Revenue  Snap
525    16000  4004
526    20000  4005
527     8000  2004
528     4000  4001
529     8000  4002
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
530  531  2015-12-13  Surulere           Hot Veggie   4000         3
531  532  2015-12-07     Lekki          BBQ Chicken   4000         1
532  533  2015-12-09  Surulere        Chicken Feast   2000         2
533  534  2015-12-08     Ikoyi            Margarita   4000         5
534  535  2015-12-06     Lekki  Hot Pepperoni Feast   4000         3

         Time  Revenue  Snap
530  08:17:23    12000  4003
531  08:17:23     4000  4001
532  08:17:28     4000  2002
533  08:17:29    20000  4005
534  08:17:30    12000  4003
CHUNK BOSS
     S/N        Date   Branch           Pizza Sold  Price  Quantity      Time  \
535  536  2015-12-09    Ikoyi       Pepperoni Suya   3000         5  08:17:31
536  537  2015-12-03  Gbagada     BBQ Philly Steak   4000         5  08:17:31
537  538  2015-12-05   Ibadan        Chicken Feast   2000         3  08:17:33
538  539  2015-12-12    Ikoyi         Extravaganza   2000         3  08:17:34
539  540  2015-12-08    Ikoyi  Hot Pepperoni Feast   4000         3  08:17:35

     Revenue  Snap
535    15000  3005
536    20000  4005
537     6000  2003
538     6000  2003
539    12000  4003
CHUNK BOSS
     S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
540  541  2015-12-14    Ibadan      Chicken Suya   4000         1  08:17:35
541  542  2015-12-07    Ibadan  BBQ Philly Steak   4000         5  08:17:36
542  543  2015-12-10     Lekki         Margarita   4000         5  08:17:37
543  544  2015-12-14   Gbagada   Pepperoni Feast   4000         2  08:17:38
544  545  2015-12-10  Surulere       BBQ Chicken   4000         2  08:17:39

     Revenue  Snap
540     4000  4001
541    20000  4005
542    20000  4005
543     8000  4002
544     8000  4002
CHUNK BOSS
     S/N        Date  Branch       Pizza Sold  Price  Quantity      Time  \
545  546  2015-12-13  Ibadan     Extravaganza   2000         2  08:17:41
546  547  2015-12-06  Ibadan    Chicken Feast   2000         1  08:17:43
547  548  2015-12-13  Ibadan       Hot Veggie   4000         5  08:17:53
548  549  2015-12-14  Ibadan    Chicken Feast   2000         1  08:17:56
549  550  2015-12-08  Ibadan  Pepperoni Feast   4000         1  08:17:59

     Revenue  Snap
545     4000  2002
546     2000  2001
547    20000  4005
548     2000  2001
549     4000  4001
CHUNK BOSS
     S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
550  551  2015-12-15    Ikoyi         Meatzaa   2000         5  08:18:02
551  552  2015-12-03    Ikoyi    Extravaganza   2000         3  08:18:02
552  553  2015-12-05  Gbagada  Chicken Legend   2000         4  08:18:03
553  554  2015-12-14    Lekki     BBQ Chicken   4000         2  08:18:03
554  555  2015-12-12    Ikoyi  Veggie Supreme   3000         5  08:18:05

     Revenue  Snap
550    10000  2005
551     6000  2003
552     8000  2004
553     8000  4002
554    15000  3005
CHUNK BOSS
     S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
555  556  2015-12-14    Ibadan  BBQ Philly Steak   4000         1  08:18:06
556  557  2015-12-09  Surulere        Hot Veggie   4000         3  08:18:08
557  558  2015-12-04     Ikoyi          Italiano   3000         4  08:18:08
558  559  2015-12-10  Surulere      Chicken Bali   2000         5  08:18:11
559  560  2015-12-07     Lekki          Italiano   3000         2  08:18:11

     Revenue  Snap
555     4000  4001
556    12000  4003
557    12000  3004
558    10000  2005
559     6000  3002
CHUNK BOSS
     S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
560  561  2015-12-15   Gbagada    Pepperoni Suya   3000         3  08:18:11
561  562  2015-12-03    Ibadan           Meatzaa   2000         1  08:18:16
562  563  2015-12-15   Gbagada   Pepperoni Feast   4000         3  08:18:17
563  564  2015-12-09    Ibadan         Beef Suya   3000         1  08:18:19
564  565  2015-12-07  Surulere  BBQ Philly Steak   4000         3  08:18:19

     Revenue  Snap
560     9000  3003
561     2000  2001
562    12000  4003
563     3000  3001
564    12000  4003
CHUNK BOSS
     S/N        Date  Branch     Pizza Sold  Price  Quantity      Time  \
565  566  2015-12-04   Ikoyi     Hot Veggie   4000         1  08:18:22
566  567  2015-12-07   Lekki        Meatzaa   2000         2  08:18:24
567  568  2015-12-14  Ibadan  Chicken Feast   2000         3  08:18:32
568  569  2015-12-14  Ibadan       Italiano   3000         3  08:18:32
569  570  2015-12-07  Ibadan      Margarita   4000         2  08:18:34

     Revenue  Snap
565     4000  4001
566     4000  2002
567     6000  2003
568     9000  3003
569     8000  4002
CHUNK BOSS
     S/N        Date   Branch           Pizza Sold  Price  Quantity      Time  \
570  571  2015-12-12    Lekki         Chicken Suya   4000         3  08:18:34
571  572  2015-12-13  Gbagada  Hot Pepperoni Feast   4000         3  08:18:36
572  573  2015-12-05  Gbagada       Pepperoni Suya   3000         5  08:18:38
573  574  2015-12-06    Ikoyi       Pepperoni Suya   3000         3  08:18:39
574  575  2015-12-04    Lekki         Chicken Suya   4000         4  08:18:42

     Revenue  Snap
570    12000  4003
571    12000  4003
572    15000  3005
573     9000  3003
574    16000  4004
CHUNK BOSS
     S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
575  576  2015-12-14    Ibadan  Veggie Supreme   3000         5  08:18:43
576  577  2015-12-10  Surulere  Veggie Supreme   3000         5  08:18:45
577  578  2015-12-13    Ibadan       Margarita   4000         3  08:18:46
578  579  2015-12-11   Gbagada    Extravaganza   2000         1  08:18:46
579  580  2015-12-14    Ibadan  Chicken Legend   2000         5  08:18:48

     Revenue  Snap
575    15000  3005
576    15000  3005
577    12000  4003
578     2000  2001
579    10000  2005
CHUNK BOSS
     S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
580  581  2015-12-08   Gbagada  Pepperoni Suya   3000         2  08:18:49
581  582  2015-12-09     Ikoyi     BBQ Chicken   4000         1  08:18:52
582  583  2015-12-13   Gbagada  Pepperoni Suya   3000         3  08:18:52
583  584  2015-12-11  Surulere   Chicken Feast   2000         2  08:18:55
584  585  2015-12-08   Gbagada      Hot Veggie   4000         4  08:18:57

     Revenue  Snap
580     6000  3002
581     4000  4001
582     9000  3003
583     4000  2002
584    16000  4004
CHUNK BOSS
     S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
585  586  2015-12-05     Lekki    Chicken Legend   2000         5  08:19:01
586  587  2015-12-09  Surulere      Chicken Suya   4000         5  08:19:01
587  588  2015-12-09    Ibadan  BBQ Philly Steak   4000         5  08:19:02
588  589  2015-12-06  Surulere         Margarita   4000         2  08:19:03
589  590  2015-12-14    Ibadan        Hot Veggie   4000         1  08:19:05

     Revenue  Snap
585    10000  2005
586    20000  4005
587    20000  4005
588     8000  4002
589     4000  4001

CHUNK BOSS
     S/N        Date  Branch        Pizza Sold  Price  Quantity      Time  \
590  591  2015-12-06   Ikoyi  BBQ Philly Steak   4000         5  08:19:07
591  592  2015-12-05  Ibadan      Chicken Bali   2000         5  08:19:07
592  593  2015-12-08   Ikoyi    Chicken Legend   2000         2  08:19:09
593  594  2015-12-03   Ikoyi           Meatzaa   2000         1  08:19:12
594  595  2015-12-03   Ikoyi         Beef Suya   3000         2  08:19:14

     Revenue  Snap
590    20000  4005
591    10000  2005
592     4000  2002
593     2000  2001
594     6000  3002
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
595  596  2015-12-09    Ibadan           Hot Veggie   4000         4
596  597  2015-12-04     Lekki  Hot Pepperoni Feast   4000         5
597  598  2015-12-14   Gbagada     BBQ Philly Steak   4000         5
598  599  2015-12-10     Ikoyi           Hot Veggie   4000         1
599  600  2015-12-05  Surulere        Chicken Feast   2000         2

         Time  Revenue  Snap
595  08:19:14    16000  4004
596  08:19:14    20000  4005
597  08:19:14    20000  4005
598  08:19:15     4000  4001
599  08:19:17     4000  2002
CHUNK BOSS
     S/N        Date   Branch           Pizza Sold  Price  Quantity      Time  \
600  601  2015-12-12  Gbagada       Pepperoni Suya   3000         4  08:19:19
601  602  2015-12-10    Ikoyi       Pepperoni Suya   3000         4  08:19:20
602  603  2015-12-05   Ibadan              Meatzaa   2000         4  08:19:24
603  604  2015-12-06    Lekki  Hot Pepperoni Feast   4000         1  08:19:27
604  605  2015-12-11   Ibadan         Extravaganza   2000         3  08:19:28

     Revenue  Snap
600    12000  3004
601    12000  3004
602     8000  2004
603     4000  4001
604     6000  2003
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
605  606  2015-12-11     Ikoyi         Extravaganza   2000         2
606  607  2015-12-14  Surulere  Hot Pepperoni Feast   4000         2
607  608  2015-12-08  Surulere          BBQ Chicken   4000         4
608  609  2015-12-14  Surulere     BBQ Philly Steak   4000         5
609  610  2015-12-05     Ikoyi         Chicken Bali   2000         2

         Time  Revenue  Snap
605  08:19:29     4000  2002
606  08:19:29     8000  4002
607  08:19:31    16000  4004
608  08:19:31    20000  4005
609  08:19:34     4000  2002
CHUNK BOSS
     S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
610  611  2015-12-12     Ikoyi         Meatzaa   2000         3  08:19:34
611  612  2015-12-09  Surulere        Italiano   3000         2  08:19:37
612  613  2015-12-06    Ibadan  Veggie Supreme   3000         3  08:19:38
613  614  2015-12-08     Ikoyi     BBQ Chicken   4000         1  08:19:38
614  615  2015-12-14   Gbagada   Chicken Feast   2000         4  08:19:42

     Revenue  Snap
610     6000  2003
611     6000  3002
612     9000  3003
613     4000  4001
614     8000  2004
CHUNK BOSS
     S/N        Date   Branch           Pizza Sold  Price  Quantity      Time  \
615  616  2015-12-06   Ibadan            Margarita   4000         4  08:19:50
616  617  2015-12-10   Ibadan             Italiano   3000         3  08:19:52
617  618  2015-12-14    Ikoyi       Chicken Legend   2000         4  08:19:53
618  619  2015-12-06  Gbagada  Hot Pepperoni Feast   4000         4  08:19:53
619  620  2015-12-10  Gbagada       Pepperoni Suya   3000         3  08:19:54

     Revenue  Snap
615    16000  4004
616     9000  3003
617     8000  2004
618    16000  4004
619     9000  3003
CHUNK BOSS
     S/N        Date  Branch        Pizza Sold  Price  Quantity      Time  \
620  621  2015-12-03   Lekki         Beef Suya   3000         1  08:19:56
621  622  2015-12-09   Ikoyi  BBQ Philly Steak   4000         2  08:19:56
622  623  2015-12-14   Lekki         Margarita   4000         2  08:19:57
623  624  2015-12-15  Ibadan      Chicken Bali   2000         3  08:19:58
624  625  2015-12-15  Ibadan           Meatzaa   2000         2  08:19:59

     Revenue  Snap
620     3000  3001
621     8000  4002
622     8000  4002
623     6000  2003
624     4000  2002
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
625  626  2015-12-12  Surulere  Hot Pepperoni Feast   4000         2
626  627  2015-12-12    Ibadan       Veggie Supreme   3000         4
627  628  2015-12-15     Lekki        Chicken Feast   2000         3
628  629  2015-12-08   Gbagada  Hot Pepperoni Feast   4000         1
629  630  2015-12-13  Surulere         Chicken Bali   2000         1

         Time  Revenue  Snap
625  08:20:01     8000  4002
626  08:20:01    12000  3004
627  08:20:02     6000  2003
628  08:20:03     4000  4001
629  08:20:04     2000  2001
CHUNK BOSS
     S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
630  631  2015-12-11    Lekki  Chicken Legend   2000         4  08:20:08
631  632  2015-12-05  Gbagada    Extravaganza   2000         4  08:20:09
632  633  2015-12-15   Ibadan    Chicken Suya   4000         5  08:20:13
633  634  2015-12-04   Ibadan  Chicken Legend   2000         2  08:20:14
634  635  2015-12-11    Ikoyi  Veggie Supreme   3000         5  08:20:19

     Revenue  Snap
630     8000  2004
631     8000  2004
632    20000  4005
633     4000  2002
634    15000  3005
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
635  636  2015-12-14     Ikoyi       Pepperoni Suya   3000         5
636  637  2015-12-12   Gbagada             Italiano   3000         5
637  638  2015-12-03   Gbagada     BBQ Philly Steak   4000         5
638  639  2015-12-10    Ibadan  Hot Pepperoni Feast   4000         2
639  640  2015-12-14  Surulere       Chicken Legend   2000         3

         Time  Revenue  Snap
635  08:20:20    15000  3005
636  08:20:20    15000  3005
637  08:20:20    20000  4005
638  08:20:21     8000  4002
639  08:20:22     6000  2003
CHUNK BOSS
     S/N        Date   Branch           Pizza Sold  Price  Quantity      Time  \
640  641  2015-12-04  Gbagada        Chicken Feast   2000         1  08:20:28
641  642  2015-12-12   Ibadan          BBQ Chicken   4000         2  08:20:28
642  643  2015-12-06    Ikoyi  Hot Pepperoni Feast   4000         3  08:20:29
643  644  2015-12-06   Ibadan           Hot Veggie   4000         2  08:20:29
644  645  2015-12-13    Lekki       Veggie Supreme   3000         3  08:20:31

     Revenue  Snap
640     2000  2001
641     8000  4002
642    12000  4003
643     8000  4002
644     9000  3003
CHUNK BOSS
     S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
645  646  2015-12-03     Lekki      Hot Veggie   4000         1  08:20:32
646  647  2015-12-07  Surulere  Veggie Supreme   3000         5  08:20:33
647  648  2015-12-13  Surulere    Chicken Suya   4000         2  08:20:41
648  649  2015-12-12   Gbagada   Chicken Feast   2000         2  08:20:41
649  650  2015-12-07   Gbagada         Meatzaa   2000         3  08:20:42

     Revenue  Snap
645     4000  4001
646    15000  3005
647     8000  4002
648     4000  2002
649     6000  2003
CHUNK BOSS
     S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
650  651  2015-12-03   Gbagada   Chicken Feast   2000         1  08:20:42
651  652  2015-12-12    Ibadan    Chicken Bali   2000         1  08:20:43
652  653  2015-12-03   Gbagada        Italiano   3000         2  08:20:43
653  654  2015-12-11     Lekki  Veggie Supreme   3000         1  08:20:43
654  655  2015-12-14  Surulere   Chicken Feast   2000         2  08:20:44

     Revenue  Snap
650     2000  2001
651     2000  2001
652     6000  3002
653     3000  3001
654     4000  2002
CHUNK BOSS
     S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
655  656  2015-12-13  Surulere         Beef Suya   3000         3  08:20:44
656  657  2015-12-03    Ibadan      Chicken Suya   4000         5  08:20:44
657  658  2015-12-14     Lekki         Beef Suya   3000         4  08:20:46
658  659  2015-12-12   Gbagada  BBQ Philly Steak   4000         4  08:20:47
659  660  2015-12-10    Ibadan      Chicken Suya   4000         1  08:20:47

     Revenue  Snap
655     9000  3003
656    20000  4005
657    12000  3004
658    16000  4004
659     4000  4001
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
660  661  2015-12-13   Gbagada            Margarita   4000         2
661  662  2015-12-06   Gbagada         Chicken Suya   4000         2
662  663  2015-12-13   Gbagada  Hot Pepperoni Feast   4000         5
663  664  2015-12-10  Surulere            Margarita   4000         1
664  665  2015-12-04    Ibadan  Hot Pepperoni Feast   4000         3

         Time  Revenue  Snap
660  08:20:48     8000  4002
661  08:20:54     8000  4002
662  08:20:54    20000  4005
663  08:20:54     4000  4001
664  08:20:56    12000  4003
CHUNK BOSS
     S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
665  666  2015-12-12  Surulere        Beef Suya   3000         4  08:20:56
666  667  2015-12-11  Surulere   Veggie Supreme   3000         2  08:20:57
667  668  2015-12-04    Ibadan     Chicken Suya   4000         4  08:20:57
668  669  2015-12-05     Ikoyi  Pepperoni Feast   4000         3  08:20:57
669  670  2015-12-15   Gbagada   Pepperoni Suya   3000         2  08:20:59

     Revenue  Snap
665    12000  3004
666     6000  3002
667    16000  4004
668    12000  4003
669     6000  3002
CHUNK BOSS
     S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
670  671  2015-12-03  Surulere          Meatzaa   2000         3  08:21:00
671  672  2015-12-13    Ibadan  Pepperoni Feast   4000         2  08:21:01
672  673  2015-12-06     Lekki      BBQ Chicken   4000         1  08:21:02
673  674  2015-12-03   Gbagada         Italiano   3000         5  08:21:03
674  675  2015-12-08     Lekki     Chicken Suya   4000         5  08:21:04

     Revenue  Snap
670     6000  2003
671     8000  4002
672     4000  4001
673    15000  3005
674    20000  4005

CHUNK BOSS
     S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
675  676  2015-12-14  Gbagada    Chicken Suya   4000         4  08:21:06
676  677  2015-12-15  Gbagada  Chicken Legend   2000         3  08:21:07
677  678  2015-12-15   Ibadan    Chicken Bali   2000         1  08:21:07
678  679  2015-12-07  Gbagada    Chicken Suya   4000         4  08:21:07
679  680  2015-12-12  Gbagada       Margarita   4000         4  08:21:07

     Revenue  Snap
675    16000  4004
676     6000  2003
677     2000  2001
678    16000  4004
679    16000  4004
CHUNK BOSS
     S/N        Date  Branch      Pizza Sold  Price  Quantity      Time  \
680  681  2015-12-11   Lekki  Veggie Supreme   3000         3  08:21:09
681  682  2015-12-13  Ibadan         Meatzaa   2000         2  08:21:11
682  683  2015-12-10   Ikoyi         Meatzaa   2000         1  08:21:11
683  684  2015-12-06  Ibadan         Meatzaa   2000         5  08:21:16
684  685  2015-12-10   Ikoyi         Meatzaa   2000         2  08:21:19

     Revenue  Snap
680     9000  3003
681     4000  2002
682     2000  2001
683    10000  2005
684     4000  2002
CHUNK BOSS
     S/N        Date    Branch     Pizza Sold  Price  Quantity      Time  \
685  686  2015-12-06   Gbagada     Hot Veggie   4000         4  08:21:22
686  687  2015-12-05    Ibadan   Chicken Suya   4000         2  08:21:22
687  688  2015-12-04  Surulere     Hot Veggie   4000         2  08:21:22
688  689  2015-12-13     Ikoyi     Hot Veggie   4000         3  08:21:23
689  690  2015-12-04    Ibadan  Chicken Feast   2000         5  08:21:23

     Revenue  Snap
685    16000  4004
686     8000  4002
687     8000  4002
688    12000  4003
689    10000  2005
CHUNK BOSS
     S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
690  691  2015-12-13    Ikoyi  Pepperoni Feast   4000         1  08:21:28
691  692  2015-12-03    Ikoyi       Hot Veggie   4000         5  08:21:28
692  693  2015-12-13  Gbagada    Chicken Feast   2000         1  08:21:28
693  694  2015-12-10   Ibadan        Margarita   4000         1  08:21:29
694  695  2015-12-04   Ibadan      BBQ Chicken   4000         2  08:21:31

     Revenue  Snap
690     4000  4001
691    20000  4005
692     2000  2001
693     4000  4001
694     8000  4002
CHUNK BOSS
     S/N        Date Branch           Pizza Sold  Price  Quantity      Time  \
695  696  2015-12-12  Lekki       Pepperoni Suya   3000         2  08:21:31
696  697  2015-12-15  Lekki       Chicken Legend   2000         4  08:21:31
697  698  2015-12-13  Ikoyi  Hot Pepperoni Feast   4000         3  08:21:32
698  699  2015-12-12  Lekki           Hot Veggie   4000         2  08:21:32
699  700  2015-12-10  Lekki          BBQ Chicken   4000         2  08:21:32

     Revenue  Snap
695     6000  3002
696     8000  2004
697    12000  4003
698     8000  4002
699     8000  4002
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
700  701  2015-12-11  Surulere          BBQ Chicken   4000         2
701  702  2015-12-07    Ibadan  Hot Pepperoni Feast   4000         3
702  703  2015-12-13  Surulere             Italiano   3000         5
703  704  2015-12-07     Lekki     BBQ Philly Steak   4000         5
704  705  2015-12-06     Ikoyi         Extravaganza   2000         2

         Time  Revenue  Snap
700  08:21:34     8000  4002
701  08:21:34    12000  4003
702  08:21:35    15000  3005
703  08:21:35    20000  4005
704  08:21:35     4000  2002
CHUNK BOSS
     S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
705  706  2015-12-04     Ikoyi    Veggie Supreme   3000         5  08:21:37
706  707  2015-12-09   Gbagada  BBQ Philly Steak   4000         5  08:21:37
707  708  2015-12-04   Gbagada    Chicken Legend   2000         2  08:21:37
708  709  2015-12-13     Lekki      Chicken Bali   2000         2  08:21:38
709  710  2015-12-05  Surulere  BBQ Philly Steak   4000         2  08:21:39

     Revenue  Snap
705    15000  3005
706    20000  4005
707     4000  2002
708     4000  2002
709     8000  4002
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
710  711  2015-12-14  Surulere         Chicken Suya   4000         5
711  712  2015-12-11     Lekki     BBQ Philly Steak   4000         3
712  713  2015-12-09     Lekki  Hot Pepperoni Feast   4000         2
713  714  2015-12-10     Lekki          BBQ Chicken   4000         3
714  715  2015-12-11    Ibadan      Pepperoni Feast   4000         3

         Time  Revenue  Snap
710  08:21:39    20000  4005
711  08:21:41    12000  4003
712  08:21:41     8000  4002
713  08:21:42    12000  4003
714  08:21:42    12000  4003
CHUNK BOSS
     S/N        Date   Branch           Pizza Sold  Price  Quantity      Time  \
715  716  2015-12-15    Ikoyi      Pepperoni Feast   4000         4  08:21:46
716  717  2015-12-11  Gbagada         Chicken Suya   4000         5  08:21:46
717  718  2015-12-07   Ibadan         Chicken Suya   4000         5  08:21:46
718  719  2015-12-13   Ibadan  Hot Pepperoni Feast   4000         4  08:21:47
719  720  2015-12-15    Lekki            Beef Suya   3000         1  08:21:48

     Revenue  Snap
715    16000  4004
716    20000  4005
717    20000  4005
718    16000  4004
719     3000  3001
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
720  721  2015-12-08     Ikoyi     BBQ Philly Steak   4000         1
721  722  2015-12-08  Surulere         Chicken Suya   4000         3
722  723  2015-12-15    Ibadan         Chicken Suya   4000         1
723  724  2015-12-12   Gbagada  Hot Pepperoni Feast   4000         5
724  725  2015-12-14    Ibadan           Hot Veggie   4000         3

         Time  Revenue  Snap
720  08:21:49     4000  4001
721  08:21:50    12000  4003
722  08:21:50     4000  4001
723  08:21:53    20000  4005
724  08:21:54    12000  4003
CHUNK BOSS
     S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
725  726  2015-12-11   Ibadan   Pepperoni Feast   4000         1  08:21:54
726  727  2015-12-14  Gbagada         Margarita   4000         5  08:21:54
727  728  2015-12-04    Lekki    Veggie Supreme   3000         3  08:21:55
728  729  2015-12-04    Lekki        Hot Veggie   4000         3  08:21:56
729  730  2015-12-06   Ibadan  BBQ Philly Steak   4000         5  08:21:56

     Revenue  Snap
725     4000  4001
726    20000  4005
727     9000  3003
728    12000  4003
729    20000  4005
CHUNK BOSS
     S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
730  731  2015-12-10  Gbagada    Chicken Suya   4000         4  08:21:56
731  732  2015-12-07  Gbagada      Hot Veggie   4000         4  08:21:58
732  733  2015-12-09  Gbagada  Veggie Supreme   3000         5  08:21:59
733  734  2015-12-06    Ikoyi  Pepperoni Suya   3000         3  08:22:02
734  735  2015-12-03   Ibadan    Extravaganza   2000         2  08:22:03

     Revenue  Snap
730    16000  4004
731    16000  4004
732    15000  3005
733     9000  3003
734     4000  2002
CHUNK BOSS
     S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
735  736  2015-12-03  Gbagada      Chicken Bali   2000         4  08:22:03
736  737  2015-12-11    Ikoyi    Pepperoni Suya   3000         5  08:22:04
737  738  2015-12-06    Lekki         Margarita   4000         1  08:22:07
738  739  2015-12-03    Ikoyi          Italiano   3000         4  08:22:08
739  740  2015-12-15  Gbagada  BBQ Philly Steak   4000         5  08:22:09

     Revenue  Snap
735     8000  2004
736    15000  3005
737     4000  4001
738    12000  3004
739    20000  4005
CHUNK BOSS
     S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
740  741  2015-12-03  Surulere   Veggie Supreme   3000         4  08:22:11
741  742  2015-12-12     Ikoyi          Meatzaa   2000         4  08:22:12
742  743  2015-12-09  Surulere     Extravaganza   2000         2  08:22:14
743  744  2015-12-11  Surulere        Beef Suya   3000         5  08:22:18
744  745  2015-12-04     Lekki  Pepperoni Feast   4000         4  08:22:24

     Revenue  Snap
740    12000  3004
741     8000  2004
742     4000  2002
743    15000  3005
744    16000  4004
CHUNK BOSS
     S/N        Date   Branch    Pizza Sold  Price  Quantity      Time  \
745  746  2015-12-07   Ibadan    Hot Veggie   4000         5  08:22:24
746  747  2015-12-15    Ikoyi  Chicken Suya   4000         5  08:22:25
747  748  2015-12-09  Gbagada  Chicken Suya   4000         2  08:22:29
748  749  2015-12-12  Gbagada     Margarita   4000         5  08:22:29
749  750  2015-12-13   Ibadan  Extravaganza   2000         2  08:22:30

     Revenue  Snap
745    20000  4005
746    20000  4005
747     8000  4002
748    20000  4005
749     4000  2002
CHUNK BOSS
     S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
750  751  2015-12-12   Ibadan        Margarita   4000         3  08:22:32
751  752  2015-12-09    Lekki         Italiano   3000         3  08:22:35
752  753  2015-12-11  Gbagada     Chicken Suya   4000         4  08:22:36
753  754  2015-12-05    Ikoyi        Margarita   4000         5  08:22:36
754  755  2015-12-06    Lekki  Pepperoni Feast   4000         3  08:22:37

     Revenue  Snap
750    12000  4003
751     9000  3003
752    16000  4004
753    20000  4005
754    12000  4003
CHUNK BOSS
     S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
755  756  2015-12-06  Surulere          Italiano   3000         4  08:22:38
756  757  2015-12-07     Ikoyi  BBQ Philly Steak   4000         5  08:22:40
757  758  2015-12-09     Ikoyi        Hot Veggie   4000         1  08:22:40
758  759  2015-12-05   Gbagada          Italiano   3000         5  08:22:41
759  760  2015-12-05  Surulere         Beef Suya   3000         3  08:22:41

     Revenue  Snap
755    12000  3004
756    20000  4005
757     4000  4001
758    15000  3005
759     9000  3003
CHUNK BOSS
     S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
760  761  2015-12-13   Gbagada     Chicken Suya   4000         1  08:22:45
761  762  2015-12-12  Surulere   Pepperoni Suya   3000         4  08:22:52
762  763  2015-12-07    Ibadan      BBQ Chicken   4000         5  08:22:52
763  764  2015-12-13     Ikoyi      BBQ Chicken   4000         1  08:22:54
764  765  2015-12-15   Gbagada  Pepperoni Feast   4000         5  08:22:55

     Revenue  Snap
760     4000  4001
761    12000  3004
762    20000  4005
763     4000  4001
764    20000  4005
CHUNK BOSS
     S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
765  766  2015-12-15   Ibadan        Italiano   3000         2  08:22:56
766  767  2015-12-04    Lekki    Chicken Suya   4000         1  08:22:57
767  768  2015-12-08   Ibadan       Beef Suya   3000         2  08:22:58
768  769  2015-12-11   Ibadan  Chicken Legend   2000         1  08:22:58
769  770  2015-12-13  Gbagada  Pepperoni Suya   3000         5  08:22:58

     Revenue  Snap
765     6000  3002
766     4000  4001
767     6000  3002
768     2000  2001
769    15000  3005

CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
770  771  2015-12-09   Gbagada  Hot Pepperoni Feast   4000         4
771  772  2015-12-08     Ikoyi             Italiano   3000         1
772  773  2015-12-12     Lekki     BBQ Philly Steak   4000         4
773  774  2015-12-11  Surulere        Chicken Feast   2000         1
774  775  2015-12-08     Ikoyi           Hot Veggie   4000         2

         Time  Revenue  Snap
770  08:23:00    16000  4004
771  08:23:01     3000  3001
772  08:23:02    16000  4004
773  08:23:03     2000  2001
774  08:23:03     8000  4002
CHUNK BOSS
     S/N        Date  Branch           Pizza Sold  Price  Quantity      Time  \
775  776  2015-12-07   Ikoyi          BBQ Chicken   4000         1  08:23:05
776  777  2015-12-14  Ibadan         Chicken Bali   2000         5  08:23:05
777  778  2015-12-05  Ibadan  Hot Pepperoni Feast   4000         2  08:23:08
778  779  2015-12-12   Lekki          BBQ Chicken   4000         5  08:23:10
779  780  2015-12-10  Ibadan  Hot Pepperoni Feast   4000         5  08:23:12

     Revenue  Snap
775     4000  4001
776    10000  2005
777     8000  4002
778    20000  4005
779    20000  4005
CHUNK BOSS
     S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
780  781  2015-12-03   Ibadan    Pepperoni Suya   3000         3  08:23:16
781  782  2015-12-15    Ikoyi      Chicken Bali   2000         4  08:23:17
782  783  2015-12-11  Gbagada  BBQ Philly Steak   4000         2  08:23:17
783  784  2015-12-15    Lekki    Chicken Legend   2000         5  08:23:21
784  785  2015-12-06    Lekki      Extravaganza   2000         2  08:23:21

     Revenue  Snap
780     9000  3003
781     8000  2004
782     8000  4002
783    10000  2005
784     4000  2002
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
785  786  2015-12-04    Ibadan          BBQ Chicken   4000         1
786  787  2015-12-08     Ikoyi             Italiano   3000         4
787  788  2015-12-11    Ibadan     BBQ Philly Steak   4000         1
788  789  2015-12-10  Surulere  Hot Pepperoni Feast   4000         3
789  790  2015-12-09    Ibadan       Pepperoni Suya   3000         1

         Time  Revenue  Snap
785  08:23:21     4000  4001
786  08:23:24    12000  3004
787  08:23:25     4000  4001
788  08:23:25    12000  4003
789  08:23:26     3000  3001
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
790  791  2015-12-08     Ikoyi       Veggie Supreme   3000         1
791  792  2015-12-15     Lekki      Pepperoni Feast   4000         2
792  793  2015-12-08  Surulere      Pepperoni Feast   4000         5
793  794  2015-12-15     Ikoyi              Meatzaa   2000         2
794  795  2015-12-03   Gbagada  Hot Pepperoni Feast   4000         2

         Time  Revenue  Snap
790  08:23:27     3000  3001
791  08:23:27     8000  4002
792  08:23:28    20000  4005
793  08:23:28     4000  2002
794  08:23:29     8000  4002
CHUNK BOSS
     S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
795  796  2015-12-10   Gbagada      Hot Veggie   4000         1  08:23:30
796  797  2015-12-12   Gbagada    Chicken Bali   2000         3  08:23:31
797  798  2015-12-11    Ibadan  Pepperoni Suya   3000         3  08:23:33
798  799  2015-12-05  Surulere  Pepperoni Suya   3000         5  08:23:34
799  800  2015-12-07   Gbagada    Chicken Bali   2000         3  08:23:35

     Revenue  Snap
795     4000  4001
796     6000  2003
797     9000  3003
798    15000  3005
799     6000  2003
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
800  801  2015-12-13     Ikoyi  Hot Pepperoni Feast   4000         4
801  802  2015-12-06    Ibadan          BBQ Chicken   4000         1
802  803  2015-12-04    Ibadan       Veggie Supreme   3000         4
803  804  2015-12-09    Ibadan     BBQ Philly Steak   4000         2
804  805  2015-12-05  Surulere             Italiano   3000         4

         Time  Revenue  Snap
800  08:23:41    16000  4004
801  08:23:43     4000  4001
802  08:23:43    12000  3004
803  08:23:44     8000  4002
804  08:23:44    12000  3004
CHUNK BOSS
     S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
805  806  2015-12-08    Ikoyi        Margarita   4000         1  08:23:45
806  807  2015-12-07  Gbagada   Pepperoni Suya   3000         5  08:23:48
807  808  2015-12-14   Ibadan       Hot Veggie   4000         3  08:23:50
808  809  2015-12-14    Ikoyi  Pepperoni Feast   4000         2  08:23:54
809  810  2015-12-08    Lekki       Hot Veggie   4000         2  08:23:55

     Revenue  Snap
805     4000  4001
806    15000  3005
807    12000  4003
808     8000  4002
809     8000  4002
CHUNK BOSS
     S/N        Date    Branch    Pizza Sold  Price  Quantity      Time  \
810  811  2015-12-08  Surulere       Meatzaa   2000         3  08:23:57
811  812  2015-12-04   Gbagada       Meatzaa   2000         4  08:23:57
812  813  2015-12-08   Gbagada  Extravaganza   2000         2  08:23:57
813  814  2015-12-13   Gbagada  Chicken Suya   4000         1  08:23:58
814  815  2015-12-13  Surulere     Margarita   4000         5  08:23:58

     Revenue  Snap
810     6000  2003
811     8000  2004
812     4000  2002
813     4000  4001
814    20000  4005
CHUNK BOSS
     S/N        Date   Branch    Pizza Sold  Price  Quantity      Time  \
815  816  2015-12-07    Ikoyi  Extravaganza   2000         1  08:23:59
816  817  2015-12-03  Gbagada     Margarita   4000         5  08:23:59
817  818  2015-12-04  Gbagada    Hot Veggie   4000         3  08:24:00
818  819  2015-12-07  Gbagada     Beef Suya   3000         5  08:24:01
819  820  2015-12-09  Gbagada   BBQ Chicken   4000         4  08:24:04

     Revenue  Snap
815     2000  2001
816    20000  4005
817    12000  4003
818    15000  3005
819    16000  4004
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
820  821  2015-12-08     Lekki     BBQ Philly Steak   4000         2
821  822  2015-12-15     Ikoyi  Hot Pepperoni Feast   4000         1
822  823  2015-12-08     Ikoyi           Hot Veggie   4000         2
823  824  2015-12-09  Surulere          BBQ Chicken   4000         1
824  825  2015-12-09    Ibadan         Extravaganza   2000         3

         Time  Revenue  Snap
820  08:24:07     8000  4002
821  08:24:09     4000  4001
822  08:24:09     8000  4002
823  08:24:12     4000  4001
824  08:24:12     6000  2003
CHUNK BOSS
     S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
825  826  2015-12-08  Surulere    Chicken Legend   2000         2  08:24:13
826  827  2015-12-09     Lekki     Chicken Feast   2000         5  08:24:16
827  828  2015-12-10     Lekki       BBQ Chicken   4000         2  08:24:16
828  829  2015-12-06   Gbagada    Veggie Supreme   3000         4  08:24:17
829  830  2015-12-13   Gbagada  BBQ Philly Steak   4000         4  08:24:17

     Revenue  Snap
825     4000  2002
826    10000  2005
827     8000  4002
828    12000  3004
829    16000  4004
CHUNK BOSS
     S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
830  831  2015-12-04     Lekki  Veggie Supreme   3000         4  08:24:19
831  832  2015-12-07     Lekki     BBQ Chicken   4000         5  08:24:20
832  833  2015-12-05  Surulere        Italiano   3000         4  08:24:20
833  834  2015-12-12     Ikoyi    Chicken Bali   2000         4  08:24:21
834  835  2015-12-11     Lekki      Hot Veggie   4000         5  08:24:23

     Revenue  Snap
830    12000  3004
831    20000  4005
832    12000  3004
833     8000  2004
834    20000  4005
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
835  836  2015-12-11   Gbagada            Margarita   4000         3
836  837  2015-12-10     Lekki             Italiano   3000         4
837  838  2015-12-12  Surulere       Pepperoni Suya   3000         1
838  839  2015-12-14     Ikoyi         Extravaganza   2000         1
839  840  2015-12-03     Lekki  Hot Pepperoni Feast   4000         2

         Time  Revenue  Snap
835  08:24:27    12000  4003
836  08:24:29    12000  3004
837  08:24:29     3000  3001
838  08:24:30     2000  2001
839  08:24:31     8000  4002
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
840  841  2015-12-14  Surulere         Chicken Suya   4000         2
841  842  2015-12-12    Ibadan         Chicken Suya   4000         2
842  843  2015-12-06  Surulere        Chicken Feast   2000         5
843  844  2015-12-04   Gbagada            Beef Suya   3000         4
844  845  2015-12-11    Ibadan  Hot Pepperoni Feast   4000         1

         Time  Revenue  Snap
840  08:24:31     8000  4002
841  08:24:31     8000  4002
842  08:24:32    10000  2005
843  08:24:33    12000  3004
844  08:24:36     4000  4001
CHUNK BOSS
     S/N        Date    Branch    Pizza Sold  Price  Quantity      Time  \
845  846  2015-12-04  Surulere  Chicken Bali   2000         4  08:24:36
846  847  2015-12-14    Ibadan  Chicken Bali   2000         1  08:24:38
847  848  2015-12-15    Ibadan       Meatzaa   2000         5  08:24:39
848  849  2015-12-05  Surulere       Meatzaa   2000         2  08:24:42
849  850  2015-12-11     Lekki  Chicken Suya   4000         2  08:24:43

     Revenue  Snap
845     8000  2004
846     2000  2001
847    10000  2005
848     4000  2002
849     8000  4002
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
850  851  2015-12-13  Surulere            Margarita   4000         5
851  852  2015-12-04     Ikoyi         Chicken Suya   4000         4
852  853  2015-12-10   Gbagada      Pepperoni Feast   4000         3
853  854  2015-12-09  Surulere             Italiano   3000         1
854  855  2015-12-14     Ikoyi  Hot Pepperoni Feast   4000         3

         Time  Revenue  Snap
850  08:24:43    20000  4005
851  08:24:48    16000  4004
852  08:24:49    12000  4003
853  08:24:52     3000  3001
854  08:24:53    12000  4003
CHUNK BOSS
     S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
855  856  2015-12-07  Surulere    Veggie Supreme   3000         5  08:24:54
856  857  2015-12-07    Ibadan  BBQ Philly Steak   4000         2  08:24:58
857  858  2015-12-09   Gbagada    Pepperoni Suya   3000         5  08:24:58
858  859  2015-12-10     Ikoyi          Italiano   3000         1  08:25:03
859  860  2015-12-08  Surulere          Italiano   3000         5  08:25:06

     Revenue  Snap
855    15000  3005
856     8000  4002
857    15000  3005
858     3000  3001
859    15000  3005
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
860  861  2015-12-07   Gbagada            Beef Suya   3000         3
861  862  2015-12-11   Gbagada       Pepperoni Suya   3000         1
862  863  2015-12-09     Lekki  Hot Pepperoni Feast   4000         5
863  864  2015-12-15  Surulere       Chicken Legend   2000         4
864  865  2015-12-07  Surulere     BBQ Philly Steak   4000         5

         Time  Revenue  Snap
860  08:25:07     9000  3003
861  08:25:09     3000  3001
862  08:25:11    20000  4005
863  08:25:12     8000  2004
864  08:25:13    20000  4005

CHUNK BOSS
     S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
865  866  2015-12-10   Ibadan  Pepperoni Suya   3000         2  08:25:15
866  867  2015-12-14  Gbagada         Meatzaa   2000         4  08:25:18
867  868  2015-12-05    Ikoyi    Extravaganza   2000         3  08:25:20
868  869  2015-12-06    Lekki       Margarita   4000         5  08:25:20
869  870  2015-12-14   Ibadan    Chicken Bali   2000         4  08:25:20

     Revenue  Snap
865     6000  3002
866     8000  2004
867     6000  2003
868    20000  4005
869     8000  2004
CHUNK BOSS
     S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
870  871  2015-12-10     Lekki  BBQ Philly Steak   4000         2  08:25:21
871  872  2015-12-12  Surulere      Chicken Suya   4000         3  08:25:22
872  873  2015-12-13  Surulere       BBQ Chicken   4000         5  08:25:22
873  874  2015-12-05   Gbagada         Beef Suya   3000         1  08:25:25
874  875  2015-12-07     Lekki       BBQ Chicken   4000         4  08:25:25

     Revenue  Snap
870     8000  4002
871    12000  4003
872    20000  4005
873     3000  3001
874    16000  4004
CHUNK BOSS
     S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
875  876  2015-12-11   Ibadan    Extravaganza   2000         2  08:25:25
876  877  2015-12-11    Ikoyi  Pepperoni Suya   3000         2  08:25:26
877  878  2015-12-15    Ikoyi     BBQ Chicken   4000         5  08:25:27
878  879  2015-12-13  Gbagada  Pepperoni Suya   3000         5  08:25:28
879  880  2015-12-03    Lekki  Pepperoni Suya   3000         4  08:25:29

     Revenue  Snap
875     4000  2002
876     6000  3002
877    20000  4005
878    15000  3005
879    12000  3004
CHUNK BOSS
     S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
880  881  2015-12-06    Lekki  Pepperoni Suya   3000         4  08:25:29
881  882  2015-12-04  Gbagada         Meatzaa   2000         3  08:25:30
882  883  2015-12-05    Ikoyi         Meatzaa   2000         1  08:25:30
883  884  2015-12-04    Ikoyi  Veggie Supreme   3000         4  08:25:30
884  885  2015-12-09    Lekki       Beef Suya   3000         5  08:25:32

     Revenue  Snap
880    12000  3004
881     6000  2003
882     2000  2001
883    12000  3004
884    15000  3005
CHUNK BOSS
     S/N        Date   Branch           Pizza Sold  Price  Quantity      Time  \
885  886  2015-12-12    Lekki       Chicken Legend   2000         1  08:25:32
886  887  2015-12-04  Gbagada      Pepperoni Feast   4000         1  08:25:32
887  888  2015-12-14    Ikoyi  Hot Pepperoni Feast   4000         5  08:25:38
888  889  2015-12-12    Ikoyi       Chicken Legend   2000         1  08:25:43
889  890  2015-12-13    Lekki             Italiano   3000         5  08:25:44

     Revenue  Snap
885     2000  2001
886     4000  4001
887    20000  4005
888     2000  2001
889    15000  3005
CHUNK BOSS
     S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
890  891  2015-12-14     Ikoyi         Meatzaa   2000         1  08:25:46
891  892  2015-12-09     Ikoyi        Italiano   3000         2  08:25:48
892  893  2015-12-05    Ibadan     BBQ Chicken   4000         3  08:25:48
893  894  2015-12-13     Ikoyi  Veggie Supreme   3000         2  08:25:49
894  895  2015-12-05  Surulere    Chicken Suya   4000         2  08:25:50

     Revenue  Snap
890     2000  2001
891     6000  3002
892    12000  4003
893     6000  3002
894     8000  4002
CHUNK BOSS
     S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
895  896  2015-12-14    Ibadan     Extravaganza   2000         5  08:25:53
896  897  2015-12-04    Ibadan     Extravaganza   2000         3  08:25:55
897  898  2015-12-08   Gbagada     Chicken Bali   2000         4  08:25:58
898  899  2015-12-05    Ibadan       Hot Veggie   4000         2  08:26:02
899  900  2015-12-08  Surulere  Pepperoni Feast   4000         4  08:26:03

     Revenue  Snap
895    10000  2005
896     6000  2003
897     8000  2004
898     8000  4002
899    16000  4004
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
900  901  2015-12-03  Surulere        Chicken Feast   2000         2
901  902  2015-12-04    Ibadan  Hot Pepperoni Feast   4000         1
902  903  2015-12-08     Lekki     BBQ Philly Steak   4000         1
903  904  2015-12-07  Surulere         Chicken Bali   2000         5
904  905  2015-12-05     Ikoyi       Veggie Supreme   3000         3

         Time  Revenue  Snap
900  08:26:04     4000  2002
901  08:26:05     4000  4001
902  08:26:06     4000  4001
903  08:26:10    10000  2005
904  08:26:11     9000  3003
CHUNK BOSS
     S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
905  906  2015-12-11   Gbagada   Chicken Legend   2000         3  08:26:12
906  907  2015-12-04  Surulere     Chicken Suya   4000         3  08:26:15
907  908  2015-12-12     Ikoyi     Chicken Suya   4000         3  08:26:17
908  909  2015-12-11  Surulere     Chicken Bali   2000         5  08:26:18
909  910  2015-12-07     Lekki  Pepperoni Feast   4000         4  08:26:19

     Revenue  Snap
905     6000  2003
906    12000  4003
907    12000  4003
908    10000  2005
909    16000  4004
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
910  911  2015-12-12  Surulere         Chicken Bali   2000         5
911  912  2015-12-12     Ikoyi          BBQ Chicken   4000         5
912  913  2015-12-06     Ikoyi  Hot Pepperoni Feast   4000         5
913  914  2015-12-12    Ibadan     BBQ Philly Steak   4000         2
914  915  2015-12-11   Gbagada              Meatzaa   2000         4

         Time  Revenue  Snap
910  08:26:20    10000  2005
911  08:26:20    20000  4005
912  08:26:23    20000  4005
913  08:26:23     8000  4002
914  08:26:23     8000  2004
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
915  916  2015-12-06   Gbagada       Chicken Legend   2000         1
916  917  2015-12-12   Gbagada  Hot Pepperoni Feast   4000         1
917  918  2015-12-09  Surulere         Extravaganza   2000         3
918  919  2015-12-07  Surulere         Extravaganza   2000         3
919  920  2015-12-15  Surulere        Chicken Feast   2000         3

         Time  Revenue  Snap
915  08:26:24     2000  2001
916  08:26:25     4000  4001
917  08:26:29     6000  2003
918  08:26:30     6000  2003
919  08:26:31     6000  2003
CHUNK BOSS
     S/N        Date    Branch           Pizza Sold  Price  Quantity  \
920  921  2015-12-10     Lekki       Veggie Supreme   3000         5
921  922  2015-12-04     Ikoyi        Chicken Feast   2000         1
922  923  2015-12-08  Surulere       Pepperoni Suya   3000         5
923  924  2015-12-12   Gbagada             Italiano   3000         4
924  925  2015-12-10   Gbagada  Hot Pepperoni Feast   4000         2

         Time  Revenue  Snap
920  08:26:32    15000  3005
921  08:26:32     2000  2001
922  08:26:33    15000  3005
923  08:26:34    12000  3004
924  08:26:34     8000  4002
CHUNK BOSS
     S/N        Date   Branch    Pizza Sold  Price  Quantity      Time  \
925  926  2015-12-08  Gbagada  Chicken Bali   2000         5  08:26:35
926  927  2015-12-14    Lekki     Beef Suya   3000         5  08:26:35
927  928  2015-12-12   Ibadan       Meatzaa   2000         5  08:26:36
928  929  2015-12-13   Ibadan  Chicken Suya   4000         3  08:26:36
929  930  2015-12-05   Ibadan   BBQ Chicken   4000         2  08:26:37

     Revenue  Snap
925    10000  2005
926    15000  3005
927    10000  2005
928    12000  4003
929     8000  4002
CHUNK BOSS
     S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
930  931  2015-12-08   Gbagada  Chicken Legend   2000         3  08:26:38
931  932  2015-12-11    Ibadan    Chicken Bali   2000         4  08:26:40
932  933  2015-12-15     Lekki      Hot Veggie   4000         4  08:26:42
933  934  2015-12-10     Ikoyi     BBQ Chicken   4000         1  08:26:43
934  935  2015-12-14  Surulere    Chicken Bali   2000         1  08:26:44

     Revenue  Snap
930     6000  2003
931     8000  2004
932    16000  4004
933     4000  4001
934     2000  2001
CHUNK BOSS
     S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
935  936  2015-12-05   Gbagada      Hot Veggie   4000         3  08:26:44
936  937  2015-12-06  Surulere     BBQ Chicken   4000         3  08:26:46
937  938  2015-12-03     Lekki    Chicken Suya   4000         5  08:26:50
938  939  2015-12-11   Gbagada    Chicken Suya   4000         5  08:26:51
939  940  2015-12-05   Gbagada  Chicken Legend   2000         4  08:26:51

     Revenue  Snap
935    12000  4003
936    12000  4003
937    20000  4005
938    20000  4005
939     8000  2004
CHUNK BOSS
     S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
940  941  2015-12-08     Ikoyi    Chicken Suya   4000         4  08:26:53
941  942  2015-12-07     Lekki    Extravaganza   2000         5  08:26:53
942  943  2015-12-06  Surulere    Chicken Suya   4000         3  08:26:58
943  944  2015-12-06     Ikoyi  Chicken Legend   2000         1  08:26:59
944  945  2015-12-05     Ikoyi       Beef Suya   3000         2  08:27:00

     Revenue  Snap
940    16000  4004
941    10000  2005
942    12000  4003
943     2000  2001
944     6000  3002

CHUNK BOSS
     S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
945  946  2015-12-11     Lekki          Meatzaa   2000         4  08:27:00
946  947  2015-12-10   Gbagada        Margarita   4000         5  08:27:00
947  948  2015-12-04   Gbagada  Pepperoni Feast   4000         5  08:27:01
948  949  2015-12-08  Surulere   Veggie Supreme   3000         3  08:27:02
949  950  2015-12-06  Surulere    Chicken Feast   2000         5  08:27:04

     Revenue  Snap
945     8000  2004
946    20000  4005
947    20000  4005
948     9000  3003
949    10000  2005
CHUNK BOSS
     S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
950  951  2015-12-09  Gbagada        Italiano   3000         2  08:27:04
951  952  2015-12-06   Ibadan    Extravaganza   2000         1  08:27:07
952  953  2015-12-10    Lekki       Margarita   4000         4  08:27:10
953  954  2015-12-10  Gbagada       Margarita   4000         5  08:27:12
954  955  2015-12-06    Lekki  Chicken Legend   2000         5  08:27:14

     Revenue  Snap
950     6000  3002
951     2000  2001
952    16000  4004
953    20000  4005
954    10000  2005
CHUNK BOSS
     S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
955  956  2015-12-04     Lekki       Margarita   4000         1  08:27:18
956  957  2015-12-08     Lekki  Chicken Legend   2000         1  08:27:18
957  958  2015-12-10    Ibadan     BBQ Chicken   4000         1  08:27:18
958  959  2015-12-11  Surulere      Hot Veggie   4000         4  08:27:25
959  960  2015-12-12     Ikoyi  Pepperoni Suya   3000         2  08:27:26

     Revenue  Snap
955     4000  4001
956     2000  2001
957     4000  4001
958    16000  4004
959     6000  3002
CHUNK BOSS
     S/N        Date  Branch        Pizza Sold  Price  Quantity      Time  \
960  961  2015-12-04   Lekki     Chicken Feast   2000         3  08:27:27
961  962  2015-12-15  Ibadan         Margarita   4000         1  08:27:27
962  963  2015-12-12   Lekki       BBQ Chicken   4000         2  08:27:30
963  964  2015-12-05  Ibadan  BBQ Philly Steak   4000         5  08:27:32
964  965  2015-12-03   Lekki           Meatzaa   2000         5  08:27:33

     Revenue  Snap
960     6000  2003
961     4000  4001
962     8000  4002
963    20000  4005
964    10000  2005
CHUNK BOSS
     S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
965  966  2015-12-08   Ibadan     Chicken Bali   2000         4  08:27:34
966  967  2015-12-10    Lekki     Chicken Bali   2000         3  08:27:35
967  968  2015-12-14   Ibadan          Meatzaa   2000         2  08:27:36
968  969  2015-12-06  Gbagada          Meatzaa   2000         5  08:27:39
969  970  2015-12-06    Ikoyi  Pepperoni Feast   4000         5  08:27:42

     Revenue  Snap
965     8000  2004
966     6000  2003
967     4000  2002
968    10000  2005
969    20000  4005
CHUNK BOSS
     S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
970  971  2015-12-05     Lekki      Hot Veggie   4000         4  08:27:43
971  972  2015-12-05   Gbagada    Chicken Bali   2000         5  08:27:45
972  973  2015-12-11  Surulere  Veggie Supreme   3000         2  08:27:46
973  974  2015-12-03  Surulere      Hot Veggie   4000         1  08:27:48
974  975  2015-12-12     Ikoyi       Beef Suya   3000         3  08:27:48

     Revenue  Snap
970    16000  4004
971    10000  2005
972     6000  3002
973     4000  4001
974     9000  3003
CHUNK BOSS
     S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
975  976  2015-12-14  Surulere         Meatzaa   2000         2  08:27:49
976  977  2015-12-08    Ibadan       Margarita   4000         5  08:27:56
977  978  2015-12-06     Lekki         Meatzaa   2000         1  08:27:56
978  979  2015-12-10     Ikoyi       Beef Suya   3000         1  08:27:59
979  980  2015-12-09   Gbagada  Chicken Legend   2000         4  08:27:59

     Revenue  Snap
975     4000  2002
976    20000  4005
977     2000  2001
978     3000  3001
979     8000  2004
CHUNK BOSS
     S/N        Date    Branch     Pizza Sold  Price  Quantity      Time  \
980  981  2015-12-14     Ikoyi    BBQ Chicken   4000         3  08:28:01
981  982  2015-12-13    Ibadan  Chicken Feast   2000         5  08:28:04
982  983  2015-12-04  Surulere    BBQ Chicken   4000         4  08:28:06
983  984  2015-12-15     Ikoyi   Chicken Bali   2000         3  08:28:08
984  985  2015-12-13     Lekki   Extravaganza   2000         5  08:28:09

     Revenue  Snap
980    12000  4003
981    10000  2005
982    16000  4004
983     6000  2003
984    10000  2005
CHUNK BOSS
     S/N        Date    Branch    Pizza Sold  Price  Quantity      Time  \
985  986  2015-12-15    Ibadan       Meatzaa   2000         1  08:28:10
986  987  2015-12-07     Lekki     Margarita   4000         3  08:28:12
987  988  2015-12-06     Ikoyi     Beef Suya   3000         2  08:28:13
988  989  2015-12-12  Surulere  Extravaganza   2000         3  08:28:13
989  990  2015-12-05  Surulere   BBQ Chicken   4000         3  08:28:16

     Revenue  Snap
985     2000  2001
986    12000  4003
987     6000  3002
988     6000  2003
989    12000  4003
CHUNK BOSS
     S/N        Date    Branch     Pizza Sold  Price  Quantity      Time  \
990  991  2015-12-15     Lekki      Margarita   4000         5  08:28:16
991  992  2015-12-03   Gbagada    BBQ Chicken   4000         2  08:28:20
992  993  2015-12-05  Surulere  Chicken Feast   2000         2  08:28:21
993  994  2015-12-11     Lekki      Margarita   4000         4  08:28:21
994  995  2015-12-12    Ibadan    BBQ Chicken   4000         5  08:28:22

     Revenue  Snap
990    20000  4005
991     8000  4002
992     4000  2002
993    16000  4004
994    20000  4005
CHUNK BOSS
      S/N        Date    Branch           Pizza Sold  Price  Quantity  \
995   996  2015-12-12    Ibadan       Veggie Supreme   3000         5
996   997  2015-12-13     Ikoyi        Chicken Feast   2000         4
997   998  2015-12-13  Surulere        Chicken Feast   2000         4
998   999  2015-12-06     Lekki       Pepperoni Suya   3000         2
999  1000  2015-12-06    Ibadan  Hot Pepperoni Feast   4000         5

         Time  Revenue  Snap
995  08:28:22    15000  3005
996  08:28:29     8000  2004
997  08:28:33     8000  2004
998  08:28:36     6000  3002
999  08:28:37    20000  4005
CHUNK BOSS
       S/N        Date    Branch     Pizza Sold  Price  Quantity      Time  \
1000  1001  2015-12-11    Ibadan       Italiano   3000         4  08:28:37
1001  1002  2015-12-03     Lekki      Beef Suya   3000         2  08:28:38
1002  1003  2015-12-14     Ikoyi     Hot Veggie   4000         1  08:28:38
1003  1004  2015-12-03   Gbagada  Chicken Feast   2000         4  08:28:40
1004  1005  2015-12-06  Surulere      Margarita   4000         2  08:28:41

      Revenue  Snap
1000    12000  3004
1001     6000  3002
1002     4000  4001
1003     8000  2004
1004     8000  4002
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
1005  1006  2015-12-08    Lekki     BBQ Chicken   4000         4  08:28:41
1006  1007  2015-12-15  Gbagada    Extravaganza   2000         3  08:28:42
1007  1008  2015-12-15    Ikoyi     BBQ Chicken   4000         1  08:28:42
1008  1009  2015-12-03    Ikoyi  Veggie Supreme   3000         2  08:28:43
1009  1010  2015-12-13    Ikoyi         Meatzaa   2000         1  08:28:46

      Revenue  Snap
1005    16000  4004
1006     6000  2003
1007     4000  4001
1008     6000  3002
1009     2000  2001
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1010  1011  2015-12-13     Lekki  Hot Pepperoni Feast   4000         5
1011  1012  2015-12-09  Surulere       Pepperoni Suya   3000         3
1012  1013  2015-12-04     Ikoyi           Hot Veggie   4000         4
1013  1014  2015-12-12     Ikoyi         Extravaganza   2000         2
1014  1015  2015-12-04   Gbagada     BBQ Philly Steak   4000         4

          Time  Revenue  Snap
1010  08:28:49    20000  4005
1011  08:28:49     9000  3003
1012  08:28:49    16000  4004
1013  08:28:49     4000  2002
1014  08:28:51    16000  4004
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1015  1016  2015-12-07     Ikoyi           Hot Veggie   4000         5
1016  1017  2015-12-05   Gbagada       Veggie Supreme   3000         4
1017  1018  2015-12-11    Ibadan        Chicken Feast   2000         3
1018  1019  2015-12-15    Ibadan  Hot Pepperoni Feast   4000         3
1019  1020  2015-12-06  Surulere         Extravaganza   2000         3

          Time  Revenue  Snap
1015  08:28:51    20000  4005
1016  08:28:52    12000  3004
1017  08:28:54     6000  2003
1018  08:28:55    12000  4003
1019  08:28:55     6000  2003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1020  1021  2015-12-14     Lekki  Hot Pepperoni Feast   4000         2
1021  1022  2015-12-12   Gbagada         Extravaganza   2000         2
1022  1023  2015-12-14    Ibadan         Extravaganza   2000         1
1023  1024  2015-12-12    Ibadan       Chicken Legend   2000         5
1024  1025  2015-12-15  Surulere         Chicken Bali   2000         4

          Time  Revenue  Snap
1020  08:29:02     8000  4002
1021  08:29:02     4000  2002
1022  08:29:04     2000  2001
1023  08:29:04    10000  2005
1024  08:29:07     8000  2004
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
1025  1026  2015-12-05    Ikoyi          BBQ Chicken   4000         1
1026  1027  2015-12-12    Lekki       Pepperoni Suya   3000         3
1027  1028  2015-12-11  Gbagada        Chicken Feast   2000         4
1028  1029  2015-12-10   Ibadan  Hot Pepperoni Feast   4000         5
1029  1030  2015-12-13  Gbagada         Chicken Suya   4000         3

          Time  Revenue  Snap
1025  08:29:07     4000  4001
1026  08:29:08     9000  3003
1027  08:29:08     8000  2004
1028  08:29:12    20000  4005
1029  08:29:13    12000  4003

CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1030  1031  2015-12-10   Gbagada           Meatzaa   2000         5  08:29:15
1031  1032  2015-12-11  Surulere  BBQ Philly Steak   4000         5  08:29:15
1032  1033  2015-12-11     Lekki      Chicken Bali   2000         4  08:29:18
1033  1034  2015-12-14    Ibadan      Extravaganza   2000         2  08:29:22
1034  1035  2015-12-09     Ikoyi   Pepperoni Feast   4000         3  08:29:22

      Revenue  Snap
1030    10000  2005
1031    20000  4005
1032     8000  2004
1033     4000  2002
1034    12000  4003
CHUNK BOSS
       S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
1035  1036  2015-12-12   Ibadan     Extravaganza   2000         1  08:29:24
1036  1037  2015-12-14  Gbagada  Pepperoni Feast   4000         1  08:29:25
1037  1038  2015-12-05   Ibadan   Pepperoni Suya   3000         4  08:29:27
1038  1039  2015-12-11   Ibadan        Margarita   4000         2  08:29:28
1039  1040  2015-12-04  Gbagada    Chicken Feast   2000         2  08:29:28

      Revenue  Snap
1035     2000  2001
1036     4000  4001
1037    12000  3004
1038     8000  4002
1039     4000  2002
CHUNK BOSS
       S/N        Date Branch    Pizza Sold  Price  Quantity      Time  \
1040  1041  2015-12-12  Lekki  Extravaganza   2000         1  08:29:29
1041  1042  2015-12-06  Lekki  Chicken Bali   2000         4  08:29:29
1042  1043  2015-12-05  Ikoyi    Hot Veggie   4000         2  08:29:33
1043  1044  2015-12-12  Ikoyi     Margarita   4000         3  08:29:34
1044  1045  2015-12-11  Lekki     Margarita   4000         4  08:29:35

      Revenue  Snap
1040     2000  2001
1041     8000  2004
1042     8000  4002
1043    12000  4003
1044    16000  4004
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
1045  1046  2015-12-08  Surulere  Chicken Legend   2000         1  08:29:37
1046  1047  2015-12-06     Lekki     BBQ Chicken   4000         1  08:29:41
1047  1048  2015-12-07     Lekki      Hot Veggie   4000         1  08:29:41
1048  1049  2015-12-03  Surulere       Beef Suya   3000         5  08:29:42
1049  1050  2015-12-03    Ibadan   Chicken Feast   2000         1  08:29:42

      Revenue  Snap
1045     2000  2001
1046     4000  4001
1047     4000  4001
1048    15000  3005
1049     2000  2001
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
1050  1051  2015-12-10    Lekki  Hot Pepperoni Feast   4000         5
1051  1052  2015-12-06    Lekki          BBQ Chicken   4000         5
1052  1053  2015-12-04   Ibadan       Veggie Supreme   3000         4
1053  1054  2015-12-12  Gbagada         Extravaganza   2000         1
1054  1055  2015-12-04   Ibadan        Chicken Feast   2000         4

          Time  Revenue  Snap
1050  08:29:46    20000  4005
1051  08:29:50    20000  4005
1052  08:29:54    12000  3004
1053  08:29:54     2000  2001
1054  08:29:57     8000  2004
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1055  1056  2015-12-05   Gbagada  BBQ Philly Steak   4000         5  08:29:59
1056  1057  2015-12-11   Gbagada           Meatzaa   2000         3  08:29:59
1057  1058  2015-12-07    Ibadan   Pepperoni Feast   4000         2  08:30:00
1058  1059  2015-12-06  Surulere         Margarita   4000         2  08:30:02
1059  1060  2015-12-03     Lekki    Chicken Legend   2000         2  08:30:03

      Revenue  Snap
1055    20000  4005
1056     6000  2003
1057     8000  4002
1058     8000  4002
1059     4000  2002
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1060  1061  2015-12-04     Ikoyi      Chicken Bali   2000         1  08:30:06
1061  1062  2015-12-10     Ikoyi        Hot Veggie   4000         3  08:30:09
1062  1063  2015-12-06   Gbagada        Hot Veggie   4000         2  08:30:09
1063  1064  2015-12-11  Surulere  BBQ Philly Steak   4000         2  08:30:10
1064  1065  2015-12-12    Ibadan   Pepperoni Feast   4000         5  08:30:10

      Revenue  Snap
1060     2000  2001
1061    12000  4003
1062     8000  4002
1063     8000  4002
1064    20000  4005
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
1065  1066  2015-12-04   Gbagada    Chicken Suya   4000         4  08:30:12
1066  1067  2015-12-09  Surulere     BBQ Chicken   4000         3  08:30:13
1067  1068  2015-12-15  Surulere  Chicken Legend   2000         1  08:30:15
1068  1069  2015-12-08     Ikoyi       Margarita   4000         1  08:30:15
1069  1070  2015-12-15   Gbagada    Extravaganza   2000         3  08:30:16

      Revenue  Snap
1065    16000  4004
1066    12000  4003
1067     2000  2001
1068     4000  4001
1069     6000  2003
CHUNK BOSS
       S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
1070  1071  2015-12-04   Ibadan     Extravaganza   2000         5  08:30:17
1071  1072  2015-12-03    Lekki        Margarita   4000         3  08:30:18
1072  1073  2015-12-03    Ikoyi         Italiano   3000         1  08:30:18
1073  1074  2015-12-08  Gbagada  Pepperoni Feast   4000         3  08:30:20
1074  1075  2015-12-07    Lekki      BBQ Chicken   4000         4  08:30:22

      Revenue  Snap
1070    10000  2005
1071    12000  4003
1072     3000  3001
1073    12000  4003
1074    16000  4004
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
1075  1076  2015-12-07    Ibadan    Chicken Suya   4000         4  08:30:22
1076  1077  2015-12-12  Surulere   Chicken Feast   2000         2  08:30:23
1077  1078  2015-12-06   Gbagada     BBQ Chicken   4000         5  08:30:23
1078  1079  2015-12-03     Ikoyi    Extravaganza   2000         3  08:30:24
1079  1080  2015-12-03  Surulere  Chicken Legend   2000         4  08:30:25

      Revenue  Snap
1075    16000  4004
1076     4000  2002
1077    20000  4005
1078     6000  2003
1079     8000  2004
CHUNK BOSS
       S/N        Date   Branch     Pizza Sold  Price  Quantity      Time  \
1080  1081  2015-12-03   Ibadan   Chicken Bali   2000         3  08:30:26
1081  1082  2015-12-13    Ikoyi  Chicken Feast   2000         4  08:30:27
1082  1083  2015-12-09    Ikoyi   Chicken Bali   2000         2  08:30:27
1083  1084  2015-12-10  Gbagada     Hot Veggie   4000         5  08:30:28
1084  1085  2015-12-13  Gbagada      Beef Suya   3000         5  08:30:29

      Revenue  Snap
1080     6000  2003
1081     8000  2004
1082     4000  2002
1083    20000  4005
1084    15000  3005
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1085  1086  2015-12-08    Ibadan     Chicken Feast   2000         5  08:30:31
1086  1087  2015-12-04  Surulere        Hot Veggie   4000         2  08:30:32
1087  1088  2015-12-03     Lekki  BBQ Philly Steak   4000         4  08:30:33
1088  1089  2015-12-15  Surulere         Beef Suya   3000         1  08:30:33
1089  1090  2015-12-06     Lekki         Beef Suya   3000         5  08:30:34

      Revenue  Snap
1085    10000  2005
1086     8000  4002
1087    16000  4004
1088     3000  3001
1089    15000  3005
CHUNK BOSS
       S/N        Date   Branch   Pizza Sold  Price  Quantity      Time  \
1090  1091  2015-12-04  Gbagada  BBQ Chicken   4000         1  08:30:34
1091  1092  2015-12-09    Lekki      Meatzaa   2000         2  08:30:35
1092  1093  2015-12-05    Ikoyi  BBQ Chicken   4000         3  08:30:37
1093  1094  2015-12-12    Ikoyi    Beef Suya   3000         4  08:30:38
1094  1095  2015-12-09   Ibadan      Meatzaa   2000         5  08:30:38

      Revenue  Snap
1090     4000  4001
1091     4000  2002
1092    12000  4003
1093    12000  3004
1094    10000  2005
CHUNK BOSS
       S/N        Date    Branch     Pizza Sold  Price  Quantity      Time  \
1095  1096  2015-12-09  Surulere  Chicken Feast   2000         1  08:30:38
1096  1097  2015-12-06   Gbagada   Chicken Bali   2000         3  08:30:43
1097  1098  2015-12-10     Lekki   Chicken Suya   4000         3  08:30:43
1098  1099  2015-12-05     Ikoyi       Italiano   3000         1  08:30:46
1099  1100  2015-12-07  Surulere      Beef Suya   3000         3  08:30:46

      Revenue  Snap
1095     2000  2001
1096     6000  2003
1097    12000  4003
1098     3000  3001
1099     9000  3003
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1100  1101  2015-12-07     Ikoyi  BBQ Philly Steak   4000         5  08:30:50
1101  1102  2015-12-05     Lekki   Pepperoni Feast   4000         3  08:30:51
1102  1103  2015-12-15   Gbagada      Chicken Suya   4000         3  08:30:52
1103  1104  2015-12-03  Surulere   Pepperoni Feast   4000         3  08:30:53
1104  1105  2015-12-11     Ikoyi  BBQ Philly Steak   4000         1  08:30:54

      Revenue  Snap
1100    20000  4005
1101    12000  4003
1102    12000  4003
1103    12000  4003
1104     4000  4001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
1105  1106  2015-12-06  Surulere  Veggie Supreme   3000         5  08:30:54
1106  1107  2015-12-09     Ikoyi       Margarita   4000         1  08:30:55
1107  1108  2015-12-06     Ikoyi  Chicken Legend   2000         4  08:30:58
1108  1109  2015-12-03  Surulere  Veggie Supreme   3000         5  08:30:59
1109  1110  2015-12-15  Surulere      Hot Veggie   4000         3  08:31:00

      Revenue  Snap
1105    15000  3005
1106     4000  4001
1107     8000  2004
1108    15000  3005
1109    12000  4003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1110  1111  2015-12-05  Surulere        Chicken Feast   2000         1
1111  1112  2015-12-06     Ikoyi  Hot Pepperoni Feast   4000         1
1112  1113  2015-12-09    Ibadan       Chicken Legend   2000         1
1113  1114  2015-12-08     Ikoyi            Margarita   4000         3
1114  1115  2015-12-10    Ibadan       Chicken Legend   2000         5

          Time  Revenue  Snap
1110  08:31:02     2000  2001
1111  08:31:03     4000  4001
1112  08:31:06     2000  2001
1113  08:31:07    12000  4003
1114  08:31:13    10000  2005
CHUNK BOSS
       S/N        Date  Branch      Pizza Sold  Price  Quantity      Time  \
1115  1116  2015-12-14   Ikoyi  Veggie Supreme   3000         2  08:31:13
1116  1117  2015-12-05  Ibadan       Margarita   4000         1  08:31:14
1117  1118  2015-12-06  Ibadan    Chicken Bali   2000         1  08:31:15
1118  1119  2015-12-13  Ibadan  Pepperoni Suya   3000         1  08:31:15
1119  1120  2015-12-04  Ibadan    Extravaganza   2000         4  08:31:15

      Revenue  Snap
1115     6000  3002
1116     4000  4001
1117     2000  2001
1118     3000  3001

1119     8000  2004
CHUNK BOSS
       S/N        Date   Branch    Pizza Sold  Price  Quantity      Time  \
1120  1121  2015-12-11  Gbagada      Italiano   3000         1  08:31:16
1121  1122  2015-12-10  Gbagada   BBQ Chicken   4000         3  08:31:16
1122  1123  2015-12-14    Ikoyi  Chicken Bali   2000         5  08:31:17
1123  1124  2015-12-09    Ikoyi       Meatzaa   2000         1  08:31:18
1124  1125  2015-12-15    Ikoyi  Chicken Bali   2000         1  08:31:18

      Revenue  Snap
1120     3000  3001
1121    12000  4003
1122    10000  2005
1123     2000  2001
1124     2000  2001
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1125  1126  2015-12-09   Gbagada    Chicken Legend   2000         1  08:31:19
1126  1127  2015-12-11     Lekki           Meatzaa   2000         3  08:31:19
1127  1128  2015-12-11  Surulere  BBQ Philly Steak   4000         5  08:31:19
1128  1129  2015-12-07    Ibadan      Chicken Suya   4000         3  08:31:19
1129  1130  2015-12-07     Lekki         Margarita   4000         3  08:31:21

      Revenue  Snap
1125     2000  2001
1126     6000  2003
1127    20000  4005
1128    12000  4003
1129    12000  4003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1130  1131  2015-12-15   Gbagada        Chicken Feast   2000         4
1131  1132  2015-12-09    Ibadan        Chicken Feast   2000         3
1132  1133  2015-12-04     Lekki  Hot Pepperoni Feast   4000         1
1133  1134  2015-12-14  Surulere             Italiano   3000         2
1134  1135  2015-12-09  Surulere       Veggie Supreme   3000         4

          Time  Revenue  Snap
1130  08:31:23     8000  2004
1131  08:31:23     6000  2003
1132  08:31:25     4000  4001
1133  08:31:25     6000  3002
1134  08:31:27    12000  3004
CHUNK BOSS
       S/N        Date  Branch      Pizza Sold  Price  Quantity      Time  \
1135  1136  2015-12-13  Ibadan    Chicken Bali   2000         1  08:31:27
1136  1137  2015-12-08  Ibadan        Italiano   3000         2  08:31:28
1137  1138  2015-12-15  Ibadan     BBQ Chicken   4000         3  08:31:29
1138  1139  2015-12-08  Ibadan   Chicken Feast   2000         3  08:31:29
1139  1140  2015-12-09   Lekki  Pepperoni Suya   3000         1  08:31:29

      Revenue  Snap
1135     2000  2001
1136     6000  3002
1137    12000  4003
1138     6000  2003
1139     3000  3001
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
1140  1141  2015-12-07  Gbagada        Chicken Feast   2000         4
1141  1142  2015-12-15    Lekki              Meatzaa   2000         4
1142  1143  2015-12-03    Lekki             Italiano   3000         1
1143  1144  2015-12-05  Gbagada  Hot Pepperoni Feast   4000         3
1144  1145  2015-12-11   Ibadan      Pepperoni Feast   4000         2

          Time  Revenue  Snap
1140  08:31:35     8000  2004
1141  08:31:35     8000  2004
1142  08:31:37     3000  3001
1143  08:31:37    12000  4003
1144  08:31:38     8000  4002
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1145  1146  2015-12-04     Ikoyi    Chicken Legend   2000         2  08:31:41
1146  1147  2015-12-03     Ikoyi       BBQ Chicken   4000         2  08:31:44
1147  1148  2015-12-10     Lekki  BBQ Philly Steak   4000         2  08:31:44
1148  1149  2015-12-06  Surulere      Extravaganza   2000         4  08:31:44
1149  1150  2015-12-12   Gbagada    Pepperoni Suya   3000         1  08:31:44

      Revenue  Snap
1145     4000  2002
1146     8000  4002
1147     8000  4002
1148     8000  2004
1149     3000  3001
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1150  1151  2015-12-06    Ibadan            Margarita   4000         1
1151  1152  2015-12-04     Lekki  Hot Pepperoni Feast   4000         2
1152  1153  2015-12-12    Ibadan         Extravaganza   2000         5
1153  1154  2015-12-09  Surulere          BBQ Chicken   4000         4
1154  1155  2015-12-11    Ibadan            Beef Suya   3000         5

          Time  Revenue  Snap
1150  08:31:49     4000  4001
1151  08:31:49     8000  4002
1152  08:31:50    10000  2005
1153  08:31:51    16000  4004
1154  08:31:52    15000  3005
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
1155  1156  2015-12-10    Ikoyi           Meatzaa   2000         4  08:31:52
1156  1157  2015-12-09    Lekki    Pepperoni Suya   3000         4  08:31:53
1157  1158  2015-12-11    Lekki    Pepperoni Suya   3000         1  08:31:54
1158  1159  2015-12-07  Gbagada  BBQ Philly Steak   4000         5  08:31:57
1159  1160  2015-12-10    Ikoyi         Beef Suya   3000         1  08:32:01

      Revenue  Snap
1155     8000  2004
1156    12000  3004
1157     3000  3001
1158    20000  4005
1159     3000  3001
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
1160  1161  2015-12-12     Lekki         Italiano   3000         3  08:32:02
1161  1162  2015-12-09     Lekki  Pepperoni Feast   4000         5  08:32:04
1162  1163  2015-12-14     Ikoyi   Veggie Supreme   3000         2  08:32:06
1163  1164  2015-12-06     Lekki          Meatzaa   2000         1  08:32:07
1164  1165  2015-12-08  Surulere        Margarita   4000         4  08:32:08

      Revenue  Snap
1160     9000  3003
1161    20000  4005
1162     6000  3002
1163     2000  2001
1164    16000  4004
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1165  1166  2015-12-07  Surulere   Pepperoni Feast   4000         4  08:32:09
1166  1167  2015-12-11     Ikoyi     Chicken Feast   2000         2  08:32:12
1167  1168  2015-12-12  Surulere  BBQ Philly Steak   4000         4  08:32:15
1168  1169  2015-12-13     Ikoyi    Veggie Supreme   3000         1  08:32:15
1169  1170  2015-12-10     Lekki    Veggie Supreme   3000         5  08:32:16

      Revenue  Snap
1165    16000  4004
1166     4000  2002
1167    16000  4004
1168     3000  3001
1169    15000  3005
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
1170  1171  2015-12-05  Gbagada    Veggie Supreme   3000         4  08:32:16
1171  1172  2015-12-03  Gbagada      Chicken Bali   2000         2  08:32:17
1172  1173  2015-12-07    Ikoyi          Italiano   3000         3  08:32:18
1173  1174  2015-12-13    Ikoyi     Chicken Feast   2000         2  08:32:21
1174  1175  2015-12-05   Ibadan  BBQ Philly Steak   4000         3  08:32:24

      Revenue  Snap
1170    12000  3004
1171     4000  2002
1172     9000  3003
1173     4000  2002
1174    12000  4003
CHUNK BOSS
       S/N        Date    Branch     Pizza Sold  Price  Quantity      Time  \
1175  1176  2015-12-14     Ikoyi   Chicken Bali   2000         3  08:32:30
1176  1177  2015-12-11   Gbagada   Extravaganza   2000         1  08:32:30
1177  1178  2015-12-13    Ibadan  Chicken Feast   2000         4  08:32:31
1178  1179  2015-12-07   Gbagada   Chicken Bali   2000         3  08:32:31
1179  1180  2015-12-05  Surulere     Hot Veggie   4000         4  08:32:34

      Revenue  Snap
1175     6000  2003
1176     2000  2001
1177     8000  2004
1178     6000  2003
1179    16000  4004
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
1180  1181  2015-12-05  Gbagada           Meatzaa   2000         1  08:32:34
1181  1182  2015-12-10    Lekki      Chicken Suya   4000         5  08:32:36
1182  1183  2015-12-03   Ibadan    Chicken Legend   2000         2  08:32:38
1183  1184  2015-12-10   Ibadan      Chicken Suya   4000         3  08:32:38
1184  1185  2015-12-07    Ikoyi  BBQ Philly Steak   4000         5  08:32:39

      Revenue  Snap
1180     2000  2001
1181    20000  4005
1182     4000  2002
1183    12000  4003
1184    20000  4005
CHUNK BOSS
       S/N        Date  Branch       Pizza Sold  Price  Quantity      Time  \
1185  1186  2015-12-08   Ikoyi  Pepperoni Feast   4000         2  08:32:40
1186  1187  2015-12-05   Ikoyi     Chicken Suya   4000         4  08:32:42
1187  1188  2015-12-12   Ikoyi       Hot Veggie   4000         5  08:32:42
1188  1189  2015-12-03  Ibadan        Beef Suya   3000         2  08:32:44
1189  1190  2015-12-05   Lekki     Extravaganza   2000         5  08:32:44

      Revenue  Snap
1185     8000  4002
1186    16000  4004
1187    20000  4005
1188     6000  3002
1189    10000  2005
CHUNK BOSS
       S/N        Date   Branch    Pizza Sold  Price  Quantity      Time  \
1190  1191  2015-12-14  Gbagada      Italiano   3000         4  08:32:46
1191  1192  2015-12-04    Lekki   BBQ Chicken   4000         2  08:32:47
1192  1193  2015-12-07    Ikoyi      Italiano   3000         4  08:32:48
1193  1194  2015-12-05  Gbagada       Meatzaa   2000         2  08:32:49
1194  1195  2015-12-12    Lekki  Chicken Suya   4000         5  08:32:56

      Revenue  Snap
1190    12000  3004
1191     8000  4002
1192    12000  3004
1193     4000  2002
1194    20000  4005
CHUNK BOSS
       S/N        Date  Branch        Pizza Sold  Price  Quantity      Time  \
1195  1196  2015-12-12   Ikoyi    Veggie Supreme   3000         5  08:32:58
1196  1197  2015-12-06   Lekki        Hot Veggie   4000         2  08:32:58
1197  1198  2015-12-13  Ibadan     Chicken Feast   2000         2  08:32:59
1198  1199  2015-12-14   Lekki  BBQ Philly Steak   4000         2  08:33:00
1199  1200  2015-12-05   Ikoyi      Chicken Bali   2000         5  08:33:02

      Revenue  Snap
1195    15000  3005
1196     8000  4002
1197     4000  2002
1198     8000  4002
1199    10000  2005
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
1200  1201  2015-12-03     Lekki        Margarita   4000         3  08:33:04
1201  1202  2015-12-11   Gbagada    Chicken Feast   2000         5  08:33:05
1202  1203  2015-12-05   Gbagada        Beef Suya   3000         3  08:33:05
1203  1204  2015-12-06  Surulere   Veggie Supreme   3000         5  08:33:07
1204  1205  2015-12-13     Lekki  Pepperoni Feast   4000         4  08:33:08

      Revenue  Snap
1200    12000  4003
1201    10000  2005
1202     9000  3003
1203    15000  3005
1204    16000  4004
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
1205  1206  2015-12-10     Ikoyi         Italiano   3000         4  08:33:11
1206  1207  2015-12-03     Ikoyi  Pepperoni Feast   4000         3  08:33:11
1207  1208  2015-12-08   Gbagada     Chicken Bali   2000         3  08:33:13
1208  1209  2015-12-15  Surulere        Margarita   4000         2  08:33:13
1209  1210  2015-12-06     Lekki         Italiano   3000         3  08:33:14

      Revenue  Snap
1205    12000  3004
1206    12000  4003
1207     6000  2003
1208     8000  4002
1209     9000  3003

CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1210  1211  2015-12-14  Surulere  Hot Pepperoni Feast   4000         5
1211  1212  2015-12-12     Ikoyi         Chicken Suya   4000         5
1212  1213  2015-12-10     Lekki  Hot Pepperoni Feast   4000         5
1213  1214  2015-12-10   Gbagada     BBQ Philly Steak   4000         3
1214  1215  2015-12-06     Ikoyi         Chicken Bali   2000         2

          Time  Revenue  Snap
1210  08:33:16    20000  4005
1211  08:33:16    20000  4005
1212  08:33:17    20000  4005
1213  08:33:17    12000  4003
1214  08:33:25     4000  2002
CHUNK BOSS
       S/N        Date  Branch       Pizza Sold  Price  Quantity      Time  \
1215  1216  2015-12-12  Ibadan    Chicken Feast   2000         3  08:33:26
1216  1217  2015-12-04   Lekki  Pepperoni Feast   4000         2  08:33:30
1217  1218  2015-12-03  Ibadan      BBQ Chicken   4000         2  08:33:32
1218  1219  2015-12-14   Ikoyi     Chicken Suya   4000         1  08:33:32
1219  1220  2015-12-04  Ibadan       Hot Veggie   4000         2  08:33:39

      Revenue  Snap
1215     6000  2003
1216     8000  4002
1217     8000  4002
1218     4000  4001
1219     8000  4002
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
1220  1221  2015-12-04  Surulere   Pepperoni Suya   3000         2  08:33:40
1221  1222  2015-12-08   Gbagada   Veggie Supreme   3000         5  08:33:44
1222  1223  2015-12-07  Surulere  Pepperoni Feast   4000         2  08:33:45
1223  1224  2015-12-07     Lekki     Extravaganza   2000         1  08:33:45
1224  1225  2015-12-13   Gbagada     Extravaganza   2000         1  08:33:46

      Revenue  Snap
1220     6000  3002
1221    15000  3005
1222     8000  4002
1223     2000  2001
1224     2000  2001
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
1225  1226  2015-12-10  Gbagada    Veggie Supreme   3000         2  08:33:47
1226  1227  2015-12-05    Ikoyi  BBQ Philly Steak   4000         1  08:33:48
1227  1228  2015-12-09    Lekki      Chicken Suya   4000         1  08:33:52
1228  1229  2015-12-12    Ikoyi          Italiano   3000         4  08:33:53
1229  1230  2015-12-09  Gbagada    Chicken Legend   2000         5  08:33:53

      Revenue  Snap
1225     6000  3002
1226     4000  4001
1227     4000  4001
1228    12000  3004
1229    10000  2005
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
1230  1231  2015-12-10  Surulere   Chicken Feast   2000         2  08:33:56
1231  1232  2015-12-09     Lekki        Italiano   3000         2  08:34:02
1232  1233  2015-12-03     Ikoyi   Chicken Feast   2000         2  08:34:03
1233  1234  2015-12-08  Surulere  Pepperoni Suya   3000         2  08:34:03
1234  1235  2015-12-11     Ikoyi    Chicken Bali   2000         1  08:34:04

      Revenue  Snap
1230     4000  2002
1231     6000  3002
1232     4000  2002
1233     6000  3002
1234     2000  2001
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
1235  1236  2015-12-12    Lekki             Italiano   3000         4
1236  1237  2015-12-06    Lekki         Extravaganza   2000         4
1237  1238  2015-12-13    Lekki         Chicken Suya   4000         2
1238  1239  2015-12-03  Gbagada             Italiano   3000         3
1239  1240  2015-12-15   Ibadan  Hot Pepperoni Feast   4000         3

          Time  Revenue  Snap
1235  08:34:07    12000  3004
1236  08:34:08     8000  2004
1237  08:34:08     8000  4002
1238  08:34:09     9000  3003
1239  08:34:14    12000  4003
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
1240  1241  2015-12-15   Gbagada    Chicken Bali   2000         1  08:34:17
1241  1242  2015-12-14  Surulere    Chicken Bali   2000         1  08:34:17
1242  1243  2015-12-03  Surulere   Chicken Feast   2000         3  08:34:21
1243  1244  2015-12-15     Lekki     BBQ Chicken   4000         4  08:34:22
1244  1245  2015-12-13     Lekki  Pepperoni Suya   3000         5  08:34:24

      Revenue  Snap
1240     2000  2001
1241     2000  2001
1242     6000  2003
1243    16000  4004
1244    15000  3005
CHUNK BOSS
       S/N        Date    Branch    Pizza Sold  Price  Quantity      Time  \
1245  1246  2015-12-06  Surulere      Italiano   3000         3  08:34:24
1246  1247  2015-12-05     Ikoyi     Beef Suya   3000         5  08:34:25
1247  1248  2015-12-05     Ikoyi  Extravaganza   2000         5  08:34:28
1248  1249  2015-12-03    Ibadan  Chicken Suya   4000         3  08:34:28
1249  1250  2015-12-04   Gbagada     Beef Suya   3000         4  08:34:29

      Revenue  Snap
1245     9000  3003
1246    15000  3005
1247    10000  2005
1248    12000  4003
1249    12000  3004
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
1250  1251  2015-12-09  Surulere  Pepperoni Feast   4000         3  08:34:29
1251  1252  2015-12-10   Gbagada        Margarita   4000         2  08:34:32
1252  1253  2015-12-09    Ibadan     Extravaganza   2000         4  08:34:33
1253  1254  2015-12-15   Gbagada   Pepperoni Suya   3000         4  08:34:33
1254  1255  2015-12-14   Gbagada          Meatzaa   2000         1  08:34:34

      Revenue  Snap
1250    12000  4003
1251     8000  4002
1252     8000  2004
1253    12000  3004
1254     2000  2001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
1255  1256  2015-12-12     Lekki  Veggie Supreme   3000         4  08:34:35
1256  1257  2015-12-05   Gbagada       Margarita   4000         4  08:34:37
1257  1258  2015-12-11  Surulere  Pepperoni Suya   3000         2  08:34:37
1258  1259  2015-12-10     Ikoyi  Chicken Legend   2000         1  08:34:42
1259  1260  2015-12-15     Lekki      Hot Veggie   4000         2  08:34:43

      Revenue  Snap
1255    12000  3004
1256    16000  4004
1257     6000  3002
1258     2000  2001
1259     8000  4002
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
1260  1261  2015-12-08  Gbagada  Veggie Supreme   3000         4  08:34:45
1261  1262  2015-12-14   Ibadan    Chicken Suya   4000         4  08:34:46
1262  1263  2015-12-13    Lekki  Pepperoni Suya   3000         3  08:34:47
1263  1264  2015-12-11    Ikoyi      Hot Veggie   4000         2  08:34:48
1264  1265  2015-12-04    Lekki  Chicken Legend   2000         1  08:34:48

      Revenue  Snap
1260    12000  3004
1261    16000  4004
1262     9000  3003
1263     8000  4002
1264     2000  2001
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
1265  1266  2015-12-12  Gbagada      Hot Veggie   4000         5  08:34:49
1266  1267  2015-12-14   Ibadan    Chicken Suya   4000         3  08:34:49
1267  1268  2015-12-12    Lekki  Chicken Legend   2000         3  08:34:56
1268  1269  2015-12-08    Ikoyi    Chicken Bali   2000         2  08:34:57
1269  1270  2015-12-10    Ikoyi      Hot Veggie   4000         3  08:34:59

      Revenue  Snap
1265    20000  4005
1266    12000  4003
1267     6000  2003
1268     4000  2002
1269    12000  4003
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
1270  1271  2015-12-06     Ikoyi  Pepperoni Feast   4000         4  08:35:00
1271  1272  2015-12-07     Lekki         Italiano   3000         2  08:35:01
1272  1273  2015-12-11     Lekki     Chicken Bali   2000         3  08:35:03
1273  1274  2015-12-10  Surulere   Veggie Supreme   3000         3  08:35:04
1274  1275  2015-12-09   Gbagada   Chicken Legend   2000         4  08:35:07

      Revenue  Snap
1270    16000  4004
1271     6000  3002
1272     6000  2003
1273     9000  3003
1274     8000  2004
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
1275  1276  2015-12-11   Gbagada  Chicken Legend   2000         4  08:35:09
1276  1277  2015-12-05     Lekki       Margarita   4000         4  08:35:10
1277  1278  2015-12-14  Surulere     BBQ Chicken   4000         1  08:35:12
1278  1279  2015-12-07  Surulere         Meatzaa   2000         2  08:35:13
1279  1280  2015-12-12     Lekki  Pepperoni Suya   3000         4  08:35:14

      Revenue  Snap
1275     8000  2004
1276    16000  4004
1277     4000  4001
1278     4000  2002
1279    12000  3004
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
1280  1281  2015-12-09   Gbagada     BBQ Chicken   4000         2  08:35:15
1281  1282  2015-12-05    Ibadan     BBQ Chicken   4000         4  08:35:17
1282  1283  2015-12-09     Lekki      Hot Veggie   4000         1  08:35:19
1283  1284  2015-12-14   Gbagada  Pepperoni Suya   3000         1  08:35:19
1284  1285  2015-12-05  Surulere  Pepperoni Suya   3000         1  08:35:19

      Revenue  Snap
1280     8000  4002
1281    16000  4004
1282     4000  4001
1283     3000  3001
1284     3000  3001
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
1285  1286  2015-12-14  Gbagada      Chicken Bali   2000         2  08:35:21
1286  1287  2015-12-13  Gbagada           Meatzaa   2000         1  08:35:21
1287  1288  2015-12-11  Gbagada          Italiano   3000         2  08:35:26
1288  1289  2015-12-05    Lekki  BBQ Philly Steak   4000         3  08:35:26
1289  1290  2015-12-15    Ikoyi          Italiano   3000         4  08:35:27

      Revenue  Snap
1285     4000  2002
1286     2000  2001
1287     6000  3002
1288    12000  4003
1289    12000  3004
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
1290  1291  2015-12-14     Ikoyi       Hot Veggie   4000         4  08:35:30
1291  1292  2015-12-07   Gbagada        Beef Suya   3000         2  08:35:31
1292  1293  2015-12-10    Ibadan  Pepperoni Feast   4000         1  08:35:31
1293  1294  2015-12-12     Ikoyi         Italiano   3000         1  08:35:35
1294  1295  2015-12-08  Surulere    Chicken Feast   2000         4  08:35:36

      Revenue  Snap
1290    16000  4004
1291     6000  3002
1292     4000  4001
1293     3000  3001
1294     8000  2004
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1295  1296  2015-12-15     Lekki      Pepperoni Feast   4000         1
1296  1297  2015-12-03   Gbagada     BBQ Philly Steak   4000         1
1297  1298  2015-12-12   Gbagada  Hot Pepperoni Feast   4000         5
1298  1299  2015-12-08  Surulere            Beef Suya   3000         3
1299  1300  2015-12-09     Lekki        Chicken Feast   2000         1

          Time  Revenue  Snap
1295  08:35:36     4000  4001
1296  08:35:36     4000  4001
1297  08:35:37    20000  4005
1298  08:35:38     9000  3003
1299  08:35:39     2000  2001

CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
1300  1301  2015-12-10    Ikoyi         Meatzaa   2000         2  08:35:43
1301  1302  2015-12-13  Gbagada        Italiano   3000         1  08:35:44
1302  1303  2015-12-10    Lekki    Chicken Bali   2000         5  08:35:44
1303  1304  2015-12-11    Ikoyi    Chicken Suya   4000         5  08:35:48
1304  1305  2015-12-14  Gbagada  Veggie Supreme   3000         5  08:35:50

      Revenue  Snap
1300     4000  2002
1301     3000  3001
1302    10000  2005
1303    20000  4005
1304    15000  3005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1305  1306  2015-12-12  Surulere          BBQ Chicken   4000         2
1306  1307  2015-12-13     Lekki      Pepperoni Feast   4000         2
1307  1308  2015-12-06  Surulere              Meatzaa   2000         1
1308  1309  2015-12-12  Surulere             Italiano   3000         2
1309  1310  2015-12-11     Lekki  Hot Pepperoni Feast   4000         1

          Time  Revenue  Snap
1305  08:35:51     8000  4002
1306  08:35:53     8000  4002
1307  08:35:54     2000  2001
1308  08:35:56     6000  3002
1309  08:35:56     4000  4001
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
1310  1311  2015-12-11  Surulere          Meatzaa   2000         2  08:35:57
1311  1312  2015-12-10     Ikoyi     Extravaganza   2000         2  08:35:58
1312  1313  2015-12-10   Gbagada  Pepperoni Feast   4000         3  08:35:58
1313  1314  2015-12-12  Surulere  Pepperoni Feast   4000         1  08:35:58
1314  1315  2015-12-03  Surulere       Hot Veggie   4000         1  08:35:59

      Revenue  Snap
1310     4000  2002
1311     4000  2002
1312    12000  4003
1313     4000  4001
1314     4000  4001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
1315  1316  2015-12-15  Surulere       Beef Suya   3000         3  08:35:59
1316  1317  2015-12-08     Ikoyi     BBQ Chicken   4000         2  08:36:00
1317  1318  2015-12-08    Ibadan  Chicken Legend   2000         1  08:36:01
1318  1319  2015-12-10    Ibadan       Beef Suya   3000         3  08:36:03
1319  1320  2015-12-07     Ikoyi  Veggie Supreme   3000         1  08:36:05

      Revenue  Snap
1315     9000  3003
1316     8000  4002
1317     2000  2001
1318     9000  3003
1319     3000  3001
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1320  1321  2015-12-09     Lekki        Chicken Feast   2000         3
1321  1322  2015-12-08  Surulere              Meatzaa   2000         5
1322  1323  2015-12-04   Gbagada  Hot Pepperoni Feast   4000         5
1323  1324  2015-12-08   Gbagada       Chicken Legend   2000         3
1324  1325  2015-12-12  Surulere       Chicken Legend   2000         5

          Time  Revenue  Snap
1320  08:36:06     6000  2003
1321  08:36:09    10000  2005
1322  08:36:11    20000  4005
1323  08:36:11     6000  2003
1324  08:36:13    10000  2005
CHUNK BOSS
       S/N        Date  Branch           Pizza Sold  Price  Quantity  \
1325  1326  2015-12-13   Lekki            Margarita   4000         3
1326  1327  2015-12-03  Ibadan             Italiano   3000         1
1327  1328  2015-12-13  Ibadan  Hot Pepperoni Feast   4000         5
1328  1329  2015-12-03   Lekki       Pepperoni Suya   3000         2
1329  1330  2015-12-12   Lekki           Hot Veggie   4000         4

          Time  Revenue  Snap
1325  08:36:14    12000  4003
1326  08:36:16     3000  3001
1327  08:36:17    20000  4005
1328  08:36:17     6000  3002
1329  08:36:19    16000  4004
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1330  1331  2015-12-12   Gbagada       BBQ Chicken   4000         3  08:36:20
1331  1332  2015-12-05  Surulere  BBQ Philly Steak   4000         4  08:36:21
1332  1333  2015-12-09    Ibadan  BBQ Philly Steak   4000         2  08:36:22
1333  1334  2015-12-12     Lekki    Veggie Supreme   3000         1  08:36:23
1334  1335  2015-12-06   Gbagada         Beef Suya   3000         5  08:36:23

      Revenue  Snap
1330    12000  4003
1331    16000  4004
1332     8000  4002
1333     3000  3001
1334    15000  3005
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1335  1336  2015-12-13   Gbagada        Hot Veggie   4000         5  08:36:24
1336  1337  2015-12-08  Surulere      Chicken Bali   2000         4  08:36:25
1337  1338  2015-12-06   Gbagada    Veggie Supreme   3000         5  08:36:26
1338  1339  2015-12-04   Gbagada  BBQ Philly Steak   4000         4  08:36:26
1339  1340  2015-12-09    Ibadan  BBQ Philly Steak   4000         3  08:36:27

      Revenue  Snap
1335    20000  4005
1336     8000  2004
1337    15000  3005
1338    16000  4004
1339    12000  4003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1340  1341  2015-12-07     Ikoyi     BBQ Philly Steak   4000         3
1341  1342  2015-12-08  Surulere             Italiano   3000         5
1342  1343  2015-12-09     Lekki  Hot Pepperoni Feast   4000         5
1343  1344  2015-12-11     Lekki     BBQ Philly Steak   4000         5
1344  1345  2015-12-07    Ibadan              Meatzaa   2000         4

          Time  Revenue  Snap
1340  08:36:27    12000  4003
1341  08:36:27    15000  3005
1342  08:36:29    20000  4005
1343  08:36:29    20000  4005
1344  08:36:29     8000  2004
CHUNK BOSS
       S/N        Date    Branch     Pizza Sold  Price  Quantity      Time  \
1345  1346  2015-12-13   Gbagada       Italiano   3000         3  08:36:32
1346  1347  2015-12-05   Gbagada    BBQ Chicken   4000         3  08:36:34
1347  1348  2015-12-14  Surulere   Chicken Suya   4000         5  08:36:34
1348  1349  2015-12-14   Gbagada  Chicken Feast   2000         1  08:36:34
1349  1350  2015-12-08   Gbagada   Chicken Suya   4000         2  08:36:35

      Revenue  Snap
1345     9000  3003
1346    12000  4003
1347    20000  4005
1348     2000  2001
1349     8000  4002
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
1350  1351  2015-12-04  Surulere        Beef Suya   3000         1  08:36:36
1351  1352  2015-12-07    Ibadan      BBQ Chicken   4000         5  08:36:36
1352  1353  2015-12-12     Lekki  Pepperoni Feast   4000         5  08:36:37
1353  1354  2015-12-15   Gbagada        Margarita   4000         2  08:36:41
1354  1355  2015-12-10   Gbagada    Chicken Feast   2000         4  08:36:41

      Revenue  Snap
1350     3000  3001
1351    20000  4005
1352    20000  4005
1353     8000  4002
1354     8000  2004
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
1355  1356  2015-12-09     Lekki  Chicken Legend   2000         5  08:36:44
1356  1357  2015-12-11     Ikoyi    Chicken Bali   2000         1  08:36:45
1357  1358  2015-12-03  Surulere       Margarita   4000         3  08:36:55
1358  1359  2015-12-07    Ibadan   Chicken Feast   2000         4  08:36:56
1359  1360  2015-12-10   Gbagada       Beef Suya   3000         2  08:36:56

      Revenue  Snap
1355    10000  2005
1356     2000  2001
1357    12000  4003
1358     8000  2004
1359     6000  3002
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1360  1361  2015-12-11    Ibadan             Italiano   3000         4
1361  1362  2015-12-07  Surulere         Extravaganza   2000         4
1362  1363  2015-12-12    Ibadan            Beef Suya   3000         4
1363  1364  2015-12-04   Gbagada         Chicken Suya   4000         1
1364  1365  2015-12-08  Surulere  Hot Pepperoni Feast   4000         5

          Time  Revenue  Snap
1360  08:37:00    12000  3004
1361  08:37:01     8000  2004
1362  08:37:03    12000  3004
1363  08:37:03     4000  4001
1364  08:37:04    20000  4005
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
1365  1366  2015-12-08    Ibadan      Hot Veggie   4000         2  08:37:05
1366  1367  2015-12-08   Gbagada   Chicken Feast   2000         3  08:37:07
1367  1368  2015-12-12  Surulere    Chicken Bali   2000         2  08:37:09
1368  1369  2015-12-05  Surulere  Chicken Legend   2000         2  08:37:09
1369  1370  2015-12-13     Ikoyi       Beef Suya   3000         3  08:37:10

      Revenue  Snap
1365     8000  4002
1366     6000  2003
1367     4000  2002
1368     4000  2002
1369     9000  3003
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
1370  1371  2015-12-10    Lekki  Veggie Supreme   3000         3  08:37:12
1371  1372  2015-12-12    Ikoyi       Margarita   4000         1  08:37:16
1372  1373  2015-12-13  Gbagada  Pepperoni Suya   3000         3  08:37:18
1373  1374  2015-12-11   Ibadan         Meatzaa   2000         3  08:37:19
1374  1375  2015-12-03  Gbagada    Chicken Suya   4000         2  08:37:22

      Revenue  Snap
1370     9000  3003
1371     4000  4001
1372     9000  3003
1373     6000  2003
1374     8000  4002
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1375  1376  2015-12-06  Surulere    Chicken Legend   2000         1  08:37:23
1376  1377  2015-12-09  Surulere           Meatzaa   2000         3  08:37:24
1377  1378  2015-12-10     Lekki   Pepperoni Feast   4000         5  08:37:24
1378  1379  2015-12-13     Lekki  BBQ Philly Steak   4000         1  08:37:24
1379  1380  2015-12-04     Ikoyi         Margarita   4000         1  08:37:25

      Revenue  Snap
1375     2000  2001
1376     6000  2003
1377    20000  4005
1378     4000  4001
1379     4000  4001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
1380  1381  2015-12-09     Ikoyi         Meatzaa   2000         4  08:37:28
1381  1382  2015-12-04    Ibadan    Chicken Suya   4000         3  08:37:28
1382  1383  2015-12-03  Surulere         Meatzaa   2000         2  08:37:28
1383  1384  2015-12-12  Surulere  Pepperoni Suya   3000         1  08:37:32
1384  1385  2015-12-12  Surulere  Veggie Supreme   3000         3  08:37:32

      Revenue  Snap
1380     8000  2004
1381    12000  4003
1382     4000  2002
1383     3000  3001
1384     9000  3003

CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1385  1386  2015-12-09     Lekki             Italiano   3000         1
1386  1387  2015-12-15     Lekki         Chicken Bali   2000         4
1387  1388  2015-12-04     Lekki        Chicken Feast   2000         2
1388  1389  2015-12-10  Surulere         Chicken Suya   4000         1
1389  1390  2015-12-03    Ibadan  Hot Pepperoni Feast   4000         5

          Time  Revenue  Snap
1385  08:37:32     3000  3001
1386  08:37:37     8000  2004
1387  08:37:37     4000  2002
1388  08:37:38     4000  4001
1389  08:37:40    20000  4005
CHUNK BOSS
       S/N        Date   Branch   Pizza Sold  Price  Quantity      Time  \
1390  1391  2015-12-13   Ibadan  BBQ Chicken   4000         1  08:37:44
1391  1392  2015-12-10   Ibadan     Italiano   3000         3  08:37:45
1392  1393  2015-12-12  Gbagada     Italiano   3000         3  08:37:46
1393  1394  2015-12-07    Ikoyi    Beef Suya   3000         4  08:37:47
1394  1395  2015-12-03   Ibadan   Hot Veggie   4000         3  08:37:49

      Revenue  Snap
1390     4000  4001
1391     9000  3003
1392     9000  3003
1393    12000  3004
1394    12000  4003
CHUNK BOSS
       S/N        Date    Branch    Pizza Sold  Price  Quantity      Time  \
1395  1396  2015-12-06    Ibadan      Italiano   3000         3  08:37:53
1396  1397  2015-12-14  Surulere  Chicken Bali   2000         2  08:37:55
1397  1398  2015-12-09     Lekki       Meatzaa   2000         1  08:37:56
1398  1399  2015-12-13   Gbagada  Chicken Bali   2000         1  08:37:57
1399  1400  2015-12-05   Gbagada      Italiano   3000         2  08:38:00

      Revenue  Snap
1395     9000  3003
1396     4000  2002
1397     2000  2001
1398     2000  2001
1399     6000  3002
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
1400  1401  2015-12-13  Gbagada     BBQ Philly Steak   4000         2
1401  1402  2015-12-14    Ikoyi  Hot Pepperoni Feast   4000         4
1402  1403  2015-12-13    Ikoyi          BBQ Chicken   4000         1
1403  1404  2015-12-11    Ikoyi          BBQ Chicken   4000         4
1404  1405  2015-12-03   Ibadan      Pepperoni Feast   4000         5

          Time  Revenue  Snap
1400  08:38:00     8000  4002
1401  08:38:01    16000  4004
1402  08:38:02     4000  4001
1403  08:38:04    16000  4004
1404  08:38:06    20000  4005
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1405  1406  2015-12-15     Ikoyi  BBQ Philly Steak   4000         2  08:38:07
1406  1407  2015-12-04  Surulere    Pepperoni Suya   3000         4  08:38:08
1407  1408  2015-12-05  Surulere     Chicken Feast   2000         5  08:38:10
1408  1409  2015-12-12   Gbagada         Beef Suya   3000         2  08:38:12
1409  1410  2015-12-13     Ikoyi    Chicken Legend   2000         4  08:38:12

      Revenue  Snap
1405     8000  4002
1406    12000  3004
1407    10000  2005
1408     6000  3002
1409     8000  2004
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1410  1411  2015-12-13    Ibadan         Beef Suya   3000         3  08:38:14
1411  1412  2015-12-14  Surulere           Meatzaa   2000         3  08:38:14
1412  1413  2015-12-04   Gbagada  BBQ Philly Steak   4000         5  08:38:16
1413  1414  2015-12-15     Lekki    Veggie Supreme   3000         4  08:38:20
1414  1415  2015-12-07     Ikoyi       BBQ Chicken   4000         3  08:38:21

      Revenue  Snap
1410     9000  3003
1411     6000  2003
1412    20000  4005
1413    12000  3004
1414    12000  4003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1415  1416  2015-12-09  Surulere             Italiano   3000         3
1416  1417  2015-12-14     Ikoyi      Pepperoni Feast   4000         5
1417  1418  2015-12-06    Ibadan         Extravaganza   2000         1
1418  1419  2015-12-08     Lekki              Meatzaa   2000         2
1419  1420  2015-12-10  Surulere  Hot Pepperoni Feast   4000         3

          Time  Revenue  Snap
1415  08:38:23     9000  3003
1416  08:38:24    20000  4005
1417  08:38:26     2000  2001
1418  08:38:32     4000  2002
1419  08:38:32    12000  4003
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
1420  1421  2015-12-04   Ibadan            Beef Suya   3000         5
1421  1422  2015-12-13    Lekki            Beef Suya   3000         4
1422  1423  2015-12-13  Gbagada     BBQ Philly Steak   4000         3
1423  1424  2015-12-07  Gbagada  Hot Pepperoni Feast   4000         2
1424  1425  2015-12-11  Gbagada             Italiano   3000         1

          Time  Revenue  Snap
1420  08:38:34    15000  3005
1421  08:38:34    12000  3004
1422  08:38:35    12000  4003
1423  08:38:35     8000  4002
1424  08:38:37     3000  3001
CHUNK BOSS
       S/N        Date   Branch   Pizza Sold  Price  Quantity      Time  \
1425  1426  2015-12-14   Ibadan    Beef Suya   3000         3  08:38:39
1426  1427  2015-12-09  Gbagada  BBQ Chicken   4000         2  08:38:40
1427  1428  2015-12-04    Lekki  BBQ Chicken   4000         4  08:38:41
1428  1429  2015-12-04    Ikoyi     Italiano   3000         2  08:38:43
1429  1430  2015-12-10  Gbagada      Meatzaa   2000         3  08:38:45

      Revenue  Snap
1425     9000  3003
1426     8000  4002
1427    16000  4004
1428     6000  3002
1429     6000  2003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1430  1431  2015-12-11  Surulere  Hot Pepperoni Feast   4000         1
1431  1432  2015-12-03  Surulere       Chicken Legend   2000         3
1432  1433  2015-12-13     Ikoyi  Hot Pepperoni Feast   4000         3
1433  1434  2015-12-04     Ikoyi             Italiano   3000         5
1434  1435  2015-12-10  Surulere  Hot Pepperoni Feast   4000         5

          Time  Revenue  Snap
1430  08:38:46     4000  4001
1431  08:38:46     6000  2003
1432  08:38:46    12000  4003
1433  08:38:52    15000  3005
1434  08:38:52    20000  4005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1435  1436  2015-12-15   Gbagada        Chicken Feast   2000         3
1436  1437  2015-12-09   Gbagada  Hot Pepperoni Feast   4000         4
1437  1438  2015-12-08  Surulere         Extravaganza   2000         5
1438  1439  2015-12-05    Ibadan         Extravaganza   2000         5
1439  1440  2015-12-09     Lekki         Chicken Suya   4000         2

          Time  Revenue  Snap
1435  08:38:53     6000  2003
1436  08:38:54    16000  4004
1437  08:38:56    10000  2005
1438  08:38:56    10000  2005
1439  08:38:57     8000  4002
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
1440  1441  2015-12-15     Ikoyi    Chicken Suya   4000         2  08:38:59
1441  1442  2015-12-12     Ikoyi         Meatzaa   2000         5  08:39:01
1442  1443  2015-12-09    Ibadan  Pepperoni Suya   3000         2  08:39:02
1443  1444  2015-12-14    Ibadan  Pepperoni Suya   3000         4  08:39:02
1444  1445  2015-12-03  Surulere        Italiano   3000         4  08:39:05

      Revenue  Snap
1440     8000  4002
1441    10000  2005
1442     6000  3002
1443    12000  3004
1444    12000  3004
CHUNK BOSS
       S/N        Date  Branch           Pizza Sold  Price  Quantity  \
1445  1446  2015-12-08  Ibadan         Chicken Bali   2000         5
1446  1447  2015-12-07   Ikoyi  Hot Pepperoni Feast   4000         5
1447  1448  2015-12-09   Ikoyi      Pepperoni Feast   4000         5
1448  1449  2015-12-10  Ibadan            Beef Suya   3000         4
1449  1450  2015-12-07   Ikoyi              Meatzaa   2000         3

          Time  Revenue  Snap
1445  08:39:08    10000  2005
1446  08:39:08    20000  4005
1447  08:39:12    20000  4005
1448  08:39:13    12000  3004
1449  08:39:14     6000  2003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1450  1451  2015-12-07     Ikoyi         Chicken Bali   2000         3
1451  1452  2015-12-04   Gbagada  Hot Pepperoni Feast   4000         2
1452  1453  2015-12-15     Lekki            Beef Suya   3000         5
1453  1454  2015-12-10  Surulere  Hot Pepperoni Feast   4000         2
1454  1455  2015-12-03     Ikoyi     BBQ Philly Steak   4000         3

          Time  Revenue  Snap
1450  08:39:14     6000  2003
1451  08:39:14     8000  4002
1452  08:39:14    15000  3005
1453  08:39:15     8000  4002
1454  08:39:16    12000  4003
CHUNK BOSS
       S/N        Date    Branch    Pizza Sold  Price  Quantity      Time  \
1455  1456  2015-12-14    Ibadan     Margarita   4000         4  08:39:17
1456  1457  2015-12-13     Lekki  Chicken Suya   4000         3  08:39:19
1457  1458  2015-12-13     Lekki     Beef Suya   3000         4  08:39:22
1458  1459  2015-12-07  Surulere  Extravaganza   2000         1  08:39:23
1459  1460  2015-12-03  Surulere       Meatzaa   2000         3  08:39:23

      Revenue  Snap
1455    16000  4004
1456    12000  4003
1457    12000  3004
1458     2000  2001
1459     6000  2003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1460  1461  2015-12-14     Lekki            Beef Suya   3000         1
1461  1462  2015-12-04  Surulere            Margarita   4000         5
1462  1463  2015-12-06  Surulere  Hot Pepperoni Feast   4000         4
1463  1464  2015-12-09  Surulere       Chicken Legend   2000         3
1464  1465  2015-12-14  Surulere        Chicken Feast   2000         2

          Time  Revenue  Snap
1460  08:39:24     3000  3001
1461  08:39:24    20000  4005
1462  08:39:24    16000  4004
1463  08:39:26     6000  2003
1464  08:39:26     4000  2002
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1465  1466  2015-12-14  Surulere    Chicken Legend   2000         1  08:39:26
1466  1467  2015-12-08     Lekki        Hot Veggie   4000         4  08:39:28
1467  1468  2015-12-06   Gbagada       BBQ Chicken   4000         4  08:39:29
1468  1469  2015-12-04   Gbagada  BBQ Philly Steak   4000         1  08:39:29
1469  1470  2015-12-06     Lekki   Pepperoni Feast   4000         5  08:39:34

      Revenue  Snap
1465     2000  2001
1466    16000  4004
1467    16000  4004
1468     4000  4001
1469    20000  4005
CHUNK BOSS
       S/N        Date    Branch    Pizza Sold  Price  Quantity      Time  \
1470  1471  2015-12-05     Lekki     Margarita   4000         5  08:39:35
1471  1472  2015-12-08    Ibadan    Hot Veggie   4000         1  08:39:37
1472  1473  2015-12-12  Surulere  Extravaganza   2000         5  08:39:37
1473  1474  2015-12-08  Surulere       Meatzaa   2000         2  08:39:38
1474  1475  2015-12-03    Ibadan      Italiano   3000         3  08:39:39

      Revenue  Snap
1470    20000  4005
1471     4000  4001
1472    10000  2005
1473     4000  2002
1474     9000  3003
CHUNK BOSS

       S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
1475  1476  2015-12-04    Ikoyi   Pepperoni Suya   3000         3  08:39:41
1476  1477  2015-12-10    Ikoyi   Pepperoni Suya   3000         4  08:39:41
1477  1478  2015-12-15    Ikoyi   Veggie Supreme   3000         3  08:39:42
1478  1479  2015-12-14  Gbagada     Extravaganza   2000         2  08:39:42
1479  1480  2015-12-05    Ikoyi  Pepperoni Feast   4000         4  08:39:42

      Revenue  Snap
1475     9000  3003
1476    12000  3004
1477     9000  3003
1478     4000  2002
1479    16000  4004
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
1480  1481  2015-12-06     Lekki  Chicken Legend   2000         1  08:39:45
1481  1482  2015-12-09     Lekki        Italiano   3000         5  08:39:47
1482  1483  2015-12-05   Gbagada  Veggie Supreme   3000         3  08:39:48
1483  1484  2015-12-07    Ibadan  Chicken Legend   2000         4  08:39:54
1484  1485  2015-12-15  Surulere  Chicken Legend   2000         3  08:39:56

      Revenue  Snap
1480     2000  2001
1481    15000  3005
1482     9000  3003
1483     8000  2004
1484     6000  2003
CHUNK BOSS
       S/N        Date    Branch    Pizza Sold  Price  Quantity      Time  \
1485  1486  2015-12-09    Ibadan    Hot Veggie   4000         1  08:39:57
1486  1487  2015-12-10  Surulere  Chicken Bali   2000         4  08:39:57
1487  1488  2015-12-09  Surulere   BBQ Chicken   4000         3  08:39:59
1488  1489  2015-12-12   Gbagada  Chicken Bali   2000         1  08:40:02
1489  1490  2015-12-12   Gbagada      Italiano   3000         1  08:40:04

      Revenue  Snap
1485     4000  4001
1486     8000  2004
1487    12000  4003
1488     2000  2001
1489     3000  3001
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1490  1491  2015-12-03  Surulere   Pepperoni Feast   4000         4  08:40:05
1491  1492  2015-12-12     Lekki      Chicken Bali   2000         4  08:40:07
1492  1493  2015-12-15     Ikoyi  BBQ Philly Steak   4000         2  08:40:07
1493  1494  2015-12-10     Lekki      Chicken Suya   4000         3  08:40:09
1494  1495  2015-12-12     Lekki      Chicken Suya   4000         1  08:40:11

      Revenue  Snap
1490    16000  4004
1491     8000  2004
1492     8000  4002
1493    12000  4003
1494     4000  4001
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
1495  1496  2015-12-04    Ikoyi  Hot Pepperoni Feast   4000         1
1496  1497  2015-12-07   Ibadan           Hot Veggie   4000         2
1497  1498  2015-12-13  Gbagada           Hot Veggie   4000         2
1498  1499  2015-12-12   Ibadan         Extravaganza   2000         4
1499  1500  2015-12-15    Lekki  Hot Pepperoni Feast   4000         3

          Time  Revenue  Snap
1495  08:40:11     4000  4001
1496  08:40:15     8000  4002
1497  08:40:18     8000  4002
1498  08:40:23     8000  2004
1499  08:40:23    12000  4003
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1500  1501  2015-12-04   Gbagada           Meatzaa   2000         1  08:40:24
1501  1502  2015-12-09  Surulere      Chicken Bali   2000         1  08:40:26
1502  1503  2015-12-12     Lekki    Chicken Legend   2000         2  08:40:27
1503  1504  2015-12-04     Lekki         Margarita   4000         4  08:40:27
1504  1505  2015-12-06    Ibadan  BBQ Philly Steak   4000         1  08:40:30

      Revenue  Snap
1500     2000  2001
1501     2000  2001
1502     4000  2002
1503    16000  4004
1504     4000  4001
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
1505  1506  2015-12-05     Ikoyi       Hot Veggie   4000         5  08:40:31
1506  1507  2015-12-09     Ikoyi  Pepperoni Feast   4000         2  08:40:31
1507  1508  2015-12-03    Ibadan      BBQ Chicken   4000         3  08:40:31
1508  1509  2015-12-08     Lekki        Margarita   4000         2  08:40:34
1509  1510  2015-12-12  Surulere   Chicken Legend   2000         3  08:40:38

      Revenue  Snap
1505    20000  4005
1506     8000  4002
1507    12000  4003
1508     8000  4002
1509     6000  2003
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
1510  1511  2015-12-15  Gbagada     BBQ Chicken   4000         1  08:40:38
1511  1512  2015-12-07    Lekki  Veggie Supreme   3000         4  08:40:42
1512  1513  2015-12-07  Gbagada       Margarita   4000         5  08:40:42
1513  1514  2015-12-14    Lekki      Hot Veggie   4000         3  08:40:43
1514  1515  2015-12-15    Lekki      Hot Veggie   4000         4  08:40:46

      Revenue  Snap
1510     4000  4001
1511    12000  3004
1512    20000  4005
1513    12000  4003
1514    16000  4004
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1515  1516  2015-12-07    Ibadan  Hot Pepperoni Feast   4000         5
1516  1517  2015-12-08     Ikoyi       Pepperoni Suya   3000         1
1517  1518  2015-12-06     Lekki      Pepperoni Feast   4000         2
1518  1519  2015-12-15  Surulere        Chicken Feast   2000         4
1519  1520  2015-12-12     Ikoyi              Meatzaa   2000         1

          Time  Revenue  Snap
1515  08:40:47    20000  4005
1516  08:40:51     3000  3001
1517  08:40:51     8000  4002
1518  08:40:53     8000  2004
1519  08:40:54     2000  2001
CHUNK BOSS
       S/N        Date    Branch    Pizza Sold  Price  Quantity      Time  \
1520  1521  2015-12-10  Surulere  Chicken Suya   4000         5  08:40:55
1521  1522  2015-12-09   Gbagada  Chicken Bali   2000         5  08:40:55
1522  1523  2015-12-12     Lekki      Italiano   3000         3  08:40:57
1523  1524  2015-12-15  Surulere     Margarita   4000         1  08:41:02
1524  1525  2015-12-06  Surulere  Extravaganza   2000         4  08:41:02

      Revenue  Snap
1520    20000  4005
1521    10000  2005
1522     9000  3003
1523     4000  4001
1524     8000  2004
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1525  1526  2015-12-09   Gbagada         Beef Suya   3000         3  08:41:03
1526  1527  2015-12-04  Surulere         Beef Suya   3000         5  08:41:03
1527  1528  2015-12-13     Lekki         Beef Suya   3000         4  08:41:07
1528  1529  2015-12-12  Surulere  BBQ Philly Steak   4000         5  08:41:08
1529  1530  2015-12-14   Gbagada      Chicken Suya   4000         2  08:41:09

      Revenue  Snap
1525     9000  3003
1526    15000  3005
1527    12000  3004
1528    20000  4005
1529     8000  4002
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
1530  1531  2015-12-05    Ikoyi  Chicken Legend   2000         5  08:41:10
1531  1532  2015-12-09  Gbagada  Chicken Legend   2000         2  08:41:11
1532  1533  2015-12-08  Gbagada       Beef Suya   3000         2  08:41:12
1533  1534  2015-12-07  Gbagada    Chicken Bali   2000         4  08:41:13
1534  1535  2015-12-06   Ibadan    Chicken Bali   2000         3  08:41:16

      Revenue  Snap
1530    10000  2005
1531     4000  2002
1532     6000  3002
1533     8000  2004
1534     6000  2003
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
1535  1536  2015-12-11    Ibadan       Margarita   4000         2  08:41:17
1536  1537  2015-12-12     Ikoyi     BBQ Chicken   4000         1  08:41:21
1537  1538  2015-12-03    Ibadan  Veggie Supreme   3000         4  08:41:22
1538  1539  2015-12-11  Surulere  Veggie Supreme   3000         2  08:41:22
1539  1540  2015-12-09   Gbagada      Hot Veggie   4000         5  08:41:23

      Revenue  Snap
1535     8000  4002
1536     4000  4001
1537    12000  3004
1538     6000  3002
1539    20000  4005
CHUNK BOSS
       S/N        Date Branch           Pizza Sold  Price  Quantity      Time  \
1540  1541  2015-12-10  Lekki          BBQ Chicken   4000         4  08:41:23
1541  1542  2015-12-05  Ikoyi          BBQ Chicken   4000         1  08:41:23
1542  1543  2015-12-08  Lekki  Hot Pepperoni Feast   4000         3  08:41:23
1543  1544  2015-12-05  Lekki          BBQ Chicken   4000         4  08:41:27
1544  1545  2015-12-13  Lekki     BBQ Philly Steak   4000         2  08:41:28

      Revenue  Snap
1540    16000  4004
1541     4000  4001
1542    12000  4003
1543    16000  4004
1544     8000  4002
CHUNK BOSS
       S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
1545  1546  2015-12-10    Lekki    Chicken Feast   2000         2  08:41:32
1546  1547  2015-12-09   Ibadan    Chicken Feast   2000         5  08:41:33
1547  1548  2015-12-14    Ikoyi        Beef Suya   3000         3  08:41:34
1548  1549  2015-12-10   Ibadan  Pepperoni Feast   4000         1  08:41:35
1549  1550  2015-12-14  Gbagada        Margarita   4000         3  08:41:36

      Revenue  Snap
1545     4000  2002
1546    10000  2005
1547     9000  3003
1548     4000  4001
1549    12000  4003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1550  1551  2015-12-08  Surulere  Hot Pepperoni Feast   4000         4
1551  1552  2015-12-04   Gbagada          BBQ Chicken   4000         1
1552  1553  2015-12-03     Ikoyi           Hot Veggie   4000         1
1553  1554  2015-12-10   Gbagada       Pepperoni Suya   3000         2
1554  1555  2015-12-07  Surulere      Pepperoni Feast   4000         3

          Time  Revenue  Snap
1550  08:41:37    16000  4004
1551  08:41:38     4000  4001
1552  08:41:41     4000  4001
1553  08:41:42     6000  3002
1554  08:41:46    12000  4003
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
1555  1556  2015-12-04  Gbagada  Veggie Supreme   3000         2  08:41:49
1556  1557  2015-12-04  Gbagada  Veggie Supreme   3000         1  08:41:52
1557  1558  2015-12-05    Ikoyi       Beef Suya   3000         3  08:41:53
1558  1559  2015-12-06   Ibadan  Veggie Supreme   3000         5  08:41:53
1559  1560  2015-12-11    Lekki       Margarita   4000         3  08:41:55

      Revenue  Snap
1555     6000  3002
1556     3000  3001
1557     9000  3003
1558    15000  3005
1559    12000  4003
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
1560  1561  2015-12-06   Gbagada  Pepperoni Suya   3000         5  08:41:57
1561  1562  2015-12-09    Ibadan  Veggie Supreme   3000         4  08:41:58
1562  1563  2015-12-03  Surulere    Extravaganza   2000         5  08:41:58
1563  1564  2015-12-14  Surulere    Chicken Bali   2000         2  08:42:04
1564  1565  2015-12-08    Ibadan       Margarita   4000         1  08:42:05

      Revenue  Snap
1560    15000  3005
1561    12000  3004
1562    10000  2005
1563     4000  2002
1564     4000  4001

CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
1565  1566  2015-12-05  Surulere    Extravaganza   2000         4  08:42:06
1566  1567  2015-12-08     Ikoyi    Chicken Suya   4000         5  08:42:07
1567  1568  2015-12-12  Surulere       Margarita   4000         3  08:42:08
1568  1569  2015-12-09   Gbagada     BBQ Chicken   4000         1  08:42:09
1569  1570  2015-12-08  Surulere  Veggie Supreme   3000         3  08:42:10

      Revenue  Snap
1565     8000  2004
1566    20000  4005
1567    12000  4003
1568     4000  4001
1569     9000  3003
CHUNK BOSS
       S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
1570  1571  2015-12-08   Ibadan   Pepperoni Suya   3000         3  08:42:10
1571  1572  2015-12-15   Ibadan         Italiano   3000         5  08:42:11
1572  1573  2015-12-04  Gbagada     Chicken Bali   2000         3  08:42:14
1573  1574  2015-12-12   Ibadan  Pepperoni Feast   4000         3  08:42:14
1574  1575  2015-12-06    Ikoyi  Pepperoni Feast   4000         2  08:42:14

      Revenue  Snap
1570     9000  3003
1571    15000  3005
1572     6000  2003
1573    12000  4003
1574     8000  4002
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1575  1576  2015-12-12  Surulere       Veggie Supreme   3000         2
1576  1577  2015-12-11     Ikoyi           Hot Veggie   4000         3
1577  1578  2015-12-09     Lekki              Meatzaa   2000         5
1578  1579  2015-12-14   Gbagada        Chicken Feast   2000         1
1579  1580  2015-12-07     Lekki  Hot Pepperoni Feast   4000         2

          Time  Revenue  Snap
1575  08:42:14     6000  3002
1576  08:42:17    12000  4003
1577  08:42:19    10000  2005
1578  08:42:20     2000  2001
1579  08:42:21     8000  4002
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1580  1581  2015-12-12     Lekki  Hot Pepperoni Feast   4000         1
1581  1582  2015-12-04     Lekki     BBQ Philly Steak   4000         3
1582  1583  2015-12-10   Gbagada     BBQ Philly Steak   4000         2
1583  1584  2015-12-07  Surulere              Meatzaa   2000         3
1584  1585  2015-12-05  Surulere  Hot Pepperoni Feast   4000         1

          Time  Revenue  Snap
1580  08:42:26     4000  4001
1581  08:42:28    12000  4003
1582  08:42:28     8000  4002
1583  08:42:31     6000  2003
1584  08:42:32     4000  4001
CHUNK BOSS
       S/N        Date  Branch           Pizza Sold  Price  Quantity  \
1585  1586  2015-12-11  Ibadan  Hot Pepperoni Feast   4000         3
1586  1587  2015-12-14   Ikoyi              Meatzaa   2000         1
1587  1588  2015-12-15   Lekki       Chicken Legend   2000         3
1588  1589  2015-12-13  Ibadan  Hot Pepperoni Feast   4000         5
1589  1590  2015-12-04   Lekki       Pepperoni Suya   3000         2

          Time  Revenue  Snap
1585  08:42:32    12000  4003
1586  08:42:32     2000  2001
1587  08:42:34     6000  2003
1588  08:42:36    20000  4005
1589  08:42:36     6000  3002
CHUNK BOSS
       S/N        Date   Branch    Pizza Sold  Price  Quantity      Time  \
1590  1591  2015-12-13   Ibadan  Chicken Bali   2000         4  08:42:36
1591  1592  2015-12-03   Ibadan     Beef Suya   3000         5  08:42:37
1592  1593  2015-12-13  Gbagada    Hot Veggie   4000         2  08:42:41
1593  1594  2015-12-10   Ibadan     Margarita   4000         3  08:42:42
1594  1595  2015-12-13    Ikoyi  Chicken Suya   4000         2  08:42:43

      Revenue  Snap
1590     8000  2004
1591    15000  3005
1592     8000  4002
1593    12000  4003
1594     8000  4002
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
1595  1596  2015-12-09     Lekki   Chicken Feast   2000         1  08:42:45
1596  1597  2015-12-10  Surulere   Chicken Feast   2000         5  08:42:45
1597  1598  2015-12-07    Ibadan        Italiano   3000         4  08:42:45
1598  1599  2015-12-12   Gbagada     BBQ Chicken   4000         4  08:42:46
1599  1600  2015-12-09  Surulere  Chicken Legend   2000         4  08:42:47

      Revenue  Snap
1595     2000  2001
1596    10000  2005
1597    12000  3004
1598    16000  4004
1599     8000  2004
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
1600  1601  2015-12-10     Ikoyi    Chicken Bali   2000         4  08:42:48
1601  1602  2015-12-04  Surulere       Margarita   4000         1  08:42:50
1602  1603  2015-12-03     Ikoyi     BBQ Chicken   4000         5  08:42:52
1603  1604  2015-12-11     Lekki         Meatzaa   2000         3  08:42:53
1604  1605  2015-12-14     Lekki  Pepperoni Suya   3000         2  08:42:54

      Revenue  Snap
1600     8000  2004
1601     4000  4001
1602    20000  4005
1603     6000  2003
1604     6000  3002
CHUNK BOSS
       S/N        Date  Branch      Pizza Sold  Price  Quantity      Time  \
1605  1606  2015-12-03   Lekki  Chicken Legend   2000         4  08:42:54
1606  1607  2015-12-13   Lekki         Meatzaa   2000         1  08:42:55
1607  1608  2015-12-08  Ibadan    Chicken Bali   2000         1  08:42:56
1608  1609  2015-12-15   Lekki       Beef Suya   3000         2  08:42:59
1609  1610  2015-12-09   Ikoyi     BBQ Chicken   4000         2  08:43:01

      Revenue  Snap
1605     8000  2004
1606     2000  2001
1607     2000  2001
1608     6000  3002
1609     8000  4002
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1610  1611  2015-12-04    Ibadan       Chicken Legend   2000         2
1611  1612  2015-12-08     Lekki      Pepperoni Feast   4000         2
1612  1613  2015-12-07  Surulere      Pepperoni Feast   4000         5
1613  1614  2015-12-03     Lekki  Hot Pepperoni Feast   4000         5
1614  1615  2015-12-12     Ikoyi             Italiano   3000         5

          Time  Revenue  Snap
1610  08:43:01     4000  2002
1611  08:43:02     8000  4002
1612  08:43:03    20000  4005
1613  08:43:04    20000  4005
1614  08:43:05    15000  3005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1615  1616  2015-12-09     Lekki  Hot Pepperoni Feast   4000         2
1616  1617  2015-12-09  Surulere         Chicken Suya   4000         4
1617  1618  2015-12-14    Ibadan      Pepperoni Feast   4000         3
1618  1619  2015-12-03     Lekki       Veggie Supreme   3000         2
1619  1620  2015-12-07  Surulere         Chicken Bali   2000         2

          Time  Revenue  Snap
1615  08:43:05     8000  4002
1616  08:43:06    16000  4004
1617  08:43:07    12000  4003
1618  08:43:08     6000  3002
1619  08:43:09     4000  2002
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
1620  1621  2015-12-10  Surulere      BBQ Chicken   4000         3  08:43:09
1621  1622  2015-12-08     Ikoyi   Chicken Legend   2000         4  08:43:10
1622  1623  2015-12-15   Gbagada  Pepperoni Feast   4000         5  08:43:14
1623  1624  2015-12-08    Ibadan    Chicken Feast   2000         4  08:43:14
1624  1625  2015-12-06  Surulere   Pepperoni Suya   3000         3  08:43:15

      Revenue  Snap
1620    12000  4003
1621     8000  2004
1622    20000  4005
1623     8000  2004
1624     9000  3003
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
1625  1626  2015-12-15     Lekki   Chicken Legend   2000         5  08:43:16
1626  1627  2015-12-03    Ibadan     Chicken Bali   2000         5  08:43:17
1627  1628  2015-12-14  Surulere         Italiano   3000         2  08:43:19
1628  1629  2015-12-11     Lekki  Pepperoni Feast   4000         1  08:43:19
1629  1630  2015-12-06  Surulere   Pepperoni Suya   3000         3  08:43:21

      Revenue  Snap
1625    10000  2005
1626    10000  2005
1627     6000  3002
1628     4000  4001
1629     9000  3003
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
1630  1631  2015-12-05    Ikoyi              Meatzaa   2000         2
1631  1632  2015-12-06    Ikoyi            Beef Suya   3000         3
1632  1633  2015-12-03  Gbagada  Hot Pepperoni Feast   4000         2
1633  1634  2015-12-09    Lekki       Veggie Supreme   3000         2
1634  1635  2015-12-07    Ikoyi         Chicken Suya   4000         1

          Time  Revenue  Snap
1630  08:43:22     4000  2002
1631  08:43:22     9000  3003
1632  08:43:22     8000  4002
1633  08:43:23     6000  3002
1634  08:43:25     4000  4001
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1635  1636  2015-12-14    Ibadan       BBQ Chicken   4000         4  08:43:26
1636  1637  2015-12-06  Surulere       BBQ Chicken   4000         3  08:43:31
1637  1638  2015-12-11     Lekki    Veggie Supreme   3000         4  08:43:31
1638  1639  2015-12-15    Ibadan    Pepperoni Suya   3000         2  08:43:32
1639  1640  2015-12-15   Gbagada  BBQ Philly Steak   4000         1  08:43:34

      Revenue  Snap
1635    16000  4004
1636    12000  4003
1637    12000  3004
1638     6000  3002
1639     4000  4001
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
1640  1641  2015-12-13   Ibadan  BBQ Philly Steak   4000         5  08:43:34
1641  1642  2015-12-06   Ibadan        Hot Veggie   4000         2  08:43:35
1642  1643  2015-12-15    Ikoyi       BBQ Chicken   4000         3  08:43:37
1643  1644  2015-12-07    Ikoyi     Chicken Feast   2000         4  08:43:38
1644  1645  2015-12-08  Gbagada    Chicken Legend   2000         2  08:43:39

      Revenue  Snap
1640    20000  4005
1641     8000  4002
1642    12000  4003
1643     8000  2004
1644     4000  2002
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
1645  1646  2015-12-08    Ibadan     Chicken Bali   2000         1  08:43:43
1646  1647  2015-12-06  Surulere   Pepperoni Suya   3000         4  08:43:48
1647  1648  2015-12-06     Lekki       Hot Veggie   4000         2  08:43:49
1648  1649  2015-12-04     Lekki     Chicken Suya   4000         5  08:43:49
1649  1650  2015-12-07     Ikoyi  Pepperoni Feast   4000         2  08:43:50

      Revenue  Snap
1645     2000  2001
1646    12000  3004
1647     8000  4002
1648    20000  4005
1649     8000  4002
CHUNK BOSS
       S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
1650  1651  2015-12-11   Ibadan     Chicken Suya   4000         2  08:43:50
1651  1652  2015-12-04    Lekki  Pepperoni Feast   4000         4  08:43:51
1652  1653  2015-12-06    Ikoyi   Pepperoni Suya   3000         2  08:43:52
1653  1654  2015-12-08  Gbagada    Chicken Feast   2000         1  08:43:54
1654  1655  2015-12-04   Ibadan        Beef Suya   3000         4  08:43:55

      Revenue  Snap
1650     8000  4002
1651    16000  4004
1652     6000  3002
1653     2000  2001
1654    12000  3004
CHUNK BOSS

       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
1655  1656  2015-12-03    Ikoyi        Italiano   3000         2  08:43:56
1656  1657  2015-12-06  Gbagada  Chicken Legend   2000         3  08:43:58
1657  1658  2015-12-05    Lekki  Chicken Legend   2000         2  08:43:59
1658  1659  2015-12-03    Ikoyi         Meatzaa   2000         1  08:44:00
1659  1660  2015-12-05   Ibadan        Italiano   3000         4  08:44:02

      Revenue  Snap
1655     6000  3002
1656     6000  2003
1657     4000  2002
1658     2000  2001
1659    12000  3004
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1660  1661  2015-12-12     Lekki    Pepperoni Suya   3000         3  08:44:03
1661  1662  2015-12-09    Ibadan           Meatzaa   2000         1  08:44:03
1662  1663  2015-12-07   Gbagada        Hot Veggie   4000         5  08:44:06
1663  1664  2015-12-04     Ikoyi  BBQ Philly Steak   4000         3  08:44:06
1664  1665  2015-12-04  Surulere      Chicken Suya   4000         1  08:44:06

      Revenue  Snap
1660     9000  3003
1661     2000  2001
1662    20000  4005
1663    12000  4003
1664     4000  4001
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1665  1666  2015-12-05  Surulere  BBQ Philly Steak   4000         3  08:44:12
1666  1667  2015-12-10     Ikoyi    Chicken Legend   2000         4  08:44:16
1667  1668  2015-12-06     Ikoyi         Beef Suya   3000         1  08:44:18
1668  1669  2015-12-08   Gbagada           Meatzaa   2000         3  08:44:21
1669  1670  2015-12-15  Surulere      Extravaganza   2000         5  08:44:21

      Revenue  Snap
1665    12000  4003
1666     8000  2004
1667     3000  3001
1668     6000  2003
1669    10000  2005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1670  1671  2015-12-14    Ibadan         Chicken Bali   2000         1
1671  1672  2015-12-08     Ikoyi      Pepperoni Feast   4000         2
1672  1673  2015-12-15     Lekki  Hot Pepperoni Feast   4000         3
1673  1674  2015-12-13  Surulere       Veggie Supreme   3000         5
1674  1675  2015-12-10     Lekki          BBQ Chicken   4000         1

          Time  Revenue  Snap
1670  08:44:22     2000  2001
1671  08:44:22     8000  4002
1672  08:44:23    12000  4003
1673  08:44:24    15000  3005
1674  08:44:25     4000  4001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
1675  1676  2015-12-12    Ibadan     BBQ Chicken   4000         2  08:44:25
1676  1677  2015-12-12     Lekki  Pepperoni Suya   3000         5  08:44:26
1677  1678  2015-12-13     Ikoyi   Chicken Feast   2000         2  08:44:29
1678  1679  2015-12-06  Surulere       Margarita   4000         2  08:44:29
1679  1680  2015-12-05   Gbagada    Chicken Bali   2000         4  08:44:30

      Revenue  Snap
1675     8000  4002
1676    15000  3005
1677     4000  2002
1678     8000  4002
1679     8000  2004
CHUNK BOSS
       S/N        Date  Branch           Pizza Sold  Price  Quantity  \
1680  1681  2015-12-11  Ibadan  Hot Pepperoni Feast   4000         5
1681  1682  2015-12-09   Lekki             Italiano   3000         4
1682  1683  2015-12-03   Lekki            Beef Suya   3000         3
1683  1684  2015-12-10   Ikoyi     BBQ Philly Steak   4000         2
1684  1685  2015-12-06  Ibadan       Chicken Legend   2000         4

          Time  Revenue  Snap
1680  08:44:30    20000  4005
1681  08:44:34    12000  3004
1682  08:44:35     9000  3003
1683  08:44:37     8000  4002
1684  08:44:38     8000  2004
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1685  1686  2015-12-03     Ikoyi    Pepperoni Suya   3000         1  08:44:40
1686  1687  2015-12-15  Surulere     Chicken Feast   2000         4  08:44:41
1687  1688  2015-12-11    Ibadan        Hot Veggie   4000         2  08:44:42
1688  1689  2015-12-08   Gbagada    Veggie Supreme   3000         4  08:44:43
1689  1690  2015-12-12     Lekki  BBQ Philly Steak   4000         3  08:44:43

      Revenue  Snap
1685     3000  3001
1686     8000  2004
1687     8000  4002
1688    12000  3004
1689    12000  4003
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1690  1691  2015-12-03  Surulere  BBQ Philly Steak   4000         2  08:44:45
1691  1692  2015-12-12     Ikoyi    Chicken Legend   2000         4  08:44:45
1692  1693  2015-12-06  Surulere          Italiano   3000         3  08:44:47
1693  1694  2015-12-05  Surulere       BBQ Chicken   4000         3  08:44:48
1694  1695  2015-12-07  Surulere   Pepperoni Feast   4000         2  08:44:51

      Revenue  Snap
1690     8000  4002
1691     8000  2004
1692     9000  3003
1693    12000  4003
1694     8000  4002
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1695  1696  2015-12-15  Surulere        Chicken Feast   2000         4
1696  1697  2015-12-14   Gbagada            Margarita   4000         3
1697  1698  2015-12-11  Surulere       Veggie Supreme   3000         5
1698  1699  2015-12-05     Lekki  Hot Pepperoni Feast   4000         2
1699  1700  2015-12-06     Lekki       Chicken Legend   2000         4

          Time  Revenue  Snap
1695  08:44:53     8000  2004
1696  08:44:56    12000  4003
1697  08:44:56    15000  3005
1698  08:44:57     8000  4002
1699  08:44:59     8000  2004
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1700  1701  2015-12-15   Gbagada  BBQ Philly Steak   4000         3  08:45:03
1701  1702  2015-12-14   Gbagada  BBQ Philly Steak   4000         1  08:45:06
1702  1703  2015-12-04   Gbagada           Meatzaa   2000         2  08:45:06
1703  1704  2015-12-12     Lekki         Margarita   4000         3  08:45:09
1704  1705  2015-12-13  Surulere     Chicken Feast   2000         2  08:45:09

      Revenue  Snap
1700    12000  4003
1701     4000  4001
1702     4000  2002
1703    12000  4003
1704     4000  2002
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1705  1706  2015-12-05    Ibadan  Hot Pepperoni Feast   4000         3
1706  1707  2015-12-14   Gbagada             Italiano   3000         2
1707  1708  2015-12-10     Lekki         Chicken Suya   4000         2
1708  1709  2015-12-08    Ibadan  Hot Pepperoni Feast   4000         2
1709  1710  2015-12-10  Surulere         Chicken Suya   4000         4

          Time  Revenue  Snap
1705  08:45:10    12000  4003
1706  08:45:10     6000  3002
1707  08:45:10     8000  4002
1708  08:45:11     8000  4002
1709  08:45:11    16000  4004
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
1710  1711  2015-12-07     Ikoyi    Chicken Feast   2000         1  08:45:11
1711  1712  2015-12-04   Gbagada        Beef Suya   3000         3  08:45:11
1712  1713  2015-12-10     Lekki     Chicken Bali   2000         4  08:45:13
1713  1714  2015-12-15  Surulere    Chicken Feast   2000         2  08:45:14
1714  1715  2015-12-06   Gbagada  Pepperoni Feast   4000         1  08:45:16

      Revenue  Snap
1710     2000  2001
1711     9000  3003
1712     8000  2004
1713     4000  2002
1714     4000  4001
CHUNK BOSS
       S/N        Date    Branch     Pizza Sold  Price  Quantity      Time  \
1715  1716  2015-12-05  Surulere   Chicken Bali   2000         5  08:45:18
1716  1717  2015-12-12   Gbagada   Chicken Suya   4000         4  08:45:19
1717  1718  2015-12-03   Gbagada      Beef Suya   3000         5  08:45:20
1718  1719  2015-12-03  Surulere       Italiano   3000         1  08:45:21
1719  1720  2015-12-05   Gbagada  Chicken Feast   2000         1  08:45:21

      Revenue  Snap
1715    10000  2005
1716    16000  4004
1717    15000  3005
1718     3000  3001
1719     2000  2001
CHUNK BOSS
       S/N        Date    Branch     Pizza Sold  Price  Quantity      Time  \
1720  1721  2015-12-11  Surulere    BBQ Chicken   4000         1  08:45:21
1721  1722  2015-12-13     Ikoyi   Chicken Bali   2000         4  08:45:28
1722  1723  2015-12-12    Ibadan  Chicken Feast   2000         3  08:45:31
1723  1724  2015-12-07    Ibadan   Chicken Bali   2000         4  08:45:33
1724  1725  2015-12-13  Surulere      Margarita   4000         4  08:45:35

      Revenue  Snap
1720     4000  4001
1721     8000  2004
1722     6000  2003
1723     8000  2004
1724    16000  4004
CHUNK BOSS
       S/N        Date Branch   Pizza Sold  Price  Quantity      Time  \
1725  1726  2015-12-12  Ikoyi    Beef Suya   3000         5  08:45:37
1726  1727  2015-12-06  Lekki    Beef Suya   3000         4  08:45:38
1727  1728  2015-12-04  Ikoyi     Italiano   3000         4  08:45:40
1728  1729  2015-12-06  Ikoyi  BBQ Chicken   4000         2  08:45:43
1729  1730  2015-12-10  Lekki     Italiano   3000         3  08:45:43

      Revenue  Snap
1725    15000  3005
1726    12000  3004
1727    12000  3004
1728     8000  4002
1729     9000  3003
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
1730  1731  2015-12-03     Ikoyi    Chicken Suya   4000         5  08:45:45
1731  1732  2015-12-10  Surulere  Pepperoni Suya   3000         4  08:45:45
1732  1733  2015-12-04     Ikoyi         Meatzaa   2000         2  08:45:47
1733  1734  2015-12-05   Gbagada      Hot Veggie   4000         1  08:45:47
1734  1735  2015-12-08   Gbagada     BBQ Chicken   4000         3  08:45:47

      Revenue  Snap
1730    20000  4005
1731    12000  3004
1732     4000  2002
1733     4000  4001
1734    12000  4003

CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
1735  1736  2015-12-09  Gbagada      Pepperoni Feast   4000         2
1736  1737  2015-12-06  Gbagada        Chicken Feast   2000         3
1737  1738  2015-12-12  Gbagada        Chicken Feast   2000         3
1738  1739  2015-12-15   Ibadan  Hot Pepperoni Feast   4000         4
1739  1740  2015-12-06    Ikoyi         Chicken Suya   4000         3

          Time  Revenue  Snap
1735  08:45:51     8000  4002
1736  08:45:52     6000  2003
1737  08:45:53     6000  2003
1738  08:45:55    16000  4004
1739  08:45:57    12000  4003
CHUNK BOSS
       S/N        Date   Branch     Pizza Sold  Price  Quantity      Time  \
1740  1741  2015-12-12  Gbagada      Beef Suya   3000         3  08:45:59
1741  1742  2015-12-05  Gbagada  Chicken Feast   2000         5  08:46:01
1742  1743  2015-12-08  Gbagada        Meatzaa   2000         1  08:46:01
1743  1744  2015-12-09   Ibadan   Chicken Suya   4000         2  08:46:02
1744  1745  2015-12-07  Gbagada       Italiano   3000         5  08:46:03

      Revenue  Snap
1740     9000  3003
1741    10000  2005
1742     2000  2001
1743     8000  4002
1744    15000  3005
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1745  1746  2015-12-15  Surulere           Meatzaa   2000         3  08:46:06
1746  1747  2015-12-11     Lekki       BBQ Chicken   4000         4  08:46:08
1747  1748  2015-12-05   Gbagada      Chicken Suya   4000         3  08:46:09
1748  1749  2015-12-04    Ibadan       BBQ Chicken   4000         5  08:46:11
1749  1750  2015-12-14    Ibadan  BBQ Philly Steak   4000         3  08:46:14

      Revenue  Snap
1745     6000  2003
1746    16000  4004
1747    12000  4003
1748    20000  4005
1749    12000  4003
CHUNK BOSS
       S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
1750  1751  2015-12-04    Ikoyi  Pepperoni Feast   4000         1  08:46:15
1751  1752  2015-12-03  Gbagada        Beef Suya   3000         3  08:46:17
1752  1753  2015-12-07    Lekki   Pepperoni Suya   3000         5  08:46:17
1753  1754  2015-12-14  Gbagada       Hot Veggie   4000         5  08:46:17
1754  1755  2015-12-11   Ibadan     Extravaganza   2000         3  08:46:18

      Revenue  Snap
1750     4000  4001
1751     9000  3003
1752    15000  3005
1753    20000  4005
1754     6000  2003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1755  1756  2015-12-06    Ibadan  Hot Pepperoni Feast   4000         5
1756  1757  2015-12-11  Surulere         Chicken Bali   2000         2
1757  1758  2015-12-03   Gbagada         Chicken Bali   2000         3
1758  1759  2015-12-15     Ikoyi           Hot Veggie   4000         1
1759  1760  2015-12-03   Gbagada         Chicken Suya   4000         1

          Time  Revenue  Snap
1755  08:46:24    20000  4005
1756  08:46:24     4000  2002
1757  08:46:25     6000  2003
1758  08:46:26     4000  4001
1759  08:46:26     4000  4001
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1760  1761  2015-12-03   Gbagada           Hot Veggie   4000         4
1761  1762  2015-12-05    Ibadan  Hot Pepperoni Feast   4000         1
1762  1763  2015-12-12     Lekki       Veggie Supreme   3000         2
1763  1764  2015-12-09     Lekki       Veggie Supreme   3000         4
1764  1765  2015-12-06  Surulere         Extravaganza   2000         2

          Time  Revenue  Snap
1760  08:46:27    16000  4004
1761  08:46:27     4000  4001
1762  08:46:28     6000  3002
1763  08:46:28    12000  3004
1764  08:46:31     4000  2002
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
1765  1766  2015-12-08   Ibadan    Chicken Bali   2000         1  08:46:31
1766  1767  2015-12-06  Gbagada  Veggie Supreme   3000         4  08:46:35
1767  1768  2015-12-10  Gbagada  Pepperoni Suya   3000         3  08:46:37
1768  1769  2015-12-13   Ibadan   Chicken Feast   2000         1  08:46:37
1769  1770  2015-12-12    Lekki    Extravaganza   2000         2  08:46:40

      Revenue  Snap
1765     2000  2001
1766    12000  3004
1767     9000  3003
1768     2000  2001
1769     4000  2002
CHUNK BOSS
       S/N        Date  Branch           Pizza Sold  Price  Quantity  \
1770  1771  2015-12-07   Lekki     BBQ Philly Steak   4000         3
1771  1772  2015-12-04  Ibadan  Hot Pepperoni Feast   4000         1
1772  1773  2015-12-12   Ikoyi           Hot Veggie   4000         3
1773  1774  2015-12-13   Ikoyi      Pepperoni Feast   4000         3
1774  1775  2015-12-08  Ibadan         Extravaganza   2000         5

          Time  Revenue  Snap
1770  08:46:40    12000  4003
1771  08:46:41     4000  4001
1772  08:46:44    12000  4003
1773  08:46:45    12000  4003
1774  08:46:45    10000  2005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1775  1776  2015-12-15     Ikoyi       Veggie Supreme   3000         2
1776  1777  2015-12-10    Ibadan              Meatzaa   2000         1
1777  1778  2015-12-13  Surulere  Hot Pepperoni Feast   4000         5
1778  1779  2015-12-08  Surulere            Margarita   4000         3
1779  1780  2015-12-15    Ibadan       Chicken Legend   2000         4

          Time  Revenue  Snap
1775  08:46:45     6000  3002
1776  08:46:47     2000  2001
1777  08:46:48    20000  4005
1778  08:46:49    12000  4003
1779  08:46:50     8000  2004
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
1780  1781  2015-12-03     Lekki   Pepperoni Suya   3000         1  08:46:50
1781  1782  2015-12-07  Surulere          Meatzaa   2000         2  08:46:50
1782  1783  2015-12-14  Surulere  Pepperoni Feast   4000         1  08:46:52
1783  1784  2015-12-10    Ibadan      BBQ Chicken   4000         2  08:46:53
1784  1785  2015-12-04     Ikoyi     Chicken Bali   2000         1  08:46:54

      Revenue  Snap
1780     3000  3001
1781     4000  2002
1782     4000  4001
1783     8000  4002
1784     2000  2001
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
1785  1786  2015-12-08  Surulere        Beef Suya   3000         2  08:46:56
1786  1787  2015-12-08   Gbagada      BBQ Chicken   4000         1  08:46:56
1787  1788  2015-12-04   Gbagada   Pepperoni Suya   3000         5  08:46:57
1788  1789  2015-12-11    Ibadan  Pepperoni Feast   4000         4  08:46:58
1789  1790  2015-12-10     Lekki  Pepperoni Feast   4000         3  08:46:58

      Revenue  Snap
1785     6000  3002
1786     4000  4001
1787    15000  3005
1788    16000  4004
1789    12000  4003
CHUNK BOSS
       S/N        Date   Branch   Pizza Sold  Price  Quantity      Time  \
1790  1791  2015-12-13    Lekki    Margarita   4000         5  08:46:58
1791  1792  2015-12-13    Lekki      Meatzaa   2000         5  08:47:01
1792  1793  2015-12-10    Lekki     Italiano   3000         2  08:47:02
1793  1794  2015-12-09  Gbagada  BBQ Chicken   4000         3  08:47:03
1794  1795  2015-12-06    Ikoyi    Margarita   4000         2  08:47:04

      Revenue  Snap
1790    20000  4005
1791    10000  2005
1792     6000  3002
1793    12000  4003
1794     8000  4002
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1795  1796  2015-12-03  Surulere  BBQ Philly Steak   4000         3  08:47:06
1796  1797  2015-12-14     Ikoyi           Meatzaa   2000         4  08:47:08
1797  1798  2015-12-10  Surulere        Hot Veggie   4000         2  08:47:08
1798  1799  2015-12-10     Ikoyi      Extravaganza   2000         5  08:47:09
1799  1800  2015-12-05    Ibadan        Hot Veggie   4000         2  08:47:10

      Revenue  Snap
1795    12000  4003
1796     8000  2004
1797     8000  4002
1798    10000  2005
1799     8000  4002
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
1800  1801  2015-12-09  Gbagada    Pepperoni Suya   3000         3  08:47:11
1801  1802  2015-12-09   Ibadan    Chicken Legend   2000         3  08:47:13
1802  1803  2015-12-15    Lekki     Chicken Feast   2000         4  08:47:14
1803  1804  2015-12-14   Ibadan  BBQ Philly Steak   4000         2  08:47:15
1804  1805  2015-12-03    Lekki   Pepperoni Feast   4000         1  08:47:16

      Revenue  Snap
1800     9000  3003
1801     6000  2003
1802     8000  2004
1803     8000  4002
1804     4000  4001
CHUNK BOSS
       S/N        Date  Branch      Pizza Sold  Price  Quantity      Time  \
1805  1806  2015-12-15   Lekki  Pepperoni Suya   3000         5  08:47:18
1806  1807  2015-12-09  Ibadan     BBQ Chicken   4000         5  08:47:19
1807  1808  2015-12-03   Lekki      Hot Veggie   4000         2  08:47:21
1808  1809  2015-12-07   Ikoyi  Pepperoni Suya   3000         4  08:47:22
1809  1810  2015-12-14  Ibadan      Hot Veggie   4000         1  08:47:22

      Revenue  Snap
1805    15000  3005
1806    20000  4005
1807     8000  4002
1808    12000  3004
1809     4000  4001
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1810  1811  2015-12-15     Ikoyi      Pepperoni Feast   4000         5
1811  1812  2015-12-07     Ikoyi  Hot Pepperoni Feast   4000         2
1812  1813  2015-12-04   Gbagada         Chicken Suya   4000         2
1813  1814  2015-12-14  Surulere          BBQ Chicken   4000         1
1814  1815  2015-12-10     Ikoyi            Beef Suya   3000         4

          Time  Revenue  Snap
1810  08:47:23    20000  4005
1811  08:47:24     8000  4002
1812  08:47:24     8000  4002
1813  08:47:25     4000  4001
1814  08:47:25    12000  3004
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1815  1816  2015-12-15     Ikoyi             Italiano   3000         5
1816  1817  2015-12-12     Lekki  Hot Pepperoni Feast   4000         3
1817  1818  2015-12-05   Gbagada     BBQ Philly Steak   4000         2
1818  1819  2015-12-07  Surulere         Chicken Suya   4000         3
1819  1820  2015-12-04  Surulere            Beef Suya   3000         1

          Time  Revenue  Snap
1815  08:47:26    15000  3005
1816  08:47:28    12000  4003
1817  08:47:28     8000  4002
1818  08:47:29    12000  4003

1819  08:47:29     3000  3001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
1820  1821  2015-12-09  Surulere    Chicken Suya   4000         3  08:47:29
1821  1822  2015-12-12   Gbagada    Chicken Suya   4000         3  08:47:30
1822  1823  2015-12-04   Gbagada   Chicken Feast   2000         1  08:47:33
1823  1824  2015-12-06  Surulere    Chicken Suya   4000         3  08:47:34
1824  1825  2015-12-05     Ikoyi  Pepperoni Suya   3000         4  08:47:37

      Revenue  Snap
1820    12000  4003
1821    12000  4003
1822     2000  2001
1823    12000  4003
1824    12000  3004
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
1825  1826  2015-12-15     Ikoyi  Pepperoni Suya   3000         2  08:47:40
1826  1827  2015-12-15     Ikoyi     BBQ Chicken   4000         2  08:47:41
1827  1828  2015-12-03     Ikoyi   Chicken Feast   2000         2  08:47:43
1828  1829  2015-12-13    Ibadan       Beef Suya   3000         1  08:47:45
1829  1830  2015-12-08  Surulere  Chicken Legend   2000         3  08:47:46

      Revenue  Snap
1825     6000  3002
1826     8000  4002
1827     4000  2002
1828     3000  3001
1829     6000  2003
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
1830  1831  2015-12-11     Ikoyi     Extravaganza   2000         5  08:47:49
1831  1832  2015-12-07  Surulere      BBQ Chicken   4000         2  08:47:52
1832  1833  2015-12-08     Lekki          Meatzaa   2000         1  08:47:52
1833  1834  2015-12-06    Ibadan  Pepperoni Feast   4000         3  08:47:52
1834  1835  2015-12-06  Surulere   Veggie Supreme   3000         4  08:47:53

      Revenue  Snap
1830    10000  2005
1831     8000  4002
1832     2000  2001
1833    12000  4003
1834    12000  3004
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
1835  1836  2015-12-10    Ikoyi      Chicken Suya   4000         4  08:47:56
1836  1837  2015-12-08    Lekki  BBQ Philly Steak   4000         3  08:47:57
1837  1838  2015-12-14  Gbagada         Margarita   4000         3  08:47:57
1838  1839  2015-12-07    Ikoyi    Pepperoni Suya   3000         3  08:47:59
1839  1840  2015-12-04   Ibadan    Veggie Supreme   3000         3  08:48:01

      Revenue  Snap
1835    16000  4004
1836    12000  4003
1837    12000  4003
1838     9000  3003
1839     9000  3003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1840  1841  2015-12-13     Ikoyi  Hot Pepperoni Feast   4000         3
1841  1842  2015-12-03  Surulere             Italiano   3000         1
1842  1843  2015-12-15   Gbagada       Chicken Legend   2000         5
1843  1844  2015-12-04    Ibadan         Chicken Suya   4000         3
1844  1845  2015-12-13     Ikoyi       Veggie Supreme   3000         5

          Time  Revenue  Snap
1840  08:48:03    12000  4003
1841  08:48:05     3000  3001
1842  08:48:05    10000  2005
1843  08:48:08    12000  4003
1844  08:48:09    15000  3005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1845  1846  2015-12-07   Gbagada             Italiano   3000         3
1846  1847  2015-12-07  Surulere            Beef Suya   3000         2
1847  1848  2015-12-05   Gbagada  Hot Pepperoni Feast   4000         3
1848  1849  2015-12-07  Surulere            Beef Suya   3000         5
1849  1850  2015-12-07     Ikoyi            Beef Suya   3000         2

          Time  Revenue  Snap
1845  08:48:09     9000  3003
1846  08:48:10     6000  3002
1847  08:48:12    12000  4003
1848  08:48:12    15000  3005
1849  08:48:13     6000  3002
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1850  1851  2015-12-09    Ibadan    Chicken Legend   2000         2  08:48:13
1851  1852  2015-12-03     Lekki  BBQ Philly Steak   4000         2  08:48:15
1852  1853  2015-12-06  Surulere       BBQ Chicken   4000         2  08:48:15
1853  1854  2015-12-03    Ibadan  BBQ Philly Steak   4000         5  08:48:17
1854  1855  2015-12-10  Surulere         Beef Suya   3000         1  08:48:21

      Revenue  Snap
1850     4000  2002
1851     8000  4002
1852     8000  4002
1853    20000  4005
1854     3000  3001
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
1855  1856  2015-12-12   Ibadan       BBQ Chicken   4000         5  08:48:22
1856  1857  2015-12-15    Lekki    Pepperoni Suya   3000         2  08:48:25
1857  1858  2015-12-10    Ikoyi  BBQ Philly Steak   4000         3  08:48:26
1858  1859  2015-12-05    Ikoyi        Hot Veggie   4000         4  08:48:27
1859  1860  2015-12-10  Gbagada  BBQ Philly Steak   4000         1  08:48:28

      Revenue  Snap
1855    20000  4005
1856     6000  3002
1857    12000  4003
1858    16000  4004
1859     4000  4001
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1860  1861  2015-12-13   Gbagada       BBQ Chicken   4000         1  08:48:33
1861  1862  2015-12-07  Surulere      Extravaganza   2000         5  08:48:34
1862  1863  2015-12-04    Ibadan  BBQ Philly Steak   4000         3  08:48:36
1863  1864  2015-12-13   Gbagada    Veggie Supreme   3000         2  08:48:36
1864  1865  2015-12-07    Ibadan     Chicken Feast   2000         3  08:48:37

      Revenue  Snap
1860     4000  4001
1861    10000  2005
1862    12000  4003
1863     6000  3002
1864     6000  2003
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
1865  1866  2015-12-12  Surulere        Beef Suya   3000         2  08:48:37
1866  1867  2015-12-09   Gbagada    Chicken Feast   2000         1  08:48:38
1867  1868  2015-12-05   Gbagada      BBQ Chicken   4000         5  08:48:38
1868  1869  2015-12-11     Ikoyi   Pepperoni Suya   3000         4  08:48:39
1869  1870  2015-12-14     Lekki  Pepperoni Feast   4000         2  08:48:40

      Revenue  Snap
1865     6000  3002
1866     2000  2001
1867    20000  4005
1868    12000  3004
1869     8000  4002
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1870  1871  2015-12-12     Lekki            Margarita   4000         2
1871  1872  2015-12-08    Ibadan            Beef Suya   3000         1
1872  1873  2015-12-05     Lekki  Hot Pepperoni Feast   4000         3
1873  1874  2015-12-15     Ikoyi            Beef Suya   3000         2
1874  1875  2015-12-07  Surulere  Hot Pepperoni Feast   4000         3

          Time  Revenue  Snap
1870  08:48:40     8000  4002
1871  08:48:41     3000  3001
1872  08:48:42    12000  4003
1873  08:48:43     6000  3002
1874  08:48:43    12000  4003
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
1875  1876  2015-12-11  Surulere        Italiano   3000         3  08:48:44
1876  1877  2015-12-09  Surulere   Chicken Feast   2000         2  08:48:45
1877  1878  2015-12-14    Ibadan    Chicken Bali   2000         3  08:48:47
1878  1879  2015-12-15   Gbagada        Italiano   3000         1  08:48:47
1879  1880  2015-12-11   Gbagada  Pepperoni Suya   3000         5  08:48:47

      Revenue  Snap
1875     9000  3003
1876     4000  2002
1877     6000  2003
1878     3000  3001
1879    15000  3005
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
1880  1881  2015-12-07  Surulere        Italiano   3000         1  08:48:47
1881  1882  2015-12-10     Lekki  Pepperoni Suya   3000         1  08:48:48
1882  1883  2015-12-05     Ikoyi         Meatzaa   2000         5  08:48:48
1883  1884  2015-12-10    Ibadan     BBQ Chicken   4000         3  08:48:48
1884  1885  2015-12-13     Ikoyi       Beef Suya   3000         5  08:48:49

      Revenue  Snap
1880     3000  3001
1881     3000  3001
1882    10000  2005
1883    12000  4003
1884    15000  3005
CHUNK BOSS
       S/N        Date   Branch    Pizza Sold  Price  Quantity      Time  \
1885  1886  2015-12-14  Gbagada     Beef Suya   3000         3  08:48:50
1886  1887  2015-12-10    Ikoyi  Chicken Suya   4000         1  08:48:50
1887  1888  2015-12-12  Gbagada     Beef Suya   3000         1  08:48:51
1888  1889  2015-12-11    Ikoyi  Chicken Suya   4000         2  08:48:51
1889  1890  2015-12-11   Ibadan  Extravaganza   2000         5  08:48:52

      Revenue  Snap
1885     9000  3003
1886     4000  4001
1887     3000  3001
1888     8000  4002
1889    10000  2005
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
1890  1891  2015-12-08  Gbagada     Chicken Feast   2000         4  08:48:52
1891  1892  2015-12-04  Gbagada  BBQ Philly Steak   4000         2  08:48:53
1892  1893  2015-12-14  Gbagada     Chicken Feast   2000         1  08:48:53
1893  1894  2015-12-15   Ibadan      Chicken Suya   4000         1  08:48:53
1894  1895  2015-12-15   Ibadan     Chicken Feast   2000         1  08:48:55

      Revenue  Snap
1890     8000  2004
1891     8000  4002
1892     2000  2001
1893     4000  4001
1894     2000  2001
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1895  1896  2015-12-03    Ibadan     Chicken Feast   2000         2  08:48:56
1896  1897  2015-12-09     Lekki       BBQ Chicken   4000         4  08:48:59
1897  1898  2015-12-04     Ikoyi  BBQ Philly Steak   4000         2  08:48:59
1898  1899  2015-12-09    Ibadan      Chicken Suya   4000         4  08:48:59
1899  1900  2015-12-06  Surulere         Margarita   4000         5  08:49:00

      Revenue  Snap
1895     4000  2002
1896    16000  4004
1897     8000  4002
1898    16000  4004
1899    20000  4005

CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1900  1901  2015-12-09     Lekki       Veggie Supreme   3000         4
1901  1902  2015-12-12     Lekki         Chicken Bali   2000         3
1902  1903  2015-12-06  Surulere            Beef Suya   3000         5
1903  1904  2015-12-04     Lekki  Hot Pepperoni Feast   4000         1
1904  1905  2015-12-04     Ikoyi           Hot Veggie   4000         1

          Time  Revenue  Snap
1900  08:49:00    12000  3004
1901  08:49:03     6000  2003
1902  08:49:05    15000  3005
1903  08:49:06     4000  4001
1904  08:49:08     4000  4001
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1905  1906  2015-12-06     Ikoyi           Meatzaa   2000         1  08:49:10
1906  1907  2015-12-08   Gbagada    Chicken Legend   2000         2  08:49:10
1907  1908  2015-12-14   Gbagada  BBQ Philly Steak   4000         2  08:49:12
1908  1909  2015-12-05  Surulere    Veggie Supreme   3000         2  08:49:14
1909  1910  2015-12-06     Ikoyi      Chicken Bali   2000         3  08:49:14

      Revenue  Snap
1905     2000  2001
1906     4000  2002
1907     8000  4002
1908     6000  3002
1909     6000  2003
CHUNK BOSS
       S/N        Date  Branch       Pizza Sold  Price  Quantity      Time  \
1910  1911  2015-12-14   Lekki     Chicken Bali   2000         2  08:49:15
1911  1912  2015-12-03  Ibadan        Margarita   4000         5  08:49:16
1912  1913  2015-12-08  Ibadan   Veggie Supreme   3000         3  08:49:19
1913  1914  2015-12-14   Ikoyi     Chicken Suya   4000         3  08:49:19
1914  1915  2015-12-12   Ikoyi  Pepperoni Feast   4000         4  08:49:21

      Revenue  Snap
1910     4000  2002
1911    20000  4005
1912     9000  3003
1913    12000  4003
1914    16000  4004
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
1915  1916  2015-12-05   Ibadan  Chicken Legend   2000         5  08:49:21
1916  1917  2015-12-12    Ikoyi        Italiano   3000         3  08:49:22
1917  1918  2015-12-04   Ibadan   Chicken Feast   2000         5  08:49:23
1918  1919  2015-12-08   Ibadan    Chicken Bali   2000         4  08:49:23
1919  1920  2015-12-05  Gbagada  Veggie Supreme   3000         1  08:49:23

      Revenue  Snap
1915    10000  2005
1916     9000  3003
1917    10000  2005
1918     8000  2004
1919     3000  3001
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1920  1921  2015-12-08     Lekki       BBQ Chicken   4000         1  08:49:24
1921  1922  2015-12-13  Surulere   Pepperoni Feast   4000         5  08:49:26
1922  1923  2015-12-11     Lekki  BBQ Philly Steak   4000         4  08:49:30
1923  1924  2015-12-04    Ibadan    Veggie Supreme   3000         5  08:49:31
1924  1925  2015-12-14   Gbagada         Margarita   4000         2  08:49:32

      Revenue  Snap
1920     4000  4001
1921    20000  4005
1922    16000  4004
1923    15000  3005
1924     8000  4002
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
1925  1926  2015-12-09     Lekki         Meatzaa   2000         5  08:49:32
1926  1927  2015-12-04  Surulere  Chicken Legend   2000         5  08:49:33
1927  1928  2015-12-13    Ibadan        Italiano   3000         4  08:49:42
1928  1929  2015-12-03     Ikoyi        Italiano   3000         5  08:49:43
1929  1930  2015-12-03     Ikoyi        Italiano   3000         3  08:49:44

      Revenue  Snap
1925    10000  2005
1926    10000  2005
1927    12000  3004
1928    15000  3005
1929     9000  3003
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
1930  1931  2015-12-07   Ibadan         Meatzaa   2000         3  08:49:45
1931  1932  2015-12-08  Gbagada  Veggie Supreme   3000         4  08:49:45
1932  1933  2015-12-14    Ikoyi        Italiano   3000         1  08:49:46
1933  1934  2015-12-12    Lekki  Chicken Legend   2000         4  08:49:46
1934  1935  2015-12-07   Ibadan  Veggie Supreme   3000         5  08:49:46

      Revenue  Snap
1930     6000  2003
1931    12000  3004
1932     3000  3001
1933     8000  2004
1934    15000  3005
CHUNK BOSS
       S/N        Date  Branch      Pizza Sold  Price  Quantity      Time  \
1935  1936  2015-12-08  Ibadan  Pepperoni Suya   3000         2  08:49:46
1936  1937  2015-12-15   Ikoyi       Beef Suya   3000         2  08:49:48
1937  1938  2015-12-07  Ibadan    Chicken Suya   4000         5  08:49:50
1938  1939  2015-12-05  Ibadan  Pepperoni Suya   3000         1  08:49:50
1939  1940  2015-12-04  Ibadan   Chicken Feast   2000         1  08:49:51

      Revenue  Snap
1935     6000  3002
1936     6000  3002
1937    20000  4005
1938     3000  3001
1939     2000  2001
CHUNK BOSS
       S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
1940  1941  2015-12-08    Lekki   Pepperoni Suya   3000         3  08:49:56
1941  1942  2015-12-14  Gbagada      BBQ Chicken   4000         2  08:49:58
1942  1943  2015-12-11    Lekki        Beef Suya   3000         4  08:49:58
1943  1944  2015-12-08  Gbagada  Pepperoni Feast   4000         1  08:49:59
1944  1945  2015-12-07  Gbagada        Margarita   4000         3  08:50:00

      Revenue  Snap
1940     9000  3003
1941     8000  4002
1942    12000  3004
1943     4000  4001
1944    12000  4003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1945  1946  2015-12-10  Surulere       Pepperoni Suya   3000         1
1946  1947  2015-12-08     Lekki              Meatzaa   2000         4
1947  1948  2015-12-09    Ibadan  Hot Pepperoni Feast   4000         1
1948  1949  2015-12-14    Ibadan            Margarita   4000         1
1949  1950  2015-12-04    Ibadan            Margarita   4000         3

          Time  Revenue  Snap
1945  08:50:03     3000  3001
1946  08:50:04     8000  2004
1947  08:50:04     4000  4001
1948  08:50:04     4000  4001
1949  08:50:06    12000  4003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1950  1951  2015-12-13  Surulere              Meatzaa   2000         5
1951  1952  2015-12-04     Lekki      Pepperoni Feast   4000         2
1952  1953  2015-12-05   Gbagada            Margarita   4000         3
1953  1954  2015-12-11    Ibadan  Hot Pepperoni Feast   4000         5
1954  1955  2015-12-10   Gbagada         Chicken Bali   2000         5

          Time  Revenue  Snap
1950  08:50:06    10000  2005
1951  08:50:11     8000  4002
1952  08:50:12    12000  4003
1953  08:50:14    20000  4005
1954  08:50:15    10000  2005
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
1955  1956  2015-12-09    Ikoyi       Margarita   4000         2  08:50:16
1956  1957  2015-12-12    Lekki    Extravaganza   2000         3  08:50:19
1957  1958  2015-12-06   Ibadan    Chicken Bali   2000         2  08:50:19
1958  1959  2015-12-05    Ikoyi     BBQ Chicken   4000         4  08:50:21
1959  1960  2015-12-07  Gbagada  Veggie Supreme   3000         1  08:50:21

      Revenue  Snap
1955     8000  4002
1956     6000  2003
1957     4000  2002
1958    16000  4004
1959     3000  3001
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
1960  1961  2015-12-07   Gbagada       Hot Veggie   4000         3  08:50:22
1961  1962  2015-12-14   Gbagada          Meatzaa   2000         2  08:50:22
1962  1963  2015-12-05  Surulere      BBQ Chicken   4000         1  08:50:24
1963  1964  2015-12-09   Gbagada    Chicken Feast   2000         1  08:50:25
1964  1965  2015-12-12     Lekki  Pepperoni Feast   4000         4  08:50:26

      Revenue  Snap
1960    12000  4003
1961     4000  2002
1962     4000  4001
1963     2000  2001
1964    16000  4004
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
1965  1966  2015-12-08   Ibadan      Hot Veggie   4000         4  08:50:28
1966  1967  2015-12-14   Ibadan    Chicken Suya   4000         1  08:50:28
1967  1968  2015-12-15    Lekki    Extravaganza   2000         1  08:50:28
1968  1969  2015-12-13    Ikoyi  Chicken Legend   2000         3  08:50:29
1969  1970  2015-12-03  Gbagada    Chicken Suya   4000         5  08:50:29

      Revenue  Snap
1965    16000  4004
1966     4000  4001
1967     2000  2001
1968     6000  2003
1969    20000  4005
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
1970  1971  2015-12-12  Gbagada       Margarita   4000         2  08:50:30
1971  1972  2015-12-12    Lekki  Pepperoni Suya   3000         4  08:50:30
1972  1973  2015-12-04    Lekki    Extravaganza   2000         2  08:50:33
1973  1974  2015-12-09  Gbagada      Hot Veggie   4000         3  08:50:34
1974  1975  2015-12-09    Ikoyi       Beef Suya   3000         1  08:50:38

      Revenue  Snap
1970     8000  4002
1971    12000  3004
1972     4000  2002
1973    12000  4003
1974     3000  3001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
1975  1976  2015-12-09   Gbagada  Pepperoni Suya   3000         4  08:50:39
1976  1977  2015-12-09  Surulere        Italiano   3000         2  08:50:41
1977  1978  2015-12-14     Ikoyi     BBQ Chicken   4000         1  08:50:41
1978  1979  2015-12-10     Ikoyi  Chicken Legend   2000         2  08:50:42
1979  1980  2015-12-10  Surulere    Chicken Bali   2000         2  08:50:43

      Revenue  Snap
1975    12000  3004
1976     6000  3002
1977     4000  4001
1978     4000  2002
1979     4000  2002
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
1980  1981  2015-12-03     Ikoyi    Pepperoni Suya   3000         5  08:50:45
1981  1982  2015-12-13  Surulere   Pepperoni Feast   4000         2  08:50:46
1982  1983  2015-12-15   Gbagada  BBQ Philly Steak   4000         5  08:50:46
1983  1984  2015-12-05  Surulere      Extravaganza   2000         3  08:50:46
1984  1985  2015-12-05  Surulere   Pepperoni Feast   4000         5  08:50:46

      Revenue  Snap
1980    15000  3005
1981     8000  4002
1982    20000  4005
1983     6000  2003
1984    20000  4005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
1985  1986  2015-12-13   Gbagada         Chicken Suya   4000         4
1986  1987  2015-12-06  Surulere          BBQ Chicken   4000         5
1987  1988  2015-12-03   Gbagada       Chicken Legend   2000         1
1988  1989  2015-12-13     Ikoyi           Hot Veggie   4000         5
1989  1990  2015-12-13     Ikoyi  Hot Pepperoni Feast   4000         2

          Time  Revenue  Snap
1985  08:50:46    16000  4004
1986  08:50:50    20000  4005
1987  08:50:51     2000  2001
1988  08:50:54    20000  4005
1989  08:50:54     8000  4002
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
1990  1991  2015-12-10    Ikoyi      Pepperoni Feast   4000         3
1991  1992  2015-12-09  Gbagada  Hot Pepperoni Feast   4000         4
1992  1993  2015-12-04    Lekki         Chicken Bali   2000         1
1993  1994  2015-12-14   Ibadan         Chicken Bali   2000         4
1994  1995  2015-12-12    Ikoyi             Italiano   3000         2

          Time  Revenue  Snap
1990  08:50:55    12000  4003
1991  08:50:56    16000  4004
1992  08:50:57     2000  2001
1993  08:50:57     8000  2004
1994  08:50:59     6000  3002
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
1995  1996  2015-12-06    Ibadan  Chicken Legend   2000         4  08:51:00
1996  1997  2015-12-04  Surulere  Chicken Legend   2000         2  08:51:01
1997  1998  2015-12-06   Gbagada  Veggie Supreme   3000         2  08:51:01
1998  1999  2015-12-08     Lekki         Meatzaa   2000         1  08:51:02
1999  2000  2015-12-08     Ikoyi        Italiano   3000         5  08:51:02

      Revenue  Snap
1995     8000  2004
1996     4000  2002
1997     6000  3002
1998     2000  2001
1999    15000  3005
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
2000  2001  2015-12-15    Ikoyi   Chicken Feast   2000         1  08:51:03
2001  2002  2015-12-14   Ibadan     BBQ Chicken   4000         4  08:51:03
2002  2003  2015-12-15    Lekki        Italiano   3000         1  08:51:07
2003  2004  2015-12-15  Gbagada  Veggie Supreme   3000         5  08:51:07
2004  2005  2015-12-04   Ibadan    Chicken Suya   4000         2  08:51:08

      Revenue  Snap
2000     2000  2001
2001    16000  4004
2002     3000  3001
2003    15000  3005
2004     8000  4002
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
2005  2006  2015-12-08     Lekki  BBQ Philly Steak   4000         5  08:51:09
2006  2007  2015-12-13     Ikoyi   Pepperoni Feast   4000         2  08:51:10
2007  2008  2015-12-13     Lekki      Chicken Suya   4000         2  08:51:11
2008  2009  2015-12-13     Ikoyi        Hot Veggie   4000         4  08:51:11
2009  2010  2015-12-12  Surulere       BBQ Chicken   4000         1  08:51:11

      Revenue  Snap
2005    20000  4005
2006     8000  4002
2007     8000  4002
2008    16000  4004
2009     4000  4001
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2010  2011  2015-12-15     Lekki           Hot Veggie   4000         1
2011  2012  2015-12-08  Surulere  Hot Pepperoni Feast   4000         2
2012  2013  2015-12-04   Gbagada          BBQ Chicken   4000         5
2013  2014  2015-12-06     Lekki         Extravaganza   2000         4
2014  2015  2015-12-08   Gbagada  Hot Pepperoni Feast   4000         5

          Time  Revenue  Snap
2010  08:51:12     4000  4001
2011  08:51:12     8000  4002
2012  08:51:12    20000  4005
2013  08:51:13     8000  2004
2014  08:51:14    20000  4005
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
2015  2016  2015-12-12    Ibadan     Chicken Bali   2000         3  08:51:16
2016  2017  2015-12-15     Lekki  Pepperoni Feast   4000         1  08:51:18
2017  2018  2015-12-12    Ibadan        Beef Suya   3000         2  08:51:19
2018  2019  2015-12-08   Gbagada    Chicken Feast   2000         1  08:51:19
2019  2020  2015-12-12  Surulere    Chicken Feast   2000         1  08:51:20

      Revenue  Snap
2015     6000  2003
2016     4000  4001
2017     6000  3002
2018     2000  2001
2019     2000  2001
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
2020  2021  2015-12-14   Gbagada   Pepperoni Suya   3000         2  08:51:21
2021  2022  2015-12-07   Gbagada       Hot Veggie   4000         3  08:51:21
2022  2023  2015-12-09   Gbagada     Chicken Suya   4000         1  08:51:22
2023  2024  2015-12-08     Lekki         Italiano   3000         3  08:51:25
2024  2025  2015-12-04  Surulere  Pepperoni Feast   4000         5  08:51:26

      Revenue  Snap
2020     6000  3002
2021    12000  4003
2022     4000  4001
2023     9000  3003
2024    20000  4005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2025  2026  2015-12-12     Lekki              Meatzaa   2000         4
2026  2027  2015-12-13     Lekki         Chicken Bali   2000         3
2027  2028  2015-12-11    Ibadan  Hot Pepperoni Feast   4000         1
2028  2029  2015-12-08    Ibadan        Chicken Feast   2000         2
2029  2030  2015-12-08  Surulere            Margarita   4000         1

          Time  Revenue  Snap
2025  08:51:26     8000  2004
2026  08:51:26     6000  2003
2027  08:51:28     4000  4001
2028  08:51:29     4000  2002
2029  08:51:29     4000  4001
CHUNK BOSS
       S/N        Date Branch           Pizza Sold  Price  Quantity      Time  \
2030  2031  2015-12-08  Lekki            Beef Suya   3000         4  08:51:30
2031  2032  2015-12-13  Lekki              Meatzaa   2000         2  08:51:31
2032  2033  2015-12-03  Ikoyi              Meatzaa   2000         2  08:51:32
2033  2034  2015-12-07  Ikoyi  Hot Pepperoni Feast   4000         3  08:51:33
2034  2035  2015-12-08  Lekki       Chicken Legend   2000         4  08:51:33

      Revenue  Snap
2030    12000  3004
2031     4000  2002
2032     4000  2002
2033    12000  4003
2034     8000  2004

CHUNK BOSS
       S/N        Date   Branch    Pizza Sold  Price  Quantity      Time  \
2035  2036  2015-12-03    Lekki    Hot Veggie   4000         1  08:51:33
2036  2037  2015-12-07    Ikoyi       Meatzaa   2000         3  08:51:34
2037  2038  2015-12-07    Ikoyi     Margarita   4000         3  08:51:35
2038  2039  2015-12-14  Gbagada     Beef Suya   3000         5  08:51:36
2039  2040  2015-12-14  Gbagada  Extravaganza   2000         3  08:51:36

      Revenue  Snap
2035     4000  4001
2036     6000  2003
2037    12000  4003
2038    15000  3005
2039     6000  2003
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
2040  2041  2015-12-11    Lekki       Beef Suya   3000         2  08:51:40
2041  2042  2015-12-09   Ibadan    Extravaganza   2000         4  08:51:40
2042  2043  2015-12-07  Gbagada  Chicken Legend   2000         5  08:51:41
2043  2044  2015-12-14    Ikoyi  Veggie Supreme   3000         3  08:51:41
2044  2045  2015-12-08   Ibadan    Chicken Bali   2000         4  08:51:42

      Revenue  Snap
2040     6000  3002
2041     8000  2004
2042    10000  2005
2043     9000  3003
2044     8000  2004
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
2045  2046  2015-12-12  Surulere     Chicken Feast   2000         3  08:51:42
2046  2047  2015-12-13    Ibadan       BBQ Chicken   4000         3  08:51:46
2047  2048  2015-12-09   Gbagada    Chicken Legend   2000         5  08:51:48
2048  2049  2015-12-15     Lekki   Pepperoni Feast   4000         3  08:51:51
2049  2050  2015-12-06   Gbagada  BBQ Philly Steak   4000         2  08:51:51

      Revenue  Snap
2045     6000  2003
2046    12000  4003
2047    10000  2005
2048    12000  4003
2049     8000  4002
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
2050  2051  2015-12-09  Surulere     Extravaganza   2000         1  08:51:52
2051  2052  2015-12-14     Lekki  Pepperoni Feast   4000         4  08:51:53
2052  2053  2015-12-15     Ikoyi   Veggie Supreme   3000         5  08:51:58
2053  2054  2015-12-09     Lekki     Extravaganza   2000         3  08:51:59
2054  2055  2015-12-09    Ibadan        Margarita   4000         2  08:52:00

      Revenue  Snap
2050     2000  2001
2051    16000  4004
2052    15000  3005
2053     6000  2003
2054     8000  4002
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
2055  2056  2015-12-12     Ikoyi  Pepperoni Feast   4000         2  08:52:01
2056  2057  2015-12-12  Surulere        Margarita   4000         4  08:52:03
2057  2058  2015-12-13     Ikoyi     Chicken Suya   4000         4  08:52:06
2058  2059  2015-12-06    Ibadan        Beef Suya   3000         2  08:52:06
2059  2060  2015-12-04     Lekki         Italiano   3000         4  08:52:06

      Revenue  Snap
2055     8000  4002
2056    16000  4004
2057    16000  4004
2058     6000  3002
2059    12000  3004
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2060  2061  2015-12-09   Gbagada              Meatzaa   2000         2
2061  2062  2015-12-07    Ibadan       Pepperoni Suya   3000         3
2062  2063  2015-12-13     Ikoyi            Margarita   4000         4
2063  2064  2015-12-11     Lekki  Hot Pepperoni Feast   4000         5
2064  2065  2015-12-13  Surulere         Chicken Bali   2000         2

          Time  Revenue  Snap
2060  08:52:07     4000  2002
2061  08:52:08     9000  3003
2062  08:52:14    16000  4004
2063  08:52:14    20000  4005
2064  08:52:14     4000  2002
CHUNK BOSS
       S/N        Date  Branch      Pizza Sold  Price  Quantity      Time  \
2065  2066  2015-12-08   Lekki  Pepperoni Suya   3000         2  08:52:15
2066  2067  2015-12-15  Ibadan  Chicken Legend   2000         4  08:52:17
2067  2068  2015-12-11  Ibadan        Italiano   3000         5  08:52:18
2068  2069  2015-12-09  Ibadan  Pepperoni Suya   3000         1  08:52:19
2069  2070  2015-12-11   Lekki  Pepperoni Suya   3000         2  08:52:20

      Revenue  Snap
2065     6000  3002
2066     8000  2004
2067    15000  3005
2068     3000  3001
2069     6000  3002
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
2070  2071  2015-12-05  Gbagada  Chicken Legend   2000         2  08:52:20
2071  2072  2015-12-06    Lekki    Extravaganza   2000         2  08:52:21
2072  2073  2015-12-15    Lekki   Chicken Feast   2000         5  08:52:22
2073  2074  2015-12-15    Ikoyi  Chicken Legend   2000         4  08:52:25
2074  2075  2015-12-12    Ikoyi   Chicken Feast   2000         3  08:52:25

      Revenue  Snap
2070     4000  2002
2071     4000  2002
2072    10000  2005
2073     8000  2004
2074     6000  2003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2075  2076  2015-12-11     Ikoyi        Chicken Feast   2000         2
2076  2077  2015-12-11     Lekki       Pepperoni Suya   3000         3
2077  2078  2015-12-07  Surulere       Pepperoni Suya   3000         3
2078  2079  2015-12-10    Ibadan     BBQ Philly Steak   4000         3
2079  2080  2015-12-08  Surulere  Hot Pepperoni Feast   4000         4

          Time  Revenue  Snap
2075  08:52:26     4000  2002
2076  08:52:26     9000  3003
2077  08:52:26     9000  3003
2078  08:52:27    12000  4003
2079  08:52:28    16000  4004
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2080  2081  2015-12-10     Lekki      Pepperoni Feast   4000         4
2081  2082  2015-12-14    Ibadan             Italiano   3000         5
2082  2083  2015-12-13    Ibadan            Beef Suya   3000         2
2083  2084  2015-12-05   Gbagada  Hot Pepperoni Feast   4000         5
2084  2085  2015-12-11  Surulere     BBQ Philly Steak   4000         2

          Time  Revenue  Snap
2080  08:52:29    16000  4004
2081  08:52:31    15000  3005
2082  08:52:32     6000  3002
2083  08:52:35    20000  4005
2084  08:52:35     8000  4002
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
2085  2086  2015-12-07  Surulere     Chicken Feast   2000         3  08:52:36
2086  2087  2015-12-09     Ikoyi    Pepperoni Suya   3000         1  08:52:37
2087  2088  2015-12-12  Surulere  BBQ Philly Steak   4000         5  08:52:38
2088  2089  2015-12-05    Ibadan    Veggie Supreme   3000         5  08:52:38
2089  2090  2015-12-05     Ikoyi    Veggie Supreme   3000         2  08:52:39

      Revenue  Snap
2085     6000  2003
2086     3000  3001
2087    20000  4005
2088    15000  3005
2089     6000  3002
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2090  2091  2015-12-14  Surulere       Pepperoni Suya   3000         1
2091  2092  2015-12-04    Ibadan  Hot Pepperoni Feast   4000         2
2092  2093  2015-12-06     Lekki      Pepperoni Feast   4000         3
2093  2094  2015-12-14     Ikoyi      Pepperoni Feast   4000         2
2094  2095  2015-12-03   Gbagada           Hot Veggie   4000         4

          Time  Revenue  Snap
2090  08:52:40     3000  3001
2091  08:52:40     8000  4002
2092  08:52:41    12000  4003
2093  08:52:44     8000  4002
2094  08:52:46    16000  4004
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
2095  2096  2015-12-11  Surulere    Veggie Supreme   3000         4  08:52:47
2096  2097  2015-12-14     Lekki  BBQ Philly Steak   4000         2  08:52:48
2097  2098  2015-12-13    Ibadan      Chicken Bali   2000         2  08:52:52
2098  2099  2015-12-09  Surulere       BBQ Chicken   4000         4  08:52:52
2099  2100  2015-12-14  Surulere  BBQ Philly Steak   4000         3  08:52:52

      Revenue  Snap
2095    12000  3004
2096     8000  4002
2097     4000  2002
2098    16000  4004
2099    12000  4003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2100  2101  2015-12-03     Ikoyi              Meatzaa   2000         3
2101  2102  2015-12-09    Ibadan  Hot Pepperoni Feast   4000         1
2102  2103  2015-12-08  Surulere        Chicken Feast   2000         4
2103  2104  2015-12-07     Ikoyi            Margarita   4000         2
2104  2105  2015-12-13    Ibadan       Veggie Supreme   3000         5

          Time  Revenue  Snap
2100  08:52:53     6000  2003
2101  08:52:53     4000  4001
2102  08:52:53     8000  2004
2103  08:52:54     8000  4002
2104  08:52:54    15000  3005
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2105  2106  2015-12-12  Surulere    Chicken Bali   2000         5  08:52:55
2106  2107  2015-12-05    Ibadan        Italiano   3000         5  08:52:55
2107  2108  2015-12-13    Ibadan    Extravaganza   2000         3  08:52:58
2108  2109  2015-12-07     Ikoyi  Pepperoni Suya   3000         4  08:52:58
2109  2110  2015-12-07     Lekki  Veggie Supreme   3000         2  08:52:58

      Revenue  Snap
2105    10000  2005
2106    15000  3005
2107     6000  2003
2108    12000  3004
2109     6000  3002
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2110  2111  2015-12-12   Gbagada     BBQ Chicken   4000         3  08:52:59
2111  2112  2015-12-11  Surulere    Extravaganza   2000         1  08:52:59
2112  2113  2015-12-08     Lekki  Veggie Supreme   3000         2  08:52:59
2113  2114  2015-12-09  Surulere       Margarita   4000         1  08:52:59
2114  2115  2015-12-04     Ikoyi  Chicken Legend   2000         3  08:53:00

      Revenue  Snap
2110    12000  4003
2111     2000  2001
2112     6000  3002
2113     4000  4001
2114     6000  2003
CHUNK BOSS
       S/N        Date    Branch     Pizza Sold  Price  Quantity      Time  \
2115  2116  2015-12-15     Ikoyi      Margarita   4000         1  08:53:00
2116  2117  2015-12-07  Surulere       Italiano   3000         3  08:53:03
2117  2118  2015-12-15  Surulere   Chicken Suya   4000         2  08:53:05
2118  2119  2015-12-05    Ibadan       Italiano   3000         1  08:53:07
2119  2120  2015-12-05     Lekki  Chicken Feast   2000         3  08:53:08

      Revenue  Snap
2115     4000  4001
2116     9000  3003
2117     8000  4002
2118     3000  3001
2119     6000  2003
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
2120  2121  2015-12-04    Ibadan   Veggie Supreme   3000         4  08:53:10
2121  2122  2015-12-07  Surulere       Hot Veggie   4000         3  08:53:16
2122  2123  2015-12-08     Ikoyi  Pepperoni Feast   4000         2  08:53:17
2123  2124  2015-12-03     Ikoyi          Meatzaa   2000         5  08:53:19
2124  2125  2015-12-08     Lekki         Italiano   3000         2  08:53:23

      Revenue  Snap
2120    12000  3004
2121    12000  4003
2122     8000  4002
2123    10000  2005
2124     6000  3002
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
2125  2126  2015-12-05    Ibadan   Pepperoni Feast   4000         4  08:53:24
2126  2127  2015-12-03   Gbagada  BBQ Philly Steak   4000         3  08:53:24
2127  2128  2015-12-10    Ibadan       BBQ Chicken   4000         2  08:53:25
2128  2129  2015-12-08  Surulere      Chicken Suya   4000         1  08:53:25
2129  2130  2015-12-07     Lekki        Hot Veggie   4000         2  08:53:25

      Revenue  Snap
2125    16000  4004
2126    12000  4003
2127     8000  4002
2128     4000  4001
2129     8000  4002

CHUNK BOSS
       S/N        Date  Branch       Pizza Sold  Price  Quantity      Time  \
2130  2131  2015-12-08  Ibadan          Meatzaa   2000         3  08:53:26
2131  2132  2015-12-06  Ibadan   Veggie Supreme   3000         2  08:53:26
2132  2133  2015-12-05   Lekki     Chicken Suya   4000         3  08:53:27
2133  2134  2015-12-05   Lekki  Pepperoni Feast   4000         3  08:53:28
2134  2135  2015-12-03  Ibadan   Pepperoni Suya   3000         2  08:53:28

      Revenue  Snap
2130     6000  2003
2131     6000  3002
2132    12000  4003
2133    12000  4003
2134     6000  3002
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2135  2136  2015-12-05   Gbagada     BBQ Chicken   4000         2  08:53:33
2136  2137  2015-12-07  Surulere  Chicken Legend   2000         2  08:53:33
2137  2138  2015-12-04     Lekki    Extravaganza   2000         1  08:53:33
2138  2139  2015-12-06  Surulere    Chicken Suya   4000         4  08:53:33
2139  2140  2015-12-10    Ibadan      Hot Veggie   4000         3  08:53:34

      Revenue  Snap
2135     8000  4002
2136     4000  2002
2137     2000  2001
2138    16000  4004
2139    12000  4003
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
2140  2141  2015-12-04  Surulere     Extravaganza   2000         5  08:53:36
2141  2142  2015-12-10     Ikoyi         Italiano   3000         3  08:53:37
2142  2143  2015-12-12   Gbagada  Pepperoni Feast   4000         1  08:53:38
2143  2144  2015-12-12  Surulere        Margarita   4000         1  08:53:39
2144  2145  2015-12-15    Ibadan       Hot Veggie   4000         5  08:53:40

      Revenue  Snap
2140    10000  2005
2141     9000  3003
2142     4000  4001
2143     4000  4001
2144    20000  4005
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
2145  2146  2015-12-12    Ibadan           Meatzaa   2000         1  08:53:42
2146  2147  2015-12-12     Ikoyi      Chicken Suya   4000         5  08:53:42
2147  2148  2015-12-15  Surulere   Pepperoni Feast   4000         2  08:53:44
2148  2149  2015-12-13  Surulere         Beef Suya   3000         5  08:53:45
2149  2150  2015-12-09    Ibadan  BBQ Philly Steak   4000         3  08:53:45

      Revenue  Snap
2145     2000  2001
2146    20000  4005
2147     8000  4002
2148    15000  3005
2149    12000  4003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2150  2151  2015-12-09     Lekki       Chicken Legend   2000         5
2151  2152  2015-12-11  Surulere      Pepperoni Feast   4000         5
2152  2153  2015-12-11     Ikoyi          BBQ Chicken   4000         5
2153  2154  2015-12-12   Gbagada  Hot Pepperoni Feast   4000         5
2154  2155  2015-12-10     Lekki         Chicken Suya   4000         2

          Time  Revenue  Snap
2150  08:53:45    10000  2005
2151  08:53:47    20000  4005
2152  08:53:47    20000  4005
2153  08:53:49    20000  4005
2154  08:53:51     8000  4002
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
2155  2156  2015-12-06   Ibadan       Pepperoni Suya   3000         5
2156  2157  2015-12-15  Gbagada             Italiano   3000         1
2157  2158  2015-12-06   Ibadan  Hot Pepperoni Feast   4000         4
2158  2159  2015-12-13  Gbagada  Hot Pepperoni Feast   4000         4
2159  2160  2015-12-10  Gbagada  Hot Pepperoni Feast   4000         3

          Time  Revenue  Snap
2155  08:53:52    15000  3005
2156  08:53:53     3000  3001
2157  08:53:54    16000  4004
2158  08:53:56    16000  4004
2159  08:53:57    12000  4003
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2160  2161  2015-12-10     Lekki      Hot Veggie   4000         4  08:53:57
2161  2162  2015-12-11   Gbagada        Italiano   3000         5  08:53:58
2162  2163  2015-12-12     Ikoyi  Veggie Supreme   3000         4  08:54:00
2163  2164  2015-12-10     Lekki      Hot Veggie   4000         5  08:54:01
2164  2165  2015-12-07  Surulere  Chicken Legend   2000         2  08:54:03

      Revenue  Snap
2160    16000  4004
2161    15000  3005
2162    12000  3004
2163    20000  4005
2164     4000  2002
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
2165  2166  2015-12-06    Ikoyi  Pepperoni Suya   3000         5  08:54:03
2166  2167  2015-12-03  Gbagada  Veggie Supreme   3000         2  08:54:03
2167  2168  2015-12-04    Lekki  Veggie Supreme   3000         2  08:54:05
2168  2169  2015-12-14    Ikoyi    Extravaganza   2000         3  08:54:06
2169  2170  2015-12-12   Ibadan       Beef Suya   3000         5  08:54:06

      Revenue  Snap
2165    15000  3005
2166     6000  3002
2167     6000  3002
2168     6000  2003
2169    15000  3005
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2170  2171  2015-12-14  Surulere  Veggie Supreme   3000         4  08:54:06
2171  2172  2015-12-13  Surulere  Pepperoni Suya   3000         2  08:54:07
2172  2173  2015-12-11    Ibadan        Italiano   3000         1  08:54:09
2173  2174  2015-12-14     Ikoyi      Hot Veggie   4000         3  08:54:09
2174  2175  2015-12-15     Ikoyi  Pepperoni Suya   3000         3  08:54:10

      Revenue  Snap
2170    12000  3004
2171     6000  3002
2172     3000  3001
2173    12000  4003
2174     9000  3003
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
2175  2176  2015-12-14  Surulere          Italiano   3000         5  08:54:10
2176  2177  2015-12-05     Ikoyi   Pepperoni Feast   4000         2  08:54:10
2177  2178  2015-12-12     Ikoyi  BBQ Philly Steak   4000         5  08:54:11
2178  2179  2015-12-03   Gbagada         Margarita   4000         2  08:54:12
2179  2180  2015-12-15  Surulere    Veggie Supreme   3000         5  08:54:15

      Revenue  Snap
2175    15000  3005
2176     8000  4002
2177    20000  4005
2178     8000  4002
2179    15000  3005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2180  2181  2015-12-04     Ikoyi  Hot Pepperoni Feast   4000         1
2181  2182  2015-12-06  Surulere       Chicken Legend   2000         2
2182  2183  2015-12-15    Ibadan       Veggie Supreme   3000         4
2183  2184  2015-12-15   Gbagada  Hot Pepperoni Feast   4000         4
2184  2185  2015-12-08     Ikoyi         Chicken Bali   2000         3

          Time  Revenue  Snap
2180  08:54:18     4000  4001
2181  08:54:18     4000  2002
2182  08:54:19    12000  3004
2183  08:54:20    16000  4004
2184  08:54:20     6000  2003
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
2185  2186  2015-12-08   Ibadan   Chicken Feast   2000         1  08:54:22
2186  2187  2015-12-03  Gbagada    Extravaganza   2000         3  08:54:24
2187  2188  2015-12-07  Gbagada         Meatzaa   2000         3  08:54:25
2188  2189  2015-12-14    Lekki  Veggie Supreme   3000         4  08:54:25
2189  2190  2015-12-13    Lekki   Chicken Feast   2000         4  08:54:28

      Revenue  Snap
2185     2000  2001
2186     6000  2003
2187     6000  2003
2188    12000  3004
2189     8000  2004
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2190  2191  2015-12-03  Surulere       Margarita   4000         5  08:54:30
2191  2192  2015-12-07    Ibadan      Hot Veggie   4000         4  08:54:31
2192  2193  2015-12-15     Ikoyi        Italiano   3000         4  08:54:31
2193  2194  2015-12-07     Ikoyi  Veggie Supreme   3000         3  08:54:31
2194  2195  2015-12-11  Surulere    Chicken Suya   4000         2  08:54:32

      Revenue  Snap
2190    20000  4005
2191    16000  4004
2192    12000  3004
2193     9000  3003
2194     8000  4002
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
2195  2196  2015-12-06    Ibadan   Pepperoni Feast   4000         2  08:54:33
2196  2197  2015-12-05   Gbagada    Chicken Legend   2000         5  08:54:35
2197  2198  2015-12-12    Ibadan  BBQ Philly Steak   4000         1  08:54:36
2198  2199  2015-12-08  Surulere      Chicken Suya   4000         4  08:54:38
2199  2200  2015-12-03  Surulere  BBQ Philly Steak   4000         4  08:54:39

      Revenue  Snap
2195     8000  4002
2196    10000  2005
2197     4000  4001
2198    16000  4004
2199    16000  4004

CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2200  2201  2015-12-08  Surulere  Veggie Supreme   3000         1  08:54:39
2201  2202  2015-12-15     Ikoyi    Chicken Suya   4000         4  08:54:41
2202  2203  2015-12-04    Ibadan       Beef Suya   3000         1  08:54:41
2203  2204  2015-12-13   Gbagada    Chicken Bali   2000         1  08:54:41
2204  2205  2015-12-06     Lekki    Extravaganza   2000         5  08:54:42

      Revenue  Snap
2200     3000  3001
2201    16000  4004
2202     3000  3001
2203     2000  2001
2204    10000  2005
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
2205  2206  2015-12-15  Gbagada     BBQ Chicken   4000         4  08:54:43
2206  2207  2015-12-11  Gbagada       Margarita   4000         2  08:54:44
2207  2208  2015-12-15   Ibadan       Beef Suya   3000         5  08:54:44
2208  2209  2015-12-13  Gbagada  Chicken Legend   2000         5  08:54:44
2209  2210  2015-12-04    Lekki    Extravaganza   2000         2  08:54:49

      Revenue  Snap
2205    16000  4004
2206     8000  4002
2207    15000  3005
2208    10000  2005
2209     4000  2002
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
2210  2211  2015-12-14  Gbagada        Hot Veggie   4000         3  08:54:50
2211  2212  2015-12-05    Lekki  BBQ Philly Steak   4000         4  08:54:53
2212  2213  2015-12-06  Gbagada      Extravaganza   2000         5  08:54:53
2213  2214  2015-12-09    Ikoyi  BBQ Philly Steak   4000         2  08:54:53
2214  2215  2015-12-06  Gbagada    Chicken Legend   2000         1  08:54:56

      Revenue  Snap
2210    12000  4003
2211    16000  4004
2212    10000  2005
2213     8000  4002
2214     2000  2001
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
2215  2216  2015-12-12   Ibadan   Pepperoni Feast   4000         2  08:55:00
2216  2217  2015-12-15    Ikoyi  BBQ Philly Steak   4000         3  08:55:01
2217  2218  2015-12-03  Gbagada         Margarita   4000         5  08:55:05
2218  2219  2015-12-15  Gbagada      Chicken Suya   4000         3  08:55:08
2219  2220  2015-12-13  Gbagada        Hot Veggie   4000         3  08:55:14

      Revenue  Snap
2215     8000  4002
2216    12000  4003
2217    20000  4005
2218    12000  4003
2219    12000  4003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2220  2221  2015-12-05   Gbagada       Veggie Supreme   3000         2
2221  2222  2015-12-08  Surulere     BBQ Philly Steak   4000         2
2222  2223  2015-12-06     Ikoyi          BBQ Chicken   4000         1
2223  2224  2015-12-11     Lekki       Veggie Supreme   3000         5
2224  2225  2015-12-07     Ikoyi  Hot Pepperoni Feast   4000         5

          Time  Revenue  Snap
2220  08:55:16     6000  3002
2221  08:55:16     8000  4002
2222  08:55:17     4000  4001
2223  08:55:18    15000  3005
2224  08:55:19    20000  4005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2225  2226  2015-12-03     Ikoyi              Meatzaa   2000         3
2226  2227  2015-12-15  Surulere       Chicken Legend   2000         1
2227  2228  2015-12-06  Surulere          BBQ Chicken   4000         5
2228  2229  2015-12-07   Gbagada          BBQ Chicken   4000         2
2229  2230  2015-12-13    Ibadan  Hot Pepperoni Feast   4000         3

          Time  Revenue  Snap
2225  08:55:20     6000  2003
2226  08:55:23     2000  2001
2227  08:55:23    20000  4005
2228  08:55:23     8000  4002
2229  08:55:24    12000  4003
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
2230  2231  2015-12-14  Surulere          Italiano   3000         4  08:55:24
2231  2232  2015-12-03     Ikoyi      Chicken Bali   2000         4  08:55:25
2232  2233  2015-12-03    Ibadan        Hot Veggie   4000         1  08:55:26
2233  2234  2015-12-09    Ibadan      Chicken Bali   2000         2  08:55:29
2234  2235  2015-12-07     Ikoyi  BBQ Philly Steak   4000         4  08:55:29

      Revenue  Snap
2230    12000  3004
2231     8000  2004
2232     4000  4001
2233     4000  2002
2234    16000  4004
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2235  2236  2015-12-12     Lekki    Chicken Suya   4000         4  08:55:30
2236  2237  2015-12-12  Surulere       Margarita   4000         1  08:55:33
2237  2238  2015-12-04   Gbagada   Chicken Feast   2000         4  08:55:36
2238  2239  2015-12-06     Lekki         Meatzaa   2000         4  08:55:38
2239  2240  2015-12-08     Lekki  Pepperoni Suya   3000         3  08:55:39

      Revenue  Snap
2235    16000  4004
2236     4000  4001
2237     8000  2004
2238     8000  2004
2239     9000  3003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2240  2241  2015-12-04  Surulere       Chicken Legend   2000         1
2241  2242  2015-12-03   Gbagada           Hot Veggie   4000         1
2242  2243  2015-12-04  Surulere         Extravaganza   2000         5
2243  2244  2015-12-12    Ibadan  Hot Pepperoni Feast   4000         1
2244  2245  2015-12-10     Lekki       Veggie Supreme   3000         4

          Time  Revenue  Snap
2240  08:55:40     2000  2001
2241  08:55:41     4000  4001
2242  08:55:41    10000  2005
2243  08:55:45     4000  4001
2244  08:55:50    12000  3004
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
2245  2246  2015-12-09    Lekki  BBQ Philly Steak   4000         4  08:55:51
2246  2247  2015-12-11    Ikoyi          Italiano   3000         5  08:55:51
2247  2248  2015-12-08    Ikoyi    Pepperoni Suya   3000         5  08:55:51
2248  2249  2015-12-05    Ikoyi       BBQ Chicken   4000         1  08:55:52
2249  2250  2015-12-15  Gbagada    Veggie Supreme   3000         3  08:55:53

      Revenue  Snap
2245    16000  4004
2246    15000  3005
2247    15000  3005
2248     4000  4001
2249     9000  3003
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2250  2251  2015-12-10  Surulere       Margarita   4000         3  08:55:53
2251  2252  2015-12-11     Ikoyi  Veggie Supreme   3000         3  08:55:54
2252  2253  2015-12-14    Ibadan    Chicken Bali   2000         4  08:55:57
2253  2254  2015-12-06     Lekki  Pepperoni Suya   3000         2  08:55:57
2254  2255  2015-12-11   Gbagada        Italiano   3000         3  08:55:58

      Revenue  Snap
2250    12000  4003
2251     9000  3003
2252     8000  2004
2253     6000  3002
2254     9000  3003
CHUNK BOSS
       S/N        Date  Branch           Pizza Sold  Price  Quantity  \
2255  2256  2015-12-07  Ibadan              Meatzaa   2000         2
2256  2257  2015-12-11  Ibadan       Chicken Legend   2000         3
2257  2258  2015-12-06   Ikoyi            Margarita   4000         5
2258  2259  2015-12-14   Lekki  Hot Pepperoni Feast   4000         3
2259  2260  2015-12-03   Ikoyi           Hot Veggie   4000         5

          Time  Revenue  Snap
2255  08:55:59     4000  2002
2256  08:56:00     6000  2003
2257  08:56:00    20000  4005
2258  08:56:01    12000  4003
2259  08:56:01    20000  4005
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
2260  2261  2015-12-13   Ibadan  Hot Pepperoni Feast   4000         4
2261  2262  2015-12-12    Ikoyi       Pepperoni Suya   3000         4
2262  2263  2015-12-05   Ibadan       Chicken Legend   2000         2
2263  2264  2015-12-11    Ikoyi       Chicken Legend   2000         3
2264  2265  2015-12-15  Gbagada         Extravaganza   2000         3

          Time  Revenue  Snap
2260  08:56:01    16000  4004
2261  08:56:04    12000  3004
2262  08:56:05     4000  2002
2263  08:56:06     6000  2003
2264  08:56:10     6000  2003
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2265  2266  2015-12-14     Ikoyi    Extravaganza   2000         5  08:56:13
2266  2267  2015-12-09     Lekki  Veggie Supreme   3000         1  08:56:15
2267  2268  2015-12-09    Ibadan     BBQ Chicken   4000         5  08:56:15
2268  2269  2015-12-03     Ikoyi     BBQ Chicken   4000         4  08:56:18
2269  2270  2015-12-06  Surulere    Chicken Bali   2000         3  08:56:18

      Revenue  Snap
2265    10000  2005
2266     3000  3001
2267    20000  4005
2268    16000  4004
2269     6000  2003
CHUNK BOSS
       S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
2270  2271  2015-12-08   Ibadan        Margarita   4000         2  08:56:19
2271  2272  2015-12-08  Gbagada  Pepperoni Feast   4000         3  08:56:19
2272  2273  2015-12-04    Ikoyi        Margarita   4000         1  08:56:21
2273  2274  2015-12-03  Gbagada        Beef Suya   3000         3  08:56:21
2274  2275  2015-12-05    Ikoyi    Chicken Feast   2000         3  08:56:21

      Revenue  Snap
2270     8000  4002
2271    12000  4003
2272     4000  4001
2273     9000  3003
2274     6000  2003
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2275  2276  2015-12-11  Surulere       Margarita   4000         1  08:56:23
2276  2277  2015-12-09   Gbagada    Chicken Bali   2000         1  08:56:24
2277  2278  2015-12-12     Ikoyi  Pepperoni Suya   3000         1  08:56:24
2278  2279  2015-12-08  Surulere    Chicken Suya   4000         1  08:56:24
2279  2280  2015-12-08   Gbagada  Veggie Supreme   3000         3  08:56:25

      Revenue  Snap
2275     4000  4001
2276     2000  2001
2277     3000  3001
2278     4000  4001
2279     9000  3003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2280  2281  2015-12-05  Surulere          BBQ Chicken   4000         5
2281  2282  2015-12-10     Lekki        Chicken Feast   2000         5
2282  2283  2015-12-13     Lekki         Chicken Bali   2000         3
2283  2284  2015-12-09   Gbagada  Hot Pepperoni Feast   4000         2
2284  2285  2015-12-08    Ibadan       Veggie Supreme   3000         1

          Time  Revenue  Snap
2280  08:56:25    20000  4005
2281  08:56:27    10000  2005
2282  08:56:30     6000  2003
2283  08:56:33     8000  4002
2284  08:56:37     3000  3001
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2285  2286  2015-12-04     Lekki  Hot Pepperoni Feast   4000         3
2286  2287  2015-12-03  Surulere       Pepperoni Suya   3000         5
2287  2288  2015-12-10    Ibadan         Chicken Suya   4000         2
2288  2289  2015-12-04  Surulere       Veggie Supreme   3000         2
2289  2290  2015-12-13    Ibadan            Margarita   4000         1

          Time  Revenue  Snap
2285  08:56:39    12000  4003
2286  08:56:41    15000  3005
2287  08:56:42     8000  4002
2288  08:56:43     6000  3002
2289  08:56:44     4000  4001
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
2290  2291  2015-12-05     Lekki  Pepperoni Feast   4000         4  08:56:44
2291  2292  2015-12-03   Gbagada  Pepperoni Feast   4000         3  08:56:46
2292  2293  2015-12-14   Gbagada          Meatzaa   2000         4  08:56:47
2293  2294  2015-12-03   Gbagada          Meatzaa   2000         3  08:56:48
2294  2295  2015-12-08  Surulere     Chicken Suya   4000         4  08:56:48

      Revenue  Snap
2290    16000  4004
2291    12000  4003
2292     8000  2004
2293     6000  2003
2294    16000  4004

CHUNK BOSS
       S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
2295  2296  2015-12-13    Lekki  Pepperoni Feast   4000         5  08:56:48
2296  2297  2015-12-03    Ikoyi        Beef Suya   3000         3  08:56:48
2297  2298  2015-12-09  Gbagada        Margarita   4000         4  08:56:48
2298  2299  2015-12-09    Lekki       Hot Veggie   4000         1  08:56:49
2299  2300  2015-12-11    Lekki   Pepperoni Suya   3000         2  08:56:52

      Revenue  Snap
2295    20000  4005
2296     9000  3003
2297    16000  4004
2298     4000  4001
2299     6000  3002
CHUNK BOSS
       S/N        Date  Branch      Pizza Sold  Price  Quantity      Time  \
2300  2301  2015-12-12   Lekki    Chicken Bali   2000         2  08:56:52
2301  2302  2015-12-10   Ikoyi  Pepperoni Suya   3000         3  08:56:54
2302  2303  2015-12-05   Lekki      Hot Veggie   4000         5  08:56:55
2303  2304  2015-12-09   Ikoyi     BBQ Chicken   4000         5  08:56:56
2304  2305  2015-12-05  Ibadan   Chicken Feast   2000         3  08:56:57

      Revenue  Snap
2300     4000  2002
2301     9000  3003
2302    20000  4005
2303    20000  4005
2304     6000  2003
CHUNK BOSS
       S/N        Date    Branch    Pizza Sold  Price  Quantity      Time  \
2305  2306  2015-12-07     Ikoyi      Italiano   3000         4  08:56:57
2306  2307  2015-12-13     Lekki     Beef Suya   3000         5  08:56:58
2307  2308  2015-12-10     Lekki  Chicken Bali   2000         2  08:56:59
2308  2309  2015-12-12    Ibadan  Chicken Bali   2000         1  08:56:59
2309  2310  2015-12-15  Surulere   BBQ Chicken   4000         5  08:57:02

      Revenue  Snap
2305    12000  3004
2306    15000  3005
2307     4000  2002
2308     2000  2001
2309    20000  4005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2310  2311  2015-12-03     Ikoyi  Hot Pepperoni Feast   4000         5
2311  2312  2015-12-08    Ibadan           Hot Veggie   4000         4
2312  2313  2015-12-05     Ikoyi              Meatzaa   2000         4
2313  2314  2015-12-13  Surulere       Pepperoni Suya   3000         2
2314  2315  2015-12-13     Lekki            Margarita   4000         3

          Time  Revenue  Snap
2310  08:57:03    20000  4005
2311  08:57:03    16000  4004
2312  08:57:04     8000  2004
2313  08:57:04     6000  3002
2314  08:57:05    12000  4003
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
2315  2316  2015-12-05    Ibadan       Hot Veggie   4000         1  08:57:05
2316  2317  2015-12-13     Lekki        Beef Suya   3000         4  08:57:06
2317  2318  2015-12-15     Lekki  Pepperoni Feast   4000         2  08:57:10
2318  2319  2015-12-14  Surulere        Beef Suya   3000         3  08:57:15
2319  2320  2015-12-09     Ikoyi     Chicken Bali   2000         2  08:57:16

      Revenue  Snap
2315     4000  4001
2316    12000  3004
2317     8000  4002
2318     9000  3003
2319     4000  2002
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
2320  2321  2015-12-14  Surulere     Chicken Feast   2000         1  08:57:18
2321  2322  2015-12-12     Ikoyi    Chicken Legend   2000         1  08:57:19
2322  2323  2015-12-11  Surulere        Hot Veggie   4000         3  08:57:20
2323  2324  2015-12-08     Ikoyi  BBQ Philly Steak   4000         3  08:57:21
2324  2325  2015-12-07    Ibadan       BBQ Chicken   4000         4  08:57:21

      Revenue  Snap
2320     2000  2001
2321     2000  2001
2322    12000  4003
2323    12000  4003
2324    16000  4004
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2325  2326  2015-12-14   Gbagada       Margarita   4000         2  08:57:22
2326  2327  2015-12-07  Surulere   Chicken Feast   2000         2  08:57:22
2327  2328  2015-12-06   Gbagada    Extravaganza   2000         1  08:57:22
2328  2329  2015-12-06     Ikoyi  Pepperoni Suya   3000         5  08:57:23
2329  2330  2015-12-05     Ikoyi   Chicken Feast   2000         1  08:57:24

      Revenue  Snap
2325     8000  4002
2326     4000  2002
2327     2000  2001
2328    15000  3005
2329     2000  2001
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2330  2331  2015-12-15  Surulere  Hot Pepperoni Feast   4000         5
2331  2332  2015-12-04  Surulere       Chicken Legend   2000         2
2332  2333  2015-12-07    Ibadan         Chicken Bali   2000         5
2333  2334  2015-12-11     Ikoyi         Chicken Suya   4000         1
2334  2335  2015-12-10   Gbagada  Hot Pepperoni Feast   4000         5

          Time  Revenue  Snap
2330  08:57:25    20000  4005
2331  08:57:25     4000  2002
2332  08:57:26    10000  2005
2333  08:57:28     4000  4001
2334  08:57:29    20000  4005
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2335  2336  2015-12-14  Surulere      Hot Veggie   4000         1  08:57:30
2336  2337  2015-12-04   Gbagada  Pepperoni Suya   3000         3  08:57:30
2337  2338  2015-12-06     Ikoyi    Chicken Suya   4000         2  08:57:30
2338  2339  2015-12-04     Ikoyi     BBQ Chicken   4000         1  08:57:32
2339  2340  2015-12-03  Surulere    Chicken Suya   4000         3  08:57:32

      Revenue  Snap
2335     4000  4001
2336     9000  3003
2337     8000  4002
2338     4000  4001
2339    12000  4003
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
2340  2341  2015-12-05  Gbagada  Chicken Legend   2000         1  08:57:34
2341  2342  2015-12-04  Gbagada       Beef Suya   3000         3  08:57:34
2342  2343  2015-12-15    Lekki    Chicken Bali   2000         1  08:57:34
2343  2344  2015-12-08  Gbagada  Veggie Supreme   3000         5  08:57:35
2344  2345  2015-12-14    Lekki  Veggie Supreme   3000         1  08:57:35

      Revenue  Snap
2340     2000  2001
2341     9000  3003
2342     2000  2001
2343    15000  3005
2344     3000  3001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2345  2346  2015-12-15   Gbagada    Chicken Suya   4000         5  08:57:37
2346  2347  2015-12-06  Surulere  Pepperoni Suya   3000         1  08:57:37
2347  2348  2015-12-14   Gbagada       Beef Suya   3000         3  08:57:37
2348  2349  2015-12-03     Ikoyi       Beef Suya   3000         4  08:57:37
2349  2350  2015-12-14     Ikoyi     BBQ Chicken   4000         2  08:57:39

      Revenue  Snap
2345    20000  4005
2346     3000  3001
2347     9000  3003
2348    12000  3004
2349     8000  4002
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
2350  2351  2015-12-14  Gbagada             Italiano   3000         3
2351  2352  2015-12-11  Gbagada  Hot Pepperoni Feast   4000         3
2352  2353  2015-12-04   Ibadan      Pepperoni Feast   4000         1
2353  2354  2015-12-09    Ikoyi      Pepperoni Feast   4000         1
2354  2355  2015-12-09  Gbagada           Hot Veggie   4000         2

          Time  Revenue  Snap
2350  08:57:40     9000  3003
2351  08:57:44    12000  4003
2352  08:57:45     4000  4001
2353  08:57:45     4000  4001
2354  08:57:45     8000  4002
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
2355  2356  2015-12-06     Ikoyi    Chicken Legend   2000         3  08:57:47
2356  2357  2015-12-04     Ikoyi    Chicken Legend   2000         4  08:57:49
2357  2358  2015-12-12    Ibadan  BBQ Philly Steak   4000         5  08:57:50
2358  2359  2015-12-04  Surulere         Beef Suya   3000         1  08:57:54
2359  2360  2015-12-09     Lekki           Meatzaa   2000         4  08:57:55

      Revenue  Snap
2355     6000  2003
2356     8000  2004
2357    20000  4005
2358     3000  3001
2359     8000  2004
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
2360  2361  2015-12-06  Surulere   Chicken Legend   2000         3  08:57:56
2361  2362  2015-12-04     Ikoyi       Hot Veggie   4000         2  08:57:57
2362  2363  2015-12-11  Surulere  Pepperoni Feast   4000         4  08:57:59
2363  2364  2015-12-03     Lekki       Hot Veggie   4000         4  08:58:00
2364  2365  2015-12-11   Gbagada   Chicken Legend   2000         3  08:58:01

      Revenue  Snap
2360     6000  2003
2361     8000  4002
2362    16000  4004
2363    16000  4004
2364     6000  2003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2365  2366  2015-12-03    Ibadan       Pepperoni Suya   3000         5
2366  2367  2015-12-07  Surulere             Italiano   3000         2
2367  2368  2015-12-04     Ikoyi            Margarita   4000         2
2368  2369  2015-12-09     Lekki  Hot Pepperoni Feast   4000         3
2369  2370  2015-12-14    Ibadan       Pepperoni Suya   3000         5

          Time  Revenue  Snap
2365  08:58:03    15000  3005
2366  08:58:03     6000  3002
2367  08:58:07     8000  4002
2368  08:58:08    12000  4003

2369  08:58:11    15000  3005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2370  2371  2015-12-11   Gbagada       Chicken Legend   2000         1
2371  2372  2015-12-10     Ikoyi       Chicken Legend   2000         2
2372  2373  2015-12-05  Surulere        Chicken Feast   2000         2
2373  2374  2015-12-14    Ibadan     BBQ Philly Steak   4000         3
2374  2375  2015-12-05     Lekki  Hot Pepperoni Feast   4000         1

          Time  Revenue  Snap
2370  08:58:11     2000  2001
2371  08:58:12     4000  2002
2372  08:58:12     4000  2002
2373  08:58:15    12000  4003
2374  08:58:16     4000  4001
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2375  2376  2015-12-03   Gbagada            Beef Suya   3000         5
2376  2377  2015-12-03     Ikoyi              Meatzaa   2000         4
2377  2378  2015-12-12  Surulere         Chicken Bali   2000         1
2378  2379  2015-12-05  Surulere          BBQ Chicken   4000         1
2379  2380  2015-12-08     Lekki  Hot Pepperoni Feast   4000         4

          Time  Revenue  Snap
2375  08:58:16    15000  3005
2376  08:58:17     8000  2004
2377  08:58:17     2000  2001
2378  08:58:17     4000  4001
2379  08:58:17    16000  4004
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
2380  2381  2015-12-15    Lekki    Veggie Supreme   3000         3  08:58:19
2381  2382  2015-12-03   Ibadan           Meatzaa   2000         5  08:58:19
2382  2383  2015-12-07   Ibadan  BBQ Philly Steak   4000         2  08:58:21
2383  2384  2015-12-08   Ibadan      Extravaganza   2000         1  08:58:21
2384  2385  2015-12-15  Gbagada     Chicken Feast   2000         2  08:58:24

      Revenue  Snap
2380     9000  3003
2381    10000  2005
2382     8000  4002
2383     2000  2001
2384     4000  2002
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2385  2386  2015-12-07     Lekki       Beef Suya   3000         2  08:58:25
2386  2387  2015-12-11     Ikoyi         Meatzaa   2000         4  08:58:27
2387  2388  2015-12-04     Lekki  Veggie Supreme   3000         2  08:58:28
2388  2389  2015-12-13   Gbagada         Meatzaa   2000         1  08:58:28
2389  2390  2015-12-15  Surulere     BBQ Chicken   4000         5  08:58:29

      Revenue  Snap
2385     6000  3002
2386     8000  2004
2387     6000  3002
2388     2000  2001
2389    20000  4005
CHUNK BOSS
       S/N        Date  Branch        Pizza Sold  Price  Quantity      Time  \
2390  2391  2015-12-04  Ibadan  BBQ Philly Steak   4000         5  08:58:30
2391  2392  2015-12-05   Lekki         Beef Suya   3000         4  08:58:31
2392  2393  2015-12-09  Ibadan       BBQ Chicken   4000         1  08:58:31
2393  2394  2015-12-11  Ibadan         Margarita   4000         5  08:58:32
2394  2395  2015-12-04   Lekki       BBQ Chicken   4000         1  08:58:32

      Revenue  Snap
2390    20000  4005
2391    12000  3004
2392     4000  4001
2393    20000  4005
2394     4000  4001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2395  2396  2015-12-14    Ibadan       Beef Suya   3000         4  08:58:33
2396  2397  2015-12-09  Surulere    Extravaganza   2000         5  08:58:34
2397  2398  2015-12-09   Gbagada  Pepperoni Suya   3000         3  08:58:34
2398  2399  2015-12-10  Surulere  Chicken Legend   2000         5  08:58:34
2399  2400  2015-12-06  Surulere       Beef Suya   3000         4  08:58:36

      Revenue  Snap
2395    12000  3004
2396    10000  2005
2397     9000  3003
2398    10000  2005
2399    12000  3004
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
2400  2401  2015-12-14   Gbagada      BBQ Chicken   4000         4  08:58:36
2401  2402  2015-12-13     Lekki   Chicken Legend   2000         5  08:58:38
2402  2403  2015-12-11  Surulere   Pepperoni Suya   3000         1  08:58:38
2403  2404  2015-12-08     Lekki   Pepperoni Suya   3000         2  08:58:38
2404  2405  2015-12-14  Surulere  Pepperoni Feast   4000         2  08:58:38

      Revenue  Snap
2400    16000  4004
2401    10000  2005
2402     3000  3001
2403     6000  3002
2404     8000  4002
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2405  2406  2015-12-12     Ikoyi        Chicken Feast   2000         2
2406  2407  2015-12-13     Ikoyi            Beef Suya   3000         5
2407  2408  2015-12-08   Gbagada            Margarita   4000         4
2408  2409  2015-12-14  Surulere      Pepperoni Feast   4000         3
2409  2410  2015-12-10     Lekki  Hot Pepperoni Feast   4000         2

          Time  Revenue  Snap
2405  08:58:41     4000  2002
2406  08:58:41    15000  3005
2407  08:58:41    16000  4004
2408  08:58:41    12000  4003
2409  08:58:42     8000  4002
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2410  2411  2015-12-14  Surulere     BBQ Philly Steak   4000         4
2411  2412  2015-12-14     Lekki  Hot Pepperoni Feast   4000         3
2412  2413  2015-12-13     Lekki     BBQ Philly Steak   4000         1
2413  2414  2015-12-09     Ikoyi          BBQ Chicken   4000         2
2414  2415  2015-12-04    Ibadan       Veggie Supreme   3000         4

          Time  Revenue  Snap
2410  08:58:43    16000  4004
2411  08:58:44    12000  4003
2412  08:58:44     4000  4001
2413  08:58:46     8000  4002
2414  08:58:46    12000  3004
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
2415  2416  2015-12-14  Gbagada    Veggie Supreme   3000         2  08:58:47
2416  2417  2015-12-14  Gbagada      Chicken Bali   2000         5  08:58:51
2417  2418  2015-12-08  Gbagada  BBQ Philly Steak   4000         4  08:58:51
2418  2419  2015-12-14  Gbagada       BBQ Chicken   4000         5  08:58:52
2419  2420  2015-12-14    Ikoyi    Veggie Supreme   3000         2  08:58:53

      Revenue  Snap
2415     6000  3002
2416    10000  2005
2417    16000  4004
2418    20000  4005
2419     6000  3002
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
2420  2421  2015-12-13    Ikoyi        Chicken Feast   2000         2
2421  2422  2015-12-06  Gbagada     BBQ Philly Steak   4000         5
2422  2423  2015-12-10    Lekki  Hot Pepperoni Feast   4000         2
2423  2424  2015-12-04    Lekki       Chicken Legend   2000         3
2424  2425  2015-12-10    Ikoyi          BBQ Chicken   4000         5

          Time  Revenue  Snap
2420  08:58:53     4000  2002
2421  08:58:53    20000  4005
2422  08:58:55     8000  4002
2423  08:58:55     6000  2003
2424  08:58:57    20000  4005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2425  2426  2015-12-08     Ikoyi           Hot Veggie   4000         4
2426  2427  2015-12-03  Surulere            Beef Suya   3000         5
2427  2428  2015-12-04    Ibadan  Hot Pepperoni Feast   4000         3
2428  2429  2015-12-15     Ikoyi     BBQ Philly Steak   4000         4
2429  2430  2015-12-03   Gbagada  Hot Pepperoni Feast   4000         5

          Time  Revenue  Snap
2425  08:58:57    16000  4004
2426  08:58:57    15000  3005
2427  08:58:58    12000  4003
2428  08:58:59    16000  4004
2429  08:59:00    20000  4005
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
2430  2431  2015-12-14  Surulere      Chicken Bali   2000         1  08:59:02
2431  2432  2015-12-10    Ibadan         Margarita   4000         4  08:59:03
2432  2433  2015-12-10   Gbagada    Veggie Supreme   3000         4  08:59:04
2433  2434  2015-12-11    Ibadan        Hot Veggie   4000         1  08:59:09
2434  2435  2015-12-09    Ibadan  BBQ Philly Steak   4000         4  08:59:09

      Revenue  Snap
2430     2000  2001
2431    16000  4004
2432    12000  3004
2433     4000  4001
2434    16000  4004
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2435  2436  2015-12-04    Ibadan  Hot Pepperoni Feast   4000         5
2436  2437  2015-12-13     Lekki       Chicken Legend   2000         4
2437  2438  2015-12-12    Ibadan             Italiano   3000         4
2438  2439  2015-12-15  Surulere         Chicken Suya   4000         1
2439  2440  2015-12-04  Surulere             Italiano   3000         5

          Time  Revenue  Snap
2435  08:59:10    20000  4005
2436  08:59:11     8000  2004
2437  08:59:11    12000  3004
2438  08:59:12     4000  4001
2439  08:59:12    15000  3005
CHUNK BOSS
       S/N        Date Branch           Pizza Sold  Price  Quantity      Time  \
2440  2441  2015-12-05  Ikoyi        Chicken Feast   2000         3  08:59:13
2441  2442  2015-12-09  Ikoyi  Hot Pepperoni Feast   4000         4  08:59:15
2442  2443  2015-12-04  Ikoyi      Pepperoni Feast   4000         1  08:59:16
2443  2444  2015-12-10  Ikoyi             Italiano   3000         4  08:59:16
2444  2445  2015-12-13  Lekki            Beef Suya   3000         4  08:59:17

      Revenue  Snap
2440     6000  2003
2441    16000  4004
2442     4000  4001
2443    12000  3004
2444    12000  3004
CHUNK BOSS
       S/N        Date  Branch           Pizza Sold  Price  Quantity  \
2445  2446  2015-12-09   Lekki     BBQ Philly Steak   4000         3
2446  2447  2015-12-10   Lekki          BBQ Chicken   4000         4
2447  2448  2015-12-09  Ibadan         Chicken Suya   4000         1
2448  2449  2015-12-12   Lekki           Hot Veggie   4000         3
2449  2450  2015-12-11   Lekki  Hot Pepperoni Feast   4000         4

          Time  Revenue  Snap
2445  08:59:17    12000  4003
2446  08:59:17    16000  4004
2447  08:59:18     4000  4001
2448  08:59:20    12000  4003

2449  08:59:24    16000  4004
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
2450  2451  2015-12-11  Surulere   Chicken Legend   2000         2  08:59:28
2451  2452  2015-12-09    Ibadan  Pepperoni Feast   4000         5  08:59:29
2452  2453  2015-12-05     Lekki  Pepperoni Feast   4000         2  08:59:29
2453  2454  2015-12-12     Ikoyi        Beef Suya   3000         5  08:59:29
2454  2455  2015-12-12    Ibadan   Veggie Supreme   3000         5  08:59:30

      Revenue  Snap
2450     4000  2002
2451    20000  4005
2452     8000  4002
2453    15000  3005
2454    15000  3005
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
2455  2456  2015-12-15    Ikoyi         Extravaganza   2000         4
2456  2457  2015-12-08  Gbagada         Chicken Suya   4000         5
2457  2458  2015-12-03   Ibadan  Hot Pepperoni Feast   4000         4
2458  2459  2015-12-09   Ibadan           Hot Veggie   4000         5
2459  2460  2015-12-06    Lekki            Beef Suya   3000         3

          Time  Revenue  Snap
2455  08:59:31     8000  2004
2456  08:59:35    20000  4005
2457  08:59:35    16000  4004
2458  08:59:35    20000  4005
2459  08:59:35     9000  3003
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
2460  2461  2015-12-10    Lekki         Extravaganza   2000         2
2461  2462  2015-12-09  Gbagada  Hot Pepperoni Feast   4000         4
2462  2463  2015-12-12    Ikoyi     BBQ Philly Steak   4000         5
2463  2464  2015-12-08   Ibadan       Veggie Supreme   3000         5
2464  2465  2015-12-09    Ikoyi              Meatzaa   2000         2

          Time  Revenue  Snap
2460  08:59:37     4000  2002
2461  08:59:37    16000  4004
2462  08:59:39    20000  4005
2463  08:59:40    15000  3005
2464  08:59:43     4000  2002
CHUNK BOSS
       S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
2465  2466  2015-12-03   Ibadan         Italiano   3000         2  08:59:45
2466  2467  2015-12-13    Lekki      BBQ Chicken   4000         3  08:59:45
2467  2468  2015-12-07  Gbagada  Pepperoni Feast   4000         1  08:59:45
2468  2469  2015-12-13    Ikoyi         Italiano   3000         3  08:59:53
2469  2470  2015-12-11   Ibadan       Hot Veggie   4000         2  08:59:55

      Revenue  Snap
2465     6000  3002
2466    12000  4003
2467     4000  4001
2468     9000  3003
2469     8000  4002
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2470  2471  2015-12-04    Ibadan  Pepperoni Suya   3000         1  08:59:55
2471  2472  2015-12-07     Ikoyi  Veggie Supreme   3000         5  08:59:56
2472  2473  2015-12-13   Gbagada    Extravaganza   2000         5  08:59:56
2473  2474  2015-12-09    Ibadan       Margarita   4000         1  08:59:56
2474  2475  2015-12-04  Surulere       Margarita   4000         3  08:59:57

      Revenue  Snap
2470     3000  3001
2471    15000  3005
2472    10000  2005
2473     4000  4001
2474    12000  4003
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
2475  2476  2015-12-06     Ikoyi      Extravaganza   2000         1  08:59:58
2476  2477  2015-12-07     Lekki         Margarita   4000         1  08:59:59
2477  2478  2015-12-08  Surulere  BBQ Philly Steak   4000         2  09:00:00
2478  2479  2015-12-12  Surulere        Hot Veggie   4000         2  09:00:00
2479  2480  2015-12-05  Surulere    Pepperoni Suya   3000         2  09:00:01

      Revenue  Snap
2475     2000  2001
2476     4000  4001
2477     8000  4002
2478     8000  4002
2479     6000  3002
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2480  2481  2015-12-05  Surulere              Meatzaa   2000         5
2481  2482  2015-12-03  Surulere  Hot Pepperoni Feast   4000         5
2482  2483  2015-12-07     Ikoyi         Chicken Suya   4000         3
2483  2484  2015-12-15  Surulere         Chicken Suya   4000         5
2484  2485  2015-12-13    Ibadan         Extravaganza   2000         5

          Time  Revenue  Snap
2480  09:00:01    10000  2005
2481  09:00:03    20000  4005
2482  09:00:04    12000  4003
2483  09:00:05    20000  4005
2484  09:00:06    10000  2005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2485  2486  2015-12-11    Ibadan  Hot Pepperoni Feast   4000         3
2486  2487  2015-12-15    Ibadan         Chicken Suya   4000         2
2487  2488  2015-12-05    Ibadan  Hot Pepperoni Feast   4000         1
2488  2489  2015-12-13  Surulere       Pepperoni Suya   3000         2
2489  2490  2015-12-04     Lekki            Margarita   4000         5

          Time  Revenue  Snap
2485  09:00:07    12000  4003
2486  09:00:07     8000  4002
2487  09:00:08     4000  4001
2488  09:00:10     6000  3002
2489  09:00:10    20000  4005
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
2490  2491  2015-12-08  Surulere       BBQ Chicken   4000         1  09:00:11
2491  2492  2015-12-12    Ibadan         Beef Suya   3000         2  09:00:12
2492  2493  2015-12-05    Ibadan   Pepperoni Feast   4000         3  09:00:13
2493  2494  2015-12-13     Ikoyi  BBQ Philly Steak   4000         4  09:00:16
2494  2495  2015-12-09    Ibadan     Chicken Feast   2000         1  09:00:18

      Revenue  Snap
2490     4000  4001
2491     6000  3002
2492    12000  4003
2493    16000  4004
2494     2000  2001
CHUNK BOSS
       S/N        Date Branch      Pizza Sold  Price  Quantity      Time  \
2495  2496  2015-12-11  Lekki      Hot Veggie   4000         2  09:00:18
2496  2497  2015-12-08  Lekki        Italiano   3000         1  09:00:18
2497  2498  2015-12-09  Ikoyi      Hot Veggie   4000         4  09:00:22
2498  2499  2015-12-15  Ikoyi  Chicken Legend   2000         2  09:00:22
2499  2500  2015-12-13  Ikoyi  Chicken Legend   2000         5  09:00:24

      Revenue  Snap
2495     8000  4002
2496     3000  3001
2497    16000  4004
2498     4000  2002
2499    10000  2005
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
2500  2501  2015-12-08    Ikoyi  Chicken Legend   2000         4  09:00:24
2501  2502  2015-12-12    Ikoyi    Extravaganza   2000         4  09:00:25
2502  2503  2015-12-11  Gbagada   Chicken Feast   2000         4  09:00:26
2503  2504  2015-12-03    Ikoyi       Beef Suya   3000         2  09:00:26
2504  2505  2015-12-14  Gbagada    Chicken Suya   4000         3  09:00:27

      Revenue  Snap
2500     8000  2004
2501     8000  2004
2502     8000  2004
2503     6000  3002
2504    12000  4003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2505  2506  2015-12-10     Lekki       Pepperoni Suya   3000         5
2506  2507  2015-12-10  Surulere  Hot Pepperoni Feast   4000         3
2507  2508  2015-12-11     Ikoyi        Chicken Feast   2000         2
2508  2509  2015-12-10     Ikoyi       Chicken Legend   2000         2
2509  2510  2015-12-13     Ikoyi         Chicken Bali   2000         5

          Time  Revenue  Snap
2505  09:00:30    15000  3005
2506  09:00:30    12000  4003
2507  09:00:30     4000  2002
2508  09:00:32     4000  2002
2509  09:00:32    10000  2005
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
2510  2511  2015-12-11    Ikoyi         Meatzaa   2000         1  09:00:33
2511  2512  2015-12-08    Lekki  Veggie Supreme   3000         2  09:00:33
2512  2513  2015-12-15  Gbagada       Beef Suya   3000         2  09:00:33
2513  2514  2015-12-03   Ibadan  Pepperoni Suya   3000         5  09:00:35
2514  2515  2015-12-06   Ibadan     BBQ Chicken   4000         3  09:00:36

      Revenue  Snap
2510     2000  2001
2511     6000  3002
2512     6000  3002
2513    15000  3005
2514    12000  4003
CHUNK BOSS
       S/N        Date    Branch    Pizza Sold  Price  Quantity      Time  \
2515  2516  2015-12-09  Surulere      Italiano   3000         3  09:00:36
2516  2517  2015-12-10   Gbagada  Chicken Bali   2000         1  09:00:37
2517  2518  2015-12-03     Ikoyi  Chicken Suya   4000         5  09:00:39
2518  2519  2015-12-08  Surulere    Hot Veggie   4000         3  09:00:39
2519  2520  2015-12-04    Ibadan       Meatzaa   2000         4  09:00:42

      Revenue  Snap
2515     9000  3003
2516     2000  2001
2517    20000  4005
2518    12000  4003
2519     8000  2004
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
2520  2521  2015-12-04  Surulere      BBQ Chicken   4000         5  09:00:43
2521  2522  2015-12-11   Gbagada  Pepperoni Feast   4000         5  09:00:43
2522  2523  2015-12-13  Surulere        Beef Suya   3000         1  09:00:43
2523  2524  2015-12-10   Gbagada   Veggie Supreme   3000         4  09:00:43
2524  2525  2015-12-05    Ibadan  Pepperoni Feast   4000         3  09:00:44

      Revenue  Snap
2520    20000  4005
2521    20000  4005
2522     3000  3001
2523    12000  3004
2524    12000  4003
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
2525  2526  2015-12-07  Gbagada    Extravaganza   2000         5  09:00:47
2526  2527  2015-12-07    Ikoyi         Meatzaa   2000         1  09:00:47
2527  2528  2015-12-05  Gbagada  Pepperoni Suya   3000         5  09:00:47
2528  2529  2015-12-06    Lekki         Meatzaa   2000         3  09:00:47
2529  2530  2015-12-13    Ikoyi       Beef Suya   3000         5  09:00:49

      Revenue  Snap
2525    10000  2005
2526     2000  2001
2527    15000  3005
2528     6000  2003
2529    15000  3005
CHUNK BOSS
       S/N        Date  Branch       Pizza Sold  Price  Quantity      Time  \
2530  2531  2015-12-10  Ibadan   Pepperoni Suya   3000         3  09:00:49
2531  2532  2015-12-10   Lekki  Pepperoni Feast   4000         2  09:00:50
2532  2533  2015-12-04   Ikoyi        Beef Suya   3000         2  09:00:50
2533  2534  2015-12-15   Ikoyi         Italiano   3000         5  09:00:51
2534  2535  2015-12-06   Lekki    Chicken Feast   2000         2  09:00:53

      Revenue  Snap
2530     9000  3003
2531     8000  4002
2532     6000  3002
2533    15000  3005

2534     4000  2002
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
2535  2536  2015-12-12  Surulere  Pepperoni Feast   4000         2  09:00:53
2536  2537  2015-12-04     Ikoyi     Extravaganza   2000         4  09:00:58
2537  2538  2015-12-14     Lekki         Italiano   3000         1  09:01:01
2538  2539  2015-12-15    Ibadan   Pepperoni Suya   3000         3  09:01:03
2539  2540  2015-12-15    Ibadan  Pepperoni Feast   4000         1  09:01:03

      Revenue  Snap
2535     8000  4002
2536     8000  2004
2537     3000  3001
2538     9000  3003
2539     4000  4001
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
2540  2541  2015-12-15    Ikoyi    Pepperoni Suya   3000         2  09:01:04
2541  2542  2015-12-03    Lekki         Beef Suya   3000         3  09:01:04
2542  2543  2015-12-03  Gbagada        Hot Veggie   4000         2  09:01:05
2543  2544  2015-12-07    Ikoyi  BBQ Philly Steak   4000         4  09:01:07
2544  2545  2015-12-12    Ikoyi         Beef Suya   3000         3  09:01:07

      Revenue  Snap
2540     6000  3002
2541     9000  3003
2542     8000  4002
2543    16000  4004
2544     9000  3003
CHUNK BOSS
       S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
2545  2546  2015-12-15   Ibadan  Pepperoni Feast   4000         5  09:01:07
2546  2547  2015-12-11  Gbagada   Chicken Legend   2000         2  09:01:07
2547  2548  2015-12-11  Gbagada        Beef Suya   3000         2  09:01:08
2548  2549  2015-12-08    Ikoyi         Italiano   3000         2  09:01:08
2549  2550  2015-12-10    Lekki  Pepperoni Feast   4000         5  09:01:08

      Revenue  Snap
2545    20000  4005
2546     4000  2002
2547     6000  3002
2548     6000  3002
2549    20000  4005
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
2550  2551  2015-12-09    Ikoyi            Beef Suya   3000         3
2551  2552  2015-12-06  Gbagada           Hot Veggie   4000         2
2552  2553  2015-12-04   Ibadan  Hot Pepperoni Feast   4000         2
2553  2554  2015-12-05   Ibadan             Italiano   3000         3
2554  2555  2015-12-14   Ibadan  Hot Pepperoni Feast   4000         5

          Time  Revenue  Snap
2550  09:01:08     9000  3003
2551  09:01:08     8000  4002
2552  09:01:10     8000  4002
2553  09:01:10     9000  3003
2554  09:01:11    20000  4005
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
2555  2556  2015-12-10     Ikoyi        Beef Suya   3000         4  09:01:12
2556  2557  2015-12-11     Lekki  Pepperoni Feast   4000         3  09:01:12
2557  2558  2015-12-09     Lekki         Italiano   3000         5  09:01:12
2558  2559  2015-12-14     Ikoyi         Italiano   3000         4  09:01:13
2559  2560  2015-12-11  Surulere          Meatzaa   2000         2  09:01:14

      Revenue  Snap
2555    12000  3004
2556    12000  4003
2557    15000  3005
2558    12000  3004
2559     4000  2002
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
2560  2561  2015-12-10   Gbagada       BBQ Chicken   4000         1  09:01:15
2561  2562  2015-12-03     Lekki       BBQ Chicken   4000         3  09:01:15
2562  2563  2015-12-14  Surulere        Hot Veggie   4000         1  09:01:15
2563  2564  2015-12-05     Ikoyi    Pepperoni Suya   3000         2  09:01:15
2564  2565  2015-12-03    Ibadan  BBQ Philly Steak   4000         2  09:01:16

      Revenue  Snap
2560     4000  4001
2561    12000  4003
2562     4000  4001
2563     6000  3002
2564     8000  4002
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2565  2566  2015-12-13  Surulere      Pepperoni Feast   4000         3
2566  2567  2015-12-07   Gbagada          BBQ Chicken   4000         3
2567  2568  2015-12-07     Ikoyi  Hot Pepperoni Feast   4000         1
2568  2569  2015-12-03  Surulere         Chicken Bali   2000         2
2569  2570  2015-12-05  Surulere       Veggie Supreme   3000         3

          Time  Revenue  Snap
2565  09:01:19    12000  4003
2566  09:01:19    12000  4003
2567  09:01:22     4000  4001
2568  09:01:23     4000  2002
2569  09:01:23     9000  3003
CHUNK BOSS
       S/N        Date  Branch       Pizza Sold  Price  Quantity      Time  \
2570  2571  2015-12-06  Ibadan     Extravaganza   2000         2  09:01:25
2571  2572  2015-12-07   Ikoyi        Margarita   4000         5  09:01:25
2572  2573  2015-12-13  Ibadan  Pepperoni Feast   4000         2  09:01:25
2573  2574  2015-12-06  Ibadan   Pepperoni Suya   3000         3  09:01:27
2574  2575  2015-12-03   Ikoyi        Margarita   4000         5  09:01:27

      Revenue  Snap
2570     4000  2002
2571    20000  4005
2572     8000  4002
2573     9000  3003
2574    20000  4005
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2575  2576  2015-12-09  Surulere  Chicken Legend   2000         4  09:01:31
2576  2577  2015-12-07     Ikoyi  Veggie Supreme   3000         4  09:01:32
2577  2578  2015-12-13     Ikoyi  Pepperoni Suya   3000         3  09:01:33
2578  2579  2015-12-10    Ibadan  Chicken Legend   2000         3  09:01:33
2579  2580  2015-12-13     Lekki       Margarita   4000         3  09:01:33

      Revenue  Snap
2575     8000  2004
2576    12000  3004
2577     9000  3003
2578     6000  2003
2579    12000  4003
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2580  2581  2015-12-11   Gbagada     BBQ Chicken   4000         1  09:01:33
2581  2582  2015-12-12     Lekki  Chicken Legend   2000         4  09:01:35
2582  2583  2015-12-09  Surulere     BBQ Chicken   4000         4  09:01:35
2583  2584  2015-12-14   Gbagada     BBQ Chicken   4000         4  09:01:38
2584  2585  2015-12-14   Gbagada  Pepperoni Suya   3000         5  09:01:40

      Revenue  Snap
2580     4000  4001
2581     8000  2004
2582    16000  4004
2583    16000  4004
2584    15000  3005
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
2585  2586  2015-12-08  Surulere      Extravaganza   2000         5  09:01:45
2586  2587  2015-12-10    Ibadan     Chicken Feast   2000         3  09:01:47
2587  2588  2015-12-12  Surulere    Chicken Legend   2000         5  09:01:47
2588  2589  2015-12-13     Ikoyi      Extravaganza   2000         2  09:01:53
2589  2590  2015-12-14  Surulere  BBQ Philly Steak   4000         1  09:01:54

      Revenue  Snap
2585    10000  2005
2586     6000  2003
2587    10000  2005
2588     4000  2002
2589     4000  4001
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2590  2591  2015-12-10   Gbagada            Margarita   4000         3
2591  2592  2015-12-09     Lekki             Italiano   3000         4
2592  2593  2015-12-05  Surulere            Beef Suya   3000         3
2593  2594  2015-12-05  Surulere         Extravaganza   2000         5
2594  2595  2015-12-05     Ikoyi  Hot Pepperoni Feast   4000         3

          Time  Revenue  Snap
2590  09:01:55    12000  4003
2591  09:01:57    12000  3004
2592  09:01:57     9000  3003
2593  09:01:58    10000  2005
2594  09:01:59    12000  4003
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
2595  2596  2015-12-06  Surulere          Meatzaa   2000         5  09:02:00
2596  2597  2015-12-13     Ikoyi         Italiano   3000         1  09:02:00
2597  2598  2015-12-04    Ibadan    Chicken Feast   2000         5  09:02:01
2598  2599  2015-12-13     Ikoyi     Extravaganza   2000         5  09:02:02
2599  2600  2015-12-15  Surulere  Pepperoni Feast   4000         1  09:02:04

      Revenue  Snap
2595    10000  2005
2596     3000  3001
2597    10000  2005
2598    10000  2005
2599     4000  4001
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2600  2601  2015-12-08  Surulere  Hot Pepperoni Feast   4000         1
2601  2602  2015-12-06     Lekki  Hot Pepperoni Feast   4000         5
2602  2603  2015-12-13     Lekki       Veggie Supreme   3000         3
2603  2604  2015-12-07     Ikoyi           Hot Veggie   4000         4
2604  2605  2015-12-15     Ikoyi           Hot Veggie   4000         1

          Time  Revenue  Snap
2600  09:02:04     4000  4001
2601  09:02:06    20000  4005
2602  09:02:07     9000  3003
2603  09:02:09    16000  4004
2604  09:02:09     4000  4001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2605  2606  2015-12-09  Surulere    Extravaganza   2000         2  09:02:10
2606  2607  2015-12-13    Ibadan   Chicken Feast   2000         2  09:02:10
2607  2608  2015-12-03   Gbagada       Beef Suya   3000         1  09:02:12
2608  2609  2015-12-10     Lekki  Veggie Supreme   3000         1  09:02:13
2609  2610  2015-12-05    Ibadan    Extravaganza   2000         5  09:02:13

      Revenue  Snap
2605     4000  2002
2606     4000  2002
2607     3000  3001
2608     3000  3001
2609    10000  2005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2610  2611  2015-12-11   Gbagada         Chicken Bali   2000         3
2611  2612  2015-12-07    Ibadan       Pepperoni Suya   3000         4
2612  2613  2015-12-06  Surulere          BBQ Chicken   4000         2
2613  2614  2015-12-05     Ikoyi      Pepperoni Feast   4000         1
2614  2615  2015-12-03     Lekki  Hot Pepperoni Feast   4000         2

          Time  Revenue  Snap
2610  09:02:16     6000  2003
2611  09:02:16    12000  3004
2612  09:02:17     8000  4002
2613  09:02:17     4000  4001
2614  09:02:21     8000  4002
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
2615  2616  2015-12-07     Ikoyi         Italiano   3000         1  09:02:22
2616  2617  2015-12-08    Ibadan  Pepperoni Feast   4000         5  09:02:23
2617  2618  2015-12-04  Surulere     Chicken Suya   4000         4  09:02:23
2618  2619  2015-12-09     Ikoyi         Italiano   3000         4  09:02:24
2619  2620  2015-12-14   Gbagada         Italiano   3000         1  09:02:26

      Revenue  Snap
2615     3000  3001
2616    20000  4005
2617    16000  4004
2618    12000  3004
2619     3000  3001

CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2620  2621  2015-12-12  Surulere    Chicken Suya   4000         1  09:02:26
2621  2622  2015-12-12     Lekki    Chicken Bali   2000         2  09:02:26
2622  2623  2015-12-06  Surulere   Chicken Feast   2000         4  09:02:27
2623  2624  2015-12-14   Gbagada  Veggie Supreme   3000         2  09:02:28
2624  2625  2015-12-06   Gbagada  Pepperoni Suya   3000         2  09:02:28

      Revenue  Snap
2620     4000  4001
2621     4000  2002
2622     8000  2004
2623     6000  3002
2624     6000  3002
CHUNK BOSS
       S/N        Date   Branch     Pizza Sold  Price  Quantity      Time  \
2625  2626  2015-12-13   Ibadan    BBQ Chicken   4000         4  09:02:29
2626  2627  2015-12-09   Ibadan   Extravaganza   2000         5  09:02:32
2627  2628  2015-12-12    Lekki  Chicken Feast   2000         4  09:02:32
2628  2629  2015-12-12  Gbagada      Beef Suya   3000         5  09:02:32
2629  2630  2015-12-07    Lekki   Chicken Suya   4000         5  09:02:33

      Revenue  Snap
2625    16000  4004
2626    10000  2005
2627     8000  2004
2628    15000  3005
2629    20000  4005
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
2630  2631  2015-12-05  Surulere          Italiano   3000         5  09:02:34
2631  2632  2015-12-14     Lekki    Pepperoni Suya   3000         2  09:02:35
2632  2633  2015-12-08   Gbagada         Margarita   4000         5  09:02:36
2633  2634  2015-12-11  Surulere  BBQ Philly Steak   4000         3  09:02:38
2634  2635  2015-12-07   Gbagada         Beef Suya   3000         5  09:02:38

      Revenue  Snap
2630    15000  3005
2631     6000  3002
2632    20000  4005
2633    12000  4003
2634    15000  3005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2635  2636  2015-12-10     Ikoyi  Hot Pepperoni Feast   4000         2
2636  2637  2015-12-03    Ibadan       Veggie Supreme   3000         5
2637  2638  2015-12-14     Lekki      Pepperoni Feast   4000         5
2638  2639  2015-12-13   Gbagada             Italiano   3000         3
2639  2640  2015-12-10  Surulere          BBQ Chicken   4000         4

          Time  Revenue  Snap
2635  09:02:41     8000  4002
2636  09:02:44    15000  3005
2637  09:02:46    20000  4005
2638  09:02:47     9000  3003
2639  09:02:47    16000  4004
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2640  2641  2015-12-04     Ikoyi       Beef Suya   3000         4  09:02:47
2641  2642  2015-12-13     Lekki    Chicken Suya   4000         1  09:02:47
2642  2643  2015-12-04   Gbagada       Margarita   4000         5  09:02:47
2643  2644  2015-12-05    Ibadan  Chicken Legend   2000         4  09:02:50
2644  2645  2015-12-15  Surulere         Meatzaa   2000         3  09:02:50

      Revenue  Snap
2640    12000  3004
2641     4000  4001
2642    20000  4005
2643     8000  2004
2644     6000  2003
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2645  2646  2015-12-07  Surulere  Veggie Supreme   3000         2  09:02:51
2646  2647  2015-12-04   Gbagada   Chicken Feast   2000         4  09:02:51
2647  2648  2015-12-13   Gbagada    Chicken Suya   4000         1  09:02:53
2648  2649  2015-12-14   Gbagada    Chicken Bali   2000         3  09:02:53
2649  2650  2015-12-05     Ikoyi   Chicken Feast   2000         4  09:02:57

      Revenue  Snap
2645     6000  3002
2646     8000  2004
2647     4000  4001
2648     6000  2003
2649     8000  2004
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
2650  2651  2015-12-04   Ibadan         Meatzaa   2000         1  09:03:00
2651  2652  2015-12-06    Lekki         Meatzaa   2000         3  09:03:01
2652  2653  2015-12-05    Lekki        Italiano   3000         5  09:03:03
2653  2654  2015-12-03  Gbagada  Chicken Legend   2000         2  09:03:04
2654  2655  2015-12-11    Lekki    Chicken Suya   4000         4  09:03:04

      Revenue  Snap
2650     2000  2001
2651     6000  2003
2652    15000  3005
2653     4000  2002
2654    16000  4004
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2655  2656  2015-12-08   Gbagada         Chicken Suya   4000         4
2656  2657  2015-12-06  Surulere       Veggie Supreme   3000         3
2657  2658  2015-12-13   Gbagada           Hot Veggie   4000         1
2658  2659  2015-12-09  Surulere  Hot Pepperoni Feast   4000         1
2659  2660  2015-12-14     Lekki         Chicken Bali   2000         1

          Time  Revenue  Snap
2655  09:03:05    16000  4004
2656  09:03:07     9000  3003
2657  09:03:08     4000  4001
2658  09:03:09     4000  4001
2659  09:03:10     2000  2001
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
2660  2661  2015-12-09  Surulere   Pepperoni Suya   3000         1  09:03:10
2661  2662  2015-12-05     Lekki  Pepperoni Feast   4000         4  09:03:10
2662  2663  2015-12-09   Gbagada          Meatzaa   2000         3  09:03:12
2663  2664  2015-12-08  Surulere     Chicken Suya   4000         5  09:03:12
2664  2665  2015-12-05  Surulere     Chicken Bali   2000         2  09:03:13

      Revenue  Snap
2660     3000  3001
2661    16000  4004
2662     6000  2003
2663    20000  4005
2664     4000  2002
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2665  2666  2015-12-14     Ikoyi     BBQ Philly Steak   4000         2
2666  2667  2015-12-06  Surulere  Hot Pepperoni Feast   4000         1
2667  2668  2015-12-05   Gbagada  Hot Pepperoni Feast   4000         4
2668  2669  2015-12-08   Gbagada            Beef Suya   3000         1
2669  2670  2015-12-05  Surulere            Margarita   4000         1

          Time  Revenue  Snap
2665  09:03:14     8000  4002
2666  09:03:15     4000  4001
2667  09:03:15    16000  4004
2668  09:03:15     3000  3001
2669  09:03:15     4000  4001
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
2670  2671  2015-12-03    Lekki       Beef Suya   3000         3  09:03:16
2671  2672  2015-12-12    Ikoyi  Chicken Legend   2000         3  09:03:18
2672  2673  2015-12-07   Ibadan  Pepperoni Suya   3000         1  09:03:20
2673  2674  2015-12-04  Gbagada      Hot Veggie   4000         1  09:03:21
2674  2675  2015-12-15    Ikoyi    Extravaganza   2000         4  09:03:22

      Revenue  Snap
2670     9000  3003
2671     6000  2003
2672     3000  3001
2673     4000  4001
2674     8000  2004
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2675  2676  2015-12-08     Lekki  Hot Pepperoni Feast   4000         3
2676  2677  2015-12-05     Ikoyi         Extravaganza   2000         1
2677  2678  2015-12-10     Lekki      Pepperoni Feast   4000         5
2678  2679  2015-12-07  Surulere       Pepperoni Suya   3000         1
2679  2680  2015-12-03     Ikoyi           Hot Veggie   4000         5

          Time  Revenue  Snap
2675  09:03:22    12000  4003
2676  09:03:22     2000  2001
2677  09:03:22    20000  4005
2678  09:03:25     3000  3001
2679  09:03:25    20000  4005
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
2680  2681  2015-12-13   Ibadan         Extravaganza   2000         2
2681  2682  2015-12-08    Ikoyi         Chicken Bali   2000         5
2682  2683  2015-12-14   Ibadan           Hot Veggie   4000         5
2683  2684  2015-12-10  Gbagada  Hot Pepperoni Feast   4000         1
2684  2685  2015-12-14   Ibadan        Chicken Feast   2000         3

          Time  Revenue  Snap
2680  09:03:27     4000  2002
2681  09:03:27    10000  2005
2682  09:03:28    20000  4005
2683  09:03:29     4000  4001
2684  09:03:29     6000  2003
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2685  2686  2015-12-03     Lekki  Veggie Supreme   3000         1  09:03:29
2686  2687  2015-12-03   Gbagada  Chicken Legend   2000         4  09:03:30
2687  2688  2015-12-13  Surulere      Hot Veggie   4000         5  09:03:31
2688  2689  2015-12-15  Surulere     BBQ Chicken   4000         3  09:03:31
2689  2690  2015-12-14  Surulere        Italiano   3000         3  09:03:35

      Revenue  Snap
2685     3000  3001
2686     8000  2004
2687    20000  4005
2688    12000  4003
2689     9000  3003
CHUNK BOSS
       S/N        Date  Branch        Pizza Sold  Price  Quantity      Time  \
2690  2691  2015-12-03  Ibadan       BBQ Chicken   4000         1  09:03:35
2691  2692  2015-12-12   Lekki  BBQ Philly Steak   4000         3  09:03:36
2692  2693  2015-12-10   Lekki          Italiano   3000         2  09:03:37
2693  2694  2015-12-14  Ibadan           Meatzaa   2000         4  09:03:42
2694  2695  2015-12-05  Ibadan           Meatzaa   2000         3  09:03:47

      Revenue  Snap
2690     4000  4001
2691    12000  4003
2692     6000  3002
2693     8000  2004
2694     6000  2003
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
2695  2696  2015-12-05  Surulere    Chicken Legend   2000         5  09:03:48
2696  2697  2015-12-05  Surulere       BBQ Chicken   4000         2  09:03:49
2697  2698  2015-12-13     Lekki  BBQ Philly Steak   4000         2  09:03:50
2698  2699  2015-12-07     Ikoyi         Beef Suya   3000         4  09:03:50
2699  2700  2015-12-15     Lekki           Meatzaa   2000         3  09:03:52

      Revenue  Snap
2695    10000  2005
2696     8000  4002
2697     8000  4002
2698    12000  3004
2699     6000  2003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2700  2701  2015-12-05   Gbagada       Pepperoni Suya   3000         4
2701  2702  2015-12-06    Ibadan            Margarita   4000         3
2702  2703  2015-12-14    Ibadan      Pepperoni Feast   4000         3
2703  2704  2015-12-03  Surulere            Beef Suya   3000         1
2704  2705  2015-12-10    Ibadan  Hot Pepperoni Feast   4000         1

          Time  Revenue  Snap
2700  09:03:52    12000  3004
2701  09:03:53    12000  4003
2702  09:03:53    12000  4003
2703  09:03:54     3000  3001
2704  09:03:55     4000  4001
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
2705  2706  2015-12-05     Ikoyi  BBQ Philly Steak   4000         4  09:03:56
2706  2707  2015-12-09     Lekki      Extravaganza   2000         4  09:03:56
2707  2708  2015-12-12  Surulere       BBQ Chicken   4000         3  09:03:56
2708  2709  2015-12-08     Lekki      Chicken Bali   2000         4  09:03:56
2709  2710  2015-12-11   Gbagada          Italiano   3000         2  09:03:57

      Revenue  Snap
2705    16000  4004
2706     8000  2004
2707    12000  4003
2708     8000  2004

2709     6000  3002
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2710  2711  2015-12-03     Lekki       Chicken Legend   2000         1
2711  2712  2015-12-14     Ikoyi       Chicken Legend   2000         5
2712  2713  2015-12-12   Gbagada              Meatzaa   2000         2
2713  2714  2015-12-13  Surulere  Hot Pepperoni Feast   4000         3
2714  2715  2015-12-04  Surulere       Chicken Legend   2000         3

          Time  Revenue  Snap
2710  09:04:02     2000  2001
2711  09:04:02    10000  2005
2712  09:04:03     4000  2002
2713  09:04:05    12000  4003
2714  09:04:07     6000  2003
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
2715  2716  2015-12-10  Gbagada  Hot Pepperoni Feast   4000         4
2716  2717  2015-12-05    Ikoyi        Chicken Feast   2000         2
2717  2718  2015-12-10   Ibadan       Veggie Supreme   3000         5
2718  2719  2015-12-13  Gbagada       Veggie Supreme   3000         1
2719  2720  2015-12-04  Gbagada             Italiano   3000         3

          Time  Revenue  Snap
2715  09:04:07    16000  4004
2716  09:04:07     4000  2002
2717  09:04:07    15000  3005
2718  09:04:08     3000  3001
2719  09:04:08     9000  3003
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
2720  2721  2015-12-05   Gbagada     Chicken Suya   4000         3  09:04:08
2721  2722  2015-12-11     Lekki   Veggie Supreme   3000         3  09:04:08
2722  2723  2015-12-12  Surulere  Pepperoni Feast   4000         3  09:04:08
2723  2724  2015-12-03   Gbagada       Hot Veggie   4000         5  09:04:12
2724  2725  2015-12-04     Lekki        Margarita   4000         1  09:04:12

      Revenue  Snap
2720    12000  4003
2721     9000  3003
2722    12000  4003
2723    20000  4005
2724     4000  4001
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
2725  2726  2015-12-05   Ibadan        Italiano   3000         1  09:04:12
2726  2727  2015-12-09    Lekki      Hot Veggie   4000         4  09:04:14
2727  2728  2015-12-08    Lekki        Italiano   3000         2  09:04:14
2728  2729  2015-12-12    Ikoyi  Veggie Supreme   3000         3  09:04:15
2729  2730  2015-12-07  Gbagada       Margarita   4000         4  09:04:15

      Revenue  Snap
2725     3000  3001
2726    16000  4004
2727     6000  3002
2728     9000  3003
2729    16000  4004
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
2730  2731  2015-12-13   Ibadan  Hot Pepperoni Feast   4000         1
2731  2732  2015-12-10    Ikoyi       Chicken Legend   2000         2
2732  2733  2015-12-11  Gbagada      Pepperoni Feast   4000         2
2733  2734  2015-12-06    Lekki         Extravaganza   2000         4
2734  2735  2015-12-04  Gbagada             Italiano   3000         3

          Time  Revenue  Snap
2730  09:04:16     4000  4001
2731  09:04:22     4000  2002
2732  09:04:22     8000  4002
2733  09:04:22     8000  2004
2734  09:04:26     9000  3003
CHUNK BOSS
       S/N        Date  Branch           Pizza Sold  Price  Quantity  \
2735  2736  2015-12-13   Ikoyi  Hot Pepperoni Feast   4000         1
2736  2737  2015-12-09  Ibadan         Chicken Suya   4000         3
2737  2738  2015-12-05   Ikoyi         Chicken Suya   4000         5
2738  2739  2015-12-09   Lekki          BBQ Chicken   4000         3
2739  2740  2015-12-09   Lekki       Chicken Legend   2000         5

          Time  Revenue  Snap
2735  09:04:26     4000  4001
2736  09:04:28    12000  4003
2737  09:04:28    20000  4005
2738  09:04:30    12000  4003
2739  09:04:31    10000  2005
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
2740  2741  2015-12-06    Ikoyi  BBQ Philly Steak   4000         1  09:04:32
2741  2742  2015-12-11  Gbagada     Chicken Feast   2000         1  09:04:34
2742  2743  2015-12-12    Lekki           Meatzaa   2000         5  09:04:34
2743  2744  2015-12-15  Gbagada       BBQ Chicken   4000         2  09:04:34
2744  2745  2015-12-08    Ikoyi           Meatzaa   2000         2  09:04:34

      Revenue  Snap
2740     4000  4001
2741     2000  2001
2742    10000  2005
2743     8000  4002
2744     4000  2002
CHUNK BOSS
       S/N        Date  Branch           Pizza Sold  Price  Quantity  \
2745  2746  2015-12-06   Ikoyi         Chicken Suya   4000         5
2746  2747  2015-12-13  Ibadan  Hot Pepperoni Feast   4000         5
2747  2748  2015-12-08  Ibadan            Beef Suya   3000         5
2748  2749  2015-12-05   Ikoyi         Chicken Bali   2000         3
2749  2750  2015-12-03   Lekki            Margarita   4000         5

          Time  Revenue  Snap
2745  09:04:36    20000  4005
2746  09:04:36    20000  4005
2747  09:04:38    15000  3005
2748  09:04:39     6000  2003
2749  09:04:39    20000  4005
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
2750  2751  2015-12-07  Gbagada            Beef Suya   3000         1
2751  2752  2015-12-11    Ikoyi            Beef Suya   3000         1
2752  2753  2015-12-12    Lekki  Hot Pepperoni Feast   4000         2
2753  2754  2015-12-13    Lekki         Chicken Bali   2000         4
2754  2755  2015-12-04    Ikoyi       Veggie Supreme   3000         2

          Time  Revenue  Snap
2750  09:04:40     3000  3001
2751  09:04:40     3000  3001
2752  09:04:42     8000  4002
2753  09:04:43     8000  2004
2754  09:04:44     6000  3002
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2755  2756  2015-12-05     Ikoyi         Chicken Bali   2000         1
2756  2757  2015-12-11  Surulere       Veggie Supreme   3000         5
2757  2758  2015-12-15    Ibadan            Beef Suya   3000         1
2758  2759  2015-12-11  Surulere  Hot Pepperoni Feast   4000         1
2759  2760  2015-12-05   Gbagada         Chicken Bali   2000         4

          Time  Revenue  Snap
2755  09:04:45     2000  2001
2756  09:04:46    15000  3005
2757  09:04:46     3000  3001
2758  09:04:47     4000  4001
2759  09:04:48     8000  2004
CHUNK BOSS
       S/N        Date    Branch    Pizza Sold  Price  Quantity      Time  \
2760  2761  2015-12-06   Gbagada    Hot Veggie   4000         1  09:04:50
2761  2762  2015-12-13   Gbagada    Hot Veggie   4000         4  09:04:51
2762  2763  2015-12-04   Gbagada  Extravaganza   2000         2  09:04:51
2763  2764  2015-12-11     Lekki     Beef Suya   3000         3  09:04:52
2764  2765  2015-12-07  Surulere  Extravaganza   2000         2  09:04:54

      Revenue  Snap
2760     4000  4001
2761    16000  4004
2762     4000  2002
2763     9000  3003
2764     4000  2002
CHUNK BOSS
       S/N        Date   Branch    Pizza Sold  Price  Quantity      Time  \
2765  2766  2015-12-10   Ibadan     Beef Suya   3000         4  09:04:56
2766  2767  2015-12-05    Lekki      Italiano   3000         3  09:04:57
2767  2768  2015-12-04    Lekki  Extravaganza   2000         2  09:04:57
2768  2769  2015-12-12    Ikoyi     Beef Suya   3000         4  09:04:57
2769  2770  2015-12-10  Gbagada  Extravaganza   2000         2  09:04:57

      Revenue  Snap
2765    12000  3004
2766     9000  3003
2767     4000  2002
2768    12000  3004
2769     4000  2002
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
2770  2771  2015-12-06   Ibadan  Hot Pepperoni Feast   4000         4
2771  2772  2015-12-11  Gbagada            Beef Suya   3000         5
2772  2773  2015-12-09    Ikoyi         Chicken Bali   2000         5
2773  2774  2015-12-12    Lekki       Veggie Supreme   3000         2
2774  2775  2015-12-09    Ikoyi  Hot Pepperoni Feast   4000         4

          Time  Revenue  Snap
2770  09:05:00    16000  4004
2771  09:05:01    15000  3005
2772  09:05:01    10000  2005
2773  09:05:03     6000  3002
2774  09:05:05    16000  4004
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2775  2776  2015-12-13  Surulere           Hot Veggie   4000         4
2776  2777  2015-12-12     Lekki         Extravaganza   2000         5
2777  2778  2015-12-04     Lekki  Hot Pepperoni Feast   4000         1
2778  2779  2015-12-15   Gbagada      Pepperoni Feast   4000         1
2779  2780  2015-12-07     Ikoyi       Chicken Legend   2000         3

          Time  Revenue  Snap
2775  09:05:06    16000  4004
2776  09:05:08    10000  2005
2777  09:05:11     4000  4001
2778  09:05:12     4000  4001
2779  09:05:13     6000  2003
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2780  2781  2015-12-15   Gbagada    Chicken Suya   4000         5  09:05:15
2781  2782  2015-12-04  Surulere  Veggie Supreme   3000         1  09:05:16
2782  2783  2015-12-06   Gbagada    Chicken Bali   2000         2  09:05:18
2783  2784  2015-12-10  Surulere        Italiano   3000         2  09:05:19
2784  2785  2015-12-07    Ibadan        Italiano   3000         4  09:05:19

      Revenue  Snap
2780    20000  4005
2781     3000  3001
2782     4000  2002
2783     6000  3002
2784    12000  3004
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
2785  2786  2015-12-09   Ibadan  Hot Pepperoni Feast   4000         3
2786  2787  2015-12-07  Gbagada         Extravaganza   2000         4
2787  2788  2015-12-10  Gbagada              Meatzaa   2000         4
2788  2789  2015-12-10   Ibadan         Chicken Bali   2000         1
2789  2790  2015-12-13    Ikoyi       Pepperoni Suya   3000         4

          Time  Revenue  Snap
2785  09:05:19    12000  4003
2786  09:05:20     8000  2004
2787  09:05:20     8000  2004
2788  09:05:21     2000  2001
2789  09:05:21    12000  3004
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
2790  2791  2015-12-10   Gbagada      Extravaganza   2000         1  09:05:22
2791  2792  2015-12-07  Surulere         Beef Suya   3000         1  09:05:24
2792  2793  2015-12-15     Ikoyi  BBQ Philly Steak   4000         3  09:05:24
2793  2794  2015-12-04     Lekki  BBQ Philly Steak   4000         3  09:05:26
2794  2795  2015-12-13     Lekki          Italiano   3000         4  09:05:30

      Revenue  Snap
2790     2000  2001
2791     3000  3001
2792    12000  4003
2793    12000  4003
2794    12000  3004
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
2795  2796  2015-12-04  Surulere   Pepperoni Feast   4000         3  09:05:34
2796  2797  2015-12-08  Surulere  BBQ Philly Steak   4000         3  09:05:37
2797  2798  2015-12-06     Lekki   Pepperoni Feast   4000         2  09:05:37
2798  2799  2015-12-10     Lekki      Extravaganza   2000         2  09:05:37
2799  2800  2015-12-14  Surulere     Chicken Feast   2000         3  09:05:38

      Revenue  Snap
2795    12000  4003
2796    12000  4003
2797     8000  4002
2798     4000  2002

2799     6000  2003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2800  2801  2015-12-13  Surulere            Margarita   4000         4
2801  2802  2015-12-05     Ikoyi             Italiano   3000         3
2802  2803  2015-12-06    Ibadan      Pepperoni Feast   4000         3
2803  2804  2015-12-10   Gbagada  Hot Pepperoni Feast   4000         2
2804  2805  2015-12-06    Ibadan         Chicken Suya   4000         5

          Time  Revenue  Snap
2800  09:05:38    16000  4004
2801  09:05:38     9000  3003
2802  09:05:39    12000  4003
2803  09:05:41     8000  4002
2804  09:05:42    20000  4005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2805  2806  2015-12-06     Ikoyi       Veggie Supreme   3000         4
2806  2807  2015-12-11  Surulere      Pepperoni Feast   4000         1
2807  2808  2015-12-05   Gbagada        Chicken Feast   2000         3
2808  2809  2015-12-05     Lekki  Hot Pepperoni Feast   4000         4
2809  2810  2015-12-10     Ikoyi     BBQ Philly Steak   4000         4

          Time  Revenue  Snap
2805  09:05:42    12000  3004
2806  09:05:43     4000  4001
2807  09:05:44     6000  2003
2808  09:05:44    16000  4004
2809  09:05:45    16000  4004
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
2810  2811  2015-12-08     Ikoyi  BBQ Philly Steak   4000         4  09:05:48
2811  2812  2015-12-07     Ikoyi          Italiano   3000         4  09:05:51
2812  2813  2015-12-06     Ikoyi      Chicken Suya   4000         5  09:05:51
2813  2814  2015-12-12     Lekki        Hot Veggie   4000         5  09:05:51
2814  2815  2015-12-04  Surulere      Chicken Bali   2000         2  09:05:52

      Revenue  Snap
2810    16000  4004
2811    12000  3004
2812    20000  4005
2813    20000  4005
2814     4000  2002
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2815  2816  2015-12-15    Ibadan  Veggie Supreme   3000         2  09:05:53
2816  2817  2015-12-07     Ikoyi        Italiano   3000         3  09:05:53
2817  2818  2015-12-12     Lekki     BBQ Chicken   4000         2  09:05:54
2818  2819  2015-12-08    Ibadan         Meatzaa   2000         1  09:05:55
2819  2820  2015-12-13  Surulere        Italiano   3000         1  09:05:55

      Revenue  Snap
2815     6000  3002
2816     9000  3003
2817     8000  4002
2818     2000  2001
2819     3000  3001
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
2820  2821  2015-12-11     Lekki     Chicken Bali   2000         2  09:05:59
2821  2822  2015-12-13     Ikoyi  Pepperoni Feast   4000         4  09:06:00
2822  2823  2015-12-05  Surulere    Chicken Feast   2000         4  09:06:04
2823  2824  2015-12-03    Ibadan    Chicken Feast   2000         5  09:06:04
2824  2825  2015-12-05     Ikoyi   Pepperoni Suya   3000         4  09:06:04

      Revenue  Snap
2820     4000  2002
2821    16000  4004
2822     8000  2004
2823    10000  2005
2824    12000  3004
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
2825  2826  2015-12-09     Lekki     Chicken Bali   2000         3  09:06:04
2826  2827  2015-12-07    Ibadan     Extravaganza   2000         1  09:06:05
2827  2828  2015-12-14  Surulere          Meatzaa   2000         2  09:06:06
2828  2829  2015-12-15   Gbagada  Pepperoni Feast   4000         2  09:06:06
2829  2830  2015-12-10     Ikoyi   Veggie Supreme   3000         4  09:06:07

      Revenue  Snap
2825     6000  2003
2826     2000  2001
2827     4000  2002
2828     8000  4002
2829    12000  3004
CHUNK BOSS
       S/N        Date  Branch       Pizza Sold  Price  Quantity      Time  \
2830  2831  2015-12-04   Ikoyi     Chicken Suya   4000         2  09:06:10
2831  2832  2015-12-14   Lekki  Pepperoni Feast   4000         5  09:06:10
2832  2833  2015-12-09   Lekki      BBQ Chicken   4000         5  09:06:11
2833  2834  2015-12-14  Ibadan     Chicken Bali   2000         3  09:06:12
2834  2835  2015-12-12   Lekki        Margarita   4000         4  09:06:12

      Revenue  Snap
2830     8000  4002
2831    20000  4005
2832    20000  4005
2833     6000  2003
2834    16000  4004
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
2835  2836  2015-12-14  Surulere  BBQ Philly Steak   4000         4  09:06:12
2836  2837  2015-12-15     Lekki      Chicken Suya   4000         5  09:06:15
2837  2838  2015-12-04     Lekki    Chicken Legend   2000         1  09:06:15
2838  2839  2015-12-11     Lekki    Chicken Legend   2000         4  09:06:16
2839  2840  2015-12-04     Ikoyi      Chicken Bali   2000         4  09:06:16

      Revenue  Snap
2835    16000  4004
2836    20000  4005
2837     2000  2001
2838     8000  2004
2839     8000  2004
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
2840  2841  2015-12-05  Gbagada      Pepperoni Feast   4000         1
2841  2842  2015-12-03    Ikoyi        Chicken Feast   2000         1
2842  2843  2015-12-07   Ibadan  Hot Pepperoni Feast   4000         3
2843  2844  2015-12-05   Ibadan             Italiano   3000         1
2844  2845  2015-12-10  Gbagada            Margarita   4000         1

          Time  Revenue  Snap
2840  09:06:16     4000  4001
2841  09:06:17     2000  2001
2842  09:06:17    12000  4003
2843  09:06:21     3000  3001
2844  09:06:22     4000  4001
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2845  2846  2015-12-15     Lekki  Hot Pepperoni Feast   4000         4
2846  2847  2015-12-05     Ikoyi              Meatzaa   2000         4
2847  2848  2015-12-14  Surulere            Beef Suya   3000         3
2848  2849  2015-12-11    Ibadan     BBQ Philly Steak   4000         5
2849  2850  2015-12-10     Ikoyi            Margarita   4000         1

          Time  Revenue  Snap
2845  09:06:22    16000  4004
2846  09:06:24     8000  2004
2847  09:06:25     9000  3003
2848  09:06:25    20000  4005
2849  09:06:26     4000  4001
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
2850  2851  2015-12-05  Gbagada    Chicken Suya   4000         1  09:06:26
2851  2852  2015-12-14  Gbagada   Chicken Feast   2000         1  09:06:30
2852  2853  2015-12-09  Gbagada  Chicken Legend   2000         2  09:06:30
2853  2854  2015-12-05    Ikoyi      Hot Veggie   4000         4  09:06:31
2854  2855  2015-12-07    Ikoyi     BBQ Chicken   4000         1  09:06:33

      Revenue  Snap
2850     4000  4001
2851     2000  2001
2852     4000  2002
2853    16000  4004
2854     4000  4001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2855  2856  2015-12-04  Surulere    Chicken Bali   2000         5  09:06:35
2856  2857  2015-12-09     Ikoyi  Pepperoni Suya   3000         4  09:06:37
2857  2858  2015-12-10   Gbagada  Veggie Supreme   3000         2  09:06:37
2858  2859  2015-12-13     Lekki  Chicken Legend   2000         1  09:06:38
2859  2860  2015-12-07   Gbagada       Beef Suya   3000         3  09:06:38

      Revenue  Snap
2855    10000  2005
2856    12000  3004
2857     6000  3002
2858     2000  2001
2859     9000  3003
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
2860  2861  2015-12-12  Gbagada  BBQ Philly Steak   4000         3  09:06:40
2861  2862  2015-12-09    Ikoyi         Margarita   4000         4  09:06:46
2862  2863  2015-12-12   Ibadan  BBQ Philly Steak   4000         2  09:06:46
2863  2864  2015-12-07    Lekki  BBQ Philly Steak   4000         5  09:06:47
2864  2865  2015-12-11  Gbagada        Hot Veggie   4000         2  09:06:48

      Revenue  Snap
2860    12000  4003
2861    16000  4004
2862     8000  4002
2863    20000  4005
2864     8000  4002
CHUNK BOSS
       S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
2865  2866  2015-12-08    Lekki  Pepperoni Feast   4000         2  09:06:48
2866  2867  2015-12-06    Ikoyi        Beef Suya   3000         5  09:06:49
2867  2868  2015-12-04    Ikoyi    Chicken Feast   2000         1  09:06:52
2868  2869  2015-12-07  Gbagada        Beef Suya   3000         1  09:06:52
2869  2870  2015-12-12    Lekki      BBQ Chicken   4000         5  09:06:52

      Revenue  Snap
2865     8000  4002
2866    15000  3005
2867     2000  2001
2868     3000  3001
2869    20000  4005
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
2870  2871  2015-12-03    Ibadan  BBQ Philly Steak   4000         5  09:06:53
2871  2872  2015-12-15  Surulere      Chicken Bali   2000         1  09:06:53
2872  2873  2015-12-14     Ikoyi    Pepperoni Suya   3000         4  09:06:53
2873  2874  2015-12-03     Lekki      Chicken Suya   4000         1  09:06:54
2874  2875  2015-12-06    Ibadan      Chicken Bali   2000         5  09:06:55

      Revenue  Snap
2870    20000  4005
2871     2000  2001
2872    12000  3004
2873     4000  4001
2874    10000  2005
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
2875  2876  2015-12-15     Lekki         Margarita   4000         3  09:06:56
2876  2877  2015-12-09     Lekki  BBQ Philly Steak   4000         2  09:06:56
2877  2878  2015-12-06  Surulere     Chicken Feast   2000         2  09:06:58
2878  2879  2015-12-10  Surulere          Italiano   3000         1  09:06:59
2879  2880  2015-12-14     Lekki    Veggie Supreme   3000         3  09:07:01

      Revenue  Snap
2875    12000  4003
2876     8000  4002
2877     4000  2002
2878     3000  3001
2879     9000  3003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2880  2881  2015-12-05  Surulere     BBQ Philly Steak   4000         4
2881  2882  2015-12-12    Ibadan  Hot Pepperoni Feast   4000         5
2882  2883  2015-12-15     Ikoyi       Chicken Legend   2000         3
2883  2884  2015-12-03     Lekki       Pepperoni Suya   3000         5
2884  2885  2015-12-09    Ibadan        Chicken Feast   2000         3

          Time  Revenue  Snap
2880  09:07:02    16000  4004
2881  09:07:04    20000  4005
2882  09:07:05     6000  2003
2883  09:07:06    15000  3005
2884  09:07:06     6000  2003
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
2885  2886  2015-12-12   Ibadan    Veggie Supreme   3000         5  09:07:07
2886  2887  2015-12-13  Gbagada          Italiano   3000         2  09:07:08
2887  2888  2015-12-14  Gbagada   Pepperoni Feast   4000         5  09:07:08
2888  2889  2015-12-15  Gbagada  BBQ Philly Steak   4000         4  09:07:09
2889  2890  2015-12-12   Ibadan         Beef Suya   3000         4  09:07:09

      Revenue  Snap
2885    15000  3005
2886     6000  3002
2887    20000  4005
2888    16000  4004

2889    12000  3004
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2890  2891  2015-12-04  Surulere            Margarita   4000         2
2891  2892  2015-12-04   Gbagada         Extravaganza   2000         4
2892  2893  2015-12-09   Gbagada  Hot Pepperoni Feast   4000         3
2893  2894  2015-12-10     Ikoyi          BBQ Chicken   4000         1
2894  2895  2015-12-11    Ibadan     BBQ Philly Steak   4000         1

          Time  Revenue  Snap
2890  09:07:09     8000  4002
2891  09:07:09     8000  2004
2892  09:07:10    12000  4003
2893  09:07:12     4000  4001
2894  09:07:13     4000  4001
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
2895  2896  2015-12-03  Surulere      BBQ Chicken   4000         2  09:07:15
2896  2897  2015-12-14    Ibadan     Chicken Suya   4000         3  09:07:15
2897  2898  2015-12-08  Surulere     Chicken Suya   4000         2  09:07:16
2898  2899  2015-12-09    Ibadan       Hot Veggie   4000         5  09:07:17
2899  2900  2015-12-15     Lekki  Pepperoni Feast   4000         3  09:07:18

      Revenue  Snap
2895     8000  4002
2896    12000  4003
2897     8000  4002
2898    20000  4005
2899    12000  4003
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
2900  2901  2015-12-07  Gbagada      Extravaganza   2000         3  09:07:18
2901  2902  2015-12-06    Ikoyi           Meatzaa   2000         2  09:07:20
2902  2903  2015-12-05    Lekki  BBQ Philly Steak   4000         1  09:07:21
2903  2904  2015-12-08    Ikoyi          Italiano   3000         1  09:07:22
2904  2905  2015-12-04  Gbagada          Italiano   3000         4  09:07:23

      Revenue  Snap
2900     6000  2003
2901     4000  2002
2902     4000  4001
2903     3000  3001
2904    12000  3004
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
2905  2906  2015-12-09     Lekki          Italiano   3000         5  09:07:24
2906  2907  2015-12-14   Gbagada  BBQ Philly Steak   4000         5  09:07:26
2907  2908  2015-12-12     Lekki         Beef Suya   3000         3  09:07:26
2908  2909  2015-12-14    Ibadan     Chicken Feast   2000         2  09:07:26
2909  2910  2015-12-06  Surulere         Margarita   4000         2  09:07:26

      Revenue  Snap
2905    15000  3005
2906    20000  4005
2907     9000  3003
2908     4000  2002
2909     8000  4002
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2910  2911  2015-12-07     Ikoyi  Hot Pepperoni Feast   4000         4
2911  2912  2015-12-13     Lekki       Veggie Supreme   3000         2
2912  2913  2015-12-04  Surulere         Extravaganza   2000         2
2913  2914  2015-12-05     Ikoyi       Veggie Supreme   3000         2
2914  2915  2015-12-06  Surulere             Italiano   3000         2

          Time  Revenue  Snap
2910  09:07:28    16000  4004
2911  09:07:28     6000  3002
2912  09:07:28     4000  2002
2913  09:07:29     6000  3002
2914  09:07:29     6000  3002
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2915  2916  2015-12-07    Ibadan    Chicken Bali   2000         2  09:07:30
2916  2917  2015-12-15     Lekki       Margarita   4000         5  09:07:31
2917  2918  2015-12-15     Lekki    Chicken Bali   2000         1  09:07:32
2918  2919  2015-12-10  Surulere       Margarita   4000         4  09:07:33
2919  2920  2015-12-05     Lekki  Pepperoni Suya   3000         2  09:07:34

      Revenue  Snap
2915     4000  2002
2916    20000  4005
2917     2000  2001
2918    16000  4004
2919     6000  3002
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2920  2921  2015-12-04     Ikoyi    Chicken Suya   4000         4  09:07:34
2921  2922  2015-12-06     Lekki      Hot Veggie   4000         1  09:07:36
2922  2923  2015-12-09  Surulere   Chicken Feast   2000         4  09:07:36
2923  2924  2015-12-14     Lekki      Hot Veggie   4000         3  09:07:36
2924  2925  2015-12-05     Lekki  Chicken Legend   2000         1  09:07:38

      Revenue  Snap
2920    16000  4004
2921     4000  4001
2922     8000  2004
2923    12000  4003
2924     2000  2001
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2925  2926  2015-12-14     Ikoyi        Chicken Feast   2000         3
2926  2927  2015-12-08  Surulere         Chicken Suya   4000         2
2927  2928  2015-12-15   Gbagada         Extravaganza   2000         5
2928  2929  2015-12-04    Ibadan  Hot Pepperoni Feast   4000         2
2929  2930  2015-12-09  Surulere      Pepperoni Feast   4000         3

          Time  Revenue  Snap
2925  09:07:38     6000  2003
2926  09:07:39     8000  4002
2927  09:07:40    10000  2005
2928  09:07:40     8000  4002
2929  09:07:41    12000  4003
CHUNK BOSS
       S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
2930  2931  2015-12-14  Gbagada  Pepperoni Feast   4000         3  09:07:43
2931  2932  2015-12-12    Ikoyi       Hot Veggie   4000         2  09:07:43
2932  2933  2015-12-14  Gbagada         Italiano   3000         2  09:07:43
2933  2934  2015-12-04  Gbagada          Meatzaa   2000         2  09:07:43
2934  2935  2015-12-11    Ikoyi        Beef Suya   3000         1  09:07:45

      Revenue  Snap
2930    12000  4003
2931     8000  4002
2932     6000  3002
2933     4000  2002
2934     3000  3001
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
2935  2936  2015-12-05    Lekki  Pepperoni Suya   3000         3  09:07:45
2936  2937  2015-12-05   Ibadan   Chicken Feast   2000         1  09:07:46
2937  2938  2015-12-15  Gbagada       Margarita   4000         2  09:07:50
2938  2939  2015-12-07   Ibadan    Extravaganza   2000         3  09:07:51
2939  2940  2015-12-09    Ikoyi      Hot Veggie   4000         1  09:07:51

      Revenue  Snap
2935     9000  3003
2936     2000  2001
2937     8000  4002
2938     6000  2003
2939     4000  4001
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
2940  2941  2015-12-04     Lekki      Extravaganza   2000         3  09:07:52
2941  2942  2015-12-12    Ibadan  BBQ Philly Steak   4000         5  09:07:53
2942  2943  2015-12-04   Gbagada      Chicken Suya   4000         3  09:07:53
2943  2944  2015-12-12  Surulere  BBQ Philly Steak   4000         4  09:07:53
2944  2945  2015-12-11    Ibadan        Hot Veggie   4000         3  09:07:54

      Revenue  Snap
2940     6000  2003
2941    20000  4005
2942    12000  4003
2943    16000  4004
2944    12000  4003
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2945  2946  2015-12-09   Gbagada  Chicken Legend   2000         2  09:07:57
2946  2947  2015-12-03   Gbagada   Chicken Feast   2000         3  09:07:58
2947  2948  2015-12-07    Ibadan      Hot Veggie   4000         3  09:07:59
2948  2949  2015-12-11   Gbagada  Veggie Supreme   3000         4  09:08:00
2949  2950  2015-12-08  Surulere    Extravaganza   2000         2  09:08:01

      Revenue  Snap
2945     4000  2002
2946     6000  2003
2947    12000  4003
2948    12000  3004
2949     4000  2002
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
2950  2951  2015-12-14  Gbagada     BBQ Chicken   4000         5  09:08:02
2951  2952  2015-12-06    Lekki  Pepperoni Suya   3000         3  09:08:02
2952  2953  2015-12-14    Lekki        Italiano   3000         4  09:08:02
2953  2954  2015-12-04    Lekki    Chicken Suya   4000         1  09:08:03
2954  2955  2015-12-09   Ibadan  Pepperoni Suya   3000         4  09:08:04

      Revenue  Snap
2950    20000  4005
2951     9000  3003
2952    12000  3004
2953     4000  4001
2954    12000  3004
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
2955  2956  2015-12-13     Lekki     Extravaganza   2000         4  09:08:04
2956  2957  2015-12-12  Surulere     Chicken Suya   4000         1  09:08:05
2957  2958  2015-12-12   Gbagada   Pepperoni Suya   3000         1  09:08:05
2958  2959  2015-12-08     Ikoyi  Pepperoni Feast   4000         5  09:08:06
2959  2960  2015-12-04     Lekki   Pepperoni Suya   3000         2  09:08:07

      Revenue  Snap
2955     8000  2004
2956     4000  4001
2957     3000  3001
2958    20000  4005
2959     6000  3002
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2960  2961  2015-12-07   Gbagada         Chicken Suya   4000         1
2961  2962  2015-12-07   Gbagada  Hot Pepperoni Feast   4000         2
2962  2963  2015-12-14   Gbagada         Chicken Bali   2000         2
2963  2964  2015-12-03   Gbagada             Italiano   3000         3
2964  2965  2015-12-13  Surulere              Meatzaa   2000         3

          Time  Revenue  Snap
2960  09:08:09     4000  4001
2961  09:08:12     8000  4002
2962  09:08:18     4000  2002
2963  09:08:19     9000  3003
2964  09:08:26     6000  2003
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
2965  2966  2015-12-03  Gbagada  Veggie Supreme   3000         4  09:08:27
2966  2967  2015-12-08  Gbagada  Pepperoni Suya   3000         3  09:08:30
2967  2968  2015-12-11   Ibadan  Chicken Legend   2000         1  09:08:34
2968  2969  2015-12-10   Ibadan  Pepperoni Suya   3000         5  09:08:36
2969  2970  2015-12-12  Gbagada       Beef Suya   3000         2  09:08:38

      Revenue  Snap
2965    12000  3004
2966     9000  3003
2967     2000  2001
2968    15000  3005
2969     6000  3002
CHUNK BOSS
       S/N        Date   Branch    Pizza Sold  Price  Quantity      Time  \
2970  2971  2015-12-08    Lekki  Extravaganza   2000         4  09:08:38
2971  2972  2015-12-08  Gbagada  Extravaganza   2000         3  09:08:39
2972  2973  2015-12-04    Lekki   BBQ Chicken   4000         3  09:08:39
2973  2974  2015-12-12    Lekki      Italiano   3000         1  09:08:40
2974  2975  2015-12-15    Ikoyi     Beef Suya   3000         5  09:08:41

      Revenue  Snap
2970     8000  2004
2971     6000  2003
2972    12000  4003
2973     3000  3001
2974    15000  3005
CHUNK BOSS

       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
2975  2976  2015-12-06     Lekki  Chicken Legend   2000         5  09:08:43
2976  2977  2015-12-06   Gbagada  Chicken Legend   2000         2  09:08:43
2977  2978  2015-12-09  Surulere         Meatzaa   2000         2  09:08:44
2978  2979  2015-12-14    Ibadan      Hot Veggie   4000         3  09:08:44
2979  2980  2015-12-06     Lekki        Italiano   3000         3  09:08:44

      Revenue  Snap
2975    10000  2005
2976     4000  2002
2977     4000  2002
2978    12000  4003
2979     9000  3003
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
2980  2981  2015-12-14  Gbagada      Chicken Bali   2000         4  09:08:48
2981  2982  2015-12-12   Ibadan    Chicken Legend   2000         3  09:08:49
2982  2983  2015-12-10  Gbagada        Hot Veggie   4000         4  09:08:49
2983  2984  2015-12-11    Ikoyi      Chicken Bali   2000         5  09:08:49
2984  2985  2015-12-07  Gbagada  BBQ Philly Steak   4000         4  09:08:50

      Revenue  Snap
2980     8000  2004
2981     6000  2003
2982    16000  4004
2983    10000  2005
2984    16000  4004
CHUNK BOSS
       S/N        Date   Branch     Pizza Sold  Price  Quantity      Time  \
2985  2986  2015-12-14  Gbagada     Hot Veggie   4000         2  09:08:52
2986  2987  2015-12-05   Ibadan  Chicken Feast   2000         4  09:08:55
2987  2988  2015-12-13  Gbagada      Margarita   4000         5  09:08:56
2988  2989  2015-12-14  Gbagada  Chicken Feast   2000         5  09:08:56
2989  2990  2015-12-04   Ibadan   Chicken Bali   2000         5  09:08:57

      Revenue  Snap
2985     8000  4002
2986     8000  2004
2987    20000  4005
2988    10000  2005
2989    10000  2005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
2990  2991  2015-12-12    Ibadan          BBQ Chicken   4000         5
2991  2992  2015-12-15     Ikoyi          BBQ Chicken   4000         1
2992  2993  2015-12-04    Ibadan  Hot Pepperoni Feast   4000         1
2993  2994  2015-12-15     Lekki          BBQ Chicken   4000         2
2994  2995  2015-12-12  Surulere        Chicken Feast   2000         5

          Time  Revenue  Snap
2990  09:08:58    20000  4005
2991  09:08:58     4000  4001
2992  09:08:59     4000  4001
2993  09:08:59     8000  4002
2994  09:08:59    10000  2005
CHUNK BOSS
       S/N        Date    Branch    Pizza Sold  Price  Quantity      Time  \
2995  2996  2015-12-13   Gbagada      Italiano   3000         3  09:09:00
2996  2997  2015-12-09  Surulere   BBQ Chicken   4000         1  09:09:00
2997  2998  2015-12-11  Surulere  Chicken Suya   4000         4  09:09:02
2998  2999  2015-12-04    Ibadan    Hot Veggie   4000         2  09:09:02
2999  3000  2015-12-07  Surulere  Extravaganza   2000         2  09:09:04

      Revenue  Snap
2995     9000  3003
2996     4000  4001
2997    16000  4004
2998     8000  4002
2999     4000  2002
CHUNK BOSS
       S/N        Date   Branch    Pizza Sold  Price  Quantity      Time  \
3000  3001  2015-12-11    Lekki  Chicken Bali   2000         3  09:09:04
3001  3002  2015-12-05  Gbagada      Italiano   3000         4  09:09:06
3002  3003  2015-12-03    Ikoyi  Chicken Suya   4000         3  09:09:06
3003  3004  2015-12-14    Lekki   BBQ Chicken   4000         5  09:09:09
3004  3005  2015-12-07   Ibadan       Meatzaa   2000         3  09:09:09

      Revenue  Snap
3000     6000  2003
3001    12000  3004
3002    12000  4003
3003    20000  4005
3004     6000  2003
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
3005  3006  2015-12-07    Ibadan          Italiano   3000         5  09:09:10
3006  3007  2015-12-03     Lekki  BBQ Philly Steak   4000         5  09:09:12
3007  3008  2015-12-03  Surulere       BBQ Chicken   4000         3  09:09:14
3008  3009  2015-12-08  Surulere        Hot Veggie   4000         3  09:09:15
3009  3010  2015-12-06   Gbagada        Hot Veggie   4000         5  09:09:18

      Revenue  Snap
3005    15000  3005
3006    20000  4005
3007    12000  4003
3008    12000  4003
3009    20000  4005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3010  3011  2015-12-10     Lekki         Chicken Bali   2000         3
3011  3012  2015-12-03  Surulere            Margarita   4000         5
3012  3013  2015-12-03     Lekki  Hot Pepperoni Feast   4000         3
3013  3014  2015-12-14  Surulere       Pepperoni Suya   3000         4
3014  3015  2015-12-15  Surulere      Pepperoni Feast   4000         2

          Time  Revenue  Snap
3010  09:09:23     6000  2003
3011  09:09:25    20000  4005
3012  09:09:28    12000  4003
3013  09:09:28    12000  3004
3014  09:09:29     8000  4002
CHUNK BOSS
       S/N        Date  Branch       Pizza Sold  Price  Quantity      Time  \
3015  3016  2015-12-03  Ibadan       Hot Veggie   4000         5  09:09:29
3016  3017  2015-12-05  Ibadan        Beef Suya   3000         2  09:09:31
3017  3018  2015-12-13  Ibadan     Chicken Suya   4000         4  09:09:32
3018  3019  2015-12-07  Ibadan     Extravaganza   2000         4  09:09:32
3019  3020  2015-12-11   Ikoyi  Pepperoni Feast   4000         3  09:09:34

      Revenue  Snap
3015    20000  4005
3016     6000  3002
3017    16000  4004
3018     8000  2004
3019    12000  4003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3020  3021  2015-12-14   Gbagada       Veggie Supreme   3000         4
3021  3022  2015-12-06  Surulere       Pepperoni Suya   3000         3
3022  3023  2015-12-15  Surulere  Hot Pepperoni Feast   4000         3
3023  3024  2015-12-13     Lekki         Chicken Bali   2000         1
3024  3025  2015-12-15   Gbagada  Hot Pepperoni Feast   4000         5

          Time  Revenue  Snap
3020  09:09:34    12000  3004
3021  09:09:36     9000  3003
3022  09:09:36    12000  4003
3023  09:09:37     2000  2001
3024  09:09:38    20000  4005
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
3025  3026  2015-12-09     Lekki     Extravaganza   2000         3  09:09:41
3026  3027  2015-12-08   Gbagada  Pepperoni Feast   4000         3  09:09:42
3027  3028  2015-12-12     Lekki        Margarita   4000         1  09:09:44
3028  3029  2015-12-05  Surulere         Italiano   3000         5  09:09:45
3029  3030  2015-12-13     Ikoyi   Veggie Supreme   3000         3  09:09:46

      Revenue  Snap
3025     6000  2003
3026    12000  4003
3027     4000  4001
3028    15000  3005
3029     9000  3003
CHUNK BOSS
       S/N        Date  Branch       Pizza Sold  Price  Quantity      Time  \
3030  3031  2015-12-13  Ibadan  Pepperoni Feast   4000         4  09:09:47
3031  3032  2015-12-05   Lekki      BBQ Chicken   4000         5  09:09:48
3032  3033  2015-12-15   Lekki   Veggie Supreme   3000         2  09:09:50
3033  3034  2015-12-12   Ikoyi     Chicken Suya   4000         3  09:09:51
3034  3035  2015-12-06  Ibadan       Hot Veggie   4000         4  09:09:51

      Revenue  Snap
3030    16000  4004
3031    20000  4005
3032     6000  3002
3033    12000  4003
3034    16000  4004
CHUNK BOSS
       S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
3035  3036  2015-12-12  Gbagada     Extravaganza   2000         2  09:09:54
3036  3037  2015-12-03   Ibadan       Hot Veggie   4000         2  09:09:54
3037  3038  2015-12-08  Gbagada      BBQ Chicken   4000         2  09:09:54
3038  3039  2015-12-12    Lekki   Chicken Legend   2000         4  09:09:55
3039  3040  2015-12-08    Ikoyi  Pepperoni Feast   4000         3  09:09:56

      Revenue  Snap
3035     4000  2002
3036     8000  4002
3037     8000  4002
3038     8000  2004
3039    12000  4003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3040  3041  2015-12-05  Surulere       Chicken Legend   2000         3
3041  3042  2015-12-13     Ikoyi         Extravaganza   2000         4
3042  3043  2015-12-12   Gbagada         Chicken Suya   4000         5
3043  3044  2015-12-12  Surulere         Extravaganza   2000         5
3044  3045  2015-12-13    Ibadan  Hot Pepperoni Feast   4000         5

          Time  Revenue  Snap
3040  09:09:57     6000  2003
3041  09:09:57     8000  2004
3042  09:09:57    20000  4005
3043  09:10:01    10000  2005
3044  09:10:02    20000  4005
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
3045  3046  2015-12-08  Surulere           Meatzaa   2000         1  09:10:02
3046  3047  2015-12-05  Surulere    Pepperoni Suya   3000         4  09:10:03
3047  3048  2015-12-07    Ibadan  BBQ Philly Steak   4000         4  09:10:04
3048  3049  2015-12-03    Ibadan      Chicken Bali   2000         5  09:10:04
3049  3050  2015-12-07     Lekki      Chicken Suya   4000         2  09:10:04

      Revenue  Snap
3045     2000  2001
3046    12000  3004
3047    16000  4004
3048    10000  2005
3049     8000  4002
CHUNK BOSS
       S/N        Date  Branch        Pizza Sold  Price  Quantity      Time  \
3050  3051  2015-12-12   Lekki  BBQ Philly Steak   4000         3  09:10:04
3051  3052  2015-12-15  Ibadan           Meatzaa   2000         3  09:10:05
3052  3053  2015-12-14   Lekki   Pepperoni Feast   4000         5  09:10:07
3053  3054  2015-12-10   Ikoyi         Beef Suya   3000         5  09:10:07
3054  3055  2015-12-09  Ibadan        Hot Veggie   4000         1  09:10:07

      Revenue  Snap
3050    12000  4003
3051     6000  2003
3052    20000  4005
3053    15000  3005
3054     4000  4001
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
3055  3056  2015-12-09   Ibadan      Extravaganza   2000         5  09:10:08
3056  3057  2015-12-10  Gbagada  BBQ Philly Steak   4000         1  09:10:09
3057  3058  2015-12-05  Gbagada      Chicken Suya   4000         4  09:10:11
3058  3059  2015-12-09  Gbagada    Veggie Supreme   3000         1  09:10:11
3059  3060  2015-12-13    Lekki         Beef Suya   3000         5  09:10:12

      Revenue  Snap
3055    10000  2005
3056     4000  4001
3057    16000  4004
3058     3000  3001
3059    15000  3005
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3060  3061  2015-12-08  Surulere       Beef Suya   3000         2  09:10:12
3061  3062  2015-12-04     Ikoyi  Chicken Legend   2000         4  09:10:13
3062  3063  2015-12-08     Ikoyi     BBQ Chicken   4000         2  09:10:13
3063  3064  2015-12-03   Gbagada   Chicken Feast   2000         2  09:10:13
3064  3065  2015-12-09    Ibadan    Extravaganza   2000         5  09:10:15

      Revenue  Snap
3060     6000  3002
3061     8000  2004
3062     8000  4002
3063     4000  2002
3064    10000  2005
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
3065  3066  2015-12-04  Surulere    Pepperoni Suya   3000         4  09:10:17
3066  3067  2015-12-10     Ikoyi  BBQ Philly Steak   4000         3  09:10:18
3067  3068  2015-12-05     Ikoyi       BBQ Chicken   4000         2  09:10:18
3068  3069  2015-12-05   Gbagada    Chicken Legend   2000         5  09:10:19
3069  3070  2015-12-03     Lekki      Extravaganza   2000         2  09:10:21

      Revenue  Snap
3065    12000  3004
3066    12000  4003
3067     8000  4002
3068    10000  2005
3069     4000  2002

CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
3070  3071  2015-12-10  Surulere  Pepperoni Feast   4000         5  09:10:22
3071  3072  2015-12-10  Surulere     Chicken Bali   2000         5  09:10:23
3072  3073  2015-12-06    Ibadan       Hot Veggie   4000         1  09:10:24
3073  3074  2015-12-12     Ikoyi  Pepperoni Feast   4000         5  09:10:24
3074  3075  2015-12-08  Surulere         Italiano   3000         3  09:10:24

      Revenue  Snap
3070    20000  4005
3071    10000  2005
3072     4000  4001
3073    20000  4005
3074     9000  3003
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3075  3076  2015-12-09   Gbagada       Beef Suya   3000         1  09:10:26
3076  3077  2015-12-06  Surulere    Chicken Suya   4000         2  09:10:26
3077  3078  2015-12-04     Lekki       Beef Suya   3000         2  09:10:26
3078  3079  2015-12-07     Ikoyi   Chicken Feast   2000         2  09:10:26
3079  3080  2015-12-11    Ibadan  Veggie Supreme   3000         3  09:10:27

      Revenue  Snap
3075     3000  3001
3076     8000  4002
3077     6000  3002
3078     4000  2002
3079     9000  3003
CHUNK BOSS
       S/N        Date  Branch      Pizza Sold  Price  Quantity      Time  \
3080  3081  2015-12-13   Ikoyi      Hot Veggie   4000         5  09:10:27
3081  3082  2015-12-09   Ikoyi  Pepperoni Suya   3000         2  09:10:28
3082  3083  2015-12-11  Ibadan      Hot Veggie   4000         5  09:10:29
3083  3084  2015-12-15  Ibadan    Chicken Bali   2000         2  09:10:29
3084  3085  2015-12-13   Ikoyi       Margarita   4000         1  09:10:30

      Revenue  Snap
3080    20000  4005
3081     6000  3002
3082    20000  4005
3083     4000  2002
3084     4000  4001
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
3085  3086  2015-12-11  Surulere        Beef Suya   3000         1  09:10:30
3086  3087  2015-12-04   Gbagada  Pepperoni Feast   4000         1  09:10:30
3087  3088  2015-12-14     Lekki  Pepperoni Feast   4000         5  09:10:30
3088  3089  2015-12-05  Surulere        Margarita   4000         4  09:10:31
3089  3090  2015-12-14     Lekki  Pepperoni Feast   4000         1  09:10:32

      Revenue  Snap
3085     3000  3001
3086     4000  4001
3087    20000  4005
3088    16000  4004
3089     4000  4001
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
3090  3091  2015-12-14  Gbagada  BBQ Philly Steak   4000         4  09:10:35
3091  3092  2015-12-07  Gbagada          Italiano   3000         4  09:10:37
3092  3093  2015-12-08   Ibadan   Pepperoni Feast   4000         1  09:10:38
3093  3094  2015-12-10  Gbagada     Chicken Feast   2000         4  09:10:40
3094  3095  2015-12-06    Ikoyi   Pepperoni Feast   4000         3  09:10:40

      Revenue  Snap
3090    16000  4004
3091    12000  3004
3092     4000  4001
3093     8000  2004
3094    12000  4003
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
3095  3096  2015-12-06  Gbagada     BBQ Philly Steak   4000         4
3096  3097  2015-12-10  Gbagada             Italiano   3000         4
3097  3098  2015-12-07   Ibadan  Hot Pepperoni Feast   4000         4
3098  3099  2015-12-03  Gbagada            Beef Suya   3000         5
3099  3100  2015-12-08   Ibadan         Chicken Bali   2000         4

          Time  Revenue  Snap
3095  09:10:40    16000  4004
3096  09:10:41    12000  3004
3097  09:10:42    16000  4004
3098  09:10:43    15000  3005
3099  09:10:43     8000  2004
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
3100  3101  2015-12-05  Surulere    Veggie Supreme   3000         2  09:10:44
3101  3102  2015-12-15  Surulere    Chicken Legend   2000         4  09:10:45
3102  3103  2015-12-11    Ibadan    Pepperoni Suya   3000         3  09:10:46
3103  3104  2015-12-10  Surulere           Meatzaa   2000         4  09:10:47
3104  3105  2015-12-09   Gbagada  BBQ Philly Steak   4000         4  09:10:48

      Revenue  Snap
3100     6000  3002
3101     8000  2004
3102     9000  3003
3103     8000  2004
3104    16000  4004
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3105  3106  2015-12-05    Ibadan  Hot Pepperoni Feast   4000         5
3106  3107  2015-12-14   Gbagada            Beef Suya   3000         2
3107  3108  2015-12-07     Ikoyi      Pepperoni Feast   4000         2
3108  3109  2015-12-12  Surulere              Meatzaa   2000         1
3109  3110  2015-12-07   Gbagada       Pepperoni Suya   3000         3

          Time  Revenue  Snap
3105  09:10:51    20000  4005
3106  09:10:51     6000  3002
3107  09:10:51     8000  4002
3108  09:10:54     2000  2001
3109  09:10:54     9000  3003
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3110  3111  2015-12-05   Gbagada  Veggie Supreme   3000         4  09:10:55
3111  3112  2015-12-12     Ikoyi         Meatzaa   2000         1  09:10:56
3112  3113  2015-12-10    Ibadan     BBQ Chicken   4000         2  09:10:56
3113  3114  2015-12-13  Surulere    Chicken Suya   4000         1  09:10:57
3114  3115  2015-12-08     Ikoyi      Hot Veggie   4000         5  09:10:59

      Revenue  Snap
3110    12000  3004
3111     2000  2001
3112     8000  4002
3113     4000  4001
3114    20000  4005
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3115  3116  2015-12-08     Lekki    Extravaganza   2000         5  09:10:59
3116  3117  2015-12-11     Lekki  Chicken Legend   2000         1  09:11:00
3117  3118  2015-12-14  Surulere      Hot Veggie   4000         2  09:11:00
3118  3119  2015-12-06     Ikoyi       Beef Suya   3000         4  09:11:01
3119  3120  2015-12-05   Gbagada     BBQ Chicken   4000         3  09:11:05

      Revenue  Snap
3115    10000  2005
3116     2000  2001
3117     8000  4002
3118    12000  3004
3119    12000  4003
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
3120  3121  2015-12-03   Ibadan  Hot Pepperoni Feast   4000         5
3121  3122  2015-12-12   Ibadan             Italiano   3000         1
3122  3123  2015-12-09   Ibadan       Veggie Supreme   3000         5
3123  3124  2015-12-09  Gbagada          BBQ Chicken   4000         3
3124  3125  2015-12-08    Ikoyi            Beef Suya   3000         1

          Time  Revenue  Snap
3120  09:11:07    20000  4005
3121  09:11:10     3000  3001
3122  09:11:10    15000  3005
3123  09:11:12    12000  4003
3124  09:11:14     3000  3001
CHUNK BOSS
       S/N        Date Branch        Pizza Sold  Price  Quantity      Time  \
3125  3126  2015-12-03  Lekki     Chicken Feast   2000         2  09:11:15
3126  3127  2015-12-12  Ikoyi  BBQ Philly Steak   4000         1  09:11:15
3127  3128  2015-12-13  Lekki  BBQ Philly Steak   4000         2  09:11:16
3128  3129  2015-12-14  Ikoyi           Meatzaa   2000         3  09:11:18
3129  3130  2015-12-15  Lekki      Extravaganza   2000         1  09:11:18

      Revenue  Snap
3125     4000  2002
3126     4000  4001
3127     8000  4002
3128     6000  2003
3129     2000  2001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3130  3131  2015-12-12    Ibadan      Hot Veggie   4000         5  09:11:19
3131  3132  2015-12-11    Ibadan    Chicken Suya   4000         5  09:11:19
3132  3133  2015-12-05   Gbagada    Extravaganza   2000         5  09:11:19
3133  3134  2015-12-06  Surulere    Extravaganza   2000         5  09:11:20
3134  3135  2015-12-15     Ikoyi  Pepperoni Suya   3000         5  09:11:22

      Revenue  Snap
3130    20000  4005
3131    20000  4005
3132    10000  2005
3133    10000  2005
3134    15000  3005
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
3135  3136  2015-12-09    Ikoyi            Margarita   4000         1
3136  3137  2015-12-08    Ikoyi           Hot Veggie   4000         1
3137  3138  2015-12-14    Lekki       Pepperoni Suya   3000         2
3138  3139  2015-12-08    Ikoyi       Pepperoni Suya   3000         3
3139  3140  2015-12-05  Gbagada  Hot Pepperoni Feast   4000         2

          Time  Revenue  Snap
3135  09:11:22     4000  4001
3136  09:11:22     4000  4001
3137  09:11:22     6000  3002
3138  09:11:24     9000  3003
3139  09:11:25     8000  4002
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
3140  3141  2015-12-08     Lekki      Chicken Bali   2000         1  09:11:25
3141  3142  2015-12-07  Surulere         Margarita   4000         3  09:11:25
3142  3143  2015-12-07   Gbagada      Extravaganza   2000         5  09:11:29
3143  3144  2015-12-03     Ikoyi  BBQ Philly Steak   4000         3  09:11:32
3144  3145  2015-12-03    Ibadan      Chicken Suya   4000         5  09:11:32

      Revenue  Snap
3140     2000  2001
3141    12000  4003
3142    10000  2005
3143    12000  4003
3144    20000  4005
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3145  3146  2015-12-03  Surulere  Chicken Legend   2000         2  09:11:32
3146  3147  2015-12-14     Lekki  Veggie Supreme   3000         2  09:11:33
3147  3148  2015-12-14    Ibadan       Beef Suya   3000         1  09:11:33
3148  3149  2015-12-07   Gbagada       Margarita   4000         1  09:11:34
3149  3150  2015-12-10   Gbagada   Chicken Feast   2000         2  09:11:34

      Revenue  Snap
3145     4000  2002
3146     6000  3002
3147     3000  3001
3148     4000  4001
3149     4000  2002
CHUNK BOSS
       S/N        Date   Branch     Pizza Sold  Price  Quantity      Time  \
3150  3151  2015-12-14   Ibadan        Meatzaa   2000         3  09:11:35
3151  3152  2015-12-11    Ikoyi      Margarita   4000         1  09:11:35
3152  3153  2015-12-15  Gbagada   Extravaganza   2000         2  09:11:35
3153  3154  2015-12-05   Ibadan  Chicken Feast   2000         2  09:11:37
3154  3155  2015-12-08  Gbagada   Chicken Suya   4000         5  09:11:39

      Revenue  Snap
3150     6000  2003
3151     4000  4001
3152     4000  2002
3153     4000  2002
3154    20000  4005
CHUNK BOSS
       S/N        Date  Branch        Pizza Sold  Price  Quantity      Time  \
3155  3156  2015-12-08   Lekki         Margarita   4000         3  09:11:39
3156  3157  2015-12-13   Lekki         Beef Suya   3000         4  09:11:40
3157  3158  2015-12-12  Ibadan  BBQ Philly Steak   4000         1  09:11:41
3158  3159  2015-12-13  Ibadan     Chicken Feast   2000         1  09:11:41
3159  3160  2015-12-14  Ibadan  BBQ Philly Steak   4000         5  09:11:42

      Revenue  Snap
3155    12000  4003
3156    12000  3004
3157     4000  4001
3158     2000  2001
3159    20000  4005
CHUNK BOSS

       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3160  3161  2015-12-03    Ibadan  Hot Pepperoni Feast   4000         3
3161  3162  2015-12-04     Ikoyi       Pepperoni Suya   3000         3
3162  3163  2015-12-13     Lekki       Pepperoni Suya   3000         3
3163  3164  2015-12-13  Surulere         Extravaganza   2000         1
3164  3165  2015-12-07     Ikoyi              Meatzaa   2000         2

          Time  Revenue  Snap
3160  09:11:42    12000  4003
3161  09:11:43     9000  3003
3162  09:11:45     9000  3003
3163  09:11:45     2000  2001
3164  09:11:45     4000  2002
CHUNK BOSS
       S/N        Date Branch       Pizza Sold  Price  Quantity      Time  \
3165  3166  2015-12-11  Ikoyi   Pepperoni Suya   3000         1  09:11:46
3166  3167  2015-12-12  Ikoyi       Hot Veggie   4000         1  09:11:47
3167  3168  2015-12-05  Lekki  Pepperoni Feast   4000         4  09:11:48
3168  3169  2015-12-07  Lekki         Italiano   3000         1  09:11:49
3169  3170  2015-12-13  Lekki   Pepperoni Suya   3000         3  09:11:49

      Revenue  Snap
3165     3000  3001
3166     4000  4001
3167    16000  4004
3168     3000  3001
3169     9000  3003
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
3170  3171  2015-12-11    Ikoyi    Chicken Suya   4000         3  09:11:51
3171  3172  2015-12-05   Ibadan        Italiano   3000         2  09:11:51
3172  3173  2015-12-04  Gbagada  Chicken Legend   2000         2  09:11:53
3173  3174  2015-12-11   Ibadan   Chicken Feast   2000         1  09:11:56
3174  3175  2015-12-09    Ikoyi  Pepperoni Suya   3000         2  09:11:56

      Revenue  Snap
3170    12000  4003
3171     6000  3002
3172     4000  2002
3173     2000  2001
3174     6000  3002
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
3175  3176  2015-12-04     Lekki       Hot Veggie   4000         5  09:11:56
3176  3177  2015-12-09   Gbagada          Meatzaa   2000         5  09:11:58
3177  3178  2015-12-14  Surulere        Margarita   4000         4  09:12:00
3178  3179  2015-12-03     Lekki        Margarita   4000         5  09:12:01
3179  3180  2015-12-04    Ibadan  Pepperoni Feast   4000         1  09:12:02

      Revenue  Snap
3175    20000  4005
3176    10000  2005
3177    16000  4004
3178    20000  4005
3179     4000  4001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3180  3181  2015-12-10     Ikoyi    Extravaganza   2000         5  09:12:02
3181  3182  2015-12-06   Gbagada         Meatzaa   2000         3  09:12:03
3182  3183  2015-12-03     Ikoyi     BBQ Chicken   4000         4  09:12:03
3183  3184  2015-12-13  Surulere       Margarita   4000         2  09:12:04
3184  3185  2015-12-03  Surulere  Pepperoni Suya   3000         5  09:12:06

      Revenue  Snap
3180    10000  2005
3181     6000  2003
3182    16000  4004
3183     8000  4002
3184    15000  3005
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
3185  3186  2015-12-12    Ikoyi     BBQ Chicken   4000         3  09:12:08
3186  3187  2015-12-04  Gbagada  Chicken Legend   2000         4  09:12:09
3187  3188  2015-12-14   Ibadan      Hot Veggie   4000         1  09:12:09
3188  3189  2015-12-05  Gbagada       Beef Suya   3000         5  09:12:11
3189  3190  2015-12-08   Ibadan    Chicken Bali   2000         1  09:12:11

      Revenue  Snap
3185    12000  4003
3186     8000  2004
3187     4000  4001
3188    15000  3005
3189     2000  2001
CHUNK BOSS
       S/N        Date    Branch     Pizza Sold  Price  Quantity      Time  \
3190  3191  2015-12-09  Surulere   Chicken Bali   2000         2  09:12:13
3191  3192  2015-12-05    Ibadan   Chicken Bali   2000         5  09:12:18
3192  3193  2015-12-13     Lekki   Chicken Suya   4000         4  09:12:18
3193  3194  2015-12-08    Ibadan      Beef Suya   3000         1  09:12:18
3194  3195  2015-12-07    Ibadan  Chicken Feast   2000         3  09:12:18

      Revenue  Snap
3190     4000  2002
3191    10000  2005
3192    16000  4004
3193     3000  3001
3194     6000  2003
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
3195  3196  2015-12-04     Ikoyi  Pepperoni Feast   4000         1  09:12:19
3196  3197  2015-12-08     Lekki   Veggie Supreme   3000         3  09:12:20
3197  3198  2015-12-04   Gbagada         Italiano   3000         5  09:12:21
3198  3199  2015-12-06   Gbagada   Veggie Supreme   3000         1  09:12:21
3199  3200  2015-12-03  Surulere   Chicken Legend   2000         5  09:12:22

      Revenue  Snap
3195     4000  4001
3196     9000  3003
3197    15000  3005
3198     3000  3001
3199    10000  2005
CHUNK BOSS
       S/N        Date    Branch    Pizza Sold  Price  Quantity      Time  \
3200  3201  2015-12-13     Lekki      Italiano   3000         3  09:12:23
3201  3202  2015-12-07    Ibadan      Italiano   3000         2  09:12:24
3202  3203  2015-12-07  Surulere     Beef Suya   3000         5  09:12:25
3203  3204  2015-12-09     Ikoyi  Extravaganza   2000         2  09:12:25
3204  3205  2015-12-03     Ikoyi     Beef Suya   3000         5  09:12:26

      Revenue  Snap
3200     9000  3003
3201     6000  3002
3202    15000  3005
3203     4000  2002
3204    15000  3005
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3205  3206  2015-12-11     Ikoyi    Extravaganza   2000         4  09:12:28
3206  3207  2015-12-10     Lekki        Italiano   3000         2  09:12:29
3207  3208  2015-12-03  Surulere        Italiano   3000         3  09:12:30
3208  3209  2015-12-04     Ikoyi  Veggie Supreme   3000         3  09:12:31
3209  3210  2015-12-13     Lekki  Veggie Supreme   3000         1  09:12:31

      Revenue  Snap
3205     8000  2004
3206     6000  3002
3207     9000  3003
3208     9000  3003
3209     3000  3001
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
3210  3211  2015-12-10     Ikoyi  Pepperoni Feast   4000         3  09:12:32
3211  3212  2015-12-05   Gbagada       Hot Veggie   4000         3  09:12:33
3212  3213  2015-12-06     Lekki   Veggie Supreme   3000         5  09:12:35
3213  3214  2015-12-05  Surulere         Italiano   3000         2  09:12:35
3214  3215  2015-12-12     Ikoyi         Italiano   3000         1  09:12:36

      Revenue  Snap
3210    12000  4003
3211    12000  4003
3212    15000  3005
3213     6000  3002
3214     3000  3001
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3215  3216  2015-12-14    Ibadan       Veggie Supreme   3000         1
3216  3217  2015-12-08     Lekki  Hot Pepperoni Feast   4000         2
3217  3218  2015-12-11     Ikoyi  Hot Pepperoni Feast   4000         2
3218  3219  2015-12-05  Surulere      Pepperoni Feast   4000         2
3219  3220  2015-12-11    Ibadan       Veggie Supreme   3000         3

          Time  Revenue  Snap
3215  09:12:39     3000  3001
3216  09:12:40     8000  4002
3217  09:12:41     8000  4002
3218  09:12:45     8000  4002
3219  09:12:47     9000  3003
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
3220  3221  2015-12-07  Gbagada  Pepperoni Suya   3000         1  09:12:49
3221  3222  2015-12-07    Ikoyi  Pepperoni Suya   3000         3  09:12:50
3222  3223  2015-12-05    Lekki        Italiano   3000         4  09:12:51
3223  3224  2015-12-09    Lekki  Chicken Legend   2000         4  09:12:52
3224  3225  2015-12-15  Gbagada    Chicken Suya   4000         2  09:12:53

      Revenue  Snap
3220     3000  3001
3221     9000  3003
3222    12000  3004
3223     8000  2004
3224     8000  4002
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3225  3226  2015-12-12  Surulere  Pepperoni Suya   3000         5  09:12:53
3226  3227  2015-12-05    Ibadan  Chicken Legend   2000         3  09:12:54
3227  3228  2015-12-05     Lekki         Meatzaa   2000         2  09:12:55
3228  3229  2015-12-14    Ibadan    Chicken Suya   4000         1  09:12:55
3229  3230  2015-12-09     Lekki    Extravaganza   2000         4  09:12:56

      Revenue  Snap
3225    15000  3005
3226     6000  2003
3227     4000  2002
3228     4000  4001
3229     8000  2004
CHUNK BOSS
       S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
3230  3231  2015-12-14    Lekki      BBQ Chicken   4000         4  09:12:57
3231  3232  2015-12-04   Ibadan    Chicken Feast   2000         4  09:12:57
3232  3233  2015-12-14   Ibadan  Pepperoni Feast   4000         1  09:12:57
3233  3234  2015-12-03   Ibadan     Chicken Bali   2000         3  09:13:00
3234  3235  2015-12-08  Gbagada    Chicken Feast   2000         1  09:13:01

      Revenue  Snap
3230    16000  4004
3231     8000  2004
3232     4000  4001
3233     6000  2003
3234     2000  2001
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
3235  3236  2015-12-05    Lekki  Pepperoni Suya   3000         2  09:13:04
3236  3237  2015-12-13  Gbagada    Chicken Suya   4000         1  09:13:04
3237  3238  2015-12-06    Ikoyi       Margarita   4000         2  09:13:05
3238  3239  2015-12-14  Gbagada  Pepperoni Suya   3000         5  09:13:05
3239  3240  2015-12-06    Ikoyi        Italiano   3000         5  09:13:06

      Revenue  Snap
3235     6000  3002
3236     4000  4001
3237     8000  4002
3238    15000  3005
3239    15000  3005
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3240  3241  2015-12-05   Gbagada     BBQ Chicken   4000         5  09:13:07
3241  3242  2015-12-14  Surulere    Chicken Bali   2000         4  09:13:10
3242  3243  2015-12-04   Gbagada  Veggie Supreme   3000         3  09:13:10
3243  3244  2015-12-06  Surulere    Extravaganza   2000         3  09:13:10
3244  3245  2015-12-09     Lekki    Extravaganza   2000         4  09:13:11

      Revenue  Snap
3240    20000  4005
3241     8000  2004
3242     9000  3003
3243     6000  2003
3244     8000  2004
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3245  3246  2015-12-11   Gbagada       Pepperoni Suya   3000         1
3246  3247  2015-12-04     Ikoyi  Hot Pepperoni Feast   4000         2
3247  3248  2015-12-13   Gbagada         Chicken Suya   4000         4
3248  3249  2015-12-07   Gbagada            Margarita   4000         4
3249  3250  2015-12-12  Surulere            Beef Suya   3000         4

          Time  Revenue  Snap
3245  09:13:11     3000  3001
3246  09:13:14     8000  4002
3247  09:13:15    16000  4004
3248  09:13:15    16000  4004
3249  09:13:15    12000  3004
CHUNK BOSS
       S/N        Date  Branch        Pizza Sold  Price  Quantity      Time  \
3250  3251  2015-12-04   Lekki      Extravaganza   2000         2  09:13:15
3251  3252  2015-12-06   Ikoyi    Pepperoni Suya   3000         5  09:13:16
3252  3253  2015-12-09   Lekki  BBQ Philly Steak   4000         5  09:13:18
3253  3254  2015-12-08   Ikoyi    Pepperoni Suya   3000         2  09:13:20
3254  3255  2015-12-13  Ibadan      Chicken Suya   4000         1  09:13:20

      Revenue  Snap
3250     4000  2002
3251    15000  3005
3252    20000  4005
3253     6000  3002
3254     4000  4001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3255  3256  2015-12-08   Gbagada      Hot Veggie   4000         4  09:13:21
3256  3257  2015-12-15  Surulere  Pepperoni Suya   3000         2  09:13:22
3257  3258  2015-12-10   Gbagada      Hot Veggie   4000         3  09:13:22
3258  3259  2015-12-12  Surulere    Chicken Suya   4000         3  09:13:23
3259  3260  2015-12-10   Gbagada      Hot Veggie   4000         1  09:13:23

      Revenue  Snap
3255    16000  4004
3256     6000  3002
3257    12000  4003
3258    12000  4003
3259     4000  4001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3260  3261  2015-12-10  Surulere  Chicken Legend   2000         4  09:13:25
3261  3262  2015-12-11     Ikoyi   Chicken Feast   2000         5  09:13:25
3262  3263  2015-12-08   Gbagada         Meatzaa   2000         4  09:13:27
3263  3264  2015-12-08    Ibadan       Beef Suya   3000         5  09:13:28
3264  3265  2015-12-05     Ikoyi      Hot Veggie   4000         1  09:13:28

      Revenue  Snap
3260     8000  2004
3261    10000  2005
3262     8000  2004
3263    15000  3005
3264     4000  4001

CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
3265  3266  2015-12-07     Ikoyi  BBQ Philly Steak   4000         2  09:13:28
3266  3267  2015-12-06     Ikoyi       BBQ Chicken   4000         5  09:13:30
3267  3268  2015-12-08    Ibadan      Chicken Bali   2000         4  09:13:31
3268  3269  2015-12-13  Surulere    Chicken Legend   2000         1  09:13:31
3269  3270  2015-12-11     Ikoyi   Pepperoni Feast   4000         1  09:13:31

      Revenue  Snap
3265     8000  4002
3266    20000  4005
3267     8000  2004
3268     2000  2001
3269     4000  4001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3270  3271  2015-12-04  Surulere   Chicken Feast   2000         4  09:13:32
3271  3272  2015-12-04     Ikoyi  Pepperoni Suya   3000         1  09:13:32
3272  3273  2015-12-03    Ibadan    Chicken Bali   2000         1  09:13:36
3273  3274  2015-12-11   Gbagada       Beef Suya   3000         4  09:13:36
3274  3275  2015-12-05    Ibadan        Italiano   3000         5  09:13:36

      Revenue  Snap
3270     8000  2004
3271     3000  3001
3272     2000  2001
3273    12000  3004
3274    15000  3005
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3275  3276  2015-12-04    Ibadan    Chicken Suya   4000         2  09:13:36
3276  3277  2015-12-05  Surulere    Chicken Suya   4000         5  09:13:37
3277  3278  2015-12-12     Lekki      Hot Veggie   4000         4  09:13:37
3278  3279  2015-12-06    Ibadan  Pepperoni Suya   3000         5  09:13:39
3279  3280  2015-12-14     Ikoyi         Meatzaa   2000         5  09:13:39

      Revenue  Snap
3275     8000  4002
3276    20000  4005
3277    16000  4004
3278    15000  3005
3279    10000  2005
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3280  3281  2015-12-15  Surulere         Meatzaa   2000         3  09:13:41
3281  3282  2015-12-07    Ibadan    Chicken Bali   2000         3  09:13:41
3282  3283  2015-12-05  Surulere        Italiano   3000         4  09:13:43
3283  3284  2015-12-09     Ikoyi  Veggie Supreme   3000         1  09:13:45
3284  3285  2015-12-06  Surulere   Chicken Feast   2000         4  09:13:46

      Revenue  Snap
3280     6000  2003
3281     6000  2003
3282    12000  3004
3283     3000  3001
3284     8000  2004
CHUNK BOSS
       S/N        Date    Branch     Pizza Sold  Price  Quantity      Time  \
3285  3286  2015-12-05    Ibadan  Chicken Feast   2000         3  09:13:47
3286  3287  2015-12-13     Ikoyi   Chicken Bali   2000         3  09:13:48
3287  3288  2015-12-08     Lekki      Beef Suya   3000         2  09:13:51
3288  3289  2015-12-04   Gbagada   Extravaganza   2000         5  09:13:52
3289  3290  2015-12-05  Surulere   Chicken Bali   2000         5  09:13:52

      Revenue  Snap
3285     6000  2003
3286     6000  2003
3287     6000  3002
3288    10000  2005
3289    10000  2005
CHUNK BOSS
       S/N        Date Branch      Pizza Sold  Price  Quantity      Time  \
3290  3291  2015-12-06  Ikoyi       Margarita   4000         5  09:13:54
3291  3292  2015-12-08  Ikoyi  Chicken Legend   2000         3  09:13:54
3292  3293  2015-12-12  Lekki  Veggie Supreme   3000         3  09:13:55
3293  3294  2015-12-09  Ikoyi  Veggie Supreme   3000         5  09:13:56
3294  3295  2015-12-11  Lekki  Veggie Supreme   3000         5  09:13:56

      Revenue  Snap
3290    20000  4005
3291     6000  2003
3292     9000  3003
3293    15000  3005
3294    15000  3005
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
3295  3296  2015-12-06   Ibadan  Hot Pepperoni Feast   4000         3
3296  3297  2015-12-06    Lekki            Margarita   4000         3
3297  3298  2015-12-12  Gbagada         Chicken Bali   2000         5
3298  3299  2015-12-03    Ikoyi        Chicken Feast   2000         5
3299  3300  2015-12-09  Gbagada         Chicken Bali   2000         1

          Time  Revenue  Snap
3295  09:13:57    12000  4003
3296  09:13:58    12000  4003
3297  09:13:59    10000  2005
3298  09:13:59    10000  2005
3299  09:14:00     2000  2001
CHUNK BOSS
       S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
3300  3301  2015-12-11  Gbagada        Margarita   4000         2  09:14:00
3301  3302  2015-12-07    Ikoyi    Chicken Feast   2000         5  09:14:01
3302  3303  2015-12-05  Gbagada  Pepperoni Feast   4000         1  09:14:03
3303  3304  2015-12-05    Lekki       Hot Veggie   4000         5  09:14:03
3304  3305  2015-12-04  Gbagada   Chicken Legend   2000         1  09:14:04

      Revenue  Snap
3300     8000  4002
3301    10000  2005
3302     4000  4001
3303    20000  4005
3304     2000  2001
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
3305  3306  2015-12-07     Ikoyi    Pepperoni Suya   3000         1  09:14:06
3306  3307  2015-12-03    Ibadan    Chicken Legend   2000         1  09:14:07
3307  3308  2015-12-07     Lekki      Chicken Bali   2000         3  09:14:08
3308  3309  2015-12-08  Surulere  BBQ Philly Steak   4000         4  09:14:08
3309  3310  2015-12-13  Surulere          Italiano   3000         2  09:14:09

      Revenue  Snap
3305     3000  3001
3306     2000  2001
3307     6000  2003
3308    16000  4004
3309     6000  3002
CHUNK BOSS
       S/N        Date  Branch        Pizza Sold  Price  Quantity      Time  \
3310  3311  2015-12-11  Ibadan    Veggie Supreme   3000         5  09:14:10
3311  3312  2015-12-06   Ikoyi  BBQ Philly Steak   4000         5  09:14:10
3312  3313  2015-12-13   Ikoyi     Chicken Feast   2000         3  09:14:12
3313  3314  2015-12-11   Lekki         Margarita   4000         4  09:14:16
3314  3315  2015-12-04   Ikoyi      Chicken Bali   2000         1  09:14:18

      Revenue  Snap
3310    15000  3005
3311    20000  4005
3312     6000  2003
3313    16000  4004
3314     2000  2001
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
3315  3316  2015-12-12    Ibadan        Beef Suya   3000         4  09:14:23
3316  3317  2015-12-09   Gbagada         Italiano   3000         1  09:14:23
3317  3318  2015-12-03   Gbagada  Pepperoni Feast   4000         5  09:14:24
3318  3319  2015-12-07  Surulere         Italiano   3000         5  09:14:25
3319  3320  2015-12-14     Lekki  Pepperoni Feast   4000         5  09:14:25

      Revenue  Snap
3315    12000  3004
3316     3000  3001
3317    20000  4005
3318    15000  3005
3319    20000  4005
CHUNK BOSS
       S/N        Date    Branch     Pizza Sold  Price  Quantity      Time  \
3320  3321  2015-12-04    Ibadan  Chicken Feast   2000         1  09:14:26
3321  3322  2015-12-15     Lekki   Extravaganza   2000         3  09:14:26
3322  3323  2015-12-13  Surulere   Chicken Bali   2000         1  09:14:27
3323  3324  2015-12-09     Ikoyi   Extravaganza   2000         1  09:14:27
3324  3325  2015-12-05     Ikoyi        Meatzaa   2000         4  09:14:29

      Revenue  Snap
3320     2000  2001
3321     6000  2003
3322     2000  2001
3323     2000  2001
3324     8000  2004
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3325  3326  2015-12-12  Surulere           Hot Veggie   4000         1
3326  3327  2015-12-03     Lekki         Chicken Suya   4000         2
3327  3328  2015-12-05     Ikoyi            Beef Suya   3000         4
3328  3329  2015-12-15   Gbagada  Hot Pepperoni Feast   4000         2
3329  3330  2015-12-10  Surulere           Hot Veggie   4000         1

          Time  Revenue  Snap
3325  09:14:30     4000  4001
3326  09:14:31     8000  4002
3327  09:14:32    12000  3004
3328  09:14:32     8000  4002
3329  09:14:32     4000  4001
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3330  3331  2015-12-13  Surulere          BBQ Chicken   4000         4
3331  3332  2015-12-12    Ibadan            Margarita   4000         4
3332  3333  2015-12-14  Surulere  Hot Pepperoni Feast   4000         1
3333  3334  2015-12-04     Ikoyi           Hot Veggie   4000         1
3334  3335  2015-12-14     Ikoyi             Italiano   3000         4

          Time  Revenue  Snap
3330  09:14:32    16000  4004
3331  09:14:33    16000  4004
3332  09:14:37     4000  4001
3333  09:14:38     4000  4001
3334  09:14:43    12000  3004
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
3335  3336  2015-12-12     Lekki         Margarita   4000         1  09:14:43
3336  3337  2015-12-06  Surulere         Beef Suya   3000         5  09:14:43
3337  3338  2015-12-07   Gbagada  BBQ Philly Steak   4000         4  09:14:44
3338  3339  2015-12-08  Surulere   Pepperoni Feast   4000         2  09:14:50
3339  3340  2015-12-04   Gbagada    Veggie Supreme   3000         1  09:14:51

      Revenue  Snap
3335     4000  4001
3336    15000  3005
3337    16000  4004
3338     8000  4002
3339     3000  3001
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
3340  3341  2015-12-06  Gbagada  Veggie Supreme   3000         2  09:14:51
3341  3342  2015-12-10  Gbagada     BBQ Chicken   4000         3  09:14:51
3342  3343  2015-12-04    Lekki  Chicken Legend   2000         3  09:14:51
3343  3344  2015-12-13    Lekki    Chicken Bali   2000         4  09:14:53
3344  3345  2015-12-06   Ibadan    Chicken Bali   2000         3  09:14:54

      Revenue  Snap
3340     6000  3002
3341    12000  4003
3342     6000  2003
3343     8000  2004
3344     6000  2003
CHUNK BOSS
       S/N        Date    Branch     Pizza Sold  Price  Quantity      Time  \
3345  3346  2015-12-04  Surulere   Extravaganza   2000         1  09:14:55
3346  3347  2015-12-14   Gbagada      Margarita   4000         4  09:14:56
3347  3348  2015-12-10   Gbagada  Chicken Feast   2000         4  09:14:57
3348  3349  2015-12-04     Lekki     Hot Veggie   4000         5  09:14:59
3349  3350  2015-12-10    Ibadan        Meatzaa   2000         2  09:15:00

      Revenue  Snap
3345     2000  2001
3346    16000  4004
3347     8000  2004
3348    20000  4005
3349     4000  2002
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
3350  3351  2015-12-11  Surulere         Beef Suya   3000         3  09:15:00
3351  3352  2015-12-09     Lekki      Chicken Bali   2000         2  09:15:02
3352  3353  2015-12-12     Lekki  BBQ Philly Steak   4000         1  09:15:03
3353  3354  2015-12-15  Surulere      Extravaganza   2000         5  09:15:03
3354  3355  2015-12-10     Lekki         Beef Suya   3000         5  09:15:05

      Revenue  Snap
3350     9000  3003
3351     4000  2002
3352     4000  4001
3353    10000  2005
3354    15000  3005
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
3355  3356  2015-12-15     Ikoyi        Hot Veggie   4000         4  09:15:06
3356  3357  2015-12-07   Gbagada    Chicken Legend   2000         3  09:15:09
3357  3358  2015-12-05     Lekki      Chicken Bali   2000         1  09:15:11
3358  3359  2015-12-07    Ibadan  BBQ Philly Steak   4000         3  09:15:12
3359  3360  2015-12-09  Surulere         Beef Suya   3000         4  09:15:13

      Revenue  Snap
3355    16000  4004
3356     6000  2003
3357     2000  2001
3358    12000  4003
3359    12000  3004
CHUNK BOSS

       S/N        Date    Branch    Pizza Sold  Price  Quantity      Time  \
3360  3361  2015-12-09  Surulere     Beef Suya   3000         4  09:15:13
3361  3362  2015-12-04     Lekki   BBQ Chicken   4000         5  09:15:18
3362  3363  2015-12-07     Ikoyi  Chicken Bali   2000         4  09:15:18
3363  3364  2015-12-06    Ibadan       Meatzaa   2000         3  09:15:20
3364  3365  2015-12-13     Ikoyi     Margarita   4000         4  09:15:20

      Revenue  Snap
3360    12000  3004
3361    20000  4005
3362     8000  2004
3363     6000  2003
3364    16000  4004
CHUNK BOSS
       S/N        Date    Branch     Pizza Sold  Price  Quantity      Time  \
3365  3366  2015-12-08  Surulere  Chicken Feast   2000         1  09:15:20
3366  3367  2015-12-06     Ikoyi   Chicken Bali   2000         2  09:15:22
3367  3368  2015-12-05     Ikoyi    BBQ Chicken   4000         3  09:15:23
3368  3369  2015-12-14   Gbagada        Meatzaa   2000         1  09:15:23
3369  3370  2015-12-09  Surulere   Extravaganza   2000         4  09:15:23

      Revenue  Snap
3365     2000  2001
3366     4000  2002
3367    12000  4003
3368     2000  2001
3369     8000  2004
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3370  3371  2015-12-07   Gbagada            Margarita   4000         5
3371  3372  2015-12-03  Surulere        Chicken Feast   2000         2
3372  3373  2015-12-06  Surulere       Veggie Supreme   3000         1
3373  3374  2015-12-15     Ikoyi             Italiano   3000         2
3374  3375  2015-12-07    Ibadan  Hot Pepperoni Feast   4000         4

          Time  Revenue  Snap
3370  09:15:25    20000  4005
3371  09:15:25     4000  2002
3372  09:15:25     3000  3001
3373  09:15:30     6000  3002
3374  09:15:30    16000  4004
CHUNK BOSS
       S/N        Date  Branch       Pizza Sold  Price  Quantity      Time  \
3375  3376  2015-12-11   Ikoyi   Pepperoni Suya   3000         4  09:15:30
3376  3377  2015-12-04  Ibadan       Hot Veggie   4000         2  09:15:33
3377  3378  2015-12-10  Ibadan  Pepperoni Feast   4000         1  09:15:36
3378  3379  2015-12-10   Ikoyi    Chicken Feast   2000         2  09:15:37
3379  3380  2015-12-03   Lekki    Chicken Feast   2000         3  09:15:37

      Revenue  Snap
3375    12000  3004
3376     8000  4002
3377     4000  4001
3378     4000  2002
3379     6000  2003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3380  3381  2015-12-03   Gbagada       Veggie Supreme   3000         2
3381  3382  2015-12-15  Surulere            Beef Suya   3000         4
3382  3383  2015-12-11     Lekki         Chicken Suya   4000         2
3383  3384  2015-12-07  Surulere  Hot Pepperoni Feast   4000         1
3384  3385  2015-12-15  Surulere             Italiano   3000         5

          Time  Revenue  Snap
3380  09:15:38     6000  3002
3381  09:15:38    12000  3004
3382  09:15:39     8000  4002
3383  09:15:40     4000  4001
3384  09:15:42    15000  3005
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
3385  3386  2015-12-12     Ikoyi         Beef Suya   3000         1  09:15:43
3386  3387  2015-12-09  Surulere  BBQ Philly Steak   4000         3  09:15:44
3387  3388  2015-12-15   Gbagada        Hot Veggie   4000         3  09:15:45
3388  3389  2015-12-04     Lekki           Meatzaa   2000         5  09:15:47
3389  3390  2015-12-03  Surulere          Italiano   3000         5  09:15:48

      Revenue  Snap
3385     3000  3001
3386    12000  4003
3387    12000  4003
3388    10000  2005
3389    15000  3005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3390  3391  2015-12-12    Ibadan          BBQ Chicken   4000         4
3391  3392  2015-12-10  Surulere  Hot Pepperoni Feast   4000         5
3392  3393  2015-12-10   Gbagada          BBQ Chicken   4000         3
3393  3394  2015-12-11   Gbagada            Margarita   4000         4
3394  3395  2015-12-10   Gbagada       Pepperoni Suya   3000         5

          Time  Revenue  Snap
3390  09:15:48    16000  4004
3391  09:15:50    20000  4005
3392  09:15:51    12000  4003
3393  09:15:53    16000  4004
3394  09:15:56    15000  3005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3395  3396  2015-12-10  Surulere         Chicken Suya   4000         2
3396  3397  2015-12-13     Lekki           Hot Veggie   4000         5
3397  3398  2015-12-05     Ikoyi  Hot Pepperoni Feast   4000         5
3398  3399  2015-12-15   Gbagada           Hot Veggie   4000         5
3399  3400  2015-12-08   Gbagada              Meatzaa   2000         2

          Time  Revenue  Snap
3395  09:15:57     8000  4002
3396  09:15:58    20000  4005
3397  09:15:58    20000  4005
3398  09:16:01    20000  4005
3399  09:16:01     4000  2002
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
3400  3401  2015-12-08    Ibadan      BBQ Chicken   4000         5  09:16:03
3401  3402  2015-12-08    Ibadan  Pepperoni Feast   4000         1  09:16:03
3402  3403  2015-12-14   Gbagada       Hot Veggie   4000         4  09:16:03
3403  3404  2015-12-08  Surulere   Pepperoni Suya   3000         2  09:16:03
3404  3405  2015-12-07   Gbagada   Chicken Legend   2000         2  09:16:03

      Revenue  Snap
3400    20000  4005
3401     4000  4001
3402    16000  4004
3403     6000  3002
3404     4000  2002
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
3405  3406  2015-12-05    Lekki           Hot Veggie   4000         3
3406  3407  2015-12-15    Ikoyi  Hot Pepperoni Feast   4000         5
3407  3408  2015-12-06   Ibadan       Chicken Legend   2000         2
3408  3409  2015-12-04    Lekki      Pepperoni Feast   4000         1
3409  3410  2015-12-09  Gbagada       Pepperoni Suya   3000         5

          Time  Revenue  Snap
3405  09:16:04    12000  4003
3406  09:16:04    20000  4005
3407  09:16:05     4000  2002
3408  09:16:07     4000  4001
3409  09:16:08    15000  3005
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3410  3411  2015-12-10  Surulere       Margarita   4000         1  09:16:08
3411  3412  2015-12-12     Ikoyi  Pepperoni Suya   3000         1  09:16:09
3412  3413  2015-12-10     Ikoyi  Chicken Legend   2000         3  09:16:10
3413  3414  2015-12-06  Surulere     BBQ Chicken   4000         2  09:16:11
3414  3415  2015-12-14     Ikoyi    Extravaganza   2000         5  09:16:12

      Revenue  Snap
3410     4000  4001
3411     3000  3001
3412     6000  2003
3413     8000  4002
3414    10000  2005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3415  3416  2015-12-09     Lekki             Italiano   3000         5
3416  3417  2015-12-08     Lekki         Extravaganza   2000         3
3417  3418  2015-12-06  Surulere      Pepperoni Feast   4000         1
3418  3419  2015-12-06   Gbagada  Hot Pepperoni Feast   4000         5
3419  3420  2015-12-10  Surulere     BBQ Philly Steak   4000         5

          Time  Revenue  Snap
3415  09:16:13    15000  3005
3416  09:16:17     6000  2003
3417  09:16:23     4000  4001
3418  09:16:23    20000  4005
3419  09:16:23    20000  4005
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
3420  3421  2015-12-03    Ikoyi   Chicken Feast   2000         4  09:16:25
3421  3422  2015-12-11    Lekki       Margarita   4000         3  09:16:26
3422  3423  2015-12-13   Ibadan  Pepperoni Suya   3000         1  09:16:26
3423  3424  2015-12-05  Gbagada       Margarita   4000         2  09:16:26
3424  3425  2015-12-15  Gbagada     BBQ Chicken   4000         5  09:16:28

      Revenue  Snap
3420     8000  2004
3421    12000  4003
3422     3000  3001
3423     8000  4002
3424    20000  4005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3425  3426  2015-12-05  Surulere             Italiano   3000         1
3426  3427  2015-12-11     Lekki  Hot Pepperoni Feast   4000         3
3427  3428  2015-12-03  Surulere            Beef Suya   3000         3
3428  3429  2015-12-03   Gbagada             Italiano   3000         3
3429  3430  2015-12-04   Gbagada         Extravaganza   2000         5

          Time  Revenue  Snap
3425  09:16:30     3000  3001
3426  09:16:30    12000  4003
3427  09:16:30     9000  3003
3428  09:16:31     9000  3003
3429  09:16:33    10000  2005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3430  3431  2015-12-08   Gbagada  Hot Pepperoni Feast   4000         2
3431  3432  2015-12-07    Ibadan       Pepperoni Suya   3000         5
3432  3433  2015-12-05     Ikoyi             Italiano   3000         2
3433  3434  2015-12-09  Surulere         Chicken Suya   4000         4
3434  3435  2015-12-06    Ibadan            Margarita   4000         5

          Time  Revenue  Snap
3430  09:16:33     8000  4002
3431  09:16:33    15000  3005
3432  09:16:34     6000  3002
3433  09:16:34    16000  4004
3434  09:16:34    20000  4005
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3435  3436  2015-12-10    Ibadan  Pepperoni Suya   3000         2  09:16:37
3436  3437  2015-12-05  Surulere      Hot Veggie   4000         5  09:16:41
3437  3438  2015-12-13   Gbagada  Pepperoni Suya   3000         2  09:16:42
3438  3439  2015-12-11     Ikoyi  Veggie Supreme   3000         3  09:16:42
3439  3440  2015-12-15  Surulere  Pepperoni Suya   3000         2  09:16:43

      Revenue  Snap
3435     6000  3002
3436    20000  4005
3437     6000  3002
3438     9000  3003
3439     6000  3002
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
3440  3441  2015-12-06     Lekki   Pepperoni Feast   4000         3  09:16:45
3441  3442  2015-12-09    Ibadan    Pepperoni Suya   3000         4  09:16:45
3442  3443  2015-12-06  Surulere    Veggie Supreme   3000         2  09:16:48
3443  3444  2015-12-11   Gbagada  BBQ Philly Steak   4000         4  09:16:48
3444  3445  2015-12-03     Lekki           Meatzaa   2000         3  09:16:50

      Revenue  Snap
3440    12000  4003
3441    12000  3004
3442     6000  3002
3443    16000  4004
3444     6000  2003
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
3445  3446  2015-12-08  Surulere      Chicken Bali   2000         5  09:16:50
3446  3447  2015-12-06     Ikoyi        Hot Veggie   4000         1  09:16:51
3447  3448  2015-12-14   Gbagada       BBQ Chicken   4000         3  09:16:53
3448  3449  2015-12-14   Gbagada           Meatzaa   2000         5  09:16:54
3449  3450  2015-12-05     Ikoyi  BBQ Philly Steak   4000         1  09:16:56

      Revenue  Snap
3445    10000  2005
3446     4000  4001
3447    12000  4003
3448    10000  2005
3449     4000  4001
CHUNK BOSS
       S/N        Date  Branch      Pizza Sold  Price  Quantity      Time  \
3450  3451  2015-12-11  Ibadan   Chicken Feast   2000         1  09:16:56
3451  3452  2015-12-11   Ikoyi  Veggie Supreme   3000         5  09:16:57
3452  3453  2015-12-03   Ikoyi  Chicken Legend   2000         4  09:16:57
3453  3454  2015-12-13   Ikoyi        Italiano   3000         4  09:16:57
3454  3455  2015-12-08   Ikoyi   Chicken Feast   2000         5  09:16:58

      Revenue  Snap
3450     2000  2001
3451    15000  3005
3452     8000  2004
3453    12000  3004
3454    10000  2005

CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
3455  3456  2015-12-07     Lekki  Pepperoni Feast   4000         1  09:16:58
3456  3457  2015-12-03  Surulere         Italiano   3000         3  09:16:59
3457  3458  2015-12-11     Lekki  Pepperoni Feast   4000         1  09:17:00
3458  3459  2015-12-09     Ikoyi        Margarita   4000         2  09:17:02
3459  3460  2015-12-06     Ikoyi   Pepperoni Suya   3000         5  09:17:04

      Revenue  Snap
3455     4000  4001
3456     9000  3003
3457     4000  4001
3458     8000  4002
3459    15000  3005
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
3460  3461  2015-12-15  Gbagada      Pepperoni Feast   4000         2
3461  3462  2015-12-15  Gbagada              Meatzaa   2000         4
3462  3463  2015-12-06   Ibadan  Hot Pepperoni Feast   4000         5
3463  3464  2015-12-11   Ibadan       Chicken Legend   2000         2
3464  3465  2015-12-15   Ibadan        Chicken Feast   2000         3

          Time  Revenue  Snap
3460  09:17:05     8000  4002
3461  09:17:06     8000  2004
3462  09:17:08    20000  4005
3463  09:17:08     4000  2002
3464  09:17:14     6000  2003
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
3465  3466  2015-12-06  Surulere     Chicken Feast   2000         4  09:17:14
3466  3467  2015-12-06   Gbagada  BBQ Philly Steak   4000         3  09:17:16
3467  3468  2015-12-08     Lekki       BBQ Chicken   4000         4  09:17:16
3468  3469  2015-12-11     Lekki    Pepperoni Suya   3000         4  09:17:16
3469  3470  2015-12-06   Gbagada      Extravaganza   2000         1  09:17:16

      Revenue  Snap
3465     8000  2004
3466    12000  4003
3467    16000  4004
3468    12000  3004
3469     2000  2001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3470  3471  2015-12-11  Surulere       Beef Suya   3000         4  09:17:16
3471  3472  2015-12-13     Ikoyi    Chicken Bali   2000         3  09:17:19
3472  3473  2015-12-03  Surulere   Chicken Feast   2000         5  09:17:19
3473  3474  2015-12-10   Gbagada  Pepperoni Suya   3000         1  09:17:21
3474  3475  2015-12-08     Lekki    Chicken Suya   4000         3  09:17:21

      Revenue  Snap
3470    12000  3004
3471     6000  2003
3472    10000  2005
3473     3000  3001
3474    12000  4003
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3475  3476  2015-12-09     Lekki    Extravaganza   2000         3  09:17:21
3476  3477  2015-12-05    Ibadan  Pepperoni Suya   3000         4  09:17:22
3477  3478  2015-12-08    Ibadan  Pepperoni Suya   3000         1  09:17:22
3478  3479  2015-12-14     Ikoyi         Meatzaa   2000         4  09:17:24
3479  3480  2015-12-04  Surulere   Chicken Feast   2000         4  09:17:24

      Revenue  Snap
3475     6000  2003
3476    12000  3004
3477     3000  3001
3478     8000  2004
3479     8000  2004
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
3480  3481  2015-12-15  Gbagada  Chicken Legend   2000         3  09:17:24
3481  3482  2015-12-04    Ikoyi  Veggie Supreme   3000         4  09:17:25
3482  3483  2015-12-05    Ikoyi       Margarita   4000         3  09:17:26
3483  3484  2015-12-15    Lekki     BBQ Chicken   4000         4  09:17:29
3484  3485  2015-12-07   Ibadan    Extravaganza   2000         2  09:17:30

      Revenue  Snap
3480     6000  2003
3481    12000  3004
3482    12000  4003
3483    16000  4004
3484     4000  2002
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
3485  3486  2015-12-04   Gbagada           Meatzaa   2000         5  09:17:31
3486  3487  2015-12-10     Ikoyi      Extravaganza   2000         1  09:17:31
3487  3488  2015-12-13   Gbagada        Hot Veggie   4000         2  09:17:31
3488  3489  2015-12-05     Ikoyi           Meatzaa   2000         5  09:17:33
3489  3490  2015-12-15  Surulere  BBQ Philly Steak   4000         4  09:17:37

      Revenue  Snap
3485    10000  2005
3486     2000  2001
3487     8000  4002
3488    10000  2005
3489    16000  4004
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3490  3491  2015-12-08     Ikoyi         Extravaganza   2000         2
3491  3492  2015-12-08  Surulere     BBQ Philly Steak   4000         4
3492  3493  2015-12-05   Gbagada  Hot Pepperoni Feast   4000         1
3493  3494  2015-12-10    Ibadan         Chicken Suya   4000         1
3494  3495  2015-12-13   Gbagada        Chicken Feast   2000         4

          Time  Revenue  Snap
3490  09:17:37     4000  2002
3491  09:17:38    16000  4004
3492  09:17:39     4000  4001
3493  09:17:40     4000  4001
3494  09:17:42     8000  2004
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
3495  3496  2015-12-15     Lekki    Pepperoni Suya   3000         3  09:17:43
3496  3497  2015-12-03  Surulere  BBQ Philly Steak   4000         4  09:17:44
3497  3498  2015-12-14     Lekki    Chicken Legend   2000         1  09:17:46
3498  3499  2015-12-09   Gbagada           Meatzaa   2000         1  09:17:47
3499  3500  2015-12-03     Lekki        Hot Veggie   4000         5  09:17:48

      Revenue  Snap
3495     9000  3003
3496    16000  4004
3497     2000  2001
3498     2000  2001
3499    20000  4005
CHUNK BOSS
       S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
3500  3501  2015-12-04    Ikoyi  Pepperoni Feast   4000         1  09:17:49
3501  3502  2015-12-03  Gbagada     Extravaganza   2000         5  09:17:51
3502  3503  2015-12-13    Lekki     Chicken Suya   4000         1  09:17:51
3503  3504  2015-12-08  Gbagada     Extravaganza   2000         3  09:17:51
3504  3505  2015-12-08   Ibadan        Margarita   4000         4  09:17:56

      Revenue  Snap
3500     4000  4001
3501    10000  2005
3502     4000  4001
3503     6000  2003
3504    16000  4004
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
3505  3506  2015-12-08     Ikoyi          Meatzaa   2000         3  09:17:56
3506  3507  2015-12-03    Ibadan    Chicken Feast   2000         2  09:17:58
3507  3508  2015-12-15   Gbagada  Pepperoni Feast   4000         1  09:17:58
3508  3509  2015-12-06   Gbagada   Chicken Legend   2000         3  09:17:59
3509  3510  2015-12-04  Surulere   Chicken Legend   2000         5  09:18:00

      Revenue  Snap
3505     6000  2003
3506     4000  2002
3507     4000  4001
3508     6000  2003
3509    10000  2005
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
3510  3511  2015-12-12    Lekki  Hot Pepperoni Feast   4000         5
3511  3512  2015-12-15  Gbagada           Hot Veggie   4000         2
3512  3513  2015-12-10    Ikoyi       Pepperoni Suya   3000         1
3513  3514  2015-12-03    Ikoyi         Chicken Suya   4000         4
3514  3515  2015-12-14    Lekki       Pepperoni Suya   3000         5

          Time  Revenue  Snap
3510  09:18:02    20000  4005
3511  09:18:04     8000  4002
3512  09:18:05     3000  3001
3513  09:18:05    16000  4004
3514  09:18:06    15000  3005
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
3515  3516  2015-12-07     Ikoyi     Chicken Suya   4000         2  09:18:08
3516  3517  2015-12-13  Surulere         Italiano   3000         2  09:18:09
3517  3518  2015-12-12  Surulere        Margarita   4000         5  09:18:10
3518  3519  2015-12-08     Ikoyi  Pepperoni Feast   4000         1  09:18:11
3519  3520  2015-12-13  Surulere     Chicken Bali   2000         3  09:18:12

      Revenue  Snap
3515     8000  4002
3516     6000  3002
3517    20000  4005
3518     4000  4001
3519     6000  2003
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
3520  3521  2015-12-08    Ibadan          Italiano   3000         3  09:18:13
3521  3522  2015-12-10   Gbagada    Pepperoni Suya   3000         2  09:18:14
3522  3523  2015-12-08  Surulere        Hot Veggie   4000         5  09:18:14
3523  3524  2015-12-07    Ibadan        Hot Veggie   4000         5  09:18:14
3524  3525  2015-12-12  Surulere  BBQ Philly Steak   4000         5  09:18:14

      Revenue  Snap
3520     9000  3003
3521     6000  3002
3522    20000  4005
3523    20000  4005
3524    20000  4005
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3525  3526  2015-12-04     Lekki  Veggie Supreme   3000         3  09:18:16
3526  3527  2015-12-11     Ikoyi  Chicken Legend   2000         1  09:18:19
3527  3528  2015-12-15     Ikoyi      Hot Veggie   4000         1  09:18:19
3528  3529  2015-12-06  Surulere       Beef Suya   3000         1  09:18:19
3529  3530  2015-12-12     Lekki    Chicken Bali   2000         1  09:18:20

      Revenue  Snap
3525     9000  3003
3526     2000  2001
3527     4000  4001
3528     3000  3001
3529     2000  2001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3530  3531  2015-12-11     Ikoyi  Pepperoni Suya   3000         4  09:18:20
3531  3532  2015-12-14  Surulere    Chicken Suya   4000         5  09:18:20
3532  3533  2015-12-13    Ibadan       Margarita   4000         4  09:18:21
3533  3534  2015-12-08     Lekki      Hot Veggie   4000         2  09:18:21
3534  3535  2015-12-14    Ibadan  Chicken Legend   2000         3  09:18:22

      Revenue  Snap
3530    12000  3004
3531    20000  4005
3532    16000  4004
3533     8000  4002
3534     6000  2003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3535  3536  2015-12-04     Ikoyi            Beef Suya   3000         3
3536  3537  2015-12-08     Ikoyi       Veggie Supreme   3000         4
3537  3538  2015-12-11    Ibadan         Chicken Bali   2000         4
3538  3539  2015-12-04     Ikoyi         Chicken Bali   2000         3
3539  3540  2015-12-12  Surulere  Hot Pepperoni Feast   4000         3

          Time  Revenue  Snap
3535  09:18:23     9000  3003
3536  09:18:25    12000  3004
3537  09:18:28     8000  2004
3538  09:18:30     6000  2003
3539  09:18:30    12000  4003
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
3540  3541  2015-12-07  Surulere           Meatzaa   2000         4  09:18:30
3541  3542  2015-12-09    Ibadan  BBQ Philly Steak   4000         3  09:18:31
3542  3543  2015-12-15   Gbagada    Pepperoni Suya   3000         5  09:18:31
3543  3544  2015-12-11     Ikoyi    Chicken Legend   2000         3  09:18:32
3544  3545  2015-12-04     Lekki      Extravaganza   2000         1  09:18:32

      Revenue  Snap
3540     8000  2004
3541    12000  4003
3542    15000  3005
3543     6000  2003
3544     2000  2001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3545  3546  2015-12-08  Surulere  Veggie Supreme   3000         2  09:18:33
3546  3547  2015-12-11     Ikoyi   Chicken Feast   2000         2  09:18:34
3547  3548  2015-12-04    Ibadan  Pepperoni Suya   3000         5  09:18:35
3548  3549  2015-12-15  Surulere  Pepperoni Suya   3000         3  09:18:38
3549  3550  2015-12-07     Ikoyi         Meatzaa   2000         2  09:18:39

      Revenue  Snap
3545     6000  3002
3546     4000  2002
3547    15000  3005
3548     9000  3003
3549     4000  2002
CHUNK BOSS

       S/N        Date    Branch    Pizza Sold  Price  Quantity      Time  \
3550  3551  2015-12-08  Surulere      Italiano   3000         3  09:18:43
3551  3552  2015-12-07     Ikoyi  Chicken Bali   2000         5  09:18:43
3552  3553  2015-12-14     Ikoyi       Meatzaa   2000         4  09:18:46
3553  3554  2015-12-08  Surulere     Margarita   4000         1  09:18:48
3554  3555  2015-12-13     Lekki     Margarita   4000         5  09:18:50

      Revenue  Snap
3550     9000  3003
3551    10000  2005
3552     8000  2004
3553     4000  4001
3554    20000  4005
CHUNK BOSS
       S/N        Date  Branch       Pizza Sold  Price  Quantity      Time  \
3555  3556  2015-12-03   Ikoyi  Pepperoni Feast   4000         2  09:18:53
3556  3557  2015-12-06   Lekki   Veggie Supreme   3000         1  09:18:54
3557  3558  2015-12-06   Ikoyi   Pepperoni Suya   3000         3  09:18:54
3558  3559  2015-12-12   Ikoyi         Italiano   3000         2  09:18:55
3559  3560  2015-12-12  Ibadan  Pepperoni Feast   4000         5  09:18:57

      Revenue  Snap
3555     8000  4002
3556     3000  3001
3557     9000  3003
3558     6000  3002
3559    20000  4005
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
3560  3561  2015-12-11   Ibadan           Meatzaa   2000         4  09:18:58
3561  3562  2015-12-06  Gbagada        Hot Veggie   4000         5  09:18:59
3562  3563  2015-12-15  Gbagada    Pepperoni Suya   3000         1  09:18:59
3563  3564  2015-12-04    Lekki  BBQ Philly Steak   4000         2  09:18:59
3564  3565  2015-12-09  Gbagada          Italiano   3000         4  09:19:00

      Revenue  Snap
3560     8000  2004
3561    20000  4005
3562     3000  3001
3563     8000  4002
3564    12000  3004
CHUNK BOSS
       S/N        Date   Branch    Pizza Sold  Price  Quantity      Time  \
3565  3566  2015-12-09    Lekki  Chicken Suya   4000         5  09:19:01
3566  3567  2015-12-12    Lekki  Chicken Suya   4000         2  09:19:04
3567  3568  2015-12-04    Ikoyi     Beef Suya   3000         1  09:19:06
3568  3569  2015-12-06    Ikoyi     Margarita   4000         4  09:19:06
3569  3570  2015-12-15  Gbagada  Extravaganza   2000         5  09:19:07

      Revenue  Snap
3565    20000  4005
3566     8000  4002
3567     3000  3001
3568    16000  4004
3569    10000  2005
CHUNK BOSS
       S/N        Date  Branch       Pizza Sold  Price  Quantity      Time  \
3570  3571  2015-12-04   Ikoyi       Hot Veggie   4000         3  09:19:09
3571  3572  2015-12-04   Lekki        Margarita   4000         1  09:19:09
3572  3573  2015-12-03  Ibadan  Pepperoni Feast   4000         4  09:19:10
3573  3574  2015-12-03   Lekki   Chicken Legend   2000         1  09:19:10
3574  3575  2015-12-14   Ikoyi   Chicken Legend   2000         2  09:19:12

      Revenue  Snap
3570    12000  4003
3571     4000  4001
3572    16000  4004
3573     2000  2001
3574     4000  2002
CHUNK BOSS
       S/N        Date  Branch        Pizza Sold  Price  Quantity      Time  \
3575  3576  2015-12-10  Ibadan   Pepperoni Feast   4000         4  09:19:14
3576  3577  2015-12-03   Ikoyi       BBQ Chicken   4000         3  09:19:15
3577  3578  2015-12-03   Lekki   Pepperoni Feast   4000         1  09:19:17
3578  3579  2015-12-10   Ikoyi  BBQ Philly Steak   4000         1  09:19:18
3579  3580  2015-12-11   Ikoyi      Chicken Suya   4000         4  09:19:21

      Revenue  Snap
3575    16000  4004
3576    12000  4003
3577     4000  4001
3578     4000  4001
3579    16000  4004
CHUNK BOSS
       S/N        Date  Branch       Pizza Sold  Price  Quantity      Time  \
3580  3581  2015-12-06   Ikoyi        Margarita   4000         4  09:19:21
3581  3582  2015-12-15  Ibadan        Beef Suya   3000         5  09:19:23
3582  3583  2015-12-15  Ibadan   Chicken Legend   2000         4  09:19:25
3583  3584  2015-12-03  Ibadan  Pepperoni Feast   4000         4  09:19:26
3584  3585  2015-12-10  Ibadan      BBQ Chicken   4000         3  09:19:27

      Revenue  Snap
3580    16000  4004
3581    15000  3005
3582     8000  2004
3583    16000  4004
3584    12000  4003
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
3585  3586  2015-12-06     Lekki         Italiano   3000         4  09:19:29
3586  3587  2015-12-05  Surulere  Pepperoni Feast   4000         3  09:19:31
3587  3588  2015-12-15  Surulere     Chicken Suya   4000         4  09:19:32
3588  3589  2015-12-14     Ikoyi     Chicken Bali   2000         3  09:19:34
3589  3590  2015-12-06    Ibadan      BBQ Chicken   4000         1  09:19:35

      Revenue  Snap
3585    12000  3004
3586    12000  4003
3587    16000  4004
3588     6000  2003
3589     4000  4001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3590  3591  2015-12-13   Gbagada    Chicken Suya   4000         3  09:19:38
3591  3592  2015-12-06    Ibadan    Chicken Suya   4000         3  09:19:39
3592  3593  2015-12-09    Ibadan  Chicken Legend   2000         4  09:19:39
3593  3594  2015-12-11     Lekki      Hot Veggie   4000         2  09:19:40
3594  3595  2015-12-13  Surulere        Italiano   3000         2  09:19:43

      Revenue  Snap
3590    12000  4003
3591    12000  4003
3592     8000  2004
3593     8000  4002
3594     6000  3002
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
3595  3596  2015-12-12  Surulere     Chicken Suya   4000         3  09:19:43
3596  3597  2015-12-10     Lekki     Chicken Bali   2000         3  09:19:44
3597  3598  2015-12-04  Surulere  Pepperoni Feast   4000         4  09:19:45
3598  3599  2015-12-08   Gbagada    Chicken Feast   2000         5  09:19:49
3599  3600  2015-12-07   Gbagada        Beef Suya   3000         1  09:19:50

      Revenue  Snap
3595    12000  4003
3596     6000  2003
3597    16000  4004
3598    10000  2005
3599     3000  3001
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
3600  3601  2015-12-04   Ibadan   Chicken Feast   2000         3  09:19:51
3601  3602  2015-12-09  Gbagada  Veggie Supreme   3000         1  09:19:53
3602  3603  2015-12-11  Gbagada   Chicken Feast   2000         3  09:19:53
3603  3604  2015-12-11    Lekki    Extravaganza   2000         1  09:19:58
3604  3605  2015-12-12    Lekki  Pepperoni Suya   3000         4  09:19:58

      Revenue  Snap
3600     6000  2003
3601     3000  3001
3602     6000  2003
3603     2000  2001
3604    12000  3004
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
3605  3606  2015-12-04    Ibadan     Chicken Feast   2000         4  09:20:02
3606  3607  2015-12-03  Surulere          Italiano   3000         5  09:20:03
3607  3608  2015-12-14    Ibadan  BBQ Philly Steak   4000         1  09:20:03
3608  3609  2015-12-07     Lekki         Beef Suya   3000         1  09:20:04
3609  3610  2015-12-08  Surulere           Meatzaa   2000         3  09:20:05

      Revenue  Snap
3605     8000  2004
3606    15000  3005
3607     4000  4001
3608     3000  3001
3609     6000  2003
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3610  3611  2015-12-09  Surulere  Chicken Legend   2000         4  09:20:08
3611  3612  2015-12-08     Lekki  Pepperoni Suya   3000         2  09:20:09
3612  3613  2015-12-14     Ikoyi      Hot Veggie   4000         2  09:20:10
3613  3614  2015-12-08  Surulere       Margarita   4000         5  09:20:12
3614  3615  2015-12-13  Surulere       Beef Suya   3000         5  09:20:12

      Revenue  Snap
3610     8000  2004
3611     6000  3002
3612     8000  4002
3613    20000  4005
3614    15000  3005
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
3615  3616  2015-12-12  Surulere       Hot Veggie   4000         2  09:20:13
3616  3617  2015-12-07  Surulere   Pepperoni Suya   3000         4  09:20:13
3617  3618  2015-12-08  Surulere  Pepperoni Feast   4000         3  09:20:17
3618  3619  2015-12-04   Gbagada      BBQ Chicken   4000         2  09:20:17
3619  3620  2015-12-06    Ibadan   Chicken Legend   2000         1  09:20:17

      Revenue  Snap
3615     8000  4002
3616    12000  3004
3617    12000  4003
3618     8000  4002
3619     2000  2001
CHUNK BOSS
       S/N        Date  Branch      Pizza Sold  Price  Quantity      Time  \
3620  3621  2015-12-07   Lekki  Chicken Legend   2000         5  09:20:18
3621  3622  2015-12-04   Ikoyi  Veggie Supreme   3000         3  09:20:21
3622  3623  2015-12-10   Lekki    Chicken Bali   2000         3  09:20:22
3623  3624  2015-12-11  Ibadan   Chicken Feast   2000         2  09:20:24
3624  3625  2015-12-15  Ibadan    Extravaganza   2000         5  09:20:24

      Revenue  Snap
3620    10000  2005
3621     9000  3003
3622     6000  2003
3623     4000  2002
3624    10000  2005
CHUNK BOSS
       S/N        Date    Branch     Pizza Sold  Price  Quantity      Time  \
3625  3626  2015-12-04    Ibadan  Chicken Feast   2000         1  09:20:24
3626  3627  2015-12-12     Lekki    BBQ Chicken   4000         1  09:20:25
3627  3628  2015-12-05    Ibadan        Meatzaa   2000         1  09:20:25
3628  3629  2015-12-15     Lekki        Meatzaa   2000         3  09:20:26
3629  3630  2015-12-14  Surulere      Margarita   4000         3  09:20:27

      Revenue  Snap
3625     2000  2001
3626     4000  4001
3627     2000  2001
3628     6000  2003
3629    12000  4003
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
3630  3631  2015-12-07     Lekki        Beef Suya   3000         3  09:20:27
3631  3632  2015-12-08     Lekki  Pepperoni Feast   4000         5  09:20:27
3632  3633  2015-12-04  Surulere         Italiano   3000         1  09:20:28
3633  3634  2015-12-09     Lekki     Chicken Bali   2000         4  09:20:28
3634  3635  2015-12-08     Lekki   Pepperoni Suya   3000         5  09:20:29

      Revenue  Snap
3630     9000  3003
3631    20000  4005
3632     3000  3001
3633     8000  2004
3634    15000  3005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3635  3636  2015-12-03    Ibadan       Chicken Legend   2000         4
3636  3637  2015-12-06  Surulere      Pepperoni Feast   4000         4
3637  3638  2015-12-12   Gbagada       Veggie Supreme   3000         5
3638  3639  2015-12-03     Lekki          BBQ Chicken   4000         4
3639  3640  2015-12-10  Surulere  Hot Pepperoni Feast   4000         2

          Time  Revenue  Snap
3635  09:20:34     8000  2004
3636  09:20:36    16000  4004
3637  09:20:41    15000  3005
3638  09:20:41    16000  4004
3639  09:20:43     8000  4002
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
3640  3641  2015-12-09    Ibadan  BBQ Philly Steak   4000         1  09:20:45
3641  3642  2015-12-13  Surulere        Hot Veggie   4000         3  09:20:46
3642  3643  2015-12-13     Lekki    Pepperoni Suya   3000         4  09:20:48
3643  3644  2015-12-05     Ikoyi  BBQ Philly Steak   4000         1  09:20:48
3644  3645  2015-12-04   Gbagada       BBQ Chicken   4000         2  09:20:51

      Revenue  Snap
3640     4000  4001
3641    12000  4003
3642    12000  3004
3643     4000  4001
3644     8000  4002
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3645  3646  2015-12-09     Lekki    Chicken Bali   2000         4  09:20:51
3646  3647  2015-12-05  Surulere  Pepperoni Suya   3000         1  09:20:52
3647  3648  2015-12-15  Surulere      Hot Veggie   4000         4  09:20:52
3648  3649  2015-12-06   Gbagada       Beef Suya   3000         2  09:20:53
3649  3650  2015-12-03     Lekki    Extravaganza   2000         5  09:20:53

      Revenue  Snap
3645     8000  2004
3646     3000  3001
3647    16000  4004
3648     6000  3002
3649    10000  2005
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
3650  3651  2015-12-09    Ibadan  BBQ Philly Steak   4000         4  09:20:55
3651  3652  2015-12-12     Lekki       BBQ Chicken   4000         5  09:20:58
3652  3653  2015-12-12  Surulere           Meatzaa   2000         2  09:20:59
3653  3654  2015-12-15     Ikoyi     Chicken Feast   2000         4  09:20:59
3654  3655  2015-12-11     Ikoyi       BBQ Chicken   4000         5  09:21:00

      Revenue  Snap
3650    16000  4004
3651    20000  4005
3652     4000  2002
3653     8000  2004
3654    20000  4005

CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3655  3656  2015-12-08  Surulere  Veggie Supreme   3000         2  09:21:00
3656  3657  2015-12-03   Gbagada    Chicken Suya   4000         5  09:21:01
3657  3658  2015-12-13  Surulere  Veggie Supreme   3000         4  09:21:01
3658  3659  2015-12-08     Ikoyi  Chicken Legend   2000         1  09:21:01
3659  3660  2015-12-10     Lekki    Extravaganza   2000         5  09:21:02

      Revenue  Snap
3655     6000  3002
3656    20000  4005
3657    12000  3004
3658     2000  2001
3659    10000  2005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3660  3661  2015-12-08    Ibadan  Hot Pepperoni Feast   4000         1
3661  3662  2015-12-11  Surulere         Extravaganza   2000         3
3662  3663  2015-12-03     Lekki            Margarita   4000         5
3663  3664  2015-12-04   Gbagada       Pepperoni Suya   3000         4
3664  3665  2015-12-09   Gbagada           Hot Veggie   4000         3

          Time  Revenue  Snap
3660  09:21:02     4000  4001
3661  09:21:03     6000  2003
3662  09:21:03    20000  4005
3663  09:21:04    12000  3004
3664  09:21:05    12000  4003
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3665  3666  2015-12-10   Gbagada  Pepperoni Suya   3000         5  09:21:07
3666  3667  2015-12-07    Ibadan    Chicken Bali   2000         3  09:21:07
3667  3668  2015-12-05     Ikoyi  Veggie Supreme   3000         3  09:21:07
3668  3669  2015-12-11  Surulere    Chicken Bali   2000         4  09:21:09
3669  3670  2015-12-12     Ikoyi    Extravaganza   2000         1  09:21:12

      Revenue  Snap
3665    15000  3005
3666     6000  2003
3667     9000  3003
3668     8000  2004
3669     2000  2001
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
3670  3671  2015-12-10    Ibadan     Extravaganza   2000         1  09:21:14
3671  3672  2015-12-11  Surulere  Pepperoni Feast   4000         5  09:21:15
3672  3673  2015-12-11    Ibadan   Veggie Supreme   3000         1  09:21:16
3673  3674  2015-12-06  Surulere       Hot Veggie   4000         3  09:21:19
3674  3675  2015-12-12    Ibadan      BBQ Chicken   4000         1  09:21:20

      Revenue  Snap
3670     2000  2001
3671    20000  4005
3672     3000  3001
3673    12000  4003
3674     4000  4001
CHUNK BOSS
       S/N        Date    Branch    Pizza Sold  Price  Quantity      Time  \
3675  3676  2015-12-15     Lekki       Meatzaa   2000         5  09:21:21
3676  3677  2015-12-03  Surulere    Hot Veggie   4000         1  09:21:22
3677  3678  2015-12-14    Ibadan  Chicken Bali   2000         1  09:21:23
3678  3679  2015-12-08    Ibadan     Margarita   4000         5  09:21:23
3679  3680  2015-12-03    Ibadan  Extravaganza   2000         1  09:21:25

      Revenue  Snap
3675    10000  2005
3676     4000  4001
3677     2000  2001
3678    20000  4005
3679     2000  2001
CHUNK BOSS
       S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
3680  3681  2015-12-15    Ikoyi        Beef Suya   3000         1  09:21:26
3681  3682  2015-12-11    Ikoyi  Pepperoni Feast   4000         5  09:21:28
3682  3683  2015-12-09   Ibadan      BBQ Chicken   4000         2  09:21:28
3683  3684  2015-12-05  Gbagada  Pepperoni Feast   4000         3  09:21:28
3684  3685  2015-12-07    Ikoyi   Pepperoni Suya   3000         2  09:21:29

      Revenue  Snap
3680     3000  3001
3681    20000  4005
3682     8000  4002
3683    12000  4003
3684     6000  3002
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3685  3686  2015-12-07  Surulere     BBQ Philly Steak   4000         4
3686  3687  2015-12-13  Surulere          BBQ Chicken   4000         3
3687  3688  2015-12-10   Gbagada       Chicken Legend   2000         4
3688  3689  2015-12-06     Ikoyi  Hot Pepperoni Feast   4000         2
3689  3690  2015-12-11     Lekki         Chicken Suya   4000         4

          Time  Revenue  Snap
3685  09:21:29    16000  4004
3686  09:21:29    12000  4003
3687  09:21:30     8000  2004
3688  09:21:31     8000  4002
3689  09:21:31    16000  4004
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3690  3691  2015-12-11  Surulere  Veggie Supreme   3000         5  09:21:32
3691  3692  2015-12-14  Surulere  Veggie Supreme   3000         1  09:21:32
3692  3693  2015-12-03     Lekki       Margarita   4000         4  09:21:33
3693  3694  2015-12-14   Gbagada       Margarita   4000         3  09:21:33
3694  3695  2015-12-07   Gbagada  Pepperoni Suya   3000         4  09:21:35

      Revenue  Snap
3690    15000  3005
3691     3000  3001
3692    16000  4004
3693    12000  4003
3694    12000  3004
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
3695  3696  2015-12-09  Surulere  BBQ Philly Steak   4000         4  09:21:35
3696  3697  2015-12-14  Surulere        Hot Veggie   4000         4  09:21:35
3697  3698  2015-12-05     Ikoyi          Italiano   3000         3  09:21:37
3698  3699  2015-12-05    Ibadan   Pepperoni Feast   4000         4  09:21:38
3699  3700  2015-12-05  Surulere      Chicken Suya   4000         2  09:21:38

      Revenue  Snap
3695    16000  4004
3696    16000  4004
3697     9000  3003
3698    16000  4004
3699     8000  4002
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3700  3701  2015-12-13    Ibadan             Italiano   3000         4
3701  3702  2015-12-11     Ikoyi          BBQ Chicken   4000         5
3702  3703  2015-12-11  Surulere       Chicken Legend   2000         5
3703  3704  2015-12-07     Lekki  Hot Pepperoni Feast   4000         2
3704  3705  2015-12-11     Ikoyi       Veggie Supreme   3000         1

          Time  Revenue  Snap
3700  09:21:38    12000  3004
3701  09:21:39    20000  4005
3702  09:21:40    10000  2005
3703  09:21:41     8000  4002
3704  09:21:43     3000  3001
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
3705  3706  2015-12-14   Gbagada    Chicken Feast   2000         5  09:21:43
3706  3707  2015-12-11   Gbagada      BBQ Chicken   4000         2  09:21:43
3707  3708  2015-12-10   Gbagada     Chicken Suya   4000         4  09:21:45
3708  3709  2015-12-09     Ikoyi  Pepperoni Feast   4000         2  09:21:46
3709  3710  2015-12-15  Surulere  Pepperoni Feast   4000         3  09:21:47

      Revenue  Snap
3705    10000  2005
3706     8000  4002
3707    16000  4004
3708     8000  4002
3709    12000  4003
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
3710  3711  2015-12-13    Ikoyi  Hot Pepperoni Feast   4000         2
3711  3712  2015-12-09  Gbagada     BBQ Philly Steak   4000         3
3712  3713  2015-12-06    Ikoyi  Hot Pepperoni Feast   4000         2
3713  3714  2015-12-09  Gbagada     BBQ Philly Steak   4000         3
3714  3715  2015-12-06    Ikoyi        Chicken Feast   2000         4

          Time  Revenue  Snap
3710  09:21:48     8000  4002
3711  09:21:49    12000  4003
3712  09:21:50     8000  4002
3713  09:21:51    12000  4003
3714  09:21:51     8000  2004
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3715  3716  2015-12-15  Surulere       Chicken Legend   2000         4
3716  3717  2015-12-11     Ikoyi      Pepperoni Feast   4000         4
3717  3718  2015-12-03    Ibadan  Hot Pepperoni Feast   4000         1
3718  3719  2015-12-06    Ibadan       Pepperoni Suya   3000         5
3719  3720  2015-12-11     Ikoyi             Italiano   3000         2

          Time  Revenue  Snap
3715  09:21:52     8000  2004
3716  09:21:52    16000  4004
3717  09:21:55     4000  4001
3718  09:22:00    15000  3005
3719  09:22:00     6000  3002
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
3720  3721  2015-12-11   Gbagada     Chicken Bali   2000         2  09:22:01
3721  3722  2015-12-03   Gbagada     Extravaganza   2000         5  09:22:01
3722  3723  2015-12-07     Lekki   Pepperoni Suya   3000         2  09:22:04
3723  3724  2015-12-05    Ibadan        Beef Suya   3000         3  09:22:05
3724  3725  2015-12-09  Surulere  Pepperoni Feast   4000         1  09:22:06

      Revenue  Snap
3720     4000  2002
3721    10000  2005
3722     6000  3002
3723     9000  3003
3724     4000  4001
CHUNK BOSS
       S/N        Date  Branch           Pizza Sold  Price  Quantity  \
3725  3726  2015-12-06  Ibadan        Chicken Feast   2000         1
3726  3727  2015-12-06  Ibadan            Margarita   4000         3
3727  3728  2015-12-07   Ikoyi           Hot Veggie   4000         3
3728  3729  2015-12-15   Ikoyi  Hot Pepperoni Feast   4000         4
3729  3730  2015-12-15   Ikoyi         Chicken Suya   4000         4

          Time  Revenue  Snap
3725  09:22:06     2000  2001
3726  09:22:10    12000  4003
3727  09:22:12    12000  4003
3728  09:22:13    16000  4004
3729  09:22:14    16000  4004
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
3730  3731  2015-12-11    Ikoyi  Hot Pepperoni Feast   4000         3
3731  3732  2015-12-13    Ikoyi  Hot Pepperoni Feast   4000         4
3732  3733  2015-12-09  Gbagada          BBQ Chicken   4000         1
3733  3734  2015-12-11   Ibadan       Pepperoni Suya   3000         2
3734  3735  2015-12-06    Ikoyi          BBQ Chicken   4000         3

          Time  Revenue  Snap
3730  09:22:14    12000  4003
3731  09:22:15    16000  4004
3732  09:22:15     4000  4001
3733  09:22:16     6000  3002
3734  09:22:17    12000  4003
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3735  3736  2015-12-15     Ikoyi   Chicken Feast   2000         2  09:22:19
3736  3737  2015-12-07    Ibadan  Veggie Supreme   3000         1  09:22:19
3737  3738  2015-12-06     Ikoyi    Extravaganza   2000         4  09:22:22
3738  3739  2015-12-12  Surulere     BBQ Chicken   4000         1  09:22:23
3739  3740  2015-12-04  Surulere  Chicken Legend   2000         5  09:22:24

      Revenue  Snap
3735     4000  2002
3736     3000  3001
3737     8000  2004
3738     4000  4001
3739    10000  2005
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3740  3741  2015-12-09     Lekki      Hot Veggie   4000         1  09:22:25
3741  3742  2015-12-15  Surulere        Italiano   3000         4  09:22:25
3742  3743  2015-12-06   Gbagada        Italiano   3000         4  09:22:25
3743  3744  2015-12-06     Lekki  Veggie Supreme   3000         3  09:22:25
3744  3745  2015-12-11    Ibadan  Pepperoni Suya   3000         1  09:22:29

      Revenue  Snap
3740     4000  4001
3741    12000  3004
3742    12000  3004
3743     9000  3003
3744     3000  3001
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
3745  3746  2015-12-11   Gbagada  BBQ Philly Steak   4000         2  09:22:30
3746  3747  2015-12-10    Ibadan         Beef Suya   3000         1  09:22:30
3747  3748  2015-12-05  Surulere          Italiano   3000         4  09:22:30
3748  3749  2015-12-10   Gbagada          Italiano   3000         2  09:22:31
3749  3750  2015-12-12   Gbagada    Pepperoni Suya   3000         5  09:22:33

      Revenue  Snap
3745     8000  4002
3746     3000  3001
3747    12000  3004
3748     6000  3002
3749    15000  3005
CHUNK BOSS

       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3750  3751  2015-12-06     Ikoyi       Pepperoni Suya   3000         3
3751  3752  2015-12-13    Ibadan              Meatzaa   2000         3
3752  3753  2015-12-06  Surulere  Hot Pepperoni Feast   4000         2
3753  3754  2015-12-09    Ibadan  Hot Pepperoni Feast   4000         5
3754  3755  2015-12-09     Lekki       Veggie Supreme   3000         2

          Time  Revenue  Snap
3750  09:22:33     9000  3003
3751  09:22:33     6000  2003
3752  09:22:36     8000  4002
3753  09:22:36    20000  4005
3754  09:22:37     6000  3002
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3755  3756  2015-12-07   Gbagada            Beef Suya   3000         1
3756  3757  2015-12-10     Ikoyi      Pepperoni Feast   4000         3
3757  3758  2015-12-05   Gbagada       Chicken Legend   2000         3
3758  3759  2015-12-06  Surulere       Pepperoni Suya   3000         3
3759  3760  2015-12-13    Ibadan  Hot Pepperoni Feast   4000         3

          Time  Revenue  Snap
3755  09:22:38     3000  3001
3756  09:22:38    12000  4003
3757  09:22:39     6000  2003
3758  09:22:39     9000  3003
3759  09:22:40    12000  4003
CHUNK BOSS
       S/N        Date  Branch           Pizza Sold  Price  Quantity  \
3760  3761  2015-12-09   Ikoyi         Extravaganza   2000         2
3761  3762  2015-12-07   Ikoyi        Chicken Feast   2000         3
3762  3763  2015-12-14  Ibadan            Margarita   4000         3
3763  3764  2015-12-13   Lekki  Hot Pepperoni Feast   4000         4
3764  3765  2015-12-09   Ikoyi       Chicken Legend   2000         2

          Time  Revenue  Snap
3760  09:22:40     4000  2002
3761  09:22:40     6000  2003
3762  09:22:42    12000  4003
3763  09:22:48    16000  4004
3764  09:22:49     4000  2002
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
3765  3766  2015-12-03    Ikoyi  Hot Pepperoni Feast   4000         4
3766  3767  2015-12-08  Gbagada  Hot Pepperoni Feast   4000         2
3767  3768  2015-12-14    Ikoyi            Beef Suya   3000         1
3768  3769  2015-12-06  Gbagada         Extravaganza   2000         4
3769  3770  2015-12-12  Gbagada            Beef Suya   3000         3

          Time  Revenue  Snap
3765  09:22:49    16000  4004
3766  09:22:49     8000  4002
3767  09:22:50     3000  3001
3768  09:22:50     8000  2004
3769  09:22:50     9000  3003
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
3770  3771  2015-12-09  Surulere   Chicken Legend   2000         5  09:22:52
3771  3772  2015-12-10     Ikoyi        Margarita   4000         2  09:22:52
3772  3773  2015-12-04     Ikoyi       Hot Veggie   4000         3  09:22:53
3773  3774  2015-12-15    Ibadan     Extravaganza   2000         4  09:22:56
3774  3775  2015-12-03     Ikoyi  Pepperoni Feast   4000         5  09:22:57

      Revenue  Snap
3770    10000  2005
3771     8000  4002
3772    12000  4003
3773     8000  2004
3774    20000  4005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3775  3776  2015-12-05    Ibadan         Chicken Bali   2000         3
3776  3777  2015-12-10     Ikoyi              Meatzaa   2000         1
3777  3778  2015-12-09   Gbagada         Extravaganza   2000         4
3778  3779  2015-12-12     Lekki         Chicken Bali   2000         4
3779  3780  2015-12-13  Surulere  Hot Pepperoni Feast   4000         4

          Time  Revenue  Snap
3775  09:22:58     6000  2003
3776  09:22:58     2000  2001
3777  09:22:59     8000  2004
3778  09:22:59     8000  2004
3779  09:23:00    16000  4004
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
3780  3781  2015-12-15     Lekki           Meatzaa   2000         3  09:23:02
3781  3782  2015-12-10   Gbagada       BBQ Chicken   4000         2  09:23:03
3782  3783  2015-12-10  Surulere      Extravaganza   2000         3  09:23:04
3783  3784  2015-12-11  Surulere  BBQ Philly Steak   4000         5  09:23:05
3784  3785  2015-12-15  Surulere   Pepperoni Feast   4000         1  09:23:05

      Revenue  Snap
3780     6000  2003
3781     8000  4002
3782     6000  2003
3783    20000  4005
3784     4000  4001
CHUNK BOSS
       S/N        Date    Branch    Pizza Sold  Price  Quantity      Time  \
3785  3786  2015-12-04  Surulere     Beef Suya   3000         4  09:23:05
3786  3787  2015-12-04   Gbagada     Margarita   4000         1  09:23:06
3787  3788  2015-12-11    Ibadan  Chicken Bali   2000         5  09:23:07
3788  3789  2015-12-12  Surulere   BBQ Chicken   4000         3  09:23:10
3789  3790  2015-12-07   Gbagada      Italiano   3000         1  09:23:12

      Revenue  Snap
3785    12000  3004
3786     4000  4001
3787    10000  2005
3788    12000  4003
3789     3000  3001
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
3790  3791  2015-12-14   Ibadan  Hot Pepperoni Feast   4000         2
3791  3792  2015-12-08  Gbagada       Pepperoni Suya   3000         5
3792  3793  2015-12-07  Gbagada          BBQ Chicken   4000         2
3793  3794  2015-12-03    Ikoyi             Italiano   3000         2
3794  3795  2015-12-14    Lekki            Beef Suya   3000         3

          Time  Revenue  Snap
3790  09:23:13     8000  4002
3791  09:23:13    15000  3005
3792  09:23:14     8000  4002
3793  09:23:15     6000  3002
3794  09:23:17     9000  3003
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
3795  3796  2015-12-13    Lekki            Margarita   4000         1
3796  3797  2015-12-12  Gbagada  Hot Pepperoni Feast   4000         4
3797  3798  2015-12-12   Ibadan            Beef Suya   3000         1
3798  3799  2015-12-08    Lekki       Chicken Legend   2000         5
3799  3800  2015-12-10  Gbagada         Extravaganza   2000         3

          Time  Revenue  Snap
3795  09:23:18     4000  4001
3796  09:23:18    16000  4004
3797  09:23:18     3000  3001
3798  09:23:19    10000  2005
3799  09:23:19     6000  2003
CHUNK BOSS
       S/N        Date   Branch    Pizza Sold  Price  Quantity      Time  \
3800  3801  2015-12-06  Gbagada     Beef Suya   3000         5  09:23:20
3801  3802  2015-12-14    Ikoyi   BBQ Chicken   4000         3  09:23:20
3802  3803  2015-12-10   Ibadan  Extravaganza   2000         1  09:23:21
3803  3804  2015-12-10    Ikoyi  Chicken Bali   2000         1  09:23:21
3804  3805  2015-12-11  Gbagada   BBQ Chicken   4000         2  09:23:22

      Revenue  Snap
3800    15000  3005
3801    12000  4003
3802     2000  2001
3803     2000  2001
3804     8000  4002
CHUNK BOSS
       S/N        Date  Branch        Pizza Sold  Price  Quantity      Time  \
3805  3806  2015-12-04   Lekki      Chicken Bali   2000         1  09:23:22
3806  3807  2015-12-06  Ibadan  BBQ Philly Steak   4000         3  09:23:24
3807  3808  2015-12-14   Ikoyi      Chicken Suya   4000         2  09:23:25
3808  3809  2015-12-06  Ibadan    Veggie Supreme   3000         4  09:23:26
3809  3810  2015-12-15  Ibadan      Chicken Bali   2000         4  09:23:28

      Revenue  Snap
3805     2000  2001
3806    12000  4003
3807     8000  4002
3808    12000  3004
3809     8000  2004
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
3810  3811  2015-12-08   Gbagada         Beef Suya   3000         5  09:23:30
3811  3812  2015-12-03    Ibadan    Pepperoni Suya   3000         1  09:23:31
3812  3813  2015-12-14    Ibadan        Hot Veggie   4000         1  09:23:31
3813  3814  2015-12-03  Surulere  BBQ Philly Steak   4000         2  09:23:34
3814  3815  2015-12-15  Surulere    Pepperoni Suya   3000         5  09:23:34

      Revenue  Snap
3810    15000  3005
3811     3000  3001
3812     4000  4001
3813     8000  4002
3814    15000  3005
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
3815  3816  2015-12-11   Gbagada       Hot Veggie   4000         3  09:23:37
3816  3817  2015-12-07  Surulere     Chicken Bali   2000         1  09:23:39
3817  3818  2015-12-11     Ikoyi     Chicken Suya   4000         4  09:23:39
3818  3819  2015-12-10  Surulere  Pepperoni Feast   4000         4  09:23:39
3819  3820  2015-12-09   Gbagada         Italiano   3000         3  09:23:40

      Revenue  Snap
3815    12000  4003
3816     2000  2001
3817    16000  4004
3818    16000  4004
3819     9000  3003
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
3820  3821  2015-12-05    Ikoyi  Hot Pepperoni Feast   4000         3
3821  3822  2015-12-09  Gbagada             Italiano   3000         4
3822  3823  2015-12-06    Lekki     BBQ Philly Steak   4000         5
3823  3824  2015-12-08    Lekki       Pepperoni Suya   3000         4
3824  3825  2015-12-13   Ibadan              Meatzaa   2000         1

          Time  Revenue  Snap
3820  09:23:40    12000  4003
3821  09:23:40    12000  3004
3822  09:23:42    20000  4005
3823  09:23:42    12000  3004
3824  09:23:43     2000  2001
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3825  3826  2015-12-03  Surulere              Meatzaa   2000         4
3826  3827  2015-12-03    Ibadan         Chicken Suya   4000         1
3827  3828  2015-12-11  Surulere        Chicken Feast   2000         5
3828  3829  2015-12-06     Lekki  Hot Pepperoni Feast   4000         5
3829  3830  2015-12-03     Lekki             Italiano   3000         5

          Time  Revenue  Snap
3825  09:23:43     8000  2004
3826  09:23:44     4000  4001
3827  09:23:46    10000  2005
3828  09:23:47    20000  4005
3829  09:23:47    15000  3005
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
3830  3831  2015-12-10    Lekki   Chicken Feast   2000         4  09:23:49
3831  3832  2015-12-11   Ibadan        Italiano   3000         3  09:23:50
3832  3833  2015-12-15    Ikoyi      Hot Veggie   4000         5  09:23:50
3833  3834  2015-12-06  Gbagada         Meatzaa   2000         2  09:23:51
3834  3835  2015-12-09    Ikoyi  Veggie Supreme   3000         4  09:23:52

      Revenue  Snap
3830     8000  2004
3831     9000  3003
3832    20000  4005
3833     4000  2002
3834    12000  3004
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
3835  3836  2015-12-13    Ibadan         Margarita   4000         5  09:23:54
3836  3837  2015-12-05   Gbagada        Hot Veggie   4000         3  09:23:54
3837  3838  2015-12-04     Lekki  BBQ Philly Steak   4000         4  09:23:55
3838  3839  2015-12-09  Surulere         Beef Suya   3000         5  09:23:55
3839  3840  2015-12-08     Ikoyi      Extravaganza   2000         1  09:23:55

      Revenue  Snap
3835    20000  4005
3836    12000  4003
3837    16000  4004
3838    15000  3005
3839     2000  2001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3840  3841  2015-12-08    Ibadan         Meatzaa   2000         4  09:23:55
3841  3842  2015-12-04   Gbagada         Meatzaa   2000         3  09:23:55
3842  3843  2015-12-14   Gbagada  Pepperoni Suya   3000         5  09:23:56
3843  3844  2015-12-03  Surulere       Beef Suya   3000         5  09:23:56
3844  3845  2015-12-07  Surulere   Chicken Feast   2000         2  09:23:58

      Revenue  Snap
3840     8000  2004
3841     6000  2003
3842    15000  3005
3843    15000  3005
3844     4000  2002
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3845  3846  2015-12-06    Ibadan       Margarita   4000         5  09:23:59
3846  3847  2015-12-13   Gbagada   Chicken Feast   2000         3  09:24:00
3847  3848  2015-12-04  Surulere  Pepperoni Suya   3000         2  09:24:00
3848  3849  2015-12-10    Ibadan        Italiano   3000         1  09:24:01
3849  3850  2015-12-06     Lekki     BBQ Chicken   4000         2  09:24:02

      Revenue  Snap
3845    20000  4005
3846     6000  2003
3847     6000  3002
3848     3000  3001
3849     8000  4002

CHUNK BOSS
       S/N        Date  Branch      Pizza Sold  Price  Quantity      Time  \
3850  3851  2015-12-15  Ibadan    Chicken Suya   4000         3  09:24:03
3851  3852  2015-12-06   Lekki  Pepperoni Suya   3000         5  09:24:03
3852  3853  2015-12-10   Ikoyi  Veggie Supreme   3000         2  09:24:03
3853  3854  2015-12-13   Lekki       Margarita   4000         2  09:24:04
3854  3855  2015-12-06   Ikoyi    Chicken Suya   4000         3  09:24:04

      Revenue  Snap
3850    12000  4003
3851    15000  3005
3852     6000  3002
3853     8000  4002
3854    12000  4003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3855  3856  2015-12-11     Lekki       Pepperoni Suya   3000         3
3856  3857  2015-12-05     Ikoyi          BBQ Chicken   4000         2
3857  3858  2015-12-06    Ibadan  Hot Pepperoni Feast   4000         1
3858  3859  2015-12-07   Gbagada         Extravaganza   2000         3
3859  3860  2015-12-08  Surulere  Hot Pepperoni Feast   4000         3

          Time  Revenue  Snap
3855  09:24:04     9000  3003
3856  09:24:05     8000  4002
3857  09:24:06     4000  4001
3858  09:24:06     6000  2003
3859  09:24:06    12000  4003
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
3860  3861  2015-12-05     Ikoyi      Chicken Bali   2000         4  09:24:06
3861  3862  2015-12-06  Surulere         Beef Suya   3000         5  09:24:07
3862  3863  2015-12-04   Gbagada      Chicken Suya   4000         3  09:24:07
3863  3864  2015-12-06     Ikoyi           Meatzaa   2000         5  09:24:09
3864  3865  2015-12-05  Surulere  BBQ Philly Steak   4000         3  09:24:10

      Revenue  Snap
3860     8000  2004
3861    15000  3005
3862    12000  4003
3863    10000  2005
3864    12000  4003
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
3865  3866  2015-12-03  Surulere         Italiano   3000         4  09:24:10
3866  3867  2015-12-08    Ibadan     Chicken Bali   2000         1  09:24:11
3867  3868  2015-12-11     Ikoyi          Meatzaa   2000         4  09:24:12
3868  3869  2015-12-03     Ikoyi       Hot Veggie   4000         1  09:24:12
3869  3870  2015-12-14  Surulere  Pepperoni Feast   4000         4  09:24:12

      Revenue  Snap
3865    12000  3004
3866     2000  2001
3867     8000  2004
3868     4000  4001
3869    16000  4004
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
3870  3871  2015-12-04   Ibadan        Italiano   3000         4  09:24:12
3871  3872  2015-12-11    Ikoyi         Meatzaa   2000         5  09:24:12
3872  3873  2015-12-08  Gbagada  Pepperoni Suya   3000         1  09:24:13
3873  3874  2015-12-05    Ikoyi      Hot Veggie   4000         1  09:24:13
3874  3875  2015-12-11   Ibadan    Extravaganza   2000         1  09:24:14

      Revenue  Snap
3870    12000  3004
3871    10000  2005
3872     3000  3001
3873     4000  4001
3874     2000  2001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3875  3876  2015-12-08     Ikoyi  Pepperoni Suya   3000         1  09:24:14
3876  3877  2015-12-05    Ibadan     BBQ Chicken   4000         3  09:24:14
3877  3878  2015-12-05     Lekki     BBQ Chicken   4000         3  09:24:14
3878  3879  2015-12-05     Ikoyi       Beef Suya   3000         3  09:24:16
3879  3880  2015-12-10  Surulere    Chicken Suya   4000         5  09:24:16

      Revenue  Snap
3875     3000  3001
3876    12000  4003
3877    12000  4003
3878     9000  3003
3879    20000  4005
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3880  3881  2015-12-12   Gbagada  Pepperoni Suya   3000         5  09:24:17
3881  3882  2015-12-11     Lekki    Chicken Bali   2000         5  09:24:18
3882  3883  2015-12-14   Gbagada  Chicken Legend   2000         1  09:24:18
3883  3884  2015-12-04  Surulere         Meatzaa   2000         1  09:24:18
3884  3885  2015-12-09  Surulere    Extravaganza   2000         3  09:24:19

      Revenue  Snap
3880    15000  3005
3881    10000  2005
3882     2000  2001
3883     2000  2001
3884     6000  2003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3885  3886  2015-12-08     Ikoyi     BBQ Philly Steak   4000         2
3886  3887  2015-12-05     Ikoyi  Hot Pepperoni Feast   4000         4
3887  3888  2015-12-06  Surulere         Chicken Suya   4000         4
3888  3889  2015-12-07     Ikoyi            Beef Suya   3000         5
3889  3890  2015-12-10   Gbagada              Meatzaa   2000         1

          Time  Revenue  Snap
3885  09:24:20     8000  4002
3886  09:24:20    16000  4004
3887  09:24:20    16000  4004
3888  09:24:21    15000  3005
3889  09:24:22     2000  2001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3890  3891  2015-12-15     Lekki  Chicken Legend   2000         2  09:24:23
3891  3892  2015-12-05   Gbagada    Chicken Suya   4000         5  09:24:24
3892  3893  2015-12-14  Surulere  Pepperoni Suya   3000         2  09:24:24
3893  3894  2015-12-05  Surulere     BBQ Chicken   4000         1  09:24:26
3894  3895  2015-12-03     Ikoyi    Chicken Bali   2000         5  09:24:26

      Revenue  Snap
3890     4000  2002
3891    20000  4005
3892     6000  3002
3893     4000  4001
3894    10000  2005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3895  3896  2015-12-11    Ibadan       Chicken Legend   2000         5
3896  3897  2015-12-10     Lekki  Hot Pepperoni Feast   4000         1
3897  3898  2015-12-07  Surulere           Hot Veggie   4000         5
3898  3899  2015-12-14     Lekki         Chicken Suya   4000         4
3899  3900  2015-12-09  Surulere              Meatzaa   2000         3

          Time  Revenue  Snap
3895  09:24:27    10000  2005
3896  09:24:27     4000  4001
3897  09:24:29    20000  4005
3898  09:24:30    16000  4004
3899  09:24:31     6000  2003
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3900  3901  2015-12-12     Ikoyi     BBQ Chicken   4000         1  09:24:32
3901  3902  2015-12-08     Lekki  Pepperoni Suya   3000         3  09:24:32
3902  3903  2015-12-06  Surulere  Pepperoni Suya   3000         2  09:24:32
3903  3904  2015-12-14     Lekki  Veggie Supreme   3000         3  09:24:34
3904  3905  2015-12-09  Surulere       Beef Suya   3000         1  09:24:34

      Revenue  Snap
3900     4000  4001
3901     9000  3003
3902     6000  3002
3903     9000  3003
3904     3000  3001
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
3905  3906  2015-12-05    Lekki         Extravaganza   2000         5
3906  3907  2015-12-06  Gbagada         Chicken Suya   4000         5
3907  3908  2015-12-15   Ibadan         Chicken Bali   2000         4
3908  3909  2015-12-13   Ibadan  Hot Pepperoni Feast   4000         2
3909  3910  2015-12-11    Ikoyi              Meatzaa   2000         1

          Time  Revenue  Snap
3905  09:24:40    10000  2005
3906  09:24:41    20000  4005
3907  09:24:42     8000  2004
3908  09:24:44     8000  4002
3909  09:24:44     2000  2001
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
3910  3911  2015-12-10  Gbagada         Meatzaa   2000         1  09:24:44
3911  3912  2015-12-12   Ibadan    Chicken Bali   2000         4  09:24:45
3912  3913  2015-12-06   Ibadan  Veggie Supreme   3000         3  09:24:48
3913  3914  2015-12-06  Gbagada    Extravaganza   2000         3  09:24:48
3914  3915  2015-12-07   Ibadan    Extravaganza   2000         5  09:24:49

      Revenue  Snap
3910     2000  2001
3911     8000  2004
3912     9000  3003
3913     6000  2003
3914    10000  2005
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
3915  3916  2015-12-07   Gbagada       BBQ Chicken   4000         5  09:24:49
3916  3917  2015-12-11  Surulere    Chicken Legend   2000         3  09:24:50
3917  3918  2015-12-08    Ibadan  BBQ Philly Steak   4000         4  09:24:53
3918  3919  2015-12-11    Ibadan        Hot Veggie   4000         4  09:24:54
3919  3920  2015-12-10     Lekki    Veggie Supreme   3000         4  09:24:55

      Revenue  Snap
3915    20000  4005
3916     6000  2003
3917    16000  4004
3918    16000  4004
3919    12000  3004
CHUNK BOSS
       S/N        Date  Branch           Pizza Sold  Price  Quantity  \
3920  3921  2015-12-14   Lekki     BBQ Philly Steak   4000         3
3921  3922  2015-12-04   Lekki            Beef Suya   3000         5
3922  3923  2015-12-15   Lekki  Hot Pepperoni Feast   4000         5
3923  3924  2015-12-04  Ibadan            Margarita   4000         3
3924  3925  2015-12-08   Ikoyi        Chicken Feast   2000         2

          Time  Revenue  Snap
3920  09:24:55    12000  4003
3921  09:24:56    15000  3005
3922  09:24:57    20000  4005
3923  09:24:58    12000  4003
3924  09:24:58     4000  2002
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3925  3926  2015-12-07     Ikoyi  Veggie Supreme   3000         3  09:24:59
3926  3927  2015-12-15     Ikoyi  Chicken Legend   2000         5  09:25:00
3927  3928  2015-12-05  Surulere    Chicken Bali   2000         3  09:25:00
3928  3929  2015-12-12  Surulere  Veggie Supreme   3000         1  09:25:02
3929  3930  2015-12-12   Gbagada    Extravaganza   2000         1  09:25:02

      Revenue  Snap
3925     9000  3003
3926    10000  2005
3927     6000  2003
3928     3000  3001
3929     2000  2001
CHUNK BOSS
       S/N        Date    Branch    Pizza Sold  Price  Quantity      Time  \
3930  3931  2015-12-06   Gbagada    Hot Veggie   4000         4  09:25:06
3931  3932  2015-12-04    Ibadan       Meatzaa   2000         1  09:25:07
3932  3933  2015-12-11    Ibadan       Meatzaa   2000         2  09:25:09
3933  3934  2015-12-15  Surulere  Chicken Bali   2000         1  09:25:10
3934  3935  2015-12-15    Ibadan   BBQ Chicken   4000         2  09:25:10

      Revenue  Snap
3930    16000  4004
3931     2000  2001
3932     4000  2002
3933     2000  2001
3934     8000  4002
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3935  3936  2015-12-08  Surulere     BBQ Chicken   4000         1  09:25:10
3936  3937  2015-12-13   Gbagada       Margarita   4000         3  09:25:12
3937  3938  2015-12-15   Gbagada  Chicken Legend   2000         2  09:25:13
3938  3939  2015-12-12     Lekki       Margarita   4000         4  09:25:13
3939  3940  2015-12-15    Ibadan      Hot Veggie   4000         5  09:25:13

      Revenue  Snap
3935     4000  4001
3936    12000  4003
3937     4000  2002
3938    16000  4004
3939    20000  4005
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
3940  3941  2015-12-10     Lekki      Extravaganza   2000         5  09:25:13
3941  3942  2015-12-06   Gbagada  BBQ Philly Steak   4000         3  09:25:15
3942  3943  2015-12-12    Ibadan      Chicken Bali   2000         4  09:25:19
3943  3944  2015-12-06     Lekki     Chicken Feast   2000         3  09:25:19
3944  3945  2015-12-15  Surulere    Pepperoni Suya   3000         2  09:25:19

      Revenue  Snap
3940    10000  2005
3941    12000  4003
3942     8000  2004
3943     6000  2003
3944     6000  3002
CHUNK BOSS
       S/N        Date  Branch        Pizza Sold  Price  Quantity      Time  \
3945  3946  2015-12-07   Ikoyi  BBQ Philly Steak   4000         5  09:25:20
3946  3947  2015-12-06   Lekki         Beef Suya   3000         1  09:25:21
3947  3948  2015-12-10   Lekki    Chicken Legend   2000         2  09:25:22
3948  3949  2015-12-13  Ibadan    Chicken Legend   2000         2  09:25:23
3949  3950  2015-12-04   Ikoyi   Pepperoni Feast   4000         1  09:25:24

      Revenue  Snap
3945    20000  4005
3946     3000  3001
3947     4000  2002
3948     4000  2002
3949     4000  4001
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3950  3951  2015-12-14   Gbagada            Margarita   4000         5
3951  3952  2015-12-15  Surulere            Margarita   4000         1
3952  3953  2015-12-12     Ikoyi      Pepperoni Feast   4000         5
3953  3954  2015-12-10     Lekki  Hot Pepperoni Feast   4000         2
3954  3955  2015-12-08   Gbagada       Pepperoni Suya   3000         2

          Time  Revenue  Snap
3950  09:25:26    20000  4005
3951  09:25:32     4000  4001
3952  09:25:33    20000  4005
3953  09:25:33     8000  4002
3954  09:25:33     6000  3002

CHUNK BOSS
       S/N        Date  Branch        Pizza Sold  Price  Quantity      Time  \
3955  3956  2015-12-09  Ibadan       BBQ Chicken   4000         2  09:25:34
3956  3957  2015-12-06   Lekki    Veggie Supreme   3000         1  09:25:35
3957  3958  2015-12-05  Ibadan         Beef Suya   3000         5  09:25:38
3958  3959  2015-12-10  Ibadan  BBQ Philly Steak   4000         1  09:25:39
3959  3960  2015-12-09   Lekki      Chicken Bali   2000         2  09:25:40

      Revenue  Snap
3955     8000  4002
3956     3000  3001
3957    15000  3005
3958     4000  4001
3959     4000  2002
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
3960  3961  2015-12-11     Lekki      BBQ Chicken   4000         4  09:25:43
3961  3962  2015-12-13     Ikoyi  Pepperoni Feast   4000         3  09:25:47
3962  3963  2015-12-09    Ibadan   Chicken Legend   2000         4  09:25:50
3963  3964  2015-12-15  Surulere     Chicken Suya   4000         1  09:25:51
3964  3965  2015-12-14     Lekki   Chicken Legend   2000         3  09:25:53

      Revenue  Snap
3960    16000  4004
3961    12000  4003
3962     8000  2004
3963     4000  4001
3964     6000  2003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3965  3966  2015-12-12   Gbagada         Chicken Bali   2000         1
3966  3967  2015-12-05  Surulere       Pepperoni Suya   3000         1
3967  3968  2015-12-03    Ibadan             Italiano   3000         5
3968  3969  2015-12-09  Surulere            Margarita   4000         4
3969  3970  2015-12-15     Lekki  Hot Pepperoni Feast   4000         4

          Time  Revenue  Snap
3965  09:25:53     2000  2001
3966  09:25:54     3000  3001
3967  09:25:55    15000  3005
3968  09:25:55    16000  4004
3969  09:25:55    16000  4004
CHUNK BOSS
       S/N        Date   Branch     Pizza Sold  Price  Quantity      Time  \
3970  3971  2015-12-14  Gbagada   Extravaganza   2000         2  09:25:55
3971  3972  2015-12-07  Gbagada  Chicken Feast   2000         1  09:25:56
3972  3973  2015-12-10  Gbagada      Beef Suya   3000         1  09:25:58
3973  3974  2015-12-03    Ikoyi   Chicken Bali   2000         5  09:25:58
3974  3975  2015-12-12  Gbagada      Beef Suya   3000         2  09:25:59

      Revenue  Snap
3970     4000  2002
3971     2000  2001
3972     3000  3001
3973    10000  2005
3974     6000  3002
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3975  3976  2015-12-11    Ibadan    Chicken Suya   4000         3  09:25:59
3976  3977  2015-12-05  Surulere  Veggie Supreme   3000         2  09:26:00
3977  3978  2015-12-12     Ikoyi       Margarita   4000         5  09:26:01
3978  3979  2015-12-11    Ibadan       Beef Suya   3000         4  09:26:02
3979  3980  2015-12-07     Lekki       Margarita   4000         4  09:26:06

      Revenue  Snap
3975    12000  4003
3976     6000  3002
3977    20000  4005
3978    12000  3004
3979    16000  4004
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3980  3981  2015-12-08  Surulere       Beef Suya   3000         5  09:26:07
3981  3982  2015-12-05     Lekki  Chicken Legend   2000         2  09:26:08
3982  3983  2015-12-08   Gbagada       Margarita   4000         2  09:26:09
3983  3984  2015-12-12     Lekki    Extravaganza   2000         4  09:26:09
3984  3985  2015-12-06     Lekki   Chicken Feast   2000         5  09:26:10

      Revenue  Snap
3980    15000  3005
3981     4000  2002
3982     8000  4002
3983     8000  2004
3984    10000  2005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3985  3986  2015-12-15     Ikoyi         Chicken Suya   4000         2
3986  3987  2015-12-12   Gbagada       Veggie Supreme   3000         5
3987  3988  2015-12-13     Lekki     BBQ Philly Steak   4000         3
3988  3989  2015-12-10  Surulere  Hot Pepperoni Feast   4000         4
3989  3990  2015-12-15  Surulere         Chicken Bali   2000         4

          Time  Revenue  Snap
3985  09:26:12     8000  4002
3986  09:26:13    15000  3005
3987  09:26:16    12000  4003
3988  09:26:17    16000  4004
3989  09:26:18     8000  2004
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
3990  3991  2015-12-09   Gbagada       Margarita   4000         2  09:26:19
3991  3992  2015-12-08  Surulere  Veggie Supreme   3000         4  09:26:20
3992  3993  2015-12-06     Ikoyi      Hot Veggie   4000         2  09:26:20
3993  3994  2015-12-11   Gbagada  Veggie Supreme   3000         3  09:26:20
3994  3995  2015-12-15     Ikoyi  Chicken Legend   2000         2  09:26:20

      Revenue  Snap
3990     8000  4002
3991    12000  3004
3992     8000  4002
3993     9000  3003
3994     4000  2002
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
3995  3996  2015-12-12    Ibadan       Pepperoni Suya   3000         5
3996  3997  2015-12-12   Gbagada        Chicken Feast   2000         3
3997  3998  2015-12-12     Ikoyi     BBQ Philly Steak   4000         1
3998  3999  2015-12-12   Gbagada       Pepperoni Suya   3000         1
3999  4000  2015-12-05  Surulere  Hot Pepperoni Feast   4000         2

          Time  Revenue  Snap
3995  09:26:22    15000  3005
3996  09:26:24     6000  2003
3997  09:26:25     4000  4001
3998  09:26:28     3000  3001
3999  09:26:28     8000  4002
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4000  4001  2015-12-13     Ikoyi           Hot Veggie   4000         2
4001  4002  2015-12-15    Ibadan             Italiano   3000         2
4002  4003  2015-12-14     Lekki       Chicken Legend   2000         3
4003  4004  2015-12-11    Ibadan         Chicken Suya   4000         5
4004  4005  2015-12-04  Surulere  Hot Pepperoni Feast   4000         1

          Time  Revenue  Snap
4000  09:26:29     8000  4002
4001  09:26:30     6000  3002
4002  09:26:30     6000  2003
4003  09:26:30    20000  4005
4004  09:26:31     4000  4001
CHUNK BOSS
       S/N        Date   Branch    Pizza Sold  Price  Quantity      Time  \
4005  4006  2015-12-12   Ibadan   BBQ Chicken   4000         2  09:26:31
4006  4007  2015-12-06  Gbagada  Chicken Bali   2000         2  09:26:32
4007  4008  2015-12-11  Gbagada  Chicken Suya   4000         1  09:26:33
4008  4009  2015-12-11  Gbagada  Extravaganza   2000         3  09:26:33
4009  4010  2015-12-06    Lekki  Chicken Bali   2000         4  09:26:34

      Revenue  Snap
4005     8000  4002
4006     4000  2002
4007     4000  4001
4008     6000  2003
4009     8000  2004
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
4010  4011  2015-12-15     Lekki        Hot Veggie   4000         4  09:26:36
4011  4012  2015-12-15   Gbagada       BBQ Chicken   4000         5  09:26:36
4012  4013  2015-12-08    Ibadan  BBQ Philly Steak   4000         3  09:26:39
4013  4014  2015-12-10     Ikoyi    Veggie Supreme   3000         3  09:26:40
4014  4015  2015-12-07  Surulere   Pepperoni Feast   4000         2  09:26:49

      Revenue  Snap
4010    16000  4004
4011    20000  4005
4012    12000  4003
4013     9000  3003
4014     8000  4002
CHUNK BOSS
       S/N        Date    Branch     Pizza Sold  Price  Quantity      Time  \
4015  4016  2015-12-03   Gbagada     Hot Veggie   4000         5  09:26:51
4016  4017  2015-12-08     Ikoyi   Extravaganza   2000         1  09:26:51
4017  4018  2015-12-04  Surulere       Italiano   3000         1  09:26:51
4018  4019  2015-12-06     Lekki   Extravaganza   2000         1  09:26:52
4019  4020  2015-12-13    Ibadan  Chicken Feast   2000         1  09:26:52

      Revenue  Snap
4015    20000  4005
4016     2000  2001
4017     3000  3001
4018     2000  2001
4019     2000  2001
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4020  4021  2015-12-12     Ikoyi  Hot Pepperoni Feast   4000         5
4021  4022  2015-12-03  Surulere              Meatzaa   2000         2
4022  4023  2015-12-12     Lekki         Extravaganza   2000         3
4023  4024  2015-12-07    Ibadan       Veggie Supreme   3000         2
4024  4025  2015-12-08  Surulere       Pepperoni Suya   3000         5

          Time  Revenue  Snap
4020  09:26:53    20000  4005
4021  09:26:54     4000  2002
4022  09:26:54     6000  2003
4023  09:26:54     6000  3002
4024  09:26:55    15000  3005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4025  4026  2015-12-06  Surulere        Chicken Feast   2000         2
4026  4027  2015-12-03     Ikoyi         Chicken Suya   4000         4
4027  4028  2015-12-07     Ikoyi      Pepperoni Feast   4000         2
4028  4029  2015-12-07    Ibadan  Hot Pepperoni Feast   4000         1
4029  4030  2015-12-07  Surulere         Chicken Bali   2000         5

          Time  Revenue  Snap
4025  09:26:57     4000  2002
4026  09:26:58    16000  4004
4027  09:26:58     8000  4002
4028  09:26:59     4000  4001
4029  09:27:00    10000  2005
CHUNK BOSS
       S/N        Date  Branch           Pizza Sold  Price  Quantity  \
4030  4031  2015-12-13   Ikoyi          BBQ Chicken   4000         4
4031  4032  2015-12-03  Ibadan       Pepperoni Suya   3000         5
4032  4033  2015-12-09   Lekki           Hot Veggie   4000         3
4033  4034  2015-12-05  Ibadan  Hot Pepperoni Feast   4000         4
4034  4035  2015-12-04   Ikoyi             Italiano   3000         4

          Time  Revenue  Snap
4030  09:27:01    16000  4004
4031  09:27:01    15000  3005
4032  09:27:02    12000  4003
4033  09:27:02    16000  4004
4034  09:27:02    12000  3004
CHUNK BOSS
       S/N        Date   Branch     Pizza Sold  Price  Quantity      Time  \
4035  4036  2015-12-03    Lekki  Chicken Feast   2000         4  09:27:03
4036  4037  2015-12-15    Ikoyi     Hot Veggie   4000         4  09:27:09
4037  4038  2015-12-13    Ikoyi     Hot Veggie   4000         4  09:27:09
4038  4039  2015-12-12  Gbagada        Meatzaa   2000         1  09:27:09
4039  4040  2015-12-10  Gbagada  Chicken Feast   2000         4  09:27:11

      Revenue  Snap
4035     8000  2004
4036    16000  4004
4037    16000  4004
4038     2000  2001
4039     8000  2004
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
4040  4041  2015-12-14    Lekki   Chicken Feast   2000         2  09:27:12
4041  4042  2015-12-15    Lekki         Meatzaa   2000         3  09:27:13
4042  4043  2015-12-08  Gbagada    Chicken Suya   4000         1  09:27:13
4043  4044  2015-12-14  Gbagada   Chicken Feast   2000         3  09:27:13
4044  4045  2015-12-10    Ikoyi  Pepperoni Suya   3000         4  09:27:14

      Revenue  Snap
4040     4000  2002
4041     6000  2003
4042     4000  4001
4043     6000  2003
4044    12000  3004
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4045  4046  2015-12-11     Lekki       Pepperoni Suya   3000         3
4046  4047  2015-12-10  Surulere      Pepperoni Feast   4000         1
4047  4048  2015-12-12     Lekki  Hot Pepperoni Feast   4000         3
4048  4049  2015-12-07    Ibadan       Pepperoni Suya   3000         2
4049  4050  2015-12-04   Gbagada     BBQ Philly Steak   4000         1

          Time  Revenue  Snap
4045  09:27:14     9000  3003
4046  09:27:15     4000  4001
4047  09:27:15    12000  4003
4048  09:27:15     6000  3002
4049  09:27:15     4000  4001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4050  4051  2015-12-12   Gbagada    Chicken Bali   2000         2  09:27:16
4051  4052  2015-12-05     Ikoyi         Meatzaa   2000         2  09:27:17
4052  4053  2015-12-10   Gbagada  Pepperoni Suya   3000         3  09:27:17
4053  4054  2015-12-14  Surulere    Chicken Bali   2000         5  09:27:18
4054  4055  2015-12-11  Surulere    Chicken Bali   2000         3  09:27:18

      Revenue  Snap
4050     4000  2002
4051     4000  2002
4052     9000  3003
4053    10000  2005
4054     6000  2003

CHUNK BOSS
       S/N        Date    Branch     Pizza Sold  Price  Quantity      Time  \
4055  4056  2015-12-03     Lekki   Extravaganza   2000         3  09:27:20
4056  4057  2015-12-15  Surulere     Hot Veggie   4000         4  09:27:20
4057  4058  2015-12-07  Surulere        Meatzaa   2000         4  09:27:21
4058  4059  2015-12-04     Ikoyi  Chicken Feast   2000         2  09:27:22
4059  4060  2015-12-03     Lekki    BBQ Chicken   4000         4  09:27:23

      Revenue  Snap
4055     6000  2003
4056    16000  4004
4057     8000  2004
4058     4000  2002
4059    16000  4004
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
4060  4061  2015-12-03   Gbagada       Hot Veggie   4000         5  09:27:23
4061  4062  2015-12-03     Ikoyi  Pepperoni Feast   4000         1  09:27:23
4062  4063  2015-12-07  Surulere         Italiano   3000         1  09:27:24
4063  4064  2015-12-09     Lekki     Chicken Bali   2000         4  09:27:24
4064  4065  2015-12-04  Surulere        Beef Suya   3000         3  09:27:24

      Revenue  Snap
4060    20000  4005
4061     4000  4001
4062     3000  3001
4063     8000  2004
4064     9000  3003
CHUNK BOSS
       S/N        Date Branch        Pizza Sold  Price  Quantity      Time  \
4065  4066  2015-12-15  Lekki    Pepperoni Suya   3000         1  09:27:25
4066  4067  2015-12-07  Ikoyi   Pepperoni Feast   4000         5  09:27:25
4067  4068  2015-12-03  Lekki    Veggie Supreme   3000         4  09:27:26
4068  4069  2015-12-04  Ikoyi     Chicken Feast   2000         4  09:27:29
4069  4070  2015-12-11  Ikoyi  BBQ Philly Steak   4000         3  09:27:30

      Revenue  Snap
4065     3000  3001
4066    20000  4005
4067    12000  3004
4068     8000  2004
4069    12000  4003
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4070  4071  2015-12-14  Surulere    Chicken Bali   2000         1  09:27:30
4071  4072  2015-12-07     Lekki      Hot Veggie   4000         2  09:27:31
4072  4073  2015-12-04   Gbagada    Chicken Suya   4000         5  09:27:31
4073  4074  2015-12-03   Gbagada     BBQ Chicken   4000         5  09:27:32
4074  4075  2015-12-09   Gbagada  Veggie Supreme   3000         3  09:27:33

      Revenue  Snap
4070     2000  2001
4071     8000  4002
4072    20000  4005
4073    20000  4005
4074     9000  3003
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4075  4076  2015-12-07   Gbagada     BBQ Chicken   4000         1  09:27:34
4076  4077  2015-12-15     Ikoyi         Meatzaa   2000         3  09:27:34
4077  4078  2015-12-14  Surulere       Beef Suya   3000         3  09:27:35
4078  4079  2015-12-15     Ikoyi  Chicken Legend   2000         2  09:27:36
4079  4080  2015-12-11    Ibadan        Italiano   3000         1  09:27:36

      Revenue  Snap
4075     4000  4001
4076     6000  2003
4077     9000  3003
4078     4000  2002
4079     3000  3001
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
4080  4081  2015-12-11  Surulere          Meatzaa   2000         2  09:27:38
4081  4082  2015-12-09   Gbagada         Italiano   3000         4  09:27:38
4082  4083  2015-12-10     Ikoyi       Hot Veggie   4000         3  09:27:39
4083  4084  2015-12-11    Ibadan  Pepperoni Feast   4000         3  09:27:44
4084  4085  2015-12-09   Gbagada         Italiano   3000         1  09:27:45

      Revenue  Snap
4080     4000  2002
4081    12000  3004
4082    12000  4003
4083    12000  4003
4084     3000  3001
CHUNK BOSS
       S/N        Date  Branch           Pizza Sold  Price  Quantity  \
4085  4086  2015-12-12   Ikoyi        Chicken Feast   2000         4
4086  4087  2015-12-03   Ikoyi  Hot Pepperoni Feast   4000         5
4087  4088  2015-12-11  Ibadan          BBQ Chicken   4000         2
4088  4089  2015-12-11  Ibadan            Margarita   4000         2
4089  4090  2015-12-15   Ikoyi     BBQ Philly Steak   4000         5

          Time  Revenue  Snap
4085  09:27:46     8000  2004
4086  09:27:47    20000  4005
4087  09:27:47     8000  4002
4088  09:27:48     8000  4002
4089  09:27:48    20000  4005
CHUNK BOSS
       S/N        Date    Branch    Pizza Sold  Price  Quantity      Time  \
4090  4091  2015-12-15  Surulere    Hot Veggie   4000         2  09:27:49
4091  4092  2015-12-12    Ibadan     Beef Suya   3000         1  09:27:51
4092  4093  2015-12-12    Ibadan     Beef Suya   3000         2  09:27:51
4093  4094  2015-12-09   Gbagada  Extravaganza   2000         1  09:27:53
4094  4095  2015-12-15   Gbagada     Beef Suya   3000         2  09:27:55

      Revenue  Snap
4090     8000  4002
4091     3000  3001
4092     6000  3002
4093     2000  2001
4094     6000  3002
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
4095  4096  2015-12-06     Ikoyi     Chicken Bali   2000         2  09:27:55
4096  4097  2015-12-07   Gbagada   Veggie Supreme   3000         5  09:27:58
4097  4098  2015-12-05     Lekki     Chicken Bali   2000         1  09:27:59
4098  4099  2015-12-10  Surulere    Chicken Feast   2000         3  09:28:01
4099  4100  2015-12-12     Ikoyi  Pepperoni Feast   4000         3  09:28:01

      Revenue  Snap
4095     4000  2002
4096    15000  3005
4097     2000  2001
4098     6000  2003
4099    12000  4003
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
4100  4101  2015-12-06   Gbagada   Pepperoni Feast   4000         2  09:28:01
4101  4102  2015-12-06  Surulere          Italiano   3000         3  09:28:01
4102  4103  2015-12-05   Gbagada       BBQ Chicken   4000         5  09:28:03
4103  4104  2015-12-08  Surulere    Pepperoni Suya   3000         4  09:28:03
4104  4105  2015-12-03  Surulere  BBQ Philly Steak   4000         4  09:28:04

      Revenue  Snap
4100     8000  4002
4101     9000  3003
4102    20000  4005
4103    12000  3004
4104    16000  4004
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
4105  4106  2015-12-07    Lekki              Meatzaa   2000         2
4106  4107  2015-12-08  Gbagada  Hot Pepperoni Feast   4000         5
4107  4108  2015-12-06    Ikoyi        Chicken Feast   2000         1
4108  4109  2015-12-15    Ikoyi          BBQ Chicken   4000         1
4109  4110  2015-12-05  Gbagada       Pepperoni Suya   3000         5

          Time  Revenue  Snap
4105  09:28:05     4000  2002
4106  09:28:08    20000  4005
4107  09:28:10     2000  2001
4108  09:28:10     4000  4001
4109  09:28:11    15000  3005
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
4110  4111  2015-12-09   Ibadan        Italiano   3000         3  09:28:11
4111  4112  2015-12-12    Lekki         Meatzaa   2000         3  09:28:12
4112  4113  2015-12-10  Gbagada  Pepperoni Suya   3000         3  09:28:13
4113  4114  2015-12-07   Ibadan  Veggie Supreme   3000         5  09:28:13
4114  4115  2015-12-06  Gbagada  Pepperoni Suya   3000         4  09:28:13

      Revenue  Snap
4110     9000  3003
4111     6000  2003
4112     9000  3003
4113    15000  3005
4114    12000  3004
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
4115  4116  2015-12-11  Surulere         Beef Suya   3000         5  09:28:16
4116  4117  2015-12-12   Gbagada         Margarita   4000         5  09:28:17
4117  4118  2015-12-05     Ikoyi     Chicken Feast   2000         3  09:28:17
4118  4119  2015-12-08     Lekki           Meatzaa   2000         5  09:28:19
4119  4120  2015-12-14   Gbagada  BBQ Philly Steak   4000         5  09:28:20

      Revenue  Snap
4115    15000  3005
4116    20000  4005
4117     6000  2003
4118    10000  2005
4119    20000  4005
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4120  4121  2015-12-04   Gbagada    Extravaganza   2000         3  09:28:21
4121  4122  2015-12-04  Surulere      Hot Veggie   4000         4  09:28:23
4122  4123  2015-12-15  Surulere  Pepperoni Suya   3000         1  09:28:25
4123  4124  2015-12-11  Surulere    Chicken Bali   2000         2  09:28:25
4124  4125  2015-12-14   Gbagada         Meatzaa   2000         5  09:28:26

      Revenue  Snap
4120     6000  2003
4121    16000  4004
4122     3000  3001
4123     4000  2002
4124    10000  2005
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
4125  4126  2015-12-08  Gbagada     Chicken Feast   2000         3  09:28:26
4126  4127  2015-12-15  Gbagada    Chicken Legend   2000         1  09:28:27
4127  4128  2015-12-09    Ikoyi  BBQ Philly Steak   4000         5  09:28:28
4128  4129  2015-12-15   Ibadan    Chicken Legend   2000         4  09:28:28
4129  4130  2015-12-13    Ikoyi    Chicken Legend   2000         2  09:28:29

      Revenue  Snap
4125     6000  2003
4126     2000  2001
4127    20000  4005
4128     8000  2004
4129     4000  2002
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4130  4131  2015-12-11  Surulere            Margarita   4000         2
4131  4132  2015-12-06   Gbagada     BBQ Philly Steak   4000         3
4132  4133  2015-12-12     Ikoyi            Margarita   4000         1
4133  4134  2015-12-04    Ibadan             Italiano   3000         2
4134  4135  2015-12-08    Ibadan  Hot Pepperoni Feast   4000         4

          Time  Revenue  Snap
4130  09:28:32     8000  4002
4131  09:28:32    12000  4003
4132  09:28:33     4000  4001
4133  09:28:34     6000  3002
4134  09:28:34    16000  4004
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
4135  4136  2015-12-12    Lekki    Pepperoni Suya   3000         1  09:28:35
4136  4137  2015-12-06   Ibadan    Pepperoni Suya   3000         5  09:28:35
4137  4138  2015-12-09  Gbagada    Pepperoni Suya   3000         4  09:28:36
4138  4139  2015-12-08    Ikoyi    Pepperoni Suya   3000         5  09:28:37
4139  4140  2015-12-06  Gbagada  BBQ Philly Steak   4000         3  09:28:39

      Revenue  Snap
4135     3000  3001
4136    15000  3005
4137    12000  3004
4138    15000  3005
4139    12000  4003
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
4140  4141  2015-12-14     Ikoyi     Chicken Bali   2000         5  09:28:39
4141  4142  2015-12-13    Ibadan        Beef Suya   3000         4  09:28:41
4142  4143  2015-12-10  Surulere   Veggie Supreme   3000         3  09:28:41
4143  4144  2015-12-09   Gbagada  Pepperoni Feast   4000         3  09:28:42
4144  4145  2015-12-13     Ikoyi     Chicken Bali   2000         2  09:28:43

      Revenue  Snap
4140    10000  2005
4141    12000  3004
4142     9000  3003
4143    12000  4003
4144     4000  2002
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
4145  4146  2015-12-07   Gbagada  Pepperoni Feast   4000         2  09:28:44
4146  4147  2015-12-07     Ikoyi  Pepperoni Feast   4000         1  09:28:45
4147  4148  2015-12-15   Gbagada         Italiano   3000         3  09:28:45
4148  4149  2015-12-04  Surulere     Chicken Bali   2000         1  09:28:46
4149  4150  2015-12-06  Surulere        Margarita   4000         3  09:28:46

      Revenue  Snap
4145     8000  4002
4146     4000  4001
4147     9000  3003
4148     2000  2001
4149    12000  4003
CHUNK BOSS

       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
4150  4151  2015-12-04   Gbagada       Hot Veggie   4000         3  09:28:50
4151  4152  2015-12-11     Ikoyi         Italiano   3000         3  09:28:53
4152  4153  2015-12-13  Surulere     Chicken Bali   2000         2  09:28:53
4153  4154  2015-12-10    Ibadan  Pepperoni Feast   4000         5  09:28:54
4154  4155  2015-12-11  Surulere         Italiano   3000         1  09:28:54

      Revenue  Snap
4150    12000  4003
4151     9000  3003
4152     4000  2002
4153    20000  4005
4154     3000  3001
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4155  4156  2015-12-08  Surulere       Pepperoni Suya   3000         1
4156  4157  2015-12-06     Lekki          BBQ Chicken   4000         3
4157  4158  2015-12-15   Gbagada  Hot Pepperoni Feast   4000         3
4158  4159  2015-12-14  Surulere          BBQ Chicken   4000         4
4159  4160  2015-12-09     Ikoyi  Hot Pepperoni Feast   4000         2

          Time  Revenue  Snap
4155  09:28:54     3000  3001
4156  09:28:56    12000  4003
4157  09:29:00    12000  4003
4158  09:29:00    16000  4004
4159  09:29:03     8000  4002
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4160  4161  2015-12-05  Surulere         Chicken Bali   2000         5
4161  4162  2015-12-11     Ikoyi       Pepperoni Suya   3000         3
4162  4163  2015-12-10     Ikoyi  Hot Pepperoni Feast   4000         5
4163  4164  2015-12-08   Gbagada         Chicken Suya   4000         5
4164  4165  2015-12-14     Ikoyi         Chicken Bali   2000         3

          Time  Revenue  Snap
4160  09:29:05    10000  2005
4161  09:29:06     9000  3003
4162  09:29:07    20000  4005
4163  09:29:10    20000  4005
4164  09:29:11     6000  2003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4165  4166  2015-12-14  Surulere      Pepperoni Feast   4000         1
4166  4167  2015-12-11     Lekki            Margarita   4000         4
4167  4168  2015-12-08     Lekki         Chicken Suya   4000         3
4168  4169  2015-12-04   Gbagada       Chicken Legend   2000         2
4169  4170  2015-12-03   Gbagada  Hot Pepperoni Feast   4000         2

          Time  Revenue  Snap
4165  09:29:12     4000  4001
4166  09:29:13    16000  4004
4167  09:29:13    12000  4003
4168  09:29:14     4000  2002
4169  09:29:15     8000  4002
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
4170  4171  2015-12-06     Lekki   Veggie Supreme   3000         5  09:29:17
4171  4172  2015-12-11  Surulere    Chicken Feast   2000         1  09:29:18
4172  4173  2015-12-06  Surulere   Pepperoni Suya   3000         4  09:29:18
4173  4174  2015-12-10     Lekki  Pepperoni Feast   4000         5  09:29:21
4174  4175  2015-12-04     Ikoyi      BBQ Chicken   4000         4  09:29:22

      Revenue  Snap
4170    15000  3005
4171     2000  2001
4172    12000  3004
4173    20000  4005
4174    16000  4004
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
4175  4176  2015-12-06   Ibadan     Chicken Feast   2000         4  09:29:26
4176  4177  2015-12-15    Lekki           Meatzaa   2000         1  09:29:27
4177  4178  2015-12-13  Gbagada          Italiano   3000         5  09:29:29
4178  4179  2015-12-12  Gbagada  BBQ Philly Steak   4000         4  09:29:30
4179  4180  2015-12-10    Ikoyi         Beef Suya   3000         5  09:29:31

      Revenue  Snap
4175     8000  2004
4176     2000  2001
4177    15000  3005
4178    16000  4004
4179    15000  3005
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4180  4181  2015-12-15  Surulere  Veggie Supreme   3000         2  09:29:33
4181  4182  2015-12-09    Ibadan    Chicken Bali   2000         1  09:29:33
4182  4183  2015-12-05  Surulere  Chicken Legend   2000         3  09:29:34
4183  4184  2015-12-10    Ibadan       Margarita   4000         1  09:29:34
4184  4185  2015-12-08     Lekki    Extravaganza   2000         4  09:29:34

      Revenue  Snap
4180     6000  3002
4181     2000  2001
4182     6000  2003
4183     4000  4001
4184     8000  2004
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4185  4186  2015-12-14  Surulere  Pepperoni Suya   3000         4  09:29:37
4186  4187  2015-12-05     Lekki        Italiano   3000         2  09:29:39
4187  4188  2015-12-04   Gbagada  Pepperoni Suya   3000         2  09:29:41
4188  4189  2015-12-09    Ibadan    Chicken Bali   2000         1  09:29:41
4189  4190  2015-12-12  Surulere    Chicken Bali   2000         5  09:29:42

      Revenue  Snap
4185    12000  3004
4186     6000  3002
4187     6000  3002
4188     2000  2001
4189    10000  2005
CHUNK BOSS
       S/N        Date  Branch      Pizza Sold  Price  Quantity      Time  \
4190  4191  2015-12-05   Ikoyi        Italiano   3000         3  09:29:46
4191  4192  2015-12-12   Lekki       Margarita   4000         4  09:29:47
4192  4193  2015-12-05   Ikoyi  Chicken Legend   2000         2  09:29:49
4193  4194  2015-12-06  Ibadan  Pepperoni Suya   3000         1  09:29:51
4194  4195  2015-12-10   Ikoyi   Chicken Feast   2000         3  09:29:52

      Revenue  Snap
4190     9000  3003
4191    16000  4004
4192     4000  2002
4193     3000  3001
4194     6000  2003
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
4195  4196  2015-12-09    Ikoyi       BBQ Chicken   4000         1  09:29:52
4196  4197  2015-12-10  Gbagada           Meatzaa   2000         5  09:29:53
4197  4198  2015-12-03    Lekki        Hot Veggie   4000         1  09:29:54
4198  4199  2015-12-09  Gbagada  BBQ Philly Steak   4000         2  09:29:54
4199  4200  2015-12-09   Ibadan         Margarita   4000         3  09:29:54

      Revenue  Snap
4195     4000  4001
4196    10000  2005
4197     4000  4001
4198     8000  4002
4199    12000  4003
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
4200  4201  2015-12-10    Ikoyi      Hot Veggie   4000         1  09:29:54
4201  4202  2015-12-10    Ikoyi    Extravaganza   2000         4  09:29:55
4202  4203  2015-12-06  Gbagada  Veggie Supreme   3000         3  09:29:57
4203  4204  2015-12-03   Ibadan      Hot Veggie   4000         1  09:29:58
4204  4205  2015-12-04   Ibadan   Chicken Feast   2000         2  09:29:58

      Revenue  Snap
4200     4000  4001
4201     8000  2004
4202     9000  3003
4203     4000  4001
4204     4000  2002
CHUNK BOSS
       S/N        Date  Branch      Pizza Sold  Price  Quantity      Time  \
4205  4206  2015-12-11  Ibadan  Veggie Supreme   3000         4  09:29:59
4206  4207  2015-12-10   Lekki      Hot Veggie   4000         2  09:30:00
4207  4208  2015-12-08   Ikoyi  Chicken Legend   2000         1  09:30:04
4208  4209  2015-12-10   Ikoyi         Meatzaa   2000         4  09:30:05
4209  4210  2015-12-08   Lekki       Beef Suya   3000         5  09:30:06

      Revenue  Snap
4205    12000  3004
4206     8000  4002
4207     2000  2001
4208     8000  2004
4209    15000  3005
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
4210  4211  2015-12-13    Lekki            Margarita   4000         3
4211  4212  2015-12-08   Ibadan  Hot Pepperoni Feast   4000         5
4212  4213  2015-12-13  Gbagada              Meatzaa   2000         1
4213  4214  2015-12-15    Ikoyi            Margarita   4000         3
4214  4215  2015-12-15    Lekki      Pepperoni Feast   4000         1

          Time  Revenue  Snap
4210  09:30:07    12000  4003
4211  09:30:09    20000  4005
4212  09:30:09     2000  2001
4213  09:30:09    12000  4003
4214  09:30:11     4000  4001
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
4215  4216  2015-12-12    Lekki      Hot Veggie   4000         4  09:30:11
4216  4217  2015-12-12  Gbagada    Chicken Bali   2000         4  09:30:12
4217  4218  2015-12-03    Lekki     BBQ Chicken   4000         5  09:30:12
4218  4219  2015-12-13    Lekki  Pepperoni Suya   3000         1  09:30:13
4219  4220  2015-12-11  Gbagada       Beef Suya   3000         3  09:30:15

      Revenue  Snap
4215    16000  4004
4216     8000  2004
4217    20000  4005
4218     3000  3001
4219     9000  3003
CHUNK BOSS
       S/N        Date    Branch    Pizza Sold  Price  Quantity      Time  \
4220  4221  2015-12-06     Ikoyi   BBQ Chicken   4000         4  09:30:15
4221  4222  2015-12-15     Lekki  Extravaganza   2000         1  09:30:17
4222  4223  2015-12-09   Gbagada     Margarita   4000         5  09:30:17
4223  4224  2015-12-15  Surulere    Hot Veggie   4000         3  09:30:21
4224  4225  2015-12-14  Surulere     Margarita   4000         2  09:30:21

      Revenue  Snap
4220    16000  4004
4221     2000  2001
4222    20000  4005
4223    12000  4003
4224     8000  4002
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
4225  4226  2015-12-05  Gbagada   Chicken Feast   2000         2  09:30:25
4226  4227  2015-12-04    Lekki  Pepperoni Suya   3000         3  09:30:26
4227  4228  2015-12-03  Gbagada       Beef Suya   3000         3  09:30:27
4228  4229  2015-12-03    Ikoyi  Veggie Supreme   3000         2  09:30:28
4229  4230  2015-12-10    Lekki    Chicken Bali   2000         4  09:30:29

      Revenue  Snap
4225     4000  2002
4226     9000  3003
4227     9000  3003
4228     6000  3002
4229     8000  2004
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
4230  4231  2015-12-09    Ibadan          Meatzaa   2000         3  09:30:31
4231  4232  2015-12-14   Gbagada     Chicken Bali   2000         2  09:30:32
4232  4233  2015-12-07  Surulere         Italiano   3000         1  09:30:34
4233  4234  2015-12-11     Ikoyi  Pepperoni Feast   4000         2  09:30:34
4234  4235  2015-12-11   Gbagada     Extravaganza   2000         5  09:30:34

      Revenue  Snap
4230     6000  2003
4231     4000  2002
4232     3000  3001
4233     8000  4002
4234    10000  2005
CHUNK BOSS
       S/N        Date  Branch      Pizza Sold  Price  Quantity      Time  \
4235  4236  2015-12-04   Lekki       Beef Suya   3000         2  09:30:35
4236  4237  2015-12-04  Ibadan  Chicken Legend   2000         2  09:30:37
4237  4238  2015-12-11   Ikoyi       Margarita   4000         5  09:30:39
4238  4239  2015-12-03   Ikoyi      Hot Veggie   4000         3  09:30:39
4239  4240  2015-12-12  Ibadan  Pepperoni Suya   3000         4  09:30:40

      Revenue  Snap
4235     6000  3002
4236     4000  2002
4237    20000  4005
4238    12000  4003
4239    12000  3004
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4240  4241  2015-12-09   Gbagada           Hot Veggie   4000         2
4241  4242  2015-12-10     Lekki        Chicken Feast   2000         2
4242  4243  2015-12-15    Ibadan      Pepperoni Feast   4000         4
4243  4244  2015-12-03    Ibadan  Hot Pepperoni Feast   4000         3
4244  4245  2015-12-05  Surulere         Extravaganza   2000         4

          Time  Revenue  Snap
4240  09:30:41     8000  4002
4241  09:30:41     4000  2002
4242  09:30:42    16000  4004
4243  09:30:43    12000  4003
4244  09:30:44     8000  2004
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4245  4246  2015-12-08     Lekki       Margarita   4000         4  09:30:46
4246  4247  2015-12-14  Surulere    Extravaganza   2000         5  09:30:48
4247  4248  2015-12-07  Surulere  Pepperoni Suya   3000         3  09:30:48
4248  4249  2015-12-15     Ikoyi       Margarita   4000         5  09:30:49
4249  4250  2015-12-10     Lekki  Veggie Supreme   3000         4  09:30:49

      Revenue  Snap
4245    16000  4004
4246    10000  2005
4247     9000  3003
4248    20000  4005

4249    12000  3004
CHUNK BOSS
       S/N        Date  Branch      Pizza Sold  Price  Quantity      Time  \
4250  4251  2015-12-09   Lekki        Italiano   3000         2  09:30:51
4251  4252  2015-12-11   Ikoyi  Pepperoni Suya   3000         2  09:30:52
4252  4253  2015-12-06   Ikoyi  Pepperoni Suya   3000         5  09:30:52
4253  4254  2015-12-06  Ibadan    Chicken Suya   4000         2  09:30:53
4254  4255  2015-12-14   Ikoyi   Chicken Feast   2000         4  09:30:54

      Revenue  Snap
4250     6000  3002
4251     6000  3002
4252    15000  3005
4253     8000  4002
4254     8000  2004
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
4255  4256  2015-12-13  Surulere          Meatzaa   2000         2  09:30:54
4256  4257  2015-12-15     Lekki   Pepperoni Suya   3000         4  09:30:56
4257  4258  2015-12-06    Ibadan       Hot Veggie   4000         3  09:30:56
4258  4259  2015-12-04   Gbagada   Chicken Legend   2000         2  09:30:57
4259  4260  2015-12-08   Gbagada  Pepperoni Feast   4000         3  09:30:57

      Revenue  Snap
4255     4000  2002
4256    12000  3004
4257    12000  4003
4258     4000  2002
4259    12000  4003
CHUNK BOSS
       S/N        Date  Branch      Pizza Sold  Price  Quantity      Time  \
4260  4261  2015-12-06   Ikoyi  Veggie Supreme   3000         3  09:30:57
4261  4262  2015-12-11   Ikoyi      Hot Veggie   4000         4  09:30:58
4262  4263  2015-12-04   Ikoyi  Chicken Legend   2000         5  09:30:58
4263  4264  2015-12-06  Ibadan  Chicken Legend   2000         5  09:31:00
4264  4265  2015-12-05   Ikoyi    Chicken Suya   4000         2  09:31:02

      Revenue  Snap
4260     9000  3003
4261    16000  4004
4262    10000  2005
4263    10000  2005
4264     8000  4002
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4265  4266  2015-12-13   Gbagada    Chicken Bali   2000         4  09:31:03
4266  4267  2015-12-11    Ibadan  Veggie Supreme   3000         1  09:31:04
4267  4268  2015-12-06   Gbagada        Italiano   3000         5  09:31:04
4268  4269  2015-12-08  Surulere    Chicken Suya   4000         1  09:31:04
4269  4270  2015-12-06     Ikoyi      Hot Veggie   4000         5  09:31:06

      Revenue  Snap
4265     8000  2004
4266     3000  3001
4267    15000  3005
4268     4000  4001
4269    20000  4005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4270  4271  2015-12-04   Gbagada         Chicken Suya   4000         1
4271  4272  2015-12-12  Surulere  Hot Pepperoni Feast   4000         2
4272  4273  2015-12-04     Ikoyi  Hot Pepperoni Feast   4000         5
4273  4274  2015-12-03  Surulere          BBQ Chicken   4000         4
4274  4275  2015-12-14     Lekki  Hot Pepperoni Feast   4000         3

          Time  Revenue  Snap
4270  09:31:07     4000  4001
4271  09:31:08     8000  4002
4272  09:31:08    20000  4005
4273  09:31:09    16000  4004
4274  09:31:10    12000  4003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4275  4276  2015-12-11     Lekki              Meatzaa   2000         2
4276  4277  2015-12-09     Lekki              Meatzaa   2000         2
4277  4278  2015-12-06   Gbagada       Pepperoni Suya   3000         3
4278  4279  2015-12-15     Ikoyi  Hot Pepperoni Feast   4000         1
4279  4280  2015-12-07  Surulere         Chicken Suya   4000         1

          Time  Revenue  Snap
4275  09:31:10     4000  2002
4276  09:31:11     4000  2002
4277  09:31:11     9000  3003
4278  09:31:12     4000  4001
4279  09:31:12     4000  4001
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4280  4281  2015-12-07     Lekki     BBQ Philly Steak   4000         4
4281  4282  2015-12-09     Lekki         Chicken Bali   2000         3
4282  4283  2015-12-06   Gbagada          BBQ Chicken   4000         4
4283  4284  2015-12-13   Gbagada            Margarita   4000         4
4284  4285  2015-12-11  Surulere  Hot Pepperoni Feast   4000         4

          Time  Revenue  Snap
4280  09:31:15    16000  4004
4281  09:31:15     6000  2003
4282  09:31:17    16000  4004
4283  09:31:17    16000  4004
4284  09:31:18    16000  4004
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
4285  4286  2015-12-07  Gbagada       Beef Suya   3000         5  09:31:20
4286  4287  2015-12-03  Gbagada    Chicken Suya   4000         5  09:31:20
4287  4288  2015-12-07    Ikoyi  Pepperoni Suya   3000         3  09:31:21
4288  4289  2015-12-05   Ibadan    Chicken Suya   4000         1  09:31:22
4289  4290  2015-12-07    Lekki  Chicken Legend   2000         3  09:31:23

      Revenue  Snap
4285    15000  3005
4286    20000  4005
4287     9000  3003
4288     4000  4001
4289     6000  2003
CHUNK BOSS
       S/N        Date  Branch       Pizza Sold  Price  Quantity      Time  \
4290  4291  2015-12-11   Ikoyi  Pepperoni Feast   4000         5  09:31:24
4291  4292  2015-12-08   Lekki         Italiano   3000         3  09:31:24
4292  4293  2015-12-03   Ikoyi      BBQ Chicken   4000         5  09:31:25
4293  4294  2015-12-12  Ibadan        Beef Suya   3000         2  09:31:27
4294  4295  2015-12-15   Lekki   Veggie Supreme   3000         5  09:31:29

      Revenue  Snap
4290    20000  4005
4291     9000  3003
4292    20000  4005
4293     6000  3002
4294    15000  3005
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
4295  4296  2015-12-04   Gbagada    Chicken Legend   2000         1  09:31:30
4296  4297  2015-12-06     Ikoyi      Chicken Bali   2000         1  09:31:30
4297  4298  2015-12-03     Ikoyi    Veggie Supreme   3000         1  09:31:30
4298  4299  2015-12-05  Surulere  BBQ Philly Steak   4000         2  09:31:31
4299  4300  2015-12-06   Gbagada    Veggie Supreme   3000         2  09:31:31

      Revenue  Snap
4295     2000  2001
4296     2000  2001
4297     3000  3001
4298     8000  4002
4299     6000  3002
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4300  4301  2015-12-05    Ibadan            Margarita   4000         4
4301  4302  2015-12-08  Surulere  Hot Pepperoni Feast   4000         5
4302  4303  2015-12-06   Gbagada         Extravaganza   2000         3
4303  4304  2015-12-04     Ikoyi              Meatzaa   2000         2
4304  4305  2015-12-12    Ibadan  Hot Pepperoni Feast   4000         3

          Time  Revenue  Snap
4300  09:31:34    16000  4004
4301  09:31:34    20000  4005
4302  09:31:35     6000  2003
4303  09:31:37     4000  2002
4304  09:31:38    12000  4003
CHUNK BOSS
       S/N        Date  Branch      Pizza Sold  Price  Quantity      Time  \
4305  4306  2015-12-09  Ibadan      Hot Veggie   4000         2  09:31:38
4306  4307  2015-12-15   Ikoyi      Hot Veggie   4000         1  09:31:42
4307  4308  2015-12-14   Ikoyi        Italiano   3000         4  09:31:43
4308  4309  2015-12-04  Ibadan  Pepperoni Suya   3000         2  09:31:50
4309  4310  2015-12-07  Ibadan       Beef Suya   3000         2  09:31:50

      Revenue  Snap
4305     8000  4002
4306     4000  4001
4307    12000  3004
4308     6000  3002
4309     6000  3002
CHUNK BOSS
       S/N        Date  Branch           Pizza Sold  Price  Quantity  \
4310  4311  2015-12-08   Ikoyi         Extravaganza   2000         1
4311  4312  2015-12-10  Ibadan        Chicken Feast   2000         3
4312  4313  2015-12-11  Ibadan       Chicken Legend   2000         4
4313  4314  2015-12-08   Ikoyi            Margarita   4000         5
4314  4315  2015-12-03  Ibadan  Hot Pepperoni Feast   4000         4

          Time  Revenue  Snap
4310  09:31:51     2000  2001
4311  09:31:51     6000  2003
4312  09:31:51     8000  2004
4313  09:31:52    20000  4005
4314  09:31:53    16000  4004
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
4315  4316  2015-12-11  Gbagada    Chicken Bali   2000         3  09:31:53
4316  4317  2015-12-13    Ikoyi    Chicken Suya   4000         5  09:31:56
4317  4318  2015-12-04   Ibadan    Extravaganza   2000         3  09:31:57
4318  4319  2015-12-05   Ibadan  Chicken Legend   2000         5  09:31:57
4319  4320  2015-12-03    Lekki   Chicken Feast   2000         1  09:31:59

      Revenue  Snap
4315     6000  2003
4316    20000  4005
4317     6000  2003
4318    10000  2005
4319     2000  2001
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
4320  4321  2015-12-04   Ibadan           Hot Veggie   4000         2
4321  4322  2015-12-04  Gbagada            Beef Suya   3000         3
4322  4323  2015-12-03    Ikoyi  Hot Pepperoni Feast   4000         4
4323  4324  2015-12-09    Lekki             Italiano   3000         5
4324  4325  2015-12-08    Lekki     BBQ Philly Steak   4000         3

          Time  Revenue  Snap
4320  09:32:00     8000  4002
4321  09:32:01     9000  3003
4322  09:32:04    16000  4004
4323  09:32:05    15000  3005
4324  09:32:06    12000  4003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4325  4326  2015-12-14    Ibadan         Chicken Suya   4000         2
4326  4327  2015-12-11   Gbagada         Extravaganza   2000         3
4327  4328  2015-12-08    Ibadan     BBQ Philly Steak   4000         4
4328  4329  2015-12-05  Surulere  Hot Pepperoni Feast   4000         1
4329  4330  2015-12-04   Gbagada      Pepperoni Feast   4000         1

          Time  Revenue  Snap
4325  09:32:07     8000  4002
4326  09:32:11     6000  2003
4327  09:32:12    16000  4004
4328  09:32:12     4000  4001
4329  09:32:12     4000  4001
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
4330  4331  2015-12-13   Gbagada    Chicken Feast   2000         3  09:32:13
4331  4332  2015-12-14  Surulere     Chicken Suya   4000         2  09:32:13
4332  4333  2015-12-10     Lekki   Chicken Legend   2000         3  09:32:16
4333  4334  2015-12-08    Ibadan        Margarita   4000         2  09:32:16
4334  4335  2015-12-15    Ibadan  Pepperoni Feast   4000         2  09:32:17

      Revenue  Snap
4330     6000  2003
4331     8000  4002
4332     6000  2003
4333     8000  4002
4334     8000  4002
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
4335  4336  2015-12-14    Ikoyi        Chicken Feast   2000         5
4336  4337  2015-12-12   Ibadan      Pepperoni Feast   4000         1
4337  4338  2015-12-03  Gbagada  Hot Pepperoni Feast   4000         3
4338  4339  2015-12-14   Ibadan       Chicken Legend   2000         4
4339  4340  2015-12-04    Lekki             Italiano   3000         3

          Time  Revenue  Snap
4335  09:32:19    10000  2005
4336  09:32:19     4000  4001
4337  09:32:19    12000  4003
4338  09:32:20     8000  2004
4339  09:32:21     9000  3003
CHUNK BOSS
       S/N        Date    Branch     Pizza Sold  Price  Quantity      Time  \
4340  4341  2015-12-11     Ikoyi   Extravaganza   2000         1  09:32:22
4341  4342  2015-12-03    Ibadan  Chicken Feast   2000         5  09:32:24
4342  4343  2015-12-10  Surulere        Meatzaa   2000         2  09:32:24
4343  4344  2015-12-11     Lekki   Chicken Suya   4000         2  09:32:25
4344  4345  2015-12-11     Ikoyi       Italiano   3000         5  09:32:26

      Revenue  Snap
4340     2000  2001
4341    10000  2005
4342     4000  2002
4343     8000  4002
4344    15000  3005
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
4345  4346  2015-12-06    Ikoyi    Chicken Bali   2000         1  09:32:26
4346  4347  2015-12-15    Lekki  Veggie Supreme   3000         2  09:32:26
4347  4348  2015-12-08  Gbagada    Chicken Bali   2000         4  09:32:28
4348  4349  2015-12-04    Lekki    Extravaganza   2000         2  09:32:28
4349  4350  2015-12-13    Lekki     BBQ Chicken   4000         3  09:32:28

      Revenue  Snap
4345     2000  2001
4346     6000  3002
4347     8000  2004
4348     4000  2002
4349    12000  4003

CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
4350  4351  2015-12-05  Gbagada  BBQ Philly Steak   4000         4  09:32:29
4351  4352  2015-12-14    Lekki         Beef Suya   3000         1  09:32:29
4352  4353  2015-12-04   Ibadan           Meatzaa   2000         3  09:32:29
4353  4354  2015-12-11    Lekki    Veggie Supreme   3000         1  09:32:30
4354  4355  2015-12-07    Lekki          Italiano   3000         4  09:32:33

      Revenue  Snap
4350    16000  4004
4351     3000  3001
4352     6000  2003
4353     3000  3001
4354    12000  3004
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4355  4356  2015-12-04  Surulere         Chicken Suya   4000         3
4356  4357  2015-12-12    Ibadan       Pepperoni Suya   3000         3
4357  4358  2015-12-04     Lekki       Veggie Supreme   3000         2
4358  4359  2015-12-09     Ikoyi            Margarita   4000         1
4359  4360  2015-12-04    Ibadan  Hot Pepperoni Feast   4000         2

          Time  Revenue  Snap
4355  09:32:33    12000  4003
4356  09:32:34     9000  3003
4357  09:32:35     6000  3002
4358  09:32:36     4000  4001
4359  09:32:37     8000  4002
CHUNK BOSS
       S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
4360  4361  2015-12-15    Lekki        Margarita   4000         2  09:32:37
4361  4362  2015-12-08    Ikoyi  Pepperoni Feast   4000         5  09:32:37
4362  4363  2015-12-03    Lekki   Pepperoni Suya   3000         3  09:32:37
4363  4364  2015-12-04  Gbagada      BBQ Chicken   4000         1  09:32:38
4364  4365  2015-12-09  Gbagada        Beef Suya   3000         4  09:32:41

      Revenue  Snap
4360     8000  4002
4361    20000  4005
4362     9000  3003
4363     4000  4001
4364    12000  3004
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
4365  4366  2015-12-08    Ikoyi  BBQ Philly Steak   4000         2  09:32:42
4366  4367  2015-12-12  Gbagada          Italiano   3000         4  09:32:45
4367  4368  2015-12-04    Lekki           Meatzaa   2000         3  09:32:47
4368  4369  2015-12-06    Ikoyi  BBQ Philly Steak   4000         1  09:32:49
4369  4370  2015-12-13    Ikoyi        Hot Veggie   4000         4  09:32:49

      Revenue  Snap
4365     8000  4002
4366    12000  3004
4367     6000  2003
4368     4000  4001
4369    16000  4004
CHUNK BOSS
       S/N        Date  Branch       Pizza Sold  Price  Quantity      Time  \
4370  4371  2015-12-10   Ikoyi     Chicken Bali   2000         4  09:32:51
4371  4372  2015-12-07  Ibadan   Veggie Supreme   3000         1  09:32:51
4372  4373  2015-12-05   Ikoyi   Veggie Supreme   3000         4  09:32:52
4373  4374  2015-12-10  Ibadan   Veggie Supreme   3000         1  09:32:55
4374  4375  2015-12-13  Ibadan  Pepperoni Feast   4000         4  09:32:56

      Revenue  Snap
4370     8000  2004
4371     3000  3001
4372    12000  3004
4373     3000  3001
4374    16000  4004
CHUNK BOSS
       S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
4375  4376  2015-12-03    Ikoyi  Pepperoni Feast   4000         5  09:32:57
4376  4377  2015-12-12   Ibadan     Chicken Bali   2000         3  09:32:57
4377  4378  2015-12-11    Lekki      BBQ Chicken   4000         1  09:32:57
4378  4379  2015-12-05   Ibadan        Margarita   4000         1  09:32:58
4379  4380  2015-12-08  Gbagada   Veggie Supreme   3000         1  09:32:59

      Revenue  Snap
4375    20000  4005
4376     6000  2003
4377     4000  4001
4378     4000  4001
4379     3000  3001
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4380  4381  2015-12-13   Gbagada       Veggie Supreme   3000         2
4381  4382  2015-12-08     Lekki  Hot Pepperoni Feast   4000         3
4382  4383  2015-12-15  Surulere     BBQ Philly Steak   4000         4
4383  4384  2015-12-11  Surulere            Beef Suya   3000         3
4384  4385  2015-12-04     Lekki         Chicken Suya   4000         2

          Time  Revenue  Snap
4380  09:32:59     6000  3002
4381  09:32:59    12000  4003
4382  09:32:59    16000  4004
4383  09:33:03     9000  3003
4384  09:33:04     8000  4002
CHUNK BOSS
       S/N        Date Branch        Pizza Sold  Price  Quantity      Time  \
4385  4386  2015-12-15  Ikoyi    Veggie Supreme   3000         3  09:33:06
4386  4387  2015-12-09  Lekki    Veggie Supreme   3000         1  09:33:06
4387  4388  2015-12-03  Ikoyi    Chicken Legend   2000         3  09:33:06
4388  4389  2015-12-12  Ikoyi   Pepperoni Feast   4000         2  09:33:07
4389  4390  2015-12-08  Lekki  BBQ Philly Steak   4000         2  09:33:07

      Revenue  Snap
4385     9000  3003
4386     3000  3001
4387     6000  2003
4388     8000  4002
4389     8000  4002
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
4390  4391  2015-12-13    Lekki  Hot Pepperoni Feast   4000         3
4391  4392  2015-12-05    Ikoyi            Beef Suya   3000         1
4392  4393  2015-12-04  Gbagada  Hot Pepperoni Feast   4000         5
4393  4394  2015-12-07    Ikoyi     BBQ Philly Steak   4000         1
4394  4395  2015-12-04    Lekki           Hot Veggie   4000         1

          Time  Revenue  Snap
4390  09:33:09    12000  4003
4391  09:33:10     3000  3001
4392  09:33:11    20000  4005
4393  09:33:11     4000  4001
4394  09:33:13     4000  4001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4395  4396  2015-12-06     Lekki       Margarita   4000         5  09:33:13
4396  4397  2015-12-10  Surulere         Meatzaa   2000         3  09:33:13
4397  4398  2015-12-04     Ikoyi       Beef Suya   3000         3  09:33:13
4398  4399  2015-12-12    Ibadan   Chicken Feast   2000         4  09:33:13
4399  4400  2015-12-13  Surulere  Pepperoni Suya   3000         4  09:33:14

      Revenue  Snap
4395    20000  4005
4396     6000  2003
4397     9000  3003
4398     8000  2004
4399    12000  3004
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
4400  4401  2015-12-04   Ibadan  Pepperoni Suya   3000         5  09:33:15
4401  4402  2015-12-09    Ikoyi    Chicken Bali   2000         1  09:33:15
4402  4403  2015-12-13  Gbagada         Meatzaa   2000         1  09:33:17
4403  4404  2015-12-10    Lekki        Italiano   3000         1  09:33:19
4404  4405  2015-12-13    Lekki  Chicken Legend   2000         5  09:33:19

      Revenue  Snap
4400    15000  3005
4401     2000  2001
4402     2000  2001
4403     3000  3001
4404    10000  2005
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4405  4406  2015-12-04     Lekki  Veggie Supreme   3000         4  09:33:20
4406  4407  2015-12-06    Ibadan         Meatzaa   2000         3  09:33:22
4407  4408  2015-12-07  Surulere         Meatzaa   2000         3  09:33:22
4408  4409  2015-12-03   Gbagada      Hot Veggie   4000         2  09:33:23
4409  4410  2015-12-15  Surulere       Margarita   4000         3  09:33:24

      Revenue  Snap
4405    12000  3004
4406     6000  2003
4407     6000  2003
4408     8000  4002
4409    12000  4003
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
4410  4411  2015-12-13     Ikoyi   Pepperoni Feast   4000         3  09:33:25
4411  4412  2015-12-15    Ibadan        Hot Veggie   4000         5  09:33:27
4412  4413  2015-12-12    Ibadan        Hot Veggie   4000         4  09:33:27
4413  4414  2015-12-05  Surulere  BBQ Philly Steak   4000         3  09:33:28
4414  4415  2015-12-11     Lekki          Italiano   3000         1  09:33:29

      Revenue  Snap
4410    12000  4003
4411    20000  4005
4412    16000  4004
4413    12000  4003
4414     3000  3001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4415  4416  2015-12-11  Surulere     BBQ Chicken   4000         4  09:33:30
4416  4417  2015-12-09    Ibadan  Veggie Supreme   3000         2  09:33:30
4417  4418  2015-12-06     Ikoyi    Extravaganza   2000         1  09:33:30
4418  4419  2015-12-05   Gbagada         Meatzaa   2000         3  09:33:32
4419  4420  2015-12-08     Ikoyi        Italiano   3000         1  09:33:32

      Revenue  Snap
4415    16000  4004
4416     6000  3002
4417     2000  2001
4418     6000  2003
4419     3000  3001
CHUNK BOSS
       S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
4420  4421  2015-12-03   Ibadan   Chicken Legend   2000         1  09:33:32
4421  4422  2015-12-03  Gbagada        Margarita   4000         1  09:33:34
4422  4423  2015-12-13   Ibadan  Pepperoni Feast   4000         1  09:33:34
4423  4424  2015-12-12   Ibadan       Hot Veggie   4000         3  09:33:35
4424  4425  2015-12-04    Lekki     Chicken Bali   2000         1  09:33:35

      Revenue  Snap
4420     2000  2001
4421     4000  4001
4422     4000  4001
4423    12000  4003
4424     2000  2001
CHUNK BOSS
       S/N        Date    Branch    Pizza Sold  Price  Quantity      Time  \
4425  4426  2015-12-11   Gbagada  Chicken Suya   4000         2  09:33:36
4426  4427  2015-12-11  Surulere  Extravaganza   2000         5  09:33:36
4427  4428  2015-12-11     Lekki    Hot Veggie   4000         5  09:33:36
4428  4429  2015-12-03     Ikoyi      Italiano   3000         3  09:33:37
4429  4430  2015-12-08   Gbagada      Italiano   3000         1  09:33:37

      Revenue  Snap
4425     8000  4002
4426    10000  2005
4427    20000  4005
4428     9000  3003
4429     3000  3001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4430  4431  2015-12-03     Ikoyi        Italiano   3000         2  09:33:38
4431  4432  2015-12-14     Ikoyi       Beef Suya   3000         1  09:33:40
4432  4433  2015-12-07  Surulere    Extravaganza   2000         5  09:33:41
4433  4434  2015-12-15     Lekki  Pepperoni Suya   3000         1  09:33:43
4434  4435  2015-12-10    Ibadan    Chicken Suya   4000         5  09:33:44

      Revenue  Snap
4430     6000  3002
4431     3000  3001
4432    10000  2005
4433     3000  3001
4434    20000  4005
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
4435  4436  2015-12-14  Surulere      BBQ Chicken   4000         4  09:33:45
4436  4437  2015-12-03     Lekki      BBQ Chicken   4000         1  09:33:47
4437  4438  2015-12-05    Ibadan  Pepperoni Feast   4000         5  09:33:48
4438  4439  2015-12-14     Ikoyi       Hot Veggie   4000         5  09:33:49
4439  4440  2015-12-09   Gbagada     Chicken Bali   2000         1  09:33:50

      Revenue  Snap
4435    16000  4004
4436     4000  4001
4437    20000  4005
4438    20000  4005
4439     2000  2001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4440  4441  2015-12-11     Lekki   Chicken Feast   2000         5  09:33:50
4441  4442  2015-12-10     Lekki    Extravaganza   2000         5  09:33:51
4442  4443  2015-12-03  Surulere        Italiano   3000         4  09:33:51
4443  4444  2015-12-05     Ikoyi  Pepperoni Suya   3000         5  09:33:52
4444  4445  2015-12-06   Gbagada      Hot Veggie   4000         1  09:33:53

      Revenue  Snap
4440    10000  2005
4441    10000  2005
4442    12000  3004
4443    15000  3005

4444     4000  4001
CHUNK BOSS
       S/N        Date  Branch      Pizza Sold  Price  Quantity      Time  \
4445  4446  2015-12-09  Ibadan    Extravaganza   2000         1  09:33:56
4446  4447  2015-12-12   Lekki  Chicken Legend   2000         4  09:33:57
4447  4448  2015-12-08  Ibadan         Meatzaa   2000         2  09:33:57
4448  4449  2015-12-04  Ibadan    Chicken Suya   4000         3  09:33:59
4449  4450  2015-12-12  Ibadan  Chicken Legend   2000         2  09:33:59

      Revenue  Snap
4445     2000  2001
4446     8000  2004
4447     4000  2002
4448    12000  4003
4449     4000  2002
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4450  4451  2015-12-11     Lekki       Beef Suya   3000         5  09:34:00
4451  4452  2015-12-05    Ibadan   Chicken Feast   2000         1  09:34:03
4452  4453  2015-12-06     Ikoyi    Chicken Suya   4000         2  09:34:04
4453  4454  2015-12-09  Surulere  Veggie Supreme   3000         3  09:34:04
4454  4455  2015-12-10    Ibadan   Chicken Feast   2000         3  09:34:06

      Revenue  Snap
4450    15000  3005
4451     2000  2001
4452     8000  4002
4453     9000  3003
4454     6000  2003
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
4455  4456  2015-12-14   Ibadan   Chicken Feast   2000         1  09:34:09
4456  4457  2015-12-10    Lekki  Chicken Legend   2000         3  09:34:10
4457  4458  2015-12-14  Gbagada  Veggie Supreme   3000         2  09:34:10
4458  4459  2015-12-03    Lekki  Pepperoni Suya   3000         4  09:34:11
4459  4460  2015-12-14    Ikoyi    Extravaganza   2000         1  09:34:13

      Revenue  Snap
4455     2000  2001
4456     6000  2003
4457     6000  3002
4458    12000  3004
4459     2000  2001
CHUNK BOSS
       S/N        Date    Branch     Pizza Sold  Price  Quantity      Time  \
4460  4461  2015-12-10   Gbagada   Extravaganza   2000         2  09:34:13
4461  4462  2015-12-08    Ibadan  Chicken Feast   2000         1  09:34:13
4462  4463  2015-12-15  Surulere  Chicken Feast   2000         2  09:34:14
4463  4464  2015-12-12     Ikoyi   Chicken Suya   4000         2  09:34:18
4464  4465  2015-12-05     Lekki   Chicken Bali   2000         3  09:34:18

      Revenue  Snap
4460     4000  2002
4461     2000  2001
4462     4000  2002
4463     8000  4002
4464     6000  2003
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
4465  4466  2015-12-13     Ikoyi  BBQ Philly Steak   4000         5  09:34:18
4466  4467  2015-12-11  Surulere          Italiano   3000         5  09:34:20
4467  4468  2015-12-03  Surulere        Hot Veggie   4000         3  09:34:20
4468  4469  2015-12-03  Surulere     Chicken Feast   2000         3  09:34:20
4469  4470  2015-12-12   Gbagada           Meatzaa   2000         1  09:34:20

      Revenue  Snap
4465    20000  4005
4466    15000  3005
4467    12000  4003
4468     6000  2003
4469     2000  2001
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4470  4471  2015-12-06    Ibadan         Extravaganza   2000         5
4471  4472  2015-12-04  Surulere  Hot Pepperoni Feast   4000         5
4472  4473  2015-12-09   Gbagada       Pepperoni Suya   3000         5
4473  4474  2015-12-04     Ikoyi         Chicken Bali   2000         4
4474  4475  2015-12-13  Surulere         Extravaganza   2000         2

          Time  Revenue  Snap
4470  09:34:26    10000  2005
4471  09:34:27    20000  4005
4472  09:34:28    15000  3005
4473  09:34:29     8000  2004
4474  09:34:30     4000  2002
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4475  4476  2015-12-08     Ikoyi   Chicken Feast   2000         4  09:34:32
4476  4477  2015-12-07     Ikoyi        Italiano   3000         4  09:34:32
4477  4478  2015-12-14    Ibadan  Veggie Supreme   3000         3  09:34:33
4478  4479  2015-12-04   Gbagada       Beef Suya   3000         5  09:34:34
4479  4480  2015-12-14  Surulere       Beef Suya   3000         3  09:34:35

      Revenue  Snap
4475     8000  2004
4476    12000  3004
4477     9000  3003
4478    15000  3005
4479     9000  3003
CHUNK BOSS
       S/N        Date    Branch    Pizza Sold  Price  Quantity      Time  \
4480  4481  2015-12-15  Surulere    Hot Veggie   4000         1  09:34:35
4481  4482  2015-12-04   Gbagada  Chicken Bali   2000         2  09:34:36
4482  4483  2015-12-05     Ikoyi  Extravaganza   2000         5  09:34:37
4483  4484  2015-12-13   Gbagada  Chicken Bali   2000         4  09:34:39
4484  4485  2015-12-04     Ikoyi  Extravaganza   2000         4  09:34:39

      Revenue  Snap
4480     4000  4001
4481     4000  2002
4482    10000  2005
4483     8000  2004
4484     8000  2004
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
4485  4486  2015-12-13   Ibadan        Hot Veggie   4000         3  09:34:41
4486  4487  2015-12-09    Ikoyi      Extravaganza   2000         3  09:34:41
4487  4488  2015-12-07   Ibadan  BBQ Philly Steak   4000         4  09:34:42
4488  4489  2015-12-10  Gbagada          Italiano   3000         1  09:34:43
4489  4490  2015-12-13  Gbagada          Italiano   3000         5  09:34:43

      Revenue  Snap
4485    12000  4003
4486     6000  2003
4487    16000  4004
4488     3000  3001
4489    15000  3005
CHUNK BOSS
       S/N        Date    Branch     Pizza Sold  Price  Quantity      Time  \
4490  4491  2015-12-14   Gbagada      Beef Suya   3000         4  09:34:44
4491  4492  2015-12-10  Surulere      Beef Suya   3000         3  09:34:44
4492  4493  2015-12-13   Gbagada   Chicken Suya   4000         3  09:34:44
4493  4494  2015-12-06   Gbagada      Margarita   4000         1  09:34:45
4494  4495  2015-12-11    Ibadan  Chicken Feast   2000         5  09:34:46

      Revenue  Snap
4490    12000  3004
4491     9000  3003
4492    12000  4003
4493     4000  4001
4494    10000  2005
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4495  4496  2015-12-12     Ikoyi    Chicken Suya   4000         4  09:34:47
4496  4497  2015-12-11    Ibadan         Meatzaa   2000         5  09:34:48
4497  4498  2015-12-05     Lekki    Chicken Bali   2000         1  09:34:50
4498  4499  2015-12-06  Surulere    Chicken Suya   4000         4  09:34:51
4499  4500  2015-12-09    Ibadan  Veggie Supreme   3000         1  09:34:51

      Revenue  Snap
4495    16000  4004
4496    10000  2005
4497     2000  2001
4498    16000  4004
4499     3000  3001
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4500  4501  2015-12-14     Lekki            Margarita   4000         5
4501  4502  2015-12-03  Surulere            Beef Suya   3000         2
4502  4503  2015-12-10   Gbagada           Hot Veggie   4000         1
4503  4504  2015-12-08    Ibadan  Hot Pepperoni Feast   4000         3
4504  4505  2015-12-10  Surulere            Beef Suya   3000         3

          Time  Revenue  Snap
4500  09:34:53    20000  4005
4501  09:34:53     6000  3002
4502  09:34:53     4000  4001
4503  09:34:54    12000  4003
4504  09:34:55     9000  3003
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4505  4506  2015-12-04  Surulere     BBQ Chicken   4000         2  09:34:56
4506  4507  2015-12-07   Gbagada       Margarita   4000         1  09:34:56
4507  4508  2015-12-06  Surulere  Veggie Supreme   3000         5  09:34:58
4508  4509  2015-12-03     Lekki    Extravaganza   2000         5  09:34:59
4509  4510  2015-12-06     Lekki  Pepperoni Suya   3000         3  09:35:00

      Revenue  Snap
4505     8000  4002
4506     4000  4001
4507    15000  3005
4508    10000  2005
4509     9000  3003
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
4510  4511  2015-12-11  Gbagada  Hot Pepperoni Feast   4000         4
4511  4512  2015-12-08    Lekki             Italiano   3000         3
4512  4513  2015-12-08  Gbagada         Chicken Bali   2000         2
4513  4514  2015-12-05  Gbagada         Chicken Suya   4000         1
4514  4515  2015-12-03    Ikoyi           Hot Veggie   4000         3

          Time  Revenue  Snap
4510  09:35:02    16000  4004
4511  09:35:04     9000  3003
4512  09:35:05     4000  2002
4513  09:35:08     4000  4001
4514  09:35:11    12000  4003
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
4515  4516  2015-12-04    Lekki  BBQ Philly Steak   4000         2  09:35:12
4516  4517  2015-12-05  Gbagada      Extravaganza   2000         1  09:35:14
4517  4518  2015-12-10    Lekki  BBQ Philly Steak   4000         3  09:35:14
4518  4519  2015-12-14    Ikoyi        Hot Veggie   4000         1  09:35:14
4519  4520  2015-12-06    Lekki    Veggie Supreme   3000         1  09:35:18

      Revenue  Snap
4515     8000  4002
4516     2000  2001
4517    12000  4003
4518     4000  4001
4519     3000  3001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4520  4521  2015-12-11   Gbagada    Chicken Bali   2000         4  09:35:18
4521  4522  2015-12-06   Gbagada  Pepperoni Suya   3000         2  09:35:20
4522  4523  2015-12-11   Gbagada       Beef Suya   3000         4  09:35:20
4523  4524  2015-12-07     Lekki  Veggie Supreme   3000         5  09:35:20
4524  4525  2015-12-03  Surulere    Chicken Bali   2000         1  09:35:20

      Revenue  Snap
4520     8000  2004
4521     6000  3002
4522    12000  3004
4523    15000  3005
4524     2000  2001
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
4525  4526  2015-12-06    Ibadan          Italiano   3000         5  09:35:20
4526  4527  2015-12-15     Lekki     Chicken Feast   2000         3  09:35:23
4527  4528  2015-12-07    Ibadan        Hot Veggie   4000         4  09:35:23
4528  4529  2015-12-13  Surulere  BBQ Philly Steak   4000         4  09:35:25
4529  4530  2015-12-10    Ibadan          Italiano   3000         2  09:35:26

      Revenue  Snap
4525    15000  3005
4526     6000  2003
4527    16000  4004
4528    16000  4004
4529     6000  3002
CHUNK BOSS
       S/N        Date  Branch      Pizza Sold  Price  Quantity      Time  \
4530  4531  2015-12-12   Ikoyi    Chicken Bali   2000         5  09:35:26
4531  4532  2015-12-08   Ikoyi  Chicken Legend   2000         1  09:35:27
4532  4533  2015-12-04  Ibadan         Meatzaa   2000         3  09:35:28
4533  4534  2015-12-08   Lekki         Meatzaa   2000         1  09:35:29
4534  4535  2015-12-10   Ikoyi       Beef Suya   3000         5  09:35:29

      Revenue  Snap
4530    10000  2005
4531     2000  2001
4532     6000  2003
4533     2000  2001
4534    15000  3005
CHUNK BOSS
       S/N        Date Branch           Pizza Sold  Price  Quantity      Time  \
4535  4536  2015-12-14  Ikoyi              Meatzaa   2000         5  09:35:30
4536  4537  2015-12-08  Ikoyi        Chicken Feast   2000         5  09:35:30
4537  4538  2015-12-04  Ikoyi  Hot Pepperoni Feast   4000         5  09:35:31
4538  4539  2015-12-08  Ikoyi         Chicken Suya   4000         1  09:35:32
4539  4540  2015-12-03  Ikoyi     BBQ Philly Steak   4000         5  09:35:32

      Revenue  Snap
4535    10000  2005
4536    10000  2005
4537    20000  4005
4538     4000  4001
4539    20000  4005

CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
4540  4541  2015-12-04   Gbagada  Pepperoni Feast   4000         4  09:35:32
4541  4542  2015-12-07   Gbagada          Meatzaa   2000         5  09:35:34
4542  4543  2015-12-09  Surulere  Pepperoni Feast   4000         3  09:35:34
4543  4544  2015-12-06    Ibadan     Chicken Suya   4000         3  09:35:35
4544  4545  2015-12-05  Surulere   Veggie Supreme   3000         5  09:35:36

      Revenue  Snap
4540    16000  4004
4541    10000  2005
4542    12000  4003
4543    12000  4003
4544    15000  3005
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
4545  4546  2015-12-13     Ikoyi      Extravaganza   2000         3  09:35:37
4546  4547  2015-12-09   Gbagada      Chicken Suya   4000         4  09:35:38
4547  4548  2015-12-06  Surulere         Beef Suya   3000         1  09:35:38
4548  4549  2015-12-14   Gbagada  BBQ Philly Steak   4000         4  09:35:40
4549  4550  2015-12-08  Surulere      Extravaganza   2000         5  09:35:42

      Revenue  Snap
4545     6000  2003
4546    16000  4004
4547     3000  3001
4548    16000  4004
4549    10000  2005
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
4550  4551  2015-12-11   Gbagada      Chicken Suya   4000         4  09:35:43
4551  4552  2015-12-14  Surulere  BBQ Philly Steak   4000         4  09:35:44
4552  4553  2015-12-09     Lekki  BBQ Philly Steak   4000         2  09:35:44
4553  4554  2015-12-14     Ikoyi      Chicken Suya   4000         5  09:35:44
4554  4555  2015-12-06    Ibadan     Chicken Feast   2000         1  09:35:45

      Revenue  Snap
4550    16000  4004
4551    16000  4004
4552     8000  4002
4553    20000  4005
4554     2000  2001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4555  4556  2015-12-06  Surulere  Chicken Legend   2000         5  09:35:45
4556  4557  2015-12-05     Lekki   Chicken Feast   2000         3  09:35:46
4557  4558  2015-12-07     Ikoyi       Beef Suya   3000         4  09:35:46
4558  4559  2015-12-11   Gbagada         Meatzaa   2000         2  09:35:46
4559  4560  2015-12-14  Surulere    Extravaganza   2000         2  09:35:47

      Revenue  Snap
4555    10000  2005
4556     6000  2003
4557    12000  3004
4558     4000  2002
4559     4000  2002
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4560  4561  2015-12-11   Gbagada       Pepperoni Suya   3000         5
4561  4562  2015-12-07  Surulere              Meatzaa   2000         1
4562  4563  2015-12-04   Gbagada             Italiano   3000         1
4563  4564  2015-12-03   Gbagada      Pepperoni Feast   4000         5
4564  4565  2015-12-14   Gbagada  Hot Pepperoni Feast   4000         4

          Time  Revenue  Snap
4560  09:35:47    15000  3005
4561  09:35:47     2000  2001
4562  09:35:48     3000  3001
4563  09:35:48    20000  4005
4564  09:35:48    16000  4004
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
4565  4566  2015-12-10  Surulere         Margarita   4000         5  09:35:50
4566  4567  2015-12-09   Gbagada  BBQ Philly Steak   4000         5  09:35:55
4567  4568  2015-12-09     Ikoyi      Chicken Suya   4000         1  09:35:55
4568  4569  2015-12-08  Surulere      Chicken Suya   4000         3  09:35:57
4569  4570  2015-12-06     Lekki         Beef Suya   3000         3  09:35:57

      Revenue  Snap
4565    20000  4005
4566    20000  4005
4567     4000  4001
4568    12000  4003
4569     9000  3003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4570  4571  2015-12-04     Lekki            Margarita   4000         5
4571  4572  2015-12-14  Surulere  Hot Pepperoni Feast   4000         5
4572  4573  2015-12-15  Surulere         Extravaganza   2000         4
4573  4574  2015-12-03  Surulere  Hot Pepperoni Feast   4000         5
4574  4575  2015-12-09  Surulere     BBQ Philly Steak   4000         2

          Time  Revenue  Snap
4570  09:35:57    20000  4005
4571  09:35:58    20000  4005
4572  09:35:58     8000  2004
4573  09:35:59    20000  4005
4574  09:35:59     8000  4002
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
4575  4576  2015-12-10     Ikoyi   Chicken Legend   2000         1  09:35:59
4576  4577  2015-12-12  Surulere  Pepperoni Feast   4000         3  09:36:00
4577  4578  2015-12-13    Ibadan  Pepperoni Feast   4000         5  09:36:00
4578  4579  2015-12-10   Gbagada     Chicken Suya   4000         3  09:36:02
4579  4580  2015-12-09     Ikoyi        Beef Suya   3000         2  09:36:02

      Revenue  Snap
4575     2000  2001
4576    12000  4003
4577    20000  4005
4578    12000  4003
4579     6000  3002
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
4580  4581  2015-12-08    Ibadan  Pepperoni Feast   4000         5  09:36:02
4581  4582  2015-12-11     Ikoyi     Extravaganza   2000         3  09:36:03
4582  4583  2015-12-07    Ibadan       Hot Veggie   4000         4  09:36:03
4583  4584  2015-12-12   Gbagada   Chicken Legend   2000         4  09:36:04
4584  4585  2015-12-11  Surulere    Chicken Feast   2000         4  09:36:04

      Revenue  Snap
4580    20000  4005
4581     6000  2003
4582    16000  4004
4583     8000  2004
4584     8000  2004
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
4585  4586  2015-12-05     Lekki        Margarita   4000         5  09:36:05
4586  4587  2015-12-09  Surulere   Chicken Legend   2000         4  09:36:06
4587  4588  2015-12-04   Gbagada   Veggie Supreme   3000         1  09:36:06
4588  4589  2015-12-10     Ikoyi  Pepperoni Feast   4000         1  09:36:07
4589  4590  2015-12-12  Surulere         Italiano   3000         2  09:36:07

      Revenue  Snap
4585    20000  4005
4586     8000  2004
4587     3000  3001
4588     4000  4001
4589     6000  3002
CHUNK BOSS
       S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
4590  4591  2015-12-07   Ibadan  Pepperoni Feast   4000         1  09:36:10
4591  4592  2015-12-13  Gbagada         Italiano   3000         1  09:36:12
4592  4593  2015-12-07    Lekki     Chicken Bali   2000         1  09:36:12
4593  4594  2015-12-08    Ikoyi      BBQ Chicken   4000         5  09:36:12
4594  4595  2015-12-08  Gbagada    Chicken Feast   2000         5  09:36:13

      Revenue  Snap
4590     4000  4001
4591     3000  3001
4592     2000  2001
4593    20000  4005
4594    10000  2005
CHUNK BOSS
       S/N        Date  Branch       Pizza Sold  Price  Quantity      Time  \
4595  4596  2015-12-13   Ikoyi     Chicken Suya   4000         2  09:36:13
4596  4597  2015-12-13  Ibadan  Pepperoni Feast   4000         3  09:36:14
4597  4598  2015-12-12   Lekki     Chicken Bali   2000         1  09:36:14
4598  4599  2015-12-10  Ibadan   Pepperoni Suya   3000         3  09:36:14
4599  4600  2015-12-15  Ibadan     Chicken Suya   4000         4  09:36:14

      Revenue  Snap
4595     8000  4002
4596    12000  4003
4597     2000  2001
4598     9000  3003
4599    16000  4004
CHUNK BOSS
       S/N        Date  Branch           Pizza Sold  Price  Quantity  \
4600  4601  2015-12-06  Ibadan        Chicken Feast   2000         3
4601  4602  2015-12-04  Ibadan            Beef Suya   3000         5
4602  4603  2015-12-07   Ikoyi       Veggie Supreme   3000         2
4603  4604  2015-12-10  Ibadan  Hot Pepperoni Feast   4000         4
4604  4605  2015-12-14   Lekki         Chicken Bali   2000         2

          Time  Revenue  Snap
4600  09:36:16     6000  2003
4601  09:36:17    15000  3005
4602  09:36:17     6000  3002
4603  09:36:19    16000  4004
4604  09:36:19     4000  2002
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4605  4606  2015-12-10   Gbagada    Chicken Bali   2000         5  09:36:21
4606  4607  2015-12-07  Surulere  Veggie Supreme   3000         2  09:36:23
4607  4608  2015-12-15     Ikoyi        Italiano   3000         4  09:36:24
4608  4609  2015-12-10  Surulere  Pepperoni Suya   3000         1  09:36:25
4609  4610  2015-12-14     Ikoyi       Beef Suya   3000         4  09:36:25

      Revenue  Snap
4605    10000  2005
4606     6000  3002
4607    12000  3004
4608     3000  3001
4609    12000  3004
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
4610  4611  2015-12-03    Ikoyi          Italiano   3000         2  09:36:26
4611  4612  2015-12-12    Lekki      Extravaganza   2000         4  09:36:27
4612  4613  2015-12-03    Lekki    Pepperoni Suya   3000         4  09:36:27
4613  4614  2015-12-10  Gbagada  BBQ Philly Steak   4000         1  09:36:27
4614  4615  2015-12-04  Gbagada     Chicken Feast   2000         5  09:36:30

      Revenue  Snap
4610     6000  3002
4611     8000  2004
4612    12000  3004
4613     4000  4001
4614    10000  2005
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4615  4616  2015-12-08     Ikoyi  Pepperoni Suya   3000         3  09:36:32
4616  4617  2015-12-09    Ibadan    Chicken Bali   2000         5  09:36:33
4617  4618  2015-12-11     Ikoyi        Italiano   3000         3  09:36:33
4618  4619  2015-12-04  Surulere  Veggie Supreme   3000         1  09:36:33
4619  4620  2015-12-11     Ikoyi       Margarita   4000         3  09:36:34

      Revenue  Snap
4615     9000  3003
4616    10000  2005
4617     9000  3003
4618     3000  3001
4619    12000  4003
CHUNK BOSS
       S/N        Date  Branch      Pizza Sold  Price  Quantity      Time  \
4620  4621  2015-12-06   Lekki  Pepperoni Suya   3000         1  09:36:34
4621  4622  2015-12-12  Ibadan   Chicken Feast   2000         1  09:36:34
4622  4623  2015-12-04  Ibadan       Margarita   4000         4  09:36:36
4623  4624  2015-12-11  Ibadan      Hot Veggie   4000         1  09:36:36
4624  4625  2015-12-05   Lekki       Margarita   4000         1  09:36:36

      Revenue  Snap
4620     3000  3001
4621     2000  2001
4622    16000  4004
4623     4000  4001
4624     4000  4001
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
4625  4626  2015-12-05     Ikoyi      Extravaganza   2000         4  09:36:37
4626  4627  2015-12-13     Lekki           Meatzaa   2000         2  09:36:37
4627  4628  2015-12-09    Ibadan  BBQ Philly Steak   4000         1  09:36:39
4628  4629  2015-12-11     Lekki      Extravaganza   2000         4  09:36:39
4629  4630  2015-12-09  Surulere  BBQ Philly Steak   4000         4  09:36:41

      Revenue  Snap
4625     8000  2004
4626     4000  2002
4627     4000  4001
4628     8000  2004
4629    16000  4004
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4630  4631  2015-12-06   Gbagada           Hot Veggie   4000         3
4631  4632  2015-12-08    Ibadan  Hot Pepperoni Feast   4000         1
4632  4633  2015-12-07  Surulere         Chicken Suya   4000         5
4633  4634  2015-12-12  Surulere      Pepperoni Feast   4000         1
4634  4635  2015-12-12  Surulere       Chicken Legend   2000         3

          Time  Revenue  Snap
4630  09:36:42    12000  4003
4631  09:36:44     4000  4001
4632  09:36:44    20000  4005
4633  09:36:44     4000  4001
4634  09:36:46     6000  2003

CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
4635  4636  2015-12-07    Lekki         Extravaganza   2000         3
4636  4637  2015-12-04   Ibadan         Extravaganza   2000         3
4637  4638  2015-12-11  Gbagada       Pepperoni Suya   3000         3
4638  4639  2015-12-04   Ibadan  Hot Pepperoni Feast   4000         2
4639  4640  2015-12-10  Gbagada       Chicken Legend   2000         4

          Time  Revenue  Snap
4635  09:36:46     6000  2003
4636  09:36:47     6000  2003
4637  09:36:48     9000  3003
4638  09:36:49     8000  4002
4639  09:36:49     8000  2004
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
4640  4641  2015-12-13  Gbagada  Hot Pepperoni Feast   4000         3
4641  4642  2015-12-04   Ibadan       Chicken Legend   2000         5
4642  4643  2015-12-03    Ikoyi         Extravaganza   2000         5
4643  4644  2015-12-08    Ikoyi         Extravaganza   2000         3
4644  4645  2015-12-03   Ibadan          BBQ Chicken   4000         5

          Time  Revenue  Snap
4640  09:36:50    12000  4003
4641  09:36:50    10000  2005
4642  09:36:51    10000  2005
4643  09:36:51     6000  2003
4644  09:36:52    20000  4005
CHUNK BOSS
       S/N        Date  Branch       Pizza Sold  Price  Quantity      Time  \
4645  4646  2015-12-09   Lekki   Veggie Supreme   3000         5  09:36:52
4646  4647  2015-12-14  Ibadan    Chicken Feast   2000         2  09:36:53
4647  4648  2015-12-10  Ibadan        Margarita   4000         4  09:36:53
4648  4649  2015-12-06  Ibadan  Pepperoni Feast   4000         2  09:36:55
4649  4650  2015-12-03  Ibadan     Chicken Bali   2000         2  09:36:59

      Revenue  Snap
4645    15000  3005
4646     4000  2002
4647    16000  4004
4648     8000  4002
4649     4000  2002
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4650  4651  2015-12-13    Ibadan        Chicken Feast   2000         1
4651  4652  2015-12-07     Ikoyi             Italiano   3000         2
4652  4653  2015-12-12   Gbagada  Hot Pepperoni Feast   4000         3
4653  4654  2015-12-14     Lekki     BBQ Philly Steak   4000         5
4654  4655  2015-12-10  Surulere          BBQ Chicken   4000         2

          Time  Revenue  Snap
4650  09:37:00     2000  2001
4651  09:37:00     6000  3002
4652  09:37:01    12000  4003
4653  09:37:02    20000  4005
4654  09:37:03     8000  4002
CHUNK BOSS
       S/N        Date    Branch    Pizza Sold  Price  Quantity      Time  \
4655  4656  2015-12-07     Ikoyi     Margarita   4000         1  09:37:05
4656  4657  2015-12-14    Ibadan  Chicken Bali   2000         5  09:37:05
4657  4658  2015-12-05     Ikoyi  Chicken Bali   2000         1  09:37:05
4658  4659  2015-12-12    Ibadan       Meatzaa   2000         1  09:37:06
4659  4660  2015-12-15  Surulere  Chicken Suya   4000         5  09:37:07

      Revenue  Snap
4655     4000  4001
4656    10000  2005
4657     2000  2001
4658     2000  2001
4659    20000  4005
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
4660  4661  2015-12-07  Gbagada       Beef Suya   3000         4  09:37:07
4661  4662  2015-12-11   Ibadan  Chicken Legend   2000         2  09:37:07
4662  4663  2015-12-07   Ibadan    Chicken Bali   2000         1  09:37:08
4663  4664  2015-12-12  Gbagada      Hot Veggie   4000         2  09:37:10
4664  4665  2015-12-09   Ibadan      Hot Veggie   4000         2  09:37:11

      Revenue  Snap
4660    12000  3004
4661     4000  2002
4662     2000  2001
4663     8000  4002
4664     8000  4002
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
4665  4666  2015-12-15  Gbagada         Extravaganza   2000         1
4666  4667  2015-12-12   Ibadan       Veggie Supreme   3000         2
4667  4668  2015-12-05   Ibadan  Hot Pepperoni Feast   4000         2
4668  4669  2015-12-12   Ibadan              Meatzaa   2000         3
4669  4670  2015-12-09   Ibadan       Chicken Legend   2000         4

          Time  Revenue  Snap
4665  09:37:14     2000  2001
4666  09:37:15     6000  3002
4667  09:37:18     8000  4002
4668  09:37:18     6000  2003
4669  09:37:19     8000  2004
CHUNK BOSS
       S/N        Date    Branch    Pizza Sold  Price  Quantity      Time  \
4670  4671  2015-12-08   Gbagada  Chicken Bali   2000         1  09:37:19
4671  4672  2015-12-04     Lekki     Margarita   4000         2  09:37:20
4672  4673  2015-12-14    Ibadan      Italiano   3000         5  09:37:20
4673  4674  2015-12-06     Lekki    Hot Veggie   4000         5  09:37:21
4674  4675  2015-12-12  Surulere  Chicken Suya   4000         2  09:37:22

      Revenue  Snap
4670     2000  2001
4671     8000  4002
4672    15000  3005
4673    20000  4005
4674     8000  4002
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4675  4676  2015-12-06     Lekki  Pepperoni Suya   3000         1  09:37:23
4676  4677  2015-12-08     Ikoyi       Beef Suya   3000         1  09:37:25
4677  4678  2015-12-05  Surulere       Margarita   4000         3  09:37:25
4678  4679  2015-12-07    Ibadan     BBQ Chicken   4000         3  09:37:26
4679  4680  2015-12-03    Ibadan  Pepperoni Suya   3000         5  09:37:27

      Revenue  Snap
4675     3000  3001
4676     3000  3001
4677    12000  4003
4678    12000  4003
4679    15000  3005
CHUNK BOSS
       S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
4680  4681  2015-12-06   Ibadan     Chicken Bali   2000         1  09:37:27
4681  4682  2015-12-15  Gbagada          Meatzaa   2000         5  09:37:29
4682  4683  2015-12-10    Lekki         Italiano   3000         5  09:37:31
4683  4684  2015-12-08  Gbagada      BBQ Chicken   4000         1  09:37:31
4684  4685  2015-12-11    Ikoyi  Pepperoni Feast   4000         5  09:37:33

      Revenue  Snap
4680     2000  2001
4681    10000  2005
4682    15000  3005
4683     4000  4001
4684    20000  4005
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4685  4686  2015-12-06     Ikoyi    Chicken Suya   4000         1  09:37:38
4686  4687  2015-12-10  Surulere  Chicken Legend   2000         4  09:37:38
4687  4688  2015-12-07     Ikoyi      Hot Veggie   4000         4  09:37:39
4688  4689  2015-12-07   Gbagada         Meatzaa   2000         3  09:37:39
4689  4690  2015-12-07  Surulere    Extravaganza   2000         2  09:37:39

      Revenue  Snap
4685     4000  4001
4686     8000  2004
4687    16000  4004
4688     6000  2003
4689     4000  2002
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4690  4691  2015-12-09   Gbagada  Chicken Legend   2000         2  09:37:40
4691  4692  2015-12-04  Surulere    Chicken Bali   2000         3  09:37:41
4692  4693  2015-12-12     Lekki       Beef Suya   3000         5  09:37:41
4693  4694  2015-12-07     Lekki        Italiano   3000         5  09:37:41
4694  4695  2015-12-07     Ikoyi     BBQ Chicken   4000         3  09:37:41

      Revenue  Snap
4690     4000  2002
4691     6000  2003
4692    15000  3005
4693    15000  3005
4694    12000  4003
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
4695  4696  2015-12-13    Lekki  Chicken Legend   2000         2  09:37:44
4696  4697  2015-12-04    Lekki  Chicken Legend   2000         3  09:37:44
4697  4698  2015-12-06  Gbagada  Veggie Supreme   3000         4  09:37:45
4698  4699  2015-12-05  Gbagada        Italiano   3000         4  09:37:45
4699  4700  2015-12-15    Lekki  Veggie Supreme   3000         3  09:37:47

      Revenue  Snap
4695     4000  2002
4696     6000  2003
4697    12000  3004
4698    12000  3004
4699     9000  3003
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
4700  4701  2015-12-11  Gbagada  Pepperoni Suya   3000         1  09:37:49
4701  4702  2015-12-14   Ibadan  Veggie Supreme   3000         3  09:37:49
4702  4703  2015-12-05    Ikoyi  Chicken Legend   2000         3  09:37:49
4703  4704  2015-12-14    Lekki      Hot Veggie   4000         2  09:37:50
4704  4705  2015-12-06    Ikoyi  Veggie Supreme   3000         3  09:37:50

      Revenue  Snap
4700     3000  3001
4701     9000  3003
4702     6000  2003
4703     8000  4002
4704     9000  3003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4705  4706  2015-12-09    Ibadan       Pepperoni Suya   3000         2
4706  4707  2015-12-11     Lekki         Chicken Suya   4000         3
4707  4708  2015-12-08  Surulere  Hot Pepperoni Feast   4000         4
4708  4709  2015-12-11     Ikoyi  Hot Pepperoni Feast   4000         3
4709  4710  2015-12-04  Surulere       Pepperoni Suya   3000         4

          Time  Revenue  Snap
4705  09:37:50     6000  3002
4706  09:37:50    12000  4003
4707  09:37:51    16000  4004
4708  09:37:51    12000  4003
4709  09:37:54    12000  3004
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4710  4711  2015-12-11     Ikoyi         Chicken Suya   4000         3
4711  4712  2015-12-04    Ibadan        Chicken Feast   2000         3
4712  4713  2015-12-12  Surulere           Hot Veggie   4000         2
4713  4714  2015-12-07    Ibadan      Pepperoni Feast   4000         3
4714  4715  2015-12-09     Lekki  Hot Pepperoni Feast   4000         1

          Time  Revenue  Snap
4710  09:37:55    12000  4003
4711  09:37:57     6000  2003
4712  09:37:58     8000  4002
4713  09:37:58    12000  4003
4714  09:38:01     4000  4001
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4715  4716  2015-12-08     Ikoyi            Beef Suya   3000         3
4716  4717  2015-12-03   Gbagada         Chicken Suya   4000         4
4717  4718  2015-12-15  Surulere          BBQ Chicken   4000         2
4718  4719  2015-12-10     Ikoyi  Hot Pepperoni Feast   4000         5
4719  4720  2015-12-08     Lekki          BBQ Chicken   4000         1

          Time  Revenue  Snap
4715  09:38:01     9000  3003
4716  09:38:02    16000  4004
4717  09:38:03     8000  4002
4718  09:38:04    20000  4005
4719  09:38:05     4000  4001
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
4720  4721  2015-12-13   Gbagada  BBQ Philly Steak   4000         5  09:38:05
4721  4722  2015-12-10    Ibadan      Extravaganza   2000         5  09:38:06
4722  4723  2015-12-15  Surulere    Veggie Supreme   3000         3  09:38:06
4723  4724  2015-12-14     Lekki         Beef Suya   3000         2  09:38:07
4724  4725  2015-12-13     Ikoyi     Chicken Feast   2000         5  09:38:08

      Revenue  Snap
4720    20000  4005
4721    10000  2005
4722     9000  3003
4723     6000  3002
4724    10000  2005
CHUNK BOSS
       S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
4725  4726  2015-12-14  Gbagada     Extravaganza   2000         3  09:38:09
4726  4727  2015-12-03    Ikoyi   Pepperoni Suya   3000         5  09:38:10
4727  4728  2015-12-09    Ikoyi   Veggie Supreme   3000         2  09:38:11
4728  4729  2015-12-11    Lekki  Pepperoni Feast   4000         4  09:38:12
4729  4730  2015-12-09   Ibadan         Italiano   3000         5  09:38:12

      Revenue  Snap
4725     6000  2003
4726    15000  3005
4727     6000  3002
4728    16000  4004
4729    15000  3005
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
4730  4731  2015-12-14    Ibadan         Margarita   4000         3  09:38:13
4731  4732  2015-12-10     Ikoyi          Italiano   3000         3  09:38:14
4732  4733  2015-12-04  Surulere    Pepperoni Suya   3000         2  09:38:16
4733  4734  2015-12-12  Surulere  BBQ Philly Steak   4000         5  09:38:17
4734  4735  2015-12-07     Lekki           Meatzaa   2000         2  09:38:19

      Revenue  Snap
4730    12000  4003
4731     9000  3003
4732     6000  3002
4733    20000  4005
4734     4000  2002

CHUNK BOSS
       S/N        Date    Branch    Pizza Sold  Price  Quantity      Time  \
4735  4736  2015-12-12  Surulere  Chicken Suya   4000         1  09:38:20
4736  4737  2015-12-03  Surulere   BBQ Chicken   4000         1  09:38:20
4737  4738  2015-12-11  Surulere  Chicken Bali   2000         5  09:38:20
4738  4739  2015-12-15    Ibadan  Extravaganza   2000         3  09:38:20
4739  4740  2015-12-07   Gbagada  Chicken Bali   2000         2  09:38:22

      Revenue  Snap
4735     4000  4001
4736     4000  4001
4737    10000  2005
4738     6000  2003
4739     4000  2002
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4740  4741  2015-12-15  Surulere       Margarita   4000         4  09:38:22
4741  4742  2015-12-12     Lekki    Chicken Suya   4000         1  09:38:24
4742  4743  2015-12-06   Gbagada  Chicken Legend   2000         3  09:38:24
4743  4744  2015-12-11  Surulere    Chicken Bali   2000         3  09:38:25
4744  4745  2015-12-07     Lekki  Veggie Supreme   3000         2  09:38:26

      Revenue  Snap
4740    16000  4004
4741     4000  4001
4742     6000  2003
4743     6000  2003
4744     6000  3002
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
4745  4746  2015-12-13    Lekki        Chicken Feast   2000         4
4746  4747  2015-12-05  Gbagada  Hot Pepperoni Feast   4000         3
4747  4748  2015-12-11  Gbagada         Chicken Suya   4000         5
4748  4749  2015-12-03   Ibadan            Margarita   4000         4
4749  4750  2015-12-09    Ikoyi       Veggie Supreme   3000         2

          Time  Revenue  Snap
4745  09:38:26     8000  2004
4746  09:38:27    12000  4003
4747  09:38:27    20000  4005
4748  09:38:29    16000  4004
4749  09:38:30     6000  3002
CHUNK BOSS
       S/N        Date  Branch           Pizza Sold  Price  Quantity  \
4750  4751  2015-12-05  Ibadan             Italiano   3000         1
4751  4752  2015-12-10  Ibadan            Beef Suya   3000         4
4752  4753  2015-12-07  Ibadan        Chicken Feast   2000         3
4753  4754  2015-12-04   Lekki      Pepperoni Feast   4000         2
4754  4755  2015-12-12  Ibadan  Hot Pepperoni Feast   4000         1

          Time  Revenue  Snap
4750  09:38:31     3000  3001
4751  09:38:31    12000  3004
4752  09:38:33     6000  2003
4753  09:38:33     8000  4002
4754  09:38:34     4000  4001
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4755  4756  2015-12-07     Lekki     BBQ Philly Steak   4000         3
4756  4757  2015-12-06  Surulere          BBQ Chicken   4000         1
4757  4758  2015-12-12    Ibadan  Hot Pepperoni Feast   4000         4
4758  4759  2015-12-07   Gbagada             Italiano   3000         5
4759  4760  2015-12-07     Lekki  Hot Pepperoni Feast   4000         4

          Time  Revenue  Snap
4755  09:38:34    12000  4003
4756  09:38:34     4000  4001
4757  09:38:35    16000  4004
4758  09:38:35    15000  3005
4759  09:38:36    16000  4004
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4760  4761  2015-12-10  Surulere            Beef Suya   3000         2
4761  4762  2015-12-04  Surulere              Meatzaa   2000         5
4762  4763  2015-12-03     Ikoyi              Meatzaa   2000         2
4763  4764  2015-12-03     Ikoyi       Veggie Supreme   3000         5
4764  4765  2015-12-12   Gbagada  Hot Pepperoni Feast   4000         2

          Time  Revenue  Snap
4760  09:38:37     6000  3002
4761  09:38:37    10000  2005
4762  09:38:38     4000  2002
4763  09:38:39    15000  3005
4764  09:38:39     8000  4002
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4765  4766  2015-12-07   Gbagada            Beef Suya   3000         2
4766  4767  2015-12-09  Surulere       Pepperoni Suya   3000         1
4767  4768  2015-12-06   Gbagada       Chicken Legend   2000         2
4768  4769  2015-12-11     Lekki  Hot Pepperoni Feast   4000         5
4769  4770  2015-12-13     Lekki            Beef Suya   3000         4

          Time  Revenue  Snap
4765  09:38:39     6000  3002
4766  09:38:40     3000  3001
4767  09:38:40     4000  2002
4768  09:38:41    20000  4005
4769  09:38:42    12000  3004
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4770  4771  2015-12-07   Gbagada           Hot Veggie   4000         2
4771  4772  2015-12-12   Gbagada        Chicken Feast   2000         2
4772  4773  2015-12-06  Surulere  Hot Pepperoni Feast   4000         1
4773  4774  2015-12-05     Ikoyi  Hot Pepperoni Feast   4000         5
4774  4775  2015-12-08   Gbagada          BBQ Chicken   4000         5

          Time  Revenue  Snap
4770  09:38:42     8000  4002
4771  09:38:43     4000  2002
4772  09:38:43     4000  4001
4773  09:38:44    20000  4005
4774  09:38:44    20000  4005
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4775  4776  2015-12-03    Ibadan       Margarita   4000         4  09:38:46
4776  4777  2015-12-13   Gbagada         Meatzaa   2000         5  09:38:46
4777  4778  2015-12-14    Ibadan  Chicken Legend   2000         3  09:38:46
4778  4779  2015-12-14     Lekki    Extravaganza   2000         2  09:38:47
4779  4780  2015-12-15  Surulere       Margarita   4000         5  09:38:48

      Revenue  Snap
4775    16000  4004
4776    10000  2005
4777     6000  2003
4778     4000  2002
4779    20000  4005
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
4780  4781  2015-12-05    Lekki       Margarita   4000         1  09:38:50
4781  4782  2015-12-07  Gbagada       Beef Suya   3000         3  09:38:51
4782  4783  2015-12-06    Ikoyi  Pepperoni Suya   3000         3  09:38:52
4783  4784  2015-12-14    Ikoyi        Italiano   3000         3  09:38:52
4784  4785  2015-12-06    Ikoyi    Chicken Suya   4000         3  09:38:53

      Revenue  Snap
4780     4000  4001
4781     9000  3003
4782     9000  3003
4783     9000  3003
4784    12000  4003
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
4785  4786  2015-12-03  Surulere      Extravaganza   2000         2  09:38:54
4786  4787  2015-12-07    Ibadan      Chicken Suya   4000         4  09:38:55
4787  4788  2015-12-15   Gbagada      Extravaganza   2000         4  09:38:56
4788  4789  2015-12-12     Lekki      Chicken Suya   4000         3  09:38:57
4789  4790  2015-12-13     Ikoyi  BBQ Philly Steak   4000         4  09:38:58

      Revenue  Snap
4785     4000  2002
4786    16000  4004
4787     8000  2004
4788    12000  4003
4789    16000  4004
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
4790  4791  2015-12-12  Surulere      BBQ Chicken   4000         5  09:38:59
4791  4792  2015-12-12    Ibadan   Chicken Legend   2000         1  09:39:00
4792  4793  2015-12-13   Gbagada  Pepperoni Feast   4000         2  09:39:00
4793  4794  2015-12-12     Lekki         Italiano   3000         4  09:39:00
4794  4795  2015-12-07   Gbagada    Chicken Feast   2000         5  09:39:00

      Revenue  Snap
4790    20000  4005
4791     2000  2001
4792     8000  4002
4793    12000  3004
4794    10000  2005
CHUNK BOSS
       S/N        Date  Branch           Pizza Sold  Price  Quantity  \
4795  4796  2015-12-10   Ikoyi       Veggie Supreme   3000         1
4796  4797  2015-12-12  Ibadan  Hot Pepperoni Feast   4000         3
4797  4798  2015-12-04   Ikoyi            Margarita   4000         1
4798  4799  2015-12-06  Ibadan              Meatzaa   2000         2
4799  4800  2015-12-09   Ikoyi       Veggie Supreme   3000         4

          Time  Revenue  Snap
4795  09:39:00     3000  3001
4796  09:39:01    12000  4003
4797  09:39:04     4000  4001
4798  09:39:04     4000  2002
4799  09:39:06    12000  3004
CHUNK BOSS
       S/N        Date  Branch        Pizza Sold  Price  Quantity      Time  \
4800  4801  2015-12-11  Ibadan         Beef Suya   3000         1  09:39:09
4801  4802  2015-12-08   Lekki  BBQ Philly Steak   4000         5  09:39:10
4802  4803  2015-12-15   Lekki          Italiano   3000         2  09:39:11
4803  4804  2015-12-12   Ikoyi      Chicken Suya   4000         2  09:39:11
4804  4805  2015-12-07   Ikoyi        Hot Veggie   4000         5  09:39:11

      Revenue  Snap
4800     3000  3001
4801    20000  4005
4802     6000  3002
4803     8000  4002
4804    20000  4005
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
4805  4806  2015-12-09    Ibadan   Pepperoni Suya   3000         1  09:39:12
4806  4807  2015-12-03  Surulere         Italiano   3000         4  09:39:12
4807  4808  2015-12-14    Ibadan        Margarita   4000         5  09:39:14
4808  4809  2015-12-07     Lekki  Pepperoni Feast   4000         3  09:39:14
4809  4810  2015-12-13    Ibadan    Chicken Feast   2000         3  09:39:14

      Revenue  Snap
4805     3000  3001
4806    12000  3004
4807    20000  4005
4808    12000  4003
4809     6000  2003
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
4810  4811  2015-12-06    Lekki   Pepperoni Feast   4000         5  09:39:18
4811  4812  2015-12-03    Lekki    Veggie Supreme   3000         2  09:39:18
4812  4813  2015-12-04    Lekki  BBQ Philly Steak   4000         1  09:39:18
4813  4814  2015-12-13  Gbagada    Veggie Supreme   3000         1  09:39:19
4814  4815  2015-12-08    Ikoyi       BBQ Chicken   4000         5  09:39:20

      Revenue  Snap
4810    20000  4005
4811     6000  3002
4812     4000  4001
4813     3000  3001
4814    20000  4005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4815  4816  2015-12-14   Gbagada  Hot Pepperoni Feast   4000         4
4816  4817  2015-12-15    Ibadan       Pepperoni Suya   3000         2
4817  4818  2015-12-14   Gbagada       Chicken Legend   2000         3
4818  4819  2015-12-08     Lekki     BBQ Philly Steak   4000         2
4819  4820  2015-12-11  Surulere              Meatzaa   2000         5

          Time  Revenue  Snap
4815  09:39:20    16000  4004
4816  09:39:21     6000  3002
4817  09:39:21     6000  2003
4818  09:39:21     8000  4002
4819  09:39:22    10000  2005
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4820  4821  2015-12-04    Ibadan       Margarita   4000         5  09:39:22
4821  4822  2015-12-09     Lekki     BBQ Chicken   4000         4  09:39:23
4822  4823  2015-12-11     Ikoyi  Chicken Legend   2000         4  09:39:23
4823  4824  2015-12-06  Surulere    Chicken Bali   2000         2  09:39:24
4824  4825  2015-12-05    Ibadan      Hot Veggie   4000         2  09:39:27

      Revenue  Snap
4820    20000  4005
4821    16000  4004
4822     8000  2004
4823     4000  2002
4824     8000  4002
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4825  4826  2015-12-12   Gbagada     BBQ Chicken   4000         4  09:39:28
4826  4827  2015-12-10    Ibadan  Chicken Legend   2000         3  09:39:29
4827  4828  2015-12-14  Surulere         Meatzaa   2000         3  09:39:29
4828  4829  2015-12-15  Surulere      Hot Veggie   4000         1  09:39:30
4829  4830  2015-12-14     Lekki    Extravaganza   2000         2  09:39:30

      Revenue  Snap
4825    16000  4004
4826     6000  2003
4827     6000  2003
4828     4000  4001
4829     4000  2002
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
4830  4831  2015-12-07  Surulere       BBQ Chicken   4000         1  09:39:31
4831  4832  2015-12-11   Gbagada    Pepperoni Suya   3000         4  09:39:31
4832  4833  2015-12-04   Gbagada   Pepperoni Feast   4000         4  09:39:31
4833  4834  2015-12-08   Gbagada  BBQ Philly Steak   4000         2  09:39:33
4834  4835  2015-12-05    Ibadan     Chicken Feast   2000         2  09:39:34

      Revenue  Snap
4830     4000  4001
4831    12000  3004
4832    16000  4004
4833     8000  4002
4834     4000  2002

CHUNK BOSS
       S/N        Date    Branch     Pizza Sold  Price  Quantity      Time  \
4835  4836  2015-12-04    Ibadan  Chicken Feast   2000         5  09:39:35
4836  4837  2015-12-09    Ibadan       Italiano   3000         5  09:39:35
4837  4838  2015-12-09    Ibadan  Chicken Feast   2000         5  09:39:35
4838  4839  2015-12-12  Surulere      Margarita   4000         1  09:39:37
4839  4840  2015-12-07    Ibadan        Meatzaa   2000         1  09:39:38

      Revenue  Snap
4835    10000  2005
4836    15000  3005
4837    10000  2005
4838     4000  4001
4839     2000  2001
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4840  4841  2015-12-11     Lekki        Italiano   3000         5  09:39:38
4841  4842  2015-12-12     Lekki       Beef Suya   3000         4  09:39:38
4842  4843  2015-12-13  Surulere  Veggie Supreme   3000         5  09:39:39
4843  4844  2015-12-10     Ikoyi  Veggie Supreme   3000         4  09:39:40
4844  4845  2015-12-08     Lekki         Meatzaa   2000         3  09:39:41

      Revenue  Snap
4840    15000  3005
4841    12000  3004
4842    15000  3005
4843    12000  3004
4844     6000  2003
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
4845  4846  2015-12-13   Ibadan  Hot Pepperoni Feast   4000         4
4846  4847  2015-12-09    Lekki            Beef Suya   3000         4
4847  4848  2015-12-14   Ibadan         Extravaganza   2000         3
4848  4849  2015-12-07  Gbagada      Pepperoni Feast   4000         5
4849  4850  2015-12-14   Ibadan             Italiano   3000         4

          Time  Revenue  Snap
4845  09:39:42    16000  4004
4846  09:39:42    12000  3004
4847  09:39:42     6000  2003
4848  09:39:42    20000  4005
4849  09:39:42    12000  3004
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4850  4851  2015-12-08    Ibadan        Italiano   3000         4  09:39:42
4851  4852  2015-12-12  Surulere   Chicken Feast   2000         4  09:39:43
4852  4853  2015-12-11     Ikoyi       Beef Suya   3000         4  09:39:43
4853  4854  2015-12-08   Gbagada  Veggie Supreme   3000         4  09:39:44
4854  4855  2015-12-15     Ikoyi    Chicken Bali   2000         2  09:39:44

      Revenue  Snap
4850    12000  3004
4851     8000  2004
4852    12000  3004
4853    12000  3004
4854     4000  2002
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4855  4856  2015-12-09   Gbagada  Pepperoni Suya   3000         4  09:39:44
4856  4857  2015-12-05     Ikoyi        Italiano   3000         4  09:39:44
4857  4858  2015-12-07  Surulere  Pepperoni Suya   3000         1  09:39:48
4858  4859  2015-12-08     Ikoyi        Italiano   3000         4  09:39:49
4859  4860  2015-12-10  Surulere    Chicken Suya   4000         4  09:39:49

      Revenue  Snap
4855    12000  3004
4856    12000  3004
4857     3000  3001
4858    12000  3004
4859    16000  4004
CHUNK BOSS
       S/N        Date    Branch    Pizza Sold  Price  Quantity      Time  \
4860  4861  2015-12-15   Gbagada  Extravaganza   2000         1  09:39:49
4861  4862  2015-12-08     Ikoyi     Beef Suya   3000         3  09:39:49
4862  4863  2015-12-08     Ikoyi  Chicken Bali   2000         1  09:39:50
4863  4864  2015-12-04  Surulere  Extravaganza   2000         2  09:39:52
4864  4865  2015-12-04   Gbagada    Hot Veggie   4000         2  09:39:53

      Revenue  Snap
4860     2000  2001
4861     9000  3003
4862     2000  2001
4863     4000  2002
4864     8000  4002
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4865  4866  2015-12-04  Surulere            Beef Suya   3000         1
4866  4867  2015-12-11   Gbagada         Chicken Suya   4000         3
4867  4868  2015-12-10     Ikoyi       Veggie Supreme   3000         4
4868  4869  2015-12-12    Ibadan  Hot Pepperoni Feast   4000         4
4869  4870  2015-12-09     Lekki         Chicken Suya   4000         5

          Time  Revenue  Snap
4865  09:39:54     3000  3001
4866  09:39:54    12000  4003
4867  09:39:56    12000  3004
4868  09:39:59    16000  4004
4869  09:39:59    20000  4005
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4870  4871  2015-12-03    Ibadan  Hot Pepperoni Feast   4000         4
4871  4872  2015-12-05     Ikoyi  Hot Pepperoni Feast   4000         4
4872  4873  2015-12-14  Surulere         Chicken Suya   4000         3
4873  4874  2015-12-04     Ikoyi     BBQ Philly Steak   4000         2
4874  4875  2015-12-14   Gbagada       Chicken Legend   2000         2

          Time  Revenue  Snap
4870  09:40:02    16000  4004
4871  09:40:03    16000  4004
4872  09:40:04    12000  4003
4873  09:40:04     8000  4002
4874  09:40:05     4000  2002
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
4875  4876  2015-12-11  Surulere  Pepperoni Feast   4000         3  09:40:06
4876  4877  2015-12-14   Gbagada  Pepperoni Feast   4000         1  09:40:07
4877  4878  2015-12-04     Lekki    Chicken Feast   2000         2  09:40:08
4878  4879  2015-12-07  Surulere        Beef Suya   3000         4  09:40:09
4879  4880  2015-12-11  Surulere      BBQ Chicken   4000         1  09:40:09

      Revenue  Snap
4875    12000  4003
4876     4000  4001
4877     4000  2002
4878    12000  3004
4879     4000  4001
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
4880  4881  2015-12-07     Ikoyi        Beef Suya   3000         4  09:40:11
4881  4882  2015-12-03     Ikoyi  Pepperoni Feast   4000         3  09:40:12
4882  4883  2015-12-05  Surulere   Pepperoni Suya   3000         5  09:40:13
4883  4884  2015-12-07  Surulere        Margarita   4000         4  09:40:15
4884  4885  2015-12-03     Lekki   Pepperoni Suya   3000         4  09:40:16

      Revenue  Snap
4880    12000  3004
4881    12000  4003
4882    15000  3005
4883    16000  4004
4884    12000  3004
CHUNK BOSS
       S/N        Date  Branch        Pizza Sold  Price  Quantity      Time  \
4885  4886  2015-12-13   Lekki    Pepperoni Suya   3000         1  09:40:16
4886  4887  2015-12-11   Ikoyi     Chicken Feast   2000         2  09:40:17
4887  4888  2015-12-05  Ibadan          Italiano   3000         2  09:40:17
4888  4889  2015-12-05   Ikoyi         Beef Suya   3000         1  09:40:17
4889  4890  2015-12-05  Ibadan  BBQ Philly Steak   4000         3  09:40:20

      Revenue  Snap
4885     3000  3001
4886     4000  2002
4887     6000  3002
4888     3000  3001
4889    12000  4003
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
4890  4891  2015-12-11   Gbagada   Veggie Supreme   3000         5  09:40:21
4891  4892  2015-12-08     Ikoyi  Pepperoni Feast   4000         2  09:40:22
4892  4893  2015-12-15  Surulere         Italiano   3000         4  09:40:24
4893  4894  2015-12-11    Ibadan     Extravaganza   2000         1  09:40:25
4894  4895  2015-12-07     Ikoyi    Chicken Feast   2000         2  09:40:25

      Revenue  Snap
4890    15000  3005
4891     8000  4002
4892    12000  3004
4893     2000  2001
4894     4000  2002
CHUNK BOSS
       S/N        Date  Branch      Pizza Sold  Price  Quantity      Time  \
4895  4896  2015-12-08  Ibadan    Chicken Suya   4000         4  09:40:26
4896  4897  2015-12-04   Ikoyi     BBQ Chicken   4000         2  09:40:27
4897  4898  2015-12-06  Ibadan     BBQ Chicken   4000         4  09:40:28
4898  4899  2015-12-09  Ibadan  Veggie Supreme   3000         1  09:40:28
4899  4900  2015-12-03   Lekki  Veggie Supreme   3000         1  09:40:29

      Revenue  Snap
4895    16000  4004
4896     8000  4002
4897    16000  4004
4898     3000  3001
4899     3000  3001
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
4900  4901  2015-12-15     Ikoyi         Margarita   4000         5  09:40:29
4901  4902  2015-12-15  Surulere  BBQ Philly Steak   4000         5  09:40:31
4902  4903  2015-12-10    Ibadan      Extravaganza   2000         3  09:40:32
4903  4904  2015-12-13     Lekki         Beef Suya   3000         5  09:40:32
4904  4905  2015-12-05     Lekki     Chicken Feast   2000         4  09:40:34

      Revenue  Snap
4900    20000  4005
4901    20000  4005
4902     6000  2003
4903    15000  3005
4904     8000  2004
CHUNK BOSS
       S/N        Date   Branch       Pizza Sold  Price  Quantity      Time  \
4905  4906  2015-12-03  Gbagada       Hot Veggie   4000         2  09:40:35
4906  4907  2015-12-09   Ibadan       Hot Veggie   4000         5  09:40:36
4907  4908  2015-12-06  Gbagada    Chicken Feast   2000         3  09:40:38
4908  4909  2015-12-05    Ikoyi  Pepperoni Feast   4000         1  09:40:39
4909  4910  2015-12-06    Ikoyi     Extravaganza   2000         5  09:40:41

      Revenue  Snap
4905     8000  4002
4906    20000  4005
4907     6000  2003
4908     4000  4001
4909    10000  2005
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
4910  4911  2015-12-15     Lekki        Margarita   4000         3  09:40:41
4911  4912  2015-12-15     Lekki     Chicken Suya   4000         3  09:40:41
4912  4913  2015-12-04     Ikoyi        Beef Suya   3000         5  09:40:42
4913  4914  2015-12-10  Surulere  Pepperoni Feast   4000         3  09:40:43
4914  4915  2015-12-04   Gbagada    Chicken Feast   2000         4  09:40:45

      Revenue  Snap
4910    12000  4003
4911    12000  4003
4912    15000  3005
4913    12000  4003
4914     8000  2004
CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
4915  4916  2015-12-08  Surulere   Veggie Supreme   3000         1  09:40:48
4916  4917  2015-12-05     Ikoyi  Pepperoni Feast   4000         3  09:40:49
4917  4918  2015-12-11   Gbagada      BBQ Chicken   4000         1  09:40:52
4918  4919  2015-12-10    Ibadan         Italiano   3000         2  09:40:52
4919  4920  2015-12-08  Surulere     Chicken Bali   2000         5  09:40:54

      Revenue  Snap
4915     3000  3001
4916    12000  4003
4917     4000  4001
4918     6000  3002
4919    10000  2005
CHUNK BOSS
       S/N        Date   Branch           Pizza Sold  Price  Quantity  \
4920  4921  2015-12-14  Gbagada           Hot Veggie   4000         3
4921  4922  2015-12-09   Ibadan              Meatzaa   2000         4
4922  4923  2015-12-07   Ibadan  Hot Pepperoni Feast   4000         5
4923  4924  2015-12-04   Ibadan        Chicken Feast   2000         3
4924  4925  2015-12-13   Ibadan            Margarita   4000         4

          Time  Revenue  Snap
4920  09:40:55    12000  4003
4921  09:40:56     8000  2004
4922  09:40:59    20000  4005
4923  09:40:59     6000  2003
4924  09:41:00    16000  4004
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
4925  4926  2015-12-09  Surulere  BBQ Philly Steak   4000         4  09:41:01
4926  4927  2015-12-14     Ikoyi    Pepperoni Suya   3000         2  09:41:02
4927  4928  2015-12-13     Ikoyi    Veggie Supreme   3000         5  09:41:02
4928  4929  2015-12-14    Ibadan      Chicken Suya   4000         4  09:41:03
4929  4930  2015-12-13   Gbagada           Meatzaa   2000         4  09:41:03

      Revenue  Snap
4925    16000  4004
4926     6000  3002
4927    15000  3005
4928    16000  4004
4929     8000  2004
CHUNK BOSS
       S/N        Date   Branch    Pizza Sold  Price  Quantity      Time  \
4930  4931  2015-12-15  Gbagada       Meatzaa   2000         1  09:41:06
4931  4932  2015-12-04   Ibadan  Chicken Suya   4000         2  09:41:07
4932  4933  2015-12-11  Gbagada    Hot Veggie   4000         3  09:41:09
4933  4934  2015-12-05   Ibadan     Beef Suya   3000         5  09:41:09
4934  4935  2015-12-07   Ibadan   BBQ Chicken   4000         5  09:41:11

      Revenue  Snap
4930     2000  2001
4931     8000  4002
4932    12000  4003
4933    15000  3005
4934    20000  4005

CHUNK BOSS
       S/N        Date    Branch       Pizza Sold  Price  Quantity      Time  \
4935  4936  2015-12-11     Lekki         Italiano   3000         1  09:41:12
4936  4937  2015-12-11   Gbagada   Chicken Legend   2000         4  09:41:14
4937  4938  2015-12-07  Surulere  Pepperoni Feast   4000         4  09:41:15
4938  4939  2015-12-11    Ibadan        Beef Suya   3000         4  09:41:15
4939  4940  2015-12-13    Ibadan   Chicken Legend   2000         4  09:41:17

      Revenue  Snap
4935     3000  3001
4936     8000  2004
4937    16000  4004
4938    12000  3004
4939     8000  2004
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4940  4941  2015-12-15     Ikoyi           Hot Veggie   4000         2
4941  4942  2015-12-07  Surulere         Chicken Bali   2000         2
4942  4943  2015-12-09  Surulere  Hot Pepperoni Feast   4000         2
4943  4944  2015-12-07   Gbagada          BBQ Chicken   4000         4
4944  4945  2015-12-04  Surulere            Margarita   4000         1

          Time  Revenue  Snap
4940  09:41:17     8000  4002
4941  09:41:20     4000  2002
4942  09:41:23     8000  4002
4943  09:41:27    16000  4004
4944  09:41:28     4000  4001
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4945  4946  2015-12-04   Gbagada        Chicken Feast   2000         2
4946  4947  2015-12-11     Ikoyi            Beef Suya   3000         4
4947  4948  2015-12-12   Gbagada           Hot Veggie   4000         2
4948  4949  2015-12-04  Surulere  Hot Pepperoni Feast   4000         2
4949  4950  2015-12-05     Ikoyi              Meatzaa   2000         2

          Time  Revenue  Snap
4945  09:41:29     4000  2002
4946  09:41:29    12000  3004
4947  09:41:31     8000  4002
4948  09:41:32     8000  4002
4949  09:41:33     4000  2002
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
4950  4951  2015-12-12  Surulere  BBQ Philly Steak   4000         4  09:41:34
4951  4952  2015-12-06     Lekki      Extravaganza   2000         5  09:41:35
4952  4953  2015-12-13     Ikoyi   Pepperoni Feast   4000         2  09:41:35
4953  4954  2015-12-05  Surulere    Veggie Supreme   3000         4  09:41:36
4954  4955  2015-12-14    Ibadan    Veggie Supreme   3000         1  09:41:36

      Revenue  Snap
4950    16000  4004
4951    10000  2005
4952     8000  4002
4953    12000  3004
4954     3000  3001
CHUNK BOSS
       S/N        Date    Branch        Pizza Sold  Price  Quantity      Time  \
4955  4956  2015-12-07   Gbagada           Meatzaa   2000         5  09:41:38
4956  4957  2015-12-08     Ikoyi    Pepperoni Suya   3000         3  09:41:39
4957  4958  2015-12-13  Surulere      Chicken Bali   2000         2  09:41:40
4958  4959  2015-12-05    Ibadan  BBQ Philly Steak   4000         1  09:41:40
4959  4960  2015-12-08    Ibadan       BBQ Chicken   4000         1  09:41:42

      Revenue  Snap
4955    10000  2005
4956     9000  3003
4957     4000  2002
4958     4000  4001
4959     4000  4001
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4960  4961  2015-12-07    Ibadan         Chicken Bali   2000         1
4961  4962  2015-12-09  Surulere         Extravaganza   2000         4
4962  4963  2015-12-07     Ikoyi         Chicken Suya   4000         4
4963  4964  2015-12-12  Surulere  Hot Pepperoni Feast   4000         3
4964  4965  2015-12-15  Surulere        Chicken Feast   2000         2

          Time  Revenue  Snap
4960  09:41:43     2000  2001
4961  09:41:44     8000  2004
4962  09:41:47    16000  4004
4963  09:41:48    12000  4003
4964  09:41:51     4000  2002
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4965  4966  2015-12-03   Gbagada  Chicken Legend   2000         4  09:41:52
4966  4967  2015-12-05     Lekki        Italiano   3000         2  09:41:52
4967  4968  2015-12-03  Surulere    Chicken Suya   4000         5  09:41:53
4968  4969  2015-12-11   Gbagada         Meatzaa   2000         3  09:41:56
4969  4970  2015-12-13   Gbagada  Pepperoni Suya   3000         2  09:41:56

      Revenue  Snap
4965     8000  2004
4966     6000  3002
4967    20000  4005
4968     6000  2003
4969     6000  3002
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4970  4971  2015-12-06  Surulere         Extravaganza   2000         2
4971  4972  2015-12-14   Gbagada         Chicken Bali   2000         1
4972  4973  2015-12-12   Gbagada  Hot Pepperoni Feast   4000         5
4973  4974  2015-12-04  Surulere              Meatzaa   2000         3
4974  4975  2015-12-12     Ikoyi       Pepperoni Suya   3000         4

          Time  Revenue  Snap
4970  09:41:58     4000  2002
4971  09:41:59     2000  2001
4972  09:42:00    20000  4005
4973  09:42:02     6000  2003
4974  09:42:04    12000  3004
CHUNK BOSS
       S/N        Date   Branch      Pizza Sold  Price  Quantity      Time  \
4975  4976  2015-12-06    Lekki         Meatzaa   2000         1  09:42:06
4976  4977  2015-12-05   Ibadan    Extravaganza   2000         5  09:42:07
4977  4978  2015-12-13  Gbagada  Veggie Supreme   3000         4  09:42:07
4978  4979  2015-12-09    Lekki    Chicken Bali   2000         1  09:42:08
4979  4980  2015-12-15    Ikoyi      Hot Veggie   4000         2  09:42:08

      Revenue  Snap
4975     2000  2001
4976    10000  2005
4977    12000  3004
4978     2000  2001
4979     8000  4002
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4980  4981  2015-12-09  Surulere  Veggie Supreme   3000         3  09:42:09
4981  4982  2015-12-12   Gbagada     BBQ Chicken   4000         2  09:42:11
4982  4983  2015-12-05     Ikoyi      Hot Veggie   4000         1  09:42:11
4983  4984  2015-12-11  Surulere     BBQ Chicken   4000         4  09:42:12
4984  4985  2015-12-13     Lekki  Pepperoni Suya   3000         3  09:42:12

      Revenue  Snap
4980     9000  3003
4981     8000  4002
4982     4000  4001
4983    16000  4004
4984     9000  3003
CHUNK BOSS
       S/N        Date    Branch           Pizza Sold  Price  Quantity  \
4985  4986  2015-12-13     Lekki          BBQ Chicken   4000         4
4986  4987  2015-12-09     Lekki             Italiano   3000         2
4987  4988  2015-12-12  Surulere       Veggie Supreme   3000         4
4988  4989  2015-12-14   Gbagada          BBQ Chicken   4000         3
4989  4990  2015-12-09    Ibadan  Hot Pepperoni Feast   4000         5

          Time  Revenue  Snap
4985  09:42:13    16000  4004
4986  09:42:14     6000  3002
4987  09:42:14    12000  3004
4988  09:42:15    12000  4003
4989  09:42:17    20000  4005
CHUNK BOSS
       S/N        Date   Branch        Pizza Sold  Price  Quantity      Time  \
4990  4991  2015-12-08  Gbagada   Pepperoni Feast   4000         2  09:42:20
4991  4992  2015-12-08    Ikoyi  BBQ Philly Steak   4000         1  09:42:22
4992  4993  2015-12-10    Lekki       BBQ Chicken   4000         4  09:42:26
4993  4994  2015-12-10    Ikoyi         Beef Suya   3000         3  09:42:27
4994  4995  2015-12-04    Lekki      Chicken Suya   4000         4  09:42:28

      Revenue  Snap
4990     8000  4002
4991     4000  4001
4992    16000  4004
4993     9000  3003
4994    16000  4004
CHUNK BOSS
       S/N        Date    Branch      Pizza Sold  Price  Quantity      Time  \
4995  4996  2015-12-13     Lekki       Margarita   4000         1  09:42:28
4996  4997  2015-12-07  Surulere       Beef Suya   3000         5  09:42:31
4997  4998  2015-12-07     Ikoyi  Pepperoni Suya   3000         4  09:42:32
4998  4999  2015-12-08   Gbagada        Italiano   3000         1  09:42:32
4999  5000  2015-12-10     Ikoyi       Beef Suya   3000         5  09:42:33

      Revenue  Snap
4995     4000  4001
4996    15000  3005
4997    12000  3004
4998     3000  3001
4999    15000  3005

In [251]:
real_boss = pd.DataFrame(columns =boss.columns)

for boss in pd.read_csv("Modified.csv", chunksize=5):
    results = boss.groupby(['Branch']).mean()
    real_boss = pd.concat([real_boss, results], sort = False)
    print(real_boss)

         S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada  5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan   1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi    3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki    3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
          S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada   5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan    1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi     3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki     3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada   9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Ibadan    8.5  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Ikoyi     8.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Surulere  6.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
           S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada    5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan     1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi      3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki      3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada    9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Ibadan     8.5  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Ikoyi      8.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Surulere   6.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Gbagada   12.5  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ibadan    14.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Lekki     11.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Surulere  15.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
           S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada    5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan     1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi      3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki      3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada    9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Ibadan     8.5  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Ikoyi      8.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Surulere   6.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Gbagada   12.5  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ibadan    14.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Lekki     11.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Surulere  15.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Gbagada   17.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ibadan    20.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0
Lekki     17.0  NaN    NaN        NaN  3500.0       5.0  NaN  17500.0  3505.0
Surulere  19.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
           S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada    5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan     1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi      3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki      3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada    9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Ibadan     8.5  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Ikoyi      8.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Surulere   6.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Gbagada   12.5  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ibadan    14.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Lekki     11.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Surulere  15.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Gbagada   17.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ibadan    20.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0
Lekki     17.0  NaN    NaN        NaN  3500.0       5.0  NaN  17500.0  3505.0
Surulere  19.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Gbagada   23.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Ikoyi     24.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Lekki     23.0  NaN    NaN        NaN  3500.0       4.0  NaN  13500.0  3504.0
Surulere  22.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0
           S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada    5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan     1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi      3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki      3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada    9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Ibadan     8.5  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Ikoyi      8.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Surulere   6.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Gbagada   12.5  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ibadan    14.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Lekki     11.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Surulere  15.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Gbagada   17.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ibadan    20.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0
Lekki     17.0  NaN    NaN        NaN  3500.0       5.0  NaN  17500.0  3505.0
Surulere  19.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Gbagada   23.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Ikoyi     24.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Lekki     23.0  NaN    NaN        NaN  3500.0       4.0  NaN  13500.0  3504.0
Surulere  22.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0
Ibadan    27.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Ikoyi     28.0  NaN    NaN        NaN  3000.0       3.0  NaN   8000.0  3003.0
Lekki     30.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
           S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada    5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan     1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi      3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki      3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada    9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Ibadan     8.5  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Ikoyi      8.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Surulere   6.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Gbagada   12.5  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ibadan    14.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Lekki     11.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Surulere  15.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Gbagada   17.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ibadan    20.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0
Lekki     17.0  NaN    NaN        NaN  3500.0       5.0  NaN  17500.0  3505.0
Surulere  19.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Gbagada   23.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Ikoyi     24.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Lekki     23.0  NaN    NaN        NaN  3500.0       4.0  NaN  13500.0  3504.0
Surulere  22.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0
Ibadan    27.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Ikoyi     28.0  NaN    NaN        NaN  3000.0       3.0  NaN   8000.0  3003.0
Lekki     30.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Gbagada   34.0  NaN    NaN        NaN  2500.0       3.0  NaN   7000.0  2503.0
Ibadan    34.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0
Ikoyi     32.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0  3002.0
Lekki     31.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
                S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada    5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan     1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi      3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki      3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada    9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
Ibadan     8.500000  NaN    NaN        NaN  4000.0  5.000000  NaN
Ikoyi      8.000000  NaN    NaN        NaN  2000.0  1.000000  NaN
Surulere   6.000000  NaN    NaN        NaN  4000.0  2.000000  NaN
Gbagada   12.500000  NaN    NaN        NaN  4000.0  3.000000  NaN
Ibadan    14.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Lekki     11.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Surulere  15.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Gbagada   17.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ibadan    20.000000  NaN    NaN        NaN  2000.0  2.000000  NaN
Lekki     17.000000  NaN    NaN        NaN  3500.0  5.000000  NaN
Surulere  19.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Gbagada   23.000000  NaN    NaN        NaN  4000.0  2.000000  NaN
Ikoyi     24.000000  NaN    NaN        NaN  3000.0  3.000000  NaN
Lekki     23.000000  NaN    NaN        NaN  3500.0  4.000000  NaN
Surulere  22.000000  NaN    NaN        NaN  3000.0  5.000000  NaN
Ibadan    27.000000  NaN    NaN        NaN  4000.0  2.000000  NaN
Ikoyi     28.000000  NaN    NaN        NaN  3000.0  3.000000  NaN
Lekki     30.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Gbagada   34.000000  NaN    NaN        NaN  2500.0  3.000000  NaN
Ibadan    34.000000  NaN    NaN        NaN  3000.0  4.000000  NaN
Ikoyi     32.000000  NaN    NaN        NaN  3000.0  2.000000  NaN
Lekki     31.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
Ibadan    39.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Ikoyi     36.000000  NaN    NaN        NaN  2000.0  2.000000  NaN
Lekki     38.333333  NaN    NaN        NaN  3000.0  2.666667  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
Ibadan    20000.000000  4005.000000
Ikoyi      2000.000000  2001.000000
Surulere   8000.000000  4002.000000
Gbagada   12000.000000  4003.000000
Ibadan    10000.000000  2005.000000
Lekki     10000.000000  2005.000000
Surulere   8000.000000  2004.000000
Gbagada   10000.000000  2005.000000
Ibadan     4000.000000  2002.000000
Lekki     17500.000000  3505.000000
Surulere  10000.000000  2005.000000
Gbagada    8000.000000  4002.000000
Ikoyi      9000.000000  3003.000000
Lekki     13500.000000  3504.000000
Surulere  15000.000000  3005.000000
Ibadan     8000.000000  4002.000000
Ikoyi      8000.000000  3003.000000
Lekki      8000.000000  2004.000000
Gbagada    7000.000000  2503.000000
Ibadan    12000.000000  3004.000000
Ikoyi      6000.000000  3002.000000
Lekki      6000.000000  2003.000000
Ibadan    20000.000000  4005.000000
Ikoyi      4000.000000  2002.000000
Lekki      7333.333333  3002.666667

                S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada    5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan     1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi      3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki      3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada    9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Ibadan     8.500000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Ikoyi      8.000000  NaN    NaN        NaN  2000.000000  1.000000  NaN
Surulere   6.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Gbagada   12.500000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Ibadan    14.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Lekki     11.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Surulere  15.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Gbagada   17.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ibadan    20.000000  NaN    NaN        NaN  2000.000000  2.000000  NaN
Lekki     17.000000  NaN    NaN        NaN  3500.000000  5.000000  NaN
Surulere  19.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Gbagada   23.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Ikoyi     24.000000  NaN    NaN        NaN  3000.000000  3.000000  NaN
Lekki     23.000000  NaN    NaN        NaN  3500.000000  4.000000  NaN
Surulere  22.000000  NaN    NaN        NaN  3000.000000  5.000000  NaN
Ibadan    27.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Ikoyi     28.000000  NaN    NaN        NaN  3000.000000  3.000000  NaN
Lekki     30.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Gbagada   34.000000  NaN    NaN        NaN  2500.000000  3.000000  NaN
Ibadan    34.000000  NaN    NaN        NaN  3000.000000  4.000000  NaN
Ikoyi     32.000000  NaN    NaN        NaN  3000.000000  2.000000  NaN
Lekki     31.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Ibadan    39.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Ikoyi     36.000000  NaN    NaN        NaN  2000.000000  2.000000  NaN
Lekki     38.333333  NaN    NaN        NaN  3000.000000  2.666667  NaN
Gbagada   43.666667  NaN    NaN        NaN  3666.666667  4.666667  NaN
Lekki     41.000000  NaN    NaN        NaN  3000.000000  2.000000  NaN
Surulere  43.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
Ibadan    20000.000000  4005.000000
Ikoyi      2000.000000  2001.000000
Surulere   8000.000000  4002.000000
Gbagada   12000.000000  4003.000000
Ibadan    10000.000000  2005.000000
Lekki     10000.000000  2005.000000
Surulere   8000.000000  2004.000000
Gbagada   10000.000000  2005.000000
Ibadan     4000.000000  2002.000000
Lekki     17500.000000  3505.000000
Surulere  10000.000000  2005.000000
Gbagada    8000.000000  4002.000000
Ikoyi      9000.000000  3003.000000
Lekki     13500.000000  3504.000000
Surulere  15000.000000  3005.000000
Ibadan     8000.000000  4002.000000
Ikoyi      8000.000000  3003.000000
Lekki      8000.000000  2004.000000
Gbagada    7000.000000  2503.000000
Ibadan    12000.000000  3004.000000
Ikoyi      6000.000000  3002.000000
Lekki      6000.000000  2003.000000
Ibadan    20000.000000  4005.000000
Ikoyi      4000.000000  2002.000000
Lekki      7333.333333  3002.666667
Gbagada   17000.000000  3671.333333
Lekki      6000.000000  3002.000000
Surulere   6000.000000  2003.000000
                S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada    5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan     1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi      3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki      3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada    9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Ibadan     8.500000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Ikoyi      8.000000  NaN    NaN        NaN  2000.000000  1.000000  NaN
Surulere   6.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Gbagada   12.500000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Ibadan    14.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Lekki     11.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Surulere  15.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Gbagada   17.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ibadan    20.000000  NaN    NaN        NaN  2000.000000  2.000000  NaN
Lekki     17.000000  NaN    NaN        NaN  3500.000000  5.000000  NaN
Surulere  19.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Gbagada   23.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Ikoyi     24.000000  NaN    NaN        NaN  3000.000000  3.000000  NaN
Lekki     23.000000  NaN    NaN        NaN  3500.000000  4.000000  NaN
Surulere  22.000000  NaN    NaN        NaN  3000.000000  5.000000  NaN
Ibadan    27.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Ikoyi     28.000000  NaN    NaN        NaN  3000.000000  3.000000  NaN
Lekki     30.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Gbagada   34.000000  NaN    NaN        NaN  2500.000000  3.000000  NaN
Ibadan    34.000000  NaN    NaN        NaN  3000.000000  4.000000  NaN
Ikoyi     32.000000  NaN    NaN        NaN  3000.000000  2.000000  NaN
Lekki     31.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Ibadan    39.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Ikoyi     36.000000  NaN    NaN        NaN  2000.000000  2.000000  NaN
Lekki     38.333333  NaN    NaN        NaN  3000.000000  2.666667  NaN
Gbagada   43.666667  NaN    NaN        NaN  3666.666667  4.666667  NaN
Lekki     41.000000  NaN    NaN        NaN  3000.000000  2.000000  NaN
Surulere  43.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Lekki     47.500000  NaN    NaN        NaN  3000.000000  2.500000  NaN
Surulere  50.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
Ibadan    20000.000000  4005.000000
Ikoyi      2000.000000  2001.000000
Surulere   8000.000000  4002.000000
Gbagada   12000.000000  4003.000000
Ibadan    10000.000000  2005.000000
Lekki     10000.000000  2005.000000
Surulere   8000.000000  2004.000000
Gbagada   10000.000000  2005.000000
Ibadan     4000.000000  2002.000000
Lekki     17500.000000  3505.000000
Surulere  10000.000000  2005.000000
Gbagada    8000.000000  4002.000000
Ikoyi      9000.000000  3003.000000
Lekki     13500.000000  3504.000000
Surulere  15000.000000  3005.000000
Ibadan     8000.000000  4002.000000
Ikoyi      8000.000000  3003.000000
Lekki      8000.000000  2004.000000
Gbagada    7000.000000  2503.000000
Ibadan    12000.000000  3004.000000
Ikoyi      6000.000000  3002.000000
Lekki      6000.000000  2003.000000
Ibadan    20000.000000  4005.000000
Ikoyi      4000.000000  2002.000000
Lekki      7333.333333  3002.666667
Gbagada   17000.000000  3671.333333
Lekki      6000.000000  3002.000000
Surulere   6000.000000  2003.000000
Lekki      8000.000000  3002.500000
Surulere  16000.000000  4004.000000
                S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada    5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan     1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi      3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki      3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada    9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Ibadan     8.500000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Ikoyi      8.000000  NaN    NaN        NaN  2000.000000  1.000000  NaN
Surulere   6.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Gbagada   12.500000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Ibadan    14.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Lekki     11.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Surulere  15.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Gbagada   17.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ibadan    20.000000  NaN    NaN        NaN  2000.000000  2.000000  NaN
Lekki     17.000000  NaN    NaN        NaN  3500.000000  5.000000  NaN
Surulere  19.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Gbagada   23.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Ikoyi     24.000000  NaN    NaN        NaN  3000.000000  3.000000  NaN
Lekki     23.000000  NaN    NaN        NaN  3500.000000  4.000000  NaN
Surulere  22.000000  NaN    NaN        NaN  3000.000000  5.000000  NaN
Ibadan    27.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Ikoyi     28.000000  NaN    NaN        NaN  3000.000000  3.000000  NaN
Lekki     30.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Gbagada   34.000000  NaN    NaN        NaN  2500.000000  3.000000  NaN
Ibadan    34.000000  NaN    NaN        NaN  3000.000000  4.000000  NaN
Ikoyi     32.000000  NaN    NaN        NaN  3000.000000  2.000000  NaN
Lekki     31.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Ibadan    39.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Ikoyi     36.000000  NaN    NaN        NaN  2000.000000  2.000000  NaN
Lekki     38.333333  NaN    NaN        NaN  3000.000000  2.666667  NaN
Gbagada   43.666667  NaN    NaN        NaN  3666.666667  4.666667  NaN
Lekki     41.000000  NaN    NaN        NaN  3000.000000  2.000000  NaN
Surulere  43.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Lekki     47.500000  NaN    NaN        NaN  3000.000000  2.500000  NaN
Surulere  50.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN
Gbagada   53.500000  NaN    NaN        NaN  3500.000000  3.000000  NaN
Ibadan    53.500000  NaN    NaN        NaN  3500.000000  3.000000  NaN
Ikoyi     51.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
Ibadan    20000.000000  4005.000000
Ikoyi      2000.000000  2001.000000
Surulere   8000.000000  4002.000000
Gbagada   12000.000000  4003.000000
Ibadan    10000.000000  2005.000000
Lekki     10000.000000  2005.000000
Surulere   8000.000000  2004.000000
Gbagada   10000.000000  2005.000000
Ibadan     4000.000000  2002.000000
Lekki     17500.000000  3505.000000
Surulere  10000.000000  2005.000000
Gbagada    8000.000000  4002.000000
Ikoyi      9000.000000  3003.000000
Lekki     13500.000000  3504.000000
Surulere  15000.000000  3005.000000
Ibadan     8000.000000  4002.000000
Ikoyi      8000.000000  3003.000000
Lekki      8000.000000  2004.000000
Gbagada    7000.000000  2503.000000
Ibadan    12000.000000  3004.000000
Ikoyi      6000.000000  3002.000000
Lekki      6000.000000  2003.000000
Ibadan    20000.000000  4005.000000
Ikoyi      4000.000000  2002.000000
Lekki      7333.333333  3002.666667
Gbagada   17000.000000  3671.333333
Lekki      6000.000000  3002.000000
Surulere   6000.000000  2003.000000
Lekki      8000.000000  3002.500000
Surulere  16000.000000  4004.000000
Gbagada    9500.000000  3503.000000
Ibadan    11000.000000  3503.000000
Ikoyi     16000.000000  4004.000000
                S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada    5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan     1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi      3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki      3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada    9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Ibadan     8.500000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Ikoyi      8.000000  NaN    NaN        NaN  2000.000000  1.000000  NaN
Surulere   6.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Gbagada   12.500000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Ibadan    14.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Lekki     11.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Surulere  15.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Gbagada   17.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ibadan    20.000000  NaN    NaN        NaN  2000.000000  2.000000  NaN
Lekki     17.000000  NaN    NaN        NaN  3500.000000  5.000000  NaN
Surulere  19.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Gbagada   23.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Ikoyi     24.000000  NaN    NaN        NaN  3000.000000  3.000000  NaN
Lekki     23.000000  NaN    NaN        NaN  3500.000000  4.000000  NaN
Surulere  22.000000  NaN    NaN        NaN  3000.000000  5.000000  NaN
Ibadan    27.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Ikoyi     28.000000  NaN    NaN        NaN  3000.000000  3.000000  NaN
Lekki     30.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Gbagada   34.000000  NaN    NaN        NaN  2500.000000  3.000000  NaN
Ibadan    34.000000  NaN    NaN        NaN  3000.000000  4.000000  NaN
Ikoyi     32.000000  NaN    NaN        NaN  3000.000000  2.000000  NaN
Lekki     31.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Ibadan    39.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Ikoyi     36.000000  NaN    NaN        NaN  2000.000000  2.000000  NaN
Lekki     38.333333  NaN    NaN        NaN  3000.000000  2.666667  NaN
Gbagada   43.666667  NaN    NaN        NaN  3666.666667  4.666667  NaN
Lekki     41.000000  NaN    NaN        NaN  3000.000000  2.000000  NaN
Surulere  43.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Lekki     47.500000  NaN    NaN        NaN  3000.000000  2.500000  NaN
Surulere  50.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN
Gbagada   53.500000  NaN    NaN        NaN  3500.000000  3.000000  NaN
Ibadan    53.500000  NaN    NaN        NaN  3500.000000  3.000000  NaN
Ikoyi     51.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN
Gbagada   59.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Surulere  57.750000  NaN    NaN        NaN  3500.000000  4.250000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
Ibadan    20000.000000  4005.000000
Ikoyi      2000.000000  2001.000000
Surulere   8000.000000  4002.000000
Gbagada   12000.000000  4003.000000
Ibadan    10000.000000  2005.000000
Lekki     10000.000000  2005.000000
Surulere   8000.000000  2004.000000
Gbagada   10000.000000  2005.000000
Ibadan     4000.000000  2002.000000
Lekki     17500.000000  3505.000000
Surulere  10000.000000  2005.000000
Gbagada    8000.000000  4002.000000
Ikoyi      9000.000000  3003.000000
Lekki     13500.000000  3504.000000
Surulere  15000.000000  3005.000000
Ibadan     8000.000000  4002.000000
Ikoyi      8000.000000  3003.000000
Lekki      8000.000000  2004.000000
Gbagada    7000.000000  2503.000000
Ibadan    12000.000000  3004.000000
Ikoyi      6000.000000  3002.000000
Lekki      6000.000000  2003.000000
Ibadan    20000.000000  4005.000000
Ikoyi      4000.000000  2002.000000
Lekki      7333.333333  3002.666667
Gbagada   17000.000000  3671.333333
Lekki      6000.000000  3002.000000
Surulere   6000.000000  2003.000000
Lekki      8000.000000  3002.500000
Surulere  16000.000000  4004.000000
Gbagada    9500.000000  3503.000000
Ibadan    11000.000000  3503.000000
Ikoyi     16000.000000  4004.000000
Gbagada   10000.000000  2005.000000
Surulere  14500.000000  3504.250000
                S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada    5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan     1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi      3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki      3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada    9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Ibadan     8.500000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Ikoyi      8.000000  NaN    NaN        NaN  2000.000000  1.000000  NaN
Surulere   6.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Gbagada   12.500000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Ibadan    14.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Lekki     11.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Surulere  15.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Gbagada   17.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ibadan    20.000000  NaN    NaN        NaN  2000.000000  2.000000  NaN
Lekki     17.000000  NaN    NaN        NaN  3500.000000  5.000000  NaN
Surulere  19.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Gbagada   23.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Ikoyi     24.000000  NaN    NaN        NaN  3000.000000  3.000000  NaN
Lekki     23.000000  NaN    NaN        NaN  3500.000000  4.000000  NaN
Surulere  22.000000  NaN    NaN        NaN  3000.000000  5.000000  NaN
Ibadan    27.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Ikoyi     28.000000  NaN    NaN        NaN  3000.000000  3.000000  NaN
Lekki     30.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Gbagada   34.000000  NaN    NaN        NaN  2500.000000  3.000000  NaN
Ibadan    34.000000  NaN    NaN        NaN  3000.000000  4.000000  NaN
Ikoyi     32.000000  NaN    NaN        NaN  3000.000000  2.000000  NaN
Lekki     31.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Ibadan    39.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Ikoyi     36.000000  NaN    NaN        NaN  2000.000000  2.000000  NaN
Lekki     38.333333  NaN    NaN        NaN  3000.000000  2.666667  NaN
Gbagada   43.666667  NaN    NaN        NaN  3666.666667  4.666667  NaN
Lekki     41.000000  NaN    NaN        NaN  3000.000000  2.000000  NaN
Surulere  43.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Lekki     47.500000  NaN    NaN        NaN  3000.000000  2.500000  NaN
Surulere  50.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN
Gbagada   53.500000  NaN    NaN        NaN  3500.000000  3.000000  NaN
Ibadan    53.500000  NaN    NaN        NaN  3500.000000  3.000000  NaN
Ikoyi     51.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN
Gbagada   59.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Surulere  57.750000  NaN    NaN        NaN  3500.000000  4.250000  NaN
Gbagada   63.000000  NaN    NaN        NaN  2666.666667  3.666667  NaN
Ibadan    65.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Lekki     61.000000  NaN    NaN        NaN  3000.000000  5.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
Ibadan    20000.000000  4005.000000
Ikoyi      2000.000000  2001.000000
Surulere   8000.000000  4002.000000
Gbagada   12000.000000  4003.000000
Ibadan    10000.000000  2005.000000
Lekki     10000.000000  2005.000000
Surulere   8000.000000  2004.000000
Gbagada   10000.000000  2005.000000
Ibadan     4000.000000  2002.000000
Lekki     17500.000000  3505.000000
Surulere  10000.000000  2005.000000
Gbagada    8000.000000  4002.000000
Ikoyi      9000.000000  3003.000000
Lekki     13500.000000  3504.000000
Surulere  15000.000000  3005.000000
Ibadan     8000.000000  4002.000000

                S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada    5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan     1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi      3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki      3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada    9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Ibadan     8.500000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Ikoyi      8.000000  NaN    NaN        NaN  2000.000000  1.000000  NaN
Surulere   6.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Gbagada   12.500000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Ibadan    14.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Lekki     11.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Surulere  15.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Gbagada   17.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ibadan    20.000000  NaN    NaN        NaN  2000.000000  2.000000  NaN
Lekki     17.000000  NaN    NaN        NaN  3500.000000  5.000000  NaN
Surulere  19.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Gbagada   23.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Ikoyi     24.000000  NaN    NaN        NaN  3000.000000  3.000000  NaN
Lekki     23.000000  NaN    NaN        NaN  3500.000000  4.000000  NaN
Surulere  22.000000  NaN    NaN        NaN  3000.000000  5.000000  NaN
Ibadan    27.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Ikoyi     28.000000  NaN    NaN        NaN  3000.000000  3.000000  NaN
Lekki     30.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Gbagada   34.000000  NaN    NaN        NaN  2500.000000  3.000000  NaN
Ibadan    34.000000  NaN    NaN        NaN  3000.000000  4.000000  NaN
Ikoyi     32.000000  NaN    NaN        NaN  3000.000000  2.000000  NaN
Lekki     31.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Ibadan    39.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Ikoyi     36.000000  NaN    NaN        NaN  2000.000000  2.000000  NaN
Lekki     38.333333  NaN    NaN        NaN  3000.000000  2.666667  NaN
Gbagada   43.666667  NaN    NaN        NaN  3666.666667  4.666667  NaN
Lekki     41.000000  NaN    NaN        NaN  3000.000000  2.000000  NaN
Surulere  43.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Lekki     47.500000  NaN    NaN        NaN  3000.000000  2.500000  NaN
Surulere  50.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN
Gbagada   53.500000  NaN    NaN        NaN  3500.000000  3.000000  NaN
Ibadan    53.500000  NaN    NaN        NaN  3500.000000  3.000000  NaN
Ikoyi     51.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN
Gbagada   59.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Surulere  57.750000  NaN    NaN        NaN  3500.000000  4.250000  NaN
Gbagada   63.000000  NaN    NaN        NaN  2666.666667  3.666667  NaN
Ibadan    65.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Lekki     61.000000  NaN    NaN        NaN  3000.000000  5.000000  NaN
Ibadan    70.000000  NaN    NaN        NaN  3000.000000  3.000000  NaN
Ikoyi     67.000000  NaN    NaN        NaN  2500.000000  2.500000  NaN
Lekki     68.000000  NaN    NaN        NaN  3000.000000  2.000000  NaN
Gbagada   75.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ibadan    73.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Ikoyi     73.000000  NaN    NaN        NaN  4000.000000  2.500000  NaN
Surulere  71.000000  NaN    NaN        NaN  4000.000000  1.000000  NaN
Gbagada   78.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Ikoyi     77.000000  NaN    NaN        NaN  3000.000000  2.000000  NaN
Lekki     77.500000  NaN    NaN        NaN  2000.000000  2.000000  NaN
Surulere  80.000000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Ibadan    82.500000  NaN    NaN        NaN  4000.000000  4.500000  NaN
Ikoyi     82.000000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Lekki     84.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
Ibadan    20000.000000  4005.000000
Ikoyi      2000.000000  2001.000000
Surulere   8000.000000  4002.000000
Gbagada   12000.000000  4003.000000
Ibadan    10000.000000  2005.000000
Lekki     10000.000000  2005.000000
Surulere   8000.000000  2004.000000
Gbagada   10000.000000  2005.000000
Ibadan     4000.000000  2002.000000
Lekki     17500.000000  3505.000000
Surulere  10000.000000  2005.000000
Gbagada    8000.000000  4002.000000
Ikoyi      9000.000000  3003.000000
Lekki     13500.000000  3504.000000
Surulere  15000.000000  3005.000000
Ibadan     8000.000000  4002.000000
Ikoyi      8000.000000  3003.000000
Lekki      8000.000000  2004.000000
Gbagada    7000.000000  2503.000000
Ibadan    12000.000000  3004.000000
Ikoyi      6000.000000  3002.000000
Lekki      6000.000000  2003.000000
Ibadan    20000.000000  4005.000000
Ikoyi      4000.000000  2002.000000
Lekki      7333.333333  3002.666667
Gbagada   17000.000000  3671.333333
Lekki      6000.000000  3002.000000
Surulere   6000.000000  2003.000000
Lekki      8000.000000  3002.500000
Surulere  16000.000000  4004.000000
Gbagada    9500.000000  3503.000000
Ibadan    11000.000000  3503.000000
Ikoyi     16000.000000  4004.000000
Gbagada   10000.000000  2005.000000
Surulere  14500.000000  3504.250000
Gbagada    8666.666667  2670.333333
Ibadan     6000.000000  2003.000000
Lekki     15000.000000  3005.000000
Ibadan     9000.000000  3003.000000
Ikoyi      5500.000000  2502.500000
Lekki      7000.000000  3002.000000
Gbagada   10000.000000  2005.000000
Ibadan    20000.000000  4005.000000
Ikoyi     10000.000000  4002.500000
Surulere   4000.000000  4001.000000
Gbagada    8000.000000  4002.000000
Ikoyi      6000.000000  3002.000000
Lekki      4000.000000  2002.000000
Surulere  12000.000000  4003.000000
Ibadan    18000.000000  4004.500000
Ikoyi     12000.000000  4003.000000
Lekki     16000.000000  4004.000000
           S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada    5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan     1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi      3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki      3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada    9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...        ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     84.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Ibadan    87.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0  3002.0
Ikoyi     89.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0
Lekki     86.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Surulere  89.0  NaN    NaN        NaN  4000.0       1.5  NaN   6000.0  4001.5

[61 rows x 9 columns]
           S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada    5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan     1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi      3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki      3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada    9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...        ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     86.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Surulere  89.0  NaN    NaN        NaN  4000.0       1.5  NaN   6000.0  4001.5
Gbagada   94.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Ibadan    92.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0
Ikoyi     93.5  NaN    NaN        NaN  3500.0       3.0  NaN  11000.0  3503.0

[64 rows x 9 columns]
           S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada    5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan     1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi      3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki      3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada    9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...        ...  ...    ...        ...     ...       ...  ...      ...     ...
Ibadan    92.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0
Ikoyi     93.5  NaN    NaN        NaN  3500.0       3.0  NaN  11000.0  3503.0
Gbagada   99.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Ikoyi     98.0  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0  4003.5
Surulere  97.5  NaN    NaN        NaN  3000.0       1.5  NaN   5000.0  3001.5

[67 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere   97.5  NaN    NaN        NaN  3000.0       1.5  NaN   5000.0  3001.5
Gbagada   105.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ikoyi     103.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0
Lekki     101.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Surulere  103.0  NaN    NaN        NaN  3000.0       4.5  NaN  14000.0  3004.5

[71 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  103.0  NaN    NaN        NaN  3000.0       4.5  NaN  14000.0  3004.5
Gbagada   107.5  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Ibadan    106.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0
Ikoyi     110.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Surulere  109.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0  3001.0

[75 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Gbagada   115.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Ibadan    112.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ikoyi     114.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Lekki     113.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0  3002.0
Surulere  111.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0

[80 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     113.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0  3002.0
Surulere  111.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Ibadan    118.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Lekki     117.5  NaN    NaN        NaN  3500.0       4.5  NaN  15500.0  3504.5
Surulere  118.5  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0

[83 rows x 9 columns]

                 S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...              ...  ...    ...        ...          ...       ...  ...
Lekki     117.500000  NaN    NaN        NaN  3500.000000  4.500000  NaN
Surulere  118.500000  NaN    NaN        NaN  3000.000000  4.000000  NaN
Gbagada   122.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Ibadan    123.333333  NaN    NaN        NaN  3333.333333  3.666667  NaN
Lekki     123.000000  NaN    NaN        NaN  3000.000000  4.000000  NaN

          Revenue    Snap
Gbagada    8000.0  2004.0
Ibadan    10000.0  2005.0
Ikoyi      5000.0  2002.5
Lekki     20000.0  4005.0
Gbagada    6000.0  2003.0
...           ...     ...
Lekki     15500.0  3504.5
Surulere  12000.0  3004.0
Gbagada    8000.0  4002.0
Ibadan    12000.0  3337.0
Lekki     12000.0  3004.0

[86 rows x 9 columns]
                S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada    5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan     1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi      3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki      3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada    9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...             ...  ...    ...        ...          ...       ...  ...
Ibadan   123.333333  NaN    NaN        NaN  3333.333333  3.666667  NaN
Lekki    123.000000  NaN    NaN        NaN  3000.000000  4.000000  NaN
Gbagada  130.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN
Ikoyi    126.500000  NaN    NaN        NaN  3500.000000  2.500000  NaN
Lekki    128.500000  NaN    NaN        NaN  3500.000000  2.500000  NaN

         Revenue    Snap
Gbagada   8000.0  2004.0
Ibadan   10000.0  2005.0
Ikoyi     5000.0  2002.5
Lekki    20000.0  4005.0
Gbagada   6000.0  2003.0
...          ...     ...
Ibadan   12000.0  3337.0
Lekki    12000.0  3004.0
Gbagada  16000.0  4004.0
Ikoyi     9500.0  3502.5
Lekki     8500.0  3502.5

[89 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     128.5  NaN    NaN        NaN  3500.0       2.5  NaN   8500.0  3502.5
Gbagada   133.5  NaN    NaN        NaN  3500.0       2.5  NaN   9500.0  3502.5
Ibadan    131.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Lekki     134.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0
Surulere  133.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0

[93 rows x 9 columns]
            S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.0  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan      1.0  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi       3.0  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki       3.0  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada     9.0  NaN    NaN        NaN  2000.000000       3.0  NaN
...         ...  ...    ...        ...          ...       ...  ...
Ibadan    131.0  NaN    NaN        NaN  2000.000000       1.0  NaN
Lekki     134.0  NaN    NaN        NaN  3000.000000       4.0  NaN
Surulere  133.0  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada   138.0  NaN    NaN        NaN  3000.000000       3.0  NaN
Ibadan    138.0  NaN    NaN        NaN  3666.666667       3.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ibadan     2000.000000  2001.000000
Lekki     12000.000000  3004.000000
Surulere  20000.000000  4005.000000
Gbagada    7000.000000  3003.000000
Ibadan    11333.333333  3669.666667

[95 rows x 9 columns]
            S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...         ...  ...    ...        ...          ...       ...  ...
Surulere  133.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada   138.0  NaN    NaN        NaN  3000.000000  3.000000  NaN
Ibadan    138.0  NaN    NaN        NaN  3666.666667  3.000000  NaN
Ikoyi     144.5  NaN    NaN        NaN  4000.000000  4.000000  NaN
Lekki     142.0  NaN    NaN        NaN  3333.333333  2.333333  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Surulere  20000.000000  4005.000000
Gbagada    7000.000000  3003.000000
Ibadan    11333.333333  3669.666667
Ikoyi     16000.000000  4004.000000
Lekki      8000.000000  3335.666667

[97 rows x 9 columns]
            S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada     5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0
Ibadan      1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ikoyi       3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN   5000.0
Lekki       3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Gbagada     9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
...         ...  ...    ...        ...          ...       ...  ...      ...
Lekki     142.0  NaN    NaN        NaN  3333.333333  2.333333  NaN   8000.0
Ibadan    147.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Ikoyi     147.0  NaN    NaN        NaN  3000.000000  1.000000  NaN   3000.0
Lekki     149.0  NaN    NaN        NaN  4000.000000  3.000000  NaN  12000.0
Surulere  150.0  NaN    NaN        NaN  4000.000000  2.000000  NaN   8000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Lekki     3335.666667
Ibadan    4005.000000
Ikoyi     3001.000000
Lekki     4003.000000
Surulere  4002.000000

[101 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  150.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Gbagada   153.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0  3002.0
Ibadan    151.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Lekki     154.5  NaN    NaN        NaN  2500.0       3.0  NaN   7000.0  2503.0
Surulere  152.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0

[105 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  152.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Gbagada   158.5  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0  3001.0
Ibadan    156.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ikoyi     158.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Surulere  159.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0

[109 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi     158.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Surulere  159.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Ibadan    163.5  NaN    NaN        NaN  3000.0       3.5  NaN  11000.0  3003.5
Ikoyi     163.5  NaN    NaN        NaN  2500.0       3.0  NaN   8000.0  2503.0
Surulere  161.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0

[112 rows x 9 columns]

            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi     163.5  NaN    NaN        NaN  2500.0       3.0  NaN   8000.0  2503.0
Surulere  161.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0
Ibadan    168.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ikoyi     168.0  NaN    NaN        NaN  3000.0       4.5  NaN  14000.0  3004.5
Lekki     168.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0

[115 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ibadan    168.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ikoyi     168.0  NaN    NaN        NaN  3000.0       4.5  NaN  14000.0  3004.5
Lekki     168.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada   175.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Surulere  172.5  NaN    NaN        NaN  3500.0       3.5  NaN  12500.0  3503.5

[117 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  172.5  NaN    NaN        NaN  3500.0       3.5  NaN  12500.0  3503.5
Gbagada   180.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Ibadan    178.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0
Ikoyi     178.0  NaN    NaN        NaN  3000.0       2.0  NaN   7000.0  3002.0
Lekki     176.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0

[121 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi     178.0  NaN    NaN        NaN  3000.0       2.0  NaN   7000.0  3002.0
Lekki     176.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Ibadan    181.5  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0  4003.5
Ikoyi     183.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Surulere  184.5  NaN    NaN        NaN  2500.0       1.0  NaN   2500.0  2501.0

[124 rows x 9 columns]
                 S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...              ...  ...    ...        ...          ...       ...  ...
Ibadan    181.500000  NaN    NaN        NaN  4000.000000       3.5  NaN
Ikoyi     183.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
Surulere  184.500000  NaN    NaN        NaN  2500.000000       1.0  NaN
Gbagada   188.666667  NaN    NaN        NaN  2333.333333       4.0  NaN
Surulere  187.000000  NaN    NaN        NaN  3500.000000       2.5  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ibadan    14000.000000  4003.500000
Ikoyi      6000.000000  2003.000000
Surulere   2500.000000  2501.000000
Gbagada    9333.333333  2337.333333
Surulere   8500.000000  3502.500000

[126 rows x 9 columns]
                 S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...              ...  ...    ...        ...          ...       ...  ...
Surulere  184.500000  NaN    NaN        NaN  2500.000000  1.000000  NaN
Gbagada   188.666667  NaN    NaN        NaN  2333.333333  4.000000  NaN
Surulere  187.000000  NaN    NaN        NaN  3500.000000  2.500000  NaN
Gbagada   193.333333  NaN    NaN        NaN  3666.666667  2.666667  NaN
Ikoyi     192.500000  NaN    NaN        NaN  3000.000000  4.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Surulere   2500.000000  2501.000000
Gbagada    9333.333333  2337.333333
Surulere   8500.000000  3502.500000
Gbagada   10333.333333  3669.333333
Ikoyi     12000.000000  3004.000000

[128 rows x 9 columns]
           S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada    5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan     1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi      3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki      3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada    9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...        ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi    192.5  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0
Gbagada  200.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ibadan   198.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Ikoyi    199.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0
Lekki    196.5  NaN    NaN        NaN  3500.0       2.5  NaN   9500.0  3502.5

[132 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi     199.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0
Lekki     196.5  NaN    NaN        NaN  3500.0       2.5  NaN   9500.0  3502.5
Gbagada   204.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Lekki     202.5  NaN    NaN        NaN  3000.0       3.5  NaN   9000.0  3003.5
Surulere  202.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0

[135 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Gbagada   204.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Lekki     202.5  NaN    NaN        NaN  3000.0       3.5  NaN   9000.0  3003.5
Surulere  202.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Ibadan    208.5  NaN    NaN        NaN  3500.0       3.5  NaN  13500.0  3503.5
Ikoyi     206.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0

[137 rows x 9 columns]

            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  202.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Ibadan    208.5  NaN    NaN        NaN  3500.0       3.5  NaN  13500.0  3503.5
Ikoyi     206.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0
Gbagada   212.5  NaN    NaN        NaN  2750.0       3.5  NaN   8750.0  2753.5
Ikoyi     215.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0

[139 rows x 9 columns]
                S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada    5.000000  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan     1.000000  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi      3.000000  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki      3.000000  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada    9.000000  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...             ...  ...    ...        ...     ...       ...  ...      ...
Gbagada  212.500000  NaN    NaN        NaN  2750.0       3.5  NaN   8750.0
Ikoyi    215.000000  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada  219.000000  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ibadan   218.000000  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ikoyi    217.666667  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0

           Snap
Gbagada  2004.0
Ibadan   2005.0
Ikoyi    2002.5
Lekki    4005.0
Gbagada  2003.0
...         ...
Gbagada  2753.5
Ikoyi    4005.0
Gbagada  2005.0
Ibadan   4005.0
Ikoyi    4002.0

[142 rows x 9 columns]
                 S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada     5.000000  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan      1.000000  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi       3.000000  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki       3.000000  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada     9.000000  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...              ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    218.000000  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ikoyi     217.666667  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Gbagada   225.000000  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Ikoyi     222.000000  NaN    NaN        NaN  2500.0       4.0  NaN   9500.0
Surulere  223.000000  NaN    NaN        NaN  2500.0       4.0  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    4005.0
Ikoyi     4002.0
Gbagada   2002.0
Ikoyi     2504.0
Surulere  2504.0

[145 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  223.0  NaN    NaN        NaN  2500.0       4.0  NaN  10000.0  2504.0
Gbagada   229.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Ibadan    226.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Ikoyi     230.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Lekki     227.5  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0

[149 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     227.5  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada   233.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ibadan    231.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Lekki     233.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Surulere  235.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0

[153 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     233.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Surulere  235.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Gbagada   238.0  NaN    NaN        NaN  2500.0       4.0  NaN  10000.0  2504.0
Ibadan    240.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Ikoyi     237.0  NaN    NaN        NaN  3000.0       2.0  NaN   7000.0  3002.0

[156 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ibadan    240.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Ikoyi     237.0  NaN    NaN        NaN  3000.0       2.0  NaN   7000.0  3002.0
Gbagada   243.5  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0
Ikoyi     241.5  NaN    NaN        NaN  3000.0       3.0  NaN  11000.0  3003.0
Surulere  245.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0

[159 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  245.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Gbagada   248.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Ikoyi     249.5  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Lekki     246.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0
Surulere  247.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0

[163 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  247.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Gbagada   253.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ibadan    254.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0
Ikoyi     253.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Lekki     252.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0

[167 rows x 9 columns]

           S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada    5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan     1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi      3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki      3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada    9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...        ...  ...    ...        ...     ...       ...  ...      ...     ...
Ibadan   254.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0
Ikoyi    253.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Lekki    252.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Ibadan   259.5  NaN    NaN        NaN  3500.0       2.5  NaN   9500.0  3502.5
Lekki    257.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0

[169 rows x 9 columns]
                S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada    5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan     1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi      3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki      3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada    9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...             ...  ...    ...        ...     ...       ...  ...
Lekki    252.000000  NaN    NaN        NaN  4000.0  2.000000  NaN
Ibadan   259.500000  NaN    NaN        NaN  3500.0  2.500000  NaN
Lekki    257.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
Gbagada  262.333333  NaN    NaN        NaN  3000.0  2.666667  NaN
Lekki    264.000000  NaN    NaN        NaN  2500.0  3.500000  NaN

              Revenue         Snap
Gbagada   8000.000000  2004.000000
Ibadan   10000.000000  2005.000000
Ikoyi     5000.000000  2002.500000
Lekki    20000.000000  4005.000000
Gbagada   6000.000000  2003.000000
...               ...          ...
Lekki     8000.000000  4002.000000
Ibadan    9500.000000  3502.500000
Lekki     6000.000000  2003.000000
Gbagada   7333.333333  3002.666667
Lekki     8500.000000  2503.500000

[171 rows x 9 columns]
                 S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...              ...  ...    ...        ...     ...       ...  ...
Gbagada   262.333333  NaN    NaN        NaN  3000.0  2.666667  NaN
Lekki     264.000000  NaN    NaN        NaN  2500.0  3.500000  NaN
Ikoyi     266.500000  NaN    NaN        NaN  4000.0  1.000000  NaN
Lekki     270.000000  NaN    NaN        NaN  2000.0  1.000000  NaN
Surulere  268.500000  NaN    NaN        NaN  3500.0  3.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Gbagada    7333.333333  3002.666667
Lekki      8500.000000  2503.500000
Ikoyi      4000.000000  4001.000000
Lekki      2000.000000  2001.000000
Surulere  10000.000000  3503.000000

[174 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  268.5  NaN    NaN        NaN  3500.0       3.0  NaN  10000.0  3503.0
Ibadan    274.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Ikoyi     271.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Lekki     273.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0  3002.0
Surulere  273.5  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0

[178 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     273.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0  3002.0
Surulere  273.5  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0
Ibadan    277.0  NaN    NaN        NaN  3000.0       2.5  NaN   8000.0  3002.5
Ikoyi     278.0  NaN    NaN        NaN  2500.0       3.0  NaN   8500.0  2503.0
Surulere  280.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0

[181 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  280.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Gbagada   284.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Ibadan    282.5  NaN    NaN        NaN  3500.0       3.0  NaN  11000.0  3503.0
Lekki     281.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Surulere  285.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0  3002.0

[185 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     281.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Surulere  285.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0  3002.0
Gbagada   287.0  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0  4003.5
Ikoyi     288.0  NaN    NaN        NaN  3500.0       3.5  NaN  12000.0  3503.5
Lekki     290.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0

[188 rows x 9 columns]
           S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada    5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan     1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi      3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki      3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada    9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...        ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki    290.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Gbagada  294.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ibadan   293.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0  3001.0
Ikoyi    291.5  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Lekki    295.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0

[192 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi     291.5  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Lekki     295.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0
Ibadan    297.5  NaN    NaN        NaN  2500.0       3.0  NaN   7500.0  2503.0
Lekki     298.5  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0
Surulere  298.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0

[195 rows x 9 columns]

            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  298.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Gbagada   305.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0  3002.0
Ibadan    304.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Lekki     301.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0
Surulere  302.5  NaN    NaN        NaN  4000.0       2.5  NaN  10000.0  4002.5

[199 rows x 9 columns]
                 S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...              ...  ...    ...        ...          ...       ...  ...
Lekki     301.000000  NaN    NaN        NaN  3000.000000       5.0  NaN
Surulere  302.500000  NaN    NaN        NaN  4000.000000       2.5  NaN
Ikoyi     310.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Lekki     308.000000  NaN    NaN        NaN  4000.000000       2.0  NaN
Surulere  307.333333  NaN    NaN        NaN  3333.333333       3.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki     15000.000000  3005.000000
Surulere  10000.000000  4002.500000
Ikoyi     20000.000000  4005.000000
Lekki      8000.000000  4002.000000
Surulere  10666.666667  3336.333333

[202 rows x 9 columns]
                 S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...              ...  ...    ...        ...          ...       ...  ...
Lekki     308.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Surulere  307.333333  NaN    NaN        NaN  3333.333333  3.000000  NaN
Gbagada   312.666667  NaN    NaN        NaN  3333.333333  3.333333  NaN
Ikoyi     314.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Surulere  313.000000  NaN    NaN        NaN  4000.000000  3.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      8000.000000  4002.000000
Surulere  10666.666667  3336.333333
Gbagada   11333.333333  3336.666667
Ikoyi      8000.000000  4002.000000
Surulere  12000.000000  4003.000000

[205 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  313.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Gbagada   316.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ikoyi     318.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Lekki     317.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Surulere  319.5  NaN    NaN        NaN  3000.0       4.5  NaN  13000.0  3004.5

[209 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  319.5  NaN    NaN        NaN  3000.0       4.5  NaN  13000.0  3004.5
Gbagada   321.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0
Ikoyi     324.5  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0  3001.0
Lekki     322.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Surulere  323.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0

[213 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada     5.00  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan      1.00  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi       3.00  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki       3.00  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada     9.00  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     324.50  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Lekki     322.00  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Surulere  323.00  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     328.25  NaN    NaN        NaN  2500.0       4.5  NaN  11500.0
Surulere  327.00  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3001.0
Lekki     2005.0
Surulere  4001.0
Lekki     2504.5
Surulere  2002.0

[215 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada     5.00  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan      1.00  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi       3.00  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki       3.00  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada     9.00  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     328.25  NaN    NaN        NaN  2500.0       4.5  NaN  11500.0
Surulere  327.00  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Gbagada   334.50  NaN    NaN        NaN  2500.0       3.0  NaN   6500.0
Ibadan    332.00  NaN    NaN        NaN  4000.0       4.5  NaN  18000.0
Ikoyi     332.00  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2504.5
Surulere  2002.0
Gbagada   2503.0
Ibadan    4004.5
Ikoyi     2001.0

[218 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ibadan    332.0  NaN    NaN        NaN  4000.0       4.5  NaN  18000.0  4004.5
Ikoyi     332.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Ikoyi     338.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0
Lekki     337.5  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Surulere  338.5  NaN    NaN        NaN  3500.0       1.5  NaN   5500.0  3501.5

[221 rows x 9 columns]
                 S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada     5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.0
Ibadan      1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.0
Ikoyi       3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.0
Lekki       3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.0
Gbagada     9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.0
...              ...  ...    ...        ...     ...       ...  ...      ...
Lekki     337.500000  NaN    NaN        NaN  3000.0  3.000000  NaN   9000.0
Surulere  338.500000  NaN    NaN        NaN  3500.0  1.500000  NaN   5500.0
Gbagada   343.000000  NaN    NaN        NaN  2000.0  1.000000  NaN   2000.0
Ibadan    345.000000  NaN    NaN        NaN  3000.0  4.000000  NaN  12000.0
Surulere  342.333333  NaN    NaN        NaN  3000.0  3.666667  NaN  11000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Lekki     3003.000000
Surulere  3501.500000
Gbagada   2001.000000
Ibadan    3004.000000
Surulere  3003.666667

[224 rows x 9 columns]
                 S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada     5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.0
Ibadan      1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.0
Ikoyi       3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.0
Lekki       3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.0
Gbagada     9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.0
...              ...  ...    ...        ...     ...       ...  ...      ...
Surulere  342.333333  NaN    NaN        NaN  3000.0  3.666667  NaN  11000.0
Gbagada   347.000000  NaN    NaN        NaN  3000.0  1.000000  NaN   3000.0
Ibadan    350.000000  NaN    NaN        NaN  3000.0  4.000000  NaN  12000.0
Lekki     347.000000  NaN    NaN        NaN  3500.0  5.000000  NaN  17500.0
Surulere  349.000000  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Surulere  3003.666667
Gbagada   3001.000000
Ibadan    3004.000000
Lekki     3505.000000
Surulere  4005.000000

[228 rows x 9 columns]

                 S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...              ...  ...    ...        ...          ...       ...  ...
Lekki     347.000000  NaN    NaN        NaN  3500.000000  5.000000  NaN
Surulere  349.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada   352.666667  NaN    NaN        NaN  3333.333333  3.333333  NaN
Ibadan    355.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ikoyi     352.000000  NaN    NaN        NaN  4000.000000  3.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki     17500.000000  3505.000000
Surulere  20000.000000  4005.000000
Gbagada   11666.666667  3336.666667
Ibadan     8000.000000  2004.000000
Ikoyi     12000.000000  4003.000000

[231 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi     352.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Gbagada   359.5  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0
Ibadan    357.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Ikoyi     356.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Surulere  358.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0

[235 rows x 9 columns]
            S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada     5.0  NaN    NaN        NaN  2000.000000       4.0  NaN   8000.0
Ibadan      1.0  NaN    NaN        NaN  2000.000000       5.0  NaN  10000.0
Ikoyi       3.0  NaN    NaN        NaN  2000.000000       2.5  NaN   5000.0
Lekki       3.0  NaN    NaN        NaN  4000.000000       5.0  NaN  20000.0
Gbagada     9.0  NaN    NaN        NaN  2000.000000       3.0  NaN   6000.0
...         ...  ...    ...        ...          ...       ...  ...      ...
Ikoyi     356.0  NaN    NaN        NaN  3000.000000       3.0  NaN   9000.0
Surulere  358.0  NaN    NaN        NaN  4000.000000       5.0  NaN  20000.0
Gbagada   362.0  NaN    NaN        NaN  2000.000000       1.0  NaN   2000.0
Ibadan    364.0  NaN    NaN        NaN  2666.666667       4.0  NaN  10000.0
Surulere  361.0  NaN    NaN        NaN  4000.000000       5.0  NaN  20000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Ikoyi     3003.000000
Surulere  4005.000000
Gbagada   2001.000000
Ibadan    2670.666667
Surulere  4005.000000

[238 rows x 9 columns]
            S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...         ...  ...    ...        ...          ...       ...  ...
Ibadan    364.0  NaN    NaN        NaN  2666.666667  4.000000  NaN
Surulere  361.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada   367.0  NaN    NaN        NaN  2000.000000  1.000000  NaN
Ikoyi     368.0  NaN    NaN        NaN  4000.000000  2.666667  NaN
Lekki     369.0  NaN    NaN        NaN  2000.000000  4.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ibadan    10000.000000  2670.666667
Surulere  20000.000000  4005.000000
Gbagada    2000.000000  2001.000000
Ikoyi     10666.666667  4002.666667
Lekki      8000.000000  2004.000000

[241 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     369.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Gbagada   372.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ikoyi     372.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Lekki     374.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Surulere  375.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0

[245 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     374.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Surulere  375.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Ikoyi     378.5  NaN    NaN        NaN  3500.0       2.5  NaN   8000.0  3502.5
Lekki     376.5  NaN    NaN        NaN  2500.0       2.5  NaN   6000.0  2502.5
Surulere  380.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0

[248 rows x 9 columns]
            S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada     5.0  NaN    NaN        NaN  2000.000000       4.0  NaN   8000.0
Ibadan      1.0  NaN    NaN        NaN  2000.000000       5.0  NaN  10000.0
Ikoyi       3.0  NaN    NaN        NaN  2000.000000       2.5  NaN   5000.0
Lekki       3.0  NaN    NaN        NaN  4000.000000       5.0  NaN  20000.0
Gbagada     9.0  NaN    NaN        NaN  2000.000000       3.0  NaN   6000.0
...         ...  ...    ...        ...          ...       ...  ...      ...
Lekki     376.5  NaN    NaN        NaN  2500.000000       2.5  NaN   6000.0
Surulere  380.0  NaN    NaN        NaN  4000.000000       5.0  NaN  20000.0
Gbagada   381.0  NaN    NaN        NaN  3000.000000       2.0  NaN   6000.0
Lekki     382.0  NaN    NaN        NaN  3000.000000       5.0  NaN  15000.0
Surulere  384.0  NaN    NaN        NaN  3333.333333       4.0  NaN  14000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Lekki     2502.500000
Surulere  4005.000000
Gbagada   3002.000000
Lekki     3005.000000
Surulere  3337.333333

[251 rows x 9 columns]
            S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada     5.0  NaN    NaN        NaN  2000.000000       4.0  NaN   8000.0
Ibadan      1.0  NaN    NaN        NaN  2000.000000       5.0  NaN  10000.0
Ikoyi       3.0  NaN    NaN        NaN  2000.000000       2.5  NaN   5000.0
Lekki       3.0  NaN    NaN        NaN  4000.000000       5.0  NaN  20000.0
Gbagada     9.0  NaN    NaN        NaN  2000.000000       3.0  NaN   6000.0
...         ...  ...    ...        ...          ...       ...  ...      ...
Lekki     382.0  NaN    NaN        NaN  3000.000000       5.0  NaN  15000.0
Surulere  384.0  NaN    NaN        NaN  3333.333333       4.0  NaN  14000.0
Ibadan    387.5  NaN    NaN        NaN  3000.000000       3.5  NaN  10500.0
Ikoyi     388.0  NaN    NaN        NaN  3000.000000       4.5  NaN  13000.0
Lekki     389.0  NaN    NaN        NaN  2000.000000       3.0  NaN   6000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Lekki     3005.000000
Surulere  3337.333333
Ibadan    3003.500000
Ikoyi     3004.500000
Lekki     2003.000000

[254 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     389.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Gbagada   392.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0  3002.0
Ikoyi     392.5  NaN    NaN        NaN  3000.0       2.5  NaN   7500.0  3002.5
Lekki     393.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Surulere  395.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0

[258 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     393.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Surulere  395.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada   397.5  NaN    NaN        NaN  3500.0       3.0  NaN   9500.0  3503.0
Ibadan    398.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Lekki     398.5  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0  4003.5

[261 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     398.5  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0  4003.5
Ibadan    403.5  NaN    NaN        NaN  2500.0       1.5  NaN   4000.0  2501.5
Ikoyi     404.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Lekki     403.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0
Surulere  401.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0

[265 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada     5.0  NaN    NaN        NaN  2000.0      4.00  NaN   8000.0
Ibadan      1.0  NaN    NaN        NaN  2000.0      5.00  NaN  10000.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0      2.50  NaN   5000.0
Lekki       3.0  NaN    NaN        NaN  4000.0      5.00  NaN  20000.0
Gbagada     9.0  NaN    NaN        NaN  2000.0      3.00  NaN   6000.0
...         ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     404.0  NaN    NaN        NaN  2000.0      4.00  NaN   8000.0
Lekki     403.0  NaN    NaN        NaN  3000.0      4.00  NaN  12000.0
Surulere  401.0  NaN    NaN        NaN  4000.0      1.00  NaN   4000.0
Ibadan    408.5  NaN    NaN        NaN  2500.0      3.75  NaN   9750.0
Surulere  406.0  NaN    NaN        NaN  3000.0      4.00  NaN  12000.0

             Snap
Gbagada   2004.00
Ibadan    2005.00
Ikoyi     2002.50
Lekki     4005.00
Gbagada   2003.00
...           ...
Ikoyi     2004.00
Lekki     3004.00
Surulere  4001.00
Ibadan    2503.75
Surulere  3004.00

[267 rows x 9 columns]
                 S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...              ...  ...    ...        ...          ...       ...  ...
Ibadan    408.500000  NaN    NaN        NaN  2500.000000  3.750000  NaN
Surulere  406.000000  NaN    NaN        NaN  3000.000000  4.000000  NaN
Ikoyi     412.333333  NaN    NaN        NaN  2333.333333  3.333333  NaN
Lekki     413.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Surulere  415.000000  NaN    NaN        NaN  3000.000000  3.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ibadan     9750.000000  2503.750000
Surulere  12000.000000  3004.000000
Ikoyi      7666.666667  2336.666667
Lekki      8000.000000  2004.000000
Surulere   9000.000000  3003.000000

[270 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     413.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Surulere  415.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Ibadan    420.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ikoyi     418.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Lekki     417.0  NaN    NaN        NaN  2500.0       3.0  NaN   7000.0  2503.0

[273 rows x 9 columns]
                S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada    5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan     1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi      3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki      3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada    9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...             ...  ...    ...        ...          ...       ...  ...
Ikoyi    418.000000  NaN    NaN        NaN  3000.000000       3.0  NaN
Lekki    417.000000  NaN    NaN        NaN  2500.000000       3.0  NaN
Gbagada  424.000000  NaN    NaN        NaN  4000.000000       4.0  NaN
Ibadan   423.333333  NaN    NaN        NaN  2333.333333       3.0  NaN
Ikoyi    421.000000  NaN    NaN        NaN  2000.000000       3.0  NaN

              Revenue         Snap
Gbagada   8000.000000  2004.000000
Ibadan   10000.000000  2005.000000
Ikoyi     5000.000000  2002.500000
Lekki    20000.000000  4005.000000
Gbagada   6000.000000  2003.000000
...               ...          ...
Ikoyi     9000.000000  3003.000000
Lekki     7000.000000  2503.000000
Gbagada  16000.000000  4004.000000
Ibadan    6666.666667  2336.333333
Ikoyi     6000.000000  2003.000000

[276 rows x 9 columns]
                S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada    5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan     1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi      3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki      3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada    9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...             ...  ...    ...        ...          ...       ...  ...
Gbagada  424.000000  NaN    NaN        NaN  4000.000000       4.0  NaN
Ibadan   423.333333  NaN    NaN        NaN  2333.333333       3.0  NaN
Ikoyi    421.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
Ikoyi    428.333333  NaN    NaN        NaN  3000.000000       2.0  NaN
Lekki    427.500000  NaN    NaN        NaN  2500.000000       3.0  NaN

              Revenue         Snap
Gbagada   8000.000000  2004.000000
Ibadan   10000.000000  2005.000000
Ikoyi     5000.000000  2002.500000
Lekki    20000.000000  4005.000000
Gbagada   6000.000000  2003.000000
...               ...          ...
Gbagada  16000.000000  4004.000000
Ibadan    6666.666667  2336.333333
Ikoyi     6000.000000  2003.000000
Ikoyi     6000.000000  3002.000000
Lekki     6500.000000  2503.000000

[278 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     427.5  NaN    NaN        NaN  2500.0       3.0  NaN   6500.0  2503.0
Gbagada   432.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan    434.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0
Ikoyi     434.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Surulere  431.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0

[282 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi     434.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Surulere  431.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan    437.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Ikoyi     437.0  NaN    NaN        NaN  3000.0       2.5  NaN   9000.0  3002.5
Lekki     439.5  NaN    NaN        NaN  3500.0       4.0  NaN  14500.0  3504.0

[285 rows x 9 columns]
                S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada    5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan     1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi      3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki      3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada    9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...             ...  ...    ...        ...          ...       ...  ...
Ikoyi    437.000000  NaN    NaN        NaN  3000.000000       2.5  NaN
Lekki    439.500000  NaN    NaN        NaN  3500.000000       4.0  NaN
Gbagada  442.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
Ibadan   442.666667  NaN    NaN        NaN  3333.333333       3.0  NaN
Ikoyi    445.000000  NaN    NaN        NaN  3000.000000       3.0  NaN

              Revenue         Snap
Gbagada   8000.000000  2004.000000
Ibadan   10000.000000  2005.000000
Ikoyi     5000.000000  2002.500000
Lekki    20000.000000  4005.000000
Gbagada   6000.000000  2003.000000
...               ...          ...
Ikoyi     9000.000000  3002.500000
Lekki    14500.000000  3504.000000
Gbagada   6000.000000  2003.000000
Ibadan    9333.333333  3336.333333
Ikoyi     9000.000000  3003.000000

[288 rows x 9 columns]
                 S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...              ...  ...    ...        ...          ...       ...  ...
Ibadan    442.666667  NaN    NaN        NaN  3333.333333       3.0  NaN
Ikoyi     445.000000  NaN    NaN        NaN  3000.000000       3.0  NaN
Ibadan    446.000000  NaN    NaN        NaN  4000.000000       4.0  NaN
Lekki     448.500000  NaN    NaN        NaN  4000.000000       1.5  NaN
Surulere  448.500000  NaN    NaN        NaN  2500.000000       4.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ibadan     9333.333333  3336.333333
Ikoyi      9000.000000  3003.000000
Ibadan    16000.000000  4004.000000
Lekki      6000.000000  4001.500000
Surulere  10500.000000  2504.000000

[291 rows x 9 columns]

            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     448.5  NaN    NaN        NaN  4000.0       1.5  NaN   6000.0  4001.5
Surulere  448.5  NaN    NaN        NaN  2500.0       4.0  NaN  10500.0  2504.0
Gbagada   453.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Ibadan    454.5  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Lekki     451.5  NaN    NaN        NaN  3000.0       2.0  NaN   7000.0  3002.0

[294 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     451.5  NaN    NaN        NaN  3000.0       2.0  NaN   7000.0  3002.0
Gbagada   460.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ibadan    457.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0  3002.0
Ikoyi     457.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Surulere  459.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0

[298 rows x 9 columns]
                 S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...              ...  ...    ...        ...          ...       ...  ...
Ibadan    457.000000  NaN    NaN        NaN  3000.000000  2.000000  NaN
Ikoyi     457.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Surulere  459.000000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Gbagada   463.666667  NaN    NaN        NaN  2333.333333  3.333333  NaN
Lekki     462.000000  NaN    NaN        NaN  2500.000000  2.500000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ibadan     6000.000000  3002.000000
Ikoyi      6000.000000  2003.000000
Surulere  12000.000000  4003.000000
Gbagada    8333.333333  2336.666667
Lekki      6500.000000  2502.500000

[300 rows x 9 columns]
           S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada    5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan     1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi      3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki      3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada    9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...        ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki    462.0  NaN    NaN        NaN  2500.0       2.5  NaN   6500.0  2502.5
Gbagada  469.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ibadan   470.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0
Ikoyi    466.5  NaN    NaN        NaN  2000.0       1.5  NaN   3000.0  2001.5
Lekki    468.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0

[304 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     468.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Ibadan    474.5  NaN    NaN        NaN  2500.0       2.5  NaN   6000.0  2502.5
Ikoyi     472.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Lekki     473.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Surulere  471.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0  3001.0

[308 rows x 9 columns]
                 S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...              ...  ...    ...        ...          ...       ...  ...
Lekki     473.000000  NaN    NaN        NaN  4000.000000       3.0  NaN
Surulere  471.000000  NaN    NaN        NaN  3000.000000       1.0  NaN
Ibadan    477.333333  NaN    NaN        NaN  3666.666667       3.0  NaN
Ikoyi     478.000000  NaN    NaN        NaN  4000.000000       2.0  NaN
Lekki     480.000000  NaN    NaN        NaN  2000.000000       2.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki     12000.000000  4003.000000
Surulere   3000.000000  3001.000000
Ibadan    11333.333333  3669.666667
Ikoyi      8000.000000  4002.000000
Lekki      4000.000000  2002.000000

[311 rows x 9 columns]
                 S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada     5.000000  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan      1.000000  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi       3.000000  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki       3.000000  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada     9.000000  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...              ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     478.000000  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Lekki     480.000000  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Ibadan    482.333333  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ikoyi     483.000000  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Surulere  485.000000  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     4002.0
Lekki     2002.0
Ibadan    3004.0
Ikoyi     3005.0
Surulere  3003.0

[314 rows x 9 columns]
                 S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.0       4.0  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.0       5.0  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.0       2.5  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.0       5.0  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.0       3.0  NaN
...              ...  ...    ...        ...     ...       ...  ...
Ikoyi     483.000000  NaN    NaN        NaN  3000.0       5.0  NaN
Surulere  485.000000  NaN    NaN        NaN  3000.0       3.0  NaN
Gbagada   488.333333  NaN    NaN        NaN  3000.0       3.0  NaN
Ikoyi     486.000000  NaN    NaN        NaN  2000.0       2.0  NaN
Lekki     489.000000  NaN    NaN        NaN  4000.0       5.0  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Ikoyi     15000.000000  3005.0
Surulere   9000.000000  3003.0
Gbagada    9333.333333  3003.0
Ikoyi      4000.000000  2002.0
Lekki     20000.000000  4005.0

[317 rows x 9 columns]
           S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada    5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan     1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi      3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki      3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada    9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...        ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi    486.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0
Lekki    489.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Ibadan   493.5  NaN    NaN        NaN  3000.0       3.0  NaN  11000.0  3003.0
Ikoyi    491.5  NaN    NaN        NaN  3500.0       4.0  NaN  14000.0  3504.0
Lekki    495.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0

[320 rows x 9 columns]

           S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada    5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan     1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi      3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki      3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada    9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...        ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki    495.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Gbagada  497.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ibadan   498.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0
Ikoyi    498.0  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0  4003.5
Lekki    499.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0

[324 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     499.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada   504.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Ibadan    502.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0
Lekki     505.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Surulere  502.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0

[328 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  502.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada   507.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Ibadan    509.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Ikoyi     507.0  NaN    NaN        NaN  3500.0       1.5  NaN   5000.0  3501.5
Lekki     510.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0

[332 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     510.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0
Gbagada   512.5  NaN    NaN        NaN  3500.0       4.0  NaN  13500.0  3504.0
Ikoyi     511.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Lekki     515.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Surulere  514.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0

[336 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     515.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Surulere  514.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Gbagada   517.5  NaN    NaN        NaN  3000.0       1.5  NaN   4500.0  3001.5
Ikoyi     517.5  NaN    NaN        NaN  3500.0       2.5  NaN   8000.0  3502.5
Surulere  520.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0

[339 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  520.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Gbagada   522.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ibadan    525.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Ikoyi     522.0  NaN    NaN        NaN  3500.0       3.0  NaN  10000.0  3503.0
Surulere  524.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0

[343 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi     522.0  NaN    NaN        NaN  3500.0       3.0  NaN  10000.0  3503.0
Surulere  524.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Gbagada   526.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Ibadan    529.0  NaN    NaN        NaN  3000.0       3.0  NaN   8000.0  3003.0
Ikoyi     528.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0

[346 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ibadan    529.0  NaN    NaN        NaN  3000.0       3.0  NaN   8000.0  3003.0
Ikoyi     528.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ikoyi     534.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Lekki     533.5  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Surulere  532.0  NaN    NaN        NaN  3000.0       2.5  NaN   8000.0  3002.5

[349 rows x 9 columns]
                 S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada     5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.0
Ibadan      1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.0
Ikoyi       3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.0
Lekki       3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.0
Gbagada     9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.0
...              ...  ...    ...        ...     ...       ...  ...      ...
Lekki     533.500000  NaN    NaN        NaN  4000.0  2.000000  NaN   8000.0
Surulere  532.000000  NaN    NaN        NaN  3000.0  2.500000  NaN   8000.0
Gbagada   537.000000  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.0
Ibadan    538.000000  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.0
Ikoyi     538.333333  NaN    NaN        NaN  3000.0  3.666667  NaN  11000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Lekki     4002.000000
Surulere  3002.500000
Gbagada   4005.000000
Ibadan    2003.000000
Ikoyi     3003.666667

[352 rows x 9 columns]
                 S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada     5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.0
Ibadan      1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.0
Ikoyi       3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.0
Lekki       3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.0
Gbagada     9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.0
...              ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     538.333333  NaN    NaN        NaN  3000.0  3.666667  NaN  11000.0
Gbagada   544.000000  NaN    NaN        NaN  4000.0  2.000000  NaN   8000.0
Ibadan    541.500000  NaN    NaN        NaN  4000.0  3.000000  NaN  12000.0
Lekki     543.000000  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.0
Surulere  545.000000  NaN    NaN        NaN  4000.0  2.000000  NaN   8000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Ikoyi     3003.666667
Gbagada   4002.000000
Ibadan    4003.000000
Lekki     4005.000000
Surulere  4002.000000

[356 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Gbagada   544.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Ibadan    541.5  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Lekki     543.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Surulere  545.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Ibadan    548.0  NaN    NaN        NaN  2800.0       2.0  NaN   6400.0  2802.0

[357 rows x 9 columns]
                 S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...              ...  ...    ...        ...          ...       ...  ...
Surulere  545.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Ibadan    548.000000  NaN    NaN        NaN  2800.000000  2.000000  NaN
Gbagada   553.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ikoyi     552.666667  NaN    NaN        NaN  2333.333333  4.333333  NaN
Lekki     554.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Surulere   8000.000000  4002.000000
Ibadan     6400.000000  2802.000000
Gbagada    8000.000000  2004.000000
Ikoyi     10333.333333  2337.666667
Lekki      8000.000000  4002.000000

[360 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     554.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Ibadan    556.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Ikoyi     558.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0
Lekki     560.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0  3002.0
Surulere  558.0  NaN    NaN        NaN  3000.0       4.0  NaN  11000.0  3004.0

[364 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     560.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0  3002.0
Surulere  558.0  NaN    NaN        NaN  3000.0       4.0  NaN  11000.0  3004.0
Gbagada   562.0  NaN    NaN        NaN  3500.0       3.0  NaN  10500.0  3503.0
Ibadan    563.0  NaN    NaN        NaN  2500.0       1.0  NaN   2500.0  2501.0
Surulere  565.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0

[367 rows x 9 columns]

            S/N Date Branch Pizza Sold   Price  Quantity Time       Revenue  \
Gbagada     5.0  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.000000
Ibadan      1.0  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.000000
Ikoyi       3.0  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.000000
Lekki       3.0  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.000000
Gbagada     9.0  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.000000
...         ...  ...    ...        ...     ...       ...  ...           ...
Ibadan    563.0  NaN    NaN        NaN  2500.0  1.000000  NaN   2500.000000
Surulere  565.0  NaN    NaN        NaN  4000.0  3.000000  NaN  12000.000000
Ibadan    569.0  NaN    NaN        NaN  3000.0  2.666667  NaN   7666.666667
Ikoyi     566.0  NaN    NaN        NaN  4000.0  1.000000  NaN   4000.000000
Lekki     567.0  NaN    NaN        NaN  2000.0  2.000000  NaN   4000.000000

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Ibadan    2501.000000
Surulere  4003.000000
Ibadan    3002.666667
Ikoyi     4001.000000
Lekki     2002.000000

[370 rows x 9 columns]
           S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada    5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan     1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi      3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki      3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada    9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...        ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi    566.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Lekki    567.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0
Gbagada  572.5  NaN    NaN        NaN  3500.0       4.0  NaN  13500.0  3504.0
Ikoyi    574.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Lekki    573.0  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0  4003.5

[373 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time       Revenue  \
Gbagada     5.0  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.000000
Ibadan      1.0  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.000000
Ikoyi       3.0  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.000000
Lekki       3.0  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.000000
Gbagada     9.0  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.000000
...         ...  ...    ...        ...     ...       ...  ...           ...
Ikoyi     574.0  NaN    NaN        NaN  3000.0  3.000000  NaN   9000.000000
Lekki     573.0  NaN    NaN        NaN  4000.0  3.500000  NaN  14000.000000
Gbagada   579.0  NaN    NaN        NaN  2000.0  1.000000  NaN   2000.000000
Ibadan    578.0  NaN    NaN        NaN  3000.0  4.333333  NaN  12333.333333
Surulere  577.0  NaN    NaN        NaN  3000.0  5.000000  NaN  15000.000000

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Ikoyi     3003.000000
Lekki     4003.500000
Gbagada   2001.000000
Ibadan    3004.333333
Surulere  3005.000000

[376 rows x 9 columns]
            S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...         ...  ...    ...        ...          ...       ...  ...
Ibadan    578.0  NaN    NaN        NaN  3000.000000  4.333333  NaN
Surulere  577.0  NaN    NaN        NaN  3000.000000  5.000000  NaN
Gbagada   583.0  NaN    NaN        NaN  3333.333333  3.000000  NaN
Ikoyi     582.0  NaN    NaN        NaN  4000.000000  1.000000  NaN
Surulere  584.0  NaN    NaN        NaN  2000.000000  2.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ibadan    12333.333333  3004.333333
Surulere  15000.000000  3005.000000
Gbagada   10333.333333  3336.333333
Ikoyi      4000.000000  4001.000000
Surulere   4000.000000  2002.000000

[379 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi     582.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Surulere  584.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0
Ibadan    589.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Lekki     586.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Surulere  588.0  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0  4003.5

[382 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada     5.00  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan      1.00  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi       3.00  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki       3.00  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada     9.00  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    589.00  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     586.00  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Surulere  588.00  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0
Ibadan    592.00  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi     593.25  NaN    NaN        NaN  2750.0       2.5  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    4003.0
Lekki     2005.0
Surulere  4003.5
Ibadan    2005.0
Ikoyi     2752.5

[384 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Gbagada   598.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Ibadan    596.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Ikoyi     599.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Lekki     597.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Surulere  600.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0

[389 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  600.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0
Gbagada   601.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0
Ibadan    604.0  NaN    NaN        NaN  2000.0       3.5  NaN   7000.0  2003.5
Ikoyi     602.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0
Lekki     604.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0

[393 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time       Revenue  \
Gbagada     5.0  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.000000
Ibadan      1.0  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.000000
Ikoyi       3.0  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.000000
Lekki       3.0  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.000000
Gbagada     9.0  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.000000
...         ...  ...    ...        ...     ...       ...  ...           ...
Ibadan    604.0  NaN    NaN        NaN  2000.0  3.500000  NaN   7000.000000
Ikoyi     602.0  NaN    NaN        NaN  3000.0  4.000000  NaN  12000.000000
Lekki     604.0  NaN    NaN        NaN  4000.0  1.000000  NaN   4000.000000
Ikoyi     608.0  NaN    NaN        NaN  2000.0  2.000000  NaN   4000.000000
Surulere  608.0  NaN    NaN        NaN  4000.0  3.666667  NaN  14666.666667

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Ibadan    2003.500000
Ikoyi     3004.000000
Lekki     4001.000000
Ikoyi     2002.000000
Surulere  4003.666667

[395 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time       Revenue  \
Gbagada     5.0  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.000000
Ibadan      1.0  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.000000
Ikoyi       3.0  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.000000
Lekki       3.0  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.000000
Gbagada     9.0  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.000000
...         ...  ...    ...        ...     ...       ...  ...           ...
Surulere  608.0  NaN    NaN        NaN  4000.0  3.666667  NaN  14666.666667
Gbagada   615.0  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.000000
Ibadan    613.0  NaN    NaN        NaN  3000.0  3.000000  NaN   9000.000000
Ikoyi     612.5  NaN    NaN        NaN  3000.0  2.000000  NaN   5000.000000
Surulere  612.0  NaN    NaN        NaN  3000.0  2.000000  NaN   6000.000000

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Surulere  4003.666667
Gbagada   2004.000000
Ibadan    3003.000000
Ikoyi     3002.000000
Surulere  3002.000000

[399 rows x 9 columns]

            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi     612.5  NaN    NaN        NaN  3000.0       2.0  NaN   5000.0  3002.0
Surulere  612.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0  3002.0
Gbagada   619.5  NaN    NaN        NaN  3500.0       3.5  NaN  12500.0  3503.5
Ibadan    616.5  NaN    NaN        NaN  3500.0       3.5  NaN  12500.0  3503.5
Ikoyi     618.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0

[402 rows x 9 columns]
           S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada    5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan     1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi      3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki      3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada    9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...        ...  ...    ...        ...     ...       ...  ...      ...     ...
Ibadan   616.5  NaN    NaN        NaN  3500.0       3.5  NaN  12500.0  3503.5
Ikoyi    618.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan   624.5  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Ikoyi    622.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Lekki    622.0  NaN    NaN        NaN  3500.0       1.5  NaN   5500.0  3501.5

[405 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     622.0  NaN    NaN        NaN  3500.0       1.5  NaN   5500.0  3501.5
Gbagada   629.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Ibadan    627.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0
Lekki     628.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Surulere  628.0  NaN    NaN        NaN  3000.0       1.5  NaN   5000.0  3001.5

[409 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  628.0  NaN    NaN        NaN  3000.0       1.5  NaN   5000.0  3001.5
Gbagada   632.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan    633.5  NaN    NaN        NaN  3000.0       3.5  NaN  12000.0  3003.5
Ikoyi     635.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0
Lekki     631.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0

[413 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     631.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Gbagada   637.5  NaN    NaN        NaN  3500.0       5.0  NaN  17500.0  3505.0
Ibadan    639.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Ikoyi     636.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0
Surulere  640.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0

[417 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  640.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Gbagada   641.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Ibadan    643.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Ikoyi     643.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Lekki     645.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0

[421 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi     643.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Lekki     645.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Gbagada   649.5  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki     646.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Surulere  647.5  NaN    NaN        NaN  3500.0       3.5  NaN  11500.0  3503.5

[424 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  647.5  NaN    NaN        NaN  3500.0       3.5  NaN  11500.0  3503.5
Gbagada   652.0  NaN    NaN        NaN  2500.0       1.5  NaN   4000.0  2501.5
Ibadan    652.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Lekki     654.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0  3001.0
Surulere  655.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0

[428 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  655.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0
Gbagada   659.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Ibadan    658.5  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Lekki     658.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0
Surulere  656.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0

[432 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     658.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0
Surulere  656.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Gbagada   662.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ibadan    665.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Surulere  664.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0

[435 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  664.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Gbagada   670.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0  3002.0
Ibadan    668.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Ikoyi     669.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Surulere  666.5  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0

[439 rows x 9 columns]

            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  666.5  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Gbagada   674.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0
Ibadan    672.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Lekki     674.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Surulere  671.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0

[443 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada     5.0  NaN    NaN        NaN  2000.0      4.00  NaN   8000.0
Ibadan      1.0  NaN    NaN        NaN  2000.0      5.00  NaN  10000.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0      2.50  NaN   5000.0
Lekki       3.0  NaN    NaN        NaN  4000.0      5.00  NaN  20000.0
Gbagada     9.0  NaN    NaN        NaN  2000.0      3.00  NaN   6000.0
...         ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    672.0  NaN    NaN        NaN  4000.0      2.00  NaN   8000.0
Lekki     674.0  NaN    NaN        NaN  4000.0      3.00  NaN  12000.0
Surulere  671.0  NaN    NaN        NaN  2000.0      3.00  NaN   6000.0
Gbagada   678.0  NaN    NaN        NaN  3500.0      3.75  NaN  13500.0
Ibadan    678.0  NaN    NaN        NaN  2000.0      1.00  NaN   2000.0

             Snap
Gbagada   2004.00
Ibadan    2005.00
Ikoyi     2002.50
Lekki     4005.00
Gbagada   2003.00
...           ...
Ibadan    4002.00
Lekki     4003.00
Surulere  2003.00
Gbagada   3503.75
Ibadan    2001.00

[445 rows x 9 columns]
           S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue     Snap
Gbagada    5.0  NaN    NaN        NaN  2000.0      4.00  NaN   8000.0  2004.00
Ibadan     1.0  NaN    NaN        NaN  2000.0      5.00  NaN  10000.0  2005.00
Ikoyi      3.0  NaN    NaN        NaN  2000.0      2.50  NaN   5000.0  2002.50
Lekki      3.0  NaN    NaN        NaN  4000.0      5.00  NaN  20000.0  4005.00
Gbagada    9.0  NaN    NaN        NaN  2000.0      3.00  NaN   6000.0  2003.00
...        ...  ...    ...        ...     ...       ...  ...      ...      ...
Gbagada  678.0  NaN    NaN        NaN  3500.0      3.75  NaN  13500.0  3503.75
Ibadan   678.0  NaN    NaN        NaN  2000.0      1.00  NaN   2000.0  2001.00
Ibadan   683.0  NaN    NaN        NaN  2000.0      3.50  NaN   7000.0  2003.50
Ikoyi    684.0  NaN    NaN        NaN  2000.0      1.50  NaN   3000.0  2001.50
Lekki    681.0  NaN    NaN        NaN  3000.0      3.00  NaN   9000.0  3003.00

[448 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     681.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Gbagada   686.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Ibadan    688.5  NaN    NaN        NaN  3000.0       3.5  NaN   9000.0  3003.5
Ikoyi     689.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Surulere  688.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0

[452 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi     689.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Surulere  688.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Gbagada   693.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Ibadan    694.5  NaN    NaN        NaN  4000.0       1.5  NaN   6000.0  4001.5
Ikoyi     691.5  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0

[455 rows x 9 columns]
           S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada    5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan     1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi      3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki      3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada    9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...        ...  ...    ...        ...     ...       ...  ...      ...     ...
Gbagada  693.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Ibadan   694.5  NaN    NaN        NaN  4000.0       1.5  NaN   6000.0  4001.5
Ikoyi    691.5  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ikoyi    698.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Lekki    698.0  NaN    NaN        NaN  3250.0       2.5  NaN   7500.0  3252.5

[457 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     698.0  NaN    NaN        NaN  3250.0       2.5  NaN   7500.0  3252.5
Ibadan    702.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ikoyi     705.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0
Lekki     704.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Surulere  702.0  NaN    NaN        NaN  3500.0       3.5  NaN  11500.0  3503.5

[461 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  702.0  NaN    NaN        NaN  3500.0       3.5  NaN  11500.0  3503.5
Gbagada   707.5  NaN    NaN        NaN  3000.0       3.5  NaN  12000.0  3003.5
Ikoyi     706.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0
Lekki     709.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0
Surulere  710.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0

[465 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time       Revenue  \
Gbagada     5.0  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.000000
Ibadan      1.0  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.000000
Ikoyi       3.0  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.000000
Lekki       3.0  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.000000
Gbagada     9.0  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.000000
...         ...  ...    ...        ...     ...       ...  ...           ...
Lekki     709.0  NaN    NaN        NaN  2000.0  2.000000  NaN   4000.000000
Surulere  710.0  NaN    NaN        NaN  4000.0  2.000000  NaN   8000.000000
Ibadan    715.0  NaN    NaN        NaN  4000.0  3.000000  NaN  12000.000000
Lekki     713.0  NaN    NaN        NaN  4000.0  2.666667  NaN  10666.666667
Surulere  711.0  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.000000

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Lekki     2002.000000
Surulere  4002.000000
Ibadan    4003.000000
Lekki     4002.666667
Surulere  4005.000000

[468 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  711.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada   717.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Ibadan    718.5  NaN    NaN        NaN  4000.0       4.5  NaN  18000.0  4004.5
Ikoyi     716.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Lekki     720.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0  3001.0

[472 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     720.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0  3001.0
Gbagada   724.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Ibadan    724.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Ikoyi     721.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Surulere  722.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0

[476 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi     721.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Surulere  722.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Gbagada   727.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Ibadan    728.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Lekki     728.5  NaN    NaN        NaN  3500.0       3.0  NaN  10500.0  3503.0

[479 rows x 9 columns]
           S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada    5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan     1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi      3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki      3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada    9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...        ...  ...    ...        ...          ...       ...  ...
Ibadan   728.0  NaN    NaN        NaN  4000.000000  3.000000  NaN
Lekki    728.5  NaN    NaN        NaN  3500.000000  3.000000  NaN
Gbagada  732.0  NaN    NaN        NaN  3666.666667  4.333333  NaN
Ibadan   735.0  NaN    NaN        NaN  2000.000000  2.000000  NaN
Ikoyi    734.0  NaN    NaN        NaN  3000.000000  3.000000  NaN

              Revenue    Snap
Gbagada   8000.000000  2004.0
Ibadan   10000.000000  2005.0
Ikoyi     5000.000000  2002.5
Lekki    20000.000000  4005.0
Gbagada   6000.000000  2003.0
...               ...     ...
Ibadan   12000.000000  4003.0
Lekki    10500.000000  3503.0
Gbagada  15666.666667  3671.0
Ibadan    4000.000000  2002.0
Ikoyi     9000.000000  3003.0

[482 rows x 9 columns]

           S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada    5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan     1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi      3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki      3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada    9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...        ...  ...    ...        ...     ...       ...  ...      ...     ...
Ibadan   735.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0
Ikoyi    734.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Gbagada  738.0  NaN    NaN        NaN  3000.0       4.5  NaN  14000.0  3004.5
Ikoyi    738.0  NaN    NaN        NaN  3000.0       4.5  NaN  13500.0  3004.5
Lekki    738.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0

[485 rows x 9 columns]
                 S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...              ...  ...    ...        ...          ...       ...  ...
Ikoyi     738.000000  NaN    NaN        NaN  3000.000000  4.500000  NaN
Lekki     738.000000  NaN    NaN        NaN  4000.000000  1.000000  NaN
Ikoyi     742.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Lekki     745.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN
Surulere  742.666667  NaN    NaN        NaN  2666.666667  3.666667  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi     13500.000000  3004.500000
Lekki      4000.000000  4001.000000
Ikoyi      8000.000000  2004.000000
Lekki     16000.000000  4004.000000
Surulere  10333.333333  2670.333333

[488 rows x 9 columns]
                 S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...              ...  ...    ...        ...          ...       ...  ...
Lekki     745.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN
Surulere  742.666667  NaN    NaN        NaN  2666.666667  3.666667  NaN
Gbagada   748.500000  NaN    NaN        NaN  4000.000000  3.500000  NaN
Ibadan    748.000000  NaN    NaN        NaN  3000.000000  3.500000  NaN
Ikoyi     747.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki     16000.000000  4004.000000
Surulere  10333.333333  2670.333333
Gbagada   14000.000000  4003.500000
Ibadan    12000.000000  3003.500000
Ikoyi     20000.000000  4005.000000

[491 rows x 9 columns]
           S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada    5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan     1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi      3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki      3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada    9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...        ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi    747.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada  753.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Ibadan   751.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ikoyi    754.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Lekki    753.5  NaN    NaN        NaN  3500.0       3.0  NaN  10500.0  3503.0

[495 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi     754.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Lekki     753.5  NaN    NaN        NaN  3500.0       3.0  NaN  10500.0  3503.0
Gbagada   759.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0
Ikoyi     757.5  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Surulere  758.0  NaN    NaN        NaN  3000.0       3.5  NaN  10500.0  3003.5

[498 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  758.0  NaN    NaN        NaN  3000.0       3.5  NaN  10500.0  3003.5
Gbagada   763.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ibadan    763.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Ikoyi     764.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Surulere  762.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0

[502 rows x 9 columns]
                 S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...              ...  ...    ...        ...          ...       ...  ...
Ikoyi     764.000000  NaN    NaN        NaN  4000.000000  1.000000  NaN
Surulere  762.000000  NaN    NaN        NaN  3000.000000  4.000000  NaN
Gbagada   770.000000  NaN    NaN        NaN  3000.000000  5.000000  NaN
Ibadan    767.666667  NaN    NaN        NaN  2666.666667  1.666667  NaN
Lekki     767.000000  NaN    NaN        NaN  4000.000000  1.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi      4000.000000  4001.000000
Surulere  12000.000000  3004.000000
Gbagada   15000.000000  3005.000000
Ibadan     4666.666667  2668.333333
Lekki      4000.000000  4001.000000

[505 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     767.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Gbagada   771.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Ikoyi     773.5  NaN    NaN        NaN  3500.0       1.5  NaN   5500.0  3501.5
Lekki     773.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Surulere  774.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0

[509 rows x 9 columns]
                 S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...              ...  ...    ...        ...          ...       ...  ...
Lekki     773.000000  NaN    NaN        NaN  4000.000000       4.0  NaN
Surulere  774.000000  NaN    NaN        NaN  2000.000000       1.0  NaN
Ibadan    778.333333  NaN    NaN        NaN  3333.333333       4.0  NaN
Ikoyi     776.000000  NaN    NaN        NaN  4000.000000       1.0  NaN
Lekki     779.000000  NaN    NaN        NaN  4000.000000       5.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki     16000.000000  4004.000000
Surulere   2000.000000  2001.000000
Ibadan    12666.666667  3337.333333
Ikoyi      4000.000000  4001.000000
Lekki     20000.000000  4005.000000

[512 rows x 9 columns]
           S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada    5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan     1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi      3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki      3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada    9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...        ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki    779.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada  783.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Ibadan   781.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Ikoyi    782.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Lekki    784.5  NaN    NaN        NaN  2000.0       3.5  NaN   7000.0  2003.5

[516 rows x 9 columns]
            S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.0  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan      1.0  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi       3.0  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki       3.0  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada     9.0  NaN    NaN        NaN  2000.000000       3.0  NaN
...         ...  ...    ...        ...          ...       ...  ...
Ikoyi     782.0  NaN    NaN        NaN  2000.000000       4.0  NaN
Lekki     784.5  NaN    NaN        NaN  2000.000000       3.5  NaN
Ibadan    788.0  NaN    NaN        NaN  3666.666667       1.0  NaN
Ikoyi     787.0  NaN    NaN        NaN  3000.000000       4.0  NaN
Surulere  789.0  NaN    NaN        NaN  4000.000000       3.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi      8000.000000  2004.000000
Lekki      7000.000000  2003.500000
Ibadan     3666.666667  3667.666667
Ikoyi     12000.000000  3004.000000
Surulere  12000.000000  4003.000000

[519 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  789.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Gbagada   795.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Ikoyi     792.5  NaN    NaN        NaN  2500.0       1.5  NaN   3500.0  2501.5
Lekki     792.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Surulere  793.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0

[523 rows x 9 columns]
                 S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...              ...  ...    ...        ...          ...       ...  ...
Lekki     792.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Surulere  793.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada   797.666667  NaN    NaN        NaN  2666.666667  2.333333  NaN
Ibadan    798.000000  NaN    NaN        NaN  3000.000000  3.000000  NaN
Surulere  799.000000  NaN    NaN        NaN  3000.000000  5.000000  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Lekki      8000.000000  4002.0
Surulere  20000.000000  4005.0
Gbagada    5333.333333  2669.0
Ibadan     9000.000000  3003.0
Surulere  15000.000000  3005.0

[526 rows x 9 columns]
            S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada     5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0
Ibadan      1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ikoyi       3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN   5000.0
Lekki       3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Gbagada     9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
...         ...  ...    ...        ...          ...       ...  ...      ...
Ibadan    798.0  NaN    NaN        NaN  3000.000000  3.000000  NaN   9000.0
Surulere  799.0  NaN    NaN        NaN  3000.000000  5.000000  NaN  15000.0
Ibadan    803.0  NaN    NaN        NaN  3666.666667  2.333333  NaN   8000.0
Ikoyi     801.0  NaN    NaN        NaN  4000.000000  4.000000  NaN  16000.0
Surulere  805.0  NaN    NaN        NaN  3000.000000  4.000000  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    3003.0
Surulere  3005.0
Ibadan    3669.0
Ikoyi     4004.0
Surulere  3004.0

[529 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  805.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0
Gbagada   807.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0
Ibadan    808.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ikoyi     807.5  NaN    NaN        NaN  4000.0       1.5  NaN   6000.0  4001.5
Lekki     810.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0

[533 rows x 9 columns]
            S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...         ...  ...    ...        ...          ...       ...  ...
Ibadan    808.0  NaN    NaN        NaN  4000.000000  3.000000  NaN
Ikoyi     807.5  NaN    NaN        NaN  4000.000000  1.500000  NaN
Lekki     810.0  NaN    NaN        NaN  4000.000000  2.000000  NaN
Gbagada   813.0  NaN    NaN        NaN  2666.666667  2.333333  NaN
Surulere  813.0  NaN    NaN        NaN  3000.000000  4.000000  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Ibadan    12000.000000  4003.0
Ikoyi      6000.000000  4001.5
Lekki      8000.000000  4002.0
Gbagada    5333.333333  2669.0
Surulere  13000.000000  3004.0

[535 rows x 9 columns]
            S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...         ...  ...    ...        ...          ...       ...  ...
Lekki     810.0  NaN    NaN        NaN  4000.000000  2.000000  NaN
Gbagada   813.0  NaN    NaN        NaN  2666.666667  2.333333  NaN
Surulere  813.0  NaN    NaN        NaN  3000.000000  4.000000  NaN
Gbagada   818.5  NaN    NaN        NaN  3750.000000  4.250000  NaN
Ikoyi     816.0  NaN    NaN        NaN  2000.000000  1.000000  NaN

               Revenue     Snap
Gbagada    8000.000000  2004.00
Ibadan    10000.000000  2005.00
Ikoyi      5000.000000  2002.50
Lekki     20000.000000  4005.00
Gbagada    6000.000000  2003.00
...                ...      ...
Lekki      8000.000000  4002.00
Gbagada    5333.333333  2669.00
Surulere  13000.000000  3004.00
Gbagada   15750.000000  3754.25
Ikoyi      2000.000000  2001.00

[537 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi     816.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Ibadan    825.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Ikoyi     822.5  NaN    NaN        NaN  4000.0       1.5  NaN   6000.0  4001.5
Lekki     821.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Surulere  824.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0

[541 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     821.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Surulere  824.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Gbagada   829.5  NaN    NaN        NaN  3500.0       4.0  NaN  14000.0  3504.0
Lekki     827.5  NaN    NaN        NaN  3000.0       3.5  NaN   9000.0  3003.5
Surulere  826.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0

[544 rows x 9 columns]
                 S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...              ...  ...    ...        ...          ...       ...  ...
Lekki     827.500000  NaN    NaN        NaN  3000.000000  3.500000  NaN
Surulere  826.000000  NaN    NaN        NaN  2000.000000  2.000000  NaN
Ikoyi     834.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Lekki     832.666667  NaN    NaN        NaN  3666.666667  4.666667  NaN
Surulere  833.000000  NaN    NaN        NaN  3000.000000  4.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      9000.000000  3003.500000
Surulere   4000.000000  2002.000000
Ikoyi      8000.000000  2004.000000
Lekki     17333.333333  3671.333333
Surulere  12000.000000  3004.000000

[547 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  833.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0
Gbagada   836.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ikoyi     839.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Lekki     838.5  NaN    NaN        NaN  3500.0       3.0  NaN  10000.0  3503.0
Surulere  838.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0  3001.0

[551 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     838.5  NaN    NaN        NaN  3500.0       3.0  NaN  10000.0  3503.0
Surulere  838.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0  3001.0
Gbagada   844.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0
Ibadan    843.5  NaN    NaN        NaN  4000.0       1.5  NaN   6000.0  4001.5
Surulere  842.0  NaN    NaN        NaN  3000.0       3.5  NaN   9000.0  3003.5

[554 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ibadan    843.5  NaN    NaN        NaN  4000.0       1.5  NaN   6000.0  4001.5
Surulere  842.0  NaN    NaN        NaN  3000.0       3.5  NaN   9000.0  3003.5
Ibadan    847.5  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Lekki     850.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Surulere  847.5  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0

[557 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     850.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Surulere  847.5  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Gbagada   853.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ikoyi     853.5  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0  4003.5
Surulere  852.5  NaN    NaN        NaN  3500.0       3.0  NaN  11500.0  3503.0

[560 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  852.5  NaN    NaN        NaN  3500.0       3.0  NaN  11500.0  3503.0
Gbagada   858.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0
Ibadan    857.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Ikoyi     859.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0  3001.0
Surulere  858.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0

[564 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi     859.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0  3001.0
Surulere  858.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0
Gbagada   861.5  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0  3002.0
Lekki     863.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Surulere  864.5  NaN    NaN        NaN  3000.0       4.5  NaN  14000.0  3004.5

[567 rows x 9 columns]

            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  864.5  NaN    NaN        NaN  3000.0       4.5  NaN  14000.0  3004.5
Gbagada   867.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan    868.0  NaN    NaN        NaN  2500.0       3.0  NaN   7000.0  2503.0
Ikoyi     868.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Lekki     869.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0

[571 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi     868.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Lekki     869.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada   874.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0  3001.0
Lekki     873.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Surulere  872.5  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0

[574 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  872.5  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Gbagada   879.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0
Ibadan    876.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0
Ikoyi     877.5  NaN    NaN        NaN  3500.0       3.5  NaN  13000.0  3503.5
Lekki     880.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0

[578 rows x 9 columns]
           S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada    5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan     1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi      3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki      3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada    9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...        ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi    877.5  NaN    NaN        NaN  3500.0       3.5  NaN  13000.0  3503.5
Lekki    880.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0
Gbagada  882.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Ikoyi    883.5  NaN    NaN        NaN  2500.0       2.5  NaN   7000.0  2502.5
Lekki    883.0  NaN    NaN        NaN  3000.0       4.5  NaN  13500.0  3004.5

[581 rows x 9 columns]
           S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada    5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan     1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi      3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki      3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada    9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...        ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi    883.5  NaN    NaN        NaN  2500.0       2.5  NaN   7000.0  2502.5
Lekki    883.0  NaN    NaN        NaN  3000.0       4.5  NaN  13500.0  3004.5
Gbagada  887.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Ikoyi    888.5  NaN    NaN        NaN  3000.0       3.0  NaN  11000.0  3003.0
Lekki    888.0  NaN    NaN        NaN  2500.0       3.0  NaN   8500.0  2503.0

[584 rows x 9 columns]
                 S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...              ...  ...    ...        ...          ...       ...  ...
Ikoyi     888.500000  NaN    NaN        NaN  3000.000000  3.000000  NaN
Lekki     888.000000  NaN    NaN        NaN  2500.000000  3.000000  NaN
Ibadan    893.000000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Ikoyi     892.333333  NaN    NaN        NaN  2666.666667  1.666667  NaN
Surulere  895.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi     11000.000000  3003.000000
Lekki      8500.000000  2503.000000
Ibadan    12000.000000  4003.000000
Ikoyi      4666.666667  2668.333333
Surulere   8000.000000  4002.000000

[587 rows x 9 columns]
                 S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...              ...  ...    ...        ...          ...       ...  ...
Ikoyi     892.333333  NaN    NaN        NaN  2666.666667  1.666667  NaN
Surulere  895.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Gbagada   898.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan    897.333333  NaN    NaN        NaN  2666.666667  3.333333  NaN
Surulere  900.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi      4666.666667  2668.333333
Surulere   8000.000000  4002.000000
Gbagada    8000.000000  2004.000000
Ibadan     8000.000000  2670.000000
Surulere  16000.000000  4004.000000

[590 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  900.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Ibadan    902.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Ikoyi     905.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Lekki     903.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Surulere  902.5  NaN    NaN        NaN  2000.0       3.5  NaN   7000.0  2003.5

[594 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  902.5  NaN    NaN        NaN  2000.0       3.5  NaN   7000.0  2003.5
Gbagada   906.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Ikoyi     908.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Lekki     910.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Surulere  908.0  NaN    NaN        NaN  3000.0       4.0  NaN  11000.0  3004.0

[598 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  908.0  NaN    NaN        NaN  3000.0       4.0  NaN  11000.0  3004.0
Gbagada   915.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan    914.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Ikoyi     912.5  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Surulere  911.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0

[602 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ibadan    914.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Ikoyi     912.5  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Surulere  911.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Gbagada   916.5  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0  3001.0
Surulere  919.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0

[604 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  919.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Gbagada   924.5  NaN    NaN        NaN  3500.0       3.0  NaN  10000.0  3503.0
Ikoyi     922.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Lekki     921.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0
Surulere  923.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0

[608 rows x 9 columns]
            S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada     5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0
Ibadan      1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ikoyi       3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN   5000.0
Lekki       3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Gbagada     9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
...         ...  ...    ...        ...          ...       ...  ...      ...
Lekki     921.0  NaN    NaN        NaN  3000.000000  5.000000  NaN  15000.0
Surulere  923.0  NaN    NaN        NaN  3000.000000  5.000000  NaN  15000.0
Gbagada   926.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ibadan    929.0  NaN    NaN        NaN  3333.333333  3.333333  NaN  10000.0
Lekki     927.0  NaN    NaN        NaN  3000.000000  5.000000  NaN  15000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Lekki     3005.000000
Surulere  3005.000000
Gbagada   2005.000000
Ibadan    3336.666667
Lekki     3005.000000

[611 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Gbagada   931.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Ibadan    932.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ikoyi     934.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Lekki     933.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Surulere  935.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0

[616 rows x 9 columns]
                 S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...              ...  ...    ...        ...          ...       ...  ...
Lekki     933.000000  NaN    NaN        NaN  4000.000000       4.0  NaN
Surulere  935.000000  NaN    NaN        NaN  2000.000000       1.0  NaN
Gbagada   938.333333  NaN    NaN        NaN  3333.333333       4.0  NaN
Lekki     938.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Surulere  937.000000  NaN    NaN        NaN  4000.000000       3.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki     16000.000000  4004.000000
Surulere   2000.000000  2001.000000
Gbagada   13333.333333  3337.333333
Lekki     20000.000000  4005.000000
Surulere  12000.000000  4003.000000

[619 rows x 9 columns]
                 S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada     5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.0
Ibadan      1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.0
Ikoyi       3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.0
Lekki       3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.0
Gbagada     9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.0
...              ...  ...    ...        ...     ...       ...  ...      ...
Lekki     938.000000  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.0
Surulere  937.000000  NaN    NaN        NaN  4000.0  3.000000  NaN  12000.0
Ikoyi     943.333333  NaN    NaN        NaN  3000.0  2.333333  NaN   8000.0
Lekki     942.000000  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.0
Surulere  943.000000  NaN    NaN        NaN  4000.0  3.000000  NaN  12000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Lekki     4005.000000
Surulere  4003.000000
Ikoyi     3002.333333
Lekki     2005.000000
Surulere  4003.000000

[622 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     942.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Surulere  943.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Gbagada   947.5  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Lekki     946.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Surulere  949.5  NaN    NaN        NaN  2500.0       4.0  NaN   9500.0  2504.0

[625 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     946.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Surulere  949.5  NaN    NaN        NaN  2500.0       4.0  NaN   9500.0  2504.0
Gbagada   952.5  NaN    NaN        NaN  3500.0       3.5  NaN  13000.0  3503.5
Ibadan    952.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Lekki     954.0  NaN    NaN        NaN  3000.0       4.5  NaN  13000.0  3004.5

[628 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     954.0  NaN    NaN        NaN  3000.0       4.5  NaN  13000.0  3004.5
Ibadan    958.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Ikoyi     960.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0  3002.0
Lekki     956.5  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0  3001.0
Surulere  959.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0

[632 rows x 9 columns]
            S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada     5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0
Ibadan      1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ikoyi       3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN   5000.0
Lekki       3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Gbagada     9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
...         ...  ...    ...        ...          ...       ...  ...      ...
Ikoyi     960.0  NaN    NaN        NaN  3000.000000  2.000000  NaN   6000.0
Lekki     956.5  NaN    NaN        NaN  3000.000000  1.000000  NaN   3000.0
Surulere  959.0  NaN    NaN        NaN  4000.000000  4.000000  NaN  16000.0
Ibadan    963.0  NaN    NaN        NaN  4000.000000  3.000000  NaN  12000.0
Lekki     963.0  NaN    NaN        NaN  2666.666667  3.333333  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3002.0
Lekki     3001.0
Surulere  4004.0
Ibadan    4003.0
Lekki     2670.0

[634 rows x 9 columns]
           S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada    5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0
Ibadan     1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ikoyi      3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN   5000.0
Lekki      3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Gbagada    9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
...        ...  ...    ...        ...          ...       ...  ...      ...
Lekki    963.0  NaN    NaN        NaN  2666.666667  3.333333  NaN   8000.0
Gbagada  969.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ibadan   967.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
Ikoyi    970.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Lekki    967.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0

           Snap
Gbagada  2004.0
Ibadan   2005.0
Ikoyi    2002.5
Lekki    4005.0
Gbagada  2003.0
...         ...
Lekki    2670.0
Gbagada  2005.0
Ibadan   2003.0
Ikoyi    4005.0
Lekki    2003.0

[638 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki     967.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Gbagada   972.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi     975.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Lekki     971.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Surulere  973.5  NaN    NaN        NaN  3500.0       1.5  NaN   5000.0  3501.5

[642 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Gbagada   980.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan    977.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Ikoyi     979.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0  3001.0
Lekki     978.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Surulere  976.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0

[647 rows x 9 columns]

            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  976.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0
Ibadan    982.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi     982.5  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Lekki     985.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Surulere  983.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0

[651 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  983.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Ibadan    986.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Ikoyi     988.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0  3002.0
Lekki     987.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Surulere  989.5  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0

[655 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  989.5  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Gbagada   992.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Ibadan    995.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Lekki     992.5  NaN    NaN        NaN  4000.0       4.5  NaN  18000.0  4004.5
Surulere  993.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0

[659 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Surulere  993.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0
Ibadan    998.0  NaN    NaN        NaN  3500.0       5.0  NaN  17500.0  3505.0
Ikoyi     997.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Lekki     999.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0  3002.0
Surulere  998.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0

[663 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   1004.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan    1001.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ikoyi     1003.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     1002.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Surulere  1005.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   2004.0
Ibadan    3004.0
Ikoyi     4001.0
Lekki     3002.0
Surulere  4002.0

[668 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1002.0  NaN    NaN        NaN  3000.0  2.000000  NaN   6000.0
Surulere  1005.0  NaN    NaN        NaN  4000.0  2.000000  NaN   8000.0
Gbagada   1007.0  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.0
Ikoyi     1009.0  NaN    NaN        NaN  3000.0  1.333333  NaN   4000.0
Lekki     1006.0  NaN    NaN        NaN  4000.0  4.000000  NaN  16000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Lekki     3002.000000
Surulere  4002.000000
Gbagada   2003.000000
Ikoyi     3001.333333
Lekki     4004.000000

[671 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1006.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Gbagada   1015.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ikoyi     1013.5  NaN    NaN        NaN  3000.0       3.0  NaN  10000.0
Lekki     1011.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  1012.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4004.0
Gbagada   4004.0
Ikoyi     3003.0
Lekki     4005.0
Surulere  3003.0

[675 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1012.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Gbagada   1017.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ibadan    1018.5  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Ikoyi     1016.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  1020.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3003.0
Gbagada   3004.0
Ibadan    3003.0
Ikoyi     4005.0
Surulere  2003.0

[679 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1020.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Gbagada   1022.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Ibadan    1023.5  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Lekki     1021.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  1025.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2003.0
Gbagada   2002.0
Ibadan    2003.0
Lekki     4002.0
Surulere  2004.0

[683 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1025.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Gbagada   1029.0  NaN    NaN        NaN  3000.0       3.5  NaN  10000.0
Ibadan    1029.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ikoyi     1026.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     1027.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2004.0
Gbagada   3003.5
Ibadan    4005.0
Ikoyi     4001.0
Lekki     3003.0

[687 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   1031.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ibadan    1034.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Ikoyi     1035.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     1033.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Surulere  1032.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   2005.0
Ibadan    2002.0
Ikoyi     4003.0
Lekki     2004.0
Surulere  4005.0

[692 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...               ...  ...    ...        ...     ...       ...  ...
Ikoyi     1035.000000  NaN    NaN        NaN  4000.0  3.000000  NaN
Lekki     1033.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Surulere  1032.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada   1038.500000  NaN    NaN        NaN  3000.0  1.500000  NaN
Ibadan    1037.666667  NaN    NaN        NaN  3000.0  2.333333  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi     12000.000000  4003.000000
Lekki      8000.000000  2004.000000
Surulere  20000.000000  4005.000000
Gbagada    4000.000000  3001.500000
Ibadan     7333.333333  3002.333333

[694 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Surulere  1032.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada   1038.500000  NaN    NaN        NaN  3000.000000  1.500000  NaN
Ibadan    1037.666667  NaN    NaN        NaN  3000.000000  2.333333  NaN
Ikoyi     1043.500000  NaN    NaN        NaN  4000.000000  2.500000  NaN
Lekki     1042.666667  NaN    NaN        NaN  2666.666667  3.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Surulere  20000.000000  4005.000000
Gbagada    4000.000000  3001.500000
Ibadan     7333.333333  3002.333333
Ikoyi     10000.000000  4002.500000
Lekki      8666.666667  2669.666667

[696 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     1043.500000  NaN    NaN        NaN  4000.000000       2.5  NaN
Lekki     1042.666667  NaN    NaN        NaN  2666.666667       3.0  NaN
Ibadan    1050.000000  NaN    NaN        NaN  2000.000000       1.0  NaN
Lekki     1047.500000  NaN    NaN        NaN  4000.000000       1.0  NaN
Surulere  1047.500000  NaN    NaN        NaN  2500.000000       3.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi     10000.000000  4002.500000
Lekki      8666.666667  2669.666667
Ibadan     2000.000000  2001.000000
Lekki      4000.000000  4001.000000
Surulere   8500.000000  2503.000000

[699 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1047.5  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Surulere  1047.5  NaN    NaN        NaN  2500.0       3.0  NaN   8500.0
Gbagada   1054.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ibadan    1054.0  NaN    NaN        NaN  2500.0       4.0  NaN  10000.0
Lekki     1051.5  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4001.0
Surulere  2503.0
Gbagada   2001.0
Ibadan    2504.0
Lekki     4005.0

[702 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1051.5  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada   1056.5  NaN    NaN        NaN  3000.0       4.0  NaN  13000.0
Ibadan    1058.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Lekki     1060.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Surulere  1059.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4005.0
Gbagada   3004.0
Ibadan    4002.0
Lekki     2002.0
Surulere  4002.0

[706 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1059.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Gbagada   1063.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ibadan    1065.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ikoyi     1061.5  NaN    NaN        NaN  3000.0       2.0  NaN   7000.0
Surulere  1064.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4002.0
Gbagada   4002.0
Ibadan    4005.0
Ikoyi     3002.0
Surulere  4002.0

[710 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1061.5  NaN    NaN        NaN  3000.0       2.0  NaN   7000.0
Surulere  1064.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Gbagada   1068.0  NaN    NaN        NaN  3000.0       3.5  NaN  11000.0
Ikoyi     1069.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Surulere  1067.5  NaN    NaN        NaN  3000.0       2.0  NaN   7000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3002.0
Surulere  4002.0
Gbagada   3003.5
Ikoyi     4001.0
Surulere  3002.0

[713 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1067.5  NaN    NaN        NaN  3000.0       2.0  NaN   7000.0
Gbagada   1074.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ibadan    1071.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi     1073.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Lekki     1073.5  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3002.0
Gbagada   4003.0
Ibadan    2005.0
Ikoyi     3001.0
Lekki     4003.5

[717 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1073.5  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0
Gbagada   1078.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ibadan    1076.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ikoyi     1079.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Surulere  1078.5  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4003.5
Gbagada   4005.0
Ibadan    4004.0
Ikoyi     2003.0
Surulere  2003.0

[721 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1079.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Surulere  1078.5  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Gbagada   1084.5  NaN    NaN        NaN  3500.0       5.0  NaN  17500.0
Ibadan    1081.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ikoyi     1082.5  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     2003.0
Surulere  2003.0
Gbagada   3505.0
Ibadan    2003.0
Ikoyi     2003.0

[724 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    1081.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ikoyi     1082.5  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ibadan    1086.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Lekki     1089.0  NaN    NaN        NaN  3500.0       4.5  NaN  15500.0
Surulere  1088.0  NaN    NaN        NaN  3500.0       1.5  NaN   5500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    2003.0
Ikoyi     2003.0
Ibadan    2005.0
Lekki     3504.5
Surulere  3501.5

[727 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1088.0  NaN    NaN        NaN  3500.0       1.5  NaN   5500.0
Gbagada   1091.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ibadan    1095.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi     1093.5  NaN    NaN        NaN  3500.0       3.5  NaN  12000.0
Lekki     1092.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3501.5
Gbagada   4001.0
Ibadan    2005.0
Ikoyi     3503.5
Lekki     2002.0

[731 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1092.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Gbagada   1097.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ikoyi     1099.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Lekki     1098.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  1098.0  NaN    NaN        NaN  2500.0       2.0  NaN   5500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2002.0
Gbagada   2003.0
Ikoyi     3001.0
Lekki     4003.0
Surulere  2502.0

[735 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1098.0  NaN    NaN        NaN  2500.0       2.0  NaN   5500.0
Gbagada   1103.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ikoyi     1103.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     1102.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  1104.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2502.0
Gbagada   4003.0
Ikoyi     4003.0
Lekki     4003.0
Surulere  4003.0

[739 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     1103.000000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Lekki     1102.000000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Surulere  1104.000000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Ikoyi     1107.500000  NaN    NaN        NaN  3000.000000  2.500000  NaN
Surulere  1108.333333  NaN    NaN        NaN  3333.333333  4.333333  NaN

          Revenue         Snap
Gbagada    8000.0  2004.000000
Ibadan    10000.0  2005.000000
Ikoyi      5000.0  2002.500000
Lekki     20000.0  4005.000000
Gbagada    6000.0  2003.000000
...           ...          ...
Ikoyi     12000.0  4003.000000
Lekki     12000.0  4003.000000
Surulere  12000.0  4003.000000
Ikoyi      6000.0  3002.500000
Surulere  14000.0  3337.666667

[741 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     1107.500000  NaN    NaN        NaN  3000.000000  2.500000  NaN
Surulere  1108.333333  NaN    NaN        NaN  3333.333333  4.333333  NaN
Ibadan    1114.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Ikoyi     1113.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Surulere  1111.000000  NaN    NaN        NaN  2000.000000  1.000000  NaN

          Revenue         Snap
Gbagada    8000.0  2004.000000
Ibadan    10000.0  2005.000000
Ikoyi      5000.0  2002.500000
Lekki     20000.0  4005.000000
Gbagada    6000.0  2003.000000
...           ...          ...
Ikoyi      6000.0  3002.500000
Surulere  14000.0  3337.666667
Ibadan     6000.0  2003.000000
Ikoyi      8000.0  4002.000000
Surulere   2000.0  2001.000000

[744 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0      4.00  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0      5.00  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0      2.50  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0      5.00  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0      3.00  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    1114.0  NaN    NaN        NaN  2000.0      3.00  NaN   6000.0
Ikoyi     1113.0  NaN    NaN        NaN  4000.0      2.00  NaN   8000.0
Surulere  1111.0  NaN    NaN        NaN  2000.0      1.00  NaN   2000.0
Ibadan    1118.5  NaN    NaN        NaN  2750.0      1.75  NaN   4250.0
Ikoyi     1116.0  NaN    NaN        NaN  3000.0      2.00  NaN   6000.0

             Snap
Gbagada   2004.00
Ibadan    2005.00
Ikoyi     2002.50
Lekki     4005.00
Gbagada   2003.00
...           ...
Ibadan    2003.00
Ikoyi     4002.00
Surulere  2001.00
Ibadan    2751.75
Ikoyi     3002.00

[746 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time       Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.000000
Ibadan       1.0  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.000000
Ikoyi        3.0  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.000000
Lekki        3.0  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.000000
Gbagada      9.0  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.000000
...          ...  ...    ...        ...     ...       ...  ...           ...
Surulere  1111.0  NaN    NaN        NaN  2000.0  1.000000  NaN   2000.000000
Ibadan    1118.5  NaN    NaN        NaN  2750.0  1.750000  NaN   4250.000000
Ikoyi     1116.0  NaN    NaN        NaN  3000.0  2.000000  NaN   6000.000000
Gbagada   1121.5  NaN    NaN        NaN  3500.0  2.000000  NaN   7500.000000
Ikoyi     1124.0  NaN    NaN        NaN  2000.0  2.333333  NaN   4666.666667

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Surulere  2001.000000
Ibadan    2751.750000
Ikoyi     3002.000000
Gbagada   3502.000000
Ikoyi     2002.333333

[748 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time       Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.000000
Ibadan       1.0  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.000000
Ikoyi        3.0  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.000000
Lekki        3.0  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.000000
Gbagada      9.0  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.000000
...          ...  ...    ...        ...     ...       ...  ...           ...
Ikoyi     1124.0  NaN    NaN        NaN  2000.0  2.333333  NaN   4666.666667
Gbagada   1126.0  NaN    NaN        NaN  2000.0  1.000000  NaN   2000.000000
Ibadan    1129.0  NaN    NaN        NaN  4000.0  3.000000  NaN  12000.000000
Lekki     1128.5  NaN    NaN        NaN  3000.0  3.000000  NaN   9000.000000
Surulere  1128.0  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.000000

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Ikoyi     2002.333333
Gbagada   2001.000000
Ibadan    4003.000000
Lekki     3003.000000
Surulere  4005.000000

[752 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1128.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada   1131.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan    1132.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Lekki     1133.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Surulere  1134.5  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4005.0
Gbagada   2004.0
Ibadan    2003.0
Lekki     4001.0
Surulere  3003.0

[756 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0      4.00  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0      5.00  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0      2.50  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0      5.00  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0      3.00  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    1132.0  NaN    NaN        NaN  2000.0      3.00  NaN   6000.0
Lekki     1133.0  NaN    NaN        NaN  4000.0      1.00  NaN   4000.0
Surulere  1134.5  NaN    NaN        NaN  3000.0      3.00  NaN   9000.0
Ibadan    1137.5  NaN    NaN        NaN  2750.0      2.25  NaN   6500.0
Lekki     1140.0  NaN    NaN        NaN  3000.0      1.00  NaN   3000.0

             Snap
Gbagada   2004.00
Ibadan    2005.00
Ikoyi     2002.50
Lekki     4005.00
Gbagada   2003.00
...           ...
Ibadan    2003.00
Lekki     4001.00
Surulere  3003.00
Ibadan    2752.25
Lekki     3001.00

[758 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada     5.0  NaN    NaN        NaN  2000.0      4.00  NaN   8000.0
Ibadan      1.0  NaN    NaN        NaN  2000.0      5.00  NaN  10000.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0      2.50  NaN   5000.0
Lekki       3.0  NaN    NaN        NaN  4000.0      5.00  NaN  20000.0
Gbagada     9.0  NaN    NaN        NaN  2000.0      3.00  NaN   6000.0
...         ...  ...    ...        ...     ...       ...  ...      ...
Ibadan   1137.5  NaN    NaN        NaN  2750.0      2.25  NaN   6500.0
Lekki    1140.0  NaN    NaN        NaN  3000.0      1.00  NaN   3000.0
Gbagada  1142.5  NaN    NaN        NaN  3000.0      3.50  NaN  10000.0
Ibadan   1145.0  NaN    NaN        NaN  4000.0      2.00  NaN   8000.0
Lekki    1142.5  NaN    NaN        NaN  2500.0      2.50  NaN   5500.0

            Snap
Gbagada  2004.00
Ibadan   2005.00
Ikoyi    2002.50
Lekki    4005.00
Gbagada  2003.00
...          ...
Ibadan   2752.25
Lekki    3001.00
Gbagada  3003.50
Ibadan   4002.00
Lekki    2502.50

[761 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1142.5  NaN    NaN        NaN  2500.0       2.5  NaN   5500.0
Gbagada   1150.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ikoyi     1146.5  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Lekki     1148.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  1149.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2502.5
Gbagada   3001.0
Ikoyi     3002.0
Lekki     4002.0
Surulere  2004.0

[765 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time       Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.000000
Ibadan       1.0  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.000000
Ikoyi        3.0  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.000000
Lekki        3.0  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.000000
Gbagada      9.0  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.000000
...          ...  ...    ...        ...     ...       ...  ...           ...
Lekki     1148.0  NaN    NaN        NaN  4000.0  2.000000  NaN   8000.000000
Surulere  1149.0  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.000000
Ibadan    1153.0  NaN    NaN        NaN  3000.0  3.666667  NaN   9666.666667
Lekki     1152.0  NaN    NaN        NaN  4000.0  2.000000  NaN   8000.000000
Surulere  1154.0  NaN    NaN        NaN  4000.0  4.000000  NaN  16000.000000

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Lekki     4002.000000
Surulere  2004.000000
Ibadan    3003.666667
Lekki     4002.000000
Surulere  4004.000000

[768 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1152.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  1154.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Gbagada   1159.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ikoyi     1158.0  NaN    NaN        NaN  2500.0       2.5  NaN   5500.0
Lekki     1157.5  NaN    NaN        NaN  3000.0       2.5  NaN   7500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4002.0
Surulere  4004.0
Gbagada   4005.0
Ikoyi     2502.5
Lekki     3002.5

[771 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0       3.0  NaN
...               ...  ...    ...        ...     ...       ...  ...
Ikoyi     1158.000000  NaN    NaN        NaN  2500.0       2.5  NaN
Lekki     1157.500000  NaN    NaN        NaN  3000.0       2.5  NaN
Ikoyi     1163.000000  NaN    NaN        NaN  3000.0       2.0  NaN
Lekki     1162.333333  NaN    NaN        NaN  3000.0       3.0  NaN
Surulere  1165.000000  NaN    NaN        NaN  4000.0       4.0  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Ikoyi      5500.000000  2502.5
Lekki      7500.000000  3002.5
Ikoyi      6000.000000  3002.0
Lekki     10333.333333  3003.0
Surulere  16000.000000  4004.0

[774 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0       3.0  NaN
...               ...  ...    ...        ...     ...       ...  ...
Lekki     1162.333333  NaN    NaN        NaN  3000.0       3.0  NaN
Surulere  1165.000000  NaN    NaN        NaN  4000.0       4.0  NaN
Ikoyi     1168.000000  NaN    NaN        NaN  2500.0       1.5  NaN
Lekki     1170.000000  NaN    NaN        NaN  3000.0       5.0  NaN
Surulere  1167.000000  NaN    NaN        NaN  4000.0       4.0  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Lekki     10333.333333  3003.0
Surulere  16000.000000  4004.0
Ikoyi      3500.000000  2501.5
Lekki     15000.000000  3005.0
Surulere  16000.000000  4004.0

[777 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1170.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Surulere  1167.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Gbagada   1171.5  NaN    NaN        NaN  2500.0       3.0  NaN   8000.0
Ibadan    1175.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ikoyi     1173.5  NaN    NaN        NaN  2500.0       2.5  NaN   6500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3005.0
Surulere  4004.0
Gbagada   2503.0
Ibadan    4003.0
Ikoyi     2502.5

[780 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1173.5  NaN    NaN        NaN  2500.0       2.5  NaN   6500.0
Gbagada   1178.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Ibadan    1178.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ikoyi     1176.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Surulere  1180.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     2502.5
Gbagada   2002.0
Ibadan    2004.0
Ikoyi     2003.0
Surulere  4004.0

[784 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1180.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Gbagada   1181.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ibadan    1183.5  NaN    NaN        NaN  3000.0       2.5  NaN   8000.0
Ikoyi     1185.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Lekki     1182.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4004.0
Gbagada   2001.0
Ibadan    3002.5
Ikoyi     4005.0
Lekki     4005.0

[788 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time       Revenue  \
Gbagada     5.0  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.000000
Ibadan      1.0  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.000000
Ikoyi       3.0  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.000000
Lekki       3.0  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.000000
Gbagada     9.0  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.000000
...         ...  ...    ...        ...     ...       ...  ...           ...
Ikoyi    1185.0  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.000000
Lekki    1182.0  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.000000
Ibadan   1189.0  NaN    NaN        NaN  3000.0  2.000000  NaN   6000.000000
Ikoyi    1187.0  NaN    NaN        NaN  4000.0  3.666667  NaN  14666.666667
Lekki    1190.0  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.000000

                Snap
Gbagada  2004.000000
Ibadan   2005.000000
Ikoyi    2002.500000
Lekki    4005.000000
Gbagada  2003.000000
...              ...
Ikoyi    4005.000000
Lekki    4005.000000
Ibadan   3002.000000
Ikoyi    4003.666667
Lekki    2005.000000

[791 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time       Revenue  \
Gbagada     5.0  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.000000
Ibadan      1.0  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.000000
Ikoyi       3.0  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.000000
Lekki       3.0  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.000000
Gbagada     9.0  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.000000
...         ...  ...    ...        ...     ...       ...  ...           ...
Ikoyi    1187.0  NaN    NaN        NaN  4000.0  3.666667  NaN  14666.666667
Lekki    1190.0  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.000000
Gbagada  1192.5  NaN    NaN        NaN  2500.0  3.000000  NaN   8000.000000
Ikoyi    1193.0  NaN    NaN        NaN  3000.0  4.000000  NaN  12000.000000
Lekki    1193.5  NaN    NaN        NaN  4000.0  3.500000  NaN  14000.000000

                Snap
Gbagada  2004.000000
Ibadan   2005.000000
Ikoyi    2002.500000
Lekki    4005.000000
Gbagada  2003.000000
...              ...
Ikoyi    4003.666667
Lekki    2005.000000
Gbagada  2503.000000
Ikoyi    3004.000000
Lekki    4003.500000

[794 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi    1193.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0
Lekki    1193.5  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0  4003.5
Ibadan   1198.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0
Ikoyi    1198.0  NaN    NaN        NaN  2500.0       5.0  NaN  12500.0  2505.0
Lekki    1198.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0

[797 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1198.0  NaN    NaN        NaN  2500.0       5.0  NaN  12500.0
Lekki     1198.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Gbagada   1202.5  NaN    NaN        NaN  2500.0       4.0  NaN   9500.0
Lekki     1203.0  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0
Surulere  1204.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     2505.0
Lekki     4002.0
Gbagada   2504.0
Lekki     4003.5
Surulere  3005.0

[800 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1204.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Gbagada   1208.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ikoyi     1206.5  NaN    NaN        NaN  3500.0       3.5  NaN  12000.0
Lekki     1210.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Surulere  1209.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3005.0
Gbagada   2003.0
Ikoyi     3503.5
Lekki     3003.0
Surulere  4002.0

[804 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1209.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Gbagada   1214.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ikoyi     1213.5  NaN    NaN        NaN  3000.0       3.5  NaN  12000.0
Lekki     1213.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  1211.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4002.0
Gbagada   4003.0
Ikoyi     3003.5
Lekki     4005.0
Surulere  4005.0

[808 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...          ...  ...    ...        ...          ...       ...  ...
Lekki     1213.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Surulere  1211.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Ibadan    1218.0  NaN    NaN        NaN  3333.333333  2.333333  NaN
Ikoyi     1219.0  NaN    NaN        NaN  4000.000000  1.000000  NaN
Lekki     1217.0  NaN    NaN        NaN  4000.000000  2.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki     20000.000000  4005.000000
Surulere  20000.000000  4005.000000
Ibadan     7333.333333  3335.666667
Ikoyi      4000.000000  4001.000000
Lekki      8000.000000  4002.000000

[811 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1219.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     1217.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Gbagada   1223.5  NaN    NaN        NaN  2500.0       3.0  NaN   8500.0
Lekki     1224.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Surulere  1222.0  NaN    NaN        NaN  3500.0       2.0  NaN   7000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     4001.0
Lekki     4002.0
Gbagada   2503.0
Lekki     2001.0
Surulere  3502.0

[814 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1224.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Surulere  1222.0  NaN    NaN        NaN  3500.0       2.0  NaN   7000.0
Gbagada   1228.0  NaN    NaN        NaN  2500.0       3.5  NaN   8000.0
Ikoyi     1228.0  NaN    NaN        NaN  3500.0       2.5  NaN   8000.0
Lekki     1228.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2001.0
Surulere  3502.0
Gbagada   2503.5
Ikoyi     3502.5
Lekki     4001.0

[817 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1228.0  NaN    NaN        NaN  3500.0       2.5  NaN   8000.0
Lekki     1228.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ikoyi     1234.0  NaN    NaN        NaN  2000.0       1.5  NaN   3000.0
Lekki     1232.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Surulere  1232.5  NaN    NaN        NaN  2500.0       2.0  NaN   5000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3502.5
Lekki     4001.0
Ikoyi     2001.5
Lekki     3002.0
Surulere  2502.0

[820 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time       Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.000000
Ibadan       1.0  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.000000
Ikoyi        3.0  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.000000
Lekki        3.0  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.000000
Gbagada      9.0  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.000000
...          ...  ...    ...        ...     ...       ...  ...           ...
Lekki     1232.0  NaN    NaN        NaN  3000.0  2.000000  NaN   6000.000000
Surulere  1232.5  NaN    NaN        NaN  2500.0  2.000000  NaN   5000.000000
Gbagada   1239.0  NaN    NaN        NaN  3000.0  3.000000  NaN   9000.000000
Ibadan    1240.0  NaN    NaN        NaN  4000.0  3.000000  NaN  12000.000000
Lekki     1237.0  NaN    NaN        NaN  3000.0  3.333333  NaN   9333.333333

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Lekki     3002.000000
Surulere  2502.000000
Gbagada   3003.000000
Ibadan    4003.000000
Lekki     3003.333333

[823 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time       Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.000000
Ibadan       1.0  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.000000
Ikoyi        3.0  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.000000
Lekki        3.0  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.000000
Gbagada      9.0  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.000000
...          ...  ...    ...        ...     ...       ...  ...           ...
Ibadan    1240.0  NaN    NaN        NaN  4000.0  3.000000  NaN  12000.000000
Lekki     1237.0  NaN    NaN        NaN  3000.0  3.333333  NaN   9333.333333
Gbagada   1241.0  NaN    NaN        NaN  2000.0  1.000000  NaN   2000.000000
Lekki     1244.5  NaN    NaN        NaN  3500.0  4.500000  NaN  15500.000000
Surulere  1242.5  NaN    NaN        NaN  2000.0  2.000000  NaN   4000.000000

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Ibadan    4003.000000
Lekki     3003.333333
Gbagada   2001.000000
Lekki     3504.500000
Surulere  2002.000000

[826 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1242.5  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Gbagada   1250.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ibadan    1249.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ikoyi     1247.5  NaN    NaN        NaN  2500.0       5.0  NaN  12500.0
Surulere  1246.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2002.0
Gbagada   3004.0
Ibadan    4003.0
Ikoyi     2505.0
Surulere  3003.0

[830 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...               ...  ...    ...        ...     ...       ...  ...
Ikoyi     1247.500000  NaN    NaN        NaN  2500.0  5.000000  NaN
Surulere  1246.000000  NaN    NaN        NaN  3000.0  3.000000  NaN
Gbagada   1253.666667  NaN    NaN        NaN  3000.0  2.333333  NaN
Ibadan    1253.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Surulere  1251.000000  NaN    NaN        NaN  4000.0  3.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi     12500.000000  2505.000000
Surulere   9000.000000  3003.000000
Gbagada    7333.333333  3002.333333
Ibadan     8000.000000  2004.000000
Surulere  12000.000000  4003.000000

[833 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1251.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Gbagada   1257.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ikoyi     1259.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Lekki     1258.0  NaN    NaN        NaN  3500.0       3.0  NaN  10000.0
Surulere  1258.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4003.0
Gbagada   4004.0
Ikoyi     2001.0
Lekki     3503.0
Surulere  3002.0

[837 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1258.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Gbagada   1261.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ibadan    1262.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ikoyi     1264.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Lekki     1264.0  NaN    NaN        NaN  2500.0       2.0  NaN   5500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3002.0
Gbagada   3004.0
Ibadan    4004.0
Ikoyi     4002.0
Lekki     2502.0

[841 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki    1264.0  NaN    NaN        NaN  2500.0       2.0  NaN   5500.0  2502.0
Gbagada  1266.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Ibadan   1267.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ikoyi    1269.5  NaN    NaN        NaN  3000.0       2.5  NaN   8000.0  3002.5
Lekki    1268.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0

[845 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1268.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Gbagada   1275.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ikoyi     1271.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Lekki     1272.5  NaN    NaN        NaN  2500.0       2.5  NaN   6000.0
Surulere  1274.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2003.0
Gbagada   2004.0
Ikoyi     4004.0
Lekki     2502.5
Surulere  3003.0

[849 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1272.5  NaN    NaN        NaN  2500.0       2.5  NaN   6000.0
Surulere  1274.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Gbagada   1276.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Lekki     1278.5  NaN    NaN        NaN  3500.0       4.0  NaN  14000.0
Surulere  1278.5  NaN    NaN        NaN  3000.0       1.5  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2502.5
Surulere  3003.0
Gbagada   2004.0
Lekki     3504.0
Surulere  3001.5

[852 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1278.5  NaN    NaN        NaN  3000.0       1.5  NaN   4000.0
Gbagada   1282.5  NaN    NaN        NaN  3500.0       1.5  NaN   5500.0
Ibadan    1282.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Lekki     1283.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Surulere  1285.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3001.5
Gbagada   3501.5
Ibadan    4004.0
Lekki     4001.0
Surulere  3001.0

[856 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
...          ...  ...    ...        ...          ...       ...  ...      ...
Lekki     1283.0  NaN    NaN        NaN  4000.000000  1.000000  NaN   4000.0
Surulere  1285.0  NaN    NaN        NaN  3000.000000  1.000000  NaN   3000.0
Gbagada   1287.0  NaN    NaN        NaN  2333.333333  1.666667  NaN   4000.0
Ikoyi     1290.0  NaN    NaN        NaN  3000.000000  4.000000  NaN  12000.0
Lekki     1289.0  NaN    NaN        NaN  4000.000000  3.000000  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4001.0
Surulere  3001.0
Gbagada   2335.0
Ikoyi     3004.0
Lekki     4003.0

[859 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1289.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Gbagada   1292.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ibadan    1293.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ikoyi     1292.5  NaN    NaN        NaN  3500.0       2.5  NaN   9500.0
Surulere  1295.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4003.0
Gbagada   3002.0
Ibadan    4001.0
Ikoyi     3502.5
Surulere  2004.0

[863 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1292.5  NaN    NaN        NaN  3500.0       2.5  NaN   9500.0
Surulere  1295.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Gbagada   1297.5  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     1298.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Surulere  1299.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3502.5
Surulere  2004.0
Gbagada   4003.0
Lekki     3001.0
Surulere  3003.0

[866 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1298.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Surulere  1299.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Gbagada   1303.5  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Ikoyi     1302.5  NaN    NaN        NaN  3000.0       3.5  NaN  12000.0
Lekki     1303.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3001.0
Surulere  3003.0
Gbagada   3003.0
Ikoyi     3003.5
Lekki     2005.0

[869 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...               ...  ...    ...        ...     ...       ...  ...
Gbagada   1303.500000  NaN    NaN        NaN  3000.0  3.000000  NaN
Ikoyi     1302.500000  NaN    NaN        NaN  3000.0  3.500000  NaN
Lekki     1303.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Lekki     1308.500000  NaN    NaN        NaN  4000.0  1.500000  NaN
Surulere  1307.666667  NaN    NaN        NaN  3000.0  1.666667  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Gbagada    9000.000000  3003.000000
Ikoyi     12000.000000  3003.500000
Lekki     10000.000000  2005.000000
Lekki      6000.000000  4001.500000
Surulere   5333.333333  3001.666667

[871 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     1308.500000  NaN    NaN        NaN  4000.000000  1.500000  NaN
Surulere  1307.666667  NaN    NaN        NaN  3000.000000  1.666667  NaN
Gbagada   1313.000000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Ikoyi     1312.000000  NaN    NaN        NaN  2000.000000  2.000000  NaN
Surulere  1313.333333  NaN    NaN        NaN  3333.333333  1.333333  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      6000.000000  4001.500000
Surulere   5333.333333  3001.666667
Gbagada   12000.000000  4003.000000
Ikoyi      4000.000000  2002.000000
Surulere   4000.000000  3334.666667

[874 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     1312.000000  NaN    NaN        NaN  2000.000000  2.000000  NaN
Surulere  1313.333333  NaN    NaN        NaN  3333.333333  1.333333  NaN
Ibadan    1318.500000  NaN    NaN        NaN  2500.000000  2.000000  NaN
Ikoyi     1318.500000  NaN    NaN        NaN  3500.000000  1.500000  NaN
Surulere  1316.000000  NaN    NaN        NaN  3000.000000  3.000000  NaN

          Revenue         Snap
Gbagada    8000.0  2004.000000
Ibadan    10000.0  2005.000000
Ikoyi      5000.0  2002.500000
Lekki     20000.0  4005.000000
Gbagada    6000.0  2003.000000
...           ...          ...
Ikoyi      4000.0  2002.000000
Surulere   4000.0  3334.666667
Ibadan     5500.0  2502.000000
Ikoyi      5500.0  3501.500000
Surulere   9000.0  3003.000000

[877 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1318.5  NaN    NaN        NaN  3500.0       1.5  NaN   5500.0
Surulere  1316.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Gbagada   1323.5  NaN    NaN        NaN  3000.0       4.0  NaN  13000.0
Lekki     1321.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Surulere  1323.5  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3501.5
Surulere  3003.0
Gbagada   3004.0
Lekki     2003.0
Surulere  2005.0

[880 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...               ...  ...    ...        ...          ...       ...  ...
Gbagada   1323.500000  NaN    NaN        NaN  3000.000000       4.0  NaN
Lekki     1321.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
Surulere  1323.500000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ibadan    1327.500000  NaN    NaN        NaN  3500.000000       3.0  NaN
Lekki     1328.333333  NaN    NaN        NaN  3666.666667       3.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Gbagada   13000.000000  3004.000000
Lekki      6000.000000  2003.000000
Surulere  10000.000000  2005.000000
Ibadan    11500.000000  3503.000000
Lekki     11333.333333  3669.666667

[882 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     1328.333333  NaN    NaN        NaN  3666.666667       3.0  NaN
Gbagada   1333.000000  NaN    NaN        NaN  3500.000000       4.0  NaN
Ibadan    1333.000000  NaN    NaN        NaN  4000.000000       2.0  NaN
Lekki     1334.000000  NaN    NaN        NaN  3000.000000       1.0  NaN
Surulere  1332.000000  NaN    NaN        NaN  4000.000000       4.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki     11333.333333  3669.666667
Gbagada   13500.000000  3504.000000
Ibadan     8000.000000  4002.000000
Lekki      3000.000000  3001.000000
Surulere  16000.000000  4004.000000

[886 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     1334.000000  NaN    NaN        NaN  3000.000000  1.000000  NaN
Surulere  1332.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN
Gbagada   1337.666667  NaN    NaN        NaN  3666.666667  4.666667  NaN
Ibadan    1340.000000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Surulere  1337.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN

          Revenue         Snap
Gbagada    8000.0  2004.000000
Ibadan    10000.0  2005.000000
Ikoyi      5000.0  2002.500000
Lekki     20000.0  4005.000000
Gbagada    6000.0  2003.000000
...           ...          ...
Lekki      3000.0  3001.000000
Surulere  16000.0  4004.000000
Gbagada   17000.0  3671.333333
Ibadan    12000.0  4003.000000
Surulere   8000.0  2004.000000

[889 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1337.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan    1345.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ikoyi     1341.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     1343.5  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  1342.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2004.0
Ibadan    2004.0
Ikoyi     4003.0
Lekki     4005.0
Surulere  3005.0

[893 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0      4.00  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0      5.00  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0      2.50  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0      5.00  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0      3.00  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1341.0  NaN    NaN        NaN  4000.0      3.00  NaN  12000.0
Lekki     1343.5  NaN    NaN        NaN  4000.0      5.00  NaN  20000.0
Surulere  1342.0  NaN    NaN        NaN  3000.0      5.00  NaN  15000.0
Gbagada   1348.0  NaN    NaN        NaN  3250.0      2.25  NaN   7750.0
Surulere  1348.0  NaN    NaN        NaN  4000.0      5.00  NaN  20000.0

             Snap
Gbagada   2004.00
Ibadan    2005.00
Ikoyi     2002.50
Lekki     4005.00
Gbagada   2003.00
...           ...
Ikoyi     4003.00
Lekki     4005.00
Surulere  3005.00
Gbagada   3252.25
Surulere  4005.00

[895 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1348.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada   1354.5  NaN    NaN        NaN  3000.0       3.0  NaN   8000.0
Ibadan    1352.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Lekki     1353.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  1351.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4005.0
Gbagada   3003.0
Ibadan    4005.0
Lekki     4005.0
Surulere  3001.0

[899 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   1360.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ibadan    1359.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ikoyi     1357.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Lekki     1356.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Surulere  1358.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   3002.0
Ibadan    2004.0
Ikoyi     2001.0
Lekki     2005.0
Surulere  4003.0

[904 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1356.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Surulere  1358.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Gbagada   1364.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ibadan    1362.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Surulere  1363.5  NaN    NaN        NaN  3000.0       4.5  NaN  14000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2005.0
Surulere  4003.0
Gbagada   4001.0
Ibadan    3004.0
Surulere  3004.5

[907 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1363.5  NaN    NaN        NaN  3000.0       4.5  NaN  14000.0
Gbagada   1367.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ibadan    1366.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ikoyi     1370.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Surulere  1368.5  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3004.5
Gbagada   2003.0
Ibadan    4002.0
Ikoyi     3003.0
Surulere  2002.0

[911 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1368.5  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Gbagada   1374.0  NaN    NaN        NaN  3500.0       2.5  NaN   8500.0
Ibadan    1374.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ikoyi     1372.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     1371.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2002.0
Gbagada   3502.5
Ibadan    2003.0
Ikoyi     4001.0
Lekki     3003.0

[915 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1372.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     1371.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Ikoyi     1380.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     1378.5  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  1376.5  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     4001.0
Lekki     3003.0
Ikoyi     4001.0
Lekki     4003.0
Surulere  2002.0

[918 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000       3.0  NaN
...          ...  ...    ...        ...          ...       ...  ...
Lekki     1378.5  NaN    NaN        NaN  4000.000000       3.0  NaN
Surulere  1376.5  NaN    NaN        NaN  2000.000000       2.0  NaN
Ibadan    1382.0  NaN    NaN        NaN  4000.000000       3.0  NaN
Ikoyi     1381.0  NaN    NaN        NaN  2000.000000       4.0  NaN
Surulere  1384.0  NaN    NaN        NaN  2666.666667       2.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki     12000.000000  4003.000000
Surulere   4000.000000  2002.000000
Ibadan    12000.000000  4003.000000
Ikoyi      8000.000000  2004.000000
Surulere   5333.333333  2668.666667

[921 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...          ...  ...    ...        ...          ...       ...  ...
Ikoyi     1381.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Surulere  1384.0  NaN    NaN        NaN  2666.666667  2.000000  NaN
Ibadan    1390.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Lekki     1387.0  NaN    NaN        NaN  2333.333333  2.333333  NaN
Surulere  1389.0  NaN    NaN        NaN  4000.000000  1.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi      8000.000000  2004.000000
Surulere   5333.333333  2668.666667
Ibadan    20000.000000  4005.000000
Lekki      5000.000000  2335.666667
Surulere   4000.000000  4001.000000

[924 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     1387.000000  NaN    NaN        NaN  2333.333333  2.333333  NaN
Surulere  1389.000000  NaN    NaN        NaN  4000.000000  1.000000  NaN
Gbagada   1393.000000  NaN    NaN        NaN  3000.000000  3.000000  NaN
Ibadan    1392.666667  NaN    NaN        NaN  3666.666667  2.333333  NaN
Ikoyi     1394.000000  NaN    NaN        NaN  3000.000000  4.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      5000.000000  2335.666667
Surulere   4000.000000  4001.000000
Gbagada    9000.000000  3003.000000
Ibadan     8333.333333  3669.000000
Ikoyi     12000.000000  3004.000000

[927 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1394.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Gbagada   1399.5  NaN    NaN        NaN  2500.0       1.5  NaN   4000.0
Ibadan    1396.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Lekki     1398.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Surulere  1397.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3004.0
Gbagada   2501.5
Ibadan    3003.0
Lekki     2001.0
Surulere  2002.0

[931 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1398.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Surulere  1397.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Gbagada   1401.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ibadan    1405.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ikoyi     1403.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2001.0
Surulere  2002.0
Gbagada   4002.0
Ibadan    4005.0
Ikoyi     4003.0

[934 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    1405.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ikoyi     1403.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Gbagada   1409.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ikoyi     1408.0  NaN    NaN        NaN  3000.0       3.0  NaN   8000.0
Surulere  1407.5  NaN    NaN        NaN  2500.0       4.5  NaN  11000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    4005.0
Ikoyi     4003.0
Gbagada   3002.0
Ikoyi     3003.0
Surulere  2504.5

[937 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   1413.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ibadan    1411.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Ikoyi     1415.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     1414.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Surulere  1412.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   4005.0
Ibadan    3003.0
Ikoyi     4003.0
Lekki     3004.0
Surulere  2003.0

[942 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1412.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ibadan    1418.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ikoyi     1417.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Lekki     1419.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Surulere  1418.0  NaN    NaN        NaN  3500.0       3.0  NaN  10500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2003.0
Ibadan    2001.0
Ikoyi     4005.0
Lekki     2002.0
Surulere  3503.0

[946 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000       3.0  NaN
...          ...  ...    ...        ...          ...       ...  ...
Lekki     1419.0  NaN    NaN        NaN  2000.000000       2.0  NaN
Surulere  1418.0  NaN    NaN        NaN  3500.000000       3.0  NaN
Gbagada   1424.0  NaN    NaN        NaN  3666.666667       2.0  NaN
Ibadan    1421.0  NaN    NaN        NaN  3000.000000       5.0  NaN
Lekki     1422.0  NaN    NaN        NaN  3000.000000       4.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      4000.000000  2002.000000
Surulere  10500.000000  3503.000000
Gbagada    7666.666667  3668.666667
Ibadan    15000.000000  3005.000000
Lekki     12000.000000  3004.000000

[949 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki    1422.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0
Gbagada  1428.5  NaN    NaN        NaN  3000.0       2.5  NaN   7000.0  3002.5
Ibadan   1426.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Ikoyi    1429.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0  3002.0
Lekki    1428.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0

[953 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ibadan    1426.000000  NaN    NaN        NaN  3000.000000       3.0  NaN
Ikoyi     1429.000000  NaN    NaN        NaN  3000.000000       2.0  NaN
Lekki     1428.000000  NaN    NaN        NaN  4000.000000       4.0  NaN
Ikoyi     1433.500000  NaN    NaN        NaN  3500.000000       4.0  NaN
Surulere  1432.666667  NaN    NaN        NaN  3333.333333       3.0  NaN

          Revenue         Snap
Gbagada    8000.0  2004.000000
Ibadan    10000.0  2005.000000
Ikoyi      5000.0  2002.500000
Lekki     20000.0  4005.000000
Gbagada    6000.0  2003.000000
...           ...          ...
Ibadan     9000.0  3003.000000
Ikoyi      6000.0  3002.000000
Lekki     16000.0  4004.000000
Ikoyi     13500.0  3504.000000
Surulere  10000.0  3336.333333

[955 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...               ...  ...    ...        ...          ...       ...  ...
Surulere  1432.666667  NaN    NaN        NaN  3333.333333       3.0  NaN
Gbagada   1436.500000  NaN    NaN        NaN  3000.000000       3.5  NaN
Ibadan    1439.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Lekki     1440.000000  NaN    NaN        NaN  4000.000000       2.0  NaN
Surulere  1438.000000  NaN    NaN        NaN  2000.000000       5.0  NaN

          Revenue         Snap
Gbagada    8000.0  2004.000000
Ibadan    10000.0  2005.000000
Ikoyi      5000.0  2002.500000
Lekki     20000.0  4005.000000
Gbagada    6000.0  2003.000000
...           ...          ...
Surulere  10000.0  3336.333333
Gbagada   11000.0  3003.500000
Ibadan    10000.0  2005.000000
Lekki      8000.0  4002.000000
Surulere  10000.0  2005.000000

[959 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1440.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  1438.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ibadan    1443.5  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Ikoyi     1441.5  NaN    NaN        NaN  3000.0       3.5  NaN   9000.0
Surulere  1445.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4002.0
Surulere  2005.0
Ibadan    3003.0
Ikoyi     3003.5
Surulere  3004.0

[962 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ibadan    1443.500000  NaN    NaN        NaN  3000.000000  3.000000  NaN
Ikoyi     1441.500000  NaN    NaN        NaN  3000.000000  3.500000  NaN
Surulere  1445.000000  NaN    NaN        NaN  3000.000000  4.000000  NaN
Ibadan    1447.500000  NaN    NaN        NaN  2500.000000  4.500000  NaN
Ikoyi     1448.333333  NaN    NaN        NaN  3333.333333  4.333333  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ibadan     9000.000000  3003.000000
Ikoyi      9000.000000  3003.500000
Surulere  12000.000000  3004.000000
Ibadan    11000.000000  2504.500000
Ikoyi     15333.333333  3337.666667

[964 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     1448.333333  NaN    NaN        NaN  3333.333333  4.333333  NaN
Gbagada   1452.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Ikoyi     1453.000000  NaN    NaN        NaN  3000.000000  3.000000  NaN
Lekki     1453.000000  NaN    NaN        NaN  3000.000000  5.000000  NaN
Surulere  1454.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi     15333.333333  3337.666667
Gbagada    8000.000000  4002.000000
Ikoyi      9000.000000  3003.000000
Lekki     15000.000000  3005.000000
Surulere   8000.000000  4002.000000

[968 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1453.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Surulere  1454.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ibadan    1456.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Lekki     1457.5  NaN    NaN        NaN  3500.0       3.5  NaN  12000.0
Surulere  1459.5  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3005.0
Surulere  4002.0
Ibadan    4004.0
Lekki     3503.5
Surulere  2002.0

[971 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    1456.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Lekki     1457.5  NaN    NaN        NaN  3500.0       3.5  NaN  12000.0
Surulere  1459.5  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Lekki     1461.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Surulere  1463.5  NaN    NaN        NaN  3000.0       3.5  NaN  11500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    4004.0
Lekki     3503.5
Surulere  2002.0
Lekki     3001.0
Surulere  3003.5

[973 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1461.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Surulere  1463.5  NaN    NaN        NaN  3000.0       3.5  NaN  11500.0
Gbagada   1468.5  NaN    NaN        NaN  4000.0       2.5  NaN  10000.0
Lekki     1468.5  NaN    NaN        NaN  4000.0       4.5  NaN  18000.0
Surulere  1466.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3001.0
Surulere  3003.5
Gbagada   4002.5
Lekki     4004.5
Surulere  2001.0

[976 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1468.5  NaN    NaN        NaN  4000.0       4.5  NaN  18000.0
Surulere  1466.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ibadan    1473.5  NaN    NaN        NaN  3500.0       2.0  NaN   6500.0
Lekki     1471.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  1473.5  NaN    NaN        NaN  2000.0       3.5  NaN   7000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4004.5
Surulere  2001.0
Ibadan    3502.0
Lekki     4005.0
Surulere  2003.5

[979 rows x 9 columns]
              S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.00  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.00  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.00  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.00  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.00  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...           ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    1473.50  NaN    NaN        NaN  3500.0       2.0  NaN   6500.0
Lekki     1471.00  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  1473.50  NaN    NaN        NaN  2000.0       3.5  NaN   7000.0
Gbagada   1479.00  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Ikoyi     1477.75  NaN    NaN        NaN  3250.0       3.5  NaN  11500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    3502.0
Lekki     4005.0
Surulere  2003.5
Gbagada   2002.0
Ikoyi     3253.5

[981 rows x 9 columns]

              S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.00  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.00  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.00  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.00  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.00  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...           ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1477.75  NaN    NaN        NaN  3250.0       3.5  NaN  11500.0
Gbagada   1483.00  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Ibadan    1484.00  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Lekki     1481.50  NaN    NaN        NaN  2500.0       3.0  NaN   8500.0
Surulere  1485.00  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3253.5
Gbagada   3003.0
Ibadan    2004.0
Lekki     2503.0
Surulere  2003.0

[985 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1481.5  NaN    NaN        NaN  2500.0       3.0  NaN   8500.0
Surulere  1485.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Gbagada   1489.5  NaN    NaN        NaN  2500.0       1.0  NaN   2500.0
Ibadan    1486.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Surulere  1487.5  NaN    NaN        NaN  3000.0       3.5  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2503.0
Surulere  2003.0
Gbagada   2501.0
Ibadan    4001.0
Surulere  3003.5

[988 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ibadan    1486.000000  NaN    NaN        NaN  4000.000000  1.000000  NaN
Surulere  1487.500000  NaN    NaN        NaN  3000.000000  3.500000  NaN
Ikoyi     1493.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Lekki     1493.666667  NaN    NaN        NaN  3333.333333  2.666667  NaN
Surulere  1491.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN

          Revenue    Snap
Gbagada    8000.0  2004.0
Ibadan    10000.0  2005.0
Ikoyi      5000.0  2002.5
Lekki     20000.0  4005.0
Gbagada    6000.0  2003.0
...           ...     ...
Ibadan     4000.0  4001.0
Surulere  10000.0  3003.5
Ikoyi      8000.0  4002.0
Lekki      8000.0  3336.0
Surulere  16000.0  4004.0

[991 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1491.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Gbagada   1498.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ibadan    1498.0  NaN    NaN        NaN  3000.0       3.0  NaN   8000.0
Ikoyi     1496.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     1500.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4004.0
Gbagada   4002.0
Ibadan    3003.0
Ikoyi     4001.0
Lekki     4003.0

[995 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1500.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Gbagada   1501.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ibadan    1505.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     1503.5  NaN    NaN        NaN  3000.0       3.0  NaN  10000.0
Surulere  1502.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4003.0
Gbagada   2001.0
Ibadan    4001.0
Lekki     3003.0
Surulere  2001.0

[999 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1502.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ibadan    1508.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ikoyi     1506.5  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0
Lekki     1509.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  1510.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2001.0
Ibadan    4003.0
Ikoyi     4003.5
Lekki     4002.0
Surulere  2003.0

[1003 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     1506.500000  NaN    NaN        NaN  4000.000000  3.500000  NaN
Lekki     1509.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Surulere  1510.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Gbagada   1512.000000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Lekki     1513.666667  NaN    NaN        NaN  3666.666667  3.666667  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi     14000.000000  4003.500000
Lekki      8000.000000  4002.000000
Surulere   6000.000000  2003.000000
Gbagada   12000.000000  4003.000000
Lekki     13333.333333  3670.333333

[1005 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     1513.666667  NaN    NaN        NaN  3666.666667  3.666667  NaN
Ibadan    1516.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Ikoyi     1518.500000  NaN    NaN        NaN  2500.000000  1.000000  NaN
Lekki     1518.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Surulere  1519.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki     13333.333333  3670.333333
Ibadan    20000.000000  4005.000000
Ikoyi      2500.000000  2501.000000
Lekki      8000.000000  4002.000000
Surulere   8000.000000  2004.000000

[1009 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     1518.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Surulere  1519.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Gbagada   1522.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Lekki     1523.000000  NaN    NaN        NaN  3000.000000  3.000000  NaN
Surulere  1523.333333  NaN    NaN        NaN  3333.333333  3.333333  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      8000.000000  4002.000000
Surulere   8000.000000  2004.000000
Gbagada   10000.000000  2005.000000
Lekki      9000.000000  3003.000000
Surulere  10666.666667  3336.666667

[1012 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     1523.000000  NaN    NaN        NaN  3000.000000  3.000000  NaN
Surulere  1523.333333  NaN    NaN        NaN  3333.333333  3.333333  NaN
Gbagada   1528.000000  NaN    NaN        NaN  3500.000000  2.500000  NaN
Lekki     1528.000000  NaN    NaN        NaN  3000.000000  4.000000  NaN
Surulere  1528.000000  NaN    NaN        NaN  3500.000000  5.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      9000.000000  3003.000000
Surulere  10666.666667  3336.666667
Gbagada    8500.000000  3502.500000
Lekki     12000.000000  3004.000000
Surulere  17500.000000  3505.000000

[1015 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
...          ...  ...    ...        ...          ...       ...  ...      ...
Lekki     1528.0  NaN    NaN        NaN  3000.000000  4.000000  NaN  12000.0
Surulere  1528.0  NaN    NaN        NaN  3500.000000  5.000000  NaN  17500.0
Gbagada   1533.0  NaN    NaN        NaN  2333.333333  2.666667  NaN   6000.0
Ibadan    1535.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
Ikoyi     1531.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3004.0
Surulere  3505.0
Gbagada   2336.0
Ibadan    2003.0
Ikoyi     2005.0

[1018 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1531.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Gbagada   1540.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ibadan    1537.0  NaN    NaN        NaN  3500.0       3.0  NaN  10000.0
Ikoyi     1537.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Surulere  1539.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     2005.0
Gbagada   4005.0
Ibadan    3503.0
Ikoyi     4001.0
Surulere  3002.0

[1022 rows x 9 columns]
              S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.00  NaN    NaN        NaN  2000.0      4.00  NaN   8000.0
Ibadan       1.00  NaN    NaN        NaN  2000.0      5.00  NaN  10000.0
Ikoyi        3.00  NaN    NaN        NaN  2000.0      2.50  NaN   5000.0
Lekki        3.00  NaN    NaN        NaN  4000.0      5.00  NaN  20000.0
Gbagada      9.00  NaN    NaN        NaN  2000.0      3.00  NaN   6000.0
...           ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    1537.00  NaN    NaN        NaN  3500.0      3.00  NaN  10000.0
Ikoyi     1537.00  NaN    NaN        NaN  4000.0      1.00  NaN   4000.0
Surulere  1539.00  NaN    NaN        NaN  3000.0      2.00  NaN   6000.0
Ikoyi     1542.00  NaN    NaN        NaN  4000.0      1.00  NaN   4000.0
Lekki     1543.25  NaN    NaN        NaN  4000.0      3.25  NaN  13000.0

             Snap
Gbagada   2004.00
Ibadan    2005.00
Ikoyi     2002.50
Lekki     4005.00
Gbagada   2003.00
...           ...
Ibadan    3503.00
Ikoyi     4001.00
Surulere  3002.00
Ikoyi     4001.00
Lekki     4003.25

[1024 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada     5.00  NaN    NaN        NaN  2000.0      4.00  NaN   8000.0
Ibadan      1.00  NaN    NaN        NaN  2000.0      5.00  NaN  10000.0
Ikoyi       3.00  NaN    NaN        NaN  2000.0      2.50  NaN   5000.0
Lekki       3.00  NaN    NaN        NaN  4000.0      5.00  NaN  20000.0
Gbagada     9.00  NaN    NaN        NaN  2000.0      3.00  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki    1543.25  NaN    NaN        NaN  4000.0      3.25  NaN  13000.0
Gbagada  1550.00  NaN    NaN        NaN  4000.0      3.00  NaN  12000.0
Ibadan   1548.00  NaN    NaN        NaN  3000.0      3.00  NaN   7000.0
Ikoyi    1548.00  NaN    NaN        NaN  3000.0      3.00  NaN   9000.0
Lekki    1546.00  NaN    NaN        NaN  2000.0      2.00  NaN   4000.0

            Snap
Gbagada  2004.00
Ibadan   2005.00
Ikoyi    2002.50
Lekki    4005.00
Gbagada  2003.00
...          ...
Lekki    4003.25
Gbagada  4003.00
Ibadan   3003.00
Ikoyi    3003.00
Lekki    2002.00

[1028 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1548.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Lekki     1546.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Gbagada   1553.0  NaN    NaN        NaN  3500.0       1.5  NaN   5000.0
Ikoyi     1553.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Surulere  1553.0  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3003.0
Lekki     2002.0
Gbagada   3501.5
Ikoyi     4001.0
Surulere  4003.5

[1031 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1553.0  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0
Gbagada   1556.5  NaN    NaN        NaN  3000.0       1.5  NaN   4500.0
Ibadan    1559.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ikoyi     1558.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Lekki     1560.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4003.5
Gbagada   3001.5
Ibadan    3005.0
Ikoyi     3003.0
Lekki     4003.0

[1035 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1558.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Lekki     1560.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Gbagada   1561.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ibadan    1563.5  NaN    NaN        NaN  3500.0       2.5  NaN   8000.0
Surulere  1563.5  NaN    NaN        NaN  2000.0       3.5  NaN   7000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3003.0
Lekki     4003.0
Gbagada   3005.0
Ibadan    3502.5
Surulere  2003.5

[1038 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time       Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.000000
Ibadan       1.0  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.000000
Ikoyi        3.0  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.000000
Lekki        3.0  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.000000
Gbagada      9.0  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.000000
...          ...  ...    ...        ...     ...       ...  ...           ...
Ibadan    1563.5  NaN    NaN        NaN  3500.0  2.500000  NaN   8000.000000
Surulere  1563.5  NaN    NaN        NaN  2000.0  3.500000  NaN   7000.000000
Gbagada   1569.0  NaN    NaN        NaN  4000.0  1.000000  NaN   4000.000000
Ikoyi     1567.0  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.000000
Surulere  1568.0  NaN    NaN        NaN  3000.0  3.333333  NaN   9666.666667

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Ibadan    3502.500000
Surulere  2003.500000
Gbagada   4001.000000
Ikoyi     4005.000000
Surulere  3003.333333

[1041 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     1567.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Surulere  1568.000000  NaN    NaN        NaN  3000.000000  3.333333  NaN
Gbagada   1573.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Ibadan    1572.333333  NaN    NaN        NaN  3333.333333  3.666667  NaN
Ikoyi     1575.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi     20000.000000  4005.000000
Surulere   9666.666667  3003.333333
Gbagada    6000.000000  2003.000000
Ibadan    12000.000000  3337.000000
Ikoyi      8000.000000  4002.000000

[1044 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1575.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Gbagada   1579.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ikoyi     1577.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     1579.0  NaN    NaN        NaN  3000.0       3.5  NaN   9000.0
Surulere  1576.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     4002.0
Gbagada   2001.0
Ikoyi     4003.0
Lekki     3003.5
Surulere  3002.0

[1048 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1579.0  NaN    NaN        NaN  3000.0       3.5  NaN   9000.0
Surulere  1576.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Gbagada   1583.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Lekki     1581.5  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  1584.5  NaN    NaN        NaN  3000.0       2.0  NaN   5000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3003.5
Surulere  3002.0
Gbagada   4002.0
Lekki     4002.0
Surulere  3002.0

[1051 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1581.5  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  1584.5  NaN    NaN        NaN  3000.0       2.0  NaN   5000.0
Ibadan    1587.5  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ikoyi     1587.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Lekki     1589.0  NaN    NaN        NaN  2500.0       2.5  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4002.0
Surulere  3002.0
Ibadan    4004.0
Ikoyi     2001.0
Lekki     2502.5

[1054 rows x 9 columns]
                 S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.0       4.0  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.0       5.0  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.0       2.5  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.0       5.0  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.0       3.0  NaN
...              ...  ...    ...        ...     ...       ...  ...
Ikoyi    1587.000000  NaN    NaN        NaN  2000.0       1.0  NaN
Lekki    1589.000000  NaN    NaN        NaN  2500.0       2.5  NaN
Gbagada  1593.000000  NaN    NaN        NaN  4000.0       2.0  NaN
Ibadan   1592.333333  NaN    NaN        NaN  3000.0       4.0  NaN
Ikoyi    1595.000000  NaN    NaN        NaN  4000.0       2.0  NaN

              Revenue    Snap
Gbagada   8000.000000  2004.0
Ibadan   10000.000000  2005.0
Ikoyi     5000.000000  2002.5
Lekki    20000.000000  4005.0
Gbagada   6000.000000  2003.0
...               ...     ...
Ikoyi     2000.000000  2001.0
Lekki     6000.000000  2502.5
Gbagada   8000.000000  4002.0
Ibadan   11666.666667  3004.0
Ikoyi     8000.000000  4002.0

[1057 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1595.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Gbagada   1599.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ibadan    1598.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Lekki     1596.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Surulere  1598.5  NaN    NaN        NaN  2000.0       4.5  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     4002.0
Gbagada   4004.0
Ibadan    3004.0
Lekki     2001.0
Surulere  2004.5

[1061 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1596.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Surulere  1598.5  NaN    NaN        NaN  2000.0       4.5  NaN   9000.0
Ikoyi     1602.0  NaN    NaN        NaN  3000.0       4.5  NaN  14000.0
Lekki     1604.5  NaN    NaN        NaN  2500.0       2.5  NaN   6000.0
Surulere  1602.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2001.0
Surulere  2004.5
Ikoyi     3004.5
Lekki     2502.5
Surulere  4001.0

[1064 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     1604.500000  NaN    NaN        NaN  2500.000000  2.500000  NaN
Surulere  1602.000000  NaN    NaN        NaN  4000.000000  1.000000  NaN
Ibadan    1608.000000  NaN    NaN        NaN  2000.000000  1.000000  NaN
Ikoyi     1610.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Lekki     1607.333333  NaN    NaN        NaN  2333.333333  2.333333  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      6000.000000  2502.500000
Surulere   4000.000000  4001.000000
Ibadan     2000.000000  2001.000000
Ikoyi      8000.000000  4002.000000
Lekki      5333.333333  2335.666667

[1067 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     1607.333333  NaN    NaN        NaN  2333.333333  2.333333  NaN
Ibadan    1611.000000  NaN    NaN        NaN  2000.000000  2.000000  NaN
Ikoyi     1615.000000  NaN    NaN        NaN  3000.000000  5.000000  NaN
Lekki     1613.000000  NaN    NaN        NaN  4000.000000  3.500000  NaN
Surulere  1613.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      5333.333333  2335.666667
Ibadan     4000.000000  2002.000000
Ikoyi     15000.000000  3005.000000
Lekki     14000.000000  4003.500000
Surulere  20000.000000  4005.000000

[1071 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1613.0  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0
Surulere  1613.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ibadan    1618.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     1617.5  NaN    NaN        NaN  3500.0       2.0  NaN   7000.0
Surulere  1618.5  NaN    NaN        NaN  3000.0       3.0  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4003.5
Surulere  4005.0
Ibadan    4003.0
Lekki     3502.0
Surulere  3003.0

[1074 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1618.5  NaN    NaN        NaN  3000.0       3.0  NaN  10000.0
Gbagada   1623.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ibadan    1624.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ikoyi     1622.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Surulere  1623.0  NaN    NaN        NaN  3500.0       3.0  NaN  10500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3003.0
Gbagada   4005.0
Ibadan    2004.0
Ikoyi     2004.0
Surulere  3503.0

[1078 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1622.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Surulere  1623.0  NaN    NaN        NaN  3500.0       3.0  NaN  10500.0
Ibadan    1627.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Lekki     1627.5  NaN    NaN        NaN  3000.0       3.0  NaN   7000.0
Surulere  1629.0  NaN    NaN        NaN  3000.0       2.5  NaN   7500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     2004.0
Surulere  3503.0
Ibadan    2005.0
Lekki     3003.0
Surulere  3002.5

[1081 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0       3.0  NaN
...               ...  ...    ...        ...     ...       ...  ...
Lekki     1627.500000  NaN    NaN        NaN  3000.0       3.0  NaN
Surulere  1629.000000  NaN    NaN        NaN  3000.0       2.5  NaN
Gbagada   1633.000000  NaN    NaN        NaN  4000.0       2.0  NaN
Ikoyi     1632.666667  NaN    NaN        NaN  3000.0       2.0  NaN
Lekki     1634.000000  NaN    NaN        NaN  3000.0       2.0  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Lekki      7000.000000  3003.0
Surulere   7500.000000  3002.5
Gbagada    8000.000000  4002.0
Ikoyi      5666.666667  3002.0
Lekki      6000.000000  3002.0

[1084 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1634.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Gbagada   1640.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ibadan    1637.5  NaN    NaN        NaN  3500.0       3.0  NaN  11000.0
Lekki     1638.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Surulere  1637.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3002.0
Gbagada   4001.0
Ibadan    3503.0
Lekki     3004.0
Surulere  4003.0

[1088 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1638.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Surulere  1637.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Gbagada   1645.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Ibadan    1641.5  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0
Ikoyi     1643.5  NaN    NaN        NaN  3000.0       3.5  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3004.0
Surulere  4003.0
Gbagada   2002.0
Ibadan    4003.5
Ikoyi     3003.5

[1091 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1643.5  NaN    NaN        NaN  3000.0       3.5  NaN  10000.0
Ibadan    1646.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ikoyi     1650.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Lekki     1648.5  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0
Surulere  1647.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3003.5
Ibadan    2001.0
Ikoyi     4002.0
Lekki     4003.5
Surulere  3004.0

[1095 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1647.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Gbagada   1654.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ibadan    1653.0  NaN    NaN        NaN  3500.0       3.0  NaN  10000.0
Ikoyi     1653.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Lekki     1652.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3004.0
Gbagada   2001.0
Ibadan    3503.0
Ikoyi     3002.0
Lekki     4004.0

[1099 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki    1652.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Gbagada  1657.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Ibadan   1660.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0
Ikoyi    1657.5  NaN    NaN        NaN  2500.0       1.5  NaN   4000.0  2501.5
Lekki    1658.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0

[1103 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   1663.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ibadan    1662.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ikoyi     1664.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     1661.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Surulere  1665.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   4005.0
Ibadan    2001.0
Ikoyi     4003.0
Lekki     3003.0
Surulere  4001.0

[1108 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1661.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Surulere  1665.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Gbagada   1669.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ikoyi     1667.5  NaN    NaN        NaN  2500.0       2.5  NaN   5500.0
Surulere  1668.0  NaN    NaN        NaN  3000.0       4.0  NaN  11000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3003.0
Surulere  4001.0
Gbagada   2003.0
Ikoyi     2502.5
Surulere  3004.0

[1111 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1668.0  NaN    NaN        NaN  3000.0       4.0  NaN  11000.0
Ibadan    1671.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ikoyi     1672.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Lekki     1674.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  1674.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3004.0
Ibadan    2001.0
Ikoyi     4002.0
Lekki     4002.0
Surulere  3005.0

[1115 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   1680.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan    1676.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ikoyi     1678.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Lekki     1677.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Surulere  1679.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   2004.0
Ibadan    4002.0
Ikoyi     2002.0
Lekki     3005.0
Surulere  4002.0

[1120 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1677.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Surulere  1679.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ibadan    1683.0  NaN    NaN        NaN  3000.0       4.5  NaN  14000.0
Ikoyi     1684.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Lekki     1682.5  NaN    NaN        NaN  3000.0       3.5  NaN  10500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3005.0
Surulere  4002.0
Ibadan    3004.5
Ikoyi     4002.0
Lekki     3003.5

[1123 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   1689.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ibadan    1688.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ikoyi     1686.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Lekki     1690.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  1687.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   3004.0
Ibadan    4002.0
Ikoyi     3001.0
Lekki     4003.0
Surulere  2004.0

[1128 rows x 9 columns]
              S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.00  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.00  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.00  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.00  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.00  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...           ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1686.00  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Lekki     1690.00  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  1687.00  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ikoyi     1692.00  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Surulere  1693.25  NaN    NaN        NaN  3750.0       2.5  NaN   9250.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3001.0
Lekki     4003.0
Surulere  2004.0
Ikoyi     2004.0
Surulere  3752.5

[1130 rows x 9 columns]
              S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.00  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.00  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.00  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.00  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.00  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...           ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1692.00  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Surulere  1693.25  NaN    NaN        NaN  3750.0       2.5  NaN   9250.0
Gbagada   1697.00  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     1699.50  NaN    NaN        NaN  3000.0       3.0  NaN   8000.0
Surulere  1697.00  NaN    NaN        NaN  2500.0       4.5  NaN  11500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     2004.0
Surulere  3752.5
Gbagada   4003.0
Lekki     3003.0
Surulere  2504.5

[1133 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000       3.0  NaN
...          ...  ...    ...        ...          ...       ...  ...
Lekki     1699.5  NaN    NaN        NaN  3000.000000       3.0  NaN
Surulere  1697.0  NaN    NaN        NaN  2500.000000       4.5  NaN
Gbagada   1702.0  NaN    NaN        NaN  3333.333333       2.0  NaN
Lekki     1704.0  NaN    NaN        NaN  4000.000000       3.0  NaN
Surulere  1705.0  NaN    NaN        NaN  2000.000000       2.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      8000.000000  3003.000000
Surulere  11500.000000  2504.500000
Gbagada    6666.666667  3335.333333
Lekki     12000.000000  4003.000000
Surulere   4000.000000  2002.000000

[1136 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1705.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Gbagada   1707.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ibadan    1707.5  NaN    NaN        NaN  4000.0       2.5  NaN  10000.0
Lekki     1708.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  1710.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2002.0
Gbagada   3002.0
Ibadan    4002.5
Lekki     4002.0
Surulere  4004.0

[1140 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1710.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Gbagada   1713.5  NaN    NaN        NaN  3500.0       2.0  NaN   6500.0
Ikoyi     1711.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Lekki     1713.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Surulere  1714.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4004.0
Gbagada   3502.0
Ikoyi     2001.0
Lekki     2004.0
Surulere  2002.0

[1144 rows x 9 columns]

                  S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.0
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.0
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.0
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.0
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.0
...               ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1711.000000  NaN    NaN        NaN  2000.0  1.000000  NaN   2000.0
Lekki     1713.000000  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.0
Surulere  1714.000000  NaN    NaN        NaN  2000.0  2.000000  NaN   4000.0
Gbagada   1718.333333  NaN    NaN        NaN  3000.0  3.333333  NaN  11000.0
Surulere  1717.500000  NaN    NaN        NaN  2500.0  3.000000  NaN   6500.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Ikoyi     2001.000000
Lekki     2004.000000
Surulere  2002.000000
Gbagada   3003.333333
Surulere  2503.000000

[1146 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.0
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.0
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.0
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.0
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.0
...               ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   1718.333333  NaN    NaN        NaN  3000.0  3.333333  NaN  11000.0
Surulere  1717.500000  NaN    NaN        NaN  2500.0  3.000000  NaN   6500.0
Ibadan    1723.500000  NaN    NaN        NaN  2000.0  3.500000  NaN   7000.0
Ikoyi     1722.000000  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.0
Surulere  1723.000000  NaN    NaN        NaN  4000.0  2.500000  NaN  10000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Gbagada   3003.333333
Surulere  2503.000000
Ibadan    2003.500000
Ikoyi     2004.000000
Surulere  4002.500000

[1149 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ibadan    1723.500000  NaN    NaN        NaN  2000.000000  3.500000  NaN
Ikoyi     1722.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Surulere  1723.000000  NaN    NaN        NaN  4000.000000  2.500000  NaN
Ikoyi     1727.666667  NaN    NaN        NaN  3333.333333  3.666667  NaN
Lekki     1728.500000  NaN    NaN        NaN  3000.000000  3.500000  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Ibadan     7000.000000  2003.5
Ikoyi      8000.000000  2004.0
Surulere  10000.000000  4002.5
Ikoyi     11666.666667  3337.0
Lekki     10500.000000  3003.5

[1151 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     1727.666667  NaN    NaN        NaN  3333.333333  3.666667  NaN
Lekki     1728.500000  NaN    NaN        NaN  3000.000000  3.500000  NaN
Gbagada   1734.500000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Ikoyi     1732.000000  NaN    NaN        NaN  3000.000000  3.500000  NaN
Surulere  1732.000000  NaN    NaN        NaN  3000.000000  4.000000  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Ikoyi     11666.666667  3337.0
Lekki     10500.000000  3003.5
Gbagada    8000.000000  4002.0
Ikoyi     12000.000000  3003.5
Surulere  12000.000000  3004.0

[1154 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...          ...  ...    ...        ...          ...       ...  ...
Ikoyi     1732.0  NaN    NaN        NaN  3000.000000  3.500000  NaN
Surulere  1732.0  NaN    NaN        NaN  3000.000000  4.000000  NaN
Gbagada   1737.0  NaN    NaN        NaN  2666.666667  2.666667  NaN
Ibadan    1739.0  NaN    NaN        NaN  4000.000000  4.000000  NaN
Ikoyi     1740.0  NaN    NaN        NaN  4000.000000  3.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi     12000.000000  3003.500000
Surulere  12000.000000  3004.000000
Gbagada    6666.666667  2669.333333
Ibadan    16000.000000  4004.000000
Ikoyi     12000.000000  4003.000000

[1157 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.00  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.00  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.00  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.00  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.00  NaN    NaN        NaN  2000.000000  3.000000  NaN
...          ...  ...    ...        ...          ...       ...  ...
Gbagada  1737.00  NaN    NaN        NaN  2666.666667  2.666667  NaN
Ibadan   1739.00  NaN    NaN        NaN  4000.000000  4.000000  NaN
Ikoyi    1740.00  NaN    NaN        NaN  4000.000000  3.000000  NaN
Gbagada  1742.75  NaN    NaN        NaN  2500.000000  3.500000  NaN
Ibadan   1744.00  NaN    NaN        NaN  4000.000000  2.000000  NaN

              Revenue         Snap
Gbagada   8000.000000  2004.000000
Ibadan   10000.000000  2005.000000
Ikoyi     5000.000000  2002.500000
Lekki    20000.000000  4005.000000
Gbagada   6000.000000  2003.000000
...               ...          ...
Gbagada   6666.666667  2669.333333
Ibadan   16000.000000  4004.000000
Ikoyi    12000.000000  4003.000000
Gbagada   9000.000000  2503.500000
Ibadan    8000.000000  4002.000000

[1159 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    1744.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Gbagada   1748.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ibadan    1749.5  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Lekki     1747.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Surulere  1746.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    4002.0
Gbagada   4003.0
Ibadan    4004.0
Lekki     4004.0
Surulere  2003.0

[1163 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1746.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Gbagada   1753.0  NaN    NaN        NaN  3500.0       4.0  NaN  14500.0
Ibadan    1755.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ikoyi     1751.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     1753.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2003.0
Gbagada   3504.0
Ibadan    2003.0
Ikoyi     4001.0
Lekki     3005.0

[1167 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1753.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Gbagada   1759.0  NaN    NaN        NaN  3000.0       2.0  NaN   5000.0
Ibadan    1756.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ikoyi     1759.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Surulere  1757.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3005.0
Gbagada   3002.0
Ibadan    4005.0
Ikoyi     4001.0
Surulere  2002.0

[1171 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1757.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Gbagada   1761.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ibadan    1762.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     1763.5  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Surulere  1765.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2002.0
Gbagada   4004.0
Ibadan    4001.0
Lekki     3003.0
Surulere  2002.0

[1175 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1763.5  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Surulere  1765.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Gbagada   1767.5  NaN    NaN        NaN  3000.0       3.5  NaN  10500.0
Ibadan    1767.5  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Lekki     1770.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3003.0
Surulere  2002.0
Gbagada   3003.5
Ibadan    2001.0
Lekki     2002.0

[1178 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ibadan   1767.5  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Lekki    1770.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0
Ibadan   1773.5  NaN    NaN        NaN  3000.0       3.0  NaN   7000.0  3003.0
Ikoyi    1773.5  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Lekki    1771.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0

[1181 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1773.5  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     1771.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ibadan    1778.5  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Ikoyi     1776.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Surulere  1778.5  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     4003.0
Lekki     4003.0
Ibadan    2002.5
Ikoyi     3002.0
Surulere  4004.0

[1184 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1778.5  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ibadan    1784.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ikoyi     1785.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Lekki     1781.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Surulere  1782.5  NaN    NaN        NaN  3000.0       1.5  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4004.0
Ibadan    4002.0
Ikoyi     2001.0
Lekki     3001.0
Surulere  3001.5

[1188 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1782.5  NaN    NaN        NaN  3000.0       1.5  NaN   4000.0
Gbagada   1787.5  NaN    NaN        NaN  3500.0       3.0  NaN   9500.0
Ibadan    1789.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Lekki     1790.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  1786.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3001.5
Gbagada   3503.0
Ibadan    4004.0
Lekki     4003.0
Surulere  3002.0

[1192 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1790.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  1786.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Gbagada   1794.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ikoyi     1795.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Lekki     1792.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4003.0
Surulere  3002.0
Gbagada   4003.0
Ikoyi     4002.0
Lekki     3004.0

[1195 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1795.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Lekki     1792.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ibadan    1800.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ikoyi     1798.0  NaN    NaN        NaN  2000.0       4.5  NaN   9000.0
Surulere  1797.0  NaN    NaN        NaN  4000.0       2.5  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     4002.0
Lekki     3004.0
Ibadan    4002.0
Ikoyi     2004.5
Surulere  4002.5

[1198 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1798.0  NaN    NaN        NaN  2000.0       4.5  NaN   9000.0
Surulere  1797.0  NaN    NaN        NaN  4000.0       2.5  NaN  10000.0
Gbagada   1801.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Ibadan    1803.0  NaN    NaN        NaN  3000.0       2.5  NaN   7000.0
Lekki     1804.0  NaN    NaN        NaN  3000.0       2.5  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     2004.5
Surulere  4002.5
Gbagada   3003.0
Ibadan    3002.5
Lekki     3002.5

[1201 rows x 9 columns]

            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ibadan   1803.0  NaN    NaN        NaN  3000.0       2.5  NaN   7000.0  3002.5
Lekki    1804.0  NaN    NaN        NaN  3000.0       2.5  NaN   6000.0  3002.5
Ibadan   1808.5  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ikoyi    1809.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0
Lekki    1807.0  NaN    NaN        NaN  3500.0       3.5  NaN  11500.0  3503.5

[1204 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     1809.000000  NaN    NaN        NaN  3000.000000  4.000000  NaN
Lekki     1807.000000  NaN    NaN        NaN  3500.000000  3.500000  NaN
Gbagada   1813.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Ikoyi     1812.666667  NaN    NaN        NaN  3666.666667  3.666667  NaN
Surulere  1814.000000  NaN    NaN        NaN  4000.000000  1.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi     12000.000000  3004.000000
Lekki     11500.000000  3503.500000
Gbagada    8000.000000  4002.000000
Ikoyi     13333.333333  3670.333333
Surulere   4000.000000  4001.000000

[1207 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1814.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Gbagada   1818.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ikoyi     1816.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Lekki     1817.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  1819.5  NaN    NaN        NaN  3500.0       2.0  NaN   7500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4001.0
Gbagada   4002.0
Ikoyi     3005.0
Lekki     4003.0
Surulere  3502.0

[1211 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1817.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  1819.5  NaN    NaN        NaN  3500.0       2.0  NaN   7500.0
Gbagada   1822.5  NaN    NaN        NaN  3000.0       2.0  NaN   7000.0
Ikoyi     1825.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Surulere  1822.5  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4003.0
Surulere  3502.0
Gbagada   3002.0
Ikoyi     3004.0
Surulere  4003.0

[1214 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1825.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Surulere  1822.5  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ibadan    1829.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ikoyi     1827.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Surulere  1830.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3004.0
Surulere  4003.0
Ibadan    3001.0
Ikoyi     3002.0
Surulere  2003.0

[1217 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1830.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ibadan    1834.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ikoyi     1831.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Lekki     1833.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Surulere  1833.5  NaN    NaN        NaN  3500.0       3.0  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2003.0
Ibadan    4003.0
Ikoyi     2005.0
Lekki     2001.0
Surulere  3503.0

[1221 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1833.5  NaN    NaN        NaN  3500.0       3.0  NaN  10000.0
Gbagada   1838.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ibadan    1840.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Ikoyi     1837.5  NaN    NaN        NaN  3500.0       3.5  NaN  12500.0
Lekki     1837.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3503.0
Gbagada   4003.0
Ibadan    3003.0
Ikoyi     3503.5
Lekki     4003.0

[1225 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1837.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Gbagada   1843.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ibadan    1844.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ikoyi     1843.0  NaN    NaN        NaN  3500.0       4.0  NaN  13500.0
Surulere  1842.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4003.0
Gbagada   2005.0
Ibadan    4003.0
Ikoyi     3504.0
Surulere  3001.0

[1229 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1843.0  NaN    NaN        NaN  3500.0       4.0  NaN  13500.0
Surulere  1842.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Gbagada   1847.0  NaN    NaN        NaN  3500.0       3.0  NaN  10500.0
Ikoyi     1850.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Surulere  1848.0  NaN    NaN        NaN  3000.0       3.5  NaN  10500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3504.0
Surulere  3001.0
Gbagada   3503.0
Ikoyi     3002.0
Surulere  3003.5

[1232 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1850.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Surulere  1848.0  NaN    NaN        NaN  3000.0       3.5  NaN  10500.0
Ibadan    1852.5  NaN    NaN        NaN  3000.0       3.5  NaN  12000.0
Lekki     1852.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  1854.0  NaN    NaN        NaN  3500.0       1.5  NaN   5500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3002.0
Surulere  3003.5
Ibadan    3003.5
Lekki     4002.0
Surulere  3501.5

[1235 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1854.0  NaN    NaN        NaN  3500.0       1.5  NaN   5500.0
Gbagada   1860.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ibadan    1856.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ikoyi     1858.5  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0
Lekki     1857.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3501.5
Gbagada   4001.0
Ibadan    4005.0
Ikoyi     4003.5
Lekki     3002.0

[1239 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1858.5  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0
Lekki     1857.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Gbagada   1862.5  NaN    NaN        NaN  3500.0       1.5  NaN   5000.0
Ibadan    1864.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Surulere  1862.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     4003.5
Lekki     3002.0
Gbagada   3501.5
Ibadan    3003.0
Surulere  2005.0

[1242 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1862.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Gbagada   1867.5  NaN    NaN        NaN  3000.0       3.0  NaN  11000.0
Ikoyi     1869.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Lekki     1870.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  1866.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2005.0
Gbagada   3003.0
Ikoyi     3004.0
Lekki     4002.0
Surulere  3002.0

[1246 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1866.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ibadan    1872.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ikoyi     1874.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Lekki     1872.0  NaN    NaN        NaN  4000.0       2.5  NaN  10000.0
Surulere  1875.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3002.0
Ibadan    3001.0
Ikoyi     3002.0
Lekki     4002.5
Surulere  4003.0

[1250 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1872.0  NaN    NaN        NaN  4000.0       2.5  NaN  10000.0
Surulere  1875.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Gbagada   1879.5  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Ibadan    1878.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Surulere  1876.5  NaN    NaN        NaN  2500.0       2.5  NaN   6500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4002.5
Surulere  4003.0
Gbagada   3003.0
Ibadan    2003.0
Surulere  2502.5

[1253 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1876.5  NaN    NaN        NaN  2500.0       2.5  NaN   6500.0
Ibadan    1884.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ikoyi     1884.0  NaN    NaN        NaN  2500.0       5.0  NaN  12500.0
Lekki     1882.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Surulere  1881.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2502.5
Ibadan    4003.0
Ikoyi     2505.0
Lekki     3001.0
Surulere  3001.0

[1257 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     1882.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Surulere  1881.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Gbagada   1887.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ibadan    1890.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi     1888.0  NaN    NaN        NaN  4000.0       1.5  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3001.0
Surulere  3001.0
Gbagada   3002.0
Ibadan    2005.0
Ikoyi     4001.5

[1260 rows x 9 columns]
            S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada     5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0
Ibadan      1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ikoyi       3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN   5000.0
Lekki       3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Gbagada     9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
...         ...  ...    ...        ...          ...       ...  ...      ...
Gbagada  1887.0  NaN    NaN        NaN  3000.000000  2.000000  NaN   6000.0
Ibadan   1890.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ikoyi    1888.0  NaN    NaN        NaN  4000.000000  1.500000  NaN   6000.0
Gbagada  1892.0  NaN    NaN        NaN  2666.666667  2.333333  NaN   6000.0
Ibadan   1894.5  NaN    NaN        NaN  3000.000000  1.000000  NaN   3000.0

           Snap
Gbagada  2004.0
Ibadan   2005.0
Ikoyi    2002.5
Lekki    4005.0
Gbagada  2003.0
...         ...
Gbagada  3002.0
Ibadan   2005.0
Ikoyi    4001.5
Gbagada  2669.0
Ibadan   3001.0

[1262 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    1894.5  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ibadan    1897.5  NaN    NaN        NaN  3000.0       3.0  NaN  10000.0
Ikoyi     1898.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Lekki     1897.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Surulere  1900.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    3001.0
Ibadan    3003.0
Ikoyi     4002.0
Lekki     4004.0
Surulere  4005.0

[1266 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...               ...  ...    ...        ...     ...       ...  ...
Lekki     1897.000000  NaN    NaN        NaN  4000.0  4.000000  NaN
Surulere  1900.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Ikoyi     1905.000000  NaN    NaN        NaN  4000.0  1.000000  NaN
Lekki     1902.333333  NaN    NaN        NaN  3000.0  2.666667  NaN
Surulere  1903.000000  NaN    NaN        NaN  3000.0  5.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki     16000.000000  4004.000000
Surulere  20000.000000  4005.000000
Ikoyi      4000.000000  4001.000000
Lekki      7333.333333  3002.666667
Surulere  15000.000000  3005.000000

[1269 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...               ...  ...    ...        ...     ...       ...  ...
Lekki     1902.333333  NaN    NaN        NaN  3000.0  2.666667  NaN
Surulere  1903.000000  NaN    NaN        NaN  3000.0  5.000000  NaN
Gbagada   1907.500000  NaN    NaN        NaN  3000.0  2.000000  NaN
Ikoyi     1908.000000  NaN    NaN        NaN  2000.0  2.000000  NaN
Surulere  1909.000000  NaN    NaN        NaN  3000.0  2.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      7333.333333  3002.666667
Surulere  15000.000000  3005.000000
Gbagada    6000.000000  3002.000000
Ikoyi      4000.000000  2002.000000
Surulere   6000.000000  3002.000000

[1272 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1908.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Surulere  1909.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ibadan    1912.5  NaN    NaN        NaN  3500.0       4.0  NaN  14500.0
Ikoyi     1914.5  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0
Lekki     1911.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     2002.0
Surulere  3002.0
Ibadan    3504.0
Ikoyi     4003.5
Lekki     2002.0

[1275 rows x 9 columns]
                 S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...              ...  ...    ...        ...     ...       ...  ...
Ikoyi    1914.500000  NaN    NaN        NaN  4000.0  3.500000  NaN
Lekki    1911.000000  NaN    NaN        NaN  2000.0  2.000000  NaN
Gbagada  1920.000000  NaN    NaN        NaN  3000.0  1.000000  NaN
Ibadan   1917.666667  NaN    NaN        NaN  2000.0  4.666667  NaN
Ikoyi    1917.000000  NaN    NaN        NaN  3000.0  3.000000  NaN

              Revenue         Snap
Gbagada   8000.000000  2004.000000
Ibadan   10000.000000  2005.000000
Ikoyi     5000.000000  2002.500000
Lekki    20000.000000  4005.000000
Gbagada   6000.000000  2003.000000
...               ...          ...
Ikoyi    14000.000000  4003.500000
Lekki     4000.000000  2002.000000
Gbagada   3000.000000  3001.000000
Ibadan    9333.333333  2004.666667
Ikoyi     9000.000000  3003.000000

[1278 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1917.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Gbagada   1925.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ibadan    1924.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Lekki     1922.0  NaN    NaN        NaN  4000.0       2.5  NaN  10000.0
Surulere  1922.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3003.0
Gbagada   4002.0
Ibadan    3005.0
Lekki     4002.5
Surulere  4005.0

[1282 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1922.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ibadan    1928.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ikoyi     1929.5  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Lekki     1926.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Surulere  1927.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4005.0
Ibadan    3004.0
Ikoyi     3004.0
Lekki     2005.0
Surulere  2005.0

[1286 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1927.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Gbagada   1932.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ibadan    1933.0  NaN    NaN        NaN  2500.0       4.0  NaN  10500.0
Ikoyi     1933.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Lekki     1934.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2005.0
Gbagada   3004.0
Ibadan    2504.0
Ikoyi     3001.0
Lekki     2004.0

[1290 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada     5.00  NaN    NaN        NaN  2000.0      4.00  NaN   8000.0
Ibadan      1.00  NaN    NaN        NaN  2000.0      5.00  NaN  10000.0
Ikoyi       3.00  NaN    NaN        NaN  2000.0      2.50  NaN   5000.0
Lekki       3.00  NaN    NaN        NaN  4000.0      5.00  NaN  20000.0
Gbagada     9.00  NaN    NaN        NaN  2000.0      3.00  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan   1933.00  NaN    NaN        NaN  2500.0      4.00  NaN  10500.0
Ikoyi    1933.00  NaN    NaN        NaN  3000.0      1.00  NaN   3000.0
Lekki    1934.00  NaN    NaN        NaN  2000.0      4.00  NaN   8000.0
Ibadan   1938.25  NaN    NaN        NaN  3000.0      2.25  NaN   7750.0
Ikoyi    1937.00  NaN    NaN        NaN  3000.0      2.00  NaN   6000.0

            Snap
Gbagada  2004.00
Ibadan   2005.00
Ikoyi    2002.50
Lekki    4005.00
Gbagada  2003.00
...          ...
Ibadan   2504.00
Ikoyi    3001.00
Lekki    2004.00
Ibadan   3002.25
Ikoyi    3002.00

[1292 rows x 9 columns]
                 S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada     5.000000  NaN    NaN        NaN  2000.0      4.00  NaN   8000.0
Ibadan      1.000000  NaN    NaN        NaN  2000.0      5.00  NaN  10000.0
Ikoyi       3.000000  NaN    NaN        NaN  2000.0      2.50  NaN   5000.0
Lekki       3.000000  NaN    NaN        NaN  4000.0      5.00  NaN  20000.0
Gbagada     9.000000  NaN    NaN        NaN  2000.0      3.00  NaN   6000.0
...              ...  ...    ...        ...     ...       ...  ...      ...
Lekki    1934.000000  NaN    NaN        NaN  2000.0      4.00  NaN   8000.0
Ibadan   1938.250000  NaN    NaN        NaN  3000.0      2.25  NaN   7750.0
Ikoyi    1937.000000  NaN    NaN        NaN  3000.0      2.00  NaN   6000.0
Gbagada  1943.666667  NaN    NaN        NaN  4000.0      2.00  NaN   8000.0
Lekki    1942.000000  NaN    NaN        NaN  3000.0      3.50  NaN  10500.0

            Snap
Gbagada  2004.00
Ibadan   2005.00
Ikoyi    2002.50
Lekki    4005.00
Gbagada  2003.00
...          ...
Lekki    2004.00
Ibadan   3002.25
Ikoyi    3002.00
Gbagada  4002.00
Lekki    3003.50

[1294 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...               ...  ...    ...        ...     ...       ...  ...
Gbagada   1943.666667  NaN    NaN        NaN  4000.0  2.000000  NaN
Lekki     1942.000000  NaN    NaN        NaN  3000.0  3.500000  NaN
Ibadan    1949.000000  NaN    NaN        NaN  4000.0  1.666667  NaN
Lekki     1947.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Surulere  1946.000000  NaN    NaN        NaN  3000.0  1.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Gbagada    8000.000000  4002.000000
Lekki     10500.000000  3003.500000
Ibadan     6666.666667  4001.666667
Lekki      8000.000000  2004.000000
Surulere   3000.000000  3001.000000

[1297 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1946.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Gbagada   1954.0  NaN    NaN        NaN  3000.0       4.0  NaN  11000.0
Ibadan    1954.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Lekki     1952.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  1951.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3001.0
Gbagada   3004.0
Ibadan    4005.0
Lekki     4002.0
Surulere  2005.0

[1301 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1951.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Gbagada   1960.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ibadan    1958.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Ikoyi     1957.5  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     1957.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2005.0
Gbagada   3001.0
Ibadan    2002.0
Ikoyi     4003.0
Lekki     2003.0

[1305 rows x 9 columns]

                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     1957.500000  NaN    NaN        NaN  4000.000000       3.0  NaN
Lekki     1957.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
Gbagada   1962.333333  NaN    NaN        NaN  2666.666667       2.0  NaN
Lekki     1965.000000  NaN    NaN        NaN  4000.000000       4.0  NaN
Surulere  1963.000000  NaN    NaN        NaN  4000.000000       1.0  NaN

          Revenue         Snap
Gbagada    8000.0  2004.000000
Ibadan    10000.0  2005.000000
Ikoyi      5000.0  2002.500000
Lekki     20000.0  4005.000000
Gbagada    6000.0  2003.000000
...           ...          ...
Ikoyi     12000.0  4003.000000
Lekki      6000.0  2003.000000
Gbagada    6000.0  2668.666667
Lekki     16000.0  4004.000000
Surulere   4000.0  4001.000000

[1308 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1963.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Gbagada   1970.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ibadan    1966.5  NaN    NaN        NaN  4000.0       2.5  NaN  10000.0
Ikoyi     1969.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Lekki     1968.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4001.0
Gbagada   4005.0
Ibadan    4002.5
Ikoyi     2003.0
Lekki     2001.0

[1312 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi    1969.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Lekki    1968.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Gbagada  1972.5  NaN    NaN        NaN  4000.0       2.5  NaN  10000.0  4002.5
Ikoyi    1975.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0  3001.0
Lekki    1972.5  NaN    NaN        NaN  2500.0       3.0  NaN   8000.0  2503.0

[1315 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     1975.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Lekki     1972.5  NaN    NaN        NaN  2500.0       3.0  NaN   8000.0
Gbagada   1976.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ikoyi     1978.5  NaN    NaN        NaN  3000.0       1.5  NaN   4000.0
Surulere  1978.5  NaN    NaN        NaN  2500.0       2.0  NaN   5000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3001.0
Lekki     2503.0
Gbagada   3004.0
Ikoyi     3001.5
Surulere  2502.0

[1318 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     1978.500000  NaN    NaN        NaN  3000.000000  1.500000  NaN
Surulere  1978.500000  NaN    NaN        NaN  2500.000000  2.000000  NaN
Gbagada   1983.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Ikoyi     1981.000000  NaN    NaN        NaN  3000.000000  5.000000  NaN
Surulere  1983.666667  NaN    NaN        NaN  3333.333333  3.333333  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi      4000.000000  3001.500000
Surulere   5000.000000  2502.000000
Gbagada   20000.000000  4005.000000
Ikoyi     15000.000000  3005.000000
Surulere  11333.333333  3336.666667

[1321 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     1981.000000  NaN    NaN        NaN  3000.000000  5.000000  NaN
Surulere  1983.666667  NaN    NaN        NaN  3333.333333  3.333333  NaN
Gbagada   1987.000000  NaN    NaN        NaN  3000.000000  2.500000  NaN
Ikoyi     1989.500000  NaN    NaN        NaN  4000.000000  3.500000  NaN
Surulere  1987.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi     15000.000000  3005.000000
Surulere  11333.333333  3336.666667
Gbagada    9000.000000  3002.500000
Ikoyi     14000.000000  4003.500000
Surulere  20000.000000  4005.000000

[1324 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1987.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada   1992.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ibadan    1994.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ikoyi     1993.0  NaN    NaN        NaN  3500.0       2.5  NaN   9000.0
Lekki     1993.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4005.0
Gbagada   4004.0
Ibadan    2004.0
Ikoyi     3502.5
Lekki     2001.0

[1328 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   1998.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ibadan    1996.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ikoyi     2000.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Lekki     1999.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Surulere  1997.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   3002.0
Ibadan    2004.0
Ikoyi     3005.0
Lekki     2001.0
Surulere  2002.0

[1333 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  1997.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Gbagada   2004.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ibadan    2003.5  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ikoyi     2001.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Lekki     2003.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2002.0
Gbagada   3005.0
Ibadan    4003.0
Ikoyi     2001.0
Lekki     3001.0

[1337 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     2001.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Lekki     2003.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ikoyi     2008.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     2007.0  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0
Surulere  2010.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     2001.0
Lekki     3001.0
Ikoyi     4003.0
Lekki     4003.5
Surulere  4001.0

[1340 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     2007.0  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0
Surulere  2010.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Gbagada   2014.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Lekki     2012.5  NaN    NaN        NaN  3000.0       2.5  NaN   6000.0
Surulere  2012.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4003.5
Surulere  4001.0
Gbagada   4005.0
Lekki     3002.5
Surulere  4002.0

[1343 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2012.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Gbagada   2019.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ibadan    2017.0  NaN    NaN        NaN  2500.0       2.5  NaN   6000.0
Lekki     2017.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Surulere  2020.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4002.0
Gbagada   2001.0
Ibadan    2502.5
Lekki     4001.0
Surulere  2001.0

[1347 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000       3.0  NaN
...          ...  ...    ...        ...          ...       ...  ...
Lekki     2017.0  NaN    NaN        NaN  4000.000000       1.0  NaN
Surulere  2020.0  NaN    NaN        NaN  2000.000000       1.0  NaN
Gbagada   2022.0  NaN    NaN        NaN  3666.666667       2.0  NaN
Lekki     2024.0  NaN    NaN        NaN  3000.000000       3.0  NaN
Surulere  2025.0  NaN    NaN        NaN  4000.000000       5.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      4000.000000  4001.000000
Surulere   2000.000000  2001.000000
Gbagada    7333.333333  3668.666667
Lekki      9000.000000  3003.000000
Surulere  20000.000000  4005.000000

[1350 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     2024.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Surulere  2025.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ibadan    2028.5  NaN    NaN        NaN  3000.0       1.5  NaN   4000.0
Lekki     2026.5  NaN    NaN        NaN  2000.0       3.5  NaN   7000.0
Surulere  2030.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3003.0
Surulere  4005.0
Ibadan    3001.5
Lekki     2003.5
Surulere  4001.0

[1353 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ibadan    2028.500000  NaN    NaN        NaN  3000.000000  1.500000  NaN
Lekki     2026.500000  NaN    NaN        NaN  2000.000000  3.500000  NaN
Surulere  2030.000000  NaN    NaN        NaN  4000.000000  1.000000  NaN
Ikoyi     2033.500000  NaN    NaN        NaN  3000.000000  2.500000  NaN
Lekki     2032.666667  NaN    NaN        NaN  2333.333333  3.333333  NaN

          Revenue         Snap
Gbagada    8000.0  2004.000000
Ibadan    10000.0  2005.000000
Ikoyi      5000.0  2002.500000
Lekki     20000.0  4005.000000
Gbagada    6000.0  2003.000000
...           ...          ...
Ibadan     4000.0  3001.500000
Lekki      7000.0  2003.500000
Surulere   4000.0  4001.000000
Ikoyi      8000.0  3002.500000
Lekki      8000.0  2336.666667

[1355 rows x 9 columns]
                 S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...              ...  ...    ...        ...          ...       ...  ...
Ikoyi    2033.500000  NaN    NaN        NaN  3000.000000  2.500000  NaN
Lekki    2032.666667  NaN    NaN        NaN  2333.333333  3.333333  NaN
Gbagada  2039.500000  NaN    NaN        NaN  2500.000000  4.000000  NaN
Ikoyi    2037.500000  NaN    NaN        NaN  3000.000000  3.000000  NaN
Lekki    2036.000000  NaN    NaN        NaN  4000.000000  1.000000  NaN

         Revenue         Snap
Gbagada   8000.0  2004.000000
Ibadan   10000.0  2005.000000
Ikoyi     5000.0  2002.500000
Lekki    20000.0  4005.000000
Gbagada   6000.0  2003.000000
...          ...          ...
Ikoyi     8000.0  3002.500000
Lekki     8000.0  2336.666667
Gbagada  10500.0  2504.000000
Ikoyi     9000.0  3003.000000
Lekki     4000.0  4001.000000

[1358 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki    2036.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Gbagada  2043.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ibadan   2043.5  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ikoyi    2044.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Lekki    2041.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0  3002.0

[1362 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     2041.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Gbagada   2049.0  NaN    NaN        NaN  3000.0       3.5  NaN   9000.0
Ibadan    2047.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     2049.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  2046.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3002.0
Gbagada   3003.5
Ibadan    4003.0
Lekki     4003.0
Surulere  2003.0

[1366 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2046.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ibadan    2055.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ikoyi     2053.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Lekki     2053.0  NaN    NaN        NaN  3000.0       3.5  NaN  11000.0
Surulere  2051.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2003.0
Ibadan    4002.0
Ikoyi     3005.0
Lekki     3003.5
Surulere  2001.0

[1370 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2051.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ibadan    2059.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ikoyi     2057.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     2060.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Surulere  2057.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2001.0
Ibadan    3002.0
Ikoyi     4003.0
Lekki     3004.0
Surulere  4004.0

[1374 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   2061.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Ibadan    2062.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Ikoyi     2063.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Lekki     2064.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  2065.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   2002.0
Ibadan    3003.0
Ikoyi     4004.0
Lekki     4005.0
Surulere  2002.0

[1379 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...          ...  ...    ...        ...          ...       ...  ...
Ikoyi     2063.0  NaN    NaN        NaN  4000.000000  4.000000  NaN
Lekki     2064.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Surulere  2065.0  NaN    NaN        NaN  2000.000000  2.000000  NaN
Ibadan    2068.0  NaN    NaN        NaN  2666.666667  3.333333  NaN
Lekki     2068.0  NaN    NaN        NaN  3000.000000  2.000000  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Ikoyi     16000.000000  4004.0
Lekki     20000.000000  4005.0
Surulere   4000.000000  2002.0
Ibadan     8666.666667  2670.0
Lekki      6000.000000  3002.0

[1381 rows x 9 columns]
            S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...         ...  ...    ...        ...          ...       ...  ...
Ibadan   2068.0  NaN    NaN        NaN  2666.666667  3.333333  NaN
Lekki    2068.0  NaN    NaN        NaN  3000.000000  2.000000  NaN
Gbagada  2071.0  NaN    NaN        NaN  2000.000000  2.000000  NaN
Ikoyi    2074.5  NaN    NaN        NaN  2000.000000  3.500000  NaN
Lekki    2072.5  NaN    NaN        NaN  2000.000000  3.500000  NaN

              Revenue    Snap
Gbagada   8000.000000  2004.0
Ibadan   10000.000000  2005.0
Ikoyi     5000.000000  2002.5
Lekki    20000.000000  4005.0
Gbagada   6000.000000  2003.0
...               ...     ...
Ibadan    8666.666667  2670.0
Lekki     6000.000000  3002.0
Gbagada   4000.000000  2002.0
Ikoyi     7000.000000  2003.5
Lekki     7000.000000  2003.5

[1384 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     2072.5  NaN    NaN        NaN  2000.0       3.5  NaN   7000.0
Ibadan    2079.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ikoyi     2076.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Lekki     2077.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Surulere  2079.0  NaN    NaN        NaN  3500.0       3.5  NaN  12500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2003.5
Ibadan    4003.0
Ikoyi     2002.0
Lekki     3003.0
Surulere  3503.5

[1388 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2079.0  NaN    NaN        NaN  3500.0       3.5  NaN  12500.0
Gbagada   2084.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ibadan    2082.5  NaN    NaN        NaN  3000.0       3.5  NaN  10500.0
Lekki     2081.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Surulere  2085.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3503.5
Gbagada   4005.0
Ibadan    3003.5
Lekki     4004.0
Surulere  4002.0

[1392 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     2081.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Surulere  2085.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ibadan    2089.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ikoyi     2088.5  NaN    NaN        NaN  3000.0       1.5  NaN   4500.0
Surulere  2087.0  NaN    NaN        NaN  3000.0       4.0  NaN  13000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4004.0
Surulere  4002.0
Ibadan    3005.0
Ikoyi     3001.5
Surulere  3004.0

[1395 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   2095.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ibadan    2092.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ikoyi     2094.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Lekki     2093.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  2091.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   4004.0
Ibadan    4002.0
Ikoyi     4002.0
Lekki     4003.0
Surulere  3001.0

[1400 rows x 9 columns]

                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     2093.000000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Surulere  2091.000000  NaN    NaN        NaN  3000.000000  1.000000  NaN
Ibadan    2098.000000  NaN    NaN        NaN  2000.000000  2.000000  NaN
Lekki     2097.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Surulere  2098.333333  NaN    NaN        NaN  3666.666667  3.666667  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki     12000.000000  4003.000000
Surulere   3000.000000  3001.000000
Ibadan     4000.000000  2002.000000
Lekki      8000.000000  4002.000000
Surulere  13333.333333  3670.333333

[1403 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     2097.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Surulere  2098.333333  NaN    NaN        NaN  3666.666667  3.666667  NaN
Ibadan    2103.500000  NaN    NaN        NaN  3500.000000  3.000000  NaN
Ikoyi     2102.500000  NaN    NaN        NaN  3000.000000  2.500000  NaN
Surulere  2103.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      8000.000000  4002.000000
Surulere  13333.333333  3670.333333
Ibadan     9500.000000  3503.000000
Ikoyi      7000.000000  3002.500000
Surulere   8000.000000  2004.000000

[1406 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2103.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan    2107.5  NaN    NaN        NaN  2500.0       4.0  NaN  10500.0
Ikoyi     2109.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Lekki     2110.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Surulere  2106.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2004.0
Ibadan    2504.0
Ikoyi     3004.0
Lekki     3002.0
Surulere  2005.0

[1410 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2106.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Gbagada   2111.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ikoyi     2115.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Lekki     2113.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Surulere  2113.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2005.0
Gbagada   4003.0
Ikoyi     2003.0
Lekki     3002.0
Surulere  3001.0

[1414 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2113.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ibadan    2119.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ikoyi     2116.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     2120.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Surulere  2117.5  NaN    NaN        NaN  3500.0       2.5  NaN   8500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3001.0
Ibadan    3001.0
Ikoyi     4001.0
Lekki     2003.0
Surulere  3502.5

[1418 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2117.5  NaN    NaN        NaN  3500.0       2.5  NaN   8500.0
Ibadan    2121.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ikoyi     2123.5  NaN    NaN        NaN  3000.0       3.5  NaN   9000.0
Lekki     2125.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Surulere  2122.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3502.5
Ibadan    3004.0
Ikoyi     3003.5
Lekki     3002.0
Surulere  4003.0

[1422 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2122.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Gbagada   2127.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ibadan    2127.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     2130.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  2129.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4003.0
Gbagada   4003.0
Ibadan    4003.0
Lekki     4002.0
Surulere  4001.0

[1426 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ibadan    2127.000000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Lekki     2130.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Surulere  2129.000000  NaN    NaN        NaN  4000.000000  1.000000  NaN
Ibadan    2132.666667  NaN    NaN        NaN  2666.666667  2.333333  NaN
Lekki     2133.500000  NaN    NaN        NaN  4000.000000  3.000000  NaN

          Revenue    Snap
Gbagada    8000.0  2004.0
Ibadan    10000.0  2005.0
Ikoyi      5000.0  2002.5
Lekki     20000.0  4005.0
Gbagada    6000.0  2003.0
...           ...     ...
Ibadan    12000.0  4003.0
Lekki      8000.0  4002.0
Surulere   4000.0  4001.0
Ibadan     6000.0  2669.0
Lekki     12000.0  4003.0

[1428 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     2133.5  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Gbagada   2136.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ibadan    2140.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     2138.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Surulere  2138.0  NaN    NaN        NaN  3000.0       3.0  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4003.0
Gbagada   4002.0
Ibadan    4003.0
Lekki     2001.0
Surulere  3003.0

[1432 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2138.0  NaN    NaN        NaN  3000.0       3.0  NaN  10000.0
Gbagada   2143.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ibadan    2145.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ikoyi     2142.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Surulere  2142.5  NaN    NaN        NaN  3000.0       3.0  NaN   7000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3003.0
Gbagada   4001.0
Ibadan    4005.0
Ikoyi     3003.0
Surulere  3003.0

[1436 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     2142.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Surulere  2142.5  NaN    NaN        NaN  3000.0       3.0  NaN   7000.0
Ibadan    2148.0  NaN    NaN        NaN  3000.0       2.0  NaN   7000.0
Ikoyi     2147.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  2148.5  NaN    NaN        NaN  3500.0       3.5  NaN  11500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3003.0
Surulere  3003.0
Ibadan    3002.0
Ikoyi     4005.0
Surulere  3503.5

[1439 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2148.5  NaN    NaN        NaN  3500.0       3.5  NaN  11500.0
Gbagada   2154.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ikoyi     2153.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Lekki     2153.0  NaN    NaN        NaN  3000.0       3.5  NaN   9000.0
Surulere  2152.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3503.5
Gbagada   4005.0
Ikoyi     4005.0
Lekki     3003.5
Surulere  4005.0

[1443 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     2153.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Lekki     2153.000000  NaN    NaN        NaN  3000.000000  3.500000  NaN
Surulere  2152.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada   2158.666667  NaN    NaN        NaN  3666.666667  2.666667  NaN
Ibadan    2157.000000  NaN    NaN        NaN  3500.000000  4.500000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi     20000.000000  4005.000000
Lekki      9000.000000  3003.500000
Surulere  20000.000000  4005.000000
Gbagada   10333.333333  3669.333333
Ibadan    15500.000000  3504.500000

[1445 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    2157.0  NaN    NaN        NaN  3500.0       4.5  NaN  15500.0
Gbagada   2162.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ikoyi     2163.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Lekki     2162.5  NaN    NaN        NaN  4000.0       4.5  NaN  18000.0
Surulere  2165.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    3504.5
Gbagada   3005.0
Ikoyi     3004.0
Lekki     4004.5
Surulere  2002.0

[1449 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2165.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Gbagada   2167.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ibadan    2170.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ikoyi     2167.5  NaN    NaN        NaN  2500.0       4.0  NaN  10500.0
Lekki     2168.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2002.0
Gbagada   3002.0
Ibadan    3005.0
Ikoyi     2504.0
Lekki     3002.0

[1453 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     2167.5  NaN    NaN        NaN  2500.0       4.0  NaN  10500.0
Lekki     2168.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ibadan    2173.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ikoyi     2174.5  NaN    NaN        NaN  3500.0       3.0  NaN  10500.0
Surulere  2171.5  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     2504.0
Lekki     3002.0
Ibadan    3001.0
Ikoyi     3503.0
Surulere  3003.0

[1456 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     2174.5  NaN    NaN        NaN  3500.0       3.0  NaN  10500.0
Surulere  2171.5  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Gbagada   2179.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ikoyi     2177.5  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0
Surulere  2178.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3503.0
Surulere  3003.0
Gbagada   4002.0
Ikoyi     4003.5
Surulere  3005.0

[1459 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2178.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Gbagada   2184.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ibadan    2183.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ikoyi     2183.0  NaN    NaN        NaN  3000.0       2.0  NaN   5000.0
Surulere  2182.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3005.0
Gbagada   4004.0
Ibadan    3004.0
Ikoyi     3002.0
Surulere  2002.0

[1463 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     2183.0  NaN    NaN        NaN  3000.0       2.0  NaN   5000.0
Surulere  2182.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Gbagada   2187.5  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ibadan    2186.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Lekki     2189.5  NaN    NaN        NaN  2500.0       4.0  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3002.0
Surulere  2002.0
Gbagada   2003.0
Ibadan    2001.0
Lekki     2504.0

[1466 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    2186.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Lekki     2189.5  NaN    NaN        NaN  2500.0       4.0  NaN  10000.0
Ibadan    2192.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ikoyi     2193.5  NaN    NaN        NaN  3000.0       3.5  NaN  10500.0
Surulere  2193.0  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    2001.0
Lekki     2504.0
Ibadan    4004.0
Ikoyi     3003.5
Surulere  4003.5

[1469 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     2193.5  NaN    NaN        NaN  3000.0       3.5  NaN  10500.0
Surulere  2193.0  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0
Gbagada   2197.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ibadan    2197.0  NaN    NaN        NaN  4000.0       1.5  NaN   6000.0
Surulere  2199.5  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3003.5
Surulere  4003.5
Gbagada   2005.0
Ibadan    4001.5
Surulere  4004.0

[1472 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   2204.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ibadan    2203.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ikoyi     2202.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Lekki     2205.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Surulere  2201.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   2001.0
Ibadan    3001.0
Ikoyi     4004.0
Lekki     2005.0
Surulere  3001.0

[1477 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     2205.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Surulere  2201.000000  NaN    NaN        NaN  3000.000000  1.000000  NaN
Gbagada   2207.333333  NaN    NaN        NaN  3333.333333  3.666667  NaN
Ibadan    2208.000000  NaN    NaN        NaN  3000.000000  5.000000  NaN
Lekki     2210.000000  NaN    NaN        NaN  2000.000000  2.000000  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Lekki     10000.000000  2005.0
Surulere   3000.000000  3001.0
Gbagada   11333.333333  3337.0
Ibadan    15000.000000  3005.0
Lekki      4000.000000  2002.0

[1480 rows x 9 columns]
            S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada     5.0  NaN    NaN        NaN  2000.000000       4.0  NaN   8000.0
Ibadan      1.0  NaN    NaN        NaN  2000.000000       5.0  NaN  10000.0
Ikoyi       3.0  NaN    NaN        NaN  2000.000000       2.5  NaN   5000.0
Lekki       3.0  NaN    NaN        NaN  4000.000000       5.0  NaN  20000.0
Gbagada     9.0  NaN    NaN        NaN  2000.000000       3.0  NaN   6000.0
...         ...  ...    ...        ...          ...       ...  ...      ...
Ibadan   2208.0  NaN    NaN        NaN  3000.000000       5.0  NaN  15000.0
Lekki    2210.0  NaN    NaN        NaN  2000.000000       2.0  NaN   4000.0
Gbagada  2213.0  NaN    NaN        NaN  2666.666667       3.0  NaN   8000.0
Ikoyi    2214.0  NaN    NaN        NaN  4000.000000       2.0  NaN   8000.0
Lekki    2212.0  NaN    NaN        NaN  4000.000000       4.0  NaN  16000.0

                Snap
Gbagada  2004.000000
Ibadan   2005.000000
Ikoyi    2002.500000
Lekki    4005.000000
Gbagada  2003.000000
...              ...
Ibadan   3005.000000
Lekki    2002.000000
Gbagada  2669.666667
Ikoyi    4002.000000
Lekki    4004.000000

[1483 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time       Revenue  \
Gbagada     5.0  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.000000
Ibadan      1.0  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.000000
Ikoyi       3.0  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.000000
Lekki       3.0  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.000000
Gbagada     9.0  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.000000
...         ...  ...    ...        ...     ...       ...  ...           ...
Ikoyi    2214.0  NaN    NaN        NaN  4000.0  2.000000  NaN   8000.000000
Lekki    2212.0  NaN    NaN        NaN  4000.0  4.000000  NaN  16000.000000
Gbagada  2219.0  NaN    NaN        NaN  4000.0  3.666667  NaN  14666.666667
Ibadan   2216.0  NaN    NaN        NaN  4000.0  2.000000  NaN   8000.000000
Ikoyi    2217.0  NaN    NaN        NaN  4000.0  3.000000  NaN  12000.000000

                Snap
Gbagada  2004.000000
Ibadan   2005.000000
Ikoyi    2002.500000
Lekki    4005.000000
Gbagada  2003.000000
...              ...
Ikoyi    4002.000000
Lekki    4004.000000
Gbagada  4003.666667
Ibadan   4002.000000
Ikoyi    4003.000000

[1486 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     2217.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Gbagada   2221.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ikoyi     2224.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     2224.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Surulere  2222.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     4003.0
Gbagada   3002.0
Ikoyi     4003.0
Lekki     3005.0
Surulere  4002.0

[1490 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2222.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Gbagada   2229.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ibadan    2230.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ikoyi     2226.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Surulere  2227.5  NaN    NaN        NaN  3000.0       3.0  NaN  11000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4002.0
Gbagada   4002.0
Ibadan    4003.0
Ikoyi     2003.0
Surulere  3003.0

[1494 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     2226.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Surulere  2227.5  NaN    NaN        NaN  3000.0       3.0  NaN  11000.0
Ibadan    2233.5  NaN    NaN        NaN  3000.0       1.5  NaN   4000.0
Ikoyi     2233.5  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Surulere  2231.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     2003.0
Surulere  3003.0
Ibadan    3001.5
Ikoyi     3004.0
Surulere  3004.0

[1497 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.0
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.0
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.0
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.0
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.0
...               ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     2233.500000  NaN    NaN        NaN  3000.0  4.000000  NaN  12000.0
Surulere  2231.000000  NaN    NaN        NaN  3000.0  4.000000  NaN  12000.0
Gbagada   2238.000000  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.0
Lekki     2238.333333  NaN    NaN        NaN  3000.0  3.666667  NaN  11000.0
Surulere  2237.000000  NaN    NaN        NaN  4000.0  1.000000  NaN   4000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Ikoyi     3004.000000
Surulere  3004.000000
Gbagada   2004.000000
Lekki     3003.666667
Surulere  4001.000000

[1500 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2237.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Gbagada   2242.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ibadan    2244.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     2245.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Surulere  2242.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4001.0
Gbagada   4001.0
Ibadan    4001.0
Lekki     3004.0
Surulere  2003.0

[1504 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...          ...  ...    ...        ...          ...       ...  ...
Lekki     2245.0  NaN    NaN        NaN  3000.000000  4.000000  NaN
Surulere  2242.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
Gbagada   2250.0  NaN    NaN        NaN  3000.000000  3.000000  NaN
Ikoyi     2248.0  NaN    NaN        NaN  3333.333333  3.666667  NaN
Lekki     2246.0  NaN    NaN        NaN  4000.000000  4.000000  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Lekki     12000.000000  3004.0
Surulere   6000.000000  2003.0
Gbagada    9000.000000  3003.0
Ikoyi     11333.333333  3337.0
Lekki     16000.000000  4004.0

[1507 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   2255.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Ibadan    2253.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ikoyi     2252.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Lekki     2254.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Surulere  2251.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   3003.0
Ibadan    2004.0
Ikoyi     3003.0
Lekki     3002.0
Surulere  4003.0

[1512 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     2254.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Surulere  2251.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ibadan    2256.5  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Ikoyi     2259.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Lekki     2259.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3002.0
Surulere  4003.0
Ibadan    2002.5
Ikoyi     4005.0
Lekki     4003.0

[1515 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi    2259.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Lekki    2259.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Gbagada  2265.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Ibadan   2262.0  NaN    NaN        NaN  3000.0       3.0  NaN  10000.0  3003.0
Ikoyi    2263.0  NaN    NaN        NaN  2500.0       3.5  NaN   9000.0  2503.5

[1518 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     2263.0  NaN    NaN        NaN  2500.0       3.5  NaN   9000.0
Ibadan    2268.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ikoyi     2267.5  NaN    NaN        NaN  3000.0       4.5  NaN  13000.0
Lekki     2267.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Surulere  2270.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     2503.5
Ibadan    4005.0
Ikoyi     3004.5
Lekki     3001.0
Surulere  2003.0

[1522 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     2267.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Surulere  2270.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Gbagada   2273.0  NaN    NaN        NaN  3500.0       3.0  NaN  10500.0
Ibadan    2271.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ikoyi     2274.0  NaN    NaN        NaN  3000.0       2.0  NaN   5000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3001.0
Surulere  2003.0
Gbagada   3503.0
Ibadan    4002.0
Ikoyi     3002.0

[1525 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    2271.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ikoyi     2274.0  NaN    NaN        NaN  3000.0       2.0  NaN   5000.0
Gbagada   2278.5  NaN    NaN        NaN  2500.0       2.0  NaN   5500.0
Ikoyi     2278.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Surulere  2277.5  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    4002.0
Ikoyi     3002.0
Gbagada   2502.0
Ikoyi     3001.0
Surulere  4001.0

[1528 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2277.5  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Gbagada   2284.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ibadan    2285.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Lekki     2282.5  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Surulere  2281.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4001.0
Gbagada   4002.0
Ibadan    3001.0
Lekki     2004.0
Surulere  4005.0

[1532 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     2282.5  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Surulere  2281.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ibadan    2289.0  NaN    NaN        NaN  4000.0       1.5  NaN   6000.0
Lekki     2286.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  2288.0  NaN    NaN        NaN  3000.0       3.5  NaN  10500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2004.0
Surulere  4005.0
Ibadan    4001.5
Lekki     4003.0
Surulere  3003.5

[1535 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...          ...  ...    ...        ...          ...       ...  ...
Lekki     2286.0  NaN    NaN        NaN  4000.000000  3.000000  NaN
Surulere  2288.0  NaN    NaN        NaN  3000.000000  3.500000  NaN
Gbagada   2293.0  NaN    NaN        NaN  2666.666667  3.333333  NaN
Lekki     2291.0  NaN    NaN        NaN  4000.000000  4.000000  NaN
Surulere  2295.0  NaN    NaN        NaN  4000.000000  4.000000  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Lekki     12000.000000  4003.0
Surulere  10500.000000  3003.5
Gbagada    8666.666667  2670.0
Lekki     16000.000000  4004.0
Surulere  16000.000000  4004.0

[1538 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     2291.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN
Surulere  2295.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN
Gbagada   2298.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN
Ikoyi     2297.000000  NaN    NaN        NaN  3000.000000  3.000000  NaN
Lekki     2298.333333  NaN    NaN        NaN  3666.666667  2.666667  NaN

          Revenue         Snap
Gbagada    8000.0  2004.000000
Ibadan    10000.0  2005.000000
Ikoyi      5000.0  2002.500000
Lekki     20000.0  4005.000000
Gbagada    6000.0  2003.000000
...           ...          ...
Lekki     16000.0  4004.000000
Surulere  16000.0  4004.000000
Gbagada   16000.0  4004.000000
Ikoyi      9000.0  3003.000000
Lekki     10000.0  3669.333333

[1541 rows x 9 columns]
                 S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...              ...  ...    ...        ...          ...       ...  ...
Ikoyi    2297.000000  NaN    NaN        NaN  3000.000000  3.000000  NaN
Lekki    2298.333333  NaN    NaN        NaN  3666.666667  2.666667  NaN
Ibadan   2305.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Ikoyi    2303.000000  NaN    NaN        NaN  3500.000000  4.000000  NaN
Lekki    2302.000000  NaN    NaN        NaN  3000.000000  3.500000  NaN

         Revenue         Snap
Gbagada   8000.0  2004.000000
Ibadan   10000.0  2005.000000
Ikoyi     5000.0  2002.500000
Lekki    20000.0  4005.000000
Gbagada   6000.0  2003.000000
...          ...          ...
Ikoyi     9000.0  3003.000000
Lekki    10000.0  3669.333333
Ibadan    6000.0  2003.000000
Ikoyi    14500.0  3504.000000
Lekki    12000.0  3003.500000

[1544 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     2302.0  NaN    NaN        NaN  3000.0       3.5  NaN  12000.0
Ibadan    2309.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ikoyi     2306.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Lekki     2307.5  NaN    NaN        NaN  2500.0       3.5  NaN   9500.0
Surulere  2310.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3003.5
Ibadan    2001.0
Ikoyi     3004.0
Lekki     2503.5
Surulere  4005.0

[1548 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2310.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ibadan    2312.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ikoyi     2312.0  NaN    NaN        NaN  3000.0       4.5  NaN  14000.0
Lekki     2315.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  2314.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4005.0
Ibadan    4004.0
Ikoyi     3004.5
Lekki     4003.0
Surulere  3002.0

[1552 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2314.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ibadan    2316.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ikoyi     2320.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Lekki     2317.5  NaN    NaN        NaN  3500.0       3.0  NaN  10000.0
Surulere  2319.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3002.0
Ibadan    4001.0
Ikoyi     2002.0
Lekki     3503.0
Surulere  3003.0

[1556 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     2317.5  NaN    NaN        NaN  3500.0       3.0  NaN  10000.0
Surulere  2319.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Ibadan    2325.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ikoyi     2323.0  NaN    NaN        NaN  3000.0       2.0  NaN   7000.0
Surulere  2322.0  NaN    NaN        NaN  3000.0       2.0  NaN   7000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3503.0
Surulere  3003.0
Ibadan    4004.0
Ikoyi     3002.0
Surulere  3002.0

[1559 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     2323.0  NaN    NaN        NaN  3000.0       2.0  NaN   7000.0
Surulere  2322.0  NaN    NaN        NaN  3000.0       2.0  NaN   7000.0
Gbagada   2327.0  NaN    NaN        NaN  3000.0       1.5  NaN   5000.0
Ikoyi     2329.5  NaN    NaN        NaN  2500.0       3.0  NaN   8500.0
Surulere  2327.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3002.0
Surulere  3002.0
Gbagada   3001.5
Ikoyi     2503.0
Surulere  2002.0

[1562 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2327.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Gbagada   2335.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ibadan    2333.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi     2334.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Surulere  2331.5  NaN    NaN        NaN  3000.0       3.5  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2002.0
Gbagada   4005.0
Ibadan    2005.0
Ikoyi     4001.0
Surulere  3003.5

[1566 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     2334.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Surulere  2331.5  NaN    NaN        NaN  3000.0       3.5  NaN  12000.0
Gbagada   2337.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Ikoyi     2338.5  NaN    NaN        NaN  4000.0       1.5  NaN   6000.0
Surulere  2338.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     4001.0
Surulere  3003.5
Gbagada   3003.0
Ikoyi     4001.5
Surulere  4002.0

[1569 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...               ...  ...    ...        ...          ...       ...  ...
Gbagada   2337.000000  NaN    NaN        NaN  3000.000000       3.0  NaN
Ikoyi     2338.500000  NaN    NaN        NaN  4000.000000       1.5  NaN
Surulere  2338.000000  NaN    NaN        NaN  4000.000000       2.0  NaN
Gbagada   2342.333333  NaN    NaN        NaN  2666.666667       3.0  NaN
Lekki     2344.000000  NaN    NaN        NaN  2500.000000       1.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Gbagada    9000.000000  3003.000000
Ikoyi      6000.000000  4001.500000
Surulere   8000.000000  4002.000000
Gbagada    8666.666667  2669.666667
Lekki      2500.000000  2501.000000

[1571 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...               ...  ...    ...        ...          ...       ...  ...
Gbagada   2342.333333  NaN    NaN        NaN  2666.666667       3.0  NaN
Lekki     2344.000000  NaN    NaN        NaN  2500.000000       1.0  NaN
Gbagada   2347.000000  NaN    NaN        NaN  3500.000000       4.0  NaN
Ikoyi     2349.500000  NaN    NaN        NaN  3500.000000       3.0  NaN
Surulere  2347.000000  NaN    NaN        NaN  3000.000000       1.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Gbagada    8666.666667  2669.666667
Lekki      2500.000000  2501.000000
Gbagada   14500.000000  3504.000000
Ikoyi     10000.000000  3503.000000
Surulere   3000.000000  3001.000000

[1574 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     2349.500000  NaN    NaN        NaN  3500.000000  3.000000  NaN
Surulere  2347.000000  NaN    NaN        NaN  3000.000000  1.000000  NaN
Gbagada   2352.666667  NaN    NaN        NaN  3666.666667  2.666667  NaN
Ibadan    2353.000000  NaN    NaN        NaN  4000.000000  1.000000  NaN
Ikoyi     2354.000000  NaN    NaN        NaN  4000.000000  1.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi     10000.000000  3503.000000
Surulere   3000.000000  3001.000000
Gbagada    9666.666667  3669.333333
Ibadan     4000.000000  4001.000000
Ikoyi      4000.000000  4001.000000

[1577 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     2354.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ibadan    2358.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ikoyi     2356.5  NaN    NaN        NaN  2000.0       3.5  NaN   7000.0
Lekki     2360.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Surulere  2359.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     4001.0
Ibadan    4005.0
Ikoyi     2003.5
Lekki     2004.0
Surulere  3001.0

[1581 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2359.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Gbagada   2365.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ikoyi     2362.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Lekki     2364.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Surulere  2362.0  NaN    NaN        NaN  3000.0       3.5  NaN  11000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3001.0
Gbagada   2003.0
Ikoyi     4002.0
Lekki     4004.0
Surulere  3003.5

[1585 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2362.0  NaN    NaN        NaN  3000.0       3.5  NaN  11000.0
Ibadan    2368.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ikoyi     2368.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Lekki     2369.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  2367.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3003.5
Ibadan    3005.0
Ikoyi     4002.0
Lekki     4003.0
Surulere  3002.0

[1589 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   2371.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ibadan    2374.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ikoyi     2372.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Lekki     2375.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Surulere  2373.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   2001.0
Ibadan    4003.0
Ikoyi     2002.0
Lekki     4001.0
Surulere  2002.0

[1594 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2373.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Gbagada   2376.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ikoyi     2377.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Lekki     2380.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Surulere  2378.5  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2002.0
Gbagada   3005.0
Ikoyi     2004.0
Lekki     4004.0
Surulere  3001.0

[1598 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...          ...  ...    ...        ...          ...       ...  ...
Lekki     2380.0  NaN    NaN        NaN  4000.000000  4.000000  NaN
Surulere  2378.5  NaN    NaN        NaN  3000.000000  1.000000  NaN
Gbagada   2385.0  NaN    NaN        NaN  2000.000000  2.000000  NaN
Ibadan    2383.0  NaN    NaN        NaN  2666.666667  2.666667  NaN
Lekki     2381.0  NaN    NaN        NaN  3000.000000  3.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki     16000.000000  4004.000000
Surulere   3000.000000  3001.000000
Gbagada    4000.000000  2002.000000
Ibadan     6666.666667  2669.333333
Lekki      9000.000000  3003.000000

[1601 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     2381.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Gbagada   2389.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ikoyi     2387.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Lekki     2387.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Surulere  2390.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3003.0
Gbagada   2001.0
Ikoyi     2004.0
Lekki     3002.0
Surulere  4005.0

[1605 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...               ...  ...    ...        ...     ...       ...  ...
Ikoyi     2387.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Lekki     2387.000000  NaN    NaN        NaN  3000.0  2.000000  NaN
Surulere  2390.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Ibadan    2392.666667  NaN    NaN        NaN  4000.0  3.666667  NaN
Lekki     2393.500000  NaN    NaN        NaN  3500.0  2.500000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi      8000.000000  2004.000000
Lekki      6000.000000  3002.000000
Surulere  20000.000000  4005.000000
Ibadan    14666.666667  4003.666667
Lekki      8000.000000  3502.500000

[1607 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ibadan    2392.666667  NaN    NaN        NaN  4000.000000  3.666667  NaN
Lekki     2393.500000  NaN    NaN        NaN  3500.000000  2.500000  NaN
Gbagada   2398.000000  NaN    NaN        NaN  3000.000000  3.000000  NaN
Ibadan    2396.000000  NaN    NaN        NaN  3000.000000  4.000000  NaN
Surulere  2398.666667  NaN    NaN        NaN  2333.333333  4.666667  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ibadan    14666.666667  4003.666667
Lekki      8000.000000  3502.500000
Gbagada    9000.000000  3003.000000
Ibadan    12000.000000  3004.000000
Surulere  10666.666667  2338.000000

[1610 rows x 9 columns]

                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ibadan    2396.000000  NaN    NaN        NaN  3000.000000  4.000000  NaN
Surulere  2398.666667  NaN    NaN        NaN  2333.333333  4.666667  NaN
Gbagada   2401.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN
Lekki     2403.000000  NaN    NaN        NaN  2500.000000  3.500000  NaN
Surulere  2404.000000  NaN    NaN        NaN  3500.000000  1.500000  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Ibadan    12000.000000  3004.0
Surulere  10666.666667  2338.0
Gbagada   16000.000000  4004.0
Lekki      8000.000000  2503.5
Surulere   5500.000000  3501.5

[1613 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2404.0  NaN    NaN        NaN  3500.0       1.5  NaN   5500.0
Gbagada   2408.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ikoyi     2406.5  NaN    NaN        NaN  2500.0       3.5  NaN   9500.0
Lekki     2410.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  2409.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3501.5
Gbagada   4004.0
Ikoyi     2503.5
Lekki     4002.0
Surulere  4003.0

[1617 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2409.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ibadan    2415.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ikoyi     2414.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Lekki     2412.5  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  2411.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4003.0
Ibadan    3004.0
Ikoyi     4002.0
Lekki     4002.0
Surulere  4004.0

[1621 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     2414.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Lekki     2412.5  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  2411.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Gbagada   2417.5  NaN    NaN        NaN  3250.0       4.0  NaN  13000.0
Ikoyi     2420.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     4002.0
Lekki     4002.0
Surulere  4004.0
Gbagada   3254.0
Ikoyi     3002.0

[1623 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Gbagada  2417.5  NaN    NaN        NaN  3250.0       4.0  NaN  13000.0  3254.0
Ikoyi    2420.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0  3002.0
Gbagada  2422.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Ikoyi    2423.0  NaN    NaN        NaN  3000.0       3.5  NaN  12000.0  3003.5
Lekki    2423.5  NaN    NaN        NaN  3000.0       2.5  NaN   7000.0  3002.5

[1626 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     2423.5  NaN    NaN        NaN  3000.0       2.5  NaN   7000.0
Gbagada   2430.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ibadan    2428.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ikoyi     2427.5  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Surulere  2427.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3002.5
Gbagada   4005.0
Ibadan    4003.0
Ikoyi     4004.0
Surulere  3005.0

[1630 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.000000  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.000000  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.000000  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.000000  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...               ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     2427.500000  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Surulere  2427.000000  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Gbagada   2433.000000  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ibadan    2433.666667  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  2431.000000  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     4004.0
Surulere  3005.0
Gbagada   3004.0
Ibadan    4003.0
Surulere  2001.0

[1633 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.000000  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.000000  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.000000  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.000000  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...               ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    2433.666667  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  2431.000000  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ibadan    2437.000000  NaN    NaN        NaN  3500.0       4.5  NaN  16000.0
Lekki     2437.000000  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Surulere  2439.500000  NaN    NaN        NaN  3500.0       3.0  NaN   9500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    4003.0
Surulere  2001.0
Ibadan    3504.5
Lekki     2004.0
Surulere  3503.0

[1636 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    2437.0  NaN    NaN        NaN  3500.0       4.5  NaN  16000.0
Lekki     2437.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Surulere  2439.5  NaN    NaN        NaN  3500.0       3.0  NaN   9500.0
Ikoyi     2442.5  NaN    NaN        NaN  3250.0       3.0  NaN   9500.0
Lekki     2445.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    3504.5
Lekki     2004.0
Surulere  3503.0
Ikoyi     3253.0
Lekki     3004.0

[1638 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2439.5  NaN    NaN        NaN  3500.0       3.0  NaN   9500.0
Ikoyi     2442.5  NaN    NaN        NaN  3250.0       3.0  NaN   9500.0
Lekki     2445.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ibadan    2448.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     2448.0  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3503.0
Ikoyi     3253.0
Lekki     3004.0
Ibadan    4001.0
Lekki     4003.5

[1640 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     2448.0  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0
Ibadan    2453.5  NaN    NaN        NaN  3500.0       5.0  NaN  17500.0
Ikoyi     2454.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Lekki     2453.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  2451.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4003.5
Ibadan    3505.0
Ikoyi     3005.0
Lekki     4002.0
Surulere  2002.0

[1644 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2451.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Gbagada   2457.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ibadan    2458.5  NaN    NaN        NaN  4000.0       4.5  NaN  18000.0
Ikoyi     2456.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Lekki     2460.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2002.0
Gbagada   4005.0
Ibadan    4004.5
Ikoyi     2004.0
Lekki     3003.0

[1648 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki    2460.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Gbagada  2462.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Ibadan   2464.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0
Ikoyi    2464.0  NaN    NaN        NaN  3000.0       3.5  NaN  12000.0  3003.5
Lekki    2461.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0

[1652 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki    2461.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0
Gbagada  2468.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Ibadan   2468.0  NaN    NaN        NaN  3500.0       2.0  NaN   7000.0  3502.0
Ikoyi    2469.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Lekki    2467.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0

[1656 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     2467.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Gbagada   2473.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ibadan    2472.5  NaN    NaN        NaN  3500.0       1.0  NaN   3500.0
Ikoyi     2472.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Surulere  2475.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4003.0
Gbagada   2005.0
Ibadan    3501.0
Ikoyi     3005.0
Surulere  4003.0

[1660 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000       3.0  NaN
...          ...  ...    ...        ...          ...       ...  ...
Ikoyi     2472.0  NaN    NaN        NaN  3000.000000       5.0  NaN
Surulere  2475.0  NaN    NaN        NaN  4000.000000       3.0  NaN
Ikoyi     2476.0  NaN    NaN        NaN  2000.000000       1.0  NaN
Lekki     2477.0  NaN    NaN        NaN  4000.000000       1.0  NaN
Surulere  2479.0  NaN    NaN        NaN  3666.666667       2.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi     15000.000000  3005.000000
Surulere  12000.000000  4003.000000
Ikoyi      2000.000000  2001.000000
Lekki      4000.000000  4001.000000
Surulere   7333.333333  3668.666667

[1663 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     2477.000000  NaN    NaN        NaN  4000.000000       1.0  NaN
Surulere  2479.000000  NaN    NaN        NaN  3666.666667       2.0  NaN
Ibadan    2485.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi     2483.000000  NaN    NaN        NaN  4000.000000       3.0  NaN
Surulere  2482.333333  NaN    NaN        NaN  3333.333333       5.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      4000.000000  4001.000000
Surulere   7333.333333  3668.666667
Ibadan    10000.000000  2005.000000
Ikoyi     12000.000000  4003.000000
Surulere  16666.666667  3338.333333

[1666 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     2483.000000  NaN    NaN        NaN  4000.000000       3.0  NaN
Surulere  2482.333333  NaN    NaN        NaN  3333.333333       5.0  NaN
Ibadan    2487.000000  NaN    NaN        NaN  4000.000000       2.0  NaN
Lekki     2490.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Surulere  2489.000000  NaN    NaN        NaN  3000.000000       2.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi     12000.000000  4003.000000
Surulere  16666.666667  3338.333333
Ibadan     8000.000000  4002.000000
Lekki     20000.000000  4005.000000
Surulere   6000.000000  3002.000000

[1669 rows x 9 columns]

                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0       3.0  NaN
...               ...  ...    ...        ...     ...       ...  ...
Lekki     2490.000000  NaN    NaN        NaN  4000.0       5.0  NaN
Surulere  2489.000000  NaN    NaN        NaN  3000.0       2.0  NaN
Ibadan    2493.333333  NaN    NaN        NaN  3000.0       2.0  NaN
Ikoyi     2494.000000  NaN    NaN        NaN  4000.0       4.0  NaN
Surulere  2491.000000  NaN    NaN        NaN  4000.0       1.0  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Lekki     20000.000000  4005.0
Surulere   6000.000000  3002.0
Ibadan     6666.666667  3002.0
Ikoyi     16000.000000  4004.0
Surulere   4000.000000  4001.0

[1672 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ibadan    2493.333333  NaN    NaN        NaN  3000.000000  2.000000  NaN
Ikoyi     2494.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN
Surulere  2491.000000  NaN    NaN        NaN  4000.000000  1.000000  NaN
Ikoyi     2499.000000  NaN    NaN        NaN  2666.666667  3.666667  NaN
Lekki     2496.500000  NaN    NaN        NaN  3500.000000  1.500000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ibadan     6666.666667  3002.000000
Ikoyi     16000.000000  4004.000000
Surulere   4000.000000  4001.000000
Ikoyi     10000.000000  2670.333333
Lekki      5500.000000  3501.500000

[1674 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Surulere  2491.000000  NaN    NaN        NaN  4000.000000  1.000000  NaN
Ikoyi     2499.000000  NaN    NaN        NaN  2666.666667  3.666667  NaN
Lekki     2496.500000  NaN    NaN        NaN  3500.000000  1.500000  NaN
Gbagada   2504.000000  NaN    NaN        NaN  3000.000000  3.500000  NaN
Ikoyi     2502.333333  NaN    NaN        NaN  2333.333333  3.333333  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Surulere   4000.000000  4001.000000
Ikoyi     10000.000000  2670.333333
Lekki      5500.000000  3501.500000
Gbagada   10000.000000  3003.500000
Ikoyi      7333.333333  2336.666667

[1676 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Gbagada   2504.000000  NaN    NaN        NaN  3000.000000  3.500000  NaN
Ikoyi     2502.333333  NaN    NaN        NaN  2333.333333  3.333333  NaN
Ikoyi     2509.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Lekki     2506.000000  NaN    NaN        NaN  3000.000000  5.000000  NaN
Surulere  2507.000000  NaN    NaN        NaN  4000.000000  3.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Gbagada   10000.000000  3003.500000
Ikoyi      7333.333333  2336.666667
Ikoyi      6000.000000  2003.000000
Lekki     15000.000000  3005.000000
Surulere  12000.000000  4003.000000

[1679 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2507.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Gbagada   2513.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ibadan    2514.5  NaN    NaN        NaN  3500.0       4.0  NaN  13500.0
Ikoyi     2511.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Lekki     2512.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4003.0
Gbagada   3002.0
Ibadan    3504.0
Ikoyi     2001.0
Lekki     3002.0

[1683 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     2512.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Gbagada   2517.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ibadan    2520.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ikoyi     2518.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  2517.5  NaN    NaN        NaN  3500.0       3.0  NaN  10500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3002.0
Gbagada   2001.0
Ibadan    2004.0
Ikoyi     4005.0
Surulere  3503.0

[1687 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     2518.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  2517.5  NaN    NaN        NaN  3500.0       3.0  NaN  10500.0
Gbagada   2523.0  NaN    NaN        NaN  3500.0       4.5  NaN  16000.0
Ibadan    2525.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  2522.0  NaN    NaN        NaN  3500.0       3.0  NaN  11500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     4005.0
Surulere  3503.0
Gbagada   3504.5
Ibadan    4003.0
Surulere  3503.0

[1690 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    2525.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  2522.0  NaN    NaN        NaN  3500.0       3.0  NaN  11500.0
Gbagada   2527.0  NaN    NaN        NaN  2500.0       5.0  NaN  12500.0
Ikoyi     2528.5  NaN    NaN        NaN  2500.0       3.0  NaN   8500.0
Lekki     2529.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    4003.0
Surulere  3503.0
Gbagada   2505.0
Ikoyi     2503.0
Lekki     2003.0

[1693 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi    2528.5  NaN    NaN        NaN  2500.0       3.0  NaN   8500.0  2503.0
Lekki    2529.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Ibadan   2531.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Ikoyi    2533.5  NaN    NaN        NaN  3000.0       3.5  NaN  10500.0  3003.5
Lekki    2533.5  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0  3002.0

[1696 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     2533.5  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ibadan    2539.5  NaN    NaN        NaN  3500.0       2.0  NaN   6500.0
Ikoyi     2537.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Lekki     2538.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Surulere  2536.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3002.0
Ibadan    3502.0
Ikoyi     2004.0
Lekki     3001.0
Surulere  4002.0

[1700 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     2538.000000  NaN    NaN        NaN  3000.000000       1.0  NaN
Surulere  2536.000000  NaN    NaN        NaN  4000.000000       2.0  NaN
Gbagada   2543.000000  NaN    NaN        NaN  4000.000000       2.0  NaN
Ikoyi     2543.333333  NaN    NaN        NaN  3333.333333       3.0  NaN
Lekki     2542.000000  NaN    NaN        NaN  3000.000000       3.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      3000.000000  3001.000000
Surulere   8000.000000  4002.000000
Gbagada    8000.000000  4002.000000
Ikoyi     10333.333333  3336.333333
Lekki      9000.000000  3003.000000

[1703 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki    2542.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Gbagada  2547.5  NaN    NaN        NaN  2500.0       2.0  NaN   5000.0  2502.0
Ibadan   2546.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Ikoyi    2549.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0  3002.0
Lekki    2550.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0

[1707 rows x 9 columns]
            S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...         ...  ...    ...        ...          ...       ...  ...
Ikoyi    2549.0  NaN    NaN        NaN  3000.000000  2.000000  NaN
Lekki    2550.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada  2552.0  NaN    NaN        NaN  4000.000000  2.000000  NaN
Ibadan   2554.0  NaN    NaN        NaN  3666.666667  3.333333  NaN
Ikoyi    2551.0  NaN    NaN        NaN  3000.000000  3.000000  NaN

              Revenue    Snap
Gbagada   8000.000000  2004.0
Ibadan   10000.000000  2005.0
Ikoyi     5000.000000  2002.5
Lekki    20000.000000  4005.0
Gbagada   6000.000000  2003.0
...               ...     ...
Ikoyi     6000.000000  3002.0
Lekki    20000.000000  4005.0
Gbagada   8000.000000  4002.0
Ibadan   12333.333333  3670.0
Ikoyi     9000.000000  3003.0

[1710 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...          ...  ...    ...        ...          ...       ...  ...
Ibadan    2554.0  NaN    NaN        NaN  3666.666667  3.333333  NaN
Ikoyi     2551.0  NaN    NaN        NaN  3000.000000  3.000000  NaN
Ikoyi     2557.5  NaN    NaN        NaN  3000.000000  4.000000  NaN
Lekki     2557.5  NaN    NaN        NaN  3500.000000  4.000000  NaN
Surulere  2560.0  NaN    NaN        NaN  2000.000000  2.000000  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Ibadan    12333.333333  3670.0
Ikoyi      9000.000000  3003.0
Ikoyi     12000.000000  3004.0
Lekki     13500.000000  3504.0
Surulere   4000.000000  2002.0

[1713 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   2561.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ibadan    2565.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ikoyi     2564.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Lekki     2562.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  2563.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   4001.0
Ibadan    4002.0
Ikoyi     3002.0
Lekki     4003.0
Surulere  4001.0

[1718 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...               ...  ...    ...        ...     ...       ...  ...
Lekki     2562.000000  NaN    NaN        NaN  4000.0  3.000000  NaN
Surulere  2563.000000  NaN    NaN        NaN  4000.0  1.000000  NaN
Gbagada   2567.000000  NaN    NaN        NaN  4000.0  3.000000  NaN
Ikoyi     2568.000000  NaN    NaN        NaN  4000.0  1.000000  NaN
Surulere  2568.333333  NaN    NaN        NaN  3000.0  2.666667  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki     12000.000000  4003.000000
Surulere   4000.000000  4001.000000
Gbagada   12000.000000  4003.000000
Ikoyi      4000.000000  4001.000000
Surulere   8333.333333  3002.666667

[1721 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...               ...  ...    ...        ...     ...       ...  ...
Gbagada   2567.000000  NaN    NaN        NaN  4000.0  3.000000  NaN
Ikoyi     2568.000000  NaN    NaN        NaN  4000.0  1.000000  NaN
Surulere  2568.333333  NaN    NaN        NaN  3000.0  2.666667  NaN
Ibadan    2572.666667  NaN    NaN        NaN  3000.0  2.333333  NaN
Ikoyi     2573.500000  NaN    NaN        NaN  4000.0  5.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Gbagada   12000.000000  4003.000000
Ikoyi      4000.000000  4001.000000
Surulere   8333.333333  3002.666667
Ibadan     7000.000000  3002.333333
Ikoyi     20000.000000  4005.000000

[1723 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     2573.5  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ibadan    2579.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ikoyi     2577.5  NaN    NaN        NaN  3000.0       3.5  NaN  10500.0
Lekki     2580.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  2576.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     4005.0
Ibadan    2003.0
Ikoyi     3003.5
Lekki     4003.0
Surulere  2004.0

[1727 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     2580.000000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Surulere  2576.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Gbagada   2583.333333  NaN    NaN        NaN  3666.666667  3.333333  NaN
Lekki     2582.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Surulere  2583.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Lekki     12000.000000  4003.0
Surulere   8000.000000  2004.0
Gbagada   11666.666667  3670.0
Lekki      8000.000000  2004.0
Surulere  16000.000000  4004.0

[1730 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
...          ...  ...    ...        ...          ...       ...  ...      ...
Lekki     2582.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0
Surulere  2583.0  NaN    NaN        NaN  4000.000000  4.000000  NaN  16000.0
Ibadan    2587.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
Ikoyi     2589.0  NaN    NaN        NaN  2000.000000  2.000000  NaN   4000.0
Surulere  2588.0  NaN    NaN        NaN  2666.666667  3.666667  NaN   8000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Lekki     2004.000000
Surulere  4004.000000
Ibadan    2003.000000
Ikoyi     2002.000000
Surulere  2670.333333

[1733 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
...          ...  ...    ...        ...          ...       ...  ...      ...
Surulere  2588.0  NaN    NaN        NaN  2666.666667  3.666667  NaN   8000.0
Gbagada   2591.0  NaN    NaN        NaN  4000.000000  3.000000  NaN  12000.0
Ikoyi     2595.0  NaN    NaN        NaN  4000.000000  3.000000  NaN  12000.0
Lekki     2592.0  NaN    NaN        NaN  3000.000000  4.000000  NaN  12000.0
Surulere  2593.5  NaN    NaN        NaN  2500.000000  4.000000  NaN   9500.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Surulere  2670.333333
Gbagada   4003.000000
Ikoyi     4003.000000
Lekki     3004.000000
Surulere  2504.000000

[1737 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     2592.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Surulere  2593.5  NaN    NaN        NaN  2500.0       4.0  NaN   9500.0
Ibadan    2598.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi     2598.0  NaN    NaN        NaN  2500.0       3.0  NaN   6500.0
Surulere  2598.0  NaN    NaN        NaN  3000.0       3.0  NaN   7000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3004.0
Surulere  2504.0
Ibadan    2005.0
Ikoyi     2503.0
Surulere  3003.0

[1740 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     2598.0  NaN    NaN        NaN  2500.0       3.0  NaN   6500.0
Surulere  2598.0  NaN    NaN        NaN  3000.0       3.0  NaN   7000.0
Ikoyi     2604.5  NaN    NaN        NaN  4000.0       2.5  NaN  10000.0
Lekki     2602.5  NaN    NaN        NaN  3500.0       4.0  NaN  14500.0
Surulere  2601.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     2503.0
Surulere  3003.0
Ikoyi     4002.5
Lekki     3504.0
Surulere  4001.0

[1743 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2601.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Gbagada   2608.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ibadan    2608.5  NaN    NaN        NaN  2000.0       3.5  NaN   7000.0
Lekki     2609.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Surulere  2606.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4001.0
Gbagada   3001.0
Ibadan    2003.5
Lekki     3001.0
Surulere  2002.0

[1747 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   2611.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ibadan    2612.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ikoyi     2614.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     2615.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  2613.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   2003.0
Ibadan    3004.0
Ikoyi     4001.0
Lekki     4002.0
Surulere  4002.0

[1752 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2613.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Gbagada   2620.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ibadan    2617.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ikoyi     2617.5  NaN    NaN        NaN  3000.0       2.5  NaN   7500.0
Surulere  2618.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4002.0
Gbagada   3001.0
Ibadan    4005.0
Ikoyi     3002.5
Surulere  4004.0

[1756 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     2617.5  NaN    NaN        NaN  3000.0       2.5  NaN   7500.0
Surulere  2618.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Gbagada   2624.5  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Lekki     2622.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Surulere  2622.0  NaN    NaN        NaN  3000.0       2.5  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3002.5
Surulere  4004.0
Gbagada   3002.0
Lekki     2002.0
Surulere  3002.5

[1759 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     2622.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Surulere  2622.0  NaN    NaN        NaN  3000.0       2.5  NaN   6000.0
Gbagada   2629.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ibadan    2626.5  NaN    NaN        NaN  3000.0       4.5  NaN  13000.0
Lekki     2629.0  NaN    NaN        NaN  3000.0       4.5  NaN  14000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2002.0
Surulere  3002.5
Gbagada   3005.0
Ibadan    3004.5
Lekki     3004.5

[1762 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    2626.5  NaN    NaN        NaN  3000.0       4.5  NaN  13000.0
Lekki     2629.0  NaN    NaN        NaN  3000.0       4.5  NaN  14000.0
Gbagada   2634.0  NaN    NaN        NaN  3500.0       5.0  NaN  17500.0
Lekki     2632.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Surulere  2632.5  NaN    NaN        NaN  3500.0       4.0  NaN  13500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    3004.5
Lekki     3004.5
Gbagada   3505.0
Lekki     3002.0
Surulere  3504.0

[1765 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   2639.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Ibadan    2637.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ikoyi     2636.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Lekki     2638.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  2640.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   3003.0
Ibadan    3005.0
Ikoyi     4002.0
Lekki     4005.0
Surulere  4004.0

[1770 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   2643.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ibadan    2644.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ikoyi     2641.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Lekki     2642.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Surulere  2645.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   4005.0
Ibadan    2004.0
Ikoyi     3004.0
Lekki     4001.0
Surulere  2003.0

[1775 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
...          ...  ...    ...        ...          ...       ...  ...      ...
Lekki     2642.0  NaN    NaN        NaN  4000.000000  1.000000  NaN   4000.0
Surulere  2645.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
Gbagada   2648.0  NaN    NaN        NaN  2666.666667  2.666667  NaN   6000.0
Ikoyi     2650.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0
Surulere  2646.0  NaN    NaN        NaN  3000.000000  2.000000  NaN   6000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Lekki     4001.000000
Surulere  2003.000000
Gbagada   2669.333333
Ikoyi     2004.000000
Surulere  3002.000000

[1778 rows x 9 columns]

                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0       3.0  NaN
...               ...  ...    ...        ...     ...       ...  ...
Ikoyi     2650.000000  NaN    NaN        NaN  2000.0       4.0  NaN
Surulere  2646.000000  NaN    NaN        NaN  3000.0       2.0  NaN
Gbagada   2654.000000  NaN    NaN        NaN  2000.0       2.0  NaN
Ibadan    2651.000000  NaN    NaN        NaN  2000.0       1.0  NaN
Lekki     2653.333333  NaN    NaN        NaN  3000.0       4.0  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Ikoyi      8000.000000  2004.0
Surulere   6000.000000  3002.0
Gbagada    4000.000000  2002.0
Ibadan     2000.000000  2001.0
Lekki     12333.333333  3004.0

[1781 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0       3.0  NaN
...               ...  ...    ...        ...     ...       ...  ...
Ibadan    2651.000000  NaN    NaN        NaN  2000.0       1.0  NaN
Lekki     2653.333333  NaN    NaN        NaN  3000.0       4.0  NaN
Gbagada   2657.000000  NaN    NaN        NaN  4000.0       2.5  NaN
Lekki     2660.000000  NaN    NaN        NaN  2000.0       1.0  NaN
Surulere  2658.000000  NaN    NaN        NaN  3500.0       2.0  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Ibadan     2000.000000  2001.0
Lekki     12333.333333  3004.0
Gbagada   10000.000000  4002.5
Lekki      2000.000000  2001.0
Surulere   6500.000000  3502.0

[1784 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.0
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.0
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.0
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.0
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.0
...               ...  ...    ...        ...     ...       ...  ...      ...
Lekki     2660.000000  NaN    NaN        NaN  2000.0  1.000000  NaN   2000.0
Surulere  2658.000000  NaN    NaN        NaN  3500.0  2.000000  NaN   6500.0
Gbagada   2663.000000  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.0
Lekki     2662.000000  NaN    NaN        NaN  4000.0  4.000000  NaN  16000.0
Surulere  2663.333333  NaN    NaN        NaN  3000.0  2.666667  NaN   9000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Lekki     2001.000000
Surulere  3502.000000
Gbagada   2003.000000
Lekki     4004.000000
Surulere  3002.666667

[1787 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.0
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.0
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.0
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.0
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.0
...               ...  ...    ...        ...     ...       ...  ...      ...
Lekki     2662.000000  NaN    NaN        NaN  4000.0  4.000000  NaN  16000.0
Surulere  2663.333333  NaN    NaN        NaN  3000.0  2.666667  NaN   9000.0
Gbagada   2668.500000  NaN    NaN        NaN  3500.0  2.500000  NaN   9500.0
Ikoyi     2666.000000  NaN    NaN        NaN  4000.0  2.000000  NaN   8000.0
Surulere  2668.500000  NaN    NaN        NaN  4000.0  1.000000  NaN   4000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Lekki     4004.000000
Surulere  3002.666667
Gbagada   3502.500000
Ikoyi     4002.000000
Surulere  4001.000000

[1790 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2668.5  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Gbagada   2674.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ibadan    2673.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ikoyi     2673.5  NaN    NaN        NaN  2000.0       3.5  NaN   7000.0
Lekki     2671.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4001.0
Gbagada   4001.0
Ibadan    3001.0
Ikoyi     2003.5
Lekki     3003.0

[1794 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     2673.5  NaN    NaN        NaN  2000.0       3.5  NaN   7000.0
Lekki     2671.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Ikoyi     2678.5  NaN    NaN        NaN  3000.0       3.0  NaN  11000.0
Lekki     2677.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Surulere  2679.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     2003.5
Lekki     3003.0
Ikoyi     3003.0
Lekki     4004.0
Surulere  3001.0

[1797 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
...          ...  ...    ...        ...          ...       ...  ...      ...
Lekki     2677.0  NaN    NaN        NaN  4000.000000  4.000000  NaN  16000.0
Surulere  2679.0  NaN    NaN        NaN  3000.000000  1.000000  NaN   3000.0
Gbagada   2684.0  NaN    NaN        NaN  4000.000000  1.000000  NaN   4000.0
Ibadan    2683.0  NaN    NaN        NaN  2666.666667  3.333333  NaN  10000.0
Ikoyi     2682.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4004.0
Surulere  3001.0
Gbagada   4001.0
Ibadan    2670.0
Ikoyi     2005.0

[1800 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...          ...  ...    ...        ...          ...       ...  ...
Ibadan    2683.0  NaN    NaN        NaN  2666.666667  3.333333  NaN
Ikoyi     2682.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Gbagada   2687.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Lekki     2686.0  NaN    NaN        NaN  3000.000000  1.000000  NaN
Surulere  2689.0  NaN    NaN        NaN  3666.666667  3.666667  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ibadan    10000.000000  2670.000000
Ikoyi     10000.000000  2005.000000
Gbagada    8000.000000  2004.000000
Lekki      3000.000000  3001.000000
Surulere  13666.666667  3670.333333

[1803 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Gbagada   2687.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Lekki     2686.000000  NaN    NaN        NaN  3000.000000  1.000000  NaN
Surulere  2689.000000  NaN    NaN        NaN  3666.666667  3.666667  NaN
Ibadan    2693.333333  NaN    NaN        NaN  2666.666667  2.666667  NaN
Lekki     2692.500000  NaN    NaN        NaN  3500.000000  2.500000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Gbagada    8000.000000  2004.000000
Lekki      3000.000000  3001.000000
Surulere  13666.666667  3670.333333
Ibadan     6000.000000  2669.333333
Lekki      9000.000000  3502.500000

[1805 rows x 9 columns]

                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ibadan    2693.333333  NaN    NaN        NaN  2666.666667  2.666667  NaN
Lekki     2692.500000  NaN    NaN        NaN  3500.000000  2.500000  NaN
Ikoyi     2699.000000  NaN    NaN        NaN  3000.000000  4.000000  NaN
Lekki     2699.000000  NaN    NaN        NaN  3000.000000  2.500000  NaN
Surulere  2696.500000  NaN    NaN        NaN  3000.000000  3.500000  NaN

          Revenue         Snap
Gbagada    8000.0  2004.000000
Ibadan    10000.0  2005.000000
Ikoyi      5000.0  2002.500000
Lekki     20000.0  4005.000000
Gbagada    6000.0  2003.000000
...           ...          ...
Ibadan     6000.0  2669.333333
Lekki      9000.0  3502.500000
Ikoyi     12000.0  3004.000000
Lekki      7000.0  3002.500000
Surulere   9000.0  3003.500000

[1808 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...               ...  ...    ...        ...     ...       ...  ...
Lekki     2699.000000  NaN    NaN        NaN  3000.0  2.500000  NaN
Surulere  2696.500000  NaN    NaN        NaN  3000.0  3.500000  NaN
Gbagada   2701.000000  NaN    NaN        NaN  3000.0  4.000000  NaN
Ibadan    2703.333333  NaN    NaN        NaN  4000.0  2.333333  NaN
Surulere  2704.000000  NaN    NaN        NaN  3000.0  1.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      7000.000000  3002.500000
Surulere   9000.000000  3003.500000
Gbagada   12000.000000  3004.000000
Ibadan     9333.333333  4002.333333
Surulere   3000.000000  3001.000000

[1811 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2704.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Gbagada   2710.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ikoyi     2706.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Lekki     2708.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Surulere  2708.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3001.0
Gbagada   3002.0
Ikoyi     4004.0
Lekki     2004.0
Surulere  4003.0

[1815 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2708.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Gbagada   2713.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Ikoyi     2712.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Lekki     2711.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Surulere  2714.5  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4003.0
Gbagada   2002.0
Ikoyi     2005.0
Lekki     2001.0
Surulere  3003.0

[1819 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     2711.000000  NaN    NaN        NaN  2000.000000  1.000000  NaN
Surulere  2714.500000  NaN    NaN        NaN  3000.000000  3.000000  NaN
Gbagada   2718.333333  NaN    NaN        NaN  3333.333333  2.666667  NaN
Ibadan    2718.000000  NaN    NaN        NaN  3000.000000  5.000000  NaN
Ikoyi     2717.000000  NaN    NaN        NaN  2000.000000  2.000000  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Lekki      2000.000000  2001.0
Surulere   9000.000000  3003.0
Gbagada    9333.333333  3336.0
Ibadan    15000.000000  3005.0
Ikoyi      4000.000000  2002.0

[1822 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    2718.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ikoyi     2717.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Gbagada   2722.5  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Lekki     2723.5  NaN    NaN        NaN  3500.0       2.0  NaN   6500.0
Surulere  2723.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    3005.0
Ikoyi     2002.0
Gbagada   4004.0
Lekki     3502.0
Surulere  4003.0

[1825 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2723.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Gbagada   2730.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ibadan    2726.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ikoyi     2729.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Lekki     2727.5  NaN    NaN        NaN  3500.0       3.0  NaN  11000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4003.0
Gbagada   4004.0
Ibadan    3001.0
Ikoyi     3003.0
Lekki     3503.0

[1829 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki    2727.5  NaN    NaN        NaN  3500.0       3.0  NaN  11000.0  3503.0
Gbagada  2734.0  NaN    NaN        NaN  3500.0       2.5  NaN   8500.0  3502.5
Ibadan   2731.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Ikoyi    2732.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0
Lekki    2734.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0

[1833 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi    2732.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0
Lekki    2734.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan   2737.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ikoyi    2737.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Lekki    2739.5  NaN    NaN        NaN  3000.0       4.0  NaN  11000.0  3004.0

[1836 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi    2737.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Lekki    2739.5  NaN    NaN        NaN  3000.0       4.0  NaN  11000.0  3004.0
Gbagada  2743.0  NaN    NaN        NaN  3000.0       1.5  NaN   5000.0  3001.5
Ikoyi    2743.0  NaN    NaN        NaN  3000.0       1.5  NaN   4000.0  3001.5
Lekki    2743.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0

[1839 rows x 9 columns]

            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi    2743.0  NaN    NaN        NaN  3000.0       1.5  NaN   4000.0  3001.5
Lekki    2743.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ibadan   2747.5  NaN    NaN        NaN  3500.0       5.0  NaN  17500.0  3505.0
Ikoyi    2747.5  NaN    NaN        NaN  3000.0       4.0  NaN  13000.0  3004.0
Lekki    2750.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0

[1842 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi    2747.5  NaN    NaN        NaN  3000.0       4.0  NaN  13000.0  3004.0
Lekki    2750.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada  2751.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0  3001.0
Ikoyi    2753.5  NaN    NaN        NaN  3000.0       1.5  NaN   4500.0  3001.5
Lekki    2753.5  NaN    NaN        NaN  3000.0       3.0  NaN   8000.0  3003.0

[1845 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     2753.5  NaN    NaN        NaN  3000.0       3.0  NaN   8000.0
Gbagada   2760.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan    2758.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ikoyi     2756.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Surulere  2758.0  NaN    NaN        NaN  3500.0       3.0  NaN   9500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3003.0
Gbagada   2004.0
Ibadan    3001.0
Ikoyi     2001.0
Surulere  3503.0

[1849 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
...          ...  ...    ...        ...          ...       ...  ...      ...
Ikoyi     2756.0  NaN    NaN        NaN  2000.000000  1.000000  NaN   2000.0
Surulere  2758.0  NaN    NaN        NaN  3500.000000  3.000000  NaN   9500.0
Gbagada   2762.0  NaN    NaN        NaN  3333.333333  2.333333  NaN   8000.0
Lekki     2764.0  NaN    NaN        NaN  3000.000000  3.000000  NaN   9000.0
Surulere  2765.0  NaN    NaN        NaN  2000.000000  2.000000  NaN   4000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Ikoyi     2001.000000
Surulere  3503.000000
Gbagada   3335.666667
Lekki     3003.000000
Surulere  2002.000000

[1852 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2765.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Gbagada   2770.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Ibadan    2766.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ikoyi     2769.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Lekki     2767.5  NaN    NaN        NaN  2500.0       2.5  NaN   6500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2002.0
Gbagada   2002.0
Ibadan    3004.0
Ikoyi     3004.0
Lekki     2502.5

[1856 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki    2767.5  NaN    NaN        NaN  2500.0       2.5  NaN   6500.0  2502.5
Gbagada  2772.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0
Ibadan   2771.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Ikoyi    2774.0  NaN    NaN        NaN  3000.0       4.5  NaN  13000.0  3004.5
Lekki    2774.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0  3002.0

[1860 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     2774.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Gbagada   2779.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ikoyi     2780.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Lekki     2777.5  NaN    NaN        NaN  3000.0       3.0  NaN   7000.0
Surulere  2776.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3002.0
Gbagada   4001.0
Ikoyi     2003.0
Lekki     3003.0
Surulere  4004.0

[1864 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     2777.5  NaN    NaN        NaN  3000.0       3.0  NaN   7000.0
Surulere  2776.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Gbagada   2782.0  NaN    NaN        NaN  3000.0       3.5  NaN  12000.0
Ibadan    2785.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Surulere  2783.0  NaN    NaN        NaN  3000.0       1.5  NaN   4500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3003.0
Surulere  4004.0
Gbagada   3003.5
Ibadan    3004.0
Surulere  3001.5

[1867 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    2785.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Surulere  2783.0  NaN    NaN        NaN  3000.0       1.5  NaN   4500.0
Gbagada   2787.5  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan    2787.5  NaN    NaN        NaN  3000.0       2.0  NaN   7000.0
Ikoyi     2790.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    3004.0
Surulere  3001.5
Gbagada   2004.0
Ibadan    3002.0
Ikoyi     3004.0

[1870 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     2790.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Gbagada   2791.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ikoyi     2793.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     2794.5  NaN    NaN        NaN  3500.0       3.5  NaN  12000.0
Surulere  2792.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3004.0
Gbagada   2001.0
Ikoyi     4003.0
Lekki     3503.5
Surulere  3001.0

[1874 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     2793.000000  NaN    NaN        NaN  4000.000000       3.0  NaN
Lekki     2794.500000  NaN    NaN        NaN  3500.000000       3.5  NaN
Surulere  2792.000000  NaN    NaN        NaN  3000.000000       1.0  NaN
Lekki     2798.500000  NaN    NaN        NaN  3000.000000       2.0  NaN
Surulere  2797.666667  NaN    NaN        NaN  3333.333333       3.0  NaN

          Revenue         Snap
Gbagada    8000.0  2004.000000
Ibadan    10000.0  2005.000000
Ikoyi      5000.0  2002.500000
Lekki     20000.0  4005.000000
Gbagada    6000.0  2003.000000
...           ...          ...
Ikoyi     12000.0  4003.000000
Lekki     12000.0  3503.500000
Surulere   3000.0  3001.000000
Lekki      6000.0  3002.000000
Surulere  10000.0  3336.333333

[1876 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...               ...  ...    ...        ...          ...       ...  ...
Surulere  2797.666667  NaN    NaN        NaN  3333.333333       3.0  NaN
Gbagada   2804.000000  NaN    NaN        NaN  4000.000000       2.0  NaN
Ibadan    2804.000000  NaN    NaN        NaN  4000.000000       4.0  NaN
Ikoyi     2802.000000  NaN    NaN        NaN  3000.000000       3.0  NaN
Surulere  2801.000000  NaN    NaN        NaN  4000.000000       4.0  NaN

          Revenue         Snap
Gbagada    8000.0  2004.000000
Ibadan    10000.0  2005.000000
Ikoyi      5000.0  2002.500000
Lekki     20000.0  4005.000000
Gbagada    6000.0  2003.000000
...           ...          ...
Surulere  10000.0  3336.333333
Gbagada    8000.0  4002.000000
Ibadan    16000.0  4004.000000
Ikoyi      9000.0  3003.000000
Surulere  16000.0  4004.000000

[1880 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2801.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Gbagada   2808.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ikoyi     2808.0  NaN    NaN        NaN  3500.0       4.0  NaN  14000.0
Lekki     2809.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Surulere  2807.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4004.0
Gbagada   2003.0
Ikoyi     3504.0
Lekki     4004.0
Surulere  4001.0

[1884 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
...          ...  ...    ...        ...          ...       ...  ...      ...
Lekki     2809.0  NaN    NaN        NaN  4000.000000  4.000000  NaN  16000.0
Surulere  2807.0  NaN    NaN        NaN  4000.000000  1.000000  NaN   4000.0
Ikoyi     2812.0  NaN    NaN        NaN  3666.666667  4.333333  NaN  16000.0
Lekki     2814.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Surulere  2815.0  NaN    NaN        NaN  2000.000000  2.000000  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4004.0
Surulere  4001.0
Ikoyi     3671.0
Lekki     4005.0
Surulere  2002.0

[1887 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2815.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Ibadan    2817.5  NaN    NaN        NaN  2500.0       1.5  NaN   4000.0
Ikoyi     2817.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Lekki     2818.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  2820.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2002.0
Ibadan    2501.5
Ikoyi     3003.0
Lekki     4002.0
Surulere  3001.0

[1891 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2820.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ibadan    2824.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi     2823.5  NaN    NaN        NaN  3500.0       4.0  NaN  14000.0
Lekki     2821.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Surulere  2823.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3001.0
Ibadan    2005.0
Ikoyi     3504.0
Lekki     2002.0
Surulere  2004.0

[1895 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   2829.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ibadan    2827.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ikoyi     2830.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Lekki     2826.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Surulere  2828.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   4002.0
Ibadan    2001.0
Ikoyi     3004.0
Lekki     2003.0
Surulere  2002.0

[1900 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...               ...  ...    ...        ...     ...       ...  ...
Lekki     2826.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
Surulere  2828.000000  NaN    NaN        NaN  2000.0  2.000000  NaN
Ibadan    2834.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
Ikoyi     2831.000000  NaN    NaN        NaN  4000.0  2.000000  NaN
Lekki     2833.333333  NaN    NaN        NaN  4000.0  4.666667  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      6000.000000  2003.000000
Surulere   4000.000000  2002.000000
Ibadan     6000.000000  2003.000000
Ikoyi      8000.000000  4002.000000
Lekki     18666.666667  4004.666667

[1903 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     2831.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Lekki     2833.333333  NaN    NaN        NaN  4000.000000  4.666667  NaN
Ikoyi     2840.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Lekki     2838.000000  NaN    NaN        NaN  2666.666667  3.333333  NaN
Surulere  2836.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi      8000.000000  4002.000000
Lekki     18666.666667  4004.666667
Ikoyi      8000.000000  2004.000000
Lekki     10000.000000  2670.000000
Surulere  16000.000000  4004.000000

[1906 rows x 9 columns]

             S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
...          ...  ...    ...        ...          ...       ...  ...      ...
Lekki     2838.0  NaN    NaN        NaN  2666.666667  3.333333  NaN  10000.0
Surulere  2836.0  NaN    NaN        NaN  4000.000000  4.000000  NaN  16000.0
Gbagada   2843.0  NaN    NaN        NaN  4000.000000  1.000000  NaN   4000.0
Ibadan    2843.5  NaN    NaN        NaN  3500.000000  2.000000  NaN   7500.0
Ikoyi     2842.0  NaN    NaN        NaN  2000.000000  1.000000  NaN   2000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2670.0
Surulere  4004.0
Gbagada   4001.0
Ibadan    3502.0
Ikoyi     2001.0

[1909 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     2842.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ibadan    2849.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ikoyi     2848.5  NaN    NaN        NaN  3000.0       2.5  NaN   6000.0
Lekki     2846.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Surulere  2848.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     2001.0
Ibadan    4005.0
Ikoyi     3002.5
Lekki     4004.0
Surulere  3003.0

[1913 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...          ...  ...    ...        ...          ...       ...  ...
Ikoyi     2848.5  NaN    NaN        NaN  3000.000000  2.500000  NaN
Lekki     2846.0  NaN    NaN        NaN  4000.000000  4.000000  NaN
Surulere  2848.0  NaN    NaN        NaN  3000.000000  3.000000  NaN
Gbagada   2852.0  NaN    NaN        NaN  2666.666667  1.333333  NaN
Ikoyi     2854.5  NaN    NaN        NaN  4000.000000  2.500000  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Ikoyi      6000.000000  3002.5
Lekki     16000.000000  4004.0
Surulere   9000.000000  3003.0
Gbagada    3333.333333  2668.0
Ikoyi     10000.000000  4002.5

[1915 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     2854.5  NaN    NaN        NaN  4000.0       2.5  NaN  10000.0
Gbagada   2859.0  NaN    NaN        NaN  3000.0       2.5  NaN   7500.0
Ikoyi     2857.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Lekki     2859.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Surulere  2856.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     4002.5
Gbagada   3002.5
Ikoyi     3004.0
Lekki     2001.0
Surulere  2005.0

[1919 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2856.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Gbagada   2863.0  NaN    NaN        NaN  4000.0       2.5  NaN  10000.0
Ibadan    2863.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ikoyi     2862.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Lekki     2864.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2005.0
Gbagada   4002.5
Ibadan    4002.0
Ikoyi     4004.0
Lekki     4005.0

[1923 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi    2862.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Lekki    2864.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada  2869.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0  3001.0
Ikoyi    2867.5  NaN    NaN        NaN  2500.0       3.0  NaN   8500.0  2503.0
Lekki    2868.0  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0  4003.5

[1926 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     2868.0  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0
Ibadan    2873.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ikoyi     2873.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Lekki     2874.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Surulere  2872.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4003.5
Ibadan    3005.0
Ikoyi     3004.0
Lekki     4001.0
Surulere  2001.0

[1930 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     2873.000000  NaN    NaN        NaN  3000.000000  4.000000  NaN
Lekki     2874.000000  NaN    NaN        NaN  4000.000000  1.000000  NaN
Surulere  2872.000000  NaN    NaN        NaN  2000.000000  1.000000  NaN
Lekki     2877.666667  NaN    NaN        NaN  3666.666667  2.666667  NaN
Surulere  2878.500000  NaN    NaN        NaN  2500.000000  1.500000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi     12000.000000  3004.000000
Lekki      4000.000000  4001.000000
Surulere   2000.000000  2001.000000
Lekki      9666.666667  3669.333333
Surulere   3500.000000  2501.500000

[1932 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2878.5  NaN    NaN        NaN  2500.0       1.5  NaN   3500.0
Ibadan    2883.5  NaN    NaN        NaN  3000.0       4.0  NaN  13000.0
Ikoyi     2883.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Lekki     2884.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Surulere  2881.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2501.5
Ibadan    3004.0
Ikoyi     2003.0
Lekki     3005.0
Surulere  4004.0

[1936 rows x 9 columns]

             S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
...          ...  ...    ...        ...          ...       ...  ...      ...
Ikoyi     2883.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
Lekki     2884.0  NaN    NaN        NaN  3000.000000  5.000000  NaN  15000.0
Surulere  2881.0  NaN    NaN        NaN  4000.000000  4.000000  NaN  16000.0
Gbagada   2888.0  NaN    NaN        NaN  3666.666667  3.666667  NaN  14000.0
Ibadan    2888.0  NaN    NaN        NaN  3000.000000  4.500000  NaN  13500.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Ikoyi     2003.000000
Lekki     3005.000000
Surulere  4004.000000
Gbagada   3670.333333
Ibadan    3004.500000

[1938 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    2888.0  NaN    NaN        NaN  3000.0       4.5  NaN  13500.0
Gbagada   2892.5  NaN    NaN        NaN  3000.0       3.5  NaN  10000.0
Ibadan    2895.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ikoyi     2894.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Surulere  2891.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    3004.5
Gbagada   3003.5
Ibadan    4001.0
Ikoyi     4001.0
Surulere  4002.0

[1942 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     2894.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Surulere  2891.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ibadan    2898.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Lekki     2900.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  2897.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     4001.0
Surulere  4002.0
Ibadan    4004.0
Lekki     4003.0
Surulere  4002.0

[1945 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     2900.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  2897.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Gbagada   2903.0  NaN    NaN        NaN  2500.0       3.5  NaN   9000.0
Ikoyi     2903.0  NaN    NaN        NaN  2500.0       1.5  NaN   3500.0
Lekki     2903.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4003.0
Surulere  4002.0
Gbagada   2503.5
Ikoyi     2501.5
Lekki     4001.0

[1948 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     2903.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Gbagada   2907.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ibadan    2909.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Lekki     2907.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Surulere  2910.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4001.0
Gbagada   4005.0
Ibadan    2002.0
Lekki     3004.0
Surulere  4002.0

[1952 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     2907.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Surulere  2910.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ikoyi     2912.5  NaN    NaN        NaN  3500.0       3.0  NaN  11000.0
Lekki     2912.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Surulere  2914.0  NaN    NaN        NaN  2500.0       2.0  NaN   5000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3004.0
Surulere  4002.0
Ikoyi     3503.0
Lekki     3002.0
Surulere  2502.0

[1955 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...               ...  ...    ...        ...     ...       ...  ...
Lekki     2912.000000  NaN    NaN        NaN  3000.0  2.000000  NaN
Surulere  2914.000000  NaN    NaN        NaN  2500.0  2.000000  NaN
Ibadan    2916.000000  NaN    NaN        NaN  2000.0  2.000000  NaN
Lekki     2918.333333  NaN    NaN        NaN  3000.0  2.666667  NaN
Surulere  2919.000000  NaN    NaN        NaN  4000.0  4.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      6000.000000  3002.000000
Surulere   5000.000000  2502.000000
Ibadan     4000.000000  2002.000000
Lekki      9333.333333  3002.666667
Surulere  16000.000000  4004.000000

[1958 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     2918.333333  NaN    NaN        NaN  3000.000000  2.666667  NaN
Surulere  2919.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN
Ikoyi     2921.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN
Lekki     2923.666667  NaN    NaN        NaN  3333.333333  1.666667  NaN
Surulere  2923.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      9333.333333  3002.666667
Surulere  16000.000000  4004.000000
Ikoyi     16000.000000  4004.000000
Lekki      6000.000000  3335.000000
Surulere   8000.000000  2004.000000

[1961 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2923.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Gbagada   2928.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ibadan    2929.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ikoyi     2926.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Surulere  2928.5  NaN    NaN        NaN  4000.0       2.5  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2004.0
Gbagada   2005.0
Ibadan    4002.0
Ikoyi     2003.0
Surulere  4002.5

[1965 rows x 9 columns]

                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...               ...  ...    ...        ...     ...       ...  ...
Ibadan    2929.000000  NaN    NaN        NaN  4000.0  2.000000  NaN
Ikoyi     2926.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
Surulere  2928.500000  NaN    NaN        NaN  4000.0  2.500000  NaN
Gbagada   2932.666667  NaN    NaN        NaN  3000.0  2.333333  NaN
Ikoyi     2933.500000  NaN    NaN        NaN  3500.0  1.500000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ibadan     8000.000000  4002.000000
Ikoyi      6000.000000  2003.000000
Surulere  10000.000000  4002.500000
Gbagada    7333.333333  3002.333333
Ikoyi      5500.000000  3501.500000

[1967 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi    2933.5  NaN    NaN        NaN  3500.0       1.5  NaN   5500.0  3501.5
Gbagada  2938.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Ibadan   2938.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0
Ikoyi    2940.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Lekki    2936.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0

[1971 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     2936.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Gbagada   2943.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ibadan    2943.5  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Lekki     2941.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Surulere  2944.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3003.0
Gbagada   4003.0
Ibadan    4004.0
Lekki     2003.0
Surulere  4004.0

[1975 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     2941.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
Surulere  2944.000000  NaN    NaN        NaN  4000.000000       4.0  NaN
Gbagada   2947.333333  NaN    NaN        NaN  2333.333333       3.0  NaN
Ibadan    2948.000000  NaN    NaN        NaN  4000.000000       3.0  NaN
Surulere  2950.000000  NaN    NaN        NaN  2000.000000       2.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      6000.000000  2003.000000
Surulere  16000.000000  4004.000000
Gbagada    7333.333333  2336.333333
Ibadan    12000.000000  4003.000000
Surulere   4000.000000  2002.000000

[1978 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...          ...  ...    ...        ...          ...       ...  ...
Ibadan    2948.0  NaN    NaN        NaN  4000.000000  3.000000  NaN
Surulere  2950.0  NaN    NaN        NaN  2000.000000  2.000000  NaN
Gbagada   2951.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Ibadan    2955.0  NaN    NaN        NaN  3000.000000  4.000000  NaN
Lekki     2953.0  NaN    NaN        NaN  3333.333333  2.666667  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Ibadan    12000.000000  4003.0
Surulere   4000.000000  2002.0
Gbagada   20000.000000  4005.0
Ibadan    12000.000000  3004.0
Lekki      8333.333333  3336.0

[1981 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...          ...  ...    ...        ...          ...       ...  ...
Lekki     2953.0  NaN    NaN        NaN  3333.333333  2.666667  NaN
Gbagada   2958.0  NaN    NaN        NaN  3000.000000  1.000000  NaN
Ikoyi     2959.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Lekki     2958.0  NaN    NaN        NaN  2500.000000  3.000000  NaN
Surulere  2957.0  NaN    NaN        NaN  4000.000000  1.000000  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Lekki      8333.333333  3336.0
Gbagada    3000.000000  3001.0
Ikoyi     20000.000000  4005.0
Lekki      7000.000000  2503.0
Surulere   4000.000000  4001.0

[1985 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     2959.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Lekki     2958.0  NaN    NaN        NaN  2500.0       3.0  NaN   7000.0
Surulere  2957.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Gbagada   2962.5  NaN    NaN        NaN  3250.0       2.0  NaN   6250.0
Surulere  2965.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     4005.0
Lekki     2503.0
Surulere  4001.0
Gbagada   3252.0
Surulere  2003.0

[1987 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.000000  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.000000  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.000000  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.000000  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...               ...  ...    ...        ...     ...       ...  ...      ...
Surulere  2957.000000  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Gbagada   2962.500000  NaN    NaN        NaN  3250.0       2.0  NaN   6250.0
Surulere  2965.000000  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Gbagada   2967.666667  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Ibadan    2968.500000  NaN    NaN        NaN  2500.0       3.0  NaN   8500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4001.0
Gbagada   3252.0
Surulere  2003.0
Gbagada   3003.0
Ibadan    2503.0

[1989 rows x 9 columns]
                 S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...              ...  ...    ...        ...     ...       ...  ...
Gbagada  2967.666667  NaN    NaN        NaN  3000.0  3.000000  NaN
Ibadan   2968.500000  NaN    NaN        NaN  2500.0  3.000000  NaN
Gbagada  2972.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
Ikoyi    2975.000000  NaN    NaN        NaN  3000.0  5.000000  NaN
Lekki    2972.666667  NaN    NaN        NaN  3000.0  2.666667  NaN

              Revenue         Snap
Gbagada   8000.000000  2004.000000
Ibadan   10000.000000  2005.000000
Ikoyi     5000.000000  2002.500000
Lekki    20000.000000  4005.000000
Gbagada   6000.000000  2003.000000
...               ...          ...
Gbagada   9000.000000  3003.000000
Ibadan    8500.000000  2503.000000
Gbagada   6000.000000  2003.000000
Ikoyi    15000.000000  3005.000000
Lekki     7666.666667  3002.666667

[1992 rows x 9 columns]

                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...               ...  ...    ...        ...     ...       ...  ...
Lekki     2972.666667  NaN    NaN        NaN  3000.0  2.666667  NaN
Gbagada   2977.000000  NaN    NaN        NaN  2000.0  2.000000  NaN
Ibadan    2979.000000  NaN    NaN        NaN  4000.0  3.000000  NaN
Lekki     2978.000000  NaN    NaN        NaN  2500.0  4.000000  NaN
Surulere  2978.000000  NaN    NaN        NaN  2000.0  2.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      7666.666667  3002.666667
Gbagada    4000.000000  2002.000000
Ibadan    12000.000000  4003.000000
Lekki      9500.000000  2504.000000
Surulere   4000.000000  2002.000000

[1996 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000       3.0  NaN
...          ...  ...    ...        ...          ...       ...  ...
Lekki     2978.0  NaN    NaN        NaN  2500.000000       4.0  NaN
Surulere  2978.0  NaN    NaN        NaN  2000.000000       2.0  NaN
Gbagada   2983.0  NaN    NaN        NaN  3333.333333       4.0  NaN
Ibadan    2982.0  NaN    NaN        NaN  2000.000000       3.0  NaN
Ikoyi     2984.0  NaN    NaN        NaN  2000.000000       5.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      9500.000000  2504.000000
Surulere   4000.000000  2002.000000
Gbagada   13333.333333  3337.333333
Ibadan     6000.000000  2003.000000
Ikoyi     10000.000000  2005.000000

[1999 rows x 9 columns]
                 S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...              ...  ...    ...        ...          ...       ...  ...
Gbagada  2983.000000  NaN    NaN        NaN  3333.333333       4.0  NaN
Ibadan   2982.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
Ikoyi    2984.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Gbagada  2987.666667  NaN    NaN        NaN  3333.333333       4.0  NaN
Ibadan   2988.500000  NaN    NaN        NaN  2000.000000       4.5  NaN

              Revenue         Snap
Gbagada   8000.000000  2004.000000
Ibadan   10000.000000  2005.000000
Ikoyi     5000.000000  2002.500000
Lekki    20000.000000  4005.000000
Gbagada   6000.000000  2003.000000
...               ...          ...
Gbagada  13333.333333  3337.333333
Ibadan    6000.000000  2003.000000
Ikoyi    10000.000000  2005.000000
Gbagada  12666.666667  3337.333333
Ibadan    9000.000000  2004.500000

[2001 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    2988.5  NaN    NaN        NaN  2000.0       4.5  NaN   9000.0
Ibadan    2992.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ikoyi     2992.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     2994.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  2995.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    2004.5
Ibadan    4003.0
Ikoyi     4001.0
Lekki     4002.0
Surulere  2005.0

[2005 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     2994.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Surulere  2995.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Gbagada   2996.000000  NaN    NaN        NaN  3000.000000  3.000000  NaN
Ibadan    2999.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Surulere  2998.333333  NaN    NaN        NaN  3333.333333  2.333333  NaN

          Revenue         Snap
Gbagada    8000.0  2004.000000
Ibadan    10000.0  2005.000000
Ikoyi      5000.0  2002.500000
Lekki     20000.0  4005.000000
Gbagada    6000.0  2003.000000
...           ...          ...
Lekki      8000.0  4002.000000
Surulere  10000.0  2005.000000
Gbagada    9000.0  3003.000000
Ibadan     8000.0  4002.000000
Surulere   8000.0  3335.666667

[2008 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Surulere  2998.333333  NaN    NaN        NaN  3333.333333  2.333333  NaN
Gbagada   3002.000000  NaN    NaN        NaN  3000.000000  4.000000  NaN
Ibadan    3005.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Ikoyi     3003.000000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Lekki     3002.500000  NaN    NaN        NaN  3000.000000  4.000000  NaN

          Revenue         Snap
Gbagada    8000.0  2004.000000
Ibadan    10000.0  2005.000000
Ikoyi      5000.0  2002.500000
Lekki     20000.0  4005.000000
Gbagada    6000.0  2003.000000
...           ...          ...
Surulere   8000.0  3335.666667
Gbagada   12000.0  3004.000000
Ibadan     6000.0  2003.000000
Ikoyi     12000.0  4003.000000
Lekki     13000.0  3004.000000

[2012 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3002.5  NaN    NaN        NaN  3000.0       4.0  NaN  13000.0
Gbagada   3010.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ibadan    3006.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Lekki     3007.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  3008.5  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3004.0
Gbagada   4005.0
Ibadan    3005.0
Lekki     4005.0
Surulere  4003.0

[2016 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ibadan    3006.000000  NaN    NaN        NaN  3000.000000  5.000000  NaN
Lekki     3007.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Surulere  3008.500000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Lekki     3012.000000  NaN    NaN        NaN  3000.000000  3.000000  NaN
Surulere  3013.666667  NaN    NaN        NaN  3666.666667  3.666667  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ibadan    15000.000000  3005.000000
Lekki     20000.000000  4005.000000
Surulere  12000.000000  4003.000000
Lekki      9000.000000  3003.000000
Surulere  13333.333333  3670.333333

[2018 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Surulere  3008.500000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Lekki     3012.000000  NaN    NaN        NaN  3000.000000  3.000000  NaN
Surulere  3013.666667  NaN    NaN        NaN  3666.666667  3.666667  NaN
Ibadan    3017.500000  NaN    NaN        NaN  3250.000000  3.750000  NaN
Ikoyi     3020.000000  NaN    NaN        NaN  4000.000000  3.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Surulere  12000.000000  4003.000000
Lekki      9000.000000  3003.000000
Surulere  13333.333333  3670.333333
Ibadan    12500.000000  3253.750000
Ikoyi     12000.000000  4003.000000

[2020 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0      4.00  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0      5.00  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0      2.50  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0      5.00  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0      3.00  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    3017.5  NaN    NaN        NaN  3250.0      3.75  NaN  12500.0
Ikoyi     3020.0  NaN    NaN        NaN  4000.0      3.00  NaN  12000.0
Gbagada   3023.0  NaN    NaN        NaN  3500.0      4.50  NaN  16000.0
Lekki     3024.0  NaN    NaN        NaN  2000.0      1.00  NaN   2000.0
Surulere  3022.5  NaN    NaN        NaN  3500.0      3.00  NaN  10500.0

             Snap
Gbagada   2004.00
Ibadan    2005.00
Ikoyi     2002.50
Lekki     4005.00
Gbagada   2003.00
...           ...
Ibadan    3253.75
Ikoyi     4003.00
Gbagada   3504.50
Lekki     2001.00
Surulere  3503.00

[2023 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3022.5  NaN    NaN        NaN  3500.0       3.0  NaN  10500.0
Gbagada   3027.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ikoyi     3030.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Lekki     3027.0  NaN    NaN        NaN  3000.0       2.0  NaN   5000.0
Surulere  3029.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3503.0
Gbagada   4003.0
Ikoyi     3003.0
Lekki     3002.0
Surulere  3005.0

[2027 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3027.0  NaN    NaN        NaN  3000.0       2.0  NaN   5000.0
Surulere  3029.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ibadan    3033.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ikoyi     3034.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     3032.5  NaN    NaN        NaN  3500.0       3.5  NaN  13000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3002.0
Surulere  3005.0
Ibadan    4004.0
Ikoyi     4003.0
Lekki     3503.5

[2030 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki    3032.5  NaN    NaN        NaN  3500.0       3.5  NaN  13000.0  3503.5
Gbagada  3037.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0  3002.0
Ibadan   3037.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Ikoyi    3040.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Lekki    3039.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0

[2034 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3039.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Gbagada   3043.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ibadan    3045.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ikoyi     3042.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Surulere  3042.5  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2004.0
Gbagada   4005.0
Ibadan    4005.0
Ikoyi     2004.0
Surulere  2004.0

[2038 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     3042.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Surulere  3042.5  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan    3048.5  NaN    NaN        NaN  3000.0       4.5  NaN  13000.0
Lekki     3050.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  3046.5  NaN    NaN        NaN  2500.0       2.5  NaN   7000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     2004.0
Surulere  2004.0
Ibadan    3004.5
Lekki     4002.0
Surulere  2502.5

[2041 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3050.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  3046.5  NaN    NaN        NaN  2500.0       2.5  NaN   7000.0
Ibadan    3053.5  NaN    NaN        NaN  3000.0       2.0  NaN   5000.0
Ikoyi     3054.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Lekki     3052.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4002.0
Surulere  2502.5
Ibadan    3002.0
Ikoyi     3005.0
Lekki     4004.0

[2044 rows x 9 columns]
            S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.0  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan      1.0  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi       3.0  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki       3.0  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada     9.0  NaN    NaN        NaN  2000.000000       3.0  NaN
...         ...  ...    ...        ...          ...       ...  ...
Ikoyi    3054.0  NaN    NaN        NaN  3000.000000       5.0  NaN
Lekki    3052.0  NaN    NaN        NaN  4000.000000       4.0  NaN
Gbagada  3058.0  NaN    NaN        NaN  3666.666667       2.0  NaN
Ibadan   3056.0  NaN    NaN        NaN  2000.000000       5.0  NaN
Lekki    3060.0  NaN    NaN        NaN  3000.000000       5.0  NaN

              Revenue         Snap
Gbagada   8000.000000  2004.000000
Ibadan   10000.000000  2005.000000
Ikoyi     5000.000000  2002.500000
Lekki    20000.000000  4005.000000
Gbagada   6000.000000  2003.000000
...               ...          ...
Ikoyi    15000.000000  3005.000000
Lekki    16000.000000  4004.000000
Gbagada   7666.666667  3668.666667
Ibadan   10000.000000  2005.000000
Lekki    15000.000000  3005.000000

[2047 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3060.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Gbagada   3064.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Ibadan    3065.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi     3062.5  NaN    NaN        NaN  3000.0       3.0  NaN   8000.0
Surulere  3061.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3005.0
Gbagada   2002.0
Ibadan    2005.0
Ikoyi     3003.0
Surulere  3002.0

[2051 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3061.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Gbagada   3069.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi     3067.5  NaN    NaN        NaN  4000.0       2.5  NaN  10000.0
Lekki     3070.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Surulere  3066.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3002.0
Gbagada   2005.0
Ikoyi     4002.5
Lekki     2002.0
Surulere  3004.0

[2055 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.0
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.0
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.0
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.0
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.0
...               ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3070.000000  NaN    NaN        NaN  2000.0  2.000000  NaN   4000.0
Surulere  3066.000000  NaN    NaN        NaN  3000.0  4.000000  NaN  12000.0
Ibadan    3073.000000  NaN    NaN        NaN  4000.0  1.000000  NaN   4000.0
Ikoyi     3074.000000  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.0
Surulere  3072.666667  NaN    NaN        NaN  3000.0  4.333333  NaN  13000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Lekki     2002.000000
Surulere  3004.000000
Ibadan    4001.000000
Ikoyi     4005.000000
Surulere  3004.333333

[2058 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   3076.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ibadan    3080.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Ikoyi     3079.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Lekki     3078.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Surulere  3077.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   3001.0
Ibadan    3003.0
Ikoyi     2002.0
Lekki     3002.0
Surulere  4002.0

[2063 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     3079.000000  NaN    NaN        NaN  2000.000000  2.000000  NaN
Lekki     3078.000000  NaN    NaN        NaN  3000.000000  2.000000  NaN
Surulere  3077.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Ibadan    3083.500000  NaN    NaN        NaN  3000.000000  3.500000  NaN
Ikoyi     3082.666667  NaN    NaN        NaN  3666.666667  2.666667  NaN

          Revenue         Snap
Gbagada    8000.0  2004.000000
Ibadan    10000.0  2005.000000
Ikoyi      5000.0  2002.500000
Lekki     20000.0  4005.000000
Gbagada    6000.0  2003.000000
...           ...          ...
Ikoyi      4000.0  2002.000000
Lekki      6000.0  3002.000000
Surulere   8000.0  4002.000000
Ibadan    12000.0  3003.500000
Ikoyi     10000.0  3669.333333

[2065 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ibadan    3083.500000  NaN    NaN        NaN  3000.000000  3.500000  NaN
Ikoyi     3082.666667  NaN    NaN        NaN  3666.666667  2.666667  NaN
Gbagada   3087.000000  NaN    NaN        NaN  4000.000000  1.000000  NaN
Lekki     3089.000000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Surulere  3087.500000  NaN    NaN        NaN  3500.000000  2.500000  NaN

          Revenue         Snap
Gbagada    8000.0  2004.000000
Ibadan    10000.0  2005.000000
Ikoyi      5000.0  2002.500000
Lekki     20000.0  4005.000000
Gbagada    6000.0  2003.000000
...           ...          ...
Ibadan    12000.0  3003.500000
Ikoyi     10000.0  3669.333333
Gbagada    4000.0  4001.000000
Lekki     12000.0  4003.000000
Surulere   9500.0  3502.500000

[2068 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.000000  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.000000  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.000000  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.000000  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...               ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3089.000000  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  3087.500000  NaN    NaN        NaN  3500.0       2.5  NaN   9500.0
Gbagada   3092.333333  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ibadan    3093.000000  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ikoyi     3095.000000  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4003.0
Surulere  3502.5
Gbagada   3004.0
Ibadan    4001.0
Ikoyi     4003.0

[2071 rows x 9 columns]
                 S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...              ...  ...    ...        ...          ...       ...  ...
Gbagada  3092.333333  NaN    NaN        NaN  3000.000000  4.000000  NaN
Ibadan   3093.000000  NaN    NaN        NaN  4000.000000  1.000000  NaN
Ikoyi    3095.000000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Gbagada  3097.333333  NaN    NaN        NaN  3333.333333  4.333333  NaN
Ibadan   3099.000000  NaN    NaN        NaN  3000.000000  4.000000  NaN

              Revenue         Snap
Gbagada   8000.000000  2004.000000
Ibadan   10000.000000  2005.000000
Ikoyi     5000.000000  2002.500000
Lekki    20000.000000  4005.000000
Gbagada   6000.000000  2003.000000
...               ...          ...
Gbagada  12000.000000  3004.000000
Ibadan    4000.000000  4001.000000
Ikoyi    12000.000000  4003.000000
Gbagada  14333.333333  3337.666667
Ibadan   12000.000000  3004.000000

[2073 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Gbagada   3097.333333  NaN    NaN        NaN  3333.333333  4.333333  NaN
Ibadan    3099.000000  NaN    NaN        NaN  3000.000000  4.000000  NaN
Gbagada   3105.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN
Ibadan    3103.000000  NaN    NaN        NaN  3000.000000  3.000000  NaN
Surulere  3102.333333  NaN    NaN        NaN  2333.333333  3.333333  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Gbagada   14333.333333  3337.666667
Ibadan    12000.000000  3004.000000
Gbagada   16000.000000  4004.000000
Ibadan     9000.000000  3003.000000
Surulere   7333.333333  2336.666667

[2076 rows x 9 columns]

                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Surulere  3102.333333  NaN    NaN        NaN  2333.333333  3.333333  NaN
Gbagada   3108.500000  NaN    NaN        NaN  3000.000000  2.500000  NaN
Ibadan    3106.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Ikoyi     3108.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Surulere  3109.000000  NaN    NaN        NaN  2000.000000  1.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Surulere   7333.333333  2336.666667
Gbagada    7500.000000  3002.500000
Ibadan    20000.000000  4005.000000
Ikoyi      8000.000000  4002.000000
Surulere   2000.000000  2001.000000

[2080 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3109.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Gbagada   3111.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ibadan    3113.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ikoyi     3113.5  NaN    NaN        NaN  3000.0       3.0  NaN  11000.0
Surulere  3114.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2001.0
Gbagada   3004.0
Ibadan    4002.0
Ikoyi     3003.0
Surulere  4001.0

[2084 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3114.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Gbagada   3120.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ikoyi     3119.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Lekki     3116.5  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Surulere  3118.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4001.0
Gbagada   4003.0
Ikoyi     3004.0
Lekki     2003.0
Surulere  4002.0

[2088 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...          ...  ...    ...        ...          ...       ...  ...
Lekki     3116.5  NaN    NaN        NaN  2000.000000  3.000000  NaN
Surulere  3118.0  NaN    NaN        NaN  4000.000000  2.000000  NaN
Gbagada   3124.0  NaN    NaN        NaN  4000.000000  3.000000  NaN
Ibadan    3122.0  NaN    NaN        NaN  3333.333333  3.666667  NaN
Ikoyi     3125.0  NaN    NaN        NaN  3000.000000  1.000000  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Lekki      6000.000000  2003.0
Surulere   8000.000000  4002.0
Gbagada   12000.000000  4003.0
Ibadan    12666.666667  3337.0
Ikoyi      3000.000000  3001.0

[2091 rows x 9 columns]
            S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...         ...  ...    ...        ...          ...       ...  ...
Gbagada  3124.0  NaN    NaN        NaN  4000.000000  3.000000  NaN
Ibadan   3122.0  NaN    NaN        NaN  3333.333333  3.666667  NaN
Ikoyi    3125.0  NaN    NaN        NaN  3000.000000  1.000000  NaN
Ikoyi    3128.0  NaN    NaN        NaN  3000.000000  2.000000  NaN
Lekki    3128.0  NaN    NaN        NaN  2666.666667  1.666667  NaN

              Revenue         Snap
Gbagada   8000.000000  2004.000000
Ibadan   10000.000000  2005.000000
Ikoyi     5000.000000  2002.500000
Lekki    20000.000000  4005.000000
Gbagada   6000.000000  2003.000000
...               ...          ...
Gbagada  12000.000000  4003.000000
Ibadan   12666.666667  3337.000000
Ikoyi     3000.000000  3001.000000
Ikoyi     5000.000000  3002.000000
Lekki     4666.666667  2668.333333

[2093 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...          ...  ...    ...        ...          ...       ...  ...
Lekki     3128.0  NaN    NaN        NaN  2666.666667  1.666667  NaN
Gbagada   3133.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ibadan    3131.5  NaN    NaN        NaN  4000.000000  5.000000  NaN
Ikoyi     3135.0  NaN    NaN        NaN  3000.000000  5.000000  NaN
Surulere  3134.0  NaN    NaN        NaN  2000.000000  5.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      4666.666667  2668.333333
Gbagada   10000.000000  2005.000000
Ibadan    20000.000000  4005.000000
Ikoyi     15000.000000  3005.000000
Surulere  10000.000000  2005.000000

[2097 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     3135.000000  NaN    NaN        NaN  3000.000000  5.000000  NaN
Surulere  3134.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Gbagada   3140.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Ikoyi     3137.333333  NaN    NaN        NaN  3666.666667  1.666667  NaN
Lekki     3138.000000  NaN    NaN        NaN  3000.000000  2.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi     15000.000000  3005.000000
Surulere  10000.000000  2005.000000
Gbagada    8000.000000  4002.000000
Ikoyi      5666.666667  3668.333333
Lekki      6000.000000  3002.000000

[2100 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   3143.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ibadan    3145.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ikoyi     3144.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     3141.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Surulere  3142.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   2005.0
Ibadan    4005.0
Ikoyi     4003.0
Lekki     2001.0
Surulere  4003.0

[2105 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3142.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Gbagada   3149.5  NaN    NaN        NaN  3000.0       1.5  NaN   4000.0
Ibadan    3148.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Lekki     3147.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Surulere  3146.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4003.0
Gbagada   3001.5
Ibadan    3001.0
Lekki     3002.0
Surulere  2002.0

[2109 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3147.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Surulere  3146.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Gbagada   3154.0  NaN    NaN        NaN  3000.0       3.5  NaN  12000.0
Ibadan    3152.5  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Ikoyi     3152.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3002.0
Surulere  2002.0
Gbagada   3003.5
Ibadan    2002.5
Ikoyi     4001.0

[2112 rows x 9 columns]

            S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...         ...  ...    ...        ...          ...       ...  ...
Gbagada  3154.0  NaN    NaN        NaN  3000.000000  3.500000  NaN
Ibadan   3152.5  NaN    NaN        NaN  2000.000000  2.500000  NaN
Ikoyi    3152.0  NaN    NaN        NaN  4000.000000  1.000000  NaN
Ibadan   3159.0  NaN    NaN        NaN  3333.333333  2.333333  NaN
Lekki    3156.5  NaN    NaN        NaN  3500.000000  3.500000  NaN

              Revenue         Snap
Gbagada   8000.000000  2004.000000
Ibadan   10000.000000  2005.000000
Ikoyi     5000.000000  2002.500000
Lekki    20000.000000  4005.000000
Gbagada   6000.000000  2003.000000
...               ...          ...
Gbagada  12000.000000  3003.500000
Ibadan    5000.000000  2002.500000
Ikoyi     4000.000000  4001.000000
Ibadan    8666.666667  3335.666667
Lekki    12000.000000  3503.500000

[2114 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3156.5  NaN    NaN        NaN  3500.0       3.5  NaN  12000.0
Ibadan    3161.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ikoyi     3163.5  NaN    NaN        NaN  2500.0       2.5  NaN   6500.0
Lekki     3163.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Surulere  3164.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3503.5
Ibadan    4003.0
Ikoyi     2502.5
Lekki     3003.0
Surulere  2001.0

[2118 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...          ...  ...    ...        ...          ...       ...  ...
Ikoyi     3163.5  NaN    NaN        NaN  2500.000000  2.500000  NaN
Lekki     3163.0  NaN    NaN        NaN  3000.000000  3.000000  NaN
Surulere  3164.0  NaN    NaN        NaN  2000.000000  1.000000  NaN
Ikoyi     3166.5  NaN    NaN        NaN  3500.000000  1.000000  NaN
Lekki     3169.0  NaN    NaN        NaN  3333.333333  2.666667  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Ikoyi      6500.000000  2502.5
Lekki      9000.000000  3003.0
Surulere   2000.000000  2001.0
Ikoyi      3500.000000  3501.0
Lekki      9333.333333  3336.0

[2120 rows x 9 columns]
            S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...         ...  ...    ...        ...          ...       ...  ...
Ikoyi    3166.5  NaN    NaN        NaN  3500.000000  1.000000  NaN
Lekki    3169.0  NaN    NaN        NaN  3333.333333  2.666667  NaN
Gbagada  3173.0  NaN    NaN        NaN  2000.000000  2.000000  NaN
Ibadan   3173.0  NaN    NaN        NaN  2500.000000  1.500000  NaN
Ikoyi    3173.0  NaN    NaN        NaN  3500.000000  2.500000  NaN

              Revenue    Snap
Gbagada   8000.000000  2004.0
Ibadan   10000.000000  2005.0
Ikoyi     5000.000000  2002.5
Lekki    20000.000000  4005.0
Gbagada   6000.000000  2003.0
...               ...     ...
Ikoyi     3500.000000  3501.0
Lekki     9333.333333  3336.0
Gbagada   4000.000000  2002.0
Ibadan    4000.000000  2501.5
Ikoyi     9000.000000  3502.5

[2123 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     3173.0  NaN    NaN        NaN  3500.0       2.5  NaN   9000.0
Gbagada   3177.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ibadan    3180.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     3177.5  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  3178.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3502.5
Gbagada   2005.0
Ibadan    4001.0
Lekki     4005.0
Surulere  4004.0

[2127 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3177.5  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  3178.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Gbagada   3182.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ikoyi     3182.0  NaN    NaN        NaN  3000.0       4.5  NaN  13000.0
Surulere  3184.5  NaN    NaN        NaN  3500.0       3.5  NaN  11500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4005.0
Surulere  4004.0
Gbagada   2003.0
Ikoyi     3004.5
Surulere  3503.5

[2130 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     3182.0  NaN    NaN        NaN  3000.0       4.5  NaN  13000.0
Surulere  3184.5  NaN    NaN        NaN  3500.0       3.5  NaN  11500.0
Gbagada   3188.0  NaN    NaN        NaN  2500.0       4.5  NaN  11500.0
Ibadan    3189.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ikoyi     3186.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3004.5
Surulere  3503.5
Gbagada   2504.5
Ibadan    3001.0
Ikoyi     4003.0

[2133 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ibadan    3189.000000  NaN    NaN        NaN  3000.000000       1.0  NaN
Ikoyi     3186.000000  NaN    NaN        NaN  4000.000000       3.0  NaN
Ibadan    3193.666667  NaN    NaN        NaN  2333.333333       3.0  NaN
Lekki     3193.000000  NaN    NaN        NaN  4000.000000       4.0  NaN
Surulere  3191.000000  NaN    NaN        NaN  2000.000000       2.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ibadan     3000.000000  3001.000000
Ikoyi     12000.000000  4003.000000
Ibadan     6333.333333  2336.333333
Lekki     16000.000000  4004.000000
Surulere   4000.000000  2002.000000

[2136 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3191.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Gbagada   3198.5  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Ikoyi     3196.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     3197.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Surulere  3200.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2002.0
Gbagada   3003.0
Ikoyi     4001.0
Lekki     3003.0
Surulere  2005.0

[2140 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3200.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ibadan    3202.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ikoyi     3204.5  NaN    NaN        NaN  2500.0       3.5  NaN   9500.0
Lekki     3201.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Surulere  3203.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2005.0
Ibadan    3002.0
Ikoyi     2503.5
Lekki     3003.0
Surulere  3005.0

[2144 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3201.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Surulere  3203.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ikoyi     3207.5  NaN    NaN        NaN  2500.0       3.5  NaN   8500.0
Lekki     3208.5  NaN    NaN        NaN  3000.0       1.5  NaN   4500.0
Surulere  3208.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3003.0
Surulere  3005.0
Ikoyi     2503.5
Lekki     3001.5
Surulere  3003.0

[2147 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3208.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Gbagada   3212.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ikoyi     3213.0  NaN    NaN        NaN  3500.0       2.0  NaN   7500.0
Lekki     3213.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Surulere  3214.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3003.0
Gbagada   4003.0
Ikoyi     3502.0
Lekki     3005.0
Surulere  3002.0

[2151 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3214.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ibadan    3218.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ikoyi     3218.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Lekki     3217.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  3219.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3002.0
Ibadan    3002.0
Ikoyi     4002.0
Lekki     4002.0
Surulere  4002.0

[2155 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3217.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  3219.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Gbagada   3223.0  NaN    NaN        NaN  3500.0       1.5  NaN   5500.0
Ikoyi     3222.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Lekki     3223.5  NaN    NaN        NaN  2500.0       4.0  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4002.0
Surulere  4002.0
Gbagada   3501.5
Ikoyi     3003.0
Lekki     2504.0

[2158 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     3222.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Lekki     3223.5  NaN    NaN        NaN  2500.0       4.0  NaN  10000.0
Ibadan    3228.0  NaN    NaN        NaN  3000.0       2.0  NaN   5000.0
Lekki     3229.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Surulere  3226.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3003.0
Lekki     2504.0
Ibadan    3002.0
Lekki     2003.0
Surulere  3005.0

[2161 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
...          ...  ...    ...        ...          ...       ...  ...      ...
Lekki     3229.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
Surulere  3226.0  NaN    NaN        NaN  3000.000000  5.000000  NaN  15000.0
Gbagada   3235.0  NaN    NaN        NaN  2000.000000  1.000000  NaN   2000.0
Ibadan    3233.0  NaN    NaN        NaN  2666.666667  2.666667  NaN   6000.0
Lekki     3231.0  NaN    NaN        NaN  4000.000000  4.000000  NaN  16000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Lekki     2003.000000
Surulere  3005.000000
Gbagada   2001.000000
Ibadan    2669.333333
Lekki     4004.000000

[2164 rows x 9 columns]
            S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada     5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0
Ibadan      1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ikoyi       3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN   5000.0
Lekki       3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Gbagada     9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
...         ...  ...    ...        ...          ...       ...  ...      ...
Ibadan   3233.0  NaN    NaN        NaN  2666.666667  2.666667  NaN   6000.0
Lekki    3231.0  NaN    NaN        NaN  4000.000000  4.000000  NaN  16000.0
Gbagada  3238.0  NaN    NaN        NaN  3500.000000  3.000000  NaN   9500.0
Ikoyi    3239.0  NaN    NaN        NaN  3500.000000  3.500000  NaN  11500.0
Lekki    3236.0  NaN    NaN        NaN  3000.000000  2.000000  NaN   6000.0

                Snap
Gbagada  2004.000000
Ibadan   2005.000000
Ikoyi    2002.500000
Lekki    4005.000000
Gbagada  2003.000000
...              ...
Ibadan   2669.333333
Lekki    4004.000000
Gbagada  3503.000000
Ikoyi    3503.500000
Lekki    3002.000000

[2167 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     3239.0  NaN    NaN        NaN  3500.0       3.5  NaN  11500.0
Lekki     3236.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Gbagada   3242.0  NaN    NaN        NaN  3500.0       4.0  NaN  14500.0
Lekki     3245.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Surulere  3243.0  NaN    NaN        NaN  2000.0       3.5  NaN   7000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3503.5
Lekki     3002.0
Gbagada   3504.0
Lekki     2004.0
Surulere  2003.5

[2170 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     3245.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Surulere  3243.000000  NaN    NaN        NaN  2000.000000       3.5  NaN
Gbagada   3247.666667  NaN    NaN        NaN  3666.666667       3.0  NaN
Ikoyi     3247.000000  NaN    NaN        NaN  4000.000000       2.0  NaN
Surulere  3250.000000  NaN    NaN        NaN  3000.000000       4.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      8000.000000  2004.000000
Surulere   7000.000000  2003.500000
Gbagada   11666.666667  3669.666667
Ikoyi      8000.000000  4002.000000
Surulere  12000.000000  3004.000000

[2173 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     3247.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  3250.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ibadan    3255.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ikoyi     3253.0  NaN    NaN        NaN  3000.0       3.5  NaN  10500.0
Lekki     3252.0  NaN    NaN        NaN  3000.0       3.5  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     4002.0
Surulere  3004.0
Ibadan    4001.0
Ikoyi     3003.5
Lekki     3003.5

[2176 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time       Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.000000
Ibadan       1.0  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.000000
Ikoyi        3.0  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.000000
Lekki        3.0  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.000000
Gbagada      9.0  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.000000
...          ...  ...    ...        ...     ...       ...  ...           ...
Ibadan    3255.0  NaN    NaN        NaN  4000.0  1.000000  NaN   4000.000000
Ikoyi     3253.0  NaN    NaN        NaN  3000.0  3.500000  NaN  10500.000000
Lekki     3252.0  NaN    NaN        NaN  3000.0  3.500000  NaN  12000.000000
Gbagada   3258.0  NaN    NaN        NaN  4000.0  2.666667  NaN  10666.666667
Surulere  3258.0  NaN    NaN        NaN  3500.0  2.500000  NaN   9000.000000

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Ibadan    4001.000000
Ikoyi     3003.500000
Lekki     3003.500000
Gbagada   4002.666667
Surulere  3502.500000

[2178 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3258.0  NaN    NaN        NaN  3500.0       2.5  NaN   9000.0
Gbagada   3263.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan    3264.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ikoyi     3263.5  NaN    NaN        NaN  3000.0       3.0  NaN   7000.0
Surulere  3261.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3502.5
Gbagada   2004.0
Ibadan    3005.0
Ikoyi     3003.0
Surulere  2004.0

[2182 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...               ...  ...    ...        ...     ...       ...  ...
Ikoyi     3263.500000  NaN    NaN        NaN  3000.0  3.000000  NaN
Surulere  3261.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan    3268.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ikoyi     3267.666667  NaN    NaN        NaN  4000.0  2.666667  NaN
Surulere  3269.000000  NaN    NaN        NaN  2000.0  1.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi      7000.000000  3003.000000
Surulere   8000.000000  2004.000000
Ibadan     8000.000000  2004.000000
Ikoyi     10666.666667  4002.666667
Surulere   2000.000000  2001.000000

[2185 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3269.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Gbagada   3274.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ibadan    3274.0  NaN    NaN        NaN  2500.0       3.0  NaN   8500.0
Ikoyi     3272.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Surulere  3271.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2001.0
Gbagada   3004.0
Ibadan    2503.0
Ikoyi     3001.0
Surulere  2004.0

[2189 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3271.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan    3277.5  NaN    NaN        NaN  3500.0       3.5  NaN  11500.0
Ikoyi     3280.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Lekki     3278.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Surulere  3277.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2004.0
Ibadan    3503.5
Ikoyi     2005.0
Lekki     4004.0
Surulere  4005.0

[2193 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...          ...  ...    ...        ...          ...       ...  ...
Lekki     3278.0  NaN    NaN        NaN  4000.000000  4.000000  NaN
Surulere  3277.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Ibadan    3282.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
Ikoyi     3284.0  NaN    NaN        NaN  3000.000000  1.000000  NaN
Surulere  3283.0  NaN    NaN        NaN  2333.333333  3.666667  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Lekki     16000.000000  4004.0
Surulere  20000.000000  4005.0
Ibadan     6000.000000  2003.0
Ikoyi      3000.000000  3001.0
Surulere   8666.666667  2337.0

[2196 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   3289.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ibadan    3286.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ikoyi     3287.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Lekki     3288.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Surulere  3290.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   2005.0
Ibadan    2003.0
Ikoyi     2003.0
Lekki     3002.0
Surulere  2005.0

[2201 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...               ...  ...    ...        ...     ...       ...  ...
Ikoyi     3287.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
Lekki     3288.000000  NaN    NaN        NaN  3000.0  2.000000  NaN
Surulere  3290.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi     3292.333333  NaN    NaN        NaN  3000.0  4.333333  NaN
Lekki     3294.000000  NaN    NaN        NaN  3000.0  4.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi      6000.000000  2003.000000
Lekki      6000.000000  3002.000000
Surulere  10000.000000  2005.000000
Ikoyi     13666.666667  3004.333333
Lekki     12000.000000  3004.000000

[2203 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki    3294.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0
Gbagada  3299.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Ibadan   3296.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ikoyi    3299.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Lekki    3297.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0

[2207 rows x 9 columns]
            S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...         ...  ...    ...        ...          ...       ...  ...
Ikoyi    3299.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Lekki    3297.0  NaN    NaN        NaN  4000.000000  3.000000  NaN
Gbagada  3303.0  NaN    NaN        NaN  3333.333333  1.333333  NaN
Ikoyi    3302.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Lekki    3304.0  NaN    NaN        NaN  4000.000000  5.000000  NaN

              Revenue         Snap
Gbagada   8000.000000  2004.000000
Ibadan   10000.000000  2005.000000
Ikoyi     5000.000000  2002.500000
Lekki    20000.000000  4005.000000
Gbagada   6000.000000  2003.000000
...               ...          ...
Ikoyi    10000.000000  2005.000000
Lekki    12000.000000  4003.000000
Gbagada   4666.666667  3334.666667
Ikoyi    10000.000000  2005.000000
Lekki    20000.000000  4005.000000

[2210 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3304.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ibadan    3307.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ikoyi     3306.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Lekki     3308.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Surulere  3309.5  NaN    NaN        NaN  3500.0       3.0  NaN  11000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4005.0
Ibadan    2001.0
Ikoyi     3001.0
Lekki     2003.0
Surulere  3503.0

[2214 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     3308.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
Surulere  3309.500000  NaN    NaN        NaN  3500.000000       3.0  NaN
Ibadan    3311.000000  NaN    NaN        NaN  3000.000000       5.0  NaN
Ikoyi     3313.333333  NaN    NaN        NaN  2666.666667       3.0  NaN
Lekki     3314.000000  NaN    NaN        NaN  4000.000000       4.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      6000.000000  2003.000000
Surulere  11000.000000  3503.000000
Ibadan    15000.000000  3005.000000
Ikoyi      9333.333333  2669.666667
Lekki     16000.000000  4004.000000

[2217 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3314.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Gbagada   3317.5  NaN    NaN        NaN  3500.0       3.0  NaN  11500.0
Ibadan    3316.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Lekki     3320.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  3319.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4004.0
Gbagada   3503.0
Ibadan    3004.0
Lekki     4005.0
Surulere  3005.0

[2221 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3319.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ibadan    3321.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ikoyi     3324.5  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki     3322.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Surulere  3323.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3005.0
Ibadan    2001.0
Ikoyi     2002.5
Lekki     2003.0
Surulere  2001.0

[2225 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3323.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Gbagada   3329.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ikoyi     3328.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Lekki     3327.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  3328.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2001.0
Gbagada   4002.0
Ikoyi     3004.0
Lekki     4002.0
Surulere  4001.0

[2229 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3327.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  3328.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ibadan    3332.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ikoyi     3334.5  NaN    NaN        NaN  3500.0       2.5  NaN   8000.0
Surulere  3332.0  NaN    NaN        NaN  4000.0       2.5  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4002.0
Surulere  4001.0
Ibadan    4004.0
Ikoyi     3502.5
Surulere  4002.5

[2232 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     3334.5  NaN    NaN        NaN  3500.0       2.5  NaN   8000.0
Surulere  3332.0  NaN    NaN        NaN  4000.0       2.5  NaN  10000.0
Gbagada   3339.0  NaN    NaN        NaN  3500.0       2.5  NaN   9500.0
Lekki     3336.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Surulere  3338.0  NaN    NaN        NaN  3500.0       3.5  NaN  11500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3502.5
Surulere  4002.5
Gbagada   3502.5
Lekki     4001.0
Surulere  3503.5

[2235 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3336.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Surulere  3338.0  NaN    NaN        NaN  3500.0       3.5  NaN  11500.0
Gbagada   3341.5  NaN    NaN        NaN  3500.0       2.5  NaN   9000.0
Ibadan    3345.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Lekki     3343.5  NaN    NaN        NaN  2000.0       3.5  NaN   7000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4001.0
Surulere  3503.5
Gbagada   3502.5
Ibadan    2003.0
Lekki     2003.5

[2238 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3343.5  NaN    NaN        NaN  2000.0       3.5  NaN   7000.0
Gbagada   3347.5  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ibadan    3350.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Lekki     3349.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  3346.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2003.5
Gbagada   3004.0
Ibadan    2002.0
Lekki     4005.0
Surulere  2001.0

[2242 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...               ...  ...    ...        ...     ...       ...  ...
Ibadan    3350.000000  NaN    NaN        NaN  2000.0  2.000000  NaN
Lekki     3349.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Surulere  3346.000000  NaN    NaN        NaN  2000.0  1.000000  NaN
Lekki     3353.333333  NaN    NaN        NaN  3000.0  2.666667  NaN
Surulere  3352.500000  NaN    NaN        NaN  2500.0  4.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ibadan     4000.000000  2002.000000
Lekki     20000.000000  4005.000000
Surulere   2000.000000  2001.000000
Lekki      7666.666667  3002.666667
Surulere   9500.000000  2504.000000

[2244 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   3357.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ibadan    3359.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ikoyi     3356.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Lekki     3358.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Surulere  3360.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   2003.0
Ibadan    4003.0
Ikoyi     4004.0
Lekki     2001.0
Surulere  3004.0

[2249 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3360.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ibadan    3364.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ikoyi     3364.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Lekki     3362.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  3361.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3004.0
Ibadan    2003.0
Ikoyi     3004.0
Lekki     4005.0
Surulere  3004.0

[2253 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3362.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  3361.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Gbagada   3369.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ikoyi     3367.5  NaN    NaN        NaN  3000.0       2.5  NaN   8000.0
Surulere  3368.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4005.0
Surulere  3004.0
Gbagada   2001.0
Ikoyi     3002.5
Surulere  2002.5

[2256 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3368.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Gbagada   3371.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ibadan    3375.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ikoyi     3374.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Surulere  3372.5  NaN    NaN        NaN  2500.0       1.5  NaN   3500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2002.5
Gbagada   4005.0
Ibadan    4004.0
Ikoyi     3002.0
Surulere  2501.5

[2260 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     3374.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Surulere  3372.5  NaN    NaN        NaN  2500.0       1.5  NaN   3500.0
Ibadan    3377.5  NaN    NaN        NaN  4000.0       1.5  NaN   6000.0
Ikoyi     3377.5  NaN    NaN        NaN  2500.0       3.0  NaN   8000.0
Lekki     3380.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3002.0
Surulere  2501.5
Ibadan    4001.5
Ikoyi     2503.0
Lekki     2003.0

[2263 rows x 9 columns]

                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     3377.500000  NaN    NaN        NaN  2500.000000  3.000000  NaN
Lekki     3380.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Gbagada   3381.000000  NaN    NaN        NaN  3000.000000  2.000000  NaN
Lekki     3383.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Surulere  3383.666667  NaN    NaN        NaN  3333.333333  3.333333  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi      8000.000000  2503.000000
Lekki      6000.000000  2003.000000
Gbagada    6000.000000  3002.000000
Lekki      8000.000000  4002.000000
Surulere  10333.333333  3336.666667

[2266 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Surulere  3383.666667  NaN    NaN        NaN  3333.333333  3.333333  NaN
Gbagada   3388.000000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Ikoyi     3386.000000  NaN    NaN        NaN  3000.000000  1.000000  NaN
Lekki     3389.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Surulere  3388.500000  NaN    NaN        NaN  3500.000000  4.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Surulere  10333.333333  3336.666667
Gbagada   12000.000000  4003.000000
Ikoyi      3000.000000  3001.000000
Lekki     10000.000000  2005.000000
Surulere  13500.000000  3504.000000

[2270 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000       3.0  NaN
...          ...  ...    ...        ...          ...       ...  ...
Lekki     3389.0  NaN    NaN        NaN  2000.000000       5.0  NaN
Surulere  3388.5  NaN    NaN        NaN  3500.000000       4.0  NaN
Gbagada   3394.0  NaN    NaN        NaN  3666.666667       4.0  NaN
Ibadan    3391.0  NaN    NaN        NaN  4000.000000       4.0  NaN
Surulere  3392.0  NaN    NaN        NaN  4000.000000       5.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki     10000.000000  2005.000000
Surulere  13500.000000  3504.000000
Gbagada   14333.333333  3670.666667
Ibadan    16000.000000  4004.000000
Surulere  20000.000000  4005.000000

[2273 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3392.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada   3399.5  NaN    NaN        NaN  3000.0       3.5  NaN  12000.0
Ikoyi     3398.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Lekki     3397.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  3396.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4005.0
Gbagada   3003.5
Ikoyi     4005.0
Lekki     4005.0
Surulere  4002.0

[2277 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3397.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  3396.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Gbagada   3404.0  NaN    NaN        NaN  3000.0       3.0  NaN  10000.0
Ibadan    3401.5  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  3404.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4005.0
Surulere  4002.0
Gbagada   3003.0
Ibadan    4003.0
Surulere  3002.0

[2280 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3404.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Gbagada   3410.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ibadan    3408.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Ikoyi     3407.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Lekki     3407.5  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3002.0
Gbagada   3005.0
Ibadan    2002.0
Ikoyi     4005.0
Lekki     4002.0

[2284 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ibadan    3408.000000  NaN    NaN        NaN  2000.000000       2.0  NaN
Ikoyi     3407.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Lekki     3407.500000  NaN    NaN        NaN  4000.000000       2.0  NaN
Ikoyi     3413.333333  NaN    NaN        NaN  2333.333333       3.0  NaN
Surulere  3412.500000  NaN    NaN        NaN  4000.000000       1.5  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ibadan     4000.000000  2002.000000
Ikoyi     20000.000000  4005.000000
Lekki      8000.000000  4002.000000
Ikoyi      6333.333333  2336.333333
Surulere   6000.000000  4001.500000

[2286 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     3413.333333  NaN    NaN        NaN  2333.333333       3.0  NaN
Surulere  3412.500000  NaN    NaN        NaN  4000.000000       1.5  NaN
Gbagada   3419.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Lekki     3416.500000  NaN    NaN        NaN  2500.000000       4.0  NaN
Surulere  3419.000000  NaN    NaN        NaN  4000.000000       3.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi      6333.333333  2336.333333
Surulere   6000.000000  4001.500000
Gbagada   20000.000000  4005.000000
Lekki     10500.000000  2504.000000
Surulere  12000.000000  4003.000000

[2289 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3419.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Gbagada   3424.5  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0
Ibadan    3423.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ikoyi     3421.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Lekki     3422.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4003.0
Gbagada   4003.5
Ibadan    3001.0
Ikoyi     2004.0
Lekki     4003.0

[2293 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     3421.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Lekki     3422.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Gbagada   3429.5  NaN    NaN        NaN  2500.0       4.0  NaN   9500.0
Lekki     3427.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  3427.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     2004.0
Lekki     4003.0
Gbagada   2504.0
Lekki     4003.0
Surulere  3002.0

[2296 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3427.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Gbagada   3431.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ibadan    3433.5  NaN    NaN        NaN  3500.0       5.0  NaN  17500.0
Ikoyi     3433.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Surulere  3434.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3002.0
Gbagada   4002.0
Ibadan    3505.0
Ikoyi     3002.0
Surulere  4004.0

[2300 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3434.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Gbagada   3438.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ibadan    3436.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ikoyi     3439.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Surulere  3438.5  NaN    NaN        NaN  3500.0       3.5  NaN  13000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4004.0
Gbagada   3002.0
Ibadan    3002.0
Ikoyi     3003.0
Surulere  3503.5

[2304 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3438.5  NaN    NaN        NaN  3500.0       3.5  NaN  13000.0
Gbagada   3444.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ibadan    3442.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Lekki     3443.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Surulere  3443.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3503.5
Gbagada   4004.0
Ibadan    3004.0
Lekki     3003.0
Surulere  3002.0

[2308 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3443.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Surulere  3443.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Gbagada   3448.5  NaN    NaN        NaN  3000.0       4.0  NaN  11000.0
Ikoyi     3448.5  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Surulere  3446.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3003.0
Surulere  3002.0
Gbagada   3004.0
Ikoyi     4001.0
Surulere  2005.0

[2311 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   3448.5  NaN    NaN        NaN  3000.0       4.0  NaN  11000.0
Ikoyi     3448.5  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Surulere  3446.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ibadan    3451.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ikoyi     3453.5  NaN    NaN        NaN  2500.0       4.5  NaN  11250.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   3004.0
Ikoyi     4001.0
Surulere  2005.0
Ibadan    2001.0
Ikoyi     2504.5

[2313 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    3451.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ikoyi     3453.5  NaN    NaN        NaN  2500.0       4.5  NaN  11250.0
Ikoyi     3459.5  NaN    NaN        NaN  3500.0       3.5  NaN  11500.0
Lekki     3457.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Surulere  3457.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    2001.0
Ikoyi     2504.5
Ikoyi     3503.5
Lekki     4001.0
Surulere  3003.0

[2316 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
...          ...  ...    ...        ...          ...       ...  ...      ...
Ikoyi     3459.5  NaN    NaN        NaN  3500.000000  3.500000  NaN  11500.0
Lekki     3457.0  NaN    NaN        NaN  4000.000000  1.000000  NaN   4000.0
Surulere  3457.0  NaN    NaN        NaN  3000.000000  3.000000  NaN   9000.0
Gbagada   3461.5  NaN    NaN        NaN  3000.000000  3.000000  NaN   8000.0
Ibadan    3464.0  NaN    NaN        NaN  2666.666667  3.333333  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3503.5
Lekki     4001.0
Surulere  3003.0
Gbagada   3003.0
Ibadan    2670.0

[2318 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
...          ...  ...    ...        ...          ...       ...  ...      ...
Gbagada   3461.5  NaN    NaN        NaN  3000.000000  3.000000  NaN   8000.0
Ibadan    3464.0  NaN    NaN        NaN  2666.666667  3.333333  NaN  10000.0
Gbagada   3468.5  NaN    NaN        NaN  3000.000000  2.000000  NaN   7000.0
Lekki     3468.5  NaN    NaN        NaN  3500.000000  4.000000  NaN  14000.0
Surulere  3466.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   3003.0
Ibadan    2670.0
Gbagada   3002.0
Lekki     3504.0
Surulere  2004.0

[2321 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3466.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Gbagada   3474.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ikoyi     3472.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Lekki     3475.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  3472.0  NaN    NaN        NaN  2500.0       4.5  NaN  11000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2004.0
Gbagada   3001.0
Ikoyi     2003.0
Lekki     4003.0
Surulere  2504.5

[2325 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3472.0  NaN    NaN        NaN  2500.0       4.5  NaN  11000.0
Ibadan    3477.5  NaN    NaN        NaN  3000.0       2.5  NaN   7500.0
Ikoyi     3479.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Lekki     3476.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Surulere  3480.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2504.5
Ibadan    3002.5
Ikoyi     2004.0
Lekki     2003.0
Surulere  2004.0

[2329 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3480.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Gbagada   3481.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ibadan    3485.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Ikoyi     3482.5  NaN    NaN        NaN  3500.0       3.5  NaN  12000.0
Lekki     3484.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2004.0
Gbagada   2003.0
Ibadan    2002.0
Ikoyi     3503.5
Lekki     4004.0

[2333 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     3482.5  NaN    NaN        NaN  3500.0       3.5  NaN  12000.0
Lekki     3484.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Gbagada   3487.0  NaN    NaN        NaN  3000.0       3.5  NaN   9000.0
Ikoyi     3488.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Surulere  3490.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3503.5
Lekki     4004.0
Gbagada   3003.5
Ikoyi     2003.0
Surulere  4004.0

[2336 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3490.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Gbagada   3494.0  NaN    NaN        NaN  3000.0       2.5  NaN   6000.0
Ibadan    3494.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ikoyi     3491.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Surulere  3492.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4004.0
Gbagada   3002.5
Ibadan    4001.0
Ikoyi     2002.0
Surulere  4004.0

[2340 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time       Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.000000
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.000000
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.000000
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.000000
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.000000
...          ...  ...    ...        ...     ...       ...  ...           ...
Ikoyi     3491.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.000000
Surulere  3492.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.000000
Gbagada   3499.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.000000
Lekki     3498.0  NaN    NaN        NaN  3000.0       3.0  NaN  10333.333333
Surulere  3497.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.000000

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     2002.0
Surulere  4004.0
Gbagada   2001.0
Lekki     3003.0
Surulere  4004.0

[2343 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3497.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Gbagada   3503.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan    3505.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ikoyi     3501.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     3503.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4004.0
Gbagada   2004.0
Ibadan    4004.0
Ikoyi     4001.0
Lekki     4001.0

[2347 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3503.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Gbagada   3508.5  NaN    NaN        NaN  3000.0       2.0  NaN   5000.0
Ibadan    3507.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Ikoyi     3506.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Surulere  3510.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4001.0
Gbagada   3002.0
Ibadan    2002.0
Ikoyi     2003.0
Surulere  2005.0

[2351 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     3506.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Surulere  3510.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Gbagada   3512.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ikoyi     3513.5  NaN    NaN        NaN  3500.0       2.5  NaN   9500.0
Lekki     3513.0  NaN    NaN        NaN  3500.0       5.0  NaN  17500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     2003.0
Surulere  2005.0
Gbagada   4002.0
Ikoyi     3502.5
Lekki     3505.0

[2354 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...               ...  ...    ...        ...     ...       ...  ...
Gbagada   3512.000000  NaN    NaN        NaN  4000.0  2.000000  NaN
Ikoyi     3513.500000  NaN    NaN        NaN  3500.0  2.500000  NaN
Lekki     3513.000000  NaN    NaN        NaN  3500.0  5.000000  NaN
Ikoyi     3517.500000  NaN    NaN        NaN  4000.0  1.500000  NaN
Surulere  3518.333333  NaN    NaN        NaN  3000.0  3.333333  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Gbagada    8000.000000  4002.000000
Ikoyi      9500.000000  3502.500000
Lekki     17500.000000  3505.000000
Ikoyi      6000.000000  4001.500000
Surulere  10666.666667  3003.333333

[2356 rows x 9 columns]

                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...               ...  ...    ...        ...     ...       ...  ...
Ikoyi     3517.500000  NaN    NaN        NaN  4000.0  1.500000  NaN
Surulere  3518.333333  NaN    NaN        NaN  3000.0  3.333333  NaN
Gbagada   3522.000000  NaN    NaN        NaN  3000.0  2.000000  NaN
Ibadan    3522.500000  NaN    NaN        NaN  3500.0  4.000000  NaN
Surulere  3524.000000  NaN    NaN        NaN  4000.0  5.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi      6000.000000  4001.500000
Surulere  10666.666667  3003.333333
Gbagada    6000.000000  3002.000000
Ibadan    14500.000000  3504.000000
Surulere  20000.000000  4005.000000

[2359 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    3522.5  NaN    NaN        NaN  3500.0       4.0  NaN  14500.0
Surulere  3524.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ikoyi     3527.5  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Lekki     3528.0  NaN    NaN        NaN  2500.0       2.0  NaN   5500.0
Surulere  3529.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    3504.0
Surulere  4005.0
Ikoyi     3001.0
Lekki     2502.0
Surulere  3001.0

[2362 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3529.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ibadan    3534.0  NaN    NaN        NaN  3000.0       3.5  NaN  11000.0
Ikoyi     3531.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Lekki     3534.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  3532.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3001.0
Ibadan    3003.5
Ikoyi     3004.0
Lekki     4002.0
Surulere  4005.0

[2366 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     3534.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Surulere  3532.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Ibadan    3538.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ikoyi     3537.333333  NaN    NaN        NaN  2666.666667  3.333333  NaN
Surulere  3540.000000  NaN    NaN        NaN  4000.000000  3.000000  NaN

          Revenue    Snap
Gbagada    8000.0  2004.0
Ibadan    10000.0  2005.0
Ikoyi      5000.0  2002.5
Lekki     20000.0  4005.0
Gbagada    6000.0  2003.0
...           ...     ...
Lekki      8000.0  4002.0
Surulere  20000.0  4005.0
Ibadan     8000.0  2004.0
Ikoyi      9000.0  2670.0
Surulere  12000.0  4003.0

[2369 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   3543.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ibadan    3542.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ikoyi     3544.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Lekki     3545.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Surulere  3541.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   3005.0
Ibadan    4003.0
Ikoyi     2003.0
Lekki     2001.0
Surulere  2004.0

[2374 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3545.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Surulere  3541.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan    3548.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ikoyi     3548.5  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Surulere  3547.5  NaN    NaN        NaN  3000.0       2.5  NaN   7500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2001.0
Surulere  2004.0
Ibadan    3005.0
Ikoyi     2002.0
Surulere  3002.5

[2377 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     3548.5  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Surulere  3547.5  NaN    NaN        NaN  3000.0       2.5  NaN   7500.0
Ikoyi     3552.5  NaN    NaN        NaN  2000.0       4.5  NaN   9000.0
Lekki     3555.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  3552.5  NaN    NaN        NaN  3500.0       2.0  NaN   6500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     2002.0
Surulere  3002.5
Ikoyi     2004.5
Lekki     4005.0
Surulere  3502.0

[2380 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     3555.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Surulere  3552.500000  NaN    NaN        NaN  3500.000000  2.000000  NaN
Ibadan    3560.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Ikoyi     3557.666667  NaN    NaN        NaN  3333.333333  2.333333  NaN
Lekki     3557.000000  NaN    NaN        NaN  3000.000000  1.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki     20000.000000  4005.000000
Surulere   6500.000000  3502.000000
Ibadan    20000.000000  4005.000000
Ikoyi      7666.666667  3335.666667
Lekki      3000.000000  3001.000000

[2383 rows x 9 columns]
                 S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...              ...  ...    ...        ...          ...       ...  ...
Ikoyi    3557.666667  NaN    NaN        NaN  3333.333333  2.333333  NaN
Lekki    3557.000000  NaN    NaN        NaN  3000.000000  1.000000  NaN
Gbagada  3563.333333  NaN    NaN        NaN  3333.333333  3.333333  NaN
Ibadan   3561.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Lekki    3564.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN

              Revenue         Snap
Gbagada   8000.000000  2004.000000
Ibadan   10000.000000  2005.000000
Ikoyi     5000.000000  2002.500000
Lekki    20000.000000  4005.000000
Gbagada   6000.000000  2003.000000
...               ...          ...
Ikoyi     7666.666667  3335.666667
Lekki     3000.000000  3001.000000
Gbagada  11666.666667  3336.666667
Ibadan    8000.000000  2004.000000
Lekki     8000.000000  4002.000000

[2386 rows x 9 columns]

            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ibadan   3561.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Lekki    3564.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Gbagada  3570.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi    3568.5  NaN    NaN        NaN  3500.0       2.5  NaN   9500.0  3502.5
Lekki    3566.5  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0  4003.5

[2389 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi    3568.5  NaN    NaN        NaN  3500.0       2.5  NaN   9500.0  3502.5
Lekki    3566.5  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0  4003.5
Ibadan   3573.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Ikoyi    3573.0  NaN    NaN        NaN  3000.0       2.5  NaN   8000.0  3002.5
Lekki    3573.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0  3001.0

[2392 rows x 9 columns]
                 S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...              ...  ...    ...        ...     ...       ...  ...
Ikoyi    3573.000000  NaN    NaN        NaN  3000.0  2.500000  NaN
Lekki    3573.000000  NaN    NaN        NaN  3000.0  1.000000  NaN
Ibadan   3576.000000  NaN    NaN        NaN  4000.0  4.000000  NaN
Ikoyi    3578.666667  NaN    NaN        NaN  4000.0  2.666667  NaN
Lekki    3578.000000  NaN    NaN        NaN  4000.0  1.000000  NaN

              Revenue         Snap
Gbagada   8000.000000  2004.000000
Ibadan   10000.000000  2005.000000
Ikoyi     5000.000000  2002.500000
Lekki    20000.000000  4005.000000
Gbagada   6000.000000  2003.000000
...               ...          ...
Ikoyi     8000.000000  3002.500000
Lekki     3000.000000  3001.000000
Ibadan   16000.000000  4004.000000
Ikoyi    10666.666667  4002.666667
Lekki     4000.000000  4001.000000

[2395 rows x 9 columns]
                 S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...              ...  ...    ...        ...     ...       ...  ...
Ibadan   3576.000000  NaN    NaN        NaN  4000.0  4.000000  NaN
Ikoyi    3578.666667  NaN    NaN        NaN  4000.0  2.666667  NaN
Lekki    3578.000000  NaN    NaN        NaN  4000.0  1.000000  NaN
Ibadan   3583.500000  NaN    NaN        NaN  3250.0  4.000000  NaN
Ikoyi    3581.000000  NaN    NaN        NaN  4000.0  4.000000  NaN

              Revenue         Snap
Gbagada   8000.000000  2004.000000
Ibadan   10000.000000  2005.000000
Ikoyi     5000.000000  2002.500000
Lekki    20000.000000  4005.000000
Gbagada   6000.000000  2003.000000
...               ...          ...
Ibadan   16000.000000  4004.000000
Ikoyi    10666.666667  4002.666667
Lekki     4000.000000  4001.000000
Ibadan   12750.000000  3254.000000
Ikoyi    16000.000000  4004.000000

[2397 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     3581.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ibadan    3590.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ikoyi     3589.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Lekki     3586.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Surulere  3587.5  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     4004.0
Ibadan    4001.0
Ikoyi     2003.0
Lekki     3004.0
Surulere  4003.5

[2401 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3587.5  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0
Gbagada   3591.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ibadan    3592.5  NaN    NaN        NaN  3000.0       3.5  NaN  10000.0
Lekki     3594.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  3595.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4003.5
Gbagada   4003.0
Ibadan    3003.5
Lekki     4002.0
Surulere  3002.0

[2405 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3594.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  3595.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Gbagada   3599.5  NaN    NaN        NaN  2500.0       3.0  NaN   6500.0
Lekki     3597.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Surulere  3597.0  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4002.0
Surulere  3002.0
Gbagada   2503.0
Lekki     2003.0
Surulere  4003.5

[2408 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3597.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Surulere  3597.0  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0
Gbagada   3602.5  NaN    NaN        NaN  2500.0       2.0  NaN   4500.0
Ibadan    3601.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Lekki     3604.5  NaN    NaN        NaN  2500.0       2.5  NaN   7000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2003.0
Surulere  4003.5
Gbagada   2502.0
Ibadan    2003.0
Lekki     2502.5

[2411 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    3601.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Lekki     3604.5  NaN    NaN        NaN  2500.0       2.5  NaN   7000.0
Ibadan    3607.0  NaN    NaN        NaN  3000.0       2.5  NaN   6000.0
Lekki     3609.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Surulere  3608.5  NaN    NaN        NaN  2500.0       4.0  NaN  10500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    2003.0
Lekki     2502.5
Ibadan    3002.5
Lekki     3001.0
Surulere  2504.0

[2414 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...               ...  ...    ...        ...     ...       ...  ...
Lekki     3609.000000  NaN    NaN        NaN  3000.0  1.000000  NaN
Surulere  3608.500000  NaN    NaN        NaN  2500.0  4.000000  NaN
Ikoyi     3613.000000  NaN    NaN        NaN  4000.0  2.000000  NaN
Lekki     3612.000000  NaN    NaN        NaN  3000.0  2.000000  NaN
Surulere  3613.333333  NaN    NaN        NaN  3000.0  4.666667  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      3000.000000  3001.000000
Surulere  10500.000000  2504.000000
Ikoyi      8000.000000  4002.000000
Lekki      6000.000000  3002.000000
Surulere  14333.333333  3004.666667

[2417 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     3612.000000  NaN    NaN        NaN  3000.000000  2.000000  NaN
Surulere  3613.333333  NaN    NaN        NaN  3000.000000  4.666667  NaN
Gbagada   3619.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Ibadan    3620.000000  NaN    NaN        NaN  2000.000000  1.000000  NaN
Surulere  3617.000000  NaN    NaN        NaN  3666.666667  3.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      6000.000000  3002.000000
Surulere  14333.333333  3004.666667
Gbagada    8000.000000  4002.000000
Ibadan     2000.000000  2001.000000
Surulere  10666.666667  3669.666667

[2420 rows x 9 columns]

             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000       3.0  NaN
...          ...  ...    ...        ...          ...       ...  ...
Ibadan    3620.0  NaN    NaN        NaN  2000.000000       1.0  NaN
Surulere  3617.0  NaN    NaN        NaN  3666.666667       3.0  NaN
Ibadan    3624.5  NaN    NaN        NaN  2000.000000       3.5  NaN
Ikoyi     3622.0  NaN    NaN        NaN  3000.000000       3.0  NaN
Lekki     3622.0  NaN    NaN        NaN  2000.000000       4.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ibadan     2000.000000  2001.000000
Surulere  10666.666667  3669.666667
Ibadan     7000.000000  2003.500000
Ikoyi      9000.000000  3003.000000
Lekki      8000.000000  2004.000000

[2423 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     3622.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Lekki     3622.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan    3627.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Lekki     3628.0  NaN    NaN        NaN  3000.0       2.0  NaN   5000.0
Surulere  3630.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3003.0
Lekki     2004.0
Ibadan    2001.0
Lekki     3002.0
Surulere  4003.0

[2426 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0      4.00  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0      5.00  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0      2.50  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0      5.00  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0      3.00  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    3627.0  NaN    NaN        NaN  2000.0      1.00  NaN   2000.0
Lekki     3628.0  NaN    NaN        NaN  3000.0      2.00  NaN   5000.0
Surulere  3630.0  NaN    NaN        NaN  4000.0      3.00  NaN  12000.0
Lekki     3633.0  NaN    NaN        NaN  3000.0      4.25  NaN  13000.0
Surulere  3633.0  NaN    NaN        NaN  3000.0      1.00  NaN   3000.0

             Snap
Gbagada   2004.00
Ibadan    2005.00
Ikoyi     2002.50
Lekki     4005.00
Gbagada   2003.00
...           ...
Ibadan    2001.00
Lekki     3002.00
Surulere  4003.00
Lekki     3004.25
Surulere  3001.00

[2428 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3633.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Gbagada   3638.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ibadan    3636.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Lekki     3639.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Surulere  3638.5  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3001.0
Gbagada   3005.0
Ibadan    2004.0
Lekki     4004.0
Surulere  4003.0

[2432 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   3645.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ibadan    3641.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ikoyi     3644.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     3643.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Surulere  3642.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   4002.0
Ibadan    4001.0
Ikoyi     4001.0
Lekki     3004.0
Surulere  4003.0

[2437 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3643.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Surulere  3642.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Gbagada   3649.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Lekki     3648.0  NaN    NaN        NaN  2000.0       4.5  NaN   9000.0
Surulere  3647.5  NaN    NaN        NaN  3500.0       2.5  NaN   9500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3004.0
Surulere  4003.0
Gbagada   3002.0
Lekki     2004.5
Surulere  3502.5

[2440 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3647.5  NaN    NaN        NaN  3500.0       2.5  NaN   9500.0
Ibadan    3651.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ikoyi     3654.5  NaN    NaN        NaN  3000.0       4.5  NaN  14000.0
Lekki     3652.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  3653.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3502.5
Ibadan    4004.0
Ikoyi     3004.5
Lekki     4005.0
Surulere  2002.0

[2444 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3653.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Gbagada   3657.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ikoyi     3659.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Lekki     3660.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Surulere  3657.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2002.0
Gbagada   4005.0
Ikoyi     2001.0
Lekki     2005.0
Surulere  3003.0

[2448 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3657.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Gbagada   3664.5  NaN    NaN        NaN  3500.0       3.5  NaN  12000.0
Ibadan    3661.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     3663.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  3662.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3003.0
Gbagada   3503.5
Ibadan    4001.0
Lekki     4005.0
Surulere  2003.0

[2452 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3662.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Gbagada   3666.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ibadan    3667.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ikoyi     3669.0  NaN    NaN        NaN  2500.0       2.0  NaN   5500.0
Surulere  3669.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2003.0
Gbagada   3005.0
Ibadan    2003.0
Ikoyi     2502.0
Surulere  2004.0

[2456 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    3667.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ikoyi     3669.0  NaN    NaN        NaN  2500.0       2.0  NaN   5500.0
Surulere  3669.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan    3673.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Surulere  3673.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    2003.0
Ikoyi     2502.0
Surulere  2004.0
Ibadan    3001.0
Surulere  4004.0

[2458 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
...          ...  ...    ...        ...          ...       ...  ...      ...
Ibadan    3673.0  NaN    NaN        NaN  3000.000000  1.000000  NaN   3000.0
Surulere  3673.0  NaN    NaN        NaN  4000.000000  4.000000  NaN  16000.0
Ibadan    3679.0  NaN    NaN        NaN  2666.666667  2.333333  NaN   8000.0
Lekki     3676.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Surulere  3677.0  NaN    NaN        NaN  4000.000000  1.000000  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    3001.0
Surulere  4004.0
Ibadan    2669.0
Lekki     2005.0
Surulere  4001.0

[2461 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     3676.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Surulere  3677.000000  NaN    NaN        NaN  4000.000000  1.000000  NaN
Gbagada   3684.000000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Ibadan    3683.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Ikoyi     3682.666667  NaN    NaN        NaN  3333.333333  2.666667  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Lekki     10000.000000  2005.0
Surulere   4000.000000  4001.0
Gbagada   12000.000000  4003.0
Ibadan     8000.000000  4002.0
Ikoyi      9666.666667  3336.0

[2464 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     3682.666667  NaN    NaN        NaN  3333.333333  2.666667  NaN
Gbagada   3688.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ikoyi     3689.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Lekki     3690.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN
Surulere  3686.500000  NaN    NaN        NaN  4000.000000  3.500000  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Ikoyi      9666.666667  3336.0
Gbagada    8000.000000  2004.0
Ikoyi      8000.000000  4002.0
Lekki     16000.000000  4004.0
Surulere  14000.000000  4003.5

[2468 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3690.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Surulere  3686.5  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0
Gbagada   3694.5  NaN    NaN        NaN  3500.0       3.5  NaN  12000.0
Lekki     3693.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Surulere  3691.5  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4004.0
Surulere  4003.5
Gbagada   3503.5
Lekki     4004.0
Surulere  3003.0

[2471 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...               ...  ...    ...        ...     ...       ...  ...
Lekki     3693.000000  NaN    NaN        NaN  4000.0  4.000000  NaN
Surulere  3691.500000  NaN    NaN        NaN  3000.0  3.000000  NaN
Ibadan    3699.000000  NaN    NaN        NaN  4000.0  4.000000  NaN
Ikoyi     3698.000000  NaN    NaN        NaN  3000.0  3.000000  NaN
Surulere  3697.666667  NaN    NaN        NaN  4000.0  3.333333  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki     16000.000000  4004.000000
Surulere   9000.000000  3003.000000
Ibadan    16000.000000  4004.000000
Ikoyi      9000.000000  3003.000000
Surulere  13333.333333  4003.333333

[2474 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...               ...  ...    ...        ...     ...       ...  ...
Surulere  3697.666667  NaN    NaN        NaN  4000.0  3.333333  NaN
Ibadan    3701.000000  NaN    NaN        NaN  3000.0  4.000000  NaN
Ikoyi     3703.500000  NaN    NaN        NaN  3500.0  3.000000  NaN
Lekki     3704.000000  NaN    NaN        NaN  4000.0  2.000000  NaN
Surulere  3703.000000  NaN    NaN        NaN  2000.0  5.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Surulere  13333.333333  4003.333333
Ibadan    12000.000000  3004.000000
Ikoyi     11500.000000  3503.000000
Lekki      8000.000000  4002.000000
Surulere  10000.000000  2005.000000

[2478 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...          ...  ...    ...        ...          ...       ...  ...
Lekki     3704.0  NaN    NaN        NaN  4000.000000  2.000000  NaN
Surulere  3703.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Gbagada   3707.0  NaN    NaN        NaN  3333.333333  3.666667  NaN
Ikoyi     3709.0  NaN    NaN        NaN  4000.000000  2.000000  NaN
Surulere  3710.0  NaN    NaN        NaN  4000.000000  3.000000  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Lekki      8000.000000  4002.0
Surulere  10000.000000  2005.0
Gbagada   11333.333333  3337.0
Ikoyi      8000.000000  4002.0
Surulere  12000.000000  4003.0

[2481 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...          ...  ...    ...        ...          ...       ...  ...
Gbagada   3707.0  NaN    NaN        NaN  3333.333333  3.666667  NaN
Ikoyi     3709.0  NaN    NaN        NaN  4000.000000  2.000000  NaN
Surulere  3710.0  NaN    NaN        NaN  4000.000000  3.000000  NaN
Gbagada   3713.0  NaN    NaN        NaN  4000.000000  3.000000  NaN
Ikoyi     3713.0  NaN    NaN        NaN  3333.333333  2.666667  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Gbagada   11333.333333  3337.0
Ikoyi      8000.000000  4002.0
Surulere  12000.000000  4003.0
Gbagada   12000.000000  4003.0
Ikoyi      8000.000000  3336.0

[2483 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
...          ...  ...    ...        ...          ...       ...  ...      ...
Gbagada   3713.0  NaN    NaN        NaN  4000.000000  3.000000  NaN  12000.0
Ikoyi     3713.0  NaN    NaN        NaN  3333.333333  2.666667  NaN   8000.0
Ibadan    3718.5  NaN    NaN        NaN  3500.000000  3.000000  NaN   9500.0
Ikoyi     3718.5  NaN    NaN        NaN  3500.000000  3.000000  NaN  11000.0
Surulere  3716.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   4003.0
Ikoyi     3336.0
Ibadan    3503.0
Ikoyi     3503.0
Surulere  2004.0

[2486 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3716.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Gbagada   3721.5  NaN    NaN        NaN  2000.0       3.5  NaN   7000.0
Ibadan    3724.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Lekki     3723.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Surulere  3725.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2004.0
Gbagada   2003.5
Ibadan    3003.0
Lekki     3002.0
Surulere  4001.0

[2490 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time       Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.000000
Ibadan       1.0  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.000000
Ikoyi        3.0  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.000000
Lekki        3.0  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.000000
Gbagada      9.0  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.000000
...          ...  ...    ...        ...     ...       ...  ...           ...
Ibadan    3724.0  NaN    NaN        NaN  3000.0  3.000000  NaN   9000.000000
Lekki     3723.0  NaN    NaN        NaN  3000.0  2.000000  NaN   6000.000000
Surulere  3725.0  NaN    NaN        NaN  4000.0  1.000000  NaN   4000.000000
Ibadan    3726.5  NaN    NaN        NaN  3000.0  2.000000  NaN   7000.000000
Ikoyi     3729.0  NaN    NaN        NaN  4000.0  3.666667  NaN  14666.666667

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Ibadan    3003.000000
Lekki     3002.000000
Surulere  4001.000000
Ibadan    3002.000000
Ikoyi     4003.666667

[2492 rows x 9 columns]
                 S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...              ...  ...    ...        ...     ...       ...  ...
Ibadan   3726.500000  NaN    NaN        NaN  3000.0  2.000000  NaN
Ikoyi    3729.000000  NaN    NaN        NaN  4000.0  3.666667  NaN
Gbagada  3733.000000  NaN    NaN        NaN  4000.0  1.000000  NaN
Ibadan   3734.000000  NaN    NaN        NaN  3000.0  2.000000  NaN
Ikoyi    3732.666667  NaN    NaN        NaN  4000.0  3.333333  NaN

              Revenue         Snap
Gbagada   8000.000000  2004.000000
Ibadan   10000.000000  2005.000000
Ikoyi     5000.000000  2002.500000
Lekki    20000.000000  4005.000000
Gbagada   6000.000000  2003.000000
...               ...          ...
Ibadan    7000.000000  3002.000000
Ikoyi    14666.666667  4003.666667
Gbagada   4000.000000  4001.000000
Ibadan    6000.000000  3002.000000
Ikoyi    13333.333333  4003.333333

[2495 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...               ...  ...    ...        ...     ...       ...  ...
Ibadan    3734.000000  NaN    NaN        NaN  3000.0  2.000000  NaN
Ikoyi     3732.666667  NaN    NaN        NaN  4000.0  3.333333  NaN
Ibadan    3737.000000  NaN    NaN        NaN  3000.0  1.000000  NaN
Ikoyi     3737.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
Surulere  3739.500000  NaN    NaN        NaN  3000.0  3.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ibadan     6000.000000  3002.000000
Ikoyi     13333.333333  4003.333333
Ibadan     3000.000000  3001.000000
Ikoyi      6000.000000  2003.000000
Surulere   7000.000000  3003.000000

[2498 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3739.5  NaN    NaN        NaN  3000.0       3.0  NaN   7000.0
Gbagada   3743.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ibadan    3745.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Lekki     3742.5  NaN    NaN        NaN  3500.0       2.0  NaN   6500.0
Surulere  3742.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3003.0
Gbagada   3004.0
Ibadan    3001.0
Lekki     3502.0
Surulere  3004.0

[2502 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     3742.500000  NaN    NaN        NaN  3500.000000       2.0  NaN
Surulere  3742.000000  NaN    NaN        NaN  3000.000000       4.0  NaN
Gbagada   3748.333333  NaN    NaN        NaN  3333.333333       3.0  NaN
Ibadan    3747.000000  NaN    NaN        NaN  3000.000000       1.0  NaN
Surulere  3748.000000  NaN    NaN        NaN  3000.000000       4.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      6500.000000  3502.000000
Surulere  12000.000000  3004.000000
Gbagada    9666.666667  3336.333333
Ibadan     3000.000000  3001.000000
Surulere  12000.000000  3004.000000

[2505 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3748.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ibadan    3753.0  NaN    NaN        NaN  3000.0       4.0  NaN  13000.0
Ikoyi     3751.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Lekki     3755.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Surulere  3753.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3004.0
Ibadan    3004.0
Ikoyi     3003.0
Lekki     3002.0
Surulere  4002.0

[2509 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3753.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Gbagada   3757.0  NaN    NaN        NaN  2500.0       2.0  NaN   4500.0
Ibadan    3760.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ikoyi     3757.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  3759.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4002.0
Gbagada   2502.0
Ibadan    4003.0
Ikoyi     4003.0
Surulere  3003.0

[2513 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...               ...  ...    ...        ...     ...       ...  ...
Ikoyi     3757.000000  NaN    NaN        NaN  4000.0  3.000000  NaN
Surulere  3759.000000  NaN    NaN        NaN  3000.0  3.000000  NaN
Ibadan    3763.000000  NaN    NaN        NaN  4000.0  3.000000  NaN
Ikoyi     3762.666667  NaN    NaN        NaN  2000.0  2.333333  NaN
Lekki     3764.000000  NaN    NaN        NaN  4000.0  4.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi     12000.000000  4003.000000
Surulere   9000.000000  3003.000000
Ibadan    12000.000000  4003.000000
Ikoyi      4666.666667  2002.333333
Lekki     16000.000000  4004.000000

[2516 rows x 9 columns]
                 S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...              ...  ...    ...        ...     ...       ...  ...
Ibadan   3763.000000  NaN    NaN        NaN  4000.0  3.000000  NaN
Ikoyi    3762.666667  NaN    NaN        NaN  2000.0  2.333333  NaN
Lekki    3764.000000  NaN    NaN        NaN  4000.0  4.000000  NaN
Gbagada  3768.666667  NaN    NaN        NaN  3000.0  3.000000  NaN
Ikoyi    3767.000000  NaN    NaN        NaN  3500.0  2.500000  NaN

              Revenue         Snap
Gbagada   8000.000000  2004.000000
Ibadan   10000.000000  2005.000000
Ikoyi     5000.000000  2002.500000
Lekki    20000.000000  4005.000000
Gbagada   6000.000000  2003.000000
...               ...          ...
Ibadan   12000.000000  4003.000000
Ikoyi     4666.666667  2002.333333
Lekki    16000.000000  4004.000000
Gbagada   8333.333333  3003.000000
Ikoyi     9500.000000  3502.500000

[2518 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...               ...  ...    ...        ...     ...       ...  ...
Gbagada   3768.666667  NaN    NaN        NaN  3000.0  3.000000  NaN
Ikoyi     3767.000000  NaN    NaN        NaN  3500.0  2.500000  NaN
Ibadan    3774.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ikoyi     3773.333333  NaN    NaN        NaN  4000.0  3.333333  NaN
Surulere  3771.000000  NaN    NaN        NaN  2000.0  5.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Gbagada    8333.333333  3003.000000
Ikoyi      9500.000000  3502.500000
Ibadan     8000.000000  2004.000000
Ikoyi     13333.333333  4003.333333
Surulere  10000.000000  2005.000000

[2521 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   3778.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan    3776.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ikoyi     3777.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Lekki     3779.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Surulere  3780.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   2004.0
Ibadan    2003.0
Ikoyi     2001.0
Lekki     2004.0
Surulere  4004.0

[2526 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.000000       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.000000       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.000000       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.000000       3.0  NaN   6000.0
...          ...  ...    ...        ...          ...       ...  ...      ...
Lekki     3779.0  NaN    NaN        NaN  2000.000000       4.0  NaN   8000.0
Surulere  3780.0  NaN    NaN        NaN  4000.000000       4.0  NaN  16000.0
Gbagada   3782.0  NaN    NaN        NaN  4000.000000       2.0  NaN   8000.0
Lekki     3781.0  NaN    NaN        NaN  2000.000000       3.0  NaN   6000.0
Surulere  3784.0  NaN    NaN        NaN  3333.333333       3.0  NaN  10000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Lekki     2004.000000
Surulere  4004.000000
Gbagada   4002.000000
Lekki     2003.000000
Surulere  3336.333333

[2529 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.000000       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.000000       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.000000       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.000000       3.0  NaN   6000.0
...          ...  ...    ...        ...          ...       ...  ...      ...
Lekki     3781.0  NaN    NaN        NaN  2000.000000       3.0  NaN   6000.0
Surulere  3784.0  NaN    NaN        NaN  3333.333333       3.0  NaN  10000.0
Gbagada   3788.5  NaN    NaN        NaN  3500.000000       1.0  NaN   3500.0
Ibadan    3788.0  NaN    NaN        NaN  2000.000000       5.0  NaN  10000.0
Surulere  3787.5  NaN    NaN        NaN  3500.000000       3.5  NaN  12000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Lekki     2003.000000
Surulere  3336.333333
Gbagada   3501.000000
Ibadan    2005.000000
Surulere  3503.500000

[2532 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3787.5  NaN    NaN        NaN  3500.0       3.5  NaN  12000.0
Gbagada   3792.5  NaN    NaN        NaN  3500.0       3.5  NaN  11500.0
Ibadan    3791.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ikoyi     3794.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Lekki     3795.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3503.5
Gbagada   3503.5
Ibadan    4002.0
Ikoyi     3002.0
Lekki     3003.0

[2536 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi    3794.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0  3002.0
Lekki    3795.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Gbagada  3798.5  NaN    NaN        NaN  3000.0       3.5  NaN  11000.0  3003.5
Ibadan   3798.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0  3001.0
Lekki    3797.5  NaN    NaN        NaN  3000.0       3.0  NaN   7000.0  3003.0

[2539 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ibadan   3798.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0  3001.0
Lekki    3797.5  NaN    NaN        NaN  3000.0       3.0  NaN   7000.0  3003.0
Gbagada  3803.0  NaN    NaN        NaN  3500.0       3.5  NaN  11500.0  3503.5
Ibadan   3803.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Ikoyi    3803.0  NaN    NaN        NaN  3000.0       2.0  NaN   7000.0  3002.0

[2542 rows x 9 columns]
                 S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...              ...  ...    ...        ...     ...       ...  ...
Ibadan   3803.000000  NaN    NaN        NaN  2000.0  1.000000  NaN
Ikoyi    3803.000000  NaN    NaN        NaN  3000.0  2.000000  NaN
Ibadan   3808.666667  NaN    NaN        NaN  3000.0  3.666667  NaN
Ikoyi    3808.000000  NaN    NaN        NaN  4000.0  2.000000  NaN
Lekki    3806.000000  NaN    NaN        NaN  2000.0  1.000000  NaN

              Revenue         Snap
Gbagada   8000.000000  2004.000000
Ibadan   10000.000000  2005.000000
Ikoyi     5000.000000  2002.500000
Lekki    20000.000000  4005.000000
Gbagada   6000.000000  2003.000000
...               ...          ...
Ibadan    2000.000000  2001.000000
Ikoyi     7000.000000  3002.000000
Ibadan   10666.666667  3003.666667
Ikoyi     8000.000000  4002.000000
Lekki     2000.000000  2001.000000

[2545 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     3808.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Lekki     3806.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Gbagada   3811.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ibadan    3812.5  NaN    NaN        NaN  3500.0       1.0  NaN   3500.0
Surulere  3814.5  NaN    NaN        NaN  3500.0       3.5  NaN  11500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     4002.0
Lekki     2001.0
Gbagada   3005.0
Ibadan    3501.0
Surulere  3503.5

[2548 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    3812.5  NaN    NaN        NaN  3500.0       1.0  NaN   3500.0
Surulere  3814.5  NaN    NaN        NaN  3500.0       3.5  NaN  11500.0
Gbagada   3818.0  NaN    NaN        NaN  3500.0       3.0  NaN  10500.0
Ikoyi     3818.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Surulere  3818.0  NaN    NaN        NaN  3000.0       2.5  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    3501.0
Surulere  3503.5
Gbagada   3503.0
Ikoyi     4004.0
Surulere  3002.5

[2551 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3818.0  NaN    NaN        NaN  3000.0       2.5  NaN   9000.0
Gbagada   3822.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ibadan    3825.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ikoyi     3821.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     3823.5  NaN    NaN        NaN  3500.0       4.5  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3002.5
Gbagada   3004.0
Ibadan    2001.0
Ikoyi     4003.0
Lekki     3504.5

[2555 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     3821.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     3823.5  NaN    NaN        NaN  3500.0       4.5  NaN  16000.0
Ibadan    3827.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     3829.5  NaN    NaN        NaN  3500.0       5.0  NaN  17500.0
Surulere  3827.0  NaN    NaN        NaN  2000.0       4.5  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     4003.0
Lekki     3504.5
Ibadan    4001.0
Lekki     3505.0
Surulere  2004.5

[2558 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3827.0  NaN    NaN        NaN  2000.0       4.5  NaN   9000.0
Gbagada   3834.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Ibadan    3832.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Ikoyi     3834.0  NaN    NaN        NaN  3500.0       4.5  NaN  16000.0
Lekki     3831.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2004.5
Gbagada   2002.0
Ibadan    3003.0
Ikoyi     3504.5
Lekki     2004.0

[2562 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   3837.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ibadan    3836.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ikoyi     3840.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Lekki     3838.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Surulere  3839.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   4003.0
Ibadan    4005.0
Ikoyi     2001.0
Lekki     4004.0
Surulere  3005.0

[2567 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3838.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Surulere  3839.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Gbagada   3842.5  NaN    NaN        NaN  2500.0       4.0  NaN  10500.0
Ibadan    3841.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Surulere  3844.5  NaN    NaN        NaN  2500.0       3.5  NaN   9500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4004.0
Surulere  3005.0
Gbagada   2504.0
Ibadan    2004.0
Surulere  2503.5

[2570 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3844.5  NaN    NaN        NaN  2500.0       3.5  NaN   9500.0
Gbagada   3847.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ibadan    3847.5  NaN    NaN        NaN  3500.0       3.0  NaN  11500.0
Lekki     3850.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  3848.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2503.5
Gbagada   2003.0
Ibadan    3503.0
Lekki     4002.0
Surulere  3002.0

[2574 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3850.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  3848.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ibadan    3851.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ikoyi     3854.0  NaN    NaN        NaN  3500.0       2.5  NaN   9000.0
Lekki     3853.0  NaN    NaN        NaN  3500.0       3.5  NaN  11500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4002.0
Surulere  3002.0
Ibadan    4003.0
Ikoyi     3502.5
Lekki     3503.5

[2577 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   3859.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ibadan    3858.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ikoyi     3857.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Lekki     3856.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Surulere  3860.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   2003.0
Ibadan    4001.0
Ikoyi     4002.0
Lekki     3003.0
Surulere  4003.0

[2582 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3856.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Surulere  3860.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Gbagada   3863.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ikoyi     3862.5  NaN    NaN        NaN  2000.0       4.5  NaN   9000.0
Surulere  3863.5  NaN    NaN        NaN  3500.0       4.0  NaN  13500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3003.0
Surulere  4003.0
Gbagada   4003.0
Ikoyi     2004.5
Surulere  3504.0

[2585 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     3862.5  NaN    NaN        NaN  2000.0       4.5  NaN   9000.0
Surulere  3863.5  NaN    NaN        NaN  3500.0       4.0  NaN  13500.0
Ibadan    3867.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ikoyi     3868.5  NaN    NaN        NaN  3000.0       2.5  NaN   6000.0
Surulere  3868.0  NaN    NaN        NaN  3500.0       4.0  NaN  14000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     2004.5
Surulere  3504.0
Ibadan    2001.0
Ikoyi     3002.5
Surulere  3504.0

[2588 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     3868.5  NaN    NaN        NaN  3000.0       2.5  NaN   6000.0
Surulere  3868.0  NaN    NaN        NaN  3500.0       4.0  NaN  14000.0
Gbagada   3873.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ibadan    3873.0  NaN    NaN        NaN  2500.0       2.5  NaN   7000.0
Ikoyi     3873.0  NaN    NaN        NaN  3000.0       3.0  NaN   7000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3002.5
Surulere  3504.0
Gbagada   3001.0
Ibadan    2502.5
Ikoyi     3003.0

[2591 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     3873.0  NaN    NaN        NaN  3000.0       3.0  NaN   7000.0
Ibadan    3877.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ikoyi     3877.5  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Lekki     3878.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  3880.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3003.0
Ibadan    4003.0
Ikoyi     3002.0
Lekki     4003.0
Surulere  4005.0

[2595 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3878.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  3880.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada   3882.0  NaN    NaN        NaN  2500.0       3.0  NaN   8500.0
Lekki     3882.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Surulere  3884.5  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4003.0
Surulere  4005.0
Gbagada   2503.0
Lekki     2005.0
Surulere  2002.0

[2598 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     3882.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Surulere  3884.500000  NaN    NaN        NaN  2000.000000  2.000000  NaN
Gbagada   3890.000000  NaN    NaN        NaN  2000.000000  1.000000  NaN
Ikoyi     3887.333333  NaN    NaN        NaN  3666.666667  3.666667  NaN
Surulere  3888.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN

          Revenue         Snap
Gbagada    8000.0  2004.000000
Ibadan    10000.0  2005.000000
Ikoyi      5000.0  2002.500000
Lekki     20000.0  4005.000000
Gbagada    6000.0  2003.000000
...           ...          ...
Lekki     10000.0  2005.000000
Surulere   4000.0  2002.000000
Gbagada    2000.0  2001.000000
Ikoyi     13000.0  3670.333333
Surulere  16000.0  4004.000000

[2601 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3888.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Gbagada   3892.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ikoyi     3895.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Lekki     3891.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Surulere  3893.5  NaN    NaN        NaN  3500.0       1.5  NaN   5000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4004.0
Gbagada   4005.0
Ikoyi     2005.0
Lekki     2002.0
Surulere  3501.5

[2605 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3891.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Surulere  3893.5  NaN    NaN        NaN  3500.0       1.5  NaN   5000.0
Ibadan    3896.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Lekki     3898.0  NaN    NaN        NaN  4000.0       2.5  NaN  10000.0
Surulere  3899.0  NaN    NaN        NaN  3000.0       4.0  NaN  13000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2002.0
Surulere  3501.5
Ibadan    2005.0
Lekki     4002.5
Surulere  3004.0

[2608 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3898.0  NaN    NaN        NaN  4000.0       2.5  NaN  10000.0
Surulere  3899.0  NaN    NaN        NaN  3000.0       4.0  NaN  13000.0
Ikoyi     3901.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     3903.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Surulere  3904.0  NaN    NaN        NaN  3000.0       1.5  NaN   4500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4002.5
Surulere  3004.0
Ikoyi     4001.0
Lekki     3003.0
Surulere  3001.5

[2611 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3904.0  NaN    NaN        NaN  3000.0       1.5  NaN   4500.0
Gbagada   3907.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ibadan    3908.5  NaN    NaN        NaN  3000.0       3.0  NaN   8000.0
Ikoyi     3910.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Lekki     3906.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3001.5
Gbagada   4005.0
Ibadan    3003.0
Ikoyi     2001.0
Lekki     2005.0

[2615 rows x 9 columns]
                 S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...              ...  ...    ...        ...          ...       ...  ...
Ibadan   3908.500000  NaN    NaN        NaN  3000.000000       3.0  NaN
Ikoyi    3910.000000  NaN    NaN        NaN  2000.000000       1.0  NaN
Lekki    3906.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Gbagada  3912.500000  NaN    NaN        NaN  2000.000000       2.0  NaN
Ibadan   3913.333333  NaN    NaN        NaN  2333.333333       4.0  NaN

         Revenue         Snap
Gbagada   8000.0  2004.000000
Ibadan   10000.0  2005.000000
Ikoyi     5000.0  2002.500000
Lekki    20000.0  4005.000000
Gbagada   6000.0  2003.000000
...          ...          ...
Ibadan    8000.0  3003.000000
Ikoyi     2000.0  2001.000000
Lekki    10000.0  2005.000000
Gbagada   4000.0  2002.000000
Ibadan    9000.0  2337.333333

[2617 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ibadan    3913.333333  NaN    NaN        NaN  2333.333333       4.0  NaN
Gbagada   3916.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Ibadan    3918.500000  NaN    NaN        NaN  4000.000000       4.0  NaN
Lekki     3920.000000  NaN    NaN        NaN  3000.000000       4.0  NaN
Surulere  3917.000000  NaN    NaN        NaN  2000.000000       3.0  NaN

          Revenue         Snap
Gbagada    8000.0  2004.000000
Ibadan    10000.0  2005.000000
Ikoyi      5000.0  2002.500000
Lekki     20000.0  4005.000000
Gbagada    6000.0  2003.000000
...           ...          ...
Ibadan     9000.0  2337.333333
Gbagada   20000.0  4005.000000
Ibadan    16000.0  4004.000000
Lekki     12000.0  3004.000000
Surulere   6000.0  2003.000000

[2621 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...          ...  ...    ...        ...          ...       ...  ...
Lekki     3920.0  NaN    NaN        NaN  3000.000000  4.000000  NaN
Surulere  3917.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
Ibadan    3924.0  NaN    NaN        NaN  4000.000000  3.000000  NaN
Ikoyi     3925.0  NaN    NaN        NaN  2000.000000  2.000000  NaN
Lekki     3922.0  NaN    NaN        NaN  3666.666667  4.333333  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Lekki     12000.000000  3004.0
Surulere   6000.000000  2003.0
Ibadan    12000.000000  4003.0
Ikoyi      4000.000000  2002.0
Lekki     15666.666667  3671.0

[2624 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...          ...  ...    ...        ...          ...       ...  ...
Ikoyi     3925.0  NaN    NaN        NaN  2000.000000  2.000000  NaN
Lekki     3922.0  NaN    NaN        NaN  3666.666667  4.333333  NaN
Gbagada   3930.0  NaN    NaN        NaN  2000.000000  1.000000  NaN
Ikoyi     3926.5  NaN    NaN        NaN  2500.000000  4.000000  NaN
Surulere  3928.5  NaN    NaN        NaN  2500.000000  2.000000  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Ikoyi      4000.000000  2002.0
Lekki     15666.666667  3671.0
Gbagada    2000.000000  2001.0
Ikoyi      9500.000000  2504.0
Surulere   4500.000000  2502.0

[2627 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     3926.500000  NaN    NaN        NaN  2500.000000  4.000000  NaN
Surulere  3928.500000  NaN    NaN        NaN  2500.000000  2.000000  NaN
Gbagada   3931.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN
Ibadan    3933.333333  NaN    NaN        NaN  2666.666667  1.666667  NaN
Surulere  3934.000000  NaN    NaN        NaN  2000.000000  1.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi      9500.000000  2504.000000
Surulere   4500.000000  2502.000000
Gbagada   16000.000000  4004.000000
Ibadan     4666.666667  2668.333333
Surulere   2000.000000  2001.000000

[2630 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3934.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Gbagada   3937.5  NaN    NaN        NaN  3000.0       2.5  NaN   8000.0
Ibadan    3940.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Lekki     3939.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Surulere  3936.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2001.0
Gbagada   3002.5
Ibadan    4005.0
Lekki     4004.0
Surulere  4001.0

[2634 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3936.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Gbagada   3942.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ibadan    3943.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Lekki     3942.5  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Surulere  3945.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4001.0
Gbagada   4003.0
Ibadan    2004.0
Lekki     2004.0
Surulere  3002.0

[2638 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3942.5  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Surulere  3945.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ibadan    3949.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Ikoyi     3948.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     3947.5  NaN    NaN        NaN  2500.0       1.5  NaN   3500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2004.0
Surulere  3002.0
Ibadan    2002.0
Ikoyi     4003.0
Lekki     2501.5

[2641 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3947.5  NaN    NaN        NaN  2500.0       1.5  NaN   3500.0
Gbagada   3953.0  NaN    NaN        NaN  3500.0       3.5  NaN  13000.0
Ikoyi     3953.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Lekki     3954.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  3952.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2501.5
Gbagada   3503.5
Ikoyi     4005.0
Lekki     4002.0
Surulere  4001.0

[2645 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     3953.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Lekki     3954.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Surulere  3952.000000  NaN    NaN        NaN  4000.000000  1.000000  NaN
Ibadan    3957.666667  NaN    NaN        NaN  3666.666667  2.666667  NaN
Lekki     3958.500000  NaN    NaN        NaN  2500.000000  1.500000  NaN

          Revenue         Snap
Gbagada    8000.0  2004.000000
Ibadan    10000.0  2005.000000
Ikoyi      5000.0  2002.500000
Lekki     20000.0  4005.000000
Gbagada    6000.0  2003.000000
...           ...          ...
Ikoyi     20000.0  4005.000000
Lekki      8000.0  4002.000000
Surulere   4000.0  4001.000000
Ibadan     9000.0  3669.333333
Lekki      3500.0  2501.500000

[2647 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3958.5  NaN    NaN        NaN  2500.0       1.5  NaN   3500.0
Ibadan    3963.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ikoyi     3962.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     3963.0  NaN    NaN        NaN  3000.0       3.5  NaN  11000.0
Surulere  3964.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2501.5
Ibadan    2004.0
Ikoyi     4003.0
Lekki     3003.5
Surulere  4001.0

[2651 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3964.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Gbagada   3966.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ibadan    3968.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Lekki     3970.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Surulere  3968.0  NaN    NaN        NaN  3500.0       2.5  NaN   9500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4001.0
Gbagada   2001.0
Ibadan    3005.0
Lekki     4004.0
Surulere  3502.5

[2655 rows x 9 columns]
              S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.00  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.00  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.00  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.00  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.00  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...           ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    3968.00  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Lekki     3970.00  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Surulere  3968.00  NaN    NaN        NaN  3500.0       2.5  NaN   9500.0
Gbagada   3972.75  NaN    NaN        NaN  2500.0       1.5  NaN   3750.0
Ikoyi     3974.00  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    3005.0
Lekki     4004.0
Surulere  3502.5
Gbagada   2501.5
Ikoyi     2005.0

[2657 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     3974.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ibadan    3977.5  NaN    NaN        NaN  3500.0       3.5  NaN  12000.0
Ikoyi     3978.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Lekki     3980.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Surulere  3977.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     2005.0
Ibadan    3503.5
Ikoyi     4005.0
Lekki     4004.0
Surulere  3002.0

[2661 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...               ...  ...    ...        ...     ...       ...  ...
Lekki     3980.000000  NaN    NaN        NaN  4000.0  4.000000  NaN
Surulere  3977.000000  NaN    NaN        NaN  3000.0  2.000000  NaN
Gbagada   3983.000000  NaN    NaN        NaN  4000.0  2.000000  NaN
Lekki     3983.666667  NaN    NaN        NaN  2000.0  3.666667  NaN
Surulere  3981.000000  NaN    NaN        NaN  3000.0  5.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki     16000.000000  4004.000000
Surulere   6000.000000  3002.000000
Gbagada    8000.000000  4002.000000
Lekki      7333.333333  2003.666667
Surulere  15000.000000  3005.000000

[2664 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3981.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Gbagada   3987.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ikoyi     3986.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Lekki     3988.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  3989.5  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3005.0
Gbagada   3005.0
Ikoyi     4002.0
Lekki     4003.0
Surulere  3004.0

[2668 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     3988.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  3989.5  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Gbagada   3992.5  NaN    NaN        NaN  3500.0       2.5  NaN   8500.0
Ikoyi     3994.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Surulere  3992.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4003.0
Surulere  3004.0
Gbagada   3502.5
Ikoyi     3002.0
Surulere  3004.0

[2671 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  3992.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Gbagada   3998.0  NaN    NaN        NaN  2500.0       2.0  NaN   4500.0
Ibadan    3996.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ikoyi     3998.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Surulere  4000.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3004.0
Gbagada   2502.0
Ibadan    3005.0
Ikoyi     4001.0
Surulere  4002.0

[2675 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4000.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ibadan    4003.0  NaN    NaN        NaN  3500.0       3.5  NaN  13000.0
Ikoyi     4001.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Lekki     4003.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Surulere  4005.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4002.0
Ibadan    3503.5
Ikoyi     4002.0
Lekki     2003.0
Surulere  4001.0

[2679 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000       3.0  NaN
...          ...  ...    ...        ...          ...       ...  ...
Lekki     4003.0  NaN    NaN        NaN  2000.000000       3.0  NaN
Surulere  4005.0  NaN    NaN        NaN  4000.000000       1.0  NaN
Gbagada   4008.0  NaN    NaN        NaN  2666.666667       2.0  NaN
Ibadan    4006.0  NaN    NaN        NaN  4000.000000       2.0  NaN
Lekki     4010.0  NaN    NaN        NaN  2000.000000       4.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      6000.000000  2003.000000
Surulere   4000.000000  4001.000000
Gbagada    4666.666667  2668.666667
Ibadan     8000.000000  4002.000000
Lekki      8000.000000  2004.000000

[2682 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   4012.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ibadan    4013.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ikoyi     4014.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Lekki     4011.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Surulere  4015.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   4005.0
Ibadan    4003.0
Ikoyi     3003.0
Lekki     4004.0
Surulere  4002.0

[2687 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   4016.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ibadan    4020.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ikoyi     4017.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Lekki     4019.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Surulere  4018.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   4005.0
Ibadan    2001.0
Ikoyi     2001.0
Lekki     2001.0
Surulere  3001.0

[2692 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4018.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ibadan    4024.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ikoyi     4021.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Lekki     4023.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Surulere  4023.5  NaN    NaN        NaN  2500.0       3.5  NaN   9500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3001.0
Ibadan    3002.0
Ikoyi     4005.0
Lekki     2003.0
Surulere  2503.5

[2696 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4023.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Surulere  4023.5  NaN    NaN        NaN  2500.0       3.5  NaN   9500.0
Ibadan    4029.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ikoyi     4027.5  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  4028.0  NaN    NaN        NaN  2000.0       3.5  NaN   7000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2003.0
Surulere  2503.5
Ibadan    4001.0
Ikoyi     4003.0
Surulere  2003.5

[2699 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     4027.5  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  4028.0  NaN    NaN        NaN  2000.0       3.5  NaN   7000.0
Ibadan    4033.0  NaN    NaN        NaN  3500.0       4.5  NaN  15500.0
Ikoyi     4033.0  NaN    NaN        NaN  3500.0       4.0  NaN  14000.0
Lekki     4033.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     4003.0
Surulere  2003.5
Ibadan    3504.5
Ikoyi     3504.0
Lekki     4003.0

[2702 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi    4033.0  NaN    NaN        NaN  3500.0       4.0  NaN  14000.0  3504.0
Lekki    4033.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Gbagada  4039.5  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Ikoyi    4037.5  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Lekki    4036.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0

[2705 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi    4037.5  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Lekki    4036.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Gbagada  4043.5  NaN    NaN        NaN  3000.0       2.0  NaN   5000.0  3002.0
Ikoyi    4045.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0
Lekki    4041.5  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5

[2708 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4041.5  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Gbagada   4050.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ibadan    4049.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Lekki     4047.0  NaN    NaN        NaN  3500.0       3.0  NaN  10500.0
Surulere  4047.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2002.5
Gbagada   4001.0
Ibadan    3002.0
Lekki     3503.0
Surulere  4001.0

[2712 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4047.0  NaN    NaN        NaN  3500.0       3.0  NaN  10500.0
Surulere  4047.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Gbagada   4052.0  NaN    NaN        NaN  2500.0       2.5  NaN   6500.0
Ikoyi     4052.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Surulere  4054.5  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3503.0
Surulere  4001.0
Gbagada   2502.5
Ikoyi     2002.0
Surulere  2004.0

[2715 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     4052.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Surulere  4054.5  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ikoyi     4059.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Lekki     4058.0  NaN    NaN        NaN  3000.0       3.5  NaN  11000.0
Surulere  4057.5  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     2002.0
Surulere  2004.0
Ikoyi     2002.0
Lekki     3003.5
Surulere  3004.0

[2718 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4057.5  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Gbagada   4061.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ikoyi     4062.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     4064.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Surulere  4064.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3004.0
Gbagada   4005.0
Ikoyi     4001.0
Lekki     2004.0
Surulere  3002.0

[2722 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     4062.000000  NaN    NaN        NaN  4000.000000       1.0  NaN
Lekki     4064.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Surulere  4064.000000  NaN    NaN        NaN  3000.000000       2.0  NaN
Ikoyi     4068.666667  NaN    NaN        NaN  3333.333333       4.0  NaN
Lekki     4067.000000  NaN    NaN        NaN  3000.000000       2.5  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi      4000.000000  4001.000000
Lekki      8000.000000  2004.000000
Surulere   6000.000000  3002.000000
Ikoyi     13333.333333  3337.333333
Lekki      7500.000000  3002.500000

[2724 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     4068.666667  NaN    NaN        NaN  3333.333333  4.000000  NaN
Lekki     4067.000000  NaN    NaN        NaN  3000.000000  2.500000  NaN
Gbagada   4074.000000  NaN    NaN        NaN  3666.666667  4.333333  NaN
Lekki     4072.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Surulere  4071.000000  NaN    NaN        NaN  2000.000000  1.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi     13333.333333  3337.333333
Lekki      7500.000000  3002.500000
Gbagada   16333.333333  3671.000000
Lekki      8000.000000  4002.000000
Surulere   2000.000000  2001.000000

[2727 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4071.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Gbagada   4076.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ibadan    4080.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ikoyi     4078.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Surulere  4078.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2001.0
Gbagada   4001.0
Ibadan    3001.0
Ikoyi     2002.5
Surulere  3003.0

[2731 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4078.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Gbagada   4083.5  NaN    NaN        NaN  3000.0       2.5  NaN   7500.0
Ibadan    4084.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ikoyi     4083.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  4081.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3003.0
Gbagada   3002.5
Ibadan    4003.0
Ikoyi     4003.0
Surulere  2002.0

[2735 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ibadan    4084.000000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Ikoyi     4083.000000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Surulere  4081.000000  NaN    NaN        NaN  2000.000000  2.000000  NaN
Ibadan    4088.500000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Ikoyi     4087.666667  NaN    NaN        NaN  3333.333333  4.666667  NaN

          Revenue    Snap
Gbagada    8000.0  2004.0
Ibadan    10000.0  2005.0
Ikoyi      5000.0  2002.5
Lekki     20000.0  4005.0
Gbagada    6000.0  2003.0
...           ...     ...
Ibadan    12000.0  4003.0
Ikoyi     12000.0  4003.0
Surulere   4000.0  2002.0
Ibadan     8000.0  4002.0
Ikoyi     16000.0  3338.0

[2737 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ibadan    4088.500000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Ikoyi     4087.666667  NaN    NaN        NaN  3333.333333  4.666667  NaN
Gbagada   4094.500000  NaN    NaN        NaN  2500.000000  1.500000  NaN
Ibadan    4092.500000  NaN    NaN        NaN  3000.000000  1.500000  NaN
Surulere  4091.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN

          Revenue    Snap
Gbagada    8000.0  2004.0
Ibadan    10000.0  2005.0
Ikoyi      5000.0  2002.5
Lekki     20000.0  4005.0
Gbagada    6000.0  2003.0
...           ...     ...
Ibadan     8000.0  4002.0
Ikoyi     16000.0  3338.0
Gbagada    4000.0  2501.5
Ibadan     4500.0  3001.5
Surulere   8000.0  4002.0

[2740 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4091.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Gbagada   4097.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ikoyi     4098.0  NaN    NaN        NaN  3000.0       2.5  NaN   8000.0
Lekki     4098.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Surulere  4099.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4002.0
Gbagada   3005.0
Ikoyi     3002.5
Lekki     2001.0
Surulere  2003.0

[2744 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     4098.000000  NaN    NaN        NaN  3000.000000  2.500000  NaN
Lekki     4098.000000  NaN    NaN        NaN  2000.000000  1.000000  NaN
Surulere  4099.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Gbagada   4102.000000  NaN    NaN        NaN  4000.000000  3.500000  NaN
Surulere  4103.666667  NaN    NaN        NaN  3333.333333  3.666667  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Ikoyi      8000.000000  3002.5
Lekki      2000.000000  2001.0
Surulere   6000.000000  2003.0
Gbagada   14000.000000  4003.5
Surulere  12333.333333  3337.0

[2746 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Gbagada   4102.000000  NaN    NaN        NaN  4000.000000  3.500000  NaN
Surulere  4103.666667  NaN    NaN        NaN  3333.333333  3.666667  NaN
Gbagada   4108.500000  NaN    NaN        NaN  3500.000000  5.000000  NaN
Ikoyi     4108.500000  NaN    NaN        NaN  3000.000000  1.000000  NaN
Lekki     4106.000000  NaN    NaN        NaN  2000.000000  2.000000  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Gbagada   14000.000000  4003.5
Surulere  12333.333333  3337.0
Gbagada   17500.000000  3505.0
Ikoyi      3000.000000  3001.0
Lekki      4000.000000  2002.0

[2749 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi    4108.5  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0  3001.0
Lekki    4106.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0  2002.0
Gbagada  4114.0  NaN    NaN        NaN  3000.0       3.5  NaN  10500.0  3003.5
Ibadan   4112.5  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0
Lekki    4112.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0

[2752 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4112.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Gbagada   4118.5  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ikoyi     4118.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Lekki     4119.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Surulere  4116.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2003.0
Gbagada   4005.0
Ikoyi     2003.0
Lekki     2005.0
Surulere  3005.0

[2756 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time       Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.000000
Ibadan       1.0  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.000000
Ikoyi        3.0  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.000000
Lekki        3.0  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.000000
Gbagada      9.0  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.000000
...          ...  ...    ...        ...     ...       ...  ...           ...
Ikoyi     4118.0  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.000000
Lekki     4119.0  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.000000
Surulere  4116.0  NaN    NaN        NaN  3000.0  5.000000  NaN  15000.000000
Gbagada   4123.0  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.000000
Surulere  4123.0  NaN    NaN        NaN  3000.0  2.333333  NaN   7666.666667

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Ikoyi     2003.000000
Lekki     2005.000000
Surulere  3005.000000
Gbagada   2004.000000
Surulere  3002.333333

[2758 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time       Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.000000
Ibadan       1.0  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.000000
Ikoyi        3.0  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.000000
Lekki        3.0  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.000000
Gbagada      9.0  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.000000
...          ...  ...    ...        ...     ...       ...  ...           ...
Gbagada   4123.0  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.000000
Surulere  4123.0  NaN    NaN        NaN  3000.0  2.333333  NaN   7666.666667
Gbagada   4126.5  NaN    NaN        NaN  2000.0  2.000000  NaN   4000.000000
Ibadan    4129.0  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.000000
Ikoyi     4129.0  NaN    NaN        NaN  3000.0  3.500000  NaN  12000.000000

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Gbagada   2004.000000
Surulere  3002.333333
Gbagada   2002.000000
Ibadan    2004.000000
Ikoyi     3003.500000

[2761 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     4129.0  NaN    NaN        NaN  3000.0       3.5  NaN  12000.0
Gbagada   4132.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ibadan    4134.5  NaN    NaN        NaN  3500.0       3.0  NaN  11000.0
Ikoyi     4133.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Surulere  4131.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3003.5
Gbagada   4003.0
Ibadan    3503.0
Ikoyi     4001.0
Surulere  4002.0

[2765 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4131.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Gbagada   4139.0  NaN    NaN        NaN  3500.0       3.5  NaN  12000.0
Ibadan    4137.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ikoyi     4139.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Lekki     4136.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4002.0
Gbagada   3503.5
Ibadan    3005.0
Ikoyi     3005.0
Lekki     3001.0

[2769 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4136.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Gbagada   4144.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ibadan    4142.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ikoyi     4143.0  NaN    NaN        NaN  2000.0       3.5  NaN   7000.0
Surulere  4143.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3001.0
Gbagada   4003.0
Ibadan    3004.0
Ikoyi     2003.5
Surulere  3003.0

[2773 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     4143.0  NaN    NaN        NaN  2000.0       3.5  NaN   7000.0
Surulere  4143.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Gbagada   4147.0  NaN    NaN        NaN  3500.0       2.5  NaN   8500.0
Ikoyi     4147.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Surulere  4149.5  NaN    NaN        NaN  3000.0       2.0  NaN   7000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     2003.5
Surulere  3003.0
Gbagada   3502.5
Ikoyi     4001.0
Surulere  3002.0

[2776 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4149.5  NaN    NaN        NaN  3000.0       2.0  NaN   7000.0
Gbagada   4151.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ibadan    4154.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ikoyi     4152.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Surulere  4154.0  NaN    NaN        NaN  2500.0       1.5  NaN   3500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3002.0
Gbagada   4003.0
Ibadan    4005.0
Ikoyi     3003.0
Surulere  2501.5

[2780 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4154.0  NaN    NaN        NaN  2500.0       1.5  NaN   3500.0
Gbagada   4158.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ikoyi     4160.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Lekki     4157.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  4157.5  NaN    NaN        NaN  3500.0       2.5  NaN   9500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2501.5
Gbagada   4003.0
Ikoyi     4002.0
Lekki     4003.0
Surulere  3502.5

[2784 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...               ...  ...    ...        ...     ...       ...  ...
Lekki     4157.000000  NaN    NaN        NaN  4000.0  3.000000  NaN
Surulere  4157.500000  NaN    NaN        NaN  3500.0  2.500000  NaN
Gbagada   4164.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Ikoyi     4163.333333  NaN    NaN        NaN  3000.0  3.666667  NaN
Surulere  4161.000000  NaN    NaN        NaN  2000.0  5.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki     12000.000000  4003.000000
Surulere   9500.000000  3502.500000
Gbagada   20000.000000  4005.000000
Ikoyi     11666.666667  3003.666667
Surulere  10000.000000  2005.000000

[2787 rows x 9 columns]

                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...               ...  ...    ...        ...     ...       ...  ...
Ikoyi     4163.333333  NaN    NaN        NaN  3000.0  3.666667  NaN
Surulere  4161.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Gbagada   4169.500000  NaN    NaN        NaN  3000.0  2.000000  NaN
Lekki     4167.500000  NaN    NaN        NaN  4000.0  3.500000  NaN
Surulere  4166.000000  NaN    NaN        NaN  4000.0  1.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi     11666.666667  3003.666667
Surulere  10000.000000  2005.000000
Gbagada    6000.000000  3002.000000
Lekki     14000.000000  4003.500000
Surulere   4000.000000  4001.000000

[2790 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4167.5  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0
Surulere  4166.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ikoyi     4175.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Lekki     4172.5  NaN    NaN        NaN  3500.0       5.0  NaN  17500.0
Surulere  4172.5  NaN    NaN        NaN  2500.0       2.5  NaN   7000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4003.5
Surulere  4001.0
Ikoyi     4004.0
Lekki     3505.0
Surulere  2502.5

[2793 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4172.5  NaN    NaN        NaN  2500.0       2.5  NaN   7000.0
Gbagada   4178.5  NaN    NaN        NaN  3500.0       4.5  NaN  15500.0
Ibadan    4176.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ikoyi     4180.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Lekki     4177.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2502.5
Gbagada   3504.5
Ibadan    2004.0
Ikoyi     3005.0
Lekki     2001.0

[2797 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     4180.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Lekki     4177.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ibadan    4183.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Lekki     4185.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Surulere  4182.0  NaN    NaN        NaN  2500.0       2.5  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3005.0
Lekki     2001.0
Ibadan    3001.0
Lekki     2004.0
Surulere  2502.5

[2800 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4182.0  NaN    NaN        NaN  2500.0       2.5  NaN   6000.0
Gbagada   4188.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ibadan    4189.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Lekki     4187.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Surulere  4188.0  NaN    NaN        NaN  2500.0       4.5  NaN  11000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2502.5
Gbagada   3002.0
Ibadan    2001.0
Lekki     3002.0
Surulere  2504.5

[2804 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...          ...  ...    ...        ...          ...       ...  ...
Lekki     4187.0  NaN    NaN        NaN  3000.000000  2.000000  NaN
Surulere  4188.0  NaN    NaN        NaN  2500.000000  4.500000  NaN
Ibadan    4194.0  NaN    NaN        NaN  3000.000000  1.000000  NaN
Ikoyi     4193.0  NaN    NaN        NaN  2333.333333  2.666667  NaN
Lekki     4192.0  NaN    NaN        NaN  4000.000000  4.000000  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Lekki      6000.000000  3002.0
Surulere  11000.000000  2504.5
Ibadan     3000.000000  3001.0
Ikoyi      6333.333333  2336.0
Lekki     16000.000000  4004.0

[2807 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki    4192.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Gbagada  4198.0  NaN    NaN        NaN  3000.0       3.5  NaN   9000.0  3003.5
Ibadan   4200.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ikoyi    4196.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Lekki    4198.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0

[2811 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi    4196.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Lekki    4198.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0
Gbagada  4203.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Ibadan   4204.5  NaN    NaN        NaN  3000.0       1.5  NaN   4000.0  3001.5
Ikoyi    4201.5  NaN    NaN        NaN  3000.0       2.5  NaN   6000.0  3002.5

[2814 rows x 9 columns]

            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ibadan   4204.5  NaN    NaN        NaN  3000.0       1.5  NaN   4000.0  3001.5
Ikoyi    4201.5  NaN    NaN        NaN  3000.0       2.5  NaN   6000.0  3002.5
Ibadan   4206.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0
Ikoyi    4208.5  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki    4208.5  NaN    NaN        NaN  3500.0       3.5  NaN  11500.0  3503.5

[2817 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki    4208.5  NaN    NaN        NaN  3500.0       3.5  NaN  11500.0  3503.5
Gbagada  4213.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Ibadan   4212.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Ikoyi    4214.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Lekki    4213.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0

[2821 rows x 9 columns]
                 S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...              ...  ...    ...        ...          ...       ...  ...
Ibadan   4212.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Ikoyi    4214.000000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Lekki    4213.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Gbagada  4218.500000  NaN    NaN        NaN  2500.000000  3.500000  NaN
Lekki    4217.666667  NaN    NaN        NaN  3666.666667  3.333333  NaN

         Revenue    Snap
Gbagada   8000.0  2004.0
Ibadan   10000.0  2005.0
Ikoyi     5000.0  2002.5
Lekki    20000.0  4005.0
Gbagada   6000.0  2003.0
...          ...     ...
Ibadan   20000.0  4005.0
Ikoyi    12000.0  4003.0
Lekki     8000.0  4002.0
Gbagada   8500.0  2503.5
Lekki    13000.0  3670.0

[2823 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     4217.666667  NaN    NaN        NaN  3666.666667  3.333333  NaN
Gbagada   4223.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Ikoyi     4221.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN
Lekki     4222.000000  NaN    NaN        NaN  2000.000000  1.000000  NaN
Surulere  4224.500000  NaN    NaN        NaN  4000.000000  2.500000  NaN

          Revenue    Snap
Gbagada    8000.0  2004.0
Ibadan    10000.0  2005.0
Ikoyi      5000.0  2002.5
Lekki     20000.0  4005.0
Gbagada    6000.0  2003.0
...           ...     ...
Lekki     13000.0  3670.0
Gbagada   20000.0  4005.0
Ikoyi     16000.0  4004.0
Lekki      2000.0  2001.0
Surulere  10000.0  4002.5

[2827 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4222.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Surulere  4224.5  NaN    NaN        NaN  4000.0       2.5  NaN  10000.0
Gbagada   4227.0  NaN    NaN        NaN  2500.0       2.5  NaN   6500.0
Ikoyi     4229.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Lekki     4228.5  NaN    NaN        NaN  2500.0       3.5  NaN   8500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2001.0
Surulere  4002.5
Gbagada   2502.5
Ikoyi     3002.0
Lekki     2503.5

[2830 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4228.5  NaN    NaN        NaN  2500.0       3.5  NaN   8500.0
Gbagada   4233.5  NaN    NaN        NaN  2000.0       3.5  NaN   7000.0
Ibadan    4231.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ikoyi     4234.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  4233.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2503.5
Gbagada   2003.5
Ibadan    2003.0
Ikoyi     4002.0
Surulere  3001.0

[2834 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     4234.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  4233.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ibadan    4238.5  NaN    NaN        NaN  2500.0       3.0  NaN   8000.0
Ikoyi     4238.5  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Lekki     4236.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     4002.0
Surulere  3001.0
Ibadan    2503.0
Ikoyi     4004.0
Lekki     3002.0

[2837 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4236.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Gbagada   4241.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ibadan    4243.5  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0
Lekki     4242.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Surulere  4245.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3002.0
Gbagada   4002.0
Ibadan    4003.5
Lekki     2002.0
Surulere  2004.0

[2841 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4242.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Surulere  4245.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ikoyi     4249.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Lekki     4248.0  NaN    NaN        NaN  3500.0       4.0  NaN  14000.0
Surulere  4247.5  NaN    NaN        NaN  2500.0       4.0  NaN   9500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2002.0
Surulere  2004.0
Ikoyi     4005.0
Lekki     3504.0
Surulere  2504.0

[2844 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     4248.000000  NaN    NaN        NaN  3500.000000  4.000000  NaN
Surulere  4247.500000  NaN    NaN        NaN  2500.000000  4.000000  NaN
Ibadan    4254.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Ikoyi     4253.333333  NaN    NaN        NaN  2666.666667  3.666667  NaN
Lekki     4251.000000  NaN    NaN        NaN  3000.000000  2.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki     14000.000000  3504.000000
Surulere   9500.000000  2504.000000
Ibadan     8000.000000  4002.000000
Ikoyi      9666.666667  2670.333333
Lekki      6000.000000  3002.000000

[2847 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4251.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Gbagada   4259.5  NaN    NaN        NaN  3000.0       2.5  NaN   8000.0
Ibadan    4258.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     4257.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Surulere  4256.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3002.0
Gbagada   3002.5
Ibadan    4003.0
Lekki     3004.0
Surulere  2002.0

[2851 rows x 9 columns]
              S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.00  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.00  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.00  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.00  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.00  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...           ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    4258.00  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     4257.00  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Surulere  4256.00  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Ibadan    4264.00  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi     4262.75  NaN    NaN        NaN  3250.0       3.5  NaN  10750.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    4003.0
Lekki     3004.0
Surulere  2002.0
Ibadan    2005.0
Ikoyi     3253.5

[2853 rows x 9 columns]
              S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.00  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.00  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.00  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.00  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.00  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...           ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     4262.75  NaN    NaN        NaN  3250.0       3.5  NaN  10750.0
Gbagada   4267.00  NaN    NaN        NaN  2500.0       4.5  NaN  11500.0
Ibadan    4267.00  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ikoyi     4270.00  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  4269.00  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3253.5
Gbagada   2504.5
Ibadan    3001.0
Ikoyi     4005.0
Surulere  4001.0

[2857 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4269.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Gbagada   4271.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ikoyi     4273.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Lekki     4275.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  4273.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4001.0
Gbagada   4001.0
Ikoyi     4005.0
Lekki     4003.0
Surulere  4003.0

[2861 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4273.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Gbagada   4278.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Ikoyi     4279.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     4276.5  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Surulere  4280.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4003.0
Gbagada   3003.0
Ikoyi     4001.0
Lekki     2002.0
Surulere  4001.0

[2865 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4276.5  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Surulere  4280.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Gbagada   4283.5  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Lekki     4281.5  NaN    NaN        NaN  3000.0       3.5  NaN  11000.0
Surulere  4285.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2002.0
Surulere  4001.0
Gbagada   4004.0
Lekki     3003.5
Surulere  4004.0

[2868 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4285.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Gbagada   4286.5  NaN    NaN        NaN  3500.0       5.0  NaN  17500.0
Ibadan    4289.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ikoyi     4288.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Lekki     4290.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4004.0
Gbagada   3505.0
Ibadan    4001.0
Ikoyi     3003.0
Lekki     2003.0

[2872 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi    4288.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Lekki    4290.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Ibadan   4294.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0  3002.0
Ikoyi    4292.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Lekki    4293.5  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0  3004.0

[2875 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     4292.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Lekki     4293.5  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Gbagada   4298.0  NaN    NaN        NaN  2500.0       1.5  NaN   4000.0
Ikoyi     4297.5  NaN    NaN        NaN  2500.0       1.0  NaN   2500.0
Surulere  4299.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     4005.0
Lekki     3004.0
Gbagada   2501.5
Ikoyi     2501.0
Surulere  4002.0

[2878 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4299.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Gbagada   4303.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ibadan    4303.0  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0
Ikoyi     4304.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Surulere  4302.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4002.0
Gbagada   2003.0
Ibadan    4003.5
Ikoyi     2002.0
Surulere  4005.0

[2882 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ibadan    4303.000000  NaN    NaN        NaN  4000.000000       3.5  NaN
Ikoyi     4304.000000  NaN    NaN        NaN  2000.000000       2.0  NaN
Surulere  4302.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Ibadan    4308.333333  NaN    NaN        NaN  3333.333333       2.0  NaN
Ikoyi     4307.500000  NaN    NaN        NaN  3500.000000       2.5  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ibadan    14000.000000  4003.500000
Ikoyi      4000.000000  2002.000000
Surulere  20000.000000  4005.000000
Ibadan     6666.666667  3335.333333
Ikoyi      8000.000000  3502.500000

[2884 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Surulere  4302.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Ibadan    4308.333333  NaN    NaN        NaN  3333.333333  2.000000  NaN
Ikoyi     4307.500000  NaN    NaN        NaN  3500.000000  2.500000  NaN
Ibadan    4313.333333  NaN    NaN        NaN  2666.666667  3.666667  NaN
Ikoyi     4312.500000  NaN    NaN        NaN  3000.000000  3.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Surulere  20000.000000  4005.000000
Ibadan     6666.666667  3335.333333
Ikoyi      8000.000000  3502.500000
Ibadan    10000.000000  2670.333333
Ikoyi     11000.000000  3003.000000

[2886 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi    4312.5  NaN    NaN        NaN  3000.0       3.0  NaN  11000.0  3003.0
Gbagada  4316.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Ibadan   4318.5  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ikoyi    4317.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Lekki    4320.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0

[2890 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Lekki    4320.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0  2001.0
Gbagada  4322.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0  3003.0
Ibadan   4321.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0  4002.0
Ikoyi    4323.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0  4004.0
Lekki    4324.5  NaN    NaN        NaN  3500.0       4.0  NaN  13500.0  3504.0

[2894 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     4323.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Lekki     4324.5  NaN    NaN        NaN  3500.0       4.0  NaN  13500.0
Gbagada   4328.5  NaN    NaN        NaN  3000.0       2.0  NaN   5000.0
Ibadan    4327.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  4329.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     4004.0
Lekki     3504.0
Gbagada   3002.0
Ibadan    4003.0
Surulere  4001.0

[2897 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4329.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Gbagada   4331.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ibadan    4334.5  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Lekki     4333.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Surulere  4332.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4001.0
Gbagada   2003.0
Ibadan    4002.0
Lekki     2003.0
Surulere  4002.0

[2901 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4332.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Gbagada   4338.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ibadan    4338.0  NaN    NaN        NaN  3000.0       2.5  NaN   6000.0
Ikoyi     4336.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Lekki     4340.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4002.0
Gbagada   4003.0
Ibadan    3002.5
Ikoyi     2005.0
Lekki     3003.0

[2905 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4340.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Ibadan    4342.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi     4343.0  NaN    NaN        NaN  2500.0       3.0  NaN   8500.0
Lekki     4344.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  4343.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3003.0
Ibadan    2005.0
Ikoyi     2503.0
Lekki     4002.0
Surulere  2002.0

[2909 rows x 9 columns]

                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...               ...  ...    ...        ...     ...       ...  ...
Lekki     4344.000000  NaN    NaN        NaN  4000.0  2.000000  NaN
Surulere  4343.000000  NaN    NaN        NaN  2000.0  2.000000  NaN
Gbagada   4348.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ikoyi     4346.000000  NaN    NaN        NaN  2000.0  1.000000  NaN
Lekki     4348.666667  NaN    NaN        NaN  3000.0  2.333333  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      8000.000000  4002.000000
Surulere   4000.000000  2002.000000
Gbagada    8000.000000  2004.000000
Ikoyi      2000.000000  2001.000000
Lekki      7333.333333  3002.333333

[2912 rows x 9 columns]
                 S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...              ...  ...    ...        ...     ...       ...  ...
Ikoyi    4346.000000  NaN    NaN        NaN  2000.0  1.000000  NaN
Lekki    4348.666667  NaN    NaN        NaN  3000.0  2.333333  NaN
Gbagada  4351.000000  NaN    NaN        NaN  4000.0  4.000000  NaN
Ibadan   4353.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
Lekki    4353.666667  NaN    NaN        NaN  3000.0  2.000000  NaN

              Revenue         Snap
Gbagada   8000.000000  2004.000000
Ibadan   10000.000000  2005.000000
Ikoyi     5000.000000  2002.500000
Lekki    20000.000000  4005.000000
Gbagada   6000.000000  2003.000000
...               ...          ...
Ikoyi     2000.000000  2001.000000
Lekki     7333.333333  3002.333333
Gbagada  16000.000000  4004.000000
Ibadan    6000.000000  2003.000000
Lekki     6000.000000  3002.000000

[2915 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.000000  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.000000  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.000000  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.000000  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...               ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4353.666667  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ibadan    4358.500000  NaN    NaN        NaN  3500.0       2.5  NaN   8500.0
Ikoyi     4359.000000  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     4358.000000  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Surulere  4356.000000  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3002.0
Ibadan    3502.5
Ikoyi     4001.0
Lekki     3002.0
Surulere  4003.0

[2919 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4358.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Surulere  4356.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Gbagada   4364.5  NaN    NaN        NaN  3500.0       2.5  NaN   8000.0
Ikoyi     4362.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Lekki     4362.0  NaN    NaN        NaN  3500.0       2.5  NaN   8500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3002.0
Surulere  4003.0
Gbagada   3502.5
Ikoyi     4005.0
Lekki     3502.5

[2922 rows x 9 columns]
                 S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...              ...  ...    ...        ...     ...       ...  ...
Ikoyi    4362.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Lekki    4362.000000  NaN    NaN        NaN  3500.0  2.500000  NaN
Gbagada  4367.000000  NaN    NaN        NaN  3000.0  4.000000  NaN
Ikoyi    4368.333333  NaN    NaN        NaN  4000.0  2.333333  NaN
Lekki    4368.000000  NaN    NaN        NaN  2000.0  3.000000  NaN

              Revenue         Snap
Gbagada   8000.000000  2004.000000
Ibadan   10000.000000  2005.000000
Ikoyi     5000.000000  2002.500000
Lekki    20000.000000  4005.000000
Gbagada   6000.000000  2003.000000
...               ...          ...
Ikoyi    20000.000000  4005.000000
Lekki     8500.000000  3502.500000
Gbagada  12000.000000  3004.000000
Ikoyi     9333.333333  4002.333333
Lekki     6000.000000  2003.000000

[2925 rows x 9 columns]
                 S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...              ...  ...    ...        ...          ...       ...  ...
Gbagada  4367.000000  NaN    NaN        NaN  3000.000000  4.000000  NaN
Ikoyi    4368.333333  NaN    NaN        NaN  4000.000000  2.333333  NaN
Lekki    4368.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Ibadan   4373.666667  NaN    NaN        NaN  3333.333333  2.000000  NaN
Ikoyi    4372.000000  NaN    NaN        NaN  2500.000000  4.000000  NaN

              Revenue         Snap
Gbagada   8000.000000  2004.000000
Ibadan   10000.000000  2005.000000
Ikoyi     5000.000000  2002.500000
Lekki    20000.000000  4005.000000
Gbagada   6000.000000  2003.000000
...               ...          ...
Gbagada  12000.000000  3004.000000
Ikoyi     9333.333333  4002.333333
Lekki     6000.000000  2003.000000
Ibadan    7333.333333  3335.333333
Ikoyi    10000.000000  2504.000000

[2927 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ikoyi    4372.0  NaN    NaN        NaN  2500.0       4.0  NaN  10000.0  2504.0
Gbagada  4380.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0  3001.0
Ibadan   4378.0  NaN    NaN        NaN  3000.0       2.0  NaN   5000.0  3002.0
Ikoyi    4376.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Lekki    4378.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0  4001.0

[2931 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     4376.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Lekki     4378.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Gbagada   4381.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Lekki     4383.5  NaN    NaN        NaN  4000.0       2.5  NaN  10000.0
Surulere  4383.5  NaN    NaN        NaN  3500.0       3.5  NaN  12500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     4005.0
Lekki     4001.0
Gbagada   3002.0
Lekki     4002.5
Surulere  3503.5

[2934 rows x 9 columns]
                  S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...               ...  ...    ...        ...     ...       ...  ...
Gbagada   4381.000000  NaN    NaN        NaN  3000.0  2.000000  NaN
Lekki     4383.500000  NaN    NaN        NaN  4000.0  2.500000  NaN
Surulere  4383.500000  NaN    NaN        NaN  3500.0  3.500000  NaN
Ikoyi     4387.666667  NaN    NaN        NaN  3000.0  2.666667  NaN
Lekki     4388.500000  NaN    NaN        NaN  3500.0  1.500000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Gbagada    6000.000000  3002.000000
Lekki     10000.000000  4002.500000
Surulere  12500.000000  3503.500000
Ikoyi      7666.666667  3002.666667
Lekki      5500.000000  3501.500000

[2936 rows x 9 columns]

                 S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.0  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.0  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.0  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.0  3.000000  NaN
...              ...  ...    ...        ...     ...       ...  ...
Ikoyi    4387.666667  NaN    NaN        NaN  3000.0  2.666667  NaN
Lekki    4388.500000  NaN    NaN        NaN  3500.0  1.500000  NaN
Gbagada  4393.000000  NaN    NaN        NaN  4000.0  5.000000  NaN
Ikoyi    4393.000000  NaN    NaN        NaN  3500.0  1.000000  NaN
Lekki    4393.000000  NaN    NaN        NaN  4000.0  2.000000  NaN

              Revenue         Snap
Gbagada   8000.000000  2004.000000
Ibadan   10000.000000  2005.000000
Ikoyi     5000.000000  2002.500000
Lekki    20000.000000  4005.000000
Gbagada   6000.000000  2003.000000
...               ...          ...
Ikoyi     7666.666667  3002.666667
Lekki     5500.000000  3501.500000
Gbagada  20000.000000  4005.000000
Ikoyi     3500.000000  3501.000000
Lekki     8000.000000  4002.000000

[2939 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4393.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ibadan    4399.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ikoyi     4398.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Lekki     4396.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  4398.5  NaN    NaN        NaN  2500.0       3.5  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4002.0
Ibadan    2004.0
Ikoyi     3003.0
Lekki     4005.0
Surulere  2503.5

[2943 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4398.5  NaN    NaN        NaN  2500.0       3.5  NaN   9000.0
Gbagada   4403.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ibadan    4401.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ikoyi     4402.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Lekki     4404.5  NaN    NaN        NaN  2500.0       3.0  NaN   6500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2503.5
Gbagada   2001.0
Ibadan    3005.0
Ikoyi     2001.0
Lekki     2503.0

[2947 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4404.5  NaN    NaN        NaN  2500.0       3.0  NaN   6500.0
Gbagada   4409.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ibadan    4407.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Lekki     4406.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Surulere  4409.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2503.0
Gbagada   4002.0
Ibadan    2003.0
Lekki     3004.0
Surulere  3003.0

[2951 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4409.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Ibadan    4412.5  NaN    NaN        NaN  4000.0       4.5  NaN  18000.0
Ikoyi     4411.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     4415.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Surulere  4414.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3003.0
Ibadan    4004.5
Ikoyi     4003.0
Lekki     3001.0
Surulere  4003.0

[2955 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4414.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Gbagada   4419.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ibadan    4417.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ikoyi     4419.0  NaN    NaN        NaN  2500.0       1.0  NaN   2500.0
Surulere  4416.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4003.0
Gbagada   2003.0
Ibadan    3002.0
Ikoyi     2501.0
Surulere  4004.0

[2959 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     4419.000000  NaN    NaN        NaN  2500.000000  1.000000  NaN
Surulere  4416.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN
Gbagada   4422.000000  NaN    NaN        NaN  4000.000000  1.000000  NaN
Ibadan    4422.666667  NaN    NaN        NaN  3333.333333  1.666667  NaN
Lekki     4425.000000  NaN    NaN        NaN  2000.000000  1.000000  NaN

          Revenue    Snap
Gbagada    8000.0  2004.0
Ibadan    10000.0  2005.0
Ikoyi      5000.0  2002.5
Lekki     20000.0  4005.0
Gbagada    6000.0  2003.0
...           ...     ...
Ikoyi      2500.0  2501.0
Surulere  16000.0  4004.0
Gbagada    4000.0  4001.0
Ibadan     6000.0  3335.0
Lekki      2000.0  2001.0

[2962 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4425.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Gbagada   4428.0  NaN    NaN        NaN  3500.0       1.5  NaN   5500.0
Ikoyi     4429.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Lekki     4428.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  4427.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2001.0
Gbagada   3501.5
Ikoyi     3003.0
Lekki     4005.0
Surulere  2005.0

[2966 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4427.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ibadan    4435.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ikoyi     4431.5  NaN    NaN        NaN  3000.0       1.5  NaN   4500.0
Lekki     4434.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Surulere  4433.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2005.0
Ibadan    4005.0
Ikoyi     3001.5
Lekki     3001.0
Surulere  2005.0

[2970 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   4440.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ibadan    4438.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ikoyi     4439.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Lekki     4437.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Surulere  4436.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   2001.0
Ibadan    4005.0
Ikoyi     4005.0
Lekki     4001.0
Surulere  4004.0

[2975 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4436.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Gbagada   4445.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ikoyi     4444.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Lekki     4441.5  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Surulere  4443.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4004.0
Gbagada   4001.0
Ikoyi     3005.0
Lekki     2005.0
Surulere  3004.0

[2979 rows x 9 columns]
              S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.00  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.00  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.00  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.00  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.00  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...           ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     4444.00  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Lekki     4441.50  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Surulere  4443.00  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ibadan    4448.25  NaN    NaN        NaN  2500.0       2.0  NaN   5500.0
Lekki     4447.00  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3005.0
Lekki     2005.0
Surulere  3004.0
Ibadan    2502.0
Lekki     2004.0

[2981 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4447.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan    4453.5  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Ikoyi     4453.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Lekki     4451.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Surulere  4454.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2004.0
Ibadan    2002.0
Ikoyi     4002.0
Lekki     3005.0
Surulere  3003.0

[2985 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4454.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Gbagada   4458.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ibadan    4456.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ikoyi     4460.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Lekki     4458.0  NaN    NaN        NaN  2500.0       3.5  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3003.0
Gbagada   3002.0
Ibadan    2001.0
Ikoyi     2001.0
Lekki     2503.5

[2989 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   4461.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Ibadan    4462.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ikoyi     4464.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Lekki     4465.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Surulere  4463.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   2002.0
Ibadan    2001.0
Ikoyi     4002.0
Lekki     2003.0
Surulere  2002.0

[2994 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4465.0  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.0
Surulere  4463.0  NaN    NaN        NaN  2000.0  2.000000  NaN   4000.0
Gbagada   4470.0  NaN    NaN        NaN  2000.0  1.000000  NaN   2000.0
Ikoyi     4466.0  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.0
Surulere  4468.0  NaN    NaN        NaN  3000.0  3.666667  NaN  11000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Lekki     2003.000000
Surulere  2002.000000
Gbagada   2001.000000
Ikoyi     4005.000000
Surulere  3003.666667

[2997 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0  2.500000  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0  5.000000  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0  3.000000  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4468.0  NaN    NaN        NaN  3000.0  3.666667  NaN  11000.0
Gbagada   4473.0  NaN    NaN        NaN  3000.0  5.000000  NaN  15000.0
Ibadan    4471.0  NaN    NaN        NaN  2000.0  5.000000  NaN  10000.0
Ikoyi     4474.0  NaN    NaN        NaN  2000.0  4.000000  NaN   8000.0
Surulere  4473.5  NaN    NaN        NaN  3000.0  3.500000  NaN  12000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Surulere  3003.666667
Gbagada   3005.000000
Ibadan    2005.000000
Ikoyi     2004.000000
Surulere  3003.500000

[3001 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4473.5  NaN    NaN        NaN  3000.0       3.5  NaN  12000.0
Gbagada   4479.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ibadan    4478.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Ikoyi     4476.5  NaN    NaN        NaN  2500.0       4.0  NaN  10000.0
Surulere  4480.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3003.5
Gbagada   3005.0
Ibadan    3003.0
Ikoyi     2504.0
Surulere  3003.0

[3005 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     4476.5  NaN    NaN        NaN  2500.0       4.0  NaN  10000.0
Surulere  4480.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Gbagada   4483.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ikoyi     4484.0  NaN    NaN        NaN  2000.0       4.5  NaN   9000.0
Surulere  4481.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     2504.0
Surulere  3003.0
Gbagada   2003.0
Ikoyi     2004.5
Surulere  4001.0

[3008 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     4484.0  NaN    NaN        NaN  2000.0       4.5  NaN   9000.0
Surulere  4481.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Gbagada   4489.5  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Ibadan    4487.0  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0
Ikoyi     4487.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     2004.5
Surulere  4001.0
Gbagada   3003.0
Ibadan    4003.5
Ikoyi     2003.0

[3011 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ibadan    4487.000000  NaN    NaN        NaN  4000.000000  3.500000  NaN
Ikoyi     4487.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Gbagada   4492.666667  NaN    NaN        NaN  3666.666667  2.666667  NaN
Ibadan    4495.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Surulere  4492.000000  NaN    NaN        NaN  3000.000000  3.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ibadan    14000.000000  4003.500000
Ikoyi      6000.000000  2003.000000
Gbagada    9333.333333  3669.333333
Ibadan    10000.000000  2005.000000
Surulere   9000.000000  3003.000000

[3014 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4492.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Ibadan    4498.5  NaN    NaN        NaN  2500.0       3.0  NaN   6500.0
Ikoyi     4496.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Lekki     4498.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Surulere  4499.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3003.0
Ibadan    2503.0
Ikoyi     4004.0
Lekki     2001.0
Surulere  4004.0

[3018 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4499.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Gbagada   4503.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ibadan    4504.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     4501.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  4503.5  NaN    NaN        NaN  3000.0       2.5  NaN   7500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4004.0
Gbagada   4001.0
Ibadan    4003.0
Lekki     4005.0
Surulere  3002.5

[3022 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4501.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  4503.5  NaN    NaN        NaN  3000.0       2.5  NaN   7500.0
Gbagada   4507.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     4509.5  NaN    NaN        NaN  2500.0       4.0  NaN   9500.0
Surulere  4507.0  NaN    NaN        NaN  3500.0       3.5  NaN  11500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4005.0
Surulere  3002.5
Gbagada   4001.0
Lekki     2504.0
Surulere  3503.5

[3025 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     4509.500000  NaN    NaN        NaN  2500.000000  4.000000  NaN
Surulere  4507.000000  NaN    NaN        NaN  3500.000000  3.500000  NaN
Gbagada   4512.666667  NaN    NaN        NaN  3333.333333  2.333333  NaN
Ikoyi     4515.000000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Lekki     4512.000000  NaN    NaN        NaN  3000.000000  3.000000  NaN

          Revenue         Snap
Gbagada    8000.0  2004.000000
Ibadan    10000.0  2005.000000
Ikoyi      5000.0  2002.500000
Lekki     20000.0  4005.000000
Gbagada    6000.0  2003.000000
...           ...          ...
Lekki      9500.0  2504.000000
Surulere  11500.0  3503.500000
Gbagada    8000.0  3335.666667
Ikoyi     12000.0  4003.000000
Lekki      9000.0  3003.000000

[3028 rows x 9 columns]
            S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.0  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan      1.0  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi       3.0  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki       3.0  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada     9.0  NaN    NaN        NaN  2000.000000       3.0  NaN
...         ...  ...    ...        ...          ...       ...  ...
Ikoyi    4515.0  NaN    NaN        NaN  4000.000000       3.0  NaN
Lekki    4512.0  NaN    NaN        NaN  3000.000000       3.0  NaN
Gbagada  4517.0  NaN    NaN        NaN  2000.000000       1.0  NaN
Ikoyi    4519.0  NaN    NaN        NaN  4000.000000       1.0  NaN
Lekki    4518.0  NaN    NaN        NaN  3666.666667       2.0  NaN

              Revenue         Snap
Gbagada   8000.000000  2004.000000
Ibadan   10000.000000  2005.000000
Ikoyi     5000.000000  2002.500000
Lekki    20000.000000  4005.000000
Gbagada   6000.000000  2003.000000
...               ...          ...
Ikoyi    12000.000000  4003.000000
Lekki     9000.000000  3003.000000
Gbagada   2000.000000  2001.000000
Ikoyi     4000.000000  4001.000000
Lekki     7666.666667  3668.666667

[3031 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...          ...  ...    ...        ...          ...       ...  ...
Ikoyi     4519.0  NaN    NaN        NaN  4000.000000  1.000000  NaN
Lekki     4518.0  NaN    NaN        NaN  3666.666667  2.000000  NaN
Gbagada   4522.0  NaN    NaN        NaN  2666.666667  3.333333  NaN
Lekki     4524.0  NaN    NaN        NaN  3000.000000  5.000000  NaN
Surulere  4525.0  NaN    NaN        NaN  2000.000000  1.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi      4000.000000  4001.000000
Lekki      7666.666667  3668.666667
Gbagada    8666.666667  2670.000000
Lekki     15000.000000  3005.000000
Surulere   2000.000000  2001.000000

[3034 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
...          ...  ...    ...        ...          ...       ...  ...
Lekki     4524.0  NaN    NaN        NaN  3000.000000  5.000000  NaN
Surulere  4525.0  NaN    NaN        NaN  2000.000000  1.000000  NaN
Ibadan    4528.0  NaN    NaN        NaN  3333.333333  3.666667  NaN
Lekki     4527.0  NaN    NaN        NaN  2000.000000  3.000000  NaN
Surulere  4529.0  NaN    NaN        NaN  4000.000000  4.000000  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Lekki     15000.000000  3005.0
Surulere   2000.000000  2001.0
Ibadan    12333.333333  3337.0
Lekki      6000.000000  2003.0
Surulere  16000.000000  4004.0

[3037 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     4527.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Surulere  4529.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN
Ibadan    4533.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Ikoyi     4532.666667  NaN    NaN        NaN  2333.333333  3.666667  NaN
Lekki     4534.000000  NaN    NaN        NaN  2000.000000  1.000000  NaN

          Revenue    Snap
Gbagada    8000.0  2004.0
Ibadan    10000.0  2005.0
Ikoyi      5000.0  2002.5
Lekki     20000.0  4005.0
Gbagada    6000.0  2003.0
...           ...     ...
Lekki      6000.0  2003.0
Surulere  16000.0  4004.0
Ibadan     6000.0  2003.0
Ikoyi      9000.0  2337.0
Lekki      2000.0  2001.0

[3040 rows x 9 columns]

                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Surulere  4529.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN
Ibadan    4533.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Ikoyi     4532.666667  NaN    NaN        NaN  2333.333333  3.666667  NaN
Lekki     4534.000000  NaN    NaN        NaN  2000.000000  1.000000  NaN
Ikoyi     4538.000000  NaN    NaN        NaN  3200.000000  4.200000  NaN

          Revenue    Snap
Gbagada    8000.0  2004.0
Ibadan    10000.0  2005.0
Ikoyi      5000.0  2002.5
Lekki     20000.0  4005.0
Gbagada    6000.0  2003.0
...           ...     ...
Surulere  16000.0  4004.0
Ibadan     6000.0  2003.0
Ikoyi      9000.0  2337.0
Lekki      2000.0  2001.0
Ikoyi     12800.0  3204.2

[3041 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4534.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ikoyi     4538.0  NaN    NaN        NaN  3200.0       4.2  NaN  12800.0
Gbagada   4541.5  NaN    NaN        NaN  3000.0       4.5  NaN  13000.0
Ibadan    4544.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  4544.0  NaN    NaN        NaN  3500.0       4.0  NaN  13500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2001.0
Ikoyi     3204.2
Gbagada   3004.5
Ibadan    4003.0
Surulere  3504.0

[3044 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    4544.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  4544.0  NaN    NaN        NaN  3500.0       4.0  NaN  13500.0
Gbagada   4548.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ikoyi     4546.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Surulere  4549.0  NaN    NaN        NaN  2500.0       3.0  NaN   6500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    4003.0
Surulere  3504.0
Gbagada   4004.0
Ikoyi     2003.0
Surulere  2503.0

[3047 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   4551.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ibadan    4555.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ikoyi     4554.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Lekki     4553.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Surulere  4552.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   4004.0
Ibadan    2001.0
Ikoyi     4005.0
Lekki     4002.0
Surulere  4004.0

[3052 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4552.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Gbagada   4559.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Ikoyi     4558.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Lekki     4557.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Surulere  4558.0  NaN    NaN        NaN  2000.0       3.5  NaN   7000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4004.0
Gbagada   2002.0
Ikoyi     3004.0
Lekki     2003.0
Surulere  2003.5

[3056 rows x 9 columns]
              S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.00  NaN    NaN        NaN  2000.0      4.00  NaN   8000.0
Ibadan       1.00  NaN    NaN        NaN  2000.0      5.00  NaN  10000.0
Ikoyi        3.00  NaN    NaN        NaN  2000.0      2.50  NaN   5000.0
Lekki        3.00  NaN    NaN        NaN  4000.0      5.00  NaN  20000.0
Gbagada      9.00  NaN    NaN        NaN  2000.0      3.00  NaN   6000.0
...           ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     4558.00  NaN    NaN        NaN  3000.0      4.00  NaN  12000.0
Lekki     4557.00  NaN    NaN        NaN  2000.0      3.00  NaN   6000.0
Surulere  4558.00  NaN    NaN        NaN  2000.0      3.50  NaN   7000.0
Gbagada   4563.25  NaN    NaN        NaN  3500.0      3.75  NaN  13500.0
Surulere  4562.00  NaN    NaN        NaN  2000.0      1.00  NaN   2000.0

             Snap
Gbagada   2004.00
Ibadan    2005.00
Ikoyi     2002.50
Lekki     4005.00
Gbagada   2003.00
...           ...
Ikoyi     3004.00
Lekki     2003.00
Surulere  2003.50
Gbagada   3503.75
Surulere  2001.00

[3058 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4562.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Gbagada   4567.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ikoyi     4568.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     4570.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Surulere  4567.5  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2001.0
Gbagada   4005.0
Ikoyi     4001.0
Lekki     3003.0
Surulere  4004.0

[3062 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     4568.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     4570.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Surulere  4567.5  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Lekki     4571.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  4573.5  NaN    NaN        NaN  3500.0       4.0  NaN  14000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     4001.0
Lekki     3003.0
Surulere  4004.0
Lekki     4005.0
Surulere  3504.0

[3064 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4573.5  NaN    NaN        NaN  3500.0       4.0  NaN  14000.0
Gbagada   4579.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ibadan    4578.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ikoyi     4578.0  NaN    NaN        NaN  2500.0       1.5  NaN   4000.0
Surulere  4577.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3504.0
Gbagada   4003.0
Ibadan    4005.0
Ikoyi     2501.5
Surulere  4003.0

[3068 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4577.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Gbagada   4584.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan    4582.0  NaN    NaN        NaN  4000.0       4.5  NaN  18000.0
Ikoyi     4582.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Surulere  4585.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4003.0
Gbagada   2004.0
Ibadan    4004.5
Ikoyi     2003.0
Surulere  2004.0

[3072 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4585.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Gbagada   4588.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ikoyi     4589.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     4586.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  4588.5  NaN    NaN        NaN  2500.0       3.0  NaN   7000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2004.0
Gbagada   3001.0
Ikoyi     4001.0
Lekki     4005.0
Surulere  2503.0

[3076 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4588.5  NaN    NaN        NaN  2500.0       3.0  NaN   7000.0
Gbagada   4593.5  NaN    NaN        NaN  2500.0       3.0  NaN   6500.0
Ibadan    4591.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ikoyi     4594.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Lekki     4593.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2503.0
Gbagada   2503.0
Ibadan    4001.0
Ikoyi     4005.0
Lekki     2001.0

[3080 rows x 9 columns]
                 S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...              ...  ...    ...        ...          ...       ...  ...
Ikoyi    4594.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Lekki    4593.000000  NaN    NaN        NaN  2000.000000  1.000000  NaN
Ibadan   4598.666667  NaN    NaN        NaN  3666.666667  3.333333  NaN
Ikoyi    4596.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Lekki    4598.000000  NaN    NaN        NaN  2000.000000  1.000000  NaN

              Revenue    Snap
Gbagada   8000.000000  2004.0
Ibadan   10000.000000  2005.0
Ikoyi     5000.000000  2002.5
Lekki    20000.000000  4005.0
Gbagada   6000.000000  2003.0
...               ...     ...
Ikoyi    20000.000000  4005.0
Lekki     2000.000000  2001.0
Ibadan   12333.333333  3670.0
Ikoyi     8000.000000  4002.0
Lekki     2000.000000  2001.0

[3083 rows x 9 columns]
                 S/N Date Branch Pizza Sold   Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.0       4.0  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.0       5.0  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.0       2.5  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.0       5.0  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.0       3.0  NaN
...              ...  ...    ...        ...     ...       ...  ...
Ikoyi    4596.000000  NaN    NaN        NaN  4000.0       2.0  NaN
Lekki    4598.000000  NaN    NaN        NaN  2000.0       1.0  NaN
Ibadan   4602.333333  NaN    NaN        NaN  3000.0       4.0  NaN
Ikoyi    4603.000000  NaN    NaN        NaN  3000.0       2.0  NaN
Lekki    4605.000000  NaN    NaN        NaN  2000.0       2.0  NaN

              Revenue    Snap
Gbagada   8000.000000  2004.0
Ibadan   10000.000000  2005.0
Ikoyi     5000.000000  2002.5
Lekki    20000.000000  4005.0
Gbagada   6000.000000  2003.0
...               ...     ...
Ikoyi     8000.000000  4002.0
Lekki     2000.000000  2001.0
Ibadan   12333.333333  3004.0
Ikoyi     6000.000000  3002.0
Lekki     4000.000000  2002.0

[3086 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     4603.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Lekki     4605.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Gbagada   4606.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi     4609.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Surulere  4608.0  NaN    NaN        NaN  3000.0       1.5  NaN   4500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3002.0
Lekki     2002.0
Gbagada   2005.0
Ikoyi     3004.0
Surulere  3001.5

[3089 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     4609.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Surulere  4608.0  NaN    NaN        NaN  3000.0       1.5  NaN   4500.0
Gbagada   4614.5  NaN    NaN        NaN  3000.0       3.0  NaN   7000.0
Ikoyi     4611.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Lekki     4612.5  NaN    NaN        NaN  2500.0       4.0  NaN  10000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3004.0
Surulere  3001.5
Gbagada   3003.0
Ikoyi     3002.0
Lekki     2504.0

[3092 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.000000       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.000000       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.000000       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.000000       3.0  NaN   6000.0
...          ...  ...    ...        ...          ...       ...  ...      ...
Ikoyi     4611.0  NaN    NaN        NaN  3000.000000       2.0  NaN   6000.0
Lekki     4612.5  NaN    NaN        NaN  2500.000000       4.0  NaN  10000.0
Ibadan    4617.0  NaN    NaN        NaN  2000.000000       5.0  NaN  10000.0
Ikoyi     4618.0  NaN    NaN        NaN  3333.333333       3.0  NaN  10000.0
Surulere  4619.0  NaN    NaN        NaN  3000.000000       1.0  NaN   3000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Ikoyi     3002.000000
Lekki     2504.000000
Ibadan    2005.000000
Ikoyi     3336.333333
Surulere  3001.000000

[3095 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000       3.0  NaN
...          ...  ...    ...        ...          ...       ...  ...
Ibadan    4617.0  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi     4618.0  NaN    NaN        NaN  3333.333333       3.0  NaN
Surulere  4619.0  NaN    NaN        NaN  3000.000000       1.0  NaN
Ibadan    4623.0  NaN    NaN        NaN  3333.333333       2.0  NaN
Lekki     4623.0  NaN    NaN        NaN  3500.000000       1.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ibadan    10000.000000  2005.000000
Ikoyi     10000.000000  3336.333333
Surulere   3000.000000  3001.000000
Ibadan     7333.333333  3335.333333
Lekki      3500.000000  3501.000000

[3097 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4623.0  NaN    NaN        NaN  3500.0       1.0  NaN   3500.0
Ibadan    4628.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ikoyi     4626.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Lekki     4628.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Surulere  4630.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3501.0
Ibadan    4001.0
Ikoyi     2004.0
Lekki     2003.0
Surulere  4004.0

[3101 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.000000       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.000000       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.000000       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.000000       3.0  NaN   6000.0
...          ...  ...    ...        ...          ...       ...  ...      ...
Lekki     4628.0  NaN    NaN        NaN  2000.000000       3.0  NaN   6000.0
Surulere  4630.0  NaN    NaN        NaN  4000.000000       4.0  NaN  16000.0
Gbagada   4631.0  NaN    NaN        NaN  4000.000000       3.0  NaN  12000.0
Ibadan    4632.0  NaN    NaN        NaN  4000.000000       1.0  NaN   4000.0
Surulere  4634.0  NaN    NaN        NaN  3333.333333       3.0  NaN  10000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Lekki     2003.000000
Surulere  4004.000000
Gbagada   4003.000000
Ibadan    4001.000000
Surulere  3336.333333

[3104 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.000000       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.000000       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.000000       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.000000       3.0  NaN   6000.0
...          ...  ...    ...        ...          ...       ...  ...      ...
Ibadan    4632.0  NaN    NaN        NaN  4000.000000       1.0  NaN   4000.0
Surulere  4634.0  NaN    NaN        NaN  3333.333333       3.0  NaN  10000.0
Gbagada   4639.0  NaN    NaN        NaN  2500.000000       3.5  NaN   8500.0
Ibadan    4638.0  NaN    NaN        NaN  3000.000000       2.5  NaN   7000.0
Lekki     4636.0  NaN    NaN        NaN  2000.000000       3.0  NaN   6000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Ibadan    4001.000000
Surulere  3336.333333
Gbagada   2503.500000
Ibadan    3002.500000
Lekki     2003.000000

[3107 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Ibadan   4638.0  NaN    NaN        NaN  3000.0       2.5  NaN   7000.0  3002.5
Lekki    4636.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
Gbagada  4641.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ibadan   4643.5  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0
Ikoyi    4643.5  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0

[3110 rows x 9 columns]
            S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue    Snap
Gbagada     5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan      1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0  2005.0
Ikoyi       3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0  2002.5
Lekki       3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0  4005.0
Gbagada     9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0  2003.0
...         ...  ...    ...        ...     ...       ...  ...      ...     ...
Gbagada  4641.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0  4003.0
Ibadan   4643.5  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0
Ikoyi    4643.5  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0  2004.0
Ibadan   4648.5  NaN    NaN        NaN  3000.0       2.5  NaN   8000.0  3002.5
Lekki    4646.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0  3005.0

[3112 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   4653.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ibadan    4651.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ikoyi     4652.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Lekki     4654.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  4655.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   4003.0
Ibadan    2001.0
Ikoyi     3002.0
Lekki     4005.0
Surulere  4002.0

[3117 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4654.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  4655.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ibadan    4658.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ikoyi     4657.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Surulere  4660.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4005.0
Surulere  4002.0
Ibadan    2003.0
Ikoyi     3001.0
Surulere  4005.0

[3120 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ibadan    4658.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Ikoyi     4657.000000  NaN    NaN        NaN  3000.000000  1.000000  NaN
Surulere  4660.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada   4662.500000  NaN    NaN        NaN  3500.000000  3.000000  NaN
Ibadan    4663.333333  NaN    NaN        NaN  2666.666667  1.666667  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ibadan     6000.000000  2003.000000
Ikoyi      3000.000000  3001.000000
Surulere  20000.000000  4005.000000
Gbagada   10000.000000  3503.000000
Ibadan     4666.666667  2668.333333

[3122 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Surulere  4660.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada   4662.500000  NaN    NaN        NaN  3500.000000  3.000000  NaN
Ibadan    4663.333333  NaN    NaN        NaN  2666.666667  1.666667  NaN
Gbagada   4666.000000  NaN    NaN        NaN  2000.000000  1.000000  NaN
Ibadan    4668.500000  NaN    NaN        NaN  2750.000000  2.750000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Surulere  20000.000000  4005.000000
Gbagada   10000.000000  3503.000000
Ibadan     4666.666667  2668.333333
Gbagada    2000.000000  2001.000000
Ibadan     7000.000000  2752.750000

[3124 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0      4.00  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0      5.00  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0      2.50  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0      5.00  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0      3.00  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    4668.5  NaN    NaN        NaN  2750.0      2.75  NaN   7000.0
Gbagada   4671.0  NaN    NaN        NaN  2000.0      1.00  NaN   2000.0
Ibadan    4673.0  NaN    NaN        NaN  3000.0      5.00  NaN  15000.0
Lekki     4673.0  NaN    NaN        NaN  4000.0      3.50  NaN  14000.0
Surulere  4675.0  NaN    NaN        NaN  4000.0      2.00  NaN   8000.0

             Snap
Gbagada   2004.00
Ibadan    2005.00
Ikoyi     2002.50
Lekki     4005.00
Gbagada   2003.00
...           ...
Ibadan    2752.75
Gbagada   2001.00
Ibadan    3005.00
Lekki     4003.50
Surulere  4002.00

[3128 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4675.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ibadan    4679.5  NaN    NaN        NaN  3500.0       4.0  NaN  13500.0
Ikoyi     4677.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Lekki     4676.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Surulere  4678.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4002.0
Ibadan    3504.0
Ikoyi     3001.0
Lekki     3001.0
Surulere  4003.0

[3132 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4678.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Gbagada   4683.0  NaN    NaN        NaN  3000.0       3.0  NaN   7000.0
Ibadan    4681.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ikoyi     4685.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Lekki     4683.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4003.0
Gbagada   3003.0
Ibadan    2001.0
Ikoyi     4005.0
Lekki     3005.0

[3136 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     4685.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Lekki     4683.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Gbagada   4689.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ikoyi     4687.0  NaN    NaN        NaN  4000.0       2.5  NaN  10000.0
Surulere  4688.5  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     4005.0
Lekki     3005.0
Gbagada   2003.0
Ikoyi     4002.5
Surulere  2003.0

[3139 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4688.5  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Gbagada   4691.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Ikoyi     4695.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     4693.5  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Surulere  4692.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2003.0
Gbagada   2002.0
Ikoyi     4003.0
Lekki     3005.0
Surulere  2003.0

[3143 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     4695.000000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Lekki     4693.500000  NaN    NaN        NaN  3000.000000  5.000000  NaN
Surulere  4692.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
Gbagada   4698.500000  NaN    NaN        NaN  3000.000000  4.000000  NaN
Lekki     4697.666667  NaN    NaN        NaN  2333.333333  2.666667  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Ikoyi     12000.000000  4003.0
Lekki     15000.000000  3005.0
Surulere   6000.000000  2003.0
Gbagada   12000.000000  3004.0
Lekki      6333.333333  2336.0

[3145 rows x 9 columns]
                 S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan      1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi       3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki       3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada     9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...              ...  ...    ...        ...          ...       ...  ...
Lekki    4697.666667  NaN    NaN        NaN  2333.333333  2.666667  NaN
Gbagada  4701.000000  NaN    NaN        NaN  3000.000000  1.000000  NaN
Ibadan   4702.000000  NaN    NaN        NaN  3000.000000  3.000000  NaN
Ikoyi    4704.000000  NaN    NaN        NaN  2500.000000  3.000000  NaN
Lekki    4704.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN

              Revenue    Snap
Gbagada   8000.000000  2004.0
Ibadan   10000.000000  2005.0
Ikoyi     5000.000000  2002.5
Lekki    20000.000000  4005.0
Gbagada   6000.000000  2003.0
...               ...     ...
Lekki     6333.333333  2336.0
Gbagada   3000.000000  3001.0
Ibadan    9000.000000  3003.0
Ikoyi     7500.000000  2503.0
Lekki     8000.000000  4002.0

[3149 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4704.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ibadan    4706.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ikoyi     4709.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     4707.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  4709.0  NaN    NaN        NaN  3500.0       4.0  NaN  14000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4002.0
Ibadan    3002.0
Ikoyi     4003.0
Lekki     4003.0
Surulere  3504.0

[3153 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4709.0  NaN    NaN        NaN  3500.0       4.0  NaN  14000.0
Ibadan    4713.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Ikoyi     4711.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Lekki     4715.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Surulere  4713.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3504.0
Ibadan    3003.0
Ikoyi     4003.0
Lekki     4001.0
Surulere  4002.0

[3157 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4713.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Gbagada   4717.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ikoyi     4717.5  NaN    NaN        NaN  3500.0       4.0  NaN  14500.0
Lekki     4720.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Surulere  4718.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4002.0
Gbagada   4004.0
Ikoyi     3504.0
Lekki     4001.0
Surulere  4002.0

[3161 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   4721.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ibadan    4722.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi     4725.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Lekki     4724.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Surulere  4723.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   4005.0
Ibadan    2005.0
Ikoyi     2005.0
Lekki     3002.0
Surulere  3003.0

[3166 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4723.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Gbagada   4726.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ibadan    4730.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ikoyi     4727.5  NaN    NaN        NaN  3000.0       3.5  NaN  10500.0
Lekki     4729.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3003.0
Gbagada   2003.0
Ibadan    3005.0
Ikoyi     3003.5
Lekki     4004.0

[3170 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4729.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ibadan    4731.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ikoyi     4732.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Lekki     4735.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Surulere  4733.5  NaN    NaN        NaN  3500.0       3.5  NaN  13000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4004.0
Ibadan    4003.0
Ikoyi     3003.0
Lekki     2002.0
Surulere  3503.5

[3174 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
...          ...  ...    ...        ...          ...       ...  ...      ...
Lekki     4735.0  NaN    NaN        NaN  2000.000000  2.000000  NaN   4000.0
Surulere  4733.5  NaN    NaN        NaN  3500.000000  3.500000  NaN  13000.0
Gbagada   4740.0  NaN    NaN        NaN  2000.000000  2.000000  NaN   4000.0
Ibadan    4739.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
Surulere  4737.0  NaN    NaN        NaN  3333.333333  2.333333  NaN   6000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Lekki     2002.000000
Surulere  3503.500000
Gbagada   2002.000000
Ibadan    2003.000000
Surulere  3335.666667

[3177 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
...          ...  ...    ...        ...          ...       ...  ...      ...
Ibadan    4739.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
Surulere  4737.0  NaN    NaN        NaN  3333.333333  2.333333  NaN   6000.0
Gbagada   4743.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
Lekki     4743.5  NaN    NaN        NaN  3500.000000  1.500000  NaN   5000.0
Surulere  4742.5  NaN    NaN        NaN  3000.000000  3.500000  NaN  11000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Ibadan    2003.000000
Surulere  3335.666667
Gbagada   2003.000000
Lekki     3501.500000
Surulere  3003.500000

[3180 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4742.5  NaN    NaN        NaN  3000.0       3.5  NaN  11000.0
Gbagada   4747.5  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ibadan    4749.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ikoyi     4750.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Lekki     4746.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3003.5
Gbagada   4004.0
Ibadan    4004.0
Ikoyi     3002.0
Lekki     2004.0

[3184 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada     5.00  NaN    NaN        NaN  2000.0      4.00  NaN   8000.0
Ibadan      1.00  NaN    NaN        NaN  2000.0      5.00  NaN  10000.0
Ikoyi       3.00  NaN    NaN        NaN  2000.0      2.50  NaN   5000.0
Lekki       3.00  NaN    NaN        NaN  4000.0      5.00  NaN  20000.0
Gbagada     9.00  NaN    NaN        NaN  2000.0      3.00  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan   4749.00  NaN    NaN        NaN  4000.0      4.00  NaN  16000.0
Ikoyi    4750.00  NaN    NaN        NaN  3000.0      2.00  NaN   6000.0
Lekki    4746.00  NaN    NaN        NaN  2000.0      4.00  NaN   8000.0
Ibadan   4752.75  NaN    NaN        NaN  3000.0      2.25  NaN   6250.0
Lekki    4754.00  NaN    NaN        NaN  4000.0      2.00  NaN   8000.0

            Snap
Gbagada  2004.00
Ibadan   2005.00
Ikoyi    2002.50
Lekki    4005.00
Gbagada  2003.00
...          ...
Ibadan   4004.00
Ikoyi    3002.00
Lekki    2004.00
Ibadan   3002.25
Lekki    4002.00

[3186 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4754.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Gbagada   4759.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ibadan    4758.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Lekki     4758.0  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0
Surulere  4757.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4002.0
Gbagada   3005.0
Ibadan    4004.0
Lekki     4003.5
Surulere  4001.0

[3190 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4758.0  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0
Surulere  4757.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Gbagada   4765.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ikoyi     4763.5  NaN    NaN        NaN  2500.0       3.5  NaN   9500.0
Surulere  4761.5  NaN    NaN        NaN  2500.0       3.5  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4003.5
Surulere  4001.0
Gbagada   4002.0
Ikoyi     2503.5
Surulere  2503.5

[3193 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     4763.5  NaN    NaN        NaN  2500.0       3.5  NaN   9500.0
Surulere  4761.5  NaN    NaN        NaN  2500.0       3.5  NaN   8000.0
Gbagada   4767.0  NaN    NaN        NaN  2500.0       2.0  NaN   5000.0
Lekki     4769.5  NaN    NaN        NaN  3500.0       4.5  NaN  16000.0
Surulere  4767.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     2503.5
Surulere  2503.5
Gbagada   2502.0
Lekki     3504.5
Surulere  3001.0

[3196 rows x 9 columns]

                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     4769.500000  NaN    NaN        NaN  3500.000000       4.5  NaN
Surulere  4767.000000  NaN    NaN        NaN  3000.000000       1.0  NaN
Gbagada   4772.666667  NaN    NaN        NaN  3333.333333       3.0  NaN
Ikoyi     4774.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Surulere  4773.000000  NaN    NaN        NaN  4000.000000       1.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki     16000.000000  3504.500000
Surulere   3000.000000  3001.000000
Gbagada   10666.666667  3336.333333
Ikoyi     20000.000000  4005.000000
Surulere   4000.000000  4001.000000

[3199 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4773.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Gbagada   4777.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ibadan    4777.0  NaN    NaN        NaN  3000.0       3.5  NaN  11000.0
Lekki     4779.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Surulere  4780.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4001.0
Gbagada   2005.0
Ibadan    3003.5
Lekki     2002.0
Surulere  4005.0

[3203 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.000000       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.000000       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.000000       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.000000       3.0  NaN   6000.0
...          ...  ...    ...        ...          ...       ...  ...      ...
Lekki     4779.0  NaN    NaN        NaN  2000.000000       2.0  NaN   4000.0
Surulere  4780.0  NaN    NaN        NaN  4000.000000       5.0  NaN  20000.0
Gbagada   4782.0  NaN    NaN        NaN  3000.000000       3.0  NaN   9000.0
Ikoyi     4784.0  NaN    NaN        NaN  3333.333333       3.0  NaN  10000.0
Lekki     4781.0  NaN    NaN        NaN  4000.000000       1.0  NaN   4000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Lekki     2002.000000
Surulere  4005.000000
Gbagada   3003.000000
Ikoyi     3336.333333
Lekki     4001.000000

[3206 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   4788.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan    4787.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ikoyi     4790.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Lekki     4789.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  4786.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   2004.0
Ibadan    4004.0
Ikoyi     4004.0
Lekki     4003.0
Surulere  2002.0

[3211 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4786.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Gbagada   4794.0  NaN    NaN        NaN  3000.0       3.5  NaN   9000.0
Ibadan    4792.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Lekki     4794.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Surulere  4791.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2002.0
Gbagada   3003.5
Ibadan    2001.0
Lekki     3004.0
Surulere  4005.0

[3215 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.0  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.0  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.0  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.0  NaN    NaN        NaN  2000.000000       3.0  NaN
...          ...  ...    ...        ...          ...       ...  ...
Ibadan    4792.0  NaN    NaN        NaN  2000.000000       1.0  NaN
Lekki     4794.0  NaN    NaN        NaN  3000.000000       4.0  NaN
Surulere  4791.0  NaN    NaN        NaN  4000.000000       5.0  NaN
Ibadan    4798.0  NaN    NaN        NaN  3000.000000       2.5  NaN
Ikoyi     4798.0  NaN    NaN        NaN  3333.333333       2.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ibadan     2000.000000  2001.000000
Lekki     12000.000000  3004.000000
Surulere  20000.000000  4005.000000
Ibadan     8000.000000  3002.500000
Ikoyi      6333.333333  3335.333333

[3217 rows x 9 columns]
            S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada     5.0  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan      1.0  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi       3.0  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki       3.0  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada     9.0  NaN    NaN        NaN  2000.000000       3.0  NaN
...         ...  ...    ...        ...          ...       ...  ...
Ibadan   4798.0  NaN    NaN        NaN  3000.000000       2.5  NaN
Ikoyi    4798.0  NaN    NaN        NaN  3333.333333       2.0  NaN
Ibadan   4801.0  NaN    NaN        NaN  3000.000000       1.0  NaN
Ikoyi    4804.5  NaN    NaN        NaN  4000.000000       3.5  NaN
Lekki    4802.5  NaN    NaN        NaN  3500.000000       3.5  NaN

              Revenue         Snap
Gbagada   8000.000000  2004.000000
Ibadan   10000.000000  2005.000000
Ikoyi     5000.000000  2002.500000
Lekki    20000.000000  4005.000000
Gbagada   6000.000000  2003.000000
...               ...          ...
Ibadan    8000.000000  3002.500000
Ikoyi     6333.333333  3335.333333
Ibadan    3000.000000  3001.000000
Ikoyi    14000.000000  4003.500000
Lekki    13000.000000  3503.500000

[3220 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time       Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.000000
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.000000
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.000000
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.000000
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.000000
...          ...  ...    ...        ...     ...       ...  ...           ...
Ikoyi     4804.5  NaN    NaN        NaN  4000.0       3.5  NaN  14000.000000
Lekki     4802.5  NaN    NaN        NaN  3500.0       3.5  NaN  13000.000000
Ibadan    4808.0  NaN    NaN        NaN  3000.0       3.0  NaN   9666.666667
Lekki     4809.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.000000
Surulere  4807.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.000000

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     4003.5
Lekki     3503.5
Ibadan    3003.0
Lekki     4003.0
Surulere  3004.0

[3223 rows x 9 columns]

             S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
...          ...  ...    ...        ...          ...       ...  ...      ...
Lekki     4809.0  NaN    NaN        NaN  4000.000000  3.000000  NaN  12000.0
Surulere  4807.0  NaN    NaN        NaN  3000.000000  4.000000  NaN  12000.0
Gbagada   4814.0  NaN    NaN        NaN  3000.000000  1.000000  NaN   3000.0
Ikoyi     4815.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Lekki     4812.0  NaN    NaN        NaN  3666.666667  2.666667  NaN  10000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Lekki     4003.000000
Surulere  3004.000000
Gbagada   3001.000000
Ikoyi     4005.000000
Lekki     3669.333333

[3226 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
...          ...  ...    ...        ...          ...       ...  ...      ...
Lekki     4812.0  NaN    NaN        NaN  3666.666667  2.666667  NaN  10000.0
Gbagada   4817.0  NaN    NaN        NaN  3000.000000  3.500000  NaN  11000.0
Ibadan    4817.0  NaN    NaN        NaN  3000.000000  2.000000  NaN   6000.0
Lekki     4819.0  NaN    NaN        NaN  4000.000000  2.000000  NaN   8000.0
Surulere  4820.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0

                 Snap
Gbagada   2004.000000
Ibadan    2005.000000
Ikoyi     2002.500000
Lekki     4005.000000
Gbagada   2003.000000
...               ...
Lekki     3669.333333
Gbagada   3003.500000
Ibadan    3002.000000
Lekki     4002.000000
Surulere  2005.000000

[3230 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4820.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ibadan    4823.0  NaN    NaN        NaN  4000.0       3.5  NaN  14000.0
Ikoyi     4823.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Lekki     4822.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Surulere  4824.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2005.0
Ibadan    4003.5
Ikoyi     2004.0
Lekki     4004.0
Surulere  2002.0

[3234 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4824.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Gbagada   4826.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ibadan    4827.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Lekki     4830.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Surulere  4828.5  NaN    NaN        NaN  3000.0       2.0  NaN   5000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2002.0
Gbagada   4004.0
Ibadan    2003.0
Lekki     2002.0
Surulere  3002.0

[3238 rows x 9 columns]
             S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.000000  2.500000  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
...          ...  ...    ...        ...          ...       ...  ...      ...
Lekki     4830.0  NaN    NaN        NaN  2000.000000  2.000000  NaN   4000.0
Surulere  4828.5  NaN    NaN        NaN  3000.000000  2.000000  NaN   5000.0
Gbagada   4833.0  NaN    NaN        NaN  3666.666667  3.333333  NaN  12000.0
Ibadan    4835.0  NaN    NaN        NaN  2000.000000  2.000000  NaN   4000.0
Surulere  4831.0  NaN    NaN        NaN  4000.000000  1.000000  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2002.0
Surulere  3002.0
Gbagada   3670.0
Ibadan    2002.0
Surulere  4001.0

[3241 rows x 9 columns]
              S/N Date Branch Pizza Sold        Price  Quantity Time  Revenue  \
Gbagada      5.00  NaN    NaN        NaN  2000.000000  4.000000  NaN   8000.0
Ibadan       1.00  NaN    NaN        NaN  2000.000000  5.000000  NaN  10000.0
Ikoyi        3.00  NaN    NaN        NaN  2000.000000  2.500000  NaN   5000.0
Lekki        3.00  NaN    NaN        NaN  4000.000000  5.000000  NaN  20000.0
Gbagada      9.00  NaN    NaN        NaN  2000.000000  3.000000  NaN   6000.0
...           ...  ...    ...        ...          ...       ...  ...      ...
Gbagada   4833.00  NaN    NaN        NaN  3666.666667  3.333333  NaN  12000.0
Ibadan    4835.00  NaN    NaN        NaN  2000.000000  2.000000  NaN   4000.0
Surulere  4831.00  NaN    NaN        NaN  4000.000000  1.000000  NaN   4000.0
Ibadan    4837.75  NaN    NaN        NaN  2250.000000  4.000000  NaN   9250.0
Surulere  4839.00  NaN    NaN        NaN  4000.000000  1.000000  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   3670.0
Ibadan    2002.0
Surulere  4001.0
Ibadan    2254.0
Surulere  4001.0

[3243 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ibadan    4837.750000  NaN    NaN        NaN  2250.000000       4.0  NaN
Surulere  4839.000000  NaN    NaN        NaN  4000.000000       1.0  NaN
Ikoyi     4844.000000  NaN    NaN        NaN  3000.000000       4.0  NaN
Lekki     4842.666667  NaN    NaN        NaN  2666.666667       4.0  NaN
Surulere  4843.000000  NaN    NaN        NaN  3000.000000       5.0  NaN

          Revenue         Snap
Gbagada    8000.0  2004.000000
Ibadan    10000.0  2005.000000
Ikoyi      5000.0  2002.500000
Lekki     20000.0  4005.000000
Gbagada    6000.0  2003.000000
...           ...          ...
Ibadan     9250.0  2254.000000
Surulere   4000.0  4001.000000
Ikoyi     12000.0  3004.000000
Lekki     11000.0  2670.666667
Surulere  15000.0  3005.000000

[3246 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     4842.666667  NaN    NaN        NaN  2666.666667  4.000000  NaN
Surulere  4843.000000  NaN    NaN        NaN  3000.000000  5.000000  NaN
Gbagada   4849.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Ibadan    4848.000000  NaN    NaN        NaN  3000.000000  3.666667  NaN
Lekki     4847.000000  NaN    NaN        NaN  3000.000000  4.000000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki     11000.000000  2670.666667
Surulere  15000.000000  3005.000000
Gbagada   20000.000000  4005.000000
Ibadan    11333.333333  3003.666667
Lekki     12000.000000  3004.000000

[3249 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4847.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Gbagada   4854.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ibadan    4851.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ikoyi     4854.0  NaN    NaN        NaN  2500.0       3.0  NaN   8000.0
Surulere  4852.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3004.0
Gbagada   3004.0
Ibadan    3004.0
Ikoyi     2503.0
Surulere  2004.0

[3253 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     4854.0  NaN    NaN        NaN  2500.0       3.0  NaN   8000.0
Surulere  4852.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Gbagada   4856.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ikoyi     4858.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Surulere  4859.0  NaN    NaN        NaN  3500.0       2.5  NaN   9500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     2503.0
Surulere  2004.0
Gbagada   3004.0
Ikoyi     3004.0
Surulere  3502.5

[3256 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     4858.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Surulere  4859.0  NaN    NaN        NaN  3500.0       2.5  NaN   9500.0
Gbagada   4863.0  NaN    NaN        NaN  3000.0       1.5  NaN   5000.0
Ikoyi     4862.5  NaN    NaN        NaN  2500.0       2.0  NaN   5500.0
Surulere  4864.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3004.0
Surulere  3502.5
Gbagada   3001.5
Ikoyi     2502.0
Surulere  2002.0

[3259 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Gbagada   4867.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ibadan    4869.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ikoyi     4868.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Lekki     4870.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Surulere  4866.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Gbagada   4003.0
Ibadan    4004.0
Ikoyi     3004.0
Lekki     4005.0
Surulere  3001.0

[3264 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4866.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Gbagada   4875.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0
Ibadan    4871.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ikoyi     4873.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  4873.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3001.0
Gbagada   2002.0
Ibadan    4004.0
Ikoyi     4003.0
Surulere  4003.0

[3268 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     4873.000000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Surulere  4873.000000  NaN    NaN        NaN  4000.000000  3.000000  NaN
Gbagada   4877.000000  NaN    NaN        NaN  4000.000000  1.000000  NaN
Lekki     4878.000000  NaN    NaN        NaN  2000.000000  2.000000  NaN
Surulere  4878.333333  NaN    NaN        NaN  3666.666667  2.666667  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi     12000.000000  4003.000000
Surulere  12000.000000  4003.000000
Gbagada    4000.000000  4001.000000
Lekki      4000.000000  2002.000000
Surulere   9333.333333  3669.333333

[3271 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     4878.000000  NaN    NaN        NaN  2000.000000  2.000000  NaN
Surulere  4878.333333  NaN    NaN        NaN  3666.666667  2.666667  NaN
Ikoyi     4881.500000  NaN    NaN        NaN  3500.000000  3.500000  NaN
Lekki     4885.000000  NaN    NaN        NaN  3000.000000  4.000000  NaN
Surulere  4883.500000  NaN    NaN        NaN  3500.000000  4.500000  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Lekki      4000.000000  2002.000000
Surulere   9333.333333  3669.333333
Ikoyi     12000.000000  3503.500000
Lekki     12000.000000  3004.000000
Surulere  15500.000000  3504.500000

[3274 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4885.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Surulere  4883.5  NaN    NaN        NaN  3500.0       4.5  NaN  15500.0
Ibadan    4889.0  NaN    NaN        NaN  3500.0       2.5  NaN   9000.0
Ikoyi     4888.0  NaN    NaN        NaN  2500.0       1.5  NaN   3500.0
Lekki     4886.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3004.0
Surulere  3504.5
Ibadan    3502.5
Ikoyi     2501.5
Lekki     3001.0

[3277 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4886.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Gbagada   4891.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Ibadan    4894.0  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Ikoyi     4893.5  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Surulere  4893.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3001.0
Gbagada   3005.0
Ibadan    2001.0
Ikoyi     3002.0
Surulere  3004.0

[3281 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     4893.500000  NaN    NaN        NaN  3000.000000       2.0  NaN
Surulere  4893.000000  NaN    NaN        NaN  3000.000000       4.0  NaN
Ibadan    4897.666667  NaN    NaN        NaN  3666.666667       3.0  NaN
Ikoyi     4897.000000  NaN    NaN        NaN  4000.000000       2.0  NaN
Lekki     4900.000000  NaN    NaN        NaN  3000.000000       1.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi      6000.000000  3002.000000
Surulere  12000.000000  3004.000000
Ibadan    11666.666667  3669.666667
Ikoyi      8000.000000  4002.000000
Lekki      3000.000000  3001.000000

[3284 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4900.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ibadan    4903.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
Ikoyi     4901.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Lekki     4904.5  NaN    NaN        NaN  2500.0       4.5  NaN  11500.0
Surulere  4902.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3001.0
Ibadan    2003.0
Ikoyi     4005.0
Lekki     2504.5
Surulere  4005.0

[3288 rows x 9 columns]

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4904.5  NaN    NaN        NaN  2500.0       4.5  NaN  11500.0
Surulere  4902.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada   4907.0  NaN    NaN        NaN  3000.0       2.5  NaN   7000.0
Ibadan    4907.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Ikoyi     4909.5  NaN    NaN        NaN  3000.0       3.0  NaN   7000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2504.5
Surulere  4005.0
Gbagada   3002.5
Ibadan    4005.0
Ikoyi     3003.0

[3291 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ikoyi     4909.5  NaN    NaN        NaN  3000.0       3.0  NaN   7000.0
Gbagada   4915.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ikoyi     4913.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0
Lekki     4911.5  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  4914.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ikoyi     3003.0
Gbagada   2004.0
Ikoyi     3005.0
Lekki     4003.0
Surulere  4003.0

[3295 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4914.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Gbagada   4918.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ibadan    4919.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ikoyi     4917.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  4918.0  NaN    NaN        NaN  2500.0       3.0  NaN   6500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4003.0
Gbagada   4001.0
Ibadan    3002.0
Ikoyi     4003.0
Surulere  2503.0

[3299 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    4919.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Ikoyi     4917.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Surulere  4918.0  NaN    NaN        NaN  2500.0       3.0  NaN   6500.0
Gbagada   4921.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ibadan    4923.5  NaN    NaN        NaN  3000.0       4.0  NaN  12500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    3002.0
Ikoyi     4003.0
Surulere  2503.0
Gbagada   4003.0
Ibadan    3004.0

[3301 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Ibadan    4923.5  NaN    NaN        NaN  3000.0       4.0  NaN  12500.0
Gbagada   4930.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan    4929.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Ikoyi     4927.5  NaN    NaN        NaN  3000.0       3.5  NaN  10500.0
Surulere  4926.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Ibadan    3004.0
Gbagada   2004.0
Ibadan    4004.0
Ikoyi     3003.5
Surulere  4004.0

[3305 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ibadan    4929.000000  NaN    NaN        NaN  4000.000000       4.0  NaN
Ikoyi     4927.500000  NaN    NaN        NaN  3000.000000       3.5  NaN
Surulere  4926.000000  NaN    NaN        NaN  4000.000000       4.0  NaN
Gbagada   4932.000000  NaN    NaN        NaN  3000.000000       2.0  NaN
Ibadan    4933.666667  NaN    NaN        NaN  3666.666667       4.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ibadan    16000.000000  4004.000000
Ikoyi     10500.000000  3003.500000
Surulere  16000.000000  4004.000000
Gbagada    7000.000000  3002.000000
Ibadan    14333.333333  3670.666667

[3307 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ibadan    4933.666667  NaN    NaN        NaN  3666.666667       4.0  NaN
Gbagada   4937.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan    4939.500000  NaN    NaN        NaN  2500.000000       4.0  NaN
Lekki     4936.000000  NaN    NaN        NaN  3000.000000       1.0  NaN
Surulere  4938.000000  NaN    NaN        NaN  4000.000000       4.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ibadan    14333.333333  3670.666667
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2504.000000
Lekki      3000.000000  3001.000000
Surulere  16000.000000  4004.000000

[3311 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Lekki     4936.000000  NaN    NaN        NaN  3000.000000  1.000000  NaN
Surulere  4938.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN
Gbagada   4944.000000  NaN    NaN        NaN  4000.000000  4.000000  NaN
Ikoyi     4941.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Surulere  4943.333333  NaN    NaN        NaN  3333.333333  1.666667  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Lekki      3000.000000  3001.0
Surulere  16000.000000  4004.0
Gbagada   16000.000000  4004.0
Ikoyi      8000.000000  4002.0
Surulere   5333.333333  3335.0

[3314 rows x 9 columns]

                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000  4.000000  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000  5.000000  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000  2.500000  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000  5.000000  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000  3.000000  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     4941.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN
Surulere  4943.333333  NaN    NaN        NaN  3333.333333  1.666667  NaN
Gbagada   4947.000000  NaN    NaN        NaN  3000.000000  2.000000  NaN
Ikoyi     4948.500000  NaN    NaN        NaN  2500.000000  3.000000  NaN
Surulere  4949.000000  NaN    NaN        NaN  4000.000000  2.000000  NaN

               Revenue    Snap
Gbagada    8000.000000  2004.0
Ibadan    10000.000000  2005.0
Ikoyi      5000.000000  2002.5
Lekki     20000.000000  4005.0
Gbagada    6000.000000  2003.0
...                ...     ...
Ikoyi      8000.000000  4002.0
Surulere   5333.333333  3335.0
Gbagada    6000.000000  3002.0
Ikoyi      8000.000000  2503.0
Surulere   8000.000000  4002.0

[3317 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4949.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ibadan    4955.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ikoyi     4953.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Lekki     4952.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Surulere  4952.5  NaN    NaN        NaN  3500.0       4.0  NaN  14000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  4002.0
Ibadan    3001.0
Ikoyi     4002.0
Lekki     2005.0
Surulere  3504.0

[3321 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4952.5  NaN    NaN        NaN  3500.0       4.0  NaN  14000.0
Gbagada   4956.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ibadan    4959.5  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Ikoyi     4957.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Surulere  4958.0  NaN    NaN        NaN  2000.0       2.0  NaN   4000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3504.0
Gbagada   2005.0
Ibadan    4001.0
Ikoyi     3003.0
Surulere  2002.0

[3325 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     4957.000000  NaN    NaN        NaN  3000.000000       3.0  NaN
Surulere  4958.000000  NaN    NaN        NaN  2000.000000       2.0  NaN
Ibadan    4961.000000  NaN    NaN        NaN  2000.000000       1.0  NaN
Ikoyi     4963.000000  NaN    NaN        NaN  4000.000000       4.0  NaN
Surulere  4963.666667  NaN    NaN        NaN  2666.666667       3.0  NaN

          Revenue         Snap
Gbagada    8000.0  2004.000000
Ibadan    10000.0  2005.000000
Ikoyi      5000.0  2002.500000
Lekki     20000.0  4005.000000
Gbagada    6000.0  2003.000000
...           ...          ...
Ikoyi      9000.0  3003.000000
Surulere   4000.0  2002.000000
Ibadan     2000.0  2001.000000
Ikoyi     16000.0  4004.000000
Surulere   8000.0  2669.666667

[3328 rows x 9 columns]
                  S/N Date Branch Pizza Sold        Price  Quantity Time  \
Gbagada      5.000000  NaN    NaN        NaN  2000.000000       4.0  NaN
Ibadan       1.000000  NaN    NaN        NaN  2000.000000       5.0  NaN
Ikoyi        3.000000  NaN    NaN        NaN  2000.000000       2.5  NaN
Lekki        3.000000  NaN    NaN        NaN  4000.000000       5.0  NaN
Gbagada      9.000000  NaN    NaN        NaN  2000.000000       3.0  NaN
...               ...  ...    ...        ...          ...       ...  ...
Ikoyi     4963.000000  NaN    NaN        NaN  4000.000000       4.0  NaN
Surulere  4963.666667  NaN    NaN        NaN  2666.666667       3.0  NaN
Gbagada   4968.333333  NaN    NaN        NaN  2333.333333       3.0  NaN
Lekki     4967.000000  NaN    NaN        NaN  3000.000000       2.0  NaN
Surulere  4968.000000  NaN    NaN        NaN  4000.000000       5.0  NaN

               Revenue         Snap
Gbagada    8000.000000  2004.000000
Ibadan    10000.000000  2005.000000
Ikoyi      5000.000000  2002.500000
Lekki     20000.000000  4005.000000
Gbagada    6000.000000  2003.000000
...                ...          ...
Ikoyi     16000.000000  4004.000000
Surulere   8000.000000  2669.666667
Gbagada    6666.666667  2336.333333
Lekki      6000.000000  3002.000000
Surulere  20000.000000  4005.000000

[3331 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4967.0  NaN    NaN        NaN  3000.0       2.0  NaN   6000.0
Surulere  4968.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada   4972.5  NaN    NaN        NaN  3000.0       3.0  NaN  11000.0
Ikoyi     4975.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Surulere  4972.5  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3002.0
Surulere  4005.0
Gbagada   3003.0
Ikoyi     3004.0
Surulere  2002.5

[3334 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4972.5  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Gbagada   4978.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Ibadan    4977.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi     4980.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Lekki     4977.5  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  2002.5
Gbagada   3004.0
Ibadan    2005.0
Ikoyi     4002.0
Lekki     2001.0

[3338 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4977.5  NaN    NaN        NaN  2000.0       1.0  NaN   2000.0
Gbagada   4982.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ikoyi     4983.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Lekki     4985.0  NaN    NaN        NaN  3000.0       3.0  NaN   9000.0
Surulere  4982.5  NaN    NaN        NaN  3500.0       3.5  NaN  12500.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     2001.0
Gbagada   4002.0
Ikoyi     4001.0
Lekki     3003.0
Surulere  3503.5

[3342 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Surulere  4982.5  NaN    NaN        NaN  3500.0       3.5  NaN  12500.0
Gbagada   4989.0  NaN    NaN        NaN  4000.0       3.0  NaN  12000.0
Ibadan    4990.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Lekki     4986.5  NaN    NaN        NaN  3500.0       3.0  NaN  11000.0
Surulere  4988.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Surulere  3503.5
Gbagada   4003.0
Ibadan    4005.0
Lekki     3503.0
Surulere  3004.0

[3346 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4986.5  NaN    NaN        NaN  3500.0       3.0  NaN  11000.0
Surulere  4988.0  NaN    NaN        NaN  3000.0       4.0  NaN  12000.0
Gbagada   4991.0  NaN    NaN        NaN  4000.0       2.0  NaN   8000.0
Ikoyi     4993.0  NaN    NaN        NaN  3500.0       2.0  NaN   6500.0
Lekki     4994.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     3503.0
Surulere  3004.0
Gbagada   4002.0
Ikoyi     3502.0
Lekki     4004.0

[3349 rows x 9 columns]
             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4994.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Gbagada   4999.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ikoyi     4999.0  NaN    NaN        NaN  3000.0       4.5  NaN  13500.0
Lekki     4996.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Surulere  4997.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4004.0
Gbagada   3001.0
Ikoyi     3004.5
Lekki     4001.0
Surulere  3005.0

[3353 rows x 9 columns]

In [253]:
print(real_boss)

             S/N Date Branch Pizza Sold   Price  Quantity Time  Revenue  \
Gbagada      5.0  NaN    NaN        NaN  2000.0       4.0  NaN   8000.0
Ibadan       1.0  NaN    NaN        NaN  2000.0       5.0  NaN  10000.0
Ikoyi        3.0  NaN    NaN        NaN  2000.0       2.5  NaN   5000.0
Lekki        3.0  NaN    NaN        NaN  4000.0       5.0  NaN  20000.0
Gbagada      9.0  NaN    NaN        NaN  2000.0       3.0  NaN   6000.0
...          ...  ...    ...        ...     ...       ...  ...      ...
Lekki     4994.0  NaN    NaN        NaN  4000.0       4.0  NaN  16000.0
Gbagada   4999.0  NaN    NaN        NaN  3000.0       1.0  NaN   3000.0
Ikoyi     4999.0  NaN    NaN        NaN  3000.0       4.5  NaN  13500.0
Lekki     4996.0  NaN    NaN        NaN  4000.0       1.0  NaN   4000.0
Surulere  4997.0  NaN    NaN        NaN  3000.0       5.0  NaN  15000.0

            Snap
Gbagada   2004.0
Ibadan    2005.0
Ikoyi     2002.5
Lekki     4005.0
Gbagada   2003.0
...          ...
Lekki     4004.0
Gbagada   3001.0
Ikoyi     3004.5
Lekki     4001.0
Surulere  3005.0

[3353 rows x 9 columns]

In [257]:
new_boss.head(5)

        S/N Date Branch Pizza Sold Price Quantity Time Revenue  Snap
Gbagada   5  NaN    NaN        NaN  2000        4  NaN    8000  2004
Ibadan    1  NaN    NaN        NaN  2000        5  NaN   10000  2005
Ikoyi     6  NaN    NaN        NaN  4000        5  NaN   10000  4005
Lekki     3  NaN    NaN        NaN  4000        5  NaN   20000  4005
Gbagada   9  NaN    NaN        NaN  2000        3  NaN    6000  2003

In [258]:
print(Bee)

     CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]